#!/usr/bin/env dothttp

@name("Get regions")
GET "{{protocol}}://{{netbox}}/api/dcim/regions/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"


@name("Get region by ID")
GET "{{protocol}}://{{netbox}}/api/dcim/regions/1/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"


@name("Create Americas region")
POST "{{protocol}}://{{netbox}}/api/dcim/regions/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"
data('{
    "name": "Region - Americas",
    "slug": "Americas",
    "description": "US, Canada, Mexico, and South America"
}')


@name("Create EMEAR region")
POST "{{protocol}}://{{netbox}}/api/dcim/regions/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"
data('{
    "name": "Region - EMEAR",
    "slug": "EMEAR",
    "description": "Europe, Middle East, and Africa"
}')


@name("Create APJ region")
POST "{{protocol}}://{{netbox}}/api/dcim/regions/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"
data('{
    "name": "Region - APJ",
    "slug": "APJ",
    "description": "Asia Pacific and Japan"
}')


@name("Get sites")
GET "{{protocol}}://{{netbox}}/api/dcim/sites/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"


@name("Create US HQ site")
POST "{{protocol}}://{{netbox}}/api/dcim/sites/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"
data('{
    "name": "Headquarters",
    "slug": "HQ",
    "status": "active",
    "region": 1,
    "time_zone": "US/Eastern",
    "description": "Suits and bean counters",
    "physical_address": "123 Main Street",
    "latitude": "39.9526",
    "longitude": "75.1652",
    "contact_name": "John Smith",
    "contact_email": "john@fakeco.dev"
}')


@name("Create US branch site")
POST "{{protocol}}://{{netbox}}/api/dcim/sites/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"
data('{
    "name": "US Branch",
    "slug": "US_Branch",
    "status": "active",
    "region": 1,
    "time_zone": "US/Eastern",
    "description": "Retail store",
    "physical_address": "456 Country Road",
    "latitude": "40.4406",
    "longitude": "79.9959",
    "contact_name": "Jane Doe",
    "contact_email": "jane@fakeco.dev"
}')


@name("Create EMEAR DC")
POST "{{protocol}}://{{netbox}}/api/dcim/sites/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"
data('{
    "name": "EMEAR Data Center",
    "slug": "EMEAR_DC",
    "status": "planned",
    "region": 2,
    "time_zone": "Europe/Amsterdam",
    "description": "New on-premises data center",
    "physical_address": "789 France Way",
    "facility": "Some colo that was cheap",
    "latitude": "48.8566",
    "longitude": "2.3522",
    "contact_name": "Pierre Maginot",
    "contact_email": "pierre@fakeco.dev"
}')


@name("Create APJ branch site")
POST "{{protocol}}://{{netbox}}/api/dcim/sites/"
"Accept": "application/json"
"Content-Type": "application/json"
"Authorization": "Token {{api_token}}"
data('{
    "name": "APJ Branch",
    "slug": "APJ_Branch",
    "status": "active",
    "region": 3,
    "time_zone": "Asia/Shanghai",
    "description": "Retail store",
    "physical_address": "531 Forbidden City Blvd",
    "latitude": "39.935539",
    "longitude": "116.405640",
    "contact_name": "Jian Chin",
    "contact_email": "jian@fakeco.dev"
}')



