#!/usr/bin/env dothttp

// By default, this call gets information about your local node and its
// connections. The `scope` parameter enabled this query to be extended
// to get further information about nodes that are visible to your node.

@name("Get Node")
GET "https://{{baseUrl}}/node"
"MCWSSAML": "<>"
? "scope"= "<>"


// Information about a specific node may be retrieved by its address.
// This is useful when navigating the network.

@name("Get Node Address")
GET "https://{{baseUrl}}/node/:address"
"MCWSSAML": "<>"



