#!/usr/bin/env dothttp

// Get the list of brands

@name("GET /brands")
GET "https://{{baseUrl}}/brands"
? "cursor"= "MTU4OTQ5NTI1ODY4NywxLTVlYmRjNWRhLTEwODZlYWFjMWRmMjEwMTNjM2I0ZjVhMA=="


// Create a new brand

@name("POST /brands")
POST "https://{{baseUrl}}/brands"
"Content-Type": "application/json"
json({
    "name": "Example Brand Name",
    "settings": {
        "colors": {
            "primary": "#9D3789",
            "secondary": "#9D3789",
            "tertiary": "#9D3789"
        },
        "email": {
            "footer": {
                "markdown": "**Bold** and _italic_ with a [link](https://www.courier.com)",
                "social": {
                    "facebook": {
                        "url": "https://www.facebook.com/example"
                    },
                    "instagram": {
                        "url": "https://www.instagram.com/example"
                    },
                    "linkedin": {
                        "url": "https://www.linkedin.com/example"
                    },
                    "medium": {
                        "url": "https://www.medium.com/example"
                    },
                    "twitter": {
                        "url": "https://www.twitter.com/example"
                    }
                }
            },
            "header": {
                "barColor": "#9D3789",
                "logo": {
                    "href": "https://www.courier.com",
                    "image": "https://www.courier.com/logo.png"
                }
            }
        }
    },
    "id": "C8CPX6HQZ5M7Q5KAMW5CXC4N98DH",
    "snippets": {
        "items": [
            {
                "format": "handlebars",
                "name": "ut commodo",
                "value": "nostrud"
            },
            {
                "format": "handlebars",
                "name": "sit nulla exercitation irure",
                "value": "cillum adipisicing aute irure"
            }
        ]
    }
})


// Fetch a specific brand by brand ID.

@name("GET /brands/{brand_id}")
GET "https://{{baseUrl}}/brands/:brand_id"


// Replace an existing brand with the supplied values.

@name("PUT /brands/{brand_id}")
PUT "https://{{baseUrl}}/brands/:brand_id"
"Content-Type": "application/json"
json({
    "name": "Example Brand Name",
    "settings": {
        "colors": {
            "primary": "#9D3789",
            "secondary": "#9D3789",
            "tertiary": "#9D3789"
        },
        "email": {
            "footer": {
                "markdown": "**Bold** and _italic_ with a [link](https://www.courier.com)",
                "social": {
                    "facebook": {
                        "url": "https://www.facebook.com/example"
                    },
                    "instagram": {
                        "url": "https://www.instagram.com/example"
                    },
                    "linkedin": {
                        "url": "https://www.linkedin.com/example"
                    },
                    "medium": {
                        "url": "https://www.medium.com/example"
                    },
                    "twitter": {
                        "url": "https://www.twitter.com/example"
                    }
                }
            },
            "header": {
                "barColor": "#9D3789",
                "logo": {
                    "href": "https://www.courier.com",
                    "image": "https://www.courier.com/logo.png"
                }
            }
        }
    },
    "snippets": {
        "items": [
            {
                "format": "handlebars",
                "name": "ut sunt",
                "value": "Ut laborum sit"
            },
            {
                "format": "handlebars",
                "name": "ut laborum in Excepteur",
                "value": "culpa exercitation"
            }
        ]
    }
})


// Delete a brand by brand ID.

@name("DELETE /brands/{brand_id}")
DELETE "https://{{baseUrl}}/brands/:brand_id"



