#!/usr/bin/env dothttp

// Return the subnet pool and mask configured for MGs in the network.
@name("getNetworkCellularGatewaySettingsSubnetPool")
GET "https://{{baseUrl}}/networks/:networkId/cellularGateway/settings/subnetPool"
"Accept": "*/*"



// Update the subnet pool and mask configuration for MGs in the network.//  #### Body Parameters // **Parameter**|**Type**|**Description** //  :-------------: |:-------------: |:-------------: // mask| integer| Mask used for the subnet of all MGs in  this network.// cidr| string| CIDR of the pool of subnets. Each MG in this network will automatically pick a subnet from this pool.
@name("updateNetworkCellularGatewaySettingsSubnetPool")
PUT "https://{{baseUrl}}/networks/:networkId/cellularGateway/settings/subnetPool"
"Accept": "*/*"
"Content-Type": "application/json"
data('{
  "cidr": "192.168.0.0/16",
  "mask": "24"
}')



