#!/usr/bin/env dothttp

// Delete projects  snippets snippet

@name("Delete Projects  Snippets Snippet")
DELETE "https://{{baseUrl}}/projects/:id/snippets/:snippet_id"


// Get projects  snippets snippet  raw

@name("Get Projects  Snippets Snippet  Raw")
GET "https://{{baseUrl}}/projects/:id/snippets/:snippet_id/raw"



