#!/usr/bin/env dothttp

// Returns quality and retention settings for the given camera

@name("getDeviceCameraQualityAndRetentionSettings")
GET "https://{{baseUrl}}/devices/:serial/camera/qualityAndRetentionSettings"
"Accept": "*/*"



// Update quality and retention settings for the given camera
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// profileId| string| The ID of a quality and retention profile to assign to the camera. The profile's settings will override all of the per-camera quality and retention settings. If the value of this parameter is null, any existing profile will be unassigned from the camera.
// motionBasedRetentionEnabled| boolean| Boolean indicating if motion-based retention is enabled(true) or disabled(false) on the camera
// audioRecordingEnabled| boolean| Boolean indicating if audio recording is enabled(true) or disabled(false) on the camera
// restrictedBandwidthModeEnabled| boolean| Boolean indicating if restricted bandwidth is enabled(true) or disabled(false) on the camera
// quality| string| Quality of the camera. Can be one of 'Standard', 'High' or 'Enhanced'. Not all qualities are supported by every camera model.
// resolution| string| Resolution of the camera. Can be one of '1280x720', '1920x1080', '1080x1080' or '2058x2058'. Not all resolutions are supported by every camera model.
// motionDetectorVersion| integer| The version of the motion detector that will be used by the camera. Only applies to Gen 2 cameras. Defaults to v2.

@name("updateDeviceCameraQualityAndRetentionSettings")
PUT "https://{{baseUrl}}/devices/:serial/camera/qualityAndRetentionSettings"
"Accept": "*/*"
"Content-Type": "application/json"
data('{
  "motionBasedRetentionEnabled": false,
  "audioRecordingEnabled": false,
  "restrictedBandwidthModeEnabled": false,
  "profileId": null,
  "quality": "Standard",
  "motionDetectorVersion": 2,
  "resolution": 720
}')


// Returns video settings for the given camera

@name("getDeviceCameraVideoSettings")
GET "https://{{baseUrl}}/devices/:serial/camera/video/settings"
"Accept": "*/*"



// Update video settings for the given camera
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// externalRtspEnabled| boolean| Boolean indicating if external rtsp stream is exposed

@name("updateDeviceCameraVideoSettings")
PUT "https://{{baseUrl}}/devices/:serial/camera/video/settings"
"Accept": "*/*"
"Content-Type": "application/json"
data('{
  "externalRtspEnabled": true
}')


// Returns a list of all camera recording schedules.

@name("getNetworkCameraSchedules")
GET "https://{{baseUrl}}/networks/:networkId/camera/schedules"
"Accept": "*/*"



// Generate a snapshot of what the camera sees at the specified time and return a link to that image.
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// timestamp| string| [optional] The snapshot will be taken from this time on the camera. The timestamp is expected to be in ISO 8601 format. If no timestamp is specified, we will assume current time.
// fullframe| boolean| [optional] If set to "true" the snapshot will be taken at full sensor resolution. This will error if used with timestamp.

@name("generateNetworkCameraSnapshot")
POST "https://{{baseUrl}}/networks/:networkId/cameras/:serial/snapshot"
"Accept": "*/*"
"Content-Type": "application/json"
data('{}')


// Returns video link to the specified camera. If a timestamp is supplied, it links to that timestamp.

@name("getNetworkCameraVideoLink")
GET "https://{{baseUrl}}/networks/:networkId/cameras/:serial/videoLink"
"Accept": "*/*"
? "timestamp"= "{{timestamp}}"




