#!/usr/bin/env dothttp

@name("Company Report Request")
GET "https://connect.creditsafe.com/v1/companies/{companyId}"
"Content-Type": "application/json"
"Authorization": "Bearer {{connectAuthToken}}"
? "language"= "en"


@name("Company Report Request - Example")
GET "https://connect.creditsafe.com/v1/companies/GB001-0-07941364"
"Content-Type": "application/json"
"Authorization": "Bearer {{connectAuthToken}}"
? "language"= "en"


@name("Company Report PDF Template Request")
GET "https://connect.creditsafe.com/v1/companies/{companyId}"
"Content-Type": "application/pdf"
"Authorization": "Bearer {{connectAuthToken}}"
"Accept": "application/pdf"
? "template"= "Summary"



