#!/usr/bin/env dothttp

@name("Testing places in Mexico")
GET "https://{{baseUrl}}/v2/places"
? "affiliateId"= "sherpa"
? "key"= "{{apiKey}}"
? "language"= "en-US"
? "filter[latitude]"= "19.4260333"
? "filter[longitude]"= "-102.0510395"
? "filter[radius]"= "100"
? "filter[limit]"= "10"
? "filter[country]"= "MEX"
? "filter[region]"= "US-CA"
? "filter[tags]"= "Antigen"


@name("Testing places in a given radius of 100 KM")
GET "https://{{baseUrl}}/v2/places"
? "affiliateId"= "sherpa"
? "key"= "{{apiKey}}"
? "language"= "en-US"
? "filter[latitude]"= "19.4260333"
? "filter[longitude]"= "-102.0510395"
? "filter[radius]"= "100"
? "filter[limit]"= "25"
? "filter[country]"= "MEX"
? "filter[region]"= "US-CA"
? "filter[tags]"= "antigen"


@name("Testing places that provides PCR test")
GET "https://{{baseUrl}}/v2/places"
? "affiliateId"= "sherpa"
? "key"= "{{apiKey}}"
? "language"= "en-US"
? "filter[latitude]"= "19.4260333"
? "filter[longitude]"= "-102.0510395"
? "filter[radius]"= "100"
? "filter[tags]"= "antigen"
? "filter[limit]"= "25"
? "filter[country]"= "MEX"
? "filter[region]"= "US-CA"



