#!/usr/bin/env dothttp

@name("Search for Apple Juice")
GET "http://localhost/rest/products/search"
? "q"= "Apple"


@name("Search for Orange Juice")
GET "http://localhost/rest/products/search"
? "q"= "Orange"


@name("Search for Everything")
GET "http://localhost/rest/products/search"



