#!/usr/bin/env dothttp

// Gives Bank Account Verification Status

@name("Verify Bank Account")
GET "https://{{sandbox_host}}/bank/:ifsc/accounts/:account_number/verify"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"
? "name"= "{{name}}"
? "mobile"= "{{mobile}}"



