#!/usr/bin/env dothttp

@name("{{url}}/api/WkCcavenue/201976")
PUT "https://{{url}}/api/WkCcavenue/201976"
basicauth("{{user_name}}", "{{api_key}}")
"Content-Type": "application/json"
data('{
	"amount": "1115.0",
	"bank_receipt_no": "null",
	"bank_ref_no": "null",
	"billing_address": "chic",
	"billing_city": "hzhzhz",
	"billing_country": "United Arab Emirates",
	"billing_email": "idea@i.com",
	"billing_name": "jkkk hhvc",
	"billing_state": "Abu Dhabi",
	"billing_tel": "9936363636",
	"billing_zip": "",
	"card_holder_name": "",
	"card_name": "MasterCard",
	"currency": "AED",
	"delivery_address": "chic",
	"delivery_city": "hzhzhz",
	"delivery_country": "United Arab Emirates",
	"delivery_name": "jkkk hhvc",
	"delivery_state": "Abu Dhabi",
	"delivery_tel": "9936363636",
	"delivery_zip": "",
	"discount_value": "0.0",
	"eci_value": "07",
	"failure_message": "",
	"mer_amount": "1115.0",
	"merchant_param1": "Paramater 1",
	"merchant_param2": "Paramater 2",
	"merchant_param3": "Paramater 3",
	"merchant_param4": "Paramater 4",
	"merchant_param5": "Paramater 5",
	"merchant_param6": "5123452346",
	"offer_code": "null",
	"offer_type": "null",
	"order_id": "201974",
	"order_status": "Success",
	"payment_mode": "Credit Card",
	"response_type": "JSON",
	"status_code": "null",
	"status_message": "The card holder was not authorised. This is used in 3-D Secure Authentication.",
	"tracking_id": "107005452081",
	"vault": "N"
}')



