#!/usr/bin/env dothttp

// This method authenticates a user to the Vault and returns a token that can be used in subsequent web services calls. In addition, this method allows you to set a new password.// // Users can authenticate using CyberArk, LDAP or RADIUS authentication.
@name("Logon")
POST "https://{{BaseURL}}/PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logon"
"Content-Type": "application/json"
data('{
	"username": "{{apiUsername}}",
	"password": "{{apiPassword}}",
	"connectionNumber": "1"
}')


// This method logs off the user and removes the Vault session.
@name("Logoff")
POST "https://{{BaseURL}}/PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logoff"
"Content-Type": "application/json"
"Authorization": "{{CyberArkLogonResult}}"



