#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List plans")
GET "https://{{baseUrl}}/marketplace_listing/plans"
? "per_page"= "30"
? "page"= "1"


@name("List accounts for a plan")
GET "https://{{baseUrl}}/marketplace_listing/plans/{{plan_id}}/accounts"
? "sort"= "created"
? "direction"= "asc"
? "per_page"= "30"
? "page"= "1"



