#!/usr/bin/env dothttp

@name("Site")
GET "https://{{host}}/services/data/v47.0/sobjects/Site/"


@name("Site Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Site/{ID}/"


@name("Describe Site")
GET "https://{{host}}/services/data/v47.0/sobjects/Site/describe/"



