#!/usr/bin/env dothttp

@name("Get tenant configuration based on service identifier")
GET "https://{{baseUrl}}/instance/microservice/:identifier/tenants/:tenantToken/configuration"
"Authorization": ""


@name("Update global configuration based on service identifier.")
POST "https://{{baseUrl}}/instance/microservice/:identifier/tenants/:tenantToken/configuration"
"Authorization": ""
"Content-Type": "application/json"
json({
    "attributes": [
        {
            "name": "<string>",
            "namespace": "<string>",
            "value": "<string>"
        },
        {
            "name": "<string>",
            "namespace": "<string>",
            "value": "<string>"
        }
    ],
    "children": [
        {
            "attributes": [
                {
                    "name": "<string>",
                    "namespace": "<string>",
                    "value": "<string>"
                },
                {
                    "name": "<string>",
                    "namespace": "<string>",
                    "value": "<string>"
                }
            ],
            "children": [
                {
                    "value": "<Circular reference to #/components/schemas/ElementContent detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/ElementContent detected>"
                }
            ],
            "id": "<string>",
            "name": "<string>",
            "namespace": "<string>"
        },
        {
            "attributes": [
                {
                    "name": "<string>",
                    "namespace": "<string>",
                    "value": "<string>"
                },
                {
                    "name": "<string>",
                    "namespace": "<string>",
                    "value": "<string>"
                }
            ],
            "children": [
                {
                    "value": "<Circular reference to #/components/schemas/ElementContent detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/ElementContent detected>"
                }
            ],
            "id": "<string>",
            "name": "<string>",
            "namespace": "<string>"
        }
    ],
    "id": "<string>",
    "name": "<string>",
    "namespace": "<string>"
})



