#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Issue Property")
GET "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/properties/:propertyKey"


@name("Set Issue Property")
PUT "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/properties/:propertyKey"
"Content-Type": "application/json"
data('{}')


@name("Delete Issue Property")
DELETE "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/properties/:propertyKey"



