#!/usr/bin/env dothttp

@name("Content Asset")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentAsset/"


@name("Content Asset Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentAsset/{ID}/"


@name("Describe Content Asset")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentAsset/describe/"



