#!/usr/bin/env dothttp

@name("Campaign")
GET "https://{{host}}/services/data/v47.0/sobjects/Campaign/"


@name("Campaign Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Campaign/{ID}/"


@name("Describe Campaign")
GET "https://{{host}}/services/data/v47.0/sobjects/Campaign/describe/"



