#!/usr/bin/env dothttp

@name("egressmatrixcell")
GET "https://{{base_url}}/ers/config/egressmatrixcell"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"
? "size"= "100"
? "page"= "1"
? "filter"= "name.CONTAINS.irv"
? "sortasc"= "name"
? "sortdsc"= "name"


@name("egressmatrixcell/{id}")
GET "https://{{base_url}}/ers/config/egressmatrixcell/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 egressmatrixcell")
POST "https://{{base_url}}/ers/config/egressmatrixcell"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 egressmatrixcell/{id}")
PUT "https://{{base_url}}/ers/config/egressmatrixcell/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 egressmatrixcell/clearallmatrixcells")
PUT "https://{{base_url}}/ers/config/egressmatrixcell/clearallmatrixcells"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 egressmatrixcell/status/{status}")
PUT "https://{{base_url}}/ers/config/egressmatrixcell/status/{{status}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 egressmatrixcell/clonecell/{id}/srcSgt/{srcSgtId}/dstSgt/{dstSgtId}")
PUT "https://{{base_url}}/ers/config/egressmatrixcell/clonecell/{{id}}/srcSgt/{{srcSgtId}}/dstSgt/{{dstSgtId}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("egressmatrixcell/{id}")
DELETE "https://{{base_url}}/ers/config/egressmatrixcell/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 egressmatrixcell/bulk/submit")
PUT "https://{{base_url}}/ers/config/egressmatrixcell/bulk/submit"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 egressmatrixcell/bulk/{bulkid}")
GET "https://{{base_url}}/ers/config/egressmatrixcell/bulk/{{bulkid}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"



