#!/usr/bin/env dothttp

// 获得所有的日期

@name("getAllHoliday")
GET "https://{{url}}/api/v1/holiday/all"


// 获得一个id，holiday
// 
// **参数**
// - id: 表示`Holiday`的主键（需要加在请求链接里）

@name("getOneHoliday")
GET "https://{{url}}/api/v1/holiday/id"


// 创建一个假期
// 
// **参数**
// - name：假期名称
// - time：假期时间（公历）

@name("creatOneHoliday")
POST "https://{{url}}/api/v1/holiday"
files(
	("name", "圣诞节"),
	("time", "12-25"),
	("status", "1")
)


// 更新假期事件
// 
// **参数**
// - id: 表示`Holiday`的主键（需要加在请求链接里）

@name("udpateOneHoliday")
PATCH "https://{{url}}/api/v1/holiday"
files(
	("name", ""),
	("time", ""),
	("status", "")
)


// 删除一个id，节日
// 
// **参数**
// - id: 表示`Holiday`的主键（需要加在请求链接里）

@name("deleteOneHoliday")
DELETE "https://{{url}}/api/v1/holiday/id"



// 搜索节假日
// 
// **参数**
// - term: 表示搜索的项目（name、time)

@name("searchHoliday")
GET "https://{{url}}/api/v1/holiday/search"


// 获得所有的节假日（按照节假日发布的时间排列）

@name("getAllHolidaySortByTime")
GET "https://{{url}}/api/v1/holiday/sort"



