#!/usr/bin/env dothttp

// Provides the list of all sent emails.
// 
// This method uses pagination.
// 
// Check the examples on the right sidebar.

@name("Get all sent emails")
GET "https://{{url}}/api/sent-emails/"
? "campaigns[]"= "1697"
? "page"= "1"
? "sort"= "created_at"
? "order"= "asc"
? "order"= "desc"
? "size"= "10"


// Provides information about single sent email by providing sent email Id.

@name("Get a single sent email")
GET "https://{{url}}/api/sent-emails/{{sent-email}}"



