#!/usr/bin/env dothttp

@name("Retrieve single contact (with its answers and messages)")
GET "https://{{base_url}}/forms/{{form_id}}/contacts/{{contact_id}}"
"Authorization": "Bearer {{token}}"
? "include_answers"= "true"
? "include_messages"= "true"


// Get all the answers of a specific question.
// 
// Optional fields for pagination:
// - `offset` to indicate from which answer we want to start the page
// - `limit` to indicate the size of the page

@name("Retrieve question answers")
GET "https://{{base_url}}/questions/{{question_id}}/answers"
"Authorization": "Bearer {{token}}"
? "limit"= "20"
? "offset"= "0"


@name("Retrieve question insights")
GET "https://{{base_url}}/questions/{{question_id}}/insights"
"Authorization": "Bearer {{token}}"



