#!/usr/bin/env dothttp

// Basic information about electronic files coming into the FEC, posted as they are received.

@name("/efile/filings/")
GET "https://{{baseUrl}}/efile/filings/"
? "per_page"= "20"
? "sort"= "-receipt_date"
? "file_number"= "<integer>"
? "file_number"= "<integer>"
? "max_receipt_date"= "<date>"
? "committee_id"= "<string>"
? "committee_id"= "<string>"
? "sort_nulls_last"= "false"
? "api_key"= "DEMO_KEY"
? "sort_null_only"= "false"
? "min_receipt_date"= "<date>"
? "page"= "1"
? "sort_hide_null"= "false"



