#!/usr/bin/env dothttp

// This method adds a web application URL to the allowed referrer list. This means access is allowed from the URL to the PVWA. Any user who is a member of the Vault admins group can run this web service.

@name("Add Allowed Referrer")
POST "https://{{BaseURL}}/passwordvault/api/Configuration/AccessRestriction/AllowedReferrers"
"Authorization": "{{CyberArkLogonResult}}"
"Content-Type": "application/json"
json({
    "referrerURL": "https://CompanyA/portal/",
    "regularExpression": false
})


// This method returns the allowed referrer list. This means access is allowed from all URLs in the list, to the PVWA. Any user who is a member of the Vault admins group can run this web service.

@name("Get Allowed Referrer")
GET "https://{{BaseURL}}/passwordvault/api/Configuration/AccessRestriction/AllowedReferrers"
"Authorization": "{{CyberArkLogonResult}}"
"Content-Type": "application/json"



