#!/usr/bin/env dothttp

@name("NumberToWords")
POST "https://www.dataaccess.com/webservicesserver/NumberConversion.wso"
"Content-Type": "text/xml; charset=utf-8"
data('<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <NumberToWords xmlns="http://www.dataaccess.com/webservicesserver/">
      <ubiNum>500</ubiNum>
    </NumberToWords>
  </soap:Body>
</soap:Envelope>')


@name("NumberToDollars")
POST "https://www.dataaccess.com/webservicesserver/NumberConversion.wso"
"Content-Type": "text/xml; charset=utf-8"
data('<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <NumberToDollars xmlns="http://www.dataaccess.com/webservicesserver/">
      <dNum>500</dNum>
    </NumberToDollars>
  </soap:Body>
</soap:Envelope>')



