#!/usr/bin/env dothttp

@name("Returns a list of salesInvoices")
GET "https://{{baseUrl}}/companies({{company_id}})/salesInvoices"
? "$top"= "<integer>"
? "$skip"= "<integer>"
? "$limit"= "<integer>"
? "$filter"= "<string>"
? "$expand"= "<string>,<string>"
? "$select"= "<string>,<string>"


@name("Creates an object of type salesInvoice in Dynamics 365 Business Central")
POST "https://{{baseUrl}}/companies({{company_id}})/salesInvoices"
"Content-Type": "<string>"
"Content-Type": "application/json"
json({
    "id": "<uuid>",
    "number": "<string>",
    "externalDocumentNumber": "<string>",
    "invoiceDate": "<dateTime>",
    "dueDate": "<dateTime>",
    "customerPurchaseOrderReference": "<string>",
    "customerId": "<uuid>",
    "contactId": "<string>",
    "customerNumber": "<string>",
    "customerName": "<string>",
    "billToName": "<string>",
    "billToCustomerId": "<uuid>",
    "billToCustomerNumber": "<string>",
    "shipToName": "<string>",
    "shipToContact": "<string>",
    "sellingPostalAddress": {
        "street": "<string>",
        "city": "<string>",
        "state": "<string>",
        "countryLetterCode": "<string>",
        "postalCode": "<string>",
        "customerFinancialDetails": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "picture": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "defaultDimensions": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "currency": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "paymentTerm": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "shipmentMethod": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "paymentMethod": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        }
    },
    "billingPostalAddress": {
        "street": "<string>",
        "city": "<string>",
        "state": "<string>",
        "countryLetterCode": "<string>",
        "postalCode": "<string>",
        "customerFinancialDetails": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "picture": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "defaultDimensions": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "currency": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "paymentTerm": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "shipmentMethod": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "paymentMethod": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        }
    },
    "shippingPostalAddress": {
        "street": "<string>",
        "city": "<string>",
        "state": "<string>",
        "countryLetterCode": "<string>",
        "postalCode": "<string>",
        "customerFinancialDetails": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "picture": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "defaultDimensions": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "currency": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "paymentTerm": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "shipmentMethod": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "paymentMethod": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        }
    },
    "currencyId": "<uuid>",
    "currencyCode": "<string>",
    "orderId": "<uuid>",
    "orderNumber": "<string>",
    "paymentTermsId": "<uuid>",
    "shipmentMethodId": "<uuid>",
    "salesperson": "<string>",
    "pricesIncludeTax": "<boolean>",
    "remainingAmount": "<decimal>",
    "discountAmount": "<decimal>",
    "discountAppliedBeforeTax": "<boolean>",
    "totalAmountExcludingTax": "<decimal>",
    "totalTaxAmount": "<decimal>",
    "totalAmountIncludingTax": "<decimal>",
    "status": "<string>",
    "lastModifiedDateTime": "<dateTime>",
    "phoneNumber": "<string>",
    "email": "<string>"
})



