#!/usr/bin/env dothttp

@name("Remove Member")
POST "https://api.dropboxapi.com/2/team/members/remove"
"Authorization": "Bearer {{access_token}}"
data('{
    "user": {
        ".tag": "{{team_member_identifier}}",
        "{{team_member_identifier}}": "{{team_member}}"
    },
    "wipe_data": {{wipe_data}},
    "transfer_dest_id": {
        ".tag": "{{dest_member_identifier}}",
        "{{dest_member_identifier}}": "{{dest_team_member}}"
    },
    "transfer_admin_id": {
        ".tag": "{{transfer_admin_identifier}}",
        "{{transfer_admin_identifier}}": "{{transfer_admin}}"
    },
    "keep_account": {{keep_account}},
    "retain_team_shares": {{retain_team_shares}}
}')



