#!/usr/bin/env dothttp

// # Get CRM Customers
// ---
// 
// Returns up to 1,000 matching, Active Customers from the MainDB.CustProspect table. If a search text value is provided, records will be returned where the COName, ID, or SearchWords match the given value (using a wild-card matches search).
// 
// # Parameters
// ---
// 
// **CompanyID** - Type *string* **:**
// The optional CompanyID used to authenticate this request
// 
// **SearchText** - Type *string* **:**
// This optional text will be searched for in the "COName", "ID", and "SearchWords" fields

@name("{GET}")
GET "https://{{ServerPath}}/CRM/Customer"
"Content-Type": "application/json"
"X-API-Key": "{{APIKey}}"
? "CompanyID"= "{{CompanyID}}"




