#!/usr/bin/env dothttp

@name("Films")
GET "https://ghibliapi.herokuapp.com/films"


@name("People")
GET "https://ghibliapi.herokuapp.com/people"


@name("Locations")
GET "https://ghibliapi.herokuapp.com/locations"


@name("Species")
GET "https://ghibliapi.herokuapp.com/species"


@name("Vehicles")
GET "https://ghibliapi.herokuapp.com/vehicles"



