#!/usr/bin/env dothttp

@name("Solution History")
GET "https://{{host}}/services/data/v47.0/sobjects/SolutionHistory/"


@name("Solution History Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/SolutionHistory/{ID}/"


@name("Describe Solution History")
GET "https://{{host}}/services/data/v47.0/sobjects/SolutionHistory/describe/"



