#!/usr/bin/env dothttp

// <h2> Description </h2>
// This operation creates a user.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/post_user.htm)

@name("User")
POST "https://{{ServerUrl}}/User"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
json({
    "users": [
        {
            "description": "backup admin user",
            "agePasswordDays": 10,
            "password": "QnVpbGRlciExMg==",
            "email": "jdoe@company.com",
            "fullName": "Jane Doe",
            "enableUser": true,
            "associatedUserGroups": [
                {
                    "userGroupName": "View"
                }
            ],
            "userEntity": {
                "userName": "jdoe"
            }
        }
    ]
})


// <h2> Description </h2>
// This operation returns a list of users.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_user.htm)

@name("User")
GET "https://{{ServerUrl}}/User"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"



// <h2> Description </h2>
// This operation returns a list of sessions for a user. The API applies to all Commvault consoles, all mobile applications, and the command line interface.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_user_active_sessions_details.htm)

@name("Session Details")
GET "https://{{ServerUrl}}/Session"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
? "userId"= "1"



// <h2> Description </h2>
// This operation returns the properties associated with a user.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_user_properties.htm)
// 
// <h3>Information returned with different levels:</h3>
// 
// 1: ListOnly
// 
// 10: Basic Properties
// 
// 30: All Properties
// 
// 40: Returns associatedUserGroups, associatedExternalUserGroups, SecurityAssociations + all other properties 
// 
// 50: Returns associatedUserGroups, associatedExternalUserGroups, SecurityAssociations, UserSecurity + all other properties 

@name("User Properties")
GET "https://{{ServerUrl}}/User/{{UserId}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
? "level"= "1"



// <h2> Description </h2>
// This operation logs off users from Web Server and the command line interface.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/delete_user_session.htm)

@name("Sessions")
DELETE "https://{{ServerUrl}}/Sessions"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
json({
    "sessions": [
        "2E1C7303-360B-4787-A09E-93C8189EBC59",
        "EMCBC189BC3-E861-4D59-86CA-BB552F8F8A02"
    ]
})


// <h2> Description </h2>
// This operation returns a list of users and user groups.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_users_usergroups.htm)

@name("Users and User Groups")
GET "https://{{ServerUrl}}/UsersAndGroups"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"



// <h2> Description </h2>
// This operation updates the properties associated with a user.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/post_user_properties.htm)

@name("User Properties")
POST "https://{{ServerUrl}}/User/{{UserId}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
json({
    "users": [
        {
            "description": "Modifying description",
            "associatedUserGroupsOperationType": 2,
            "agePasswordDays": 120,
            "password": "QnVpbGRlciExMg==",
            "email": "jdoe@company.com",
            "fullName": "Jane Doe",
            "enableUser": true,
            "associatedUserGroups": [
                {
                    "userGroupName": "View All"
                }
            ],
            "userEntity": {
                "userName": "jdoe"
            },
            "validationParameters": {
                "password": "QnVpbGRlciExMg=="
            }
        }
    ]
})


// This operation disables a User

@name("Disable User")
PUT "https://{{ServerUrl}}/User/{{UserId}}/Disable"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"



// This operation enables a User

@name("Enable User")
PUT "https://{{ServerUrl}}/User/{{UserId}}/Enable"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"



// <h2> Description </h2>
// This operation deletes a user.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/delete_user.htm)

@name("User")
DELETE "https://{{ServerUrl}}/User/{{userId}}"
"Accept": "application/json"
"Authtoken": "{{TOKEN}}"
? "newUserId"= "0"
? "newUserGroupId"= "0"




