#!/usr/bin/env dothttp

// Save **partial** data as field(s) within the document with provided `id`. Note that the fields in the request body are wrapped inside a `doc` key. Read more [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-update.html#_updates_with_a_partial_document).
// 
// | Variable       | Description                           |
// |----------------|---------------------------------------|
// | app            | App name                              |
// | id             | Document ID (a unique string)         |
// | credentials_64 | App's credentials encoded with base64 |

@name("/:app/_doc/:id/_update")
POST "https://{{host}}/{{app}}/{{type}}/{{id}}/_update"
"Authorization": "Basic {{credentials_64}}"
"Content-Type": "application/json"
json({
    "doc": {
        "text": "A quick brown fox jumps over the lazy dog."
    }
})


// Save **partial** data as field(s) within the document with provided `id` via a script. Note that the fields in the request body are wrapped inside a `script` key. Read more [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-update.html#_scripted_updates).
// 
// | Variable       | Description                           |
// |----------------|---------------------------------------|
// | app            | App name                              |
// | id             | Document ID (a unique string)         |
// | credentials_64 | App's credentials encoded with base64 |

@name("/:app/_doc/:id/_update (via script)")
POST "https://{{host}}/{{app}}/{{type}}/{{id}}/_update"
"Authorization": "Basic {{credentials_64}}"
"Content-Type": "application/json"
json({
    "script": {
        "inline": "ctx._source.text += params.tag",
        "params": {
            "tag": " I am an additional sentence."
        }
    }
})



