#!/usr/bin/env dothttp

// Adds role assignments to the role.
// Add Assignment

@name("Adds a Roles Assignments By ID")
PUT "https://{{baseUrl}}/1.0/roles/:id/assignments"


// Returns a template, which is an example add assignments context that can be used as a reference for what add
//  assignments context objects should look like.
// Add Assignments Context Template

@name("Roles Assignments Template Add assignments")
GET "https://{{baseUrl}}/1.0/roles/:id/assignments/template/addassignments"



