#!/usr/bin/env dothttp

// Fetch onboarding status of cameras
@name("Fetch Onboarding Status Of Cameras")
GET "https://{{baseUrl}}/organizations/:organizationId/camera/onboarding/statuses"
"X-Cisco-Meraki-API-Key": ""
? "serials"= "{{serials}}"
? "networkIds"= "{{networkIds}}"


// Notify that credential handoff to camera has completed//  #### Body Parameters // **Parameter**|**Type**|**Description** //  :-------------: |:-------------: |:-------------: // serial| string| Serial of camera// wirelessCredentialsSent| boolean| Note whether credentials were sent successfully
@name("Notify That Credential Handoff To Camera Has Completed")
PUT "https://{{baseUrl}}/organizations/:organizationId/camera/onboarding/statuses"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "serial": "<string>",
    "wirelessCredentialsSent": "<boolean>"
}')



