#!/usr/bin/env dothttp

// This resource reports the number of shipments and the corresponding shipment types that the account booked during the selected time period.
// Shipment type can either be parcel or pallet.
// The 2 consolidation parameters (consolidateAccounts and consolidateCarriers) can be used to get more insight on sub-account and carrier level.
// 
// The max allowed report period is 1 year, i.e. the time between startDate and endDate.

@name("9.1 Shipment Counters")
GET "https://{{base_url}}/v2/reports/{{account}}/shipmentcounter"
? "startDate"= "2020-09-01"
? "endDate"= "2020-09-30"
? "consolidateAccounts"= "false"
? "consolidateCarriers"= "false"
? "account"= "DEMO,DEMOSUB"



