#!/usr/bin/env dothttp

// <p>Returns a list of security zones. Can optionally sort the resulting list in ascending or
//  descending order. Other params given will be used as search values.</p>
//  <p class="italicize">Examples:</p>
//  <div class="code indent"><pre>/restman/1.0/securityZones?name=MySecurityZone</pre></div>
//  <p>Returns security zone with name "MySecurityZone".</p>
//  <p>If a parameter is not a valid search value a bad request error will be returned.</p>
// List

@name("List All Security Zones")
GET "https://{{baseUrl}}/1.0/securityZones"
? "sort"= "<string>"
? "order"= "<string>"
? "name"= "<array>"


// Returns a security zone with the given ID.
// Get

@name("List Security Zones By ID")
GET "https://{{baseUrl}}/1.0/securityZones/:id"


// Returns a template, which is an example security zone that can be used as a reference for what security zone
//  objects should look like.
// Template

@name("Security Zones Template")
GET "https://{{baseUrl}}/1.0/securityZones/template"



