#!/usr/bin/env dothttp

@name("Macro Usage")
GET "https://{{host}}/services/data/v47.0/sobjects/MacroUsage/"


@name("Macro Usage Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/MacroUsage/{ID}/"


@name("Describe Macro Usage")
GET "https://{{host}}/services/data/v47.0/sobjects/MacroUsage/describe/"



