#!/usr/bin/env dothttp

@name("List customer balance transactions")
GET "https://{{baseUrl}}/v1/customers/:customer/balance_transactions"
"Content-Type": "application/x-www-form-urlencoded"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "limit"= "<integer>"
? "starting_after"= "<string>"


@name("Create a customer balance transaction")
POST "https://{{baseUrl}}/v1/customers/:customer/balance_transactions"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "amount": [
        "<integer>"
    ],
    "currency": [
        "<string>"
    ],
    "description": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})


@name("Retrieve a customer balance transaction")
GET "https://{{baseUrl}}/v1/customers/:customer/balance_transactions/:transaction"
"Content-Type": "application/x-www-form-urlencoded"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"


@name("Update a customer balance transaction")
POST "https://{{baseUrl}}/v1/customers/:customer/balance_transactions/:transaction"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "description": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})



