#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Issue Link Type")
GET "None://{{baseUrl}}/rest/api/3/issueLinkType/:issueLinkTypeId"


@name("Update Issue Link Type")
PUT "None://{{baseUrl}}/rest/api/3/issueLinkType/:issueLinkTypeId"
"Content-Type": "application/json"
data('{
    "id": "<string>",
    "name": "<string>",
    "inward": "<string>",
    "outward": "<string>"
}')


@name("Delete Issue Link Type")
DELETE "None://{{baseUrl}}/rest/api/3/issueLinkType/:issueLinkTypeId"



