#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Issue Link Type")
GET "https://{{baseUrl}}/rest/api/3/issueLinkType/:issueLinkTypeId"


@name("Update Issue Link Type")
PUT "https://{{baseUrl}}/rest/api/3/issueLinkType/:issueLinkTypeId"
"Content-Type": "application/json"
data('{
    "id": "<string>",
    "name": "<string>",
    "inward": "<string>",
    "outward": "<string>"
}')


@name("Delete Issue Link Type")
DELETE "https://{{baseUrl}}/rest/api/3/issueLinkType/:issueLinkTypeId"



