#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List organization repositories")
GET "https://{{baseUrl}}/orgs/{{org}}/repos"
? "type"= "forks"
? "sort"= "created"
? "direction"= "asc"
? "per_page"= "30"
? "page"= "1"


@name("Create an organization repository")
POST "https://{{baseUrl}}/orgs/{{org}}/repos"
"Content-Type": "application/json"
json({
    "name": "Hello-World",
    "description": "This is your first repository",
    "homepage": "https://github.com",
    "private": false,
    "has_issues": true,
    "has_projects": true,
    "has_wiki": true
})



