#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get an issue")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo/issues/:issue_number}}/"


@name("Update an issue")
PATCH "https://{{baseUrl}}/repos/{{owner}}/{{repo/issues/:issue_number}}/"
"Content-Type": "application/json"
json({
    "title": "Found a bug",
    "body": "I'm having a problem with this.",
    "assignees": [
        "octocat"
    ],
    "milestone": 1,
    "state": "open",
    "labels": [
        "bug"
    ]
})


@name("List issue events")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo/issues/{{issue_number}}/events}}/"
? "per_page"= "30"
? "page"= "1"


@name("List timeline events for an issue")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo/issues/{{issue_number}}/timeline}}/"
? "per_page"= "30"
? "page"= "1"



