#!/usr/bin/env dothttp

@name("Case Team Template Member")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamTemplateMember/"


@name("Case Team Template Member Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamTemplateMember/{ID}/"


@name("Describe Case Team Template Member")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamTemplateMember/describe/"



