#!/usr/bin/env dothttp

@name("Embedded Service Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/EmbeddedServiceDetail/"


@name("Embedded Service Detail Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/EmbeddedServiceDetail/{ID}/"


@name("Describe Embedded Service Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/EmbeddedServiceDetail/describe/"



