#!/usr/bin/env dothttp

@name("Solution Status")
GET "https://{{host}}/services/data/v47.0/sobjects/SolutionStatus/"


@name("Solution Status Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/SolutionStatus/{ID}/"


@name("Describe Solution Status")
GET "https://{{host}}/services/data/v47.0/sobjects/SolutionStatus/describe/"



