#!/usr/bin/env dothttp

@name("Create Auction")
POST "https://order-uat.blocklist.mobi/api/auctions"
"Content-Type": "application/json"
data('{
	"item_id": "3",
	"currency_id": "1",
	"time_start": "2018-10-17 13:45",
	"time_end": "2018-10-17 20:45",
	"starting_price": "10"
}')


@name("List Auctions")
GET "https://order-uat.blocklist.mobi/api/auctions"
? "user_ids"= "6"
? "disabled"= "0"



@name("Update Auction")
PUT "https://order-uat.blocklist.mobi/api/auctions/1"
"Content-Type": "application/json"
data('{
	"item_id": "3",
	"currency_id": "1",
	"time_start": "2018-10-17 13:45",
	"time_end": "2018-10-17 20:45",
	"starting_price": "10",
	"disabled": false
}')


@name("Delete Auction")
DELETE "https://order-uat.blocklist.mobi/api/auctions/2"



@name("Bid on Auctions")
POST "https://order-uat.blocklist.mobi/api/auction_standings"
"Content-Type": "application/json"
data('{
	"auction_id": 1,
	"price": "18"
}')


@name("List Auction Biddings")
GET "https://order-uat.blocklist.mobi/api/auction_standings"
? "auction_ids"= "1"




