#!/usr/bin/env dothttp

@name("Add product to wishlist")
PUT "https://{{url}}/api/addtowishlist/{{customer_id}}"
basicauth("{{user_name}}", "{{api_key}}")
"Content-Type": "application/json"
data('{"product_data":{"amount":"1","extra":[],"product_id":5765,"product_options":[]}}')


@name("Delete product from whishlist")
GET "https://{{url}}/api/addtowishlist/{{customer_id}}"
basicauth("{{user_name}}", "{{api_key}}")
? "item_id"= "{{item_id}}"
? "scope"= "wishlist_product_delete"
? "lang_code"= "{{lang_code}}"
? "currency_code"= "{{currency_code}}"




