#!/usr/bin/env dothttp

@name("List Devices (with tag)")
GET "https://{{WEBEXAPI}}/devices"
"Authorization": "Bearer {{access_token}}"
? 'tag'= '"postman"'


@name("List Devices (xAPI enabled)")
GET "https://{{WEBEXAPI}}/devices"
"Authorization": "Bearer {{access_token}}"
? "permissions"= "xapi"


@name("Get my Details")
GET "https://{{WEBEXAPI}}/people/me"
"Authorization": "Bearer {{access_token}}"



