#!/usr/bin/env dothttp

@name("Returns a list of journalLines")
GET "https://{{baseUrl}}/companies({{company_id}})/journals({{journal_id}})/journalLines"
? "$top"= "<integer>"
? "$skip"= "<integer>"
? "$limit"= "<integer>"
? "$filter"= "<string>"
? "$expand"= "<string>,<string>"
? "$select"= "<string>,<string>"


@name("Creates an object of type journalLine in Dynamics 365 Business Central")
POST "https://{{baseUrl}}/companies({{company_id}})/journals({{journal_id}})/journalLines"
"Content-Type": "<string>"
"Content-Type": "application/json"
data('{
    "id": "<uuid>",
    "journalDisplayName": "<string>",
    "lineNumber": "<integer>",
    "accountType": "<string>",
    "accountId": "<uuid>",
    "accountNumber": "<string>",
    "postingDate": "<dateTime>",
    "documentNumber": "<string>",
    "externalDocumentNumber": "<string>",
    "amount": "<decimal>",
    "description": "<string>",
    "comment": "<string>",
    "dimensions": [
        {
            "code": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "displayName": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "valueCode": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "valueDisplayName": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "customer": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        {
            "code": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "displayName": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "valueCode": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "valueDisplayName": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "customer": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        }
    ],
    "lastModifiedDateTime": "<dateTime>"
}')



