#!/usr/bin/env dothttp

@name("Returns qa flow rate audits data by state")
GET "https://{{baseUrl}}/qaFlowRateAudits/byState"
? "email"= "esse nostrud veniam id"
? "key"= "esse nostrud veniam id"
? "param"= "esse nostrud veniam id"
? "bdate"= "esse nostrud veniam id"
? "edate"= "esse nostrud veniam id"
? "cbdate"= "esse nostrud veniam id"
? "cedate"= "esse nostrud veniam id"
? "state"= "esse nostrud veniam id"


@name("Returns qa flow rate audits data by county")
GET "https://{{baseUrl}}/qaFlowRateAudits/byCounty"
? "email"= "esse nostrud veniam id"
? "key"= "esse nostrud veniam id"
? "param"= "esse nostrud veniam id"
? "bdate"= "esse nostrud veniam id"
? "edate"= "esse nostrud veniam id"
? "cbdate"= "esse nostrud veniam id"
? "cedate"= "esse nostrud veniam id"
? "state"= "esse nostrud veniam id"
? "county"= "esse nostrud veniam id"


@name("Returns qa flow rate audits data by site")
GET "https://{{baseUrl}}/qaFlowRateAudits/bySite"
? "email"= "esse nostrud veniam id"
? "key"= "esse nostrud veniam id"
? "param"= "esse nostrud veniam id"
? "bdate"= "esse nostrud veniam id"
? "edate"= "esse nostrud veniam id"
? "cbdate"= "esse nostrud veniam id"
? "cedate"= "esse nostrud veniam id"
? "state"= "esse nostrud veniam id"
? "county"= "esse nostrud veniam id"
? "site"= "esse nostrud veniam id"


@name("Returns qa flow rate audits data by primary quality assurance organization code")
GET "https://{{baseUrl}}/qaFlowRateAudits/byPQAO"
? "email"= "esse nostrud veniam id"
? "key"= "esse nostrud veniam id"
? "param"= "esse nostrud veniam id"
? "bdate"= "esse nostrud veniam id"
? "edate"= "esse nostrud veniam id"
? "cbdate"= "esse nostrud veniam id"
? "cedate"= "esse nostrud veniam id"
? "pqao"= "esse nostrud veniam id"


@name("Returns qa flow rate audits data by monitoring agency code")
GET "https://{{baseUrl}}/qaFlowRateAudits/byMA"
? "email"= "esse nostrud veniam id"
? "key"= "esse nostrud veniam id"
? "param"= "esse nostrud veniam id"
? "bdate"= "esse nostrud veniam id"
? "edate"= "esse nostrud veniam id"
? "cbdate"= "esse nostrud veniam id"
? "cedate"= "esse nostrud veniam id"
? "agency"= "esse nostrud veniam id"



