#!/usr/bin/env dothttp

@name("What's the word?")
GET "https://{{baseUrl}}/api/wordsearch/"


// Click on the Body tab to view the request body being submitted. Fill in correct answer inside each pair of quotes and press Send!

@name("Submit answers")
POST "https://{{baseUrl}}/api/wordsearch/submit"
json({
    "answers": [
        "",
        "",
        "",
        "",
        "",
        ""
    ]
})



