#!/usr/bin/env dothttp

// Get a list of valid device options.

@name("Get options")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/owners/options"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"


// Get a list of groups.
// 
// 
// Certain fields are encrypted.  Please see [Data Encryption Documentation](https://www.netify.ai/developer/netify-api/data-encryption) for details.

@name("Get groups")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/groups"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"


// Create a new group identity.  The following parameters should be encrypted with your secret passphrase:
// 
// * name
// * description

@name("Create group")
POST "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/groups"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"
? "name"= "Executive Team"
? "description"= "All members of the senior executive team"


// Update an existing group identity.  The following data should be encrypted:
// 
// * name
// * description

@name("Update group")
PATCH "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/groups/:id"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"
? "name"= "Exec Team"


// Delete an existing group.

@name("Delete group")
DELETE "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/groups/:id"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"



