#!/usr/bin/env dothttp

// List all organizations visible by your account.
// 
// https://developer.webex.com/endpoint-organizations-get.html
// 
// Example Response:
// ``` json
// {
//   'items' : [ {
//     'id' : 'OTZhYmMyYWEtM2RjYy0xMWU1LWExNTItZmUzNDgxOWNkYzlh',
//     'displayName' : 'Acme, Inc.',
//     'created' : '2015-10-18T14:26:16+00:00'
//   } ]
// }
// ```

@name("List Organizations")
GET "https://{{WEBEXAPI}}/organizations"
"Authorization": "Bearer {{access_token}}"


// List admin audit events in your organization. Several query parameters are available to filter the response.
// 
// Long result sets will be split into pages.
// 
// https://developer.webex.com/docs/api/v1/admin-audit-events/list-admin-audit-events

@name("List Admin Audit Events")
GET "https://{{WEBEXAPI}}/adminAudit/events"
"Authorization": "Bearer {{access_token}}"
? "orgId"= "{{_organization}}"
? "from"= "{{_yesterday}}"
? "to"= "{{_now}}"


// List admin audit events in your organization. Several query parameters are available to filter the response.
// 
// Long result sets will be split into pages.
// 
// https://developer.webex.com/docs/api/v1/admin-audit-events/list-admin-audit-events

@name("List Admin Audit Events (max)")
GET "https://{{WEBEXAPI}}/adminAudit/events"
"Authorization": "Bearer {{access_token}}"
? "orgId"= "{{_organization}}"
? "from"= "{{_yesterday}}"
? "to"= "{{_now}}"
? "max"= "5"



