#!/usr/bin/env dothttp

@name("Get Time Comparation v2")
GET "https://{{sb_client}}.salesboard.biz/v2/tablet-dashboard"
"XREQUESTEDWITH": "mobileHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? 'filters'= '{"ID_Team":68,"ID_User":1151,"period":{"startDate":1549411200000,"endDate":1549411200000},"compareTo":{"type":"period","startDate":1549324800000,"endDate":1549324800000}}'


@name("POST Time Comparation v2")
POST "https://{{sb_client}}.salesboard.biz/v2/tablet-dashboard"
"XREQUESTEDWITH": "mobileHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"




