#!/usr/bin/env dothttp

// Returns a list of jobs with a word in the description and locaiton.
@name("GitHub Jobs")
GET "https://jobs.github.com/positions.json"
? "description"= "api"
? "location"= "new+york"



