#!/usr/bin/env dothttp

// This example uses a holiday web service to query which holidays occur in the month of November.
@name("Holiday web service")
POST "http://www.holidaywebservice.com/HolidayService_v2/HolidayService2.asmx"
"Content-Type": "text/xml"
data('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hs="http://www.holidaywebservice.com/HolidayService_v2/">
 <soapenv:Body>
     <hs:GetHolidaysForMonth>
        <hs:year>2018</hs:year>
        <hs:countryCode>UnitedStates</hs:countryCode>
        <hs:month>11</hs:month>
     </hs:GetHolidaysForMonth>
 </soapenv:Body>
</soapenv:Envelope>')



