#!/usr/bin/env dothttp

@name("Opportunity Share")
GET "https://{{host}}/services/data/v47.0/sobjects/OpportunityShare/"


@name("Opportunity Share Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/OpportunityShare/{ID}/"


@name("Describe Opportunity Share")
GET "https://{{host}}/services/data/v47.0/sobjects/OpportunityShare/describe/"



