#!/usr/bin/env dothttp

@name("Case Team Role")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamRole/"


@name("Case Team Role Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamRole/{ID}/"


@name("Describe Case Team Role")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamRole/describe/"



