#!/usr/bin/env dothttp

@name("Lead")
GET "https://{{host}}/services/data/v47.0/sobjects/Lead/"


@name("Lead Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Lead/{ID}/"


@name("Describe Lead")
GET "https://{{host}}/services/data/v47.0/sobjects/Lead/describe/"



