#!/usr/bin/env dothttp

@name("Event Change Event")
GET "https://{{host}}/services/data/v47.0/sobjects/EventChangeEvent/"


@name("Event Change Event Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/EventChangeEvent/{ID}/"


@name("Describe Event Change Event")
GET "https://{{host}}/services/data/v47.0/sobjects/EventChangeEvent/describe/"



