#!/usr/bin/env dothttp

// Rota para carregar todos casos da ONG

@name("Profile")
GET "https://be-the-hero-api-backend.herokuapp.com/profile"
"Authorization": "4a9a350a"


@name("Login")
POST "https://be-the-hero-api-backend.herokuapp.com/sessions"
"Content-Type": "application/json"
json({
    "id": "4a9a350a"
})



