#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List repository issues")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/issues"
? "milestone"= "aliqua consectetur elit incididu"
? "state"= "open"
? "assignee"= "aliqua consectetur elit incididu"
? "creator"= "aliqua consectetur elit incididu"
? "mentioned"= "aliqua consectetur elit incididu"
? "labels"= "aliqua consectetur elit incididu"
? "sort"= "created"
? "direction"= "desc"
? "since"= "aliqua consectetur elit incididu"
? "per_page"= "30"
? "page"= "1"


@name("Create an issue")
POST "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/issues"
"Content-Type": "application/json"
json({
    "title": "Found a bug",
    "body": "I'm having a problem with this.",
    "assignees": [
        "octocat"
    ],
    "milestone": 1,
    "labels": [
        "bug"
    ]
})



