#!/usr/bin/env dothttp

@name("/wc/v3/orders/:order_id/notes/:id")
GET "https://{{baseUrl}}/wc/v3/orders/:order_id/notes/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "context"= "view"
? "context"= "view"


@name("/wc/v3/orders/:order_id/notes/:id")
DELETE "https://{{baseUrl}}/wc/v3/orders/:order_id/notes/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "force"= "<string>"



