#!/usr/bin/env dothttp

// The metadata includes the dimension and measure that are part of the calculated insight.
// 
// 
// https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_insights_meta_ci_name.htm

@name("Metadata")
GET "https://{{dne_c360OffcoreUrl}}/api/v1/profile/metadata"



// Returns the metadata for the data model object. Metadata includes the list of fields, data types and indexes available for lookup.
// 
// https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_profile_meta_dmname.htm

@name("Metadata - DMO")
GET "https://{{dne_c360OffcoreUrl}}/api/v1/profile/metadata/Individual__dlm"



// Returns data model objects based on search indexes and filters. Use this API call to retrieve the object record based on the primary key or secondary keys. Returns an empty list when records are not found.
// 
// 
// https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_profile_dmname_id.htm

@name("DMO - By ID")
GET "https://{{dne_c360OffcoreUrl}}/api/v1/profile/Individual__dlm/0033u000013rWpQAAU"
? "fields"= "Id__c,FirstName__c,LastName__c,Preferred_Channel__c,Address_State_Prov__c"
? "limit"= "100"
? "filters"= "[Address_State_Prov__c=AR,Preferred_Channel__c=SMS]"



// Returns data model objects based on search indexes and filters. Use this API call to retrieve the object record based on the primary key or secondary keys. Returns an empty list when records are not found.
// 
// 
// https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_profile_dmname_id.htm

@name("DMO - By Search Key")
GET "https://{{dne_c360OffcoreUrl}}/api/v1/profile/Individual__dlm/Conway"
? "searchKey"= "Address_City__c"
? "fields"= "Id__c,FirstName__c,LastName__c,Preferred_Channel__c,Address_State_Prov__c,Account_Manager__c"
? "limit"= "100"
? "filters"= "[Address_State_Prov__c=AR,Account_Manager__c=Justin Chen]"



// Returns data model objects based on search filters. Use this API call to retrieve the object records after applying the selected filter(s).
// 
// https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_profile_dmname.htm

@name("DMO")
GET "https://{{dne_c360OffcoreUrl}}/api/v1/profile/Individual__dlm"
? "fields"= "Id__c,FirstName__c,LastName__c,Preferred_Channel__c,Address_State_Prov__c"
? "limit"= "100"
? "filters"= "[Address_State_Prov__c=AR,Preferred_Channel__c=SMS]"



// Returns data model objects and child objects based on indexes and search filters.
// 
// 
// https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_profile_dmname_id_child_dmname.htm

@name("DMO and Children - By ID")
GET "https://{{dne_c360OffcoreUrl}}/api/v1/profile/UnifiedIndividual__dlm/2d297bce-fb5f-36d9-923d-3ce3641937e9/UnifiedContactPointEmail__dlm"
? "fields"= "Id__c,EmailDomain__c,PrimaryFlag__c,PartyId__c,EmailAddress__c"
? "limit"= "10"
? "filters"= "[FirstName__c=Aaron]"



// Returns data model objects and child objects based on indexes and search filters.
// 
// 
// https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_profile_dmname_id_child_dmname.htm

@name("DMO and Children - By Search Key")
GET "https://{{dne_c360OffcoreUrl}}/api/v1/profile/UnifiedIndividual__dlm/Conway/UnifiedContactPointEmail__dlm"
? "searchKey"= "Address_City__c"
? "fields"= "Id__c"
? "limit"= "10"
? "filters"= "[Address_State_Prov__c=AR]"



// Returns data model objects and a computed view based on indexes and search filters.
// 
// 
// https://developer.salesforce.com/docs/atlas.en-us.c360a_api.meta/c360a_api/c360a_api_profile_dmname_id_ci_ci_name.htm

@name("DMO and Calculated Insight - By ID")
GET "https://{{dne_c360OffcoreUrl}}/api/v1/profile/Individual__dlm/0033u00000yvqdoAAA/calculated-insights/Service_Cases__cio"
? "dimensions"= "IndividualId__c,CaseType__c,CaseStatus__c,CaseDay__c"
? "limit"= "10"
? "filters"= "[Address_State_Prov__c=ON]"




