#!/usr/bin/env dothttp

@name("Retrieve interfaces from vManage")
GET "https://{{vmanage}}/dataservice/device/interface/synced"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interfaces per VPN")
GET "https://{{vmanage}}/dataservice/device/interface/vpn"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve interfaces ARP statistics")
GET "https://{{vmanage}}/dataservice/device/interface/arp_stats"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interfaces serial ?")
GET "https://{{vmanage}}/dataservice/device/interface/serial"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interface error statistics")
GET "https://{{vmanage}}/dataservice/device/interface/error_stats"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interface packet size statistics")
GET "https://{{vmanage}}/dataservice/device/interface/pkt_size"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interface port statistics")
GET "https://{{vmanage}}/dataservice/device/interface/port_stats"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interface queue statistics")
GET "https://{{vmanage}}/dataservice/device/interface/queue_stats"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interface statistics")
GET "https://{{vmanage}}/dataservice/device/interface/stats"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interface IPv6 statistics")
GET "https://{{vmanage}}/dataservice/device/interface/ipv6Stats"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"


@name("Retrieve interfaces from Device")
GET "https://{{vmanage}}/dataservice/device/interface"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "ifname"= "{{ifName}}"
? "af-type"= "{{afType}}"



