#!/usr/bin/env dothttp

@name("Event Feed")
GET "https://{{host}}/services/data/v47.0/sobjects/EventFeed/"


@name("Event Feed Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/EventFeed/{ID}/"


@name("Describe Event Feed")
GET "https://{{host}}/services/data/v47.0/sobjects/EventFeed/describe/"



