#!/usr/bin/env dothttp

// Creates a new content template. Note, blueprint templates cannot be created via the REST API.
// 
// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
// 'Admin' permission for the space to create a space template or 'Confluence Administrator'
// global permission to create a global template.

@name("Create content template")
POST "https://{{baseUrl}}/api/template"
"Content-Type": "application/json"
json({
    "name": "<string>",
    "templateType": "<string>",
    "body": {
        "storage": {
            "value": "<string>",
            "representation": "<string>"
        }
    },
    "description": "<string>",
    "labels": [
        {
            "prefix": "dolore deserunt ut est anim",
            "name": "occaecat quis culpa ad non",
            "id": "laborum nisi ipsum",
            "label": "labore laborum sint"
        },
        {
            "prefix": "proident tempor",
            "name": "incididunt cupidatat ea",
            "id": "non dolore quis proident",
            "label": "labore sint"
        }
    ],
    "space": {
        "key": "<string>"
    }
})


// Updates a content template. Note, blueprint templates cannot be updated
// via the REST API.
// 
// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
// 'Admin' permission for the space to create a space template or 'Confluence Administrator'
// global permission to create a global template.

@name("Update content template")
PUT "https://{{baseUrl}}/api/template"
"Content-Type": "application/json"
json({
    "templateId": "<string>",
    "name": "<string>",
    "templateType": "<string>",
    "body": {
        "value": "<string>",
        "representation": "<string>"
    },
    "description": "<string>",
    "labels": [
        {
            "prefix": "ipsum dolor Excepteur Duis",
            "name": "nulla et ipsum voluptate consectetur",
            "id": "nostrud enim proident cupidatat eu",
            "label": "enim Lorem veniam amet"
        },
        {
            "prefix": "amet",
            "name": "officia adipisicing ut labo",
            "id": "ipsum in tempor",
            "label": "est occaecat magna"
        }
    ],
    "space": {
        "key": "<string>"
    }
})


// Returns all templates provided by blueprints. Use this method to retrieve
// all global blueprint templates or all blueprint templates in a space.
// 
// Note, all global blueprints are inherited by each space. Space blueprints
// can be customised without affecting the global blueprints.
// 
// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
// Permission to access the Confluence site ('Can use' global permission).

@name("Get blueprint templates")
GET "https://{{baseUrl}}/api/template/blueprint"
? "spaceKey"= "<string>"
? "start"= "0"
? "limit"= "25"
? "expand"= "<string>"
? "expand"= "<string>"


// Returns all content templates. Use this method to retrieve all global
// content templates or all content templates in a space.
// 
// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
// 'Admin' permission for the space to view space templates and 'Confluence
// Administrator' global permission to view global templates.

@name("Get content templates")
GET "https://{{baseUrl}}/api/template/page"
? "spaceKey"= "<string>"
? "start"= "0"
? "limit"= "25"
? "expand"= "<string>"
? "expand"= "<string>"



