#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Selected Time Tracking Provider")
GET "{{baseUrl}}/rest/api/3/configuration/timetracking"


@name("Select Time Tracking Provider")
PUT "{{baseUrl}}/rest/api/3/configuration/timetracking"
"Content-Type": "application/json"
data('{
    "key": "<string>",
    "name": "<string>"
}')


@name("Get All Time Tracking Providers")
GET "{{baseUrl}}/rest/api/3/configuration/timetracking/list"



