#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get All Permissions")
GET "{{baseUrl}}/rest/api/3/permissions"


@name("Get Bulk Permissions")
POST "{{baseUrl}}/rest/api/3/permissions/check"
"Content-Type": "application/json"
data('{
    "projectPermissions": [
        {
            "permissions": [
                "<string>"
            ],
            "issues": [
                "<long>"
            ],
            "projects": [
                "<long>"
            ]
        }
    ],
    "globalPermissions": [
        "<string>"
    ],
    "accountId": "<string>"
}')


@name("Get Permitted Projects")
POST "{{baseUrl}}/rest/api/3/permissions/project"
"Content-Type": "application/json"
data('{
    "permissions": [
        "<string>",
        "<string>"
    ]
}')



