#!/usr/bin/env dothttp

// Get list of Shipments

@name("List Shipments")
GET "https://{{baseUrl}}/v1/shipments"
"API-Key": "{{API_KEY}}"


// Create one or multiple shipments.

@name("Create Shipments")
POST "https://{{baseUrl}}/v1/shipments"
"API-Key": "{{API_KEY}}"
"Content-Type": "application/json"



// Query Shipments created using your own custom ID convention using this endpint

@name("Get Shipment By External ID")
GET "https://{{baseUrl}}/v1/shipments/external_shipment_id/:external_shipment_id"
"API-Key": "{{API_KEY}}"


// The shipment-recognition API makes it easy for you to extract shipping data from unstructured text, including people's names, addresses, package weights and dimensions, insurance and delivery requirements, and more.
// 
// Data often enters your system as unstructured text (for example: emails, SMS messages, support tickets, or other documents). ShipEngine's shipment-recognition API helps you extract meaningful, structured data from this unstructured text. The parsed shipment data is returned in the same structure that's used for other ShipEngine APIs, so you can easily use the parsed data to create a shipping label.
// 
// > **Note:** Shipment recognition is currently supported for the United States, Canada, Australia, New Zealand, the United Kingdom, and Ireland.

@name("Parse shipping info")
PUT "https://{{baseUrl}}/v1/shipments/recognize"
"API-Key": "{{API_KEY}}"
"Content-Type": "application/json"
json({
    "text": "I have a 4oz package that's 5x10x14in, and I need to ship it to Margie McMiller at 3800 North Lamar suite 200 in austin, tx 78652. Please send it via USPS first class and require an adult signature. It also needs to be insured for $400.
"
})



