#!/usr/bin/env dothttp

# imported from http://0.0.0.0:8000/Salesforce_APIs.postman_collection.json

@name("Get Record Data and Object Metadata")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/record-ui/:RECORD_IDS"


@name("Get Record Layout Metadata")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/layout/:SOBJECT_API_NAME"


@name("Get a Directory of Supported Objects")
GET "{{_endpoint}}/services/data/v{{version}}/ui-api/object-info"


@name("Get Object Metadata")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/object-info/:SOBJECT_API_NAME"


@name("Get Values for a Picklist Field")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/object-info/:SOBJECT_API_NAME/picklist-values/:RECORD_TYPE_ID/:FIELD_API_NAME"


@name("Get Values for All Picklist Fields of a Record Type")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/object-info/:SOBJECT_API_NAME/picklist-values/:RECORD_TYPE_ID"


@name("Get Child Records")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/records/:RECORD_ID/child-relationships/:RELATIONSHIP_NAME
"


@name("Get a Record")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/records/:RECORD_ID"


@name("Get a Batch of Records")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/records/batch/:RECORD_IDS"


@name("Create a Record")
POST "{{_endpoint}}/services/data/v{{version}}/ui-api/records"
"Content-Type": "application/json"
data('{
    "allowSaveOnDuplicate": false,
    "apiName": "Object",
    "fields": {
        "FieldAPIName": "FieldValue"
    }
}')


@name("Get Default Values to Clone a Record")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/record-defaults/clone/:RECORD_ID"



@name("Get Default Values to Create a Record")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/record-defaults/create/:RECORD_ID"



@name("Update a Record")
PATCH "None://{{_endpoint}}/services/data/v{{version}}/ui-api/records/:RECORD_ID"
"Content-Type": "application/json"
data('{
    "allowSaveOnDuplicate": false,
    "apiName": "Object",
    "fields": {
        "FieldAPIName": "FieldValue"
    }
}')


@name("Delete a Record")
DELETE "None://{{_endpoint}}/services/data/v{{version}}/ui-api/records/:RECORD_ID"



@name("Get Lookup Field Suggestions")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/lookups/:SOBJECT_API_NAME/:FIELD_API_NAME"



@name("Get Lookup Field Suggestions for a Specified Object")
GET "None://{{_endpoint}}/services/data/v{{version}}/ui-api/lookups/:SOBJECT_API_NAME/:FIELD_API_NAME/:TARGET_API_NAME"




