#!/usr/bin/env dothttp

// This endpoint returns details about the Tweet specified by the requested ID.
// 
// For full details, see the [API reference](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id) for this endpoint.

@name("Single Tweet")
GET "https://api.twitter.com/2/tweets/:id"


// This endpoint returns details about the Tweet specified by the requested ID.
// 
// For full details, see the [API reference](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id) for this endpoint.

@name("Single Tweet Usercontext")
GET "https://api.twitter.com/2/tweets/:id"


// This endpoint returns details about up to 100 Tweets specified by the requested IDs. 
// 
// For full details, see the [API reference](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets) for this endpoint.

@name("Multiple Tweets")
GET "https://api.twitter.com/2/tweets"



