#!/usr/bin/env dothttp

@name("Login")
POST "https://apis.rmlconnect.net/auth/v1/login/"
"Content-Type": "application/json"
json({
    "username": "{username}",
    "password": "{password}"
})


@name("Capability check")
POST "https://apis.rmlconnect.net/wba/v1/contacts"
"Authorization": "{token}"
data('{
    "contacts":["<NUM1>","<NUM2>",...,"NUM50">]
}')



