#!/usr/bin/env dothttp

@name("accounts/:account_id/cards/poll")
GET "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/cards/poll"


@name("accounts/:account_id/cards/poll/:card_id")
GET "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/cards/poll/:card_id"


@name("accounts/:account_id/cards/poll")
POST "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/cards/poll"


@name("accounts/:account_id/cards/poll/:card_id")
DELETE "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/cards/poll/:card_id"



