#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Check Issues Against Jql")
POST "{{baseUrl}}/rest/api/3/jql/match"
"Content-Type": "application/json"
data('{
    "issueIds": [
        "<long>"
    ],
    "jqls": [
        "<string>",
        "<string>"
    ]
}')


@name("Parse Jql Query")
POST "None://{{baseUrl}}/rest/api/3/jql/parse"
"Content-Type": "application/json"
? "validation"= "strict"
data('{
    "queries": [
        "<string>",
        "<string>"
    ]
}')


@name("Convert User Identifiers To Account Ids In Jql Queries")
POST "{{baseUrl}}/rest/api/3/jql/pdcleaner"
"Content-Type": "application/json"
data('{
    "queryStrings": [
        "<string>",
        "<string>"
    ]
}')



