#!/usr/bin/env dothttp

// Returns a list of all templates in the user's account.

@name("Get all Templates")
GET "https://api.dns.constellix.com/v1/templates"
"Content-Type": "application/json"
"x-cns-security-token": "{{x-cns-security-token}}"
? "offset"= "0"
? "max"= "10"
? "sort"= "name"
? "order"= "asc"


// Creates one or more new templates in the user's account.

@name("Create a Template")
POST "https://api.dns.constellix.com/v1/templates/"
"Content-Type": "application/json"
"x-cns-security-token": "{{x-cns-security-token}}"
data('[
  {
    "name": "sampleTemplate3",
  }
]')


// Returns an existing template with the given ID.

@name("Get an Existing Template")
GET "https://api.dns.constellix.com/v1/templates/547"
"Content-Type": "application/json"
"x-cns-security-token": "{{x-cns-security-token}}"
files(
	("id", "{{id1}}")
)


// Updates an existing template in the user's account.
// 
// <table class="confluenceTable">
//   <colgroup>
//     <col>
//     <col>
//     <col>
//   </colgroup>
//   <tbody>
//     <tr>
//       <td class="confluenceTd">
//         <p><span style="color: rgb(0,0,0);" data-mce-style="color: #000000;"><strong><span style="text-decoration: none;" data-mce-style="text-decoration: none;">Field </span></strong></span></p>
//       </td>
//       <td class="confluenceTd">
//         <p><span style="color: rgb(0,0,0);" data-mce-style="color: #000000;"><strong><span style="text-decoration: none;" data-mce-style="text-decoration: none;">Type</span></strong></span></p>
//       </td>
//       <td class="confluenceTd">
//         <p><span style="color: rgb(0,0,0);" data-mce-style="color: #000000;"><strong><span style="text-decoration: none;" data-mce-style="text-decoration: none;">Description</span></strong></span></p>
//       </td>
//     </tr>
//     <tr>
//       <td class="confluenceTd">
//         <p><span style="color: rgb(51,51,51);text-decoration: none;" data-mce-style="color: #333333; text-decoration: none;">name <strong><span style="text-decoration: none;color: rgb(255,0,0);" data-mce-style="text-decoration: none; color: #ff0000;">*</span><span style="text-decoration: none;" data-mce-style="text-decoration: none;">&nbsp;</span></strong></span></p>
//       </td>
//       <td class="confluenceTd">
//         <p><span style="color: rgb(51,51,51);text-decoration: none;" data-mce-style="color: #333333; text-decoration: none;">String[]</span></p>
//       </td>
//       <td class="confluenceTd">
//         <p><span style="color: rgb(51,51,51);text-decoration: none;" data-mce-style="color: #333333; text-decoration: none;">Template names</span></p>
//       </td>
//     </tr>
//   </tbody>
// </table>

@name("Update an Existing Template")
PUT "https://api.dns.constellix.com/v1/templates/547"
"Content-Type": "application/json"
"x-cns-security-token": "{{x-cns-security-token}}"
data('
    {
      "hasGtdRegions": true,
      "hasGeoIP": false
    }')


// Deletes a template.

@name("Delete an Existing Template")
DELETE "https://api.dns.constellix.com/v1/templates/549"
"Content-Type": "application/json"
"x-cns-security-token": "{{x-cns-security-token}}"




