#!/usr/bin/env dothttp

// Creates a recurring application charge

@name("Creates a recurring application charge")
POST "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/recurring_application_charges.json"
"Content-Type": "application/json"



// Retrieves a single charge

@name("Retrieves a single charge")
GET "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/recurring_application_charges/{{recurring_application_charge_id}}.json"
"Content-Type": "application/json"


// Retrieves a list of recurring application charges

@name("Retrieves a list of recurring application charges")
GET "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/recurring_application_charges.json"
"Content-Type": "application/json"


// Activates a previously accepted recurring application charge

@name("Activates a recurring application charge")
POST "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/recurring_application_charges/{{recurring_application_charge_id}}/activate.json"
"Content-Type": "application/json"



// Cancels a recurring application charge

@name("Cancels a recurring application charge")
DELETE "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/recurring_application_charges/{{recurring_application_charge_id}}.json"
"Content-Type": "application/json"



// Updates the capped amount of an active recurring application charge

@name("Updates the capped amount of a recurring application charge")
PUT "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/recurring_application_charges/{{recurring_application_charge_id}}/customize.json"
"Content-Type": "application/json"




