#!/usr/bin/env dothttp

//  #### Response Parameter
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// id|string|id of the zone
// name|string|name of the zone
// map_id|string|map_id of the zone
// sdkclient_waits|object|sdkclient wait time right now
// client_waits|object|client wait time right now
// asset_waits|object|ble asset wait time right now
// num_assets|int|number of assets
// num_clients|int|number of wifi clients (unconnected + connected)
// num_sdkclients|int|number of sdk clients
// max|int|longest wait time in seconds
// min|int|shortest wait time in seconds
// avg|int|average wait time in seconds
// p95|int|95th percentile of all the wait time(s)

@name("getSiteZoneStats")
GET "https://{{host}}/api/v1/sites/:site_id/stats/zones"
? "map_id"= "{{map_id}}"


//  #### Response Parameter
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
//  id|string|id of the zone
//  name|string|name of the zone
//  map_id|string|map_id of the zone
//  sdkclient_waits|object|sdkclient wait time right now
//  client_waits|object|client wait time right now
//  sdkclients|list|list of sdkclients currently in the zone and when they entered
//  clients|list|list of clients currently in the zone and when they entered
//  assets|list|list of ble assets currently in the zone and when they entered
//  max|int|longest wait time in seconds
//  min|int|shortest wait time in seconds
//  avg|int|average wait time in seconds
//  p95|int|95th percentile of all the wait time(s)

@name("getSiteZoneStatsDetails")
GET "https://{{host}}/api/v1/sites/:site_id/stats/:zone_type/:zone_id"


//  #### Query Parameter
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
//  user_type|string|user type, client (default) / sdkclient / asset
//  user|string|client MAC / Asset MAC / SDK UUID
//  scope_id|string|if scope == map/zone/rssizone, the scope id
//  scope|string|scope, site (default) / map / zone / rssizone
//  tags|string|tags

@name("searchSiteZoneSessions")
GET "https://{{host}}/api/v1/sites/:site_id/:zone_type/visits/search"
? "user_type"= "{{user_type}}"
? "scope_id"= "{{scope_id}}"


//  #### Query Parameter
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
//  ser_type|string|user type, client (default) / sdkclient / asset
//  user|string|client MAC / Asset MAC / SDK UUID
//  scope_id|string|if scope == map/zone/rssizone, the scope id
//  scope|string|scope, site (default) / map / zone / rssizone

@name("countSiteZoneSessions")
GET "https://{{host}}/api/v1/sites/:site_id/:zone_type/count"
? "distinct"= "scope_id"



