#!/usr/bin/env dothttp

@name("Undecided Event Relation")
GET "https://{{host}}/services/data/v47.0/sobjects/UndecidedEventRelation/"


@name("Undecided Event Relation Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/UndecidedEventRelation/{ID}/"


@name("Describe Undecided Event Relation")
GET "https://{{host}}/services/data/v47.0/sobjects/UndecidedEventRelation/describe/"



