#!/usr/bin/env dothttp

@name("Example of New Merchant")
VIEW "https://<your registered webhook url>/"
"Content-Type": "application/json"
"X-Signature": "<HMAC SHA256 signature of body>"
data('{
    "network_merchant_id": "the-network-merchant-mid"
}')


@name("Example of Transaction Matched")
VIEW "https://<your registered webhook url>/"
"Content-Type": "application/json"
"X-Signature": "<HMAC SHA256 signature of body>"
data('{
    "matched_transaction": {
        "transaction": "725b17862a5289489dcaeb26dab749810146",
        "consumer": "C-X-123",
        "receipt": "R-X-123",
        "receipt_type": "smart"
    }
}')



