#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Share Permission")
GET "https://{{baseUrl}}/rest/api/3/filter/:id/permission/:permissionId"


@name("Delete Share Permission")
DELETE "https://{{baseUrl}}/rest/api/3/filter/:id/permission/:permissionId"



