#!/usr/bin/env dothttp

// List all the scenes available, regardless of the parent groups.

@name("List Scenes")
GET "https://{{address}}{{apiBasePath}}/scenes/"
"Authorization": "Bearer {{access_token}}"



// Get a particular scene by it's Id.  A scene contains it's parent Group.

@name("Get Scene")
GET "https://{{address}}{{apiBasePath}}/scenes/{{scene_id}}"
"Authorization": "Bearer {{access_token}}"



// Recall a specific scene on the gateway.

@name("Apply Scene")
PATCH "https://{{address}}{{apiBasePath}}/scenes/{{scene_id}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{access_token}}"
data('{
  "action": "apply"
}')



