#!/usr/bin/env dothttp

@name("Sweden")
POST "https://resttest.datazoo.com/api/Global/Verify.json"
data('{
    "dataSources": [
        "Global All"
    ],
    "reportingReference": "abcd1234",
    "country": "SE",
    "idCardNo": "7810105333",
    "firstName": "ALBERT",
    "middleName": null,
    "lastName": "OLSSON",
    "paternalName":null,
    "maternalName":null,
    "dateOfBirth":"1978-10-10",
    "unitNo":null, 
    "streetNo": "10",
    "streetName":"TRADSGARDSGATAN",
    "district":null,
    "city": "NORRKOPING",
    "province":null,
    "postCode":"60242",
    "phoneNo":"705746889",
    "emailAddress":null,
    "GlobalAllConsentObtained":false
}
')



