#!/usr/bin/env dothttp

// 获得系统所有的关注列表

@name("getAllFocus")
GET "https://{{url}}/api/v1/focus/all"


// 获得一个id的关注列表
// 
// **参数**
// - id: 表示`Foucs的`主键（需要加在请求链接里）

@name("getOneFocus")
GET "https://{{url}}/api/v1/focus/4"


// 新增一个关注列表

@name("creatOneFocus")
POST "https://{{url}}/api/v1/focus"
files(
	("userID", "6"),
	("focusUserID", "1")
)


// 通过用户帐号，新增一个关注列表

@name("FocusByAccount")
POST "https://{{url}}/api/v1/focus/account"
files(
	("userID", "6"),
	("account", "17759132743")
)


// 删除一个关注id
// 
// **参数**
// - id: 表示`Foucs`的主键（需要加在请求链接里）

@name("deleteOneFocus")
DELETE "https://{{url}}/api/v1/focus/id"



// 删除一个关注信息
// 
// **参数**
// - userID: 表示`关注者`的主键
// - focusUserID: 表示`被关注者`的主键

@name("deleteOneFocusByUserID")
DELETE "https://{{url}}/api/v1/focus/id"
files(
	("userID", "1"),
	("focusUserID", "2")
)


// 获得所有的用户信息（按照姓名排列）

@name("getAllFocusSortByTime")
GET "https://{{url}}/api/v1/focus/sort"



