#!/usr/bin/env dothttp

// REST API Index

@name("http://localhost:8000")
GET "http://localhost/"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"



// Register a new user in the database

@name("http://localhost:8000/v1/auth/register")
POST "http://localhost/v1/auth/register"
"Content-Type": "application/json"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"
data('{
	"first_name": "Fru",
	"last_name": "Kerick",
	"email": "frukerickjeff@gmail.com",
	"password": "secret23",
	"password_confirmation": "secret23"
}')


// Authenticate a user by its email and password

@name("http://localhost:8000/v1/auth/login")
POST "http://localhost/v1/auth/login"
"Content-Type": "application/json"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"
data('{
	"email": "frukerickjeff@gmail.com",
	"password": "secret23"
}')


// Save a post in the database. Requires authenticated.

@name("http://localhost:8000/v1/posts/")
POST "http://localhost/v1/posts/"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"
"Content-Type": "application/json"
"Authorization": "Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3N1ZXIiOiJzaW1wbGUtand0IiwiaWQiOjEyLCJpc3N1ZWRfYXQiOjE1NTIzNDY4NzMsImV4cGlyZXMiOjE1NTI0MzMyNzN9.iYC5eScdYP4sgYQBCAhxdfx0uqIhHEj0JV9Mqqj4WZY"
data('{
	"user_id": 12,
	"title": "Post Title",
	"description": "Post description..."
}')


// Retrieve all posts from the database

@name("http://localhost:8000/v1/posts?limit={limit}&page={page}")
GET "http://localhost/v1/posts"
"x-api-key": "rpEEbYoWLacQ0uNCqL21efTUL8LVI0PQ3IFdDvijno2gg8GO1GpTPuVKok2AKiSf"
? "limit"= "1"
? "page"= "2"



// Retrieve a single post from the database by its ID

@name("http://localhost:8000/v1/posts/{id}")
GET "http://localhost/v1/posts/5"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"



// Retrieve a single post from the database by its slug

@name("http://localhost:8000/v1/posts/{slug}")
GET "http://localhost/v1/posts/post-title"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"



// Update a post in the database. Requires authenticated. Only the user who created the post is authorized to perform this action.

@name("http://localhost:8000/v1/posts/{id}")
PUT "http://localhost/v1/posts/6"
"Content-Type": "application/json"
"Authorization": "Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3N1ZXIiOiJzaW1wbGUtand0IiwiaWQiOjEyLCJpc3N1ZWRfYXQiOjE1NTIzNDY4NzMsImV4cGlyZXMiOjE1NTI0MzMyNzN9.iYC5eScdYP4sgYQBCAhxdfx0uqIhHEj0JV9Mqqj4WZY"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"
data('{
	"title": "Post Title Changed",
	"description": "Post description changed"
}')


// Delete a post from the database. Requires authenticated. Only the user who created the post is authorized to perform this action.

@name("http://localhost:8000/v1/posts/{id}")
DELETE "http://localhost/v1/posts/6"
"Authorization": "Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3N1ZXIiOiJzaW1wbGUtand0IiwiaWQiOjEyLCJpc3N1ZWRfYXQiOjE1NTIzNDY4NzMsImV4cGlyZXMiOjE1NTI0MzMyNzN9.iYC5eScdYP4sgYQBCAhxdfx0uqIhHEj0JV9Mqqj4WZY"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"



// Retrieve all users from the database

@name("http://localhost:8000/v1/users?limit={limit}&page={page}")
GET "http://localhost/v1/users"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"
? "limit"= "2"
? "page"= "3"



// Retrieve a single user from the database by its ID

@name("http://localhost:8000/v1/users/{id}")
GET "http://localhost/v1/users/12"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"



// Retrieve a single user from the database by its slug

@name("http://localhost:8000/v1/users/{slug}")
GET "http://localhost/v1/users/fru-kerick-3"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"



// Update a user record in the datatabase. Requires authentication. User is only authorized to update his/her details.

@name("http://localhost:8000/v1/users/update")
PUT "http://localhost/v1/users/update"
"Content-Type": "application/json"
"Authorization": "Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3N1ZXIiOiJzaW1wbGUtand0IiwiaWQiOjEyLCJpc3N1ZWRfYXQiOjE1NTIzNDY4NzMsImV4cGlyZXMiOjE1NTI0MzMyNzN9.iYC5eScdYP4sgYQBCAhxdfx0uqIhHEj0JV9Mqqj4WZY"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"
data('{
	"last_name": "k3r1ck",
	"email": "fru@k3r1ck.com"
}')


// Delete a user record in the datatabase. Requires authentication. User is only authorized to delete his/her details.

@name("http://localhost:8000/v1/users/delete")
DELETE "http://localhost/v1/users/delete"
"Authorization": "Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3N1ZXIiOiJzaW1wbGUtand0IiwiaWQiOjE3LCJpc3N1ZWRfYXQiOjE1NTI0MzU3MjgsImV4cGlyZXMiOjE1NTI1MjIxMjh9.RhPDxlqiXPsS7g_7H0ANqSPQbZvrofFej6r6raQwXIU"
"x-api-key": "OfJr4qriSrw7iZMpaWJm4OOrjGdfCgzrMQvTUkx7quaejgyokYy95yhnpjaLoiBT"




