#!/usr/bin/env dothttp

// OAuth required scopes: OR.Settings or OR.Settings.Read.
// 
// Required permissions: Settings.View.

@name("Gets a settings value based on its key.")
GET "https://{{baseUrl}}/odata/Settings('{{key}}')"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"


// OAuth required scopes: OR.Settings or OR.Settings.Write.
// 
// Required permissions: Settings.Edit.

@name("Edits a setting.")
PUT "https://{{baseUrl}}/odata/Settings('{{key}}')"
"Content-Type": "application/json"
json({
    "Name": "veniam dolor pariatur sed",
    "Value": "occaecat elit dolore et",
    "Scope": "Application",
    "Id": "amet ad"
})



