#!/usr/bin/env dothttp

// Get all champion mastery entries sorted by number of champion points descending.

@name("All Masteries by Summoner ID")
GET "https://{{URL}}/lol/champion-mastery/v4/champion-masteries/by-summoner/:Encrypted Summoner ID"


// Get a champion mastery by player ID and champion ID.

@name("Champion Mastery by Summoner ID and Champion ID")
GET "https://{{URL}}/lol/champion-mastery/v4/champion-masteries/by-summoner/:Encrypted Summoner ID/by-champion/:Champion ID"


// Get a player's total champion mastery score, which is the sum of individual champion mastery levels.

@name("Total Mastery by Summoner ID")
GET "https://{{URL}}/lol/champion-mastery/v4/scores/by-summoner/:Encrypted Summoner ID"



