#!/usr/bin/env dothttp

@name("Login")
POST "https://login.salesforce.com/services/oauth2/token"
? "grant_type"= "password"
? "client_id"= "3MVG9A2kN3Bn17httEK2ANzDHyzAgnOB77TRv6_aIbmY2RABqZactM9kAHuUQ1RSy3x.I8c5PrYlP6MOKrjnv"
? "client_secret"= "7333070224220149636"
? "username"= "vs-integracion-sf@security.cl"
? "password"= "vS*s.1nt3.fNhiec99cmNWZpkAfuCC0Qcqvu"


@name("CrearJob")
POST "https://vidasecurity.my.salesforce.com/services/async/46.0/job"
"X-SFDC-Session": "00Di0000000XoSJ!AQ8AQLSm9bbIox86FFUB0JNeWfv.OsPyQ1TfYtE20.Pbta2XLOjvlICP0UR1oVZrkPylP2qprEzrTFaW.MTV9.IWjtOrfgOR"
"Content-Type": "application/json"
json({
    "operation": "upsert",
    "object": "Poliza__c",
    "externalIdFieldName": "N_Poliza__c",
    "contentType": "JSON"
})


@name("CrearBatch")
POST "https://vidasecurity.my.salesforce.com/services/async/46.0/job/7500H00000QMTZTQA5/batch"
"X-SFDC-Session": "00Di0000000XoSJ!AQ8AQLSm9bbIox86FFUB0JNeWfv.OsPyQ1TfYtE20.Pbta2XLOjvlICP0UR1oVZrkPylP2qprEzrTFaW.MTV9.IWjtOrfgOR"
"Content-Type": "application/json"
json([
    {
        "IDVS__c": "105832273",
        "Agente__c": null,
        "Apellidos_Asegurado__c": "GONZALEZ GUTIERREZ",
        "Codigo_Agente__c": null,
        "Codigo_de_Producto__c": "9720",
        "Codigo_Ejecutivo__c": "20971",
        "Cuenta__c": "0010n000013LsOaAAK",
        "DV__c": "5",
        "Edad_al_Momento_de_Contratar__c": 39,
        "Ejecutivo_de_Clientes__c": "ANA LUISA ARZOLA HERNANDEZ",
        "Empresa_Origen__c": "Vida Security",
        "Estatus__c": "ACTIVA",
        "Fecha_Entrega_de_la_Poliza__c": "2012-08-01",
        "Fecha_Sometimiento__c": "2012-08-01",
        "Forma_de_Pago__c": "DIRECTO",
        "Frecuencia_de_Pago__c": "M",
        "IdPoliza__c": "16066419",
        "Modalidad_APV__c": "N",
        "Moneda_Poliza__c": "UF",
        "N_Poliza__c": "5582853",
        "Name": "5582853",
        "Nombre_Asegurado__c": "CARLA VERONICA",
        "Nombre_de_Producto__c": "57 MAX 2.0.",
        "Prima_Total__c": "2.5",
        "Prima_Adicional__c": "0",
        "Prima_en_Exceso__c": ".1158",
        "Prima_Minima__c": "2.3842",
        "Rut_Asegurado__c": "10581511",
        "Sucursal_Ejecutivo_de_Clientes__c": "LYON (IND)",
        "Valor_Poliza__c": "34.409",
        "Fecha_Inicio_de_Poliza__c": "2012-07-30",
        "Fecha_Termino_de_Poliza__c": "2020-07-31",
        "Fecha_Ultimo_Pago__c": "2014-08-07",
        "Gerencia_Comerc_y_Cliente__c": "SI",
        "Con_o_Sin_Ahorro__c": "Con Ahorro",
        "Tipo_Producto__c": "57",
        "RecordType": {
            "Name": "Individuales"
        }
    }
])


@name("CerrarJob")
POST "https://vidasecurity.my.salesforce.com/services/async/46.0/job/7500H00000QMTZTQA5"
"Content-Type": "application/json"
"X-SFDC-Session": "00Di0000000XoSJ!AQ8AQLSm9bbIox86FFUB0JNeWfv.OsPyQ1TfYtE20.Pbta2XLOjvlICP0UR1oVZrkPylP2qprEzrTFaW.MTV9.IWjtOrfgOR"
json({
    "state": "Closed"
})


@name("ObtenerBatch")
GET "https://vidasecurity.my.salesforce.com/services/async/46.0/job/7500H00000QMTZTQA5/batch/7510H00000YCxd7QAD"
"Content-Type": "application/json"
"X-SFDC-Session": "00Di0000000XoSJ!AQ8AQLSm9bbIox86FFUB0JNeWfv.OsPyQ1TfYtE20.Pbta2XLOjvlICP0UR1oVZrkPylP2qprEzrTFaW.MTV9.IWjtOrfgOR"


@name("Resultados")
GET "https://vidasecurity.my.salesforce.com/services/async/46.0/job/7500H00000QMTZTQA5/batch/7510H00000YCxd7QAD/result"
"Content-Type": "application/json"
"X-SFDC-Session": "00Di0000000XoSJ!AQ8AQLSm9bbIox86FFUB0JNeWfv.OsPyQ1TfYtE20.Pbta2XLOjvlICP0UR1oVZrkPylP2qprEzrTFaW.MTV9.IWjtOrfgOR"


@name("Poliza")
GET "https://{{host}}/"



