#!/usr/bin/env dothttp

@name("Contact History")
GET "https://{{host}}/services/data/v47.0/sobjects/ContactHistory/"


@name("Contact History Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/ContactHistory/{ID}/"


@name("Describe Contact History")
GET "https://{{host}}/services/data/v47.0/sobjects/ContactHistory/describe/"



