#!/usr/bin/env dothttp

@name("Get Issue Link Types")
GET "https://{{JiraHost}}/rest/api/2/issueLinkType"
basicauth("[JIRA-USERNAME]", "[Token]")


@name("Get Issue Fields")
GET "https://{{JiraHost}}/rest/api/2/search"
basicauth("[JIRA-USERNAME]", "[Token]")
? "jql"= "key=ABC-123"



