#!/usr/bin/env dothttp

@name("V1 - Get List of Articles")
GET "https://{{base_path}}/api/index.php/v1/content/article"
basicauth("{{super_username}}", "{{super_password}}")
"Content-Type": "application/json"


@name("V1 - Get Single Article")
GET "https://{{base_path}}/api/index.php/v1/content/article/6"
basicauth("{{super_username}}", "{{super_password}}")
"Content-Type": "application/json"


@name("V1 - Create an Article")
POST "https://{{base_path}}/api/index.php/v1/content/article"
basicauth("{{super_username}}", "{{super_password}}")
"Content-Type": "application/json"
data('{
    "alias": "my-article-another-one-new",
    "articletext": "My text",
    "catid": 8,
    "language": "*",
    "metadesc": "",
    "metakey": "",
    "title": "Here\'s an article"
}')


@name("V1 - Update an Article")
PATCH "https://{{base_path}}/api/index.php/v1/content/article/10"
basicauth("{{super_username}}", "{{super_password}}")
"Content-Type": "application/json"
data('{
    "catid": 64,
    "title": "Updated article"
}')


@name("V1 - Delete an Article")
DELETE "https://{{base_path}}/api/index.php/v1/content/article/7"
basicauth("{{super_username}}", "{{super_password}}")
"Content-Type": "application/json"




