#!/usr/bin/env dothttp

// Insert client_id and redirect_id - this will form your authorization request URL. Copy it and run it in the browser. Scan the QR-code as a sandbox user with the sandbox app.

@name("Create an authorization request")
POST "https://oauth.sandbox.bunq.com/auth"
"Content-Type": "application/json"
"Cache-Control": "no-cache"
"User-Agent": "postman"
"X-Bunq-Language": "en_US"
"X-Bunq-Region": "nl_NL"
"X-Bunq-Client-Request-Id": "{{request_id}}"
"X-Bunq-Geolocation": "{{geolocation}}"
"X-Bunq-Client-Authentication": "{{session_token}}"
"X-Bunq-Client-Signature": "{{signature}}"
? "response_type"= "code"
data('{
  "currency": "EUR",
  "description": "my first test MA",
  "daily_limit": {
    "value": "100",
    "currency": "EUR"
  },
  "status": "ACTIVE",
  "setting": {
    "default_avatar_status": "AVATAR_DEFAULT",
    "restriction_chat": "ALLOW_INCOMING"
  }
}')


// Insert the parameters to form your token exchange URL. You receive `code` after a user accepts your authorization URL.

@name("Create token exchange")
POST "https://api-oauth.sandbox.bunq.com/v1/token"
"Content-Type": "application/json"
"Cache-Control": "no-cache"
"User-Agent": "postman"
"X-Bunq-Language": "en_US"
"X-Bunq-Region": "nl_NL"
"X-Bunq-Client-Request-Id": "{{request_id}}"
"X-Bunq-Geolocation": "{{geolocation}}"
"X-Bunq-Client-Authentication": "{{session_token}}"
"X-Bunq-Client-Signature": "{{signature}}"
? "grant_type"= "authorization_code"
data('{
  "currency": "EUR",
  "description": "my first test MA",
  "daily_limit": {
    "value": "100",
    "currency": "EUR"
  },
  "status": "ACTIVE",
  "setting": {
    "default_avatar_status": "AVATAR_DEFAULT",
    "restriction_chat": "ALLOW_INCOMING"
  }
}')



