#!/usr/bin/env dothttp

// Retrive carrier info by ID

@name("Get Carrier By ID")
GET "https://{{baseUrl}}/v1/carriers/:carrier_id"
"API-Key": "{{API_KEY}}"


// Add Funds To A Carrier

@name("Add Funds To Carrier")
PUT "https://{{baseUrl}}/v1/carriers/:carrier_id/add_funds"
"API-Key": "{{API_KEY}}"
"Content-Type": "application/json"
data('""')


// Get a list of the options available for the carrier

@name("Get Carrier Options")
GET "https://{{baseUrl}}/v1/carriers/:carrier_id/options"
"API-Key": "{{API_KEY}}"


// List the package types associated with the carrier

@name("List Carrier Package Types")
GET "https://{{baseUrl}}/v1/carriers/:carrier_id/packages"
"API-Key": "{{API_KEY}}"


// List the services associated with the carrier ID

@name("List Carrier Services")
GET "https://{{baseUrl}}/v1/carriers/:carrier_id/services"
"API-Key": "{{API_KEY}}"



