#!/usr/bin/env dothttp

// Delete projects  deploy keys key

@name("Delete Projects  Deploy Keys Key")
DELETE "https://{{baseUrl}}/projects/:id/deploy_keys/:key_id"


// Delete projects  deploy keys key  disable

@name("Delete Projects  Deploy Keys Key  Disable")
DELETE "https://{{baseUrl}}/projects/:id/deploy_keys/:key_id/disable"


// Post projects  deploy keys key  enable

@name("Add Projects  Deploy Keys Key  Enable")
POST "https://{{baseUrl}}/projects/:id/deploy_keys/:key_id/enable"



