#!/usr/bin/env dothttp

// Return the connectivity testing destinations for an MX network
@name("getNetworkConnectivityMonitoringDestinations")
GET "https://{{baseUrl}}/networks/:networkId/connectivityMonitoringDestinations"
"Accept": "*/*"



// Update the connectivity testing destinations for an MX network//  #### Body Parameters // **Parameter**|**Type**|**Description** //  :-------------: |:-------------: |:-------------: // destinations| array| The list of connectivity monitoring destinations
@name("updateNetworkConnectivityMonitoringDestinations")
PUT "https://{{baseUrl}}/networks/:networkId/connectivityMonitoringDestinations"
"Accept": "*/*"
"Content-Type": "application/json"
data('{
  "destinations": [
    {
      "ip": "8.8.8.8",
      "description": "Google",
      "default": false
    },
    {
      "ip": "1.23.45.67",
      "description": "test description",
      "default": true
    },
    {
      "ip": "9.8.7.6"
    }
  ]
}')



