#!/usr/bin/env dothttp

// Lists all of your email addresses, and specifies which one is visible to the public. This endpoint is accessible with the `user:email` scope.

@name("List email addresses for the authenticated user")
GET "https://{{baseUrl}}/user/emails"
? "per_page"= "30"
? "page"= "1"


// This endpoint is accessible with the `user` scope.

@name("Add an email address for the authenticated user")
POST "https://{{baseUrl}}/user/emails"
"Content-Type": "application/json"
json({
    "emails": [
        "<string>",
        "<string>"
    ]
})


// This endpoint is accessible with the `user` scope.

@name("Delete an email address for the authenticated user")
DELETE "https://{{baseUrl}}/user/emails"
"Content-Type": "application/json"
json({
    "emails": [
        "<string>",
        "<string>"
    ]
})



