#!/usr/bin/env dothttp

@name("Membership Information Links Post")
POST "https://{{baseUrl}}/membership/v1/membershipinformationlinks"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "code": [
        "<string>"
    ],
    "html": [
        "<string>"
    ],
    "displayOrder": [
        "<integer>"
    ],
    "membersOnly": [
        "<boolean>"
    ],
    "isActive": [
        "<boolean>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isConfiguration": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})


@name("Membership Information Links Get")
GET "https://{{baseUrl}}/membership/v1/membershipinformationlinks/:tenantid"
"Authorization": "<string>"
? "msql"= "<string>"
? "page"= "<integer>"
? "pageSize"= "<integer>"


@name("Membership Information Links Get")
GET "https://{{baseUrl}}/membership/v1/membershipinformationlinks/description/:tenantid"
"Authorization": "<string>"


@name("Membership Information Links Delete")
DELETE "https://{{baseUrl}}/membership/v1/membershipinformationlinks/delete/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"



