#!/usr/bin/env dothttp

@name("Report")
GET "https://{{host}}/services/data/v47.0/sobjects/Report/"


@name("Report Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Report/{ID}/"


@name("Describe Report")
GET "https://{{host}}/services/data/v47.0/sobjects/Report/describe/"



