#!/usr/bin/env dothttp

@name("/")
POST "https://{{site_url}}/dokan/v1/cart/items"
"Content-Type": "application/json"
"X-Dokan-App": "true"
"X-Dokan-WC-Session": "{{dokan_wc_session}}"
? "dokan_app_token"= "{{customer_token}}"
data('{
	"product_id": {{product_id_1}},
	"quantity": 1
}')


@name("/batch")
PUT "https://{{site_url}}/dokan/v1/cart/items/{{cart_item_key}}"
"Content-Type": "application/json"
data('{
	"quantity": 10
}')


@name("/")
GET "https://{{site_url}}/dokan/v1/cart/items"
"X-Dokan-App": "true"
"X-Dokan-WC-Session": "{{dokan_wc_session}}"
? "dokan_app_token"= "{{customer_token}}"


@name("/{key}")
DELETE "https://{{site_url}}/dokan/v1/cart/items/{{cart_item_key}}"


@name("/{key}/restore")
PUT "https://{{site_url}}/dokan/v1/cart/items/{{cart_item_key}}/restore"


@name("/")
DELETE "https://{{site_url}}/dokan/v1/cart/items"
? "dokan_app_token"= "{{customer_token}}"


@name("/{key}")
PUT "https://{{site_url}}/dokan/v1/cart/items/{{cart_item_key}}"
"Content-Type": "application/json"
"X-Dokan-App": "true"
"X-Dokan-WC-Session": "{{dokan_wc_session}}"
? "dokan_app_token"= "{{customer_token}}"
data('{
	"quantity": 2
}')



