#!/usr/bin/env dothttp

@name("Create a contact for a partner tenant")
POST "https://{{base_url}}/api/2/contacts"
"Content-Type": "application/json"
data('{
    "firstname": "My Name",
    "lastname": "My Last Name",
    "email": "test2@example.com",
    "tenant_id": "{{partner_tenant_id}}",
    "types": [
    "technical"
  ]
}')


@name("Get a partner tenant contacts")
GET "https://{{base_url}}/api/2/tenants/{{partner_tenant_id}}/contacts"


@name("Get a contact for id")
GET "https://{{base_url}}/api/2/contacts/{{contact_id}}"
"Content-Type": "application/json"



