#!/usr/bin/env dothttp

// Get a list of paginated groups.

@name("List contact groups")
GET "https://{{api_url}}/contact-groups"
"Content-Type": "application/json"
"Accept": "application/json"
? "limit"= "15"


// Create a new contact group.

@name("Create a new contact group")
POST "https://{{api_url}}/contact-groups"
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "name": "Some group"
})


// Retrieve a contact group by its slug.

@name("Retrieve a contact group")
GET "https://{{api_url}}/contact-groups/{{contact_group_slug}}"
"Content-Type": "application/json"
"Accept": "application/json"


// Update an existing contact group.

@name("Update a contact group")
PATCH "https://{{api_url}}/contact-groups/{{contact_group_slug}}"
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "description": "Some updated group description",
    "discount_active": true,
    "discount_percentage": 10
})


// Add a contact to a group.

@name("Add contact to group")
POST "https://{{api_url}}/contact-groups/{{contact_group_slug}}/contacts/add"
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "number": 61
})


// Empty a contact group.

@name("Empty a contact group")
POST "https://{{api_url}}/contact-groups/{{contact_group_slug}}/empty"
"Content-Type": "application/json"
"Accept": "application/json"



// Delete a contact group.

@name("Delete a contact group")
DELETE "https://{{api_url}}/contact-groups/{{contact_group_slug}}"
"Content-Type": "application/json"
"Accept": "application/json"




