#!/usr/bin/env dothttp

// This pulls all the tweets for @ACHealthDept and saves them to the environment.

@name("Alamance County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:ACHealthDept"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @HealthAllegheny and saves them to the environment.

@name("Alleghany County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:HealthAllegheny"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @AppDistrictHD and saves them to the environment.

@name("Appalachian District Health Department (AppHealthCare)")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:AppDistrictHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @BCHealthDept and saves them to the environment.

@name("Beaufort County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:BCHealthDept"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @CabarrusHealth and saves them to the environment.

@name("Cabarrus County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:CabarrusHealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @county_caldwell and saves them to the environment.

@name("Caldwell County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:county_caldwell"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @ARHS_NC and saves them to the environment.

@name("Carteret County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:ARHS_NC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @ARHS_NC and saves them to the environment.

@name("Chowan County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:ARHS_NC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @cravencountync and saves them to the environment.

@name("Craven County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:cravencountync"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @DCHealthDept_NC and saves them to the environment.

@name("Davidson County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:DCHealthDept_NC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @DurhamHealthNC and saves them to the environment.

@name("Durham County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:DurhamHealthNC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @gastonhhs and saves them to the environment.

@name("Gaston County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:gastonhhs"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @ARHS_NC and saves them to the environment.

@name("Gates County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:ARHS_NC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @GrahamCoHealth and saves them to the environment.

@name("Graham County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:GrahamCoHealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @Granvillevance3 and saves them to the environment.

@name("Granville County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:Granvillevance3"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @hcphs_nc and saves them to the environment.

@name("Halifax County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:hcphs_nc"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @ARHS_NC and saves them to the environment.

@name("Hertford County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:ARHS_NC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @HokeCoHD and saves them to the environment.

@name("Hoke County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:HokeCoHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @MeckCounty and saves them to the environment.

@name("Mecklenburg County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:MeckCounty"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @mitchell_health and saves them to the environment.

@name("Mitchell County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:mitchell_health"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @mocohealth and saves them to the environment.

@name("Moore County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:mocohealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @nhchealth and saves them to the environment.

@name("New Hanover County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:nhchealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @OCHealthDept?ref_src=twsrc%5Etfw%7Ctwcamp%5Eembeddedtimeline%7Ctwterm%5Eprofile%3AOCHealthDept&ref_url=https%3A%2F%2Fwww.onslowcountync.gov%2F149%2FHealth and saves them to the environment.

@name("Onslow County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:OCHealthDept?ref_src=twsrc^tfw|twcamp^embeddedtimeline|twterm^profile:OCHealthDept&ref_url=https://www.onslowcountync.gov/149/Health"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @OrangeHealthNC and saves them to the environment.

@name("Orange County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:OrangeHealthNC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @ARHS_NC and saves them to the environment.

@name("Perquimans County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:ARHS_NC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @PersonCountyNC and saves them to the environment.

@name("Person County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:PersonCountyNC"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @rowancountync and saves them to the environment.

@name("Rowan County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:rowancountync"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @SwainCountyHeal and saves them to the environment.

@name("Swain County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:SwainCountyHeal"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @Granvillevance3 and saves them to the environment.

@name("Vance County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:Granvillevance3"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @AppDistrictHD and saves them to the environment.

@name("Watauga County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:AppDistrictHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @YadkinHSA and saves them to the environment.

@name("Yadkin County")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:YadkinHSA"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"



