#!/usr/bin/env dothttp

@name("localhost:4040/api/emergency/create/:token")
POST "https://192.168.8.100/api/emergency/create/:token"
files(
	("user", "5cb7864c26b5a0352c464181"),
	("pi", "5db6b78ec558732246b19f56"),
	("comments", "Help me")
)


@name("Get Requests")
GET "https://192.168.8.100/api/emergency/get-requests/:token"


@name("Get Request")
GET "https://192.168.8.100/api/emergency/request-status/:request/:token"



