#!/usr/bin/env dothttp

@name("/files/{{id}}")
GET "https://{{base-api-url}}/files/{{id}}"
"Authorization": "Bearer {{your-api-key}}"
"Content-Type": "application/json"


// The optional parameter `?alt=media` can be used in order to download the media in binary instead of base64. It's recommended in particular for performance.
// 
// Here is how to use it: `{{endpoint}}/files/{{file_id}}/download?alt=media`.
// 
// You will be able to write it directly into a file instead of handling base64.

@name("/files/{{id}}/download")
GET "https://{{base-api-url}}/files/{{id}}/download"
"Authorization": "Bearer {{your-api-key}}"
"Content-Type": "application/json"



