#!/usr/bin/env dothttp

@name("Get all commonly used licenses")
GET "https://{{baseUrl}}/licenses"
? "featured"= "<boolean>"
? "per_page"= "30"


@name("Get a license")
GET "https://{{baseUrl}}/licenses/:license"



