#!/usr/bin/env dothttp

@name("List All Rules to Monitor on Portfolio")
GET "https://connect.creditsafe.com/v1/monitoring/eventRules"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"


@name("List Global Rules to Monitor on Portfolio")
GET "https://connect.creditsafe.com/v1/monitoring/eventRules/XX"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"


@name("List Local Rules to Monitor on Portfolio - Country Specific")
GET "https://connect.creditsafe.com/v1/monitoring/eventRules/FR"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"


@name("Editing Global Notification Rules on Portfolio")
PUT "https://connect.creditsafe.com/v1/monitoring/portfolios/{portfolioId}/eventRules/XX"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"
data('[
      {
        "ruleCode": 104,
        "isActive": 1
   
    },
      {
        "ruleCode": 105,
        "isActive": 1
   
    },
      {
        "ruleCode": 106,
        "isActive": 1
   
    },
      {
        "ruleCode": 107,
        "isActive": 1
   
    }
    
]

//These are Global Rules (notice XX parameter)')


@name("Editing Local Notification Rules on Portfolio")
PUT "https://connect.creditsafe.com/v1/monitoring/portfolios/{portfolioId}/eventRules/FR"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"
data('[
    {
        "ruleCode": 408,
        "isActive": 1
    },
    {
        "ruleCode": 503,
        "isActive": 1
    },
    {
        "ruleCode": 520,
        "isActive": 1
    },
    {
        "ruleCode": 521,
        "isActive": 1
    }
]

//These are FR local Rules (notice FR parameter) - Check List Rules endpoint to see which rules they reference.')


@name("Monitor drop in Credit Score (Global Rule Example)")
PUT "https://connect.creditsafe.com/v1/monitoring/portfolios/{portfolioId}/eventRules/XX"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"
data('[
      {
        "ruleCode": 101,
        "isActive": 1,
        "param0": "1",
        "param1": "B"
    }
]   
//Rating Band (A-E) Drops by 1 banding, or goes less than a "B" Rating
//XX represents a global rule')


@name("Monitor CCJ Annoucements (Local Rule Example)")
PUT "https://connect.creditsafe.com/v1/monitoring/portfolios/{portfolioId}/eventRules/GB"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"
data('[
      {
        "ruleCode": 1811,
        "isActive": 1
      }
]   

//Notice countryCode is a specific country, not XX for global.
//No param0, param1, param2 on this rule (check the List Rules to Monitor to see if they are required for the specific rule)')


@name("Set Rules back to Default (none)")
PUT "https://connect.creditsafe.com/v1/monitoring/portfolios/{portfolioId}/eventRules/setDefault"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"




