#!/usr/bin/env dothttp

@name("https://localhost:44352/api/style/32bd8b79-eac4-456c-b87d-0bed55087031")
DELETE "https://localhost/api/style/32bd8b79-eac4-456c-b87d-0bed55087031"



@name("https://localhost:44352/api/style/")
POST "https://localhost/api/style/"
data('"Kane"')


@name("https://localhost:44352/api/style/e012dcd8-82dd-44ce-a0c8-08d7f002e730")
GET "https://localhost/api/style/"
data('"Undertaker"')


@name("https://localhost:44352/api/style/e012dcd8-82dd-44ce-a0c8-08d7f002e730")
PUT "https://localhost/api/style/e012dcd8-82dd-44ce-a0c8-08d7f002e730"
data('"Kane"')


@name("https://localhost:44352/api/style/a59c901e-64a6-40ae-bbaa-08d7f042aacf")
GET "https://localhost/api/style/a59c901e-64a6-40ae-bbaa-08d7f042aacf"
data('"Undertaker"')



