#!/usr/bin/env dothttp

@name("Email Template")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailTemplate/"


@name("Email Template Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailTemplate/{ID}/"


@name("Describe Email Template")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailTemplate/describe/"



