#!/usr/bin/env dothttp

@name("Content User Subscription")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentUserSubscription/"


@name("Content User Subscription Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentUserSubscription/{ID}/"


@name("Describe Content User Subscription")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentUserSubscription/describe/"



