#!/usr/bin/env dothttp

@name("Get Device Audio Volume")
GET "https://{{WEBEXAPI}}/xapi/status"
"Authorization": "Bearer {{access_token}}"
? "deviceId"= "{{_deviceId}}"
? "name"= "Audio.Volume"


@name("Get Device Audio (all)")
GET "https://{{WEBEXAPI}}/xapi/status"
"Authorization": "Bearer {{access_token}}"
? "deviceId"= "{{_deviceId}}"
? "name"= "Audio.*"


@name("Get Device Status (all)")
GET "https://{{WEBEXAPI}}/xapi/status"
"Authorization": "Bearer {{access_token}}"
? "deviceId"= "{{_deviceId}}"
? "name"= "*"



