#!/usr/bin/env dothttp

@name("Address Web Tool")
POST "http://production.shippingapis.com/ShippingApi.dll"
? "API"= "Verify"
? 'XML'= '<AddressValidateRequest USERID="{{USERID}}"><Revision>1</Revision><Address ID="0"><Address1></Address1><Address2>29851 Aventura k</Address2><City></City><State>CA</State><Zip5>92688</Zip5><Zip4></Zip4></Address></AddressValidateRequest>'



@name("ZIP Code Lookup Web Tool")
POST "http://production.shippingapis.com/ShippingAPITest.dll"
? "API"= "ZipCodeLookup"
? 'XML'= '<ZipCodeLookupRequest USERID="{{USERID}}"><Address ID="0"><Address1></Address1><Address2>6406 Ivy Lane</Address2><City>Greenbelt</City><State>MD</State></Address></ZipCodeLookupRequest>'


@name("City/State Lookup Web Tool")
POST "http://production.shippingapis.com/ShippingApi.dll"
? "API"= "CityStateLookup"
? 'XML'= '<CityStateLookupRequest USERID="{{USERID}}"><ZipCode ID="0"><Zip5>20024</Zip5></ZipCode></CityStateLookupRequest>'



