#!/usr/bin/env dothttp

@name("Security Custom Baseline")
GET "https://{{host}}/services/data/v47.0/sobjects/SecurityCustomBaseline/"


@name("Security Custom Baseline Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/SecurityCustomBaseline/{ID}/"


@name("Describe Security Custom Baseline")
GET "https://{{host}}/services/data/v47.0/sobjects/SecurityCustomBaseline/describe/"



