#!/usr/bin/env dothttp

@name("/get_car_type")
GET "http://localhost/get_car_type"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"



@name("/get_car_brands")
GET "http://localhost/get_car_brands"


@name("save_car_leads_step_1")
POST "https://apidigital.bfi.co.id/save_car_leads_step_1"
basicauth("BFIcorporate", "B9IT7g(ZcD#2")
"Content-Type": "application/json"
json({
    "name": "Febrianto",
    "email": "febrielven@gmail.com",
    "phone_number": "081268526827"
})


@name("/get_car_models")
POST "http://www.bficorporatedev.com/get_car_models"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "type_id": "134304DA-217E-44C5-BCE5-99D00427EA1C",
    "brand_id": "F66C9CE3-C6E3-40C9-A804-FBD0E65B0A7B"
})


@name("save_car_leads_step_2")
POST "http://localhost/save_car_leads_step_2"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "018CC17E-28F1-4D7E-AAE4-8F19FF36A97A",
    "province_id": "B8E13A16-D951-40B9-A1AF-A7D25AF70F54",
    "city_id": "C9560C69-C60F-46CC-8EBA-F5928645306C",
    "district_id": "613FC85B-DFE2-4E96-9513-A4192ABE08B5",
    "subdistrict_id": "0CE84354-C449-4055-B43C-D45D5D0155CB",
    "zipcode_id": "AA7AB2F4-4AD1-4335-AAA5-02186F5CE4DD",
    "address": "jln. Belimbing no 3 Jakarta Selatan 4"
})


@name("/get_car_year")
POST "http://localhost/get_car_year"
"Content-Type": "application/json"
json({
    "model_id": "E333E950-5AFB-4A47-964F-19684EB8FD91"
})


@name("/save_car_leads_step_3")
POST "http://localhost/save_car_leads_step_3"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "FA1BDFD7-C3B3-4DD8-AA92-70294D332910",
    "car_type_id": "7C31042F-A413-4474-ABD1-C6910DBD2A73",
    "car_brand_id": "B7156201-A7DB-4FD6-81CD-35639E5DDACA",
    "car_model_id": "30AC9468-E0A5-4B6B-A4DD-0CC60DD23345",
    "car_year_id": "701E6ADB-C179-4426-B182-EADA2A09683C",
    "bpkb_atas_nama": false
})


@name("/get_car_tenor_list")
POST "http://localhost/get_car_tenor_list"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "51EE1C69-0DD4-41BE-AA2D-0FF60B445763"
})


@name("/get_car_funding")
POST "http://localhost/get_car_funding"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "51EE1C69-0DD4-41BE-AA2D-0FF60B445763"
})


@name("/get_car_funding")
GET "http://localhost/get_car_funding"
"Content-Type": "application/json"
json({
    "submission_id": "FA1BDFD7-C3B3-4DD8-AA92-70294D332910"
})


@name("/save_car_leads_step_5")
POST "http://localhost/save_car_leads_step_5"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "FA1BDFD7-C3B3-4DD8-AA92-70294D332910",
    "is_news_letter": true
})


@name("/save_car_leads_step_4")
POST "http://localhost/save_car_leads_step_4"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "FA1BDFD7-C3B3-4DD8-AA92-70294D332910"
})


@name("/save_car_leads_step_6")
POST "http://localhost/save_car_leads_step_6"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "FA1BDFD7-C3B3-4DD8-AA92-70294D332910"
})


@name("http://localhost:4000/car_calculate")
POST "https://www.bficorporatedev.com/car_calculate"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "0AB78AB2-6BE0-469A-BC0C-20F26B78F6A0",
    "funding": "3000000",
    "tenor": "36",
    "insurance": [
        "67E91332-E5B2-4ED2-9126-2BB828B00F82",
        "67E91332-E5B2-4ED2-9126-2BB828B00F82",
        "67E91332-E5B2-4ED2-9126-2BB828B00F82"
    ]
})


@name("http://localhost:4000/get_car_insurance_list")
POST "http://localhost/get_car_insurance_list"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "FA1BDFD7-C3B3-4DD8-AA92-70294D332910",
    "tenor": 12
})


@name("http://localhost:4000/get_car_funding")
POST "http://localhost/get_car_funding"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
json({
    "submission_id": "FA1BDFD7-C3B3-4DD8-AA92-70294D332910"
})



