#!/usr/bin/env dothttp

// List the dashboard administrators in this organization

@name("getOrganizationAdmins")
GET "https://{{baseUrl}}/organizations/:organizationId/admins"
"Accept": "*/*"



// Create a new dashboard administrator
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// email| string| The email of the dashboard administrator. This attribute can not be updated.
// name| string| The name of the dashboard administrator
// orgAccess| string| The privilege of the dashboard administrator on the organization. Can be one of 'full', 'read-only', 'enterprise' or 'none'
// tags| array| The list of tags that the dashboard administrator has privileges on
// networks| array| The list of networks that the dashboard administrator has privileges on

@name("createOrganizationAdmin")
POST "https://{{baseUrl}}/organizations/:organizationId/admins"
"Accept": "*/*"
"Content-Type": "application/json"
data('{
  "name": "Miles Meraki",
  "email": "miles@meraki.com",
  "orgAccess": "none",
  "tags": [
    {
      "tag": "west",
      "access": "read-only"
    }
  ]
}')


// Update an administrator
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// name| string| The name of the dashboard administrator
// orgAccess| string| The privilege of the dashboard administrator on the organization. Can be one of 'full', 'read-only', 'enterprise' or 'none'
// tags| array| The list of tags that the dashboard administrator has privileges on
// networks| array| The list of networks that the dashboard administrator has privileges on

@name("updateOrganizationAdmin")
PUT "https://{{baseUrl}}/organizations/:organizationId/admins/:id"
"Accept": "*/*"
"Content-Type": "application/json"
data('{
  "name": "Miles Meraki",
  "email": "miles@meraki.com",
  "orgAccess": "none",
  "tags": [
    {
      "tag": "west",
      "access": "read-only"
    }
  ]
}')


// Revoke all access for a dashboard administrator within this organization

@name("deleteOrganizationAdmin")
DELETE "https://{{baseUrl}}/organizations/:organizationId/admins/:id"
"Accept": "*/*"




