#!/usr/bin/env dothttp

// Export budget for blueprint in CSV or XLSX format.
// 
// Path Parameters
// ===============
// - **BLUEPRINT_ID**: _UUID_, Blueprint ID
// - **FORMAT**: _String_, one of "csv", "xlsx"
// 
// Optional query parameters
// =========================
// - **currency**: _String_. Currency in ISO_4217 format. Should be one of "USD", "AUD", "CHF", "CKK", "EUR", "GBP", "HKD", "JPY", "NOK", "NZD", "SEK", "ZAR". Defaults to "USD".
// - **period**: _String_. Period for budget. Should be one of "h" (hourly), "d" (daily), "w" (weekly), "m" (monthly), "y" (yearly).Defaults to "m".
// - **rate**: _String_. Should be one of "effective" (includes upfront fees) or "stated" (excludes upfront fees). Defaults to "effective".
// Responses
// =========
// - **200 OK on success**, with the content type being one of:
//   - text/csv
//   - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
// - 401 Unauthorized
// - 403 Forbidden, insufficient privileges
// - 404 Blueprint not found

@name("Export budget for a blueprint")
GET "https://{{cloudcraft_url}}/blueprint/BLUEPRINT_ID/budget/FORMAT"



