#!/usr/bin/env dothttp

@name("Attached Content Document")
GET "https://{{host}}/services/data/v47.0/sobjects/AttachedContentDocument/"


@name("Attached Content Document Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/AttachedContentDocument/{ID}/"


@name("Describe Attached Content Document")
GET "https://{{host}}/services/data/v47.0/sobjects/AttachedContentDocument/describe/"



