#!/usr/bin/env dothttp

// Retrieves a list of JSON descriptions for all tags in your VideoAsk account.

@name("Retrieve tags")
GET "https://{{base_url}}/tags"
"Authorization": "Bearer {{token}}"
? "limit"= "0"
? "offset"= "0"


@name("Create a tag")
POST "https://{{base_url}}/tags"
"Authorization": "Bearer {{token}}"
"Content-Type": "application/json"
json({
    "title": "My tag"
})


@name("Add a tag to a contact")
PATCH "https://{{base_url}}/contacts/{{contact_id}}/tags/{{tag_id}}"
"Authorization": "Bearer {{token}}"
"Content-Type": "application/json"
json({
    "action": "add"
})


@name("Remove a tag from a contact")
PATCH "https://{{base_url}}/contacts/{{contact_id}}/tags/{{tag_id}}"
"Authorization": "Bearer {{token}}"
"Content-Type": "application/json"
json({
    "action": "remove"
})


@name("Update a tag")
PATCH "https://{{base_url}}/tags/{{tag_id}}"
"Authorization": "Bearer {{token}}"
"Content-Type": "application/json"
json({
    "title": "My tag"
})


@name("Delete a tag")
DELETE "https://{{base_url}}/tags/{{tag_id}}"
"Authorization": "Bearer {{token}}"
"Content-Type": "application/json"



