#!/usr/bin/env dothttp

// Uploads a photo. Uploading apps can call the flickr.people.getUploadStatus method in the regular API to obtain file and bandwidth limits for the user.

@name("Upload")
POST "https://{{baseUrl}}/upload"
? "title"= "<>"
? "description"= "<>"
? "tags"= "<>"
? "is_public"= "<>"
? "is_friend"= "<>"
? "is_family"= "<>"
? "safety_level"= "<>"
? "content_type"= "<>"
? "hidden"= "<>"
? "async"= "<>"


// Replaces a photo that has already been uploaded to Flickr. Uploading apps can call the flickr.people.getUploadStatus method in the regular API to obtain file and bandwidth limits for the user.

@name("Replace")
POST "https://{{baseUrl}}/replace"
? "photo_id"= "<>"
? "async"= "<>"



