#!/usr/bin/env dothttp

// Calls to Connect require a valid JWT authentication token to be supplied as a REST header. An authentication token can be obtained by calling the Authenticate endpoint with your CS Connect credentials in the request raw body. Please note that all authentication credentials are case sensitive. 
// 
// 
// Successful calls will return an active authentication token, which will persist for one hour. Take a copy of the JSON response field value token. This is your validated authentication token that needs to be included as a REST header to all other calls.
// 
// When your token expires, you can request another independently of your current token. More than one valid token can exist simultaneously.

@name("Authenticate / Generate Auth Token")
POST "https://connect.creditsafe.com/v1/authenticate"
"Content-Type": "application/json"
data('{
    "username": "username@domain.com",
    "password": "yourPasswordHere"
}

//Response Token will be saved to a global variable in postman called connectAuthToken')


// In certain integrations you may want your user users to be presented with a list of countries that your account has access to (for example, to pick a region to search specifically in).

@name("List Countries in Subscription")
GET "https://connect.creditsafe.com/v1/access/countries"
"Content-Type": "application/json"
"Authorization": "Bearer {{connectAuthToken}}"



