#!/usr/bin/env dothttp

@name("Alarms")
GET "https://{{vmanage}}/dataservice/data/device/statistics/alarm"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Application-Aware Routing Status")
GET "https://{{vmanage}}/dataservice/data/device/statistics/approutestatsstatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Audit Logs")
GET "https://{{vmanage}}/dataservice/data/device/statistics/auditlog"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Bridge Interfaces")
GET "https://{{vmanage}}/dataservice/data/device/statistics/bridgeinterfacestatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Bridge MAC Addresses")
GET "https://{{vmanage}}/dataservice/data/device/statistics/bridgemacstatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("CloudExpress Service")
GET "https://{{vmanage}}/dataservice/data/device/statistics/cloudxstatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Device Configuration")
GET "https://{{vmanage}}/dataservice/data/device/statistics/deviceconfiguration"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Device Events")
GET "https://{{vmanage}}/dataservice/data/device/statistics/deviceevents"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Device System Status")
GET "https://{{vmanage}}/dataservice/data/device/statistics/devicesystemstatusstatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("DPI")
GET "https://{{vmanage}}/dataservice/data/device/statistics/dpistatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Flow Logs")
GET "https://{{vmanage}}/dataservice/data/device/statistics/flowlogstatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("Interfaces")
GET "https://{{vmanage}}/dataservice/data/device/statistics/interfacestatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("WLAN Clients")
GET "https://{{vmanage}}/dataservice/data/device/statistics/wlanclientinfostatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("?urlf?")
GET "https://{{vmanage}}/dataservice/data/device/statistics/urlf"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("?fwall?")
GET "https://{{vmanage}}/dataservice/data/device/statistics/fwall"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("?umbrella?")
GET "https://{{vmanage}}/dataservice/data/device/statistics/umbrella"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("?ipsalert?")
GET "https://{{vmanage}}/dataservice/data/device/statistics/ipsalert"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"


@name("?speedtest?")
GET "https://{{vmanage}}/dataservice/data/device/statistics/speedtest"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "startDate"= "{{startDate}}"
? "endDate"= "{{endDate}}"
? "timeZone"= "{{timeZone}}"
? "count"= "{{count}}"



