#!/usr/bin/env dothttp

@name("Creates or updates an PortalForm with a specific ID")
PUT "https://{{baseUrl}}/security/v1/portalform/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "customObject": [
        "<string>"
    ],
    "maximumNumberOfSubmissions": [
        "<integer>"
    ],
    "accessMode": [
        "<integer>"
    ],
    "formSubmissionManagementLinkText": [
        "<string>"
    ],
    "managementFieldsToDisplay": [
        "[\"<string>\",\"<string>\"]"
    ],
    "allowAnonymousSubmissions": [
        "<boolean>"
    ],
    "anonymousSubmissionCompletionUrl": [
        "<string>"
    ],
    "displayOrder": [
        "<integer>"
    ],
    "loginScreenDisplayName": [
        "<string>"
    ],
    "displayOnHomeScreen": [
        "<boolean>"
    ],
    "homeScreenDisplayName": [
        "<string>"
    ],
    "customerType": [
        "<integer>"
    ],
    "module": [
        "<string>"
    ],
    "description": [
        "<string>"
    ],
    "showFrom": [
        "<dateTime>"
    ],
    "showUntil": [
        "<dateTime>"
    ],
    "membersOnly": [
        "<boolean>"
    ],
    "displayOnLoginScreen": [
        "<boolean>"
    ],
    "confirmationEmail": [
        "<string>"
    ],
    "formInstructions": [
        "<string>"
    ],
    "editInstructions": [
        "<string>"
    ],
    "confirmationInstructions": [
        "<string>"
    ],
    "viewInstructions": [
        "<string>"
    ],
    "manageInstructions": [
        "<string>"
    ],
    "postSubmissionInstructions": [
        "<string>"
    ],
    "createPageLayout": [
        "<string>"
    ],
    "editPageLayout": [
        "<string>"
    ],
    "viewPageLayout": [
        "<string>"
    ],
    "activityType": [
        "<string>"
    ],
    "valueAssignments": [
        "[{\"fieldName\":\"<string>\",\"valueToSet\":\"<string>\",\"onlyIfPreviouslyNull\":\"<boolean>\",\"clearExistingValues\":\"<boolean>\"},{\"fieldName\":\"<string>\",\"valueToSet\":\"<string>\",\"onlyIfPreviouslyNull\":\"<boolean>\",\"clearExistingValues\":\"<boolean>\"}]"
    ],
    "isActive": [
        "<boolean>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})


@name("Deletes an PortalForm with a specific ID")
DELETE "https://{{baseUrl}}/security/v1/portalform/delete/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"



