#!/usr/bin/env dothttp

// <h4>Transaction success</h4>
// 
// ```
// {
//     "id": "cd31ee05-f5bd-461d-82a1-c733fb6a1ffd",
//     "env": 1,
//     "agency_id": "de001eab-11f4-4572-942e-6f1dbffe2f8f",
//     "facematch_score": "98.07",
//     "transaction_status": 1,
//     "request_timestamp": "2019-03-23 13:23:43:486 +05:30",
//     "response_timestamp": "2019-03-23 13:23:43:891 +05:30",
//     "face_matched": "Very likely"
// }
// ```

@name("Verification API")
POST "https://{{base_url}}/utils/face-match"
"qt_api_key": "{{qt_api_key_value}}"
"qt_agency_id": "{{qt_agency_id}}"
"Content-Type": "application/json"
json({
    "Id_base64": "<base 64 of image >",
    "User_photo_base64": "<base 64 of image >"
})



