#!/usr/bin/env dothttp

// Add client to sale
// 
// ### Note
// This endpoint is only being used internally and not subjected to user input, the input that is provided herein is already validated in other point of the sale creation. 
// 
// #### Path Variables
// ```
// sale_id             4EC041C2-E733-4C56-B622-490AFF39942E    
// ```
// 
// #### Reponse status codes
// | Code| Message|Reason | 
// | -- | -- | -- | 
// | 200| OK| return sale client| 
// | 400| Bad request|Malformed request syntax, read the docs | 
// | 422| Invalid info for process|Field value error, read the docs | 
// | 422| Unprocessable Entity Error|Business rule error, read the docs | 
// | 404| Not found| Bad endpoint invocation | 

@name("Add client")
GET "https://{{base_url}}/sales/companyNumber/207443/branchNumber/15784/lasts"
json({
    "clientId": "C5F831DA-47A9-4860-B339-C7E78138A407",
    "taxId": "SARB931102MDFNYR8O4",
    "companyNumber": 20156,
    "commercialName": "Terra nova",
    "businessName": "Terra nova"
})


// Update client info
// 
// ### Note
// This endpoint is only being used internally and not subjected to user input, the input that is provided herein is already validated in other point of the sale creation. 
// 
// #### Path Variables
// ```
// sale_id             4EC041C2-E733-4C56-B622-490AFF39942E    
// ```
// 
// #### Reponse status codes
// | Code| Message|Reason | 
// | -- | -- | -- | 
// | 200| OK| return sale client| 
// | 400| Bad request|Malformed request syntax, read the docs | 
// | 422| Invalid info for process|Field value error, read the docs | 
// | 422| Unprocessable Entity Error|Business rule error, read the docs | 
// | 404| Not found| Bad endpoint invocation | 

@name("Update client")
PATCH "https://{{base_url}}/sales/BF1D7AB4-0E85-48DA-BBB0-CE94D26VF2A7/sale_client"
json({
    "clientId": "C5F831DA-47A9-4860-B339-C7E78138A407",
    "taxId": "SARB931102MDFNYR8O4",
    "companyNumber": 20156,
    "commercialName": "Terra nova",
    "businessName": "Terra nova"
})



