#!/usr/bin/env dothttp

// Retrieve a policy version by the version number
// Get Version

@name("List Policies Versions By ID And Versio nNumber")
GET "https://{{baseUrl}}/1.0/policies/:id/versions/:versionNumber"


// Activates the specified policy version
// Activate Version

@name("Policies Versions Activate By ID")
POST "https://{{baseUrl}}/1.0/policies/:id/versions/:versionNumber/activate"


// Sets the comment on a specific policy version.
// Set Version Comment

@name("Set Policies Versions Comment By ID")
PUT "https://{{baseUrl}}/1.0/policies/:id/versions/:versionNumber/comment"



