#!/usr/bin/env dothttp

@name("Community")
GET "https://{{host}}/services/data/v47.0/sobjects/Community/"


@name("Community Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Community/{ID}/"


@name("Describe Community")
GET "https://{{host}}/services/data/v47.0/sobjects/Community/describe/"



