#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Issue Type Screen Schemes For Projects")
GET "https://{{baseUrl}}/rest/api/3/issuetypescreenscheme/project"
? "startAt"= "0"
? "maxResults"= "50"
? "projectId"= "<long>"


@name("Assign Issue Type Screen Scheme To Project")
PUT "{{baseUrl}}/rest/api/3/issuetypescreenscheme/project"
"Content-Type": "application/json"
data('{
    "issueTypeScreenSchemeId": "<string>",
    "projectId": "<string>"
}')



