#!/usr/bin/env dothttp

// Lookup and retrieve all metadata related to all discovered devices on the network.

@name("Get devices")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/intelligence/discovery/devices"
"x-net-site": "{{SITE_UUID}}"
"x-api-key": "{{API_KEY}}"


// Lookup and retrieve all metadata related to a device discovered on the network.

@name("Get device")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/intelligence/discovery/devices/:mac"
"x-net-site": "{{SITE_UUID}}"
"x-api-key": "{{API_KEY}}"


// Analyze MAC address.

@name("Analyze MAC")
POST "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/intelligence/discovery/devices/:mac/analyze"
"x-net-site": "{{SITE_UUID}}"
"x-api-key": "{{API_KEY}}"



