#!/usr/bin/env dothttp

@name("Create Topic")
POST "https://iid.googleapis.com/iid/v1:batchAdd"
"Authorization": "key={{server_key}}"
"Content-Type": "application/json"
data('{
   "to": "/topics/YOUR_TOPIC_NAME",
   "registration_tokens": ["ARRAY_OF_FCM_TOKENS"]
}')


@name("Validate FCM")
GET "https://iid.googleapis.com/iid/info/{{iid_token}}"
"Authorization": "key={{server_key}}"


@name("Remove Topic")
POST "https://iid.googleapis.com/iid/v1:batchRemove"
"Authorization": "key={{server_key}}"
"Content-Type": "application/json"
data(' {
   "to": "/topics/TOPIC_NAME",
   "registration_tokens": ["FCM_TOKENS"]
 }')


@name("Send Notification")
POST "https://fcm.googleapis.com/fcm/send"
"Content-Type": "application/json"
"Authorization": "key={{server_key}}"
data('{
  "priority":"HIGH",
  "data":{
   
  },
  "to":"VALID_FCM_TOKENS"
}')


@name("Create Group ")
POST "https://android.googleapis.com/gcm/notification"
"Content-Type": "application/json"
"Authorization": "key={{server_key}}"
"project_id": "{{project_id}}"
data('{
   "operation": "add",
   "notification_key_name": "ANY_GROUP_NAME",
   "registration_ids": ["VALID_FCM"]
}')


@name("Import Token APNs")
POST "https://{{host}}/"


@name("Send Notification to Topic")
POST "https://fcm.googleapis.com/v1/projects/umh-app/messages:send"
"Content-Type": "application/json"
"Authorization": "Bearer ya29.c.ElpaBh9SzohgWCFyo5eYIXtIZj4TpLY2cnbEVxWJR2mv3rbA9dZsv8nCx4NXsZTJFNSfztmW1_aEpVJy3mepxi9jbi3jpaBqoXFPvfGL-IIrXou0CpQ2_nnhmrM"
data('{
   "message":{
    "topic": "paralela",
    "notification" : {
      "body" : "This is a Firebase Cloud Messaging Topic Message!",
      "title" : "FCM Message"
    }
   }
}')


@name("Send Notification Specific")
POST "https://fcm.googleapis.com/fcm/send"
"Content-Type": "application/json"
"Authorization": "key={{server_key}}"
data('{
  "priority":"HIGH",
  "data":{
   
  },
  "to":"VALID_FCM_TOKENS"
}')



