#!/usr/bin/env dothttp

@name("Returns a set of response headers from the query string.")
GET "https://{{baseUrl}}/response-headers"


@name("Returns a set of response headers from the query string.")
POST "https://{{baseUrl}}/response-headers"



