#!/usr/bin/env dothttp

@name("Get whitelisted addresses")
GET "https://{{BASE_URL}}/{{mydomain}}/whitelists"
"Authorization": "Basic {{token}}"


@name("Add whitelisted addresses")
POST "https://{{BASE_URL}}/{{mydomain}}/whitelists"
"Authorization": "Basic {{token}}"
files(
	("address", "mbkane04@gmail.com")
)


@name("Get single whitelisted address")
GET "https://{{BASE_URL}}/{{mydomain}}/whitelists/{{address}}"
"Authorization": "Basic {{token}}"
files(
	("address", "mbkane04@gmail.com")
)


@name("Delete single whitelisted address")
DELETE "https://{{BASE_URL}}/{{mydomain}}/whitelists/{{address}}"
"Authorization": "Basic {{token}}"
files(
	("address", "mbkane04@gmail.com")
)


@name("Remove all whitelisted addresses")
DELETE "https://{{BASE_URL}}/{{mydomain}}/whitelists"
"Authorization": "Basic {{token}}"
files(
	("address", "")
)



