#!/usr/bin/env dothttp

// Learn about [working with variables](https://learning.postman.com/docs/postman/variables-and-environments/variables/) in Postman.
// 
// Under the **Tests** tab, parse the server response and save an environment variable called `key` to be used in subsequent requests. **Send** this request to initialize that variable `key`.

@name("Login - with variable")
POST "https://qhiug7xk62.execute-api.eu-central-1.amazonaws.com/default/Bucket"
"x-api-key": "B8q6CdR6707ZV9YxGnivN4kHl9zbvP0h6jwxOsBS"
"Content-Type": "application/json"
json({
    "type": "login",
    "json": "{'user': 'company', 'password': 'company'}"
})


// Under the **Body** tab, use `{{key}}` to access the environment variable called `key` that we initialized in the preceding request.

@name("Get bucket - with variable")
POST "https://qhiug7xk62.execute-api.eu-central-1.amazonaws.com/default/Bucket"
"x-api-key": "B8q6CdR6707ZV9YxGnivN4kHl9zbvP0h6jwxOsBS"
"Content-Type": "application/json"
json({
    "type": "get_bucket",
    "json": "{'key': {{key}} }"
})



