#!/usr/bin/env dothttp

// This endpoint shows information about an editorial image, including a URL to a preview image and the sizes that it is available in.

@name("Get editorial video content details")
GET "https://{{baseUrl}}/v2/editorial/videos/:id"
? "country"= "<country-code-3>"



