#!/usr/bin/env dothttp

@name("Get all repository topics")
GET "https://{{baseUrl}}/repos/:owner/:repo/topics"


@name("Replace all repository topics")
PUT "https://{{baseUrl}}/repos/:owner/:repo/topics"
"Content-Type": "application/json"
data('{
    "names": [
        "<string>",
        "<string>"
    ]
}')



