#!/usr/bin/env dothttp

@name("/purchases/discount")
POST "https://{{baseUrl}}/purchases/discount"
"Content-Type": "application/json"
"x-api-key": "{{apiKey}}"
"Authorization": "<Authorization>"
? "code"= "<code>"
? "items_cost"= "<items_cost>"
? "delivery_cost"= "<delivery_cost>"



@name("/purchases/discount")
OPTIONS "https://{{baseUrl}}/purchases/discount"



