#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get the code of conduct for a repository")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo/community/code_of_conduct}}/"


@name("Get community profile metrics")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo/community/profile}}/"



