#!/usr/bin/env dothttp

// It fetches all Campaigns for the user. 
// Possible "status": ['draft', 'running', 'paused', 'stopped']

@name("Get Appointments Campaign Key Value")
GET "https://{{sb_client}}.salesboard.biz/v2/dashboards/appointments"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "include"= "details, address, contactTypes, meetingNotes"
? 'filters'= '{"campaignKeyValue": ["{{sb_campaign_key_value}}"]}'


// It fetches all Campaigns for the user. 
// Possible "status": ['draft', 'running', 'paused', 'stopped']

@name("Get Appointments")
GET "https://{{sb_client}}.salesboard.biz/v2/dashboards/appointments"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "include"= "details, address, contactTypes, meetingNotes"


// It fetches all Campaigns for the user. 
// Possible "status": ['draft', 'running', 'paused', 'stopped']

@name("Get Appointment by ID")
GET "https://{{sb_client}}.salesboard.biz/v2/dashboards/appointments/{{sb_appointment_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"


@name("Create Appointment")
POST "https://{{sb_client}}.salesboard.biz/v2/dashboards/appointments"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
json({
    "name": "Jan Jansen",
    "campaignKeyValue": "{{sb_campaign_key_value}}",
    "ID_Story": 1,
    "ID_Campaign": 2,
    "startDate": 1561033067000,
    "endDate": 1589382201000,
    "link": "",
    "meetingNotes": "Some notes for the meeting",
    "address": "Koninginnegracht 19, 2514 AB The Hague, The Netherlands",
    "contactTypes": [
        "video"
    ]
})


@name("Update Appointment")
PUT "https://{{sb_client}}.salesboard.biz/v2/dashboards/appointments/{{sb_appointment_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
json({
    "name": "Tim Jansen",
    "meetingNotes": "Contact person changed. Some notes for the meeting",
    "address": "Koninginnegracht 19, 2514 AB The Hague",
    "startDate": 1561033067001,
    "endDate": 1589382201001,
    "ID_Story": 10,
    "ID_Campaign": 20
})


@name("Delete Appointment")
DELETE "https://{{sb_client}}.salesboard.biz/v2/dashboards/appointments/{{sb_appointment_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"




