#!/usr/bin/env dothttp

@name("(ALL USER) get a subtask by id")
GET "https://hvcg-tm.herokuapp.com/subtasks/1"


// first to find assignable task . Meaning the staff is assigned to the team that is assigned to the project of the subtask.
// 
// as a result , you really dont want to let the user just assign anyone that the user like . the user must find assignable staff first
// 
// you have to send to the api : "/assignable/subtask/{subtaskId}"

@name("(ALL USER) Find all assignable staff")
GET "https://hvcg-tm.herokuapp.com/assignable/subtask/11"


// like task category 
// 
// but you must also supply date start , date finish and status 
// 
// the status is currently restricted to 3 Enum values :
// "NOT_STARTED" , "IN_PROGRESS" , "FINISHED" 
// 
// if you dont use the correct value the status will not be accept

@name("(ADMIN ONLY) make a subtask from the task category ")
POST "https://hvcg-tm.herokuapp.com/subtasks"
"Content-Type": "application/json"



// let us assign a staff to a substask again to modify and delete 

@name("(ADMIN ONLY) assign a staff to task")
POST "https://hvcg-tm.herokuapp.com/staffSubtasks"
"Content-Type": "application/json"



// lile tas category above we can modify the subtask using PUT

@name("(ADMIN ONLY) to update a subtask using PUT")
PUT "https://hvcg-tm.herokuapp.com/subtasks/21"
"Content-Type": "application/json"



// This API will make help to switch task category of a subtask

@name("switch taskcategory of subtask")
PUT "https://hvcg-tm.herokuapp.com/switch/taskCategory/subtask"
"Content-Type": "application/json"



// To delete like the above we need to send a DELETE request to the subtask href

@name("(ADMIN ONLY) delete a subtask")
DELETE "https://hvcg-tm.herokuapp.com/subtasks/21"


// to delete a staff-subtask assignment we need to send a delete Request to the staff-substask assignment link

@name("(ADMIN ONLY) Delete a staff-subtask assignment")
DELETE "https://hvcg-tm.herokuapp.com/staffSubtasks/11"



