#!/usr/bin/env dothttp

@name("accounts/:account_id/tax_settings")
GET "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/tax_settings"


@name("accounts/:account_id/tax_settings")
PUT "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/tax_settings"



