#!/usr/bin/env dothttp

// Replace {{url}} with the URL for the mock that you have created for this collection.
// 
// 
// This will fetch the saved example for the North American continent

@name("Mock  request example")
POST "https://{{url}}/continents"
"Content-Type": "text/xml"
"x-mock-match-request-body": "true"
data('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hol="http://www.holidaywebservice.com/HolidayService_v2/">
   <soapenv:Header/>
   <soapenv:Body>
      <hol:GetCountriesAvailable/>
      <Filter>
      	<mil:continent>North America</mil:continent>
      </Filter>
   </soapenv:Body>
</soapenv:Envelope>')


// Replace {{url}} with the URL for the mock that you have created for this collection.
// 
// This will fetch the saved example for the North American continent

@name("Mock  request example (Empty Data)")
POST "https://{{url}}/continents"
"Content-Type": "text/xml"
"x-mock-match-request-body": "true"
data('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hol="http://www.holidaywebservice.com/HolidayService_v2/">
   <soapenv:Header/>
   <soapenv:Body>
      <hol:GetCountriesAvailable/>
      <Filter>
      	<mil:continent></mil:continent>
      </Filter>
   </soapenv:Body>
</soapenv:Envelope>')



