#!/usr/bin/env dothttp

@name("/clients/:id/update")
PUT "https://{{baseUrl}}/clients/:id/update"
"x-api-key": "{{apiKey}}"
"Authorization": "<Authorization>"
? "birthdate"= "<birthdate>"
? "gender"= "<genero>"


@name("/clients/:id/update")
OPTIONS "https://{{baseUrl}}/clients/:id/update"



