#!/usr/bin/env dothttp

// Order Validation for placing Crypto Orders. This step should be performed before order placement. The result will either be a server error (with an error code) or response as shown below.

@name("Order Preview")
POST "https://{{url}}/api/orders/v2/crypto/preview"
"Content-Type": "application/json"
data('{
	"account":{
		"accountId": 12345, //optional
		"accountNumber": "optional"
		
	},
	"order":{
		"orderType":\'MARKET/LIMIT\',
		"quote":{
			"symbol": \'FX/Currency\'
			
		},
	"expectedValue": \'Value in base currency to purchase\',
	"limitPx": \'IF ORDERTYPE == LIMIT THEN SET LIMIT PX\',
	"transaction":\'BUY/SELL\'
		
	}
}')


// Request is the same as preview. Response:

@name("Order Place")
POST "https://{{host}}/"
"Content-Type": "application/json"
data('{
	"account":{
		"accountId": 12345, //optional
		"accountNumber": "optional"
		
	},
	"order":{
		"orderType":\'MARKET/LIMIT\',
		"quote":{
			"symbol": \'FX/Currency\'
			
		},
	"expectedValue": \'Value in base currency to purchase\',
	"limitPx": \'IF ORDERTYPE == LIMIT THEN SET LIMIT PX\',
	"transaction":\'BUY/SELL\'
		
	}
}')



