#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get a discussion (Legacy)")
GET "https://{{baseUrl}}/teams/{{team_id}}/discussions/{{discussion_number}}/"


@name("Update a discussion (Legacy)")
PATCH "https://{{baseUrl}}/teams/{{team_id}}/discussions/{{discussion_number}}/"
"Content-Type": "application/json"
json({
    "title": "Welcome to our first team post"
})


@name("Delete a discussion (Legacy)")
DELETE "https://{{baseUrl}}/teams/{{team_id}}/discussions/{{discussion_number}}/"



