#!/usr/bin/env dothttp

@name("Create payment (3-D Secure 2)")
POST "https://{{UNLIMINT_API_URL}}/api/payments"
"Content-Type": "application/json"
json({
    "request": {
        "id": "{{$guid}}",
        "time": "{{request_time}}"
    },
    "merchant_order": {
        "id": "{{$randomUUID}}",
        "description": "Postman Collection Order ('{{request_name}}')"
    },
    "payment_method": "BANKCARD",
    "payment_data": {
        "amount": "12.34",
        "currency": "{{TERMINAL_CURRENCY}}",
        "trans_type": "01"
    },
    "card_account": {
        "acct_type": "01"
    },
    "customer": {
        "email": "{{CUSTOMER_EMAIL}}",
        "phone": "+1 123456789",
        "work_phone": "+1 987654321",
        "home_phone": "+1 462526747"
    }
})



