#!/usr/bin/env dothttp

// Gets the project role details and the default actors associated with the role. The list of default actors is sorted by display name.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Get Project Role By Id")
GET "https://{{baseUrl}}/rest/api/3/role/:id"


// Updates the project role's name and description. You must include both a name and a description in the request.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Fully Update Project Role")
PUT "https://{{baseUrl}}/rest/api/3/role/:id"
"Content-Type": "application/json"
json({
    "name": "<string>",
    "description": "<string>"
})


// Updates either the project role's name or its description.
// 
// You cannot update both the name and description at the same time using this operation. If you send a request with a name and a description only the name is updated.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Partial Update Project Role")
POST "https://{{baseUrl}}/rest/api/3/role/:id"
"Content-Type": "application/json"
json({
    "name": "<string>",
    "description": "<string>"
})


// Deletes a project role. You must specify a replacement project role if you wish to delete a project role that is in use.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Delete Project Role")
DELETE "https://{{baseUrl}}/rest/api/3/role/:id"
? "swap"= "<long>"



