#!/usr/bin/env dothttp

// You won't receive a response from calls made to `http://localhost:3001/` unless you have a server running locally.
@name("hello world")
GET "https://{{localhost}}/"


// You won't receive a response from calls made to `http://localhost:3001/` unless you have a server running locally.
@name("turn on / off")
POST "https://{{localhost}}/"
json({
    "on": true
})


// You won't receive a response from calls made to `http://localhost:3001/` unless you have a server running locally.
@name("update light color")
POST "https://{{localhost}}/"
json({
    "on": false,
    "sat": 254,
    "bri": 250,
    "hue": 50000
})



