#!/usr/bin/env dothttp

// The response contains the following fields:
// 
// * `objects`: List of the events that have taken place. If no events are available, then there are none left to paginate through using the `cursor` at this time.
// 
// * `cursor`: A string identifying a location in the stream immediately after the events described in `objects`.
// 
// * `count`: Number of events returned.
// 
// * `type`: Will always be `object_list`.
// 
// * `api`: Will always be `events`.
// 
// The returned cursor should be used in subsequent requests so that only events that have not been seen previously are returned.
// 
// The `remaining` attribute used to be available as well but has been deprecated due to limitations with performance and accuracy.

@name("List events")
GET "https://{{base-url}}/accounts/me/events"



