#!/usr/bin/env dothttp

@name("Email Services Function")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailServicesFunction/"


@name("Email Services Function Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailServicesFunction/{ID}/"


@name("Describe Email Services Function")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailServicesFunction/describe/"



