#!/usr/bin/env dothttp

@name("LED Panel ON")
PUT "https://{{servername}}/v1/devices/{{id}}"
"Host": "{{servername}}:20443"
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0"
"Accept": "*/*"
"Accept-Language": "en-US,it-IT;q=0.8,it;q=0.5,en;q=0.3"
"Accept-Encoding": "gzip, deflate, br"
"Referer": "https://{{servername}}:20443/devices"
"Content-Type": "application/json"
"Authorization": "Bearer {{accessToken}}"
"Origin": "https://{{servername}}:20443"
"Content-Length": "37"
"Connection": "keep-alive"
"Pragma": "no-cache"
"Cache-Control": "no-cache"
json({
    "command": "config-output",
    "value": 1
})


@name("LED Panel OFF")
PUT "https://{{servername}}/v1/devices/{{id}}"
"Host": "{{servername}}:20443"
"User-Agent": " Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0"
"Accept": " */*"
"Accept-Language": " en-US,it-IT;q=0.8,it;q=0.5,en;q=0.3"
"Accept-Encoding": " gzip, deflate, br"
"Referer": " https://{{servername}}:20443/devices"
"Content-Type": "application/json"
"Authorization": " Bearer {{accessToken}}"
"Origin": " https://{{servername}}:20443"
"Content-Length": " 37"
"Connection": " keep-alive"
"Pragma": " no-cache"
"Cache-Control": " no-cache"
json({
    "command": "config-output",
    "value": 0
})


@name("LED Panel Locate")
PUT "https://{{servername}}/v1/devices/{{id}}"
"Host": "{{servername}}:20443"
"User-Agent": " Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0"
"Accept": " */*"
"Accept-Language": " en-US,it-IT;q=0.8,it;q=0.5,en;q=0.3"
"Accept-Encoding": " gzip, deflate, br"
"Referer": " https://{{servername}}:20443/devices"
"Content-Type": "application/json"
"Authorization": " Bearer {{accessToken}}"
"Origin": " https://{{servername}}:20443"
"Content-Length": "20"
"Connection": " keep-alive"
"Pragma": " no-cache"
"Cache-Control": " no-cache"
json({
    "command": "locate"
})


@name("LED Panel Dimmer")
PUT "https://{{servername}}/v1/devices/{{id}}"
"Host": "{{servername}}:20443"
"User-Agent": " Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0"
"Accept": " */*"
"Accept-Language": " en-US,it-IT;q=0.8,it;q=0.5,en;q=0.3"
"Accept-Encoding": " gzip, deflate, br"
"Referer": " https://{{servername}}:20443/devices"
"Content-Type": " application/json"
"Authorization": " Bearer {{accessToken}}"
"Origin": " https://{{servername}}:20443"
"Content-Length": " 29"
"Connection": " keep-alive"
"Pragma": " no-cache"
"Cache-Control": " no-cache"
data('{"command":"sync","value":1}')


@name("Get tokens")
POST "https://{{servername}}/v1/login"
"Host": "{{servername}}:20443"
"User-Agent": " Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0"
"Accept": " */*"
"Accept-Language": " en-US,it-IT;q=0.8,it;q=0.5,en;q=0.3"
"Accept-Encoding": "gzip, deflate, br"
"Referer": " https://{{servername}}:20443/login?redirect=%2Fstatistics"
"Content-Type": "application/json"
"Origin": " https://{{servername}}:20443"
"Content-Length": " 45"
"Connection": " keep-alive"
"Pragma": " no-cache"
"Cache-Control": " no-cache"
data('{"username":{{username}},"password":{{password}}}')



