#!/usr/bin/env dothttp

// # Get CRM Information for Note Creation + File Upload
// ---
// 
// Gets information that can be used to control note creation with the CRM. It can return information about a customer or prospect by email address, but will always return the types of files that are allowed to be uploaded, and whether files are allowed to be uploaded at all
// 
// # Parameters
// ---
// 
// **CompanyID** - Type *string* **:**
// The optional CompanyID used to authenticate this request
// 
// **Email** - Type *string* **:**
// This optional email address of a customer or prospect that will be looked for in the MainDB.CustProspect table

@name("{GET}")
GET "https://{{ServerPath}}/CRM/Info"
"Content-Type": "application/json"
"X-API-Key": "{{APIKey}}"
? "CompanyID"= "{{CompanyID}}"




