#!/usr/bin/env dothttp

@name("Apex Component")
GET "https://{{host}}/services/data/v47.0/sobjects/ApexComponent/"


@name("Apex Component Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/ApexComponent/{ID}/"


@name("Describe Apex Component")
GET "https://{{host}}/services/data/v47.0/sobjects/ApexComponent/describe/"



