#!/usr/bin/env dothttp

@name("Update an existing tenant script")
POST "https://{{baseUrl}}/instance/microservice/:identifier/tenants/:tenantToken/scripting/scripts/:scriptId/versions/:versionId"
"Authorization": ""
"Content-Type": "application/json"
json({
    "content": "<string>",
    "description": "<string>",
    "id": "<string>",
    "name": "<string>",
    "type": "<string>"
})


@name("Activate a tenant script version")
POST "https://{{baseUrl}}/instance/microservice/:identifier/tenants/:tenantToken/scripting/scripts/:scriptId/versions/:versionId/activate"
"Authorization": ""


@name("Clone an existing tenant script version to create a new version")
POST "https://{{baseUrl}}/instance/microservice/:identifier/tenants/:tenantToken/scripting/scripts/:scriptId/versions/:versionId/clone"
"Authorization": ""
"Content-Type": "application/json"
json({
    "comment": "<string>"
})


@name("Get content for a tenant script based on unique script id and version id")
GET "https://{{baseUrl}}/instance/microservice/:identifier/tenants/:tenantToken/scripting/scripts/:scriptId/versions/:versionId/content"
"Authorization": ""



