#!/usr/bin/env dothttp

@name("Buzz")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "BM=1"
}')


@name("LastCycle")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "LC=1"
}')


// Detergent & Softener

@name("AutodoseWasher")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "SetDet=1&SetSoft=1"
}')


@name("OpenDoor")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "OpenDoorOpt=7"
}')


@name("PauseWasher")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "Pa=1"
}')


// ONE, TWO, THREE

@name("SetHardnessWasher")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "HL=1"
}')


@name("Stop")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "Reset=1"
}')


// This is over complicated just to start a program as their is a tones of options and programs...
// Missing W2, ...

@name("Start")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
    "appliance_id": "{{APPLIANCE_ID}}",
    "body": "DelayStart=0&ExtraDry=0&OpenDoorOpt=0&TreinUno=0&Program=P1&MetaCarico=0&OpzProg=p&W1=1&StartStop=1&eco=1"
}')


@name("Checkup")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "StartCheckUp=1"
}')


@name("ResetCheckup")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "Write=1&StartStop=0&Program=11"
}')


@name("UpdateData")
POST "https://{{CANDY_BASE_URI}}/api/v1/commands.json"
"Content-Type": "application/json"
data('{
	"appliance_id": "{{APPLIANCE_ID}}",
	"body": "available_tabs=100&tabs_box_size=20"
}')



