#!/usr/bin/env dothttp

@name("Register")
POST "https://{{apiUrl}}/users/"
"Content-Type": "application/json"
"X-Requested-With": "XMLHttpRequest"
data('{
	"email":"john@jacob.com", 
	"password":"johnnyjacob", 
	"username":"johnjacob", 
	"fullname":"John Jacob", 
	"bio":"left for dead"
}')


@name("Login")
POST "https://{{apiUrl}}/users/login"
"Content-Type": "application/json"
"X-Requested-With": "XMLHttpRequest"
data('{"email":"john@jacob.com", "password":"johnnyjacob"}')


@name("Login and Remember Token")
POST "https://{{apiUrl}}/users/login"
"Content-Type": "application/json"
"X-Requested-With": "XMLHttpRequest"
data('{"email":"john@jacob.com", "password":"johnnyjacob"}')


@name("Current User")
GET "https://{{apiUrl}}/user"
"Content-Type": "application/json"
"X-Requested-With": "XMLHttpRequest"
"Authorization": "{{token}}"


@name("Update User")
PUT "https://{{apiUrl}}/user"
"Content-Type": "application/json"
"X-Requested-With": "XMLHttpRequest"
"Authorization": "Token {{token}}"
data('{"email":"john@jacob.com"}')



