#!/usr/bin/env dothttp

// Login user

@name("Login")
POST "https://localhost/api/users/login"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "email": [
        "rockersandip96@gmail.com"
    ],
    "password": [
        "123456"
    ]
})


// Register User

@name("Signup")
GET "https://localhost/api/users/register"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "name": [
        "Jhon Doe"
    ],
    "password": [
        "123456"
    ],
    "password2": [
        "123456"
    ],
    "email": [
        "jhondoe@gmail.com"
    ]
})


// get all expenses for current user

@name("Get All Expenses")
GET "https://localhost/api/expenses"


// get certain expense data with id

@name("Get Specific Expense")
GET "https://localhost/api/expenses/5cca9066da1d2b07a066b5e7"


// create new expense data

@name("Create Expense")
POST "https://localhost/api/expenses"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "description": [
        "some description"
    ],
    "amount": [
        "22"
    ],
    "category": [
        "Housing"
    ]
})


// update existing expense data

@name("Update Expense")
POST "https://localhost/api/expenses"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "description": [
        "some updated description"
    ],
    "amount": [
        "27"
    ],
    "category": [
        "Housing"
    ]
})


// delete existing expense data

@name("Delete Expense")
DELETE "https://localhost/api/expenses/5ccf435708392f4ff896dd45"
"Content-Type": "application/x-www-form-urlencoded"



