#!/usr/bin/env dothttp

// 
// Retrieve all trades of the company.
// 
// #### Request Params 
// | Name | Value |
// | --- | --- |
// | **includes[]** | Options of options: `work_types`
// 
// > Example `includes[]=work_types`
// 
// #### includes[] Details
// 
// > work_types 
// 
// The Work type information will be returned by includes in the format below:
// 
// ```json
// "work_types": {
//     "data": [
//         {
//             "id": 12,
//             "name": "window",
//             "trade_id": 31,
//             "color": "#0D98BA"
//         },
//         {
//             "id": 11,
//             "name": "clearnig",
//             "trade_id": 31,
//             "color": "#FE6F5E"
//         }
//     ]
// }
// ```
// 
// work_types will have the list of the work types. 
// 
// #####  Work type field detail
// 
// * **id**: Unique project id   
// * **name**: Work type name.
// * **trade_id**: Trade id associated with work type.
// * **color**: Color information associated with work type.
//  
// 

@name("Company Trades ")
GET "https://{{baseUrl}}/company/trades"
"authorization": "Bearer {{accessToken}}"



