#!/usr/bin/env dothttp

// Login

@name("GET SSO Login methods")
GET "https://{{sb_client}}.salesboard.biz/v1/crm/login-methods"
"XREQUESTEDWITH": "WebAppHttpRequest"


// Login

@name("Login with Pipedrive (SB Native)")
POST "https://{{sb_client}}.salesboard.biz/v1/crm/login"
"XREQUESTEDWITH": "mobileHttpRequest"
"Content-Type": "application/x-www-form-urlencoded"



// Login

@name("Login with Google (SB Login WebApp)")
POST "https://{{sb_client}}.salesboard.biz/v1/crm/login"
"XREQUESTEDWITH": "WebAppHttpRequest"
json({
    "crmType": "google",
    "oauthToken": "{{oauthToken}}"
})


// Login

@name("Login with Pipedrive (SB Login WebApp)")
POST "https://{{sb_client}}.salesboard.biz/v1/crm/login"
"XREQUESTEDWITH": "WebAppHttpRequest"



// Login

@name("Login with Salesforce (SF Canvas)")
POST "https://{{sb_client}}.salesboard.biz/v1/crm/login"
"XREQUESTEDWITH": "SalesforceHttpRequest"
"Content-Type": "application/x-www-form-urlencoded"



// Login

@name("Login with Salesforce (SB Native)")
POST "https://{{sb_client}}.salesboard.biz/v1/crm/login"
"XREQUESTEDWITH": "mobileHttpRequest"
"Content-Type": "application/x-www-form-urlencoded"



// Login

@name("Refresh Token (debug)")
POST "https://{{sb_client}}.salesboard.biz/v1/crm/debug-refresh-token"
"XREQUESTEDWITH": "XMLHttpRequest"



// Login

@name("Refresh Token (debug)")
POST "https://{{sb_client}}.salesboard.biz/v1/crm/debug-refresh-token"
"XREQUESTEDWITH": "XMLHttpRequest"



// Login

@name("GET SSO Login methods Copy")
GET "https://{{sb_client}}.salesboard.biz/v1/crm/login-methods"
"XREQUESTEDWITH": "WebAppHttpRequest"



