#!/usr/bin/env dothttp

// #### `filter` Parameter
// Must be set to a [SCIM filtering expression](https://tools.ietf.org/html/rfc7644#section-3.4.2.2) in the form of `occurredAt ge <time-stamp>`, for example `occurredAt ge "2019-09-01T00:00:00Z"`
// 
// The following attributes can be used in filter expressions:
// 
// Attribute | Operators | Notes
// --------- | --------- | -----
// occurredAt | ge | A date-time String for the starting date of the data to include, in ISO 8601 format (yyyy-MM-dd'T'HH:mm:ss.SSS'Z')
// 
// #### `samplePeriod` Parameter
// Specifies the time interval in hours. Must be an integer from 1-8760 (inclusive).
// 
// #### `samplePeriodCount` Parameter
// Specifies the number of sample periods. Must be an integer from 1-1000 (inclusive).
// 
// #### `limit` Parameter
// Optional. Must be an integer from 1-1000 (inclusive).
// <br>
// Limits the number of Apps for which data is returned.

@name("READ Authentications Per Application")
GET "https://{{apiPath}}/environments/{{envID}}/applicationSignons"
"Authorization": "Bearer {{jwtToken}}"
? "limit"= "10"
? "samplePeriod"= "1"
? "samplePeriodCount"= "10"
? 'filter'= 'occurredAt ge "2019-06-01T00:00:00Z"'



