#!/usr/bin/env dothttp

// <h2>Description</h2>
// This operation returns a list of servers for a Company or all Companies which this Tenant Operator is associated with.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_client.htm)
// 
// <h2>Request Headers</h2>
// <table class="tableintopic" border="0" cellspacing="0" cellpadding="2">
// <tbody>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">Name</p>
// </td>
// <td>
// <p class="tabletext">Description</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">Accept</p>
// </td>
// <td>
// <p class="tabletext">The format of the response. Valid values are: application/xml or application/json.</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">Authtoken</p>
// </td>
// <td>
// <p class="tabletext">The authentication token received after successfully logging on.</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">operatorcompanyid</p>
// </td>
// <td>
// <p class="tabletext">Company Id to filter results for this operation.</p>
// </td>
// </tr>
// </tbody>
// </table>

@name("Servers")
GET "https://{{ServerUrl}}/Client"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"operatorcompanyid": "{{OrganizationId}}"
? "Hiddenclients"= "false"
? "includevm"= "true"


// <h2> Description </h2>
// This operation returns a list of users for a Company or all Companies which this Tenant Operator is associated with.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_user.htm)
// 
// 
// <h2>Request Headers</h2>
// <table class="tableintopic" border="0" cellspacing="0" cellpadding="2">
// <tbody>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">Name</p>
// </td>
// <td>
// <p class="tabletext">Description</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">Accept</p>
// </td>
// <td>
// <p class="tabletext">The format of the response. Valid values are: application/xml or application/json.</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">Authtoken</p>
// </td>
// <td>
// <p class="tabletext">The authentication token received after successfully logging on.</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">operatorcompanyid</p>
// </td>
// <td>
// <p class="tabletext">Company Id to filter results for this operation.</p>
// </td>
// </tr>
// </tbody>
// </table>

@name("Users")
GET "https://{{ServerUrl}}/User"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"operatorcompanyid": "{{OrganizationId}}"



