#!/usr/bin/env dothttp

// Get role mappings// 
@name("Get role mappings [SAT] ")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}/groups/{{groupId}}/role-mappings"
"Content-Type": "application/json"


// Update role mappings// 
@name("Update role mappings [SAT] ")
POST "https://{{keycloak_url}}/admin/realms/{{realm}}/groups/{{groupId}}/role-mappings/realm"
"Content-Type": "application/json"
data('[{
	"attributes": {},
	"clientRole": false,
	"composite": false,
	"description": "added role mapping from rest api",
	"name": "Investigator",
	"containerId": "heroes"
}]')


// Get realm-level role mappings// 
@name("Get realm-level role mappings  [SAT] ")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}/groups/{{groupId}}/role-mappings/realm"
"Content-Type": "application/json"


// Get available realm-level role mappings// 
@name("Get available realm-level role mappings  [SAT] ")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}/groups/{{groupId}}/role-mappings/realm/available"
"Content-Type": "application/json"


// Delete realm-level role mappings// 
@name("Delete realm-level role mappings  [SAT] ")
DELETE "https://{{keycloak_url}}/admin/realms/{{realm}}/groups/{{groupId}}/role-mappings/realm"
"Content-Type": "application/json"
data('{
	"attributes": {},
	"clientRole": false,
	"composite": false,
	"description": "added role mapping from rest api",
	"name": "investigator"
}')


// Get effective realm-level role mappings This will recurse all composite roles to get the result.
@name("Get effective realm-level role mappings  [SAT] ")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}/groups/{{groupId}}/role-mappings/realm/composite"
"Content-Type": "application/json"


// Get role mappings
@name("Get role mappings [SAT] ")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}/users/{{userId}}/role-mappings"
"Content-Type": "application/json"


// Get realm-level role mappings
@name("Get realm-level role mappings [SAT] ")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}/users/{{userId}}/role-mappings/realm"
"Content-Type": "application/json"


// Add realm-level role mappings to the user
@name("Add realm-level role mappings to the user [SAT] ")
POST "https://{{keycloak_url}}/admin/realms/{{realm}}/users/{{userId}}/role-mappings/realm"
"Content-Type": "application/json"
data('[{
        "name": "offline_access_2",
        "description": "${role_offline-access}",
        "composite": false,
        "clientRole": false,
        "containerId": "heroes"
}]')


// Delete realm-level role mappings to the user
@name("Delete realm-level role mappings to the user [SAT] ")
DELETE "https://{{keycloak_url}}/admin/realms/{{realm}}/users/{{userId}}/role-mappings/realm"
"Content-Type": "application/json"
data('[{
        "name": "offline_access_2",
        "description": "${role_offline-access}",
        "composite": false,
        "clientRole": false,
        "containerId": "heroes"
}]')


// Get realm-level roles that can be mapped
@name("Get realm-level roles that can be mapped [SAT] ")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}/users/{{userId}}/role-mappings/realm/available"
"Content-Type": "application/json"


// Get effective realm-level role mappings This will recurse all composite roles to get the result
@name("Get effective realm-level roles that can be mapped [SAT] ")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}/users/{{userId}}/role-mappings/realm/composite"
"Content-Type": "application/json"



