#!/usr/bin/env dothttp

// If you are authenticated as the given user, you will see your private events. Otherwise, you'll only see public events.

@name("List events for the authenticated user")
GET "https://{{baseUrl}}/users/:username/events"
? "per_page"= "30"
? "page"= "1"


// This is the user's organization dashboard. You must be authenticated as the user to view this.

@name("List organization events for the authenticated user")
GET "https://{{baseUrl}}/users/:username/events/orgs/:org"
? "per_page"= "30"
? "page"= "1"


@name("List public events for a user")
GET "https://{{baseUrl}}/users/:username/events/public"
? "per_page"= "30"
? "page"= "1"



