#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get All Users Default")
GET "None://{{baseUrl}}/rest/api/3/users"
? "startAt"= "0"
? "maxResults"= "50"


@name("Get All Users")
GET "None://{{baseUrl}}/rest/api/3/users/search"
? "startAt"= "0"
? "maxResults"= "50"



