#!/usr/bin/env dothttp

@name("User List View")
GET "https://{{host}}/services/data/v47.0/sobjects/UserListView/"


@name("User List View Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/UserListView/{ID}/"


@name("Describe User List View")
GET "https://{{host}}/services/data/v47.0/sobjects/UserListView/describe/"



