#!/usr/bin/env dothttp

// See https://documentation.salesboard.biz for more info about webhooks.

@name("GET Hooks")
GET "https://{{sb_client}}.salesboard.biz/v1/hooks"
"XREQUESTEDWITH": "XMLHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"



