#!/usr/bin/env dothttp

# imported from https://raw.githubusercontent.com/fbsamples/WhatsApp-Business-API-Postman-Collection/master/collection.json

@name("Backup-Settings")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49d1c70>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"password": "<Password for Backup>"
}')


@name("Restore-Settings")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49e0130>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"password": "<Password for Backup>",
	"data": "<Data to Restore, from Backup API>"
}')



