#!/usr/bin/env dothttp

// Retrieve all customers flagged as VIP in the database

@name("Get customers")
GET "https://{{url}}/customers"
"Content-Type": "application/json"


// Retrieve a specific customer flagged as VIP in the database using the customer ID

@name("Get customer")
GET "https://{{url}}/customer"
"Content-Type": "application/json"
? "id"= "{{cust_id}}"


// Add a new customer to the VIP database supplying their name and type

@name("Add customer")
POST "https://{{url}}/customer"
"Content-Type": "application/json"
json({
    "name": "Dorothy Zbornak",
    "type": "Individual"
})


// Update a customer in the VIP database supplying their name and type

@name("Update customer")
PATCH "https://{{url}}/customer"
"Content-Type": "application/json"
? "id"= "{{cust_id}}"
json({
    "name": "Rose Nyland",
    "type": "Individual"
})



