#!/usr/bin/env dothttp

// ## Login Api
// 
// Test Admin

@name("CREATE")
POST "http://54.154.59.231/admin/api/v1/foods/5ce5dcf029431c1742d9a2a4/quantities"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1ODU1NDc4MSwiZXhwIjoxNTU5MTU5NTgxfQ.cDfpLWBseQN0NSsKG5oXMgEzzflFlE5Wm7IGid2Ci_0"
json({
    "priceReference": 80.2,
    "quantity": 800
})


// ## Login Api
// 
// Test Admin

@name("READ")
GET "http://54.154.59.231/admin/api/v1/foods/5ce5dcf029431c1742d9a2a4/quantities"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1ODU1NDc4MSwiZXhwIjoxNTU5MTU5NTgxfQ.cDfpLWBseQN0NSsKG5oXMgEzzflFlE5Wm7IGid2Ci_0"


// ## Login Api
// 
// Test Admin

@name("UPDATE")
PUT "http://54.154.59.231/admin/api/v1/foods/quantities/5ce729a489174643bf0a2618"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1ODU1NDc4MSwiZXhwIjoxNTU5MTU5NTgxfQ.cDfpLWBseQN0NSsKG5oXMgEzzflFlE5Wm7IGid2Ci_0"
json({
    "priceReference": 310.5
})


// ## Login Api
// 
// Test Admin

@name("DELETE")
DELETE "http://54.154.59.231/admin/api/v1/foods/quantities/5ce724fe7d952a4273a531fe"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1ODU1NDc4MSwiZXhwIjoxNTU5MTU5NTgxfQ.cDfpLWBseQN0NSsKG5oXMgEzzflFlE5Wm7IGid2Ci_0"



