#!/usr/bin/env dothttp

// Reversa una transacción previamente capturada.

@name("REFUND")
POST "https://{{PAYMENTS_API}}/"
"Content-Type": "application/json"
"Accept": "application/json"
data('{
	"test": {{TEST}},
	"language": "{{LANGUAGE}}",
	"command": "SUBMIT_TRANSACTION",
	"merchant": {
		"apiKey": "{{API_KEY}}",
		"apiLogin": "{{API_LOGIN}}"
	},
	"transaction": {
		"order": {
			"id": 0000000
		},
		"type": "REFUND",
		"reason": "REFUND",
		"parentTransactionId": "PARENT_TRANSACTION_ID"
	}
}')


// Reversa una transacción previamente autorizada.

@name("VOID")
POST "https://{{PAYMENTS_API}}/"
"Content-Type": "application/json"
"Accept": "application/json"
data('{
	"test": {{TEST}},
	"language": "{{LANGUAGE}}",
	"command": "SUBMIT_TRANSACTION",
	"merchant": {
		"apiKey": "{{API_KEY}}",
		"apiLogin": "{{API_LOGIN}}"
	},
	"transaction": {
		"order": {
			"id": 0000000
		},
		"type": "VOID",
		"parentTransactionId": "PARENT_TRANSACTION_ID"
	}
}')



