#!/usr/bin/env dothttp

// <h2>Description</h2>
// This operation creates a Plan.

@name("Plan")
POST "https://{{ServerUrl}}/v2/Plan"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
data('{
  "plan": {
    "featureInfo": {
      "edgedriveInfo": {
        "enableNotificationsForShares": true,
        "auditDriveActivities": true,
        "edgeDriveAssociations": {
          "indexServer": {
            "clientId": 3,
            "clientName": "GDPR_IndexServer"
          }
        }
      }
    },
    "inheritance": {
      "isSealed": true
    },
    "storage": {
      "storagePolicy": {},
      "copy": [
        {
          "active": 1,
          "isDefault": 1,
          "dedupeFlags": {
            "enableDASHFull": 1,
            "useGlobalDedupStore": 1,
            "enableDeduplication": 1,
            "enableClientSideDedup": 1
          },
          "storagePolicyFlags": {
            "blockLevelDedup": 1
          },
          "retentionRules": {
            "retainBackupDataForDays": 730,
            "retentionFlags": {
              "enableDataAging": 1
            }
          },
          "useGlobalPolicy": {
            "storagePolicyName": "SP_AdminConsole",
            "storagePolicyId": 3
          }
        }
      ]
    },
    "laptop": {
      "features": {
        "categoryPermission": {
          "categoriesPermissionList": [
            {
              "permissionId": 146,
              "permissionName": "Edge Drive",
              "_type_": 122
            },
            {
              "permissionId": 148,
              "permissionName": "DLP",
              "_type_": 122
            }
          ]
        }
      },
      "content": {
        "backupContent": [
          {
            "idatype": 2,
            "subClientPolicy": {
              "backupSetEntity": {
                "backupsetName": "Windows subclient policy"
              },
              "subClientList": [
                {
                  "contentOperationType": 1,
                  "fsSubClientProp": {
                    "useVSSForSystemState": false,
                    "backupRetention": true,
                    "backupSystemState": false,
                    "afterDeletionKeepItemsForNDays": 730,
                    "extendRetentionForNDays": -1,
                    "archiverRetentionMode": 2,
                    "enableOnePass": true,
                    "useVSS": true,
                    "extendStoragePolicyRetention": true,
                    "keepAtLeastPreviousVersions": 5,
                    "catalogACL": true,
                    "archiverRetention": false,
                    "olderFileVersionsMode": 2,
                    "backupRetentionMode": 1,
                    "backupSystemStateforFullBkpOnly": false,
                    "keepVersions": 5,
                    "scanOption": 2,
                    "keepOlderVersionsForNDays": -1,
                    "diskCleanupRules": {
                      "fileModifiedTimeOlderThan": 90,
                      "fileSizeGreaterThan": 1024,
                      "afterArchivingRule": 1,
                      "fileCreatedTimeOlderThan": 0,
                      "maximumFileSize": 0,
                      "fileAccessTimeOlderThan": 90,
                      "startCleaningIfLessThan": 50,
                      "archiveReadOnlyFiles": false,
                      "stopCleaningIfupto": 80,
                      "enableArchivingWithRules": true
                    }
                  },
                  "content": [
                    {
                      "path": "\\%Desktop%"
                    },
                    {
                      "path": "\\%Documents%"
                    },
                    {
                      "path": "\\%Office%"
                    },
                    {
                      "path": "\\%Pictures%"
                    },
                    {
                      "path": "\\%Image%"
                    },
                    {
                      "excludePath": "\\%Temporary Files (Windows)%"
                    },
                    {
                      "excludePath": "C:\\Program Files"
                    },
                    {
                      "excludePath": "C:\\Program Files (x86)"
                    },
                    {
                      "excludePath": "C:\\Windows"
                    }
                  ],
                  "commonProperties": {
                    "storageDevice": {
                      "softwareCompression": 2,
                      "deDuplicationOptions": {
                        "enableDeduplication": true,
                        "generateSignature": 1
                      }
                    }
                  }
                }
              ]
            }
          },
          {
            "idatype": 3,
            "subClientPolicy": {
              "backupSetEntity": {
                "backupsetName": "Linux subclient policy"
              },
              "subClientList": [
                {
                  "contentOperationType": 1,
                  "fsSubClientProp": {
                    "backupRetention": true,
                    "afterDeletionKeepItemsForNDays": 730,
                    "extendRetentionForNDays": -1,
                    "archiverRetentionMode": 2,
                    "enableOnePass": true,
                    "useVSS": true,
                    "extendStoragePolicyRetention": true,
                    "keepAtLeastPreviousVersions": 5,
                    "catalogACL": true,
                    "archiverRetention": false,
                    "olderFileVersionsMode": 2,
                    "backupRetentionMode": 1,
                    "keepVersions": 5,
                    "scanOption": 1,
                    "keepOlderVersionsForNDays": -1,
                    "diskCleanupRules": {
                      "fileModifiedTimeOlderThan": 90,
                      "fileSizeGreaterThan": 1024,
                      "afterArchivingRule": 1,
                      "fileCreatedTimeOlderThan": 0,
                      "maximumFileSize": 0,
                      "fileAccessTimeOlderThan": 90,
                      "startCleaningIfLessThan": 50,
                      "archiveReadOnlyFiles": false,
                      "stopCleaningIfupto": 80,
                      "enableArchivingWithRules": true
                    }
                  },
                  "content": [
                    {
                      "path": "/%Desktop%"
                    },
                    {
                      "path": "/%Documents%"
                    },
                    {
                      "path": "/%Office%"
                    },
                    {
                      "path": "/%Pictures%"
                    },
                    {
                      "path": "/%Image%"
                    },
                    {
                      "excludePath": "/%Temporary Files (Linux)%"
                    }
                  ],
                  "commonProperties": {
                    "storageDevice": {
                      "softwareCompression": 2,
                      "deDuplicationOptions": {
                        "enableDeduplication": true,
                        "generateSignature": 1
                      }
                    }
                  }
                }
              ]
            }
          },
          {
            "idatype": 4,
            "subClientPolicy": {
              "backupSetEntity": {
                "backupsetName": "Mac subclient policy"
              },
              "subClientList": [
                {
                  "contentOperationType": 1,
                  "fsSubClientProp": {
                    "backupRetention": true,
                    "afterDeletionKeepItemsForNDays": 730,
                    "extendRetentionForNDays": -1,
                    "archiverRetentionMode": 2,
                    "enableOnePass": true,
                    "useVSS": true,
                    "extendStoragePolicyRetention": true,
                    "keepAtLeastPreviousVersions": 5,
                    "catalogACL": true,
                    "archiverRetention": false,
                    "olderFileVersionsMode": 2,
                    "backupRetentionMode": 1,
                    "keepVersions": 5,
                    "scanOption": 1,
                    "keepOlderVersionsForNDays": -1,
                    "diskCleanupRules": {
                      "fileModifiedTimeOlderThan": 90,
                      "fileSizeGreaterThan": 1024,
                      "afterArchivingRule": 1,
                      "fileCreatedTimeOlderThan": 0,
                      "maximumFileSize": 0,
                      "fileAccessTimeOlderThan": 90,
                      "startCleaningIfLessThan": 50,
                      "archiveReadOnlyFiles": false,
                      "stopCleaningIfupto": 80,
                      "enableArchivingWithRules": true
                    }
                  },
                  "content": [
                    {
                      "path": "/%Desktop%"
                    },
                    {
                      "path": "/%Documents%"
                    },
                    {
                      "path": "/%Office%"
                    },
                    {
                      "path": "/%Pictures%"
                    },
                    {
                      "path": "/%Image%"
                    },
                    {
                      "excludePath": "/%Temporary Files (Mac)%"
                    }
                  ],
                  "commonProperties": {
                    "storageDevice": {
                      "softwareCompression": 2,
                      "deDuplicationOptions": {
                        "enableDeduplication": true,
                        "generateSignature": 1
                      }
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "options": {
      "edgeDriveQuota": 0,
      "quota": 0
    },
    "summary": {
      "description": "Laptop_Plan_Test",
      "restrictions": 1,
      "type": 2,
      "slaInterval": 30,
      "rpoInMinutes": 480,
      "subtype": 33554439,
      "planOwner": {
        "userGUID": "AB0335D1-9923-4248-8740-6C36132C857A",
        "userName": "admin",
        "userId": 1
      },
      "plan": {
        "planName": "Laptop_Plan_Test"
      }
    },
    "alerts": {
      "alerts": [
        {
          "alertName": "No backup for last 4 days",
          "alertId": 8
        },
        {
          "alertName": "Restore Job failed",
          "alertId": 9
        },
        {
          "alertName": "Edge drive quota alert",
          "alertId": 10
        },
        {
          "alertName": "File system quota alert",
          "alertId": 59
        }
      ]
    },
    "schedule": {
      "task": {
        "taskType": 4,
        "taskFlags": {
          "isEdgeDrive": false,
          "isEZOperation": false,
          "disabled": false
        }
      },
      "subTasks": [
        {
          "subTask": {
            "subTaskName": "Incremental Automatic schedule",
            "subTaskType": 2,
            "flags": 65536,
            "operationType": 2,
            "subTaskId": 1
          },
          "pattern": {
            "freq_subday_interval": 0,
            "freq_type": 1024,
            "active_end_time": 0,
            "name": "Incremental Automatic schedule",
            "freq_recurrence_factor": 0
          },
          "options": {
            "backupOpts": {
              "backupLevel": 2,
              "incLevel": 1,
              "runIncrementalBackup": true,
              "cdrOptions": {
                "incremental": true
              },
              "dataOpt": {
                "useCatalogServer": true,
                "followMountPoints": true,
                "daysBetweenSyntheticBackup": 0
              }
            },
            "commonOpts": {
              "automaticSchedulePattern": {
                "maxBackupInterval": 24,
                "ignoreOpWindowPastMaxInterval": false,
                "minBackupIntervalMinutes": 0,
                "maxBackupIntervalMinutes": 0,
                "minSyncInterval": 0,
                "minBackupInterval": 8,
                "minSyncIntervalMinutes": 2,
                "stopIfOnBattery": {
                  "enabled": false
                },
                "acPower": {
                  "enabled": false
                },
                "specfificNetwork": {
                  "enabled": false,
                  "ipAddress": {
                    "subnet": 24,
                    "address": "0.0.0.0"
                  }
                },
                "stopSleepIfBackUp": {
                  "enabled": false
                },
                "newOrModifiedFile": {
                  "enabled": true
                },
                "wiredNetworkConnection": {
                  "enabled": false
                },
                "minNetworkBandwidth": {
                  "enabled": false
                }
              }
            }
          }
        },
        {
          "subTask": {
            "subTaskName": "Space Reclamation",
            "subTaskType": 2,
            "flags": 0,
            "operationType": 2,
            "subTaskId": 1
          },
          "pattern": {
            "freq_subday_interval": 0,
            "freq_type": 1024,
            "active_end_time": 0,
            "name": "Space Reclamation",
            "freq_recurrence_factor": 0
          },
          "options": {
            "backupOpts": {
              "truncateLogsOnSource": false,
              "backupLevel": 4,
              "incLevel": 0,
              "runIncrementalBackup": false,
              "doNotTruncateLog": false,
              "vsaBackupOptions": {
                "backupFailedVMsOnly": false
              },
              "dataOpt": {
                "useCatalogServer": true,
                "followMountPoints": true,
                "useMultiStream": true,
                "useMaximumStreams": true,
                "enforceTransactionLogUsage": false,
                "skipConsistencyCheck": false,
                "maxNumberOfStreams": 1,
                "createNewIndex": true,
                "daysBetweenSyntheticBackup": 90,
                "autoCopy": true
              }
            },
            "commonOpts": {
              "automaticSchedulePattern": {
                "maxBackupInterval": 72,
                "ignoreOpWindowPastMaxInterval": true,
                "minBackupIntervalMinutes": 15,
                "maxBackupIntervalMinutes": 0,
                "minSyncInterval": 0,
                "minBackupInterval": 0,
                "minSyncIntervalMinutes": 0,
                "stopIfOnBattery": {
                  "enabled": false
                },
                "acPower": {
                  "enabled": false
                },
                "specfificNetwork": {
                  "enabled": false,
                  "ipAddress": {
                    "subnet": 24,
                    "address": "0.0.0.0"
                  }
                },
                "stopSleepIfBackUp": {
                  "enabled": false
                },
                "newOrModifiedFile": {
                  "enabled": false
                },
                "wiredNetworkConnection": {
                  "enabled": false
                },
                "minNetworkBandwidth": {
                  "enabled": false
                }
              }
            }
          }
        }
      ]
    }
  }
}')


// <h2>Description</h2>
// This operation returns a list of Plans.

@name("Plan")
GET "https://{{ServerUrl}}/v2/Plan"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"


// <h2>Description</h2>
// This operation returns details of a plan.

@name("Plan Details")
GET "https://{{ServerUrl}}/v2/Plan/{{PlanId}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"


// <h2>Description</h2>
// This operation Updates a Plan.

@name("Plan")
PUT "https://{{ServerUrl}}/v2/Plan/{{PlanId}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
data('{
  "summary": {
    "plan": {
      "planName": "Updated Plan Name"
    }
  }
}')


// <h2>Description</h2>
// This operation deletes a Plan.

@name("Plan")
DELETE "https://{{ServerUrl}}/Plan/{{PlanId}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
? "confirmDelete"= "true"




