#!/usr/bin/env dothttp

// generate cards with this API. 
// 
// note
// 0000000000 0103 11 1
// 
// a number like this willbe displayed for the card
// 
// 1 is serial_no
// 11 is batch
// 
// thus, watch out for the last 3 numbers

@name("/generate card")
POST "https://instant-transaction.herokuapp.com/safepay/generate/card"
"Content-Type": "application/json"
json({
    "type": 4,
    "phone_number": "08121704437"
})


// This endpoint credits the dealer's account with dealer_id specified
// 
// 
// 
// the only required parameter is amount to be credited.

@name("register dealer")
POST "https://instant-transaction.herokuapp.com/safepay/register_account"
json({
    "dealer_id": ""
})


// other phone numbers which would be eligible to carry out transactions are added with this enpoint.
// 
// 
// it take one number at a time.

@name("register sub dealer")
PUT "https://instant-transaction.herokuapp.com/add_number/user000004"
json({
    "phone_number": "07069223521"
})



