#!/usr/bin/env dothttp

// Sends a password reset token to the provided email address

@name("Send Password Reset")
POST "{{protocol}}://{{host}}/api/v1/password-resets/"
"Accept": "application/json; charset=utf-8"
"Content-Type": "application/json; charset=utf-8"
"Authorization": "Key {{apiKey}}"
data('{
	"applicationId": 1,
	"email": "{{identityEmail}}"
}')


@name("Get Password Reset")
GET "{{protocol}}://{{host}}/api/v1/password-resets/{{resetToken}}"
"Accept": "application/json; charset=utf-8"
"Content-Type": "application/json; charset=utf-8"
"Authorization": "Key {{apiKey}}"
data('{
  "email": "{{identityEmail}}"
}')


// Resets the password associated with the provided reset token

@name("Password Reset")
POST "{{protocol}}://{{host}}/api/v1/password-resets/{{resetToken}}"
"Accept": "application/json; charset=utf-8"
"Content-Type": "application/json; charset=utf-8"
"Authorization": "Key {{apiKey}}"
data('{
	"password": "!Password3"
}')


// Resets the password associated with the provided reset token

@name("Password Reset w/ No Reuse")
POST "{{protocol}}://{{host}}/api/v1/password-resets/{{resetToken}}"
"Accept": "application/json; charset=utf-8"
"Content-Type": "application/json; charset=utf-8"
"Authorization": "Key {{apiKey}}"
data('{
    "password": "!Password3",
    "restrictPasswordReuse": true
}')


@name("List Active Sessions")
GET "{{protocol}}://{{host}}/api/v1/sessions"
"Accept": "application/json; charset=utf-8"
"Content-Type": "application/json; charset=utf-8"
"Authorization": "Key {{apiKey}}"
? "status"= "active"




