#!/usr/bin/env dothttp

@name("/procedures")
POST "https://{{base-api-url}}/procedures"
"Content-Type": "application/json"
json({
    "name": "My procedure",
    "description": "Description of my procedure with initial fields",
    "start": false,
    "initials": true
})



