#!/usr/bin/env dothttp

@name("accounts/:account_id/tailored_audiences/:tailored_audience_id/permissions")
GET "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/tailored_audiences/:tailored_audience_id/permissions"


@name("accounts/:account_id/tailored_audiences/:tailored_audience_id/permissions")
POST "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/tailored_audiences/:tailored_audience_id/permissions"


@name("accounts/:account_id/tailored_audiences/:tailored_audience_id/permissions/:tailored_audience_permission_id")
DELETE "https://ads-api.twitter.com/{{version}}/accounts/{{account_id}}/tailored_audiences/:tailored_audience_id/permissions/:tailored_audience_permission_id"




