#!/usr/bin/env dothttp

# imported from http://localhost:8000/Stripe%20API.postman_collection.json

@name("List all cards")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604bd307f0>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Create a card")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604bd32670>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "currency": [
        "<string>"
    ],
    "type": [
        "<string>"
    ],
    "cardholder": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "replacement_for": [
        "<string>"
    ],
    "replacement_reason": [
        "<string>"
    ],
    "shipping[address]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"postal_code\":\"<string>\",\"line2\":\"<string>\",\"state\":\"<string>\"}"
    ],
    "shipping[name]": [
        "<string>"
    ],
    "shipping[service]": [
        "<string>"
    ],
    "shipping[type]": [
        "<string>"
    ],
    "spending_controls[allowed_categories]": [
        "[\"<string>\",\"<string>\"]"
    ],
    "spending_controls[blocked_categories]": [
        "[\"<string>\",\"<string>\"]"
    ],
    "spending_controls[spending_limits]": [
        "[{\"amount\":\"<integer>\",\"interval\":\"<string>\",\"categories\":[\"<string>\",\"<string>\"]},{\"amount\":\"<integer>\",\"interval\":\"<string>\",\"categories\":[\"<string>\",\"<string>\"]}]"
    ],
    "status": [
        "<string>"
    ]
})


@name("Retrieve a card")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604bd32ee0>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Update a card")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604bd345b0>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "cancellation_reason": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "spending_controls[allowed_categories]": [
        "[\"<string>\",\"<string>\"]"
    ],
    "spending_controls[blocked_categories]": [
        "[\"<string>\",\"<string>\"]"
    ],
    "spending_controls[spending_limits]": [
        "[{\"amount\":\"<integer>\",\"interval\":\"<string>\",\"categories\":[\"<string>\",\"<string>\"]},{\"amount\":\"<integer>\",\"interval\":\"<string>\",\"categories\":[\"<string>\",\"<string>\"]}]"
    ],
    "status": [
        "<string>"
    ]
})



