#!/usr/bin/env dothttp

@name("Datacloud Address")
GET "https://{{host}}/services/data/v47.0/sobjects/DatacloudAddress/"


@name("Datacloud Address Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/DatacloudAddress/{ID}/"


@name("Describe Datacloud Address")
GET "https://{{host}}/services/data/v47.0/sobjects/DatacloudAddress/describe/"



