#!/usr/bin/env dothttp

@name("Products Get")
GET "https://{{baseUrl}}/orders/v1/products/details/:id"
"Authorization": "<string>"


@name("Products Get")
GET "https://{{baseUrl}}/orders/v1/products/details/:id/:entityId"
"Authorization": "<string>"



