#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Permission Scheme Grant")
GET "None://{{baseUrl}}/rest/api/3/permissionscheme/:schemeId/permission/:permissionId"
? "expand"= "<string>"


@name("Delete Permission Scheme Grant")
DELETE "None://{{baseUrl}}/rest/api/3/permissionscheme/:schemeId/permission/:permissionId"



