#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Permission Scheme Grant")
GET "https://{{baseUrl}}/rest/api/3/permissionscheme/:schemeId/permission/:permissionId"
? "expand"= "<string>"


@name("Delete Permission Scheme Grant")
DELETE "https://{{baseUrl}}/rest/api/3/permissionscheme/:schemeId/permission/:permissionId"



