#!/usr/bin/env dothttp

@name("Retrieve either one or many BatchPayments for invoices")
GET "https://{{baseUrl}}/BatchPayments"
"If-Modified-Since": "<dateTime>"
"xero-tenant-id": "<string>"
? "where"= "<string>"
? "order"= "<string>"


@name("Create one or many BatchPayments for invoices")
PUT "https://{{baseUrl}}/BatchPayments"
"xero-tenant-id": "<string>"
"Content-Type": "application/json"
? "summarizeErrors"= "false"
json({
    "BatchPayments": [
        {
            "Account": {
                "Code": "<string>",
                "Name": "<string>",
                "AccountID": "<uuid>",
                "Type": "<string>",
                "BankAccountNumber": "<string>",
                "Status": "<string>",
                "Description": "<string>",
                "BankAccountType": "<string>",
                "CurrencyCode": "<string>",
                "TaxType": "<string>",
                "EnablePaymentsToAccount": "<boolean>",
                "ShowInExpenseClaims": "<boolean>",
                "ReportingCode": "<string>",
                "AddToWatchlist": "<boolean>",
                "ValidationErrors": [
                    {
                        "Message": "<string>"
                    },
                    {
                        "Message": "<string>"
                    }
                ]
            },
            "Reference": "<string>",
            "Particulars": "<string>",
            "Code": "<string>",
            "Details": "<string>",
            "Narrative": "<string>",
            "DateString": "<string>",
            "Date": "<string>",
            "Amount": "<double>",
            "Payments": [
                {
                    "Invoice": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Date": "<string>",
                        "DueDate": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "InvoiceNumber": "<string>",
                        "Reference": "<string>",
                        "BrandingThemeID": "<uuid>",
                        "Url": "<string>",
                        "CurrencyCode": "<string>",
                        "CurrencyRate": "<double>",
                        "Status": "<string>",
                        "SentToContact": "<boolean>",
                        "ExpectedPaymentDate": "<string>",
                        "PlannedPaymentDate": "<string>",
                        "InvoiceID": "<uuid>",
                        "RepeatingInvoiceID": "<uuid>",
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "HasErrors": "false",
                        "StatusAttributeString": "<string>",
                        "ValidationErrors": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Warnings": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "CreditNote": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "DueDate": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "FullyPaidOnDate": "<string>",
                        "CreditNoteID": "<uuid>",
                        "CreditNoteNumber": "<string>",
                        "Reference": "<string>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Payments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "BrandingThemeID": "<uuid>",
                        "StatusAttributeString": "<string>",
                        "HasAttachments": "false",
                        "HasErrors": "false",
                        "ValidationErrors": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "Prepayment": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "PrepaymentID": "<uuid>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "Overpayment": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "OverpaymentID": "<uuid>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Payments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "InvoiceNumber": "<string>",
                    "CreditNoteNumber": "<string>",
                    "Account": {
                        "Code": "<string>",
                        "Name": "<string>",
                        "AccountID": "<uuid>",
                        "Type": "<string>",
                        "BankAccountNumber": "<string>",
                        "Status": "<string>",
                        "Description": "<string>",
                        "BankAccountType": "<string>",
                        "CurrencyCode": "<string>",
                        "TaxType": "<string>",
                        "EnablePaymentsToAccount": "<boolean>",
                        "ShowInExpenseClaims": "<boolean>",
                        "ReportingCode": "<string>",
                        "AddToWatchlist": "<boolean>",
                        "ValidationErrors": [
                            {
                                "Message": "<string>"
                            },
                            {
                                "Message": "<string>"
                            }
                        ]
                    },
                    "Code": "<string>",
                    "Date": "<string>",
                    "CurrencyRate": "<double>",
                    "Amount": "<double>",
                    "Reference": "<string>",
                    "IsReconciled": "<boolean>",
                    "Status": "<string>",
                    "PaymentID": "<uuid>",
                    "BankAccountNumber": "<string>",
                    "Particulars": "<string>",
                    "Details": "<string>",
                    "HasAccount": "false",
                    "HasValidationErrors": "false",
                    "StatusAttributeString": "<string>",
                    "ValidationErrors": [
                        {
                            "Message": "<string>"
                        },
                        {
                            "Message": "<string>"
                        }
                    ]
                },
                {
                    "Invoice": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Date": "<string>",
                        "DueDate": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "InvoiceNumber": "<string>",
                        "Reference": "<string>",
                        "BrandingThemeID": "<uuid>",
                        "Url": "<string>",
                        "CurrencyCode": "<string>",
                        "CurrencyRate": "<double>",
                        "Status": "<string>",
                        "SentToContact": "<boolean>",
                        "ExpectedPaymentDate": "<string>",
                        "PlannedPaymentDate": "<string>",
                        "InvoiceID": "<uuid>",
                        "RepeatingInvoiceID": "<uuid>",
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "HasErrors": "false",
                        "StatusAttributeString": "<string>",
                        "ValidationErrors": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Warnings": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "CreditNote": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "DueDate": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "FullyPaidOnDate": "<string>",
                        "CreditNoteID": "<uuid>",
                        "CreditNoteNumber": "<string>",
                        "Reference": "<string>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Payments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "BrandingThemeID": "<uuid>",
                        "StatusAttributeString": "<string>",
                        "HasAttachments": "false",
                        "HasErrors": "false",
                        "ValidationErrors": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "Prepayment": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "PrepaymentID": "<uuid>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "Overpayment": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "OverpaymentID": "<uuid>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Payments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "InvoiceNumber": "<string>",
                    "CreditNoteNumber": "<string>",
                    "Account": {
                        "Code": "<string>",
                        "Name": "<string>",
                        "AccountID": "<uuid>",
                        "Type": "<string>",
                        "BankAccountNumber": "<string>",
                        "Status": "<string>",
                        "Description": "<string>",
                        "BankAccountType": "<string>",
                        "CurrencyCode": "<string>",
                        "TaxType": "<string>",
                        "EnablePaymentsToAccount": "<boolean>",
                        "ShowInExpenseClaims": "<boolean>",
                        "ReportingCode": "<string>",
                        "AddToWatchlist": "<boolean>",
                        "ValidationErrors": [
                            {
                                "Message": "<string>"
                            },
                            {
                                "Message": "<string>"
                            }
                        ]
                    },
                    "Code": "<string>",
                    "Date": "<string>",
                    "CurrencyRate": "<double>",
                    "Amount": "<double>",
                    "Reference": "<string>",
                    "IsReconciled": "<boolean>",
                    "Status": "<string>",
                    "PaymentID": "<uuid>",
                    "BankAccountNumber": "<string>",
                    "Particulars": "<string>",
                    "Details": "<string>",
                    "HasAccount": "false",
                    "HasValidationErrors": "false",
                    "StatusAttributeString": "<string>",
                    "ValidationErrors": [
                        {
                            "Message": "<string>"
                        },
                        {
                            "Message": "<string>"
                        }
                    ]
                }
            ]
        },
        {
            "Account": {
                "Code": "<string>",
                "Name": "<string>",
                "AccountID": "<uuid>",
                "Type": "<string>",
                "BankAccountNumber": "<string>",
                "Status": "<string>",
                "Description": "<string>",
                "BankAccountType": "<string>",
                "CurrencyCode": "<string>",
                "TaxType": "<string>",
                "EnablePaymentsToAccount": "<boolean>",
                "ShowInExpenseClaims": "<boolean>",
                "ReportingCode": "<string>",
                "AddToWatchlist": "<boolean>",
                "ValidationErrors": [
                    {
                        "Message": "<string>"
                    },
                    {
                        "Message": "<string>"
                    }
                ]
            },
            "Reference": "<string>",
            "Particulars": "<string>",
            "Code": "<string>",
            "Details": "<string>",
            "Narrative": "<string>",
            "DateString": "<string>",
            "Date": "<string>",
            "Amount": "<double>",
            "Payments": [
                {
                    "Invoice": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Date": "<string>",
                        "DueDate": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "InvoiceNumber": "<string>",
                        "Reference": "<string>",
                        "BrandingThemeID": "<uuid>",
                        "Url": "<string>",
                        "CurrencyCode": "<string>",
                        "CurrencyRate": "<double>",
                        "Status": "<string>",
                        "SentToContact": "<boolean>",
                        "ExpectedPaymentDate": "<string>",
                        "PlannedPaymentDate": "<string>",
                        "InvoiceID": "<uuid>",
                        "RepeatingInvoiceID": "<uuid>",
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "HasErrors": "false",
                        "StatusAttributeString": "<string>",
                        "ValidationErrors": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Warnings": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "CreditNote": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "DueDate": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "FullyPaidOnDate": "<string>",
                        "CreditNoteID": "<uuid>",
                        "CreditNoteNumber": "<string>",
                        "Reference": "<string>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Payments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "BrandingThemeID": "<uuid>",
                        "StatusAttributeString": "<string>",
                        "HasAttachments": "false",
                        "HasErrors": "false",
                        "ValidationErrors": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "Prepayment": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "PrepaymentID": "<uuid>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "Overpayment": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "OverpaymentID": "<uuid>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Payments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "InvoiceNumber": "<string>",
                    "CreditNoteNumber": "<string>",
                    "Account": {
                        "Code": "<string>",
                        "Name": "<string>",
                        "AccountID": "<uuid>",
                        "Type": "<string>",
                        "BankAccountNumber": "<string>",
                        "Status": "<string>",
                        "Description": "<string>",
                        "BankAccountType": "<string>",
                        "CurrencyCode": "<string>",
                        "TaxType": "<string>",
                        "EnablePaymentsToAccount": "<boolean>",
                        "ShowInExpenseClaims": "<boolean>",
                        "ReportingCode": "<string>",
                        "AddToWatchlist": "<boolean>",
                        "ValidationErrors": [
                            {
                                "Message": "<string>"
                            },
                            {
                                "Message": "<string>"
                            }
                        ]
                    },
                    "Code": "<string>",
                    "Date": "<string>",
                    "CurrencyRate": "<double>",
                    "Amount": "<double>",
                    "Reference": "<string>",
                    "IsReconciled": "<boolean>",
                    "Status": "<string>",
                    "PaymentID": "<uuid>",
                    "BankAccountNumber": "<string>",
                    "Particulars": "<string>",
                    "Details": "<string>",
                    "HasAccount": "false",
                    "HasValidationErrors": "false",
                    "StatusAttributeString": "<string>",
                    "ValidationErrors": [
                        {
                            "Message": "<string>"
                        },
                        {
                            "Message": "<string>"
                        }
                    ]
                },
                {
                    "Invoice": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Date": "<string>",
                        "DueDate": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "InvoiceNumber": "<string>",
                        "Reference": "<string>",
                        "BrandingThemeID": "<uuid>",
                        "Url": "<string>",
                        "CurrencyCode": "<string>",
                        "CurrencyRate": "<double>",
                        "Status": "<string>",
                        "SentToContact": "<boolean>",
                        "ExpectedPaymentDate": "<string>",
                        "PlannedPaymentDate": "<string>",
                        "InvoiceID": "<uuid>",
                        "RepeatingInvoiceID": "<uuid>",
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "HasErrors": "false",
                        "StatusAttributeString": "<string>",
                        "ValidationErrors": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Warnings": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "CreditNote": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "DueDate": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "FullyPaidOnDate": "<string>",
                        "CreditNoteID": "<uuid>",
                        "CreditNoteNumber": "<string>",
                        "Reference": "<string>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Payments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "BrandingThemeID": "<uuid>",
                        "StatusAttributeString": "<string>",
                        "HasAttachments": "false",
                        "HasErrors": "false",
                        "ValidationErrors": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "Prepayment": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "PrepaymentID": "<uuid>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "Overpayment": {
                        "Type": "<string>",
                        "Contact": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "Date": "<string>",
                        "Status": "<string>",
                        "LineAmountTypes": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "LineItems": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "SubTotal": "<double>",
                        "TotalTax": "<double>",
                        "Total": "<double>",
                        "CurrencyCode": "<string>",
                        "OverpaymentID": "<uuid>",
                        "CurrencyRate": "<double>",
                        "RemainingCredit": "<double>",
                        "Allocations": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "AppliedAmount": "<double>",
                        "Payments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "Attachments": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ]
                    },
                    "InvoiceNumber": "<string>",
                    "CreditNoteNumber": "<string>",
                    "Account": {
                        "Code": "<string>",
                        "Name": "<string>",
                        "AccountID": "<uuid>",
                        "Type": "<string>",
                        "BankAccountNumber": "<string>",
                        "Status": "<string>",
                        "Description": "<string>",
                        "BankAccountType": "<string>",
                        "CurrencyCode": "<string>",
                        "TaxType": "<string>",
                        "EnablePaymentsToAccount": "<boolean>",
                        "ShowInExpenseClaims": "<boolean>",
                        "ReportingCode": "<string>",
                        "AddToWatchlist": "<boolean>",
                        "ValidationErrors": [
                            {
                                "Message": "<string>"
                            },
                            {
                                "Message": "<string>"
                            }
                        ]
                    },
                    "Code": "<string>",
                    "Date": "<string>",
                    "CurrencyRate": "<double>",
                    "Amount": "<double>",
                    "Reference": "<string>",
                    "IsReconciled": "<boolean>",
                    "Status": "<string>",
                    "PaymentID": "<uuid>",
                    "BankAccountNumber": "<string>",
                    "Particulars": "<string>",
                    "Details": "<string>",
                    "HasAccount": "false",
                    "HasValidationErrors": "false",
                    "StatusAttributeString": "<string>",
                    "ValidationErrors": [
                        {
                            "Message": "<string>"
                        },
                        {
                            "Message": "<string>"
                        }
                    ]
                }
            ]
        }
    ]
})



