#!/usr/bin/env dothttp

@name("devices/list")
GET "https://mihome4u.co.uk/api/v1/devices/list"
basicauth("{{energenie_username}}", "{{energenie_password}}")


@name("subdevices/list")
GET "https://mihome4u.co.uk/api/v1/subdevices/list"
basicauth("{{energenie_username}}", "{{energenie_password}}")


@name("subdevices/power_off")
GET "https://mihome4u.co.uk/api/v1/subdevices/power_off"
basicauth("{{energenie_username}}", "{{energenie_password}}")
? 'params'= '{"id":{{subdevice_id}},"socket":0}'


@name("subdevices/power_on")
GET "https://mihome4u.co.uk/api/v1/subdevices/power_on"
basicauth("{{energenie_username}}", "{{energenie_password}}")
? 'params'= '{"id":{{subdevice_id}},"socket":0}'


@name("subdevices/get_data")
GET "https://mihome4u.co.uk/api/v1/subdevices/get_data"
basicauth("{{energenie_username}}", "{{energenie_password}}")
? 'params'= '{"start_time":"01-01-2016","end_time":"01-02-2017", "id":{{subdevice_id}}, "data_type":"reported_temperature", "resolution":"daily"}'


@name("notifications/list")
GET "https://mihome4u.co.uk/api/v1/notifications/list"
basicauth("{{energenie_username}}", "{{energenie_password}}")



