#!/usr/bin/env dothttp

// Information about the specified subscription. Also used to delete a subscription, for example, to unfollow a record or a topic.// A subscription ID is returned as part of the response body for follower and following resources, for example, /records/recordId/followers. In addition, subscriptions IDs are also returned in many summary response bodies, such as group summary or user summary.// // https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_subscriptions.htm
@name("Subscriptions Resource - DELETE")
DELETE "https://{{_endpoint}}/services/data/v{{version}}/chatter/subscriptions/:SUBSCRIPTION_ID"



