#!/usr/bin/env dothttp

@name("Get my profile")
GET "https://{{root}}api/v1/myprofile"
"token": "{{token}}"


@name("Update my profile Copy")
PUT "https://{{root}}api/v1/myprofile"
"token": "{{token}}"
"Content-Type": "application/json"
json({
    "username": "Rian",
    "password": "321321",
    "email": "opee101@yopmail.com"
})



