#!/usr/bin/env dothttp

// # Create a new company's setting of "override appointment times"

@name("company_override_appointment_times_create")
POST "https://test1.fullslate.com/api/v2/company/override_appointment_times"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"
data('{
	"services": [42,43],
    "mode": "MANUAL",
    "times": [
        {
            "day": "Mon",
            "fixed_start_time": [
                "07:00:00"
            ]
        },
        {
            "day": "Tue",
            "fixed_start_time": [
                "07:00:00"
            ]
        },
        {
            "day": "Wed",
            "fixed_start_time": [
                "07:00:00"
            ]
        },
        {
            "day": "Sat",
            "fixed_start_time": [
                "06:00:00"
            ]
        }
    ]
}')


// # Update a particular company's override appointment times' setting

@name("company_override_appointment_times_update")
PATCH "https://test1.fullslate.com/api/v2/company/override_appointment_times/2410"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"
data('{
	"services": [10, 20],
    "mode": "MANUAL",
    "times": [
        {
            "day": "Wed",
            "fixed_start_time": [
                "06:00:00"
            ]
        },
        {
            "day": "Sat",
            "fixed_start_time": [
                "06:00:00"
            ]
        }
    ]
}')


// # Display a list of company's override appointment times' settings

@name("company_override_appointment_times_index")
GET "https://test1.fullslate.com/api/v2/company/override_appointment_times"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"


// # Show company's particular override appointment times' setting

@name("company_override_appointment_times_show")
GET "https://test1.fullslate.com/api/v2/company/override_appointment_times/2401"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"


// # Delete a override appointment times of company settings

@name("company_override_appointment_times_destroy")
DELETE "https://test1.fullslate.com/api/v2/company/override_appointment_times/2410"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"




