#!/usr/bin/env dothttp

// Deprecated -- use UserMgmt/RemoveUsers() instead.
@name("{{baseUrl}}/CDirectoryService/BulkDeleteUsers")
POST "https://{{baseUrl}}/CDirectoryService/BulkDeleteUsers"
"Content-Type": "application/json"
data('{
    "Users": "<string>"
}')


// User must be a cloud user.//             Specified user must be you, you must be a system administrator or have user management permissions.//             Specifying 'ServiceUser' will override the 'InEveryBodyRole' property if both are provided.
@name("{{baseUrl}}/CDirectoryService/ChangeUser")
POST "https://{{baseUrl}}/CDirectoryService/ChangeUser"
"Content-Type": "application/json"
data('{
    "CmaRedirectedUserUuid": "<string>",
    "HomeNumber": "<string>",
    "AccountExp": "<dateTime>",
    "ReportsTo": "<string>",
    "DisplayName": "<string>",
    "PasswordNeverExpire": "<boolean>",
    "ID": "<string>",
    "OfficeNumber": "<string>",
    "MobileNumber": "<string>",
    "InEverybodyRole": "<boolean>",
    "ServiceUser": "<boolean>",
    "PreferredCulture": "<string>",
    "Mail": "<string>",
    "Description": "<string>",
    "Name": "<string>"
}')


// You must be a system administrator or have user management permissions.//             Specifying 'ServiceUser' will override the 'InEveryBodyRole' property if both are provided.
@name("{{baseUrl}}/CDirectoryService/CreateUser")
POST "https://{{baseUrl}}/CDirectoryService/CreateUser"
"Content-Type": "application/json"
data('{
    "Name": "<string>",
    "InEverybodyRole": "<boolean>",
    "SendSmsInvite": "<boolean>",
    "InSysAdminRole": "<boolean>",
    "Description": "<string>",
    "MobileNumber": "<string>",
    "Password": "<string>",
    "CmaRedirectedUserUuid": "<string>",
    "ServiceUser": "<boolean>",
    "OfficeNumber": "<string>",
    "ReportsTo": "<string>",
    "SendEmailInvite": "<boolean>",
    "HomeNumber": "<string>",
    "DisplayName": "<string>",
    "ForcePasswordChangeNext": "<boolean>",
    "PasswordNeverExpire": "<boolean>",
    "Mail": "<string>"
}')


// You must be a system administrator or have user management permissions.//                 Specifying 'ServiceUser' will override the 'InEveryBodyRole' property if both are provided.//                 //                 The file(s) must conform to the following format:
@name("{{baseUrl}}/CDirectoryService/CreateUserBulk")
POST "https://{{baseUrl}}/CDirectoryService/CreateUserBulk"
"Content-Type": "application/json"
data('{
    "Name": "<string>",
    "InEverybodyRole": "<boolean>",
    "SendSmsInvite": "<boolean>",
    "InSysAdminRole": "<boolean>",
    "Description": "<string>",
    "MobileNumber": "<string>",
    "Password": "<string>",
    "CmaRedirectedUserUuid": "<string>",
    "ServiceUser": "<boolean>",
    "OfficeNumber": "<string>",
    "ReportsTo": "<string>",
    "SendEmailInvite": "<boolean>",
    "HomeNumber": "<string>",
    "DisplayName": "<string>",
    "ForcePasswordChangeNext": "<boolean>",
    "PasswordNeverExpire": "<boolean>",
    "Mail": "<string>"
}')


// You must be a system administrator or have user management permissions.
@name("{{baseUrl}}/CDirectoryService/CreateUserQuick")
POST "https://{{baseUrl}}/CDirectoryService/CreateUserQuick"
"Content-Type": "application/json"
data('{
    "Mail": "<string>",
    "Name": "<string>",
    "HomeNumber": "<string>",
    "AccountExp": "<dateTime>",
    "ReportsTo": "<string>",
    "PasswordNeverExpire": "<string>",
    "DisplayName": "<string>",
    "OfficeNumber": "<string>",
    "MobileNumber": "<string>",
    "InEverybodyRole": "<string>",
    "Description": "<string>"
}')


// You must be a system administrator or have user management permissions.//             Specifying 'ServiceUser' will override the 'InEveryBodyRole' property if both are provided.
@name("{{baseUrl}}/CDirectoryService/CreateUsers")
POST "https://{{baseUrl}}/CDirectoryService/CreateUsers"
"Content-Type": "application/json"
data('{
    "Rows": [
        {
            "InEverybodyRole": "<boolean>",
            "SendSmsInvite": "<boolean>",
            "InSysAdminRole": "<boolean>",
            "Description": "<string>",
            "Name": "<string>",
            "MobileNumber": "<string>",
            "Password": "<string>",
            "CmaRedirectedUserUuid": "<string>",
            "ServiceUser": "<boolean>",
            "OfficeNumber": "<string>",
            "ReportsTo": "<string>",
            "SendEmailInvite": "<boolean>",
            "HomeNumber": "<string>",
            "DisplayName": "<string>",
            "ForcePasswordChangeNext": "<boolean>",
            "PasswordNeverExpire": "<boolean>",
            "Mail": "<string>"
        },
        {
            "InEverybodyRole": "<boolean>",
            "SendSmsInvite": "<boolean>",
            "InSysAdminRole": "<boolean>",
            "Description": "<string>",
            "Name": "<string>",
            "MobileNumber": "<string>",
            "Password": "<string>",
            "CmaRedirectedUserUuid": "<string>",
            "ServiceUser": "<boolean>",
            "OfficeNumber": "<string>",
            "ReportsTo": "<string>",
            "SendEmailInvite": "<boolean>",
            "HomeNumber": "<string>",
            "DisplayName": "<string>",
            "ForcePasswordChangeNext": "<boolean>",
            "PasswordNeverExpire": "<boolean>",
            "Mail": "<string>"
        }
    ]
}')


@name("{{baseUrl}}/CDirectoryService/Delete")
POST "https://{{baseUrl}}/CDirectoryService/Delete"
? "id"= "<string>"


// (Deprecated - use UserMgmt/RemoveUser instead.)//             You must be a system administrator or have user management permissions.  User must exist, and cannot be the current user.//             Cloud users will be deleted; users from other directory services will be removed from the cloud.
@name("{{baseUrl}}/CDirectoryService/DeleteUser")
POST "https://{{baseUrl}}/CDirectoryService/DeleteUser"
? "ID"= "<string>"


// You must be a system administrator or have user management permissions.  User is exempt from MFA login for a specified amount of time.
@name("{{baseUrl}}/CDirectoryService/ExemptUserFromMfa")
POST "https://{{baseUrl}}/CDirectoryService/ExemptUserFromMfa"
? "ID"= "<string>"
? "timespan"= "<integer>"


@name("{{baseUrl}}/CDirectoryService/GetBulkImportWithExtAtt")
POST "https://{{baseUrl}}/CDirectoryService/GetBulkImportWithExtAtt"


// You must be a system administrator or have user management permissions.
@name("{{baseUrl}}/CDirectoryService/GetTechSupportUser")
POST "https://{{baseUrl}}/CDirectoryService/GetTechSupportUser"


// Specified user must be you, you must be a system administrator, or have user management permissions.
@name("{{baseUrl}}/CDirectoryService/GetUser")
POST "https://{{baseUrl}}/CDirectoryService/GetUser"
"Content-Type": "application/json"
data('{
    "ID": "<string>"
}')


@name("{{baseUrl}}/CDirectoryService/GetUserAttributes")
POST "https://{{baseUrl}}/CDirectoryService/GetUserAttributes"


// Specified user must be you, you must be a system administrator, or have user management permissions.
@name("{{baseUrl}}/CDirectoryService/GetUserByName")
POST "https://{{baseUrl}}/CDirectoryService/GetUserByName"
"Content-Type": "application/json"
data('{
    "username": "<string>"
}')


@name("{{baseUrl}}/CDirectoryService/GetUsers")
POST "https://{{baseUrl}}/CDirectoryService/GetUsers"


@name("{{baseUrl}}/CDirectoryService/GetUsersFromCsvFile")
POST "https://{{baseUrl}}/CDirectoryService/GetUsersFromCsvFile"
"Content-Type": "application/json"
data('{
    "FileName": {
        "InEverybodyRole": "<boolean>",
        "SendSmsInvite": "<boolean>",
        "InSysAdminRole": "<boolean>",
        "Description": "<string>",
        "Name": "<string>",
        "MobileNumber": "<string>",
        "Password": "<string>",
        "CmaRedirectedUserUuid": "<string>",
        "ServiceUser": "<boolean>",
        "OfficeNumber": "<string>",
        "ReportsTo": "<string>",
        "SendEmailInvite": "<boolean>",
        "HomeNumber": "<string>",
        "DisplayName": "<string>",
        "ForcePasswordChangeNext": "<boolean>",
        "PasswordNeverExpire": "<boolean>",
        "Mail": "<string>"
    }
}')


// You must be a system administrator or have user management permissions.  Support will receive portal access for the specified time period.
@name("{{baseUrl}}/CDirectoryService/GrantAccess")
POST "https://{{baseUrl}}/CDirectoryService/GrantAccess"
"Content-Type": "application/json"
data('{
    "SupportAccessTimeInMinute": "<integer>",
    "SupportEmailAddress": "<string>",
    "SendEmail": "<boolean>"
}')


// You must be a system administrator or have user management permissions.  User cached identity in the cloud is reloaded from their directory service.//             Useful when user details have changed in their remote directory service, but have not yet been pushed to the cloud.
@name("{{baseUrl}}/CDirectoryService/RefreshToken")
POST "https://{{baseUrl}}/CDirectoryService/RefreshToken"
? "ID"= "<string>"
? "directoryServiceUuid"= "<string>"


// You must be a system administrator or have user management permissions.//             May perform the updates to users asyncronously if list of users is large (will return before updates are complete).
@name("{{baseUrl}}/CDirectoryService/RemoveAuthSource")
POST "https://{{baseUrl}}/CDirectoryService/RemoveAuthSource"
"Content-Type": "application/json"
data('{
    "Users": [
        "<string>",
        "<string>"
    ],
    "SendInvites": "<boolean>"
}')


// You must be a system administrator or have user management permissions.//             Will perform the updates to users asyncronously (will return before updates are complete).
@name("{{baseUrl}}/CDirectoryService/RemoveFederationAuthSource")
POST "https://{{baseUrl}}/CDirectoryService/RemoveFederationAuthSource"
? "federationUuid"= "<string>"
? "sendInvites"= "<string>"


// Specified user must be you, you must be a system administrator or have user management permissions.//                 The file is attached to the call so need to figure out how to document that without bodyargs
@name("{{baseUrl}}/CDirectoryService/SetUserPicture")
POST "https://{{baseUrl}}/CDirectoryService/SetUserPicture"
"Content-Type": "application/json"
? "ID"= "<string>"
data('{
    "File": "<object>"
}')


// You must be a system administrator or have user management permissions.  Specified cloud user may not be the default system adminstrator.//             Specified new state may either be 'None' or include one or more of the following values (comma separated): Locked, Disabled, or Expired.
@name("{{baseUrl}}/CDirectoryService/SetUserState")
POST "https://{{baseUrl}}/CDirectoryService/SetUserState"
"Content-Type": "application/json"
data('{
    "ID": "<string>",
    "state": "<string>"
}')


@name("{{baseUrl}}/CDirectoryService/StandardJsonResultWithPermissionCheck")
POST "https://{{baseUrl}}/CDirectoryService/StandardJsonResultWithPermissionCheck"
? "action"= "<string>"


// Seems to be second part of a two part call.
@name("{{baseUrl}}/CDirectoryService/SubmitUploadedFile")
POST "https://{{baseUrl}}/CDirectoryService/SubmitUploadedFile"
"Content-Type": "application/json"
data('{
    "File": "<object>"
}')



