#!/usr/bin/env dothttp

// Gets a project by its `id`. Returns a `404 Not Found` status if projects are disabled. If you do not have sufficient privileges to perform this action, a `401 Unauthorized` or `410 Gone` status is returned.

@name("Get a project")
GET "https://{{baseUrl}}/projects/:project_id"


// Updates a project board's information. Returns a `404 Not Found` status if projects are disabled. If you do not have sufficient privileges to perform this action, a `401 Unauthorized` or `410 Gone` status is returned.

@name("Update a project")
PATCH "https://{{baseUrl}}/projects/:project_id"
"Content-Type": "application/json"
json({
    "name": "<string>",
    "body": "<string>",
    "state": "<string>",
    "organization_permission": "<string>",
    "private": "<boolean>"
})


// Deletes a project board. Returns a `404 Not Found` status if projects are disabled.

@name("Delete a project")
DELETE "https://{{baseUrl}}/projects/:project_id"



