#!/usr/bin/env dothttp

// Lists all active Webex devices associated with the authenticated user, such as devices activated in personal mode, or devices to which the user is actively paired or using. Administrators can list all devices within an organization.// // https://developer.webex.com/docs/api/v1/devices/list-devices
@name("List Devices")
GET "https://{{WEBEXAPI}}/devices"
"Authorization": "Bearer {{access_token}}"


// Shows details for a device, by ID.// Specify the device ID in the deviceId parameter in the URI.// // https://developer.webex.com/docs/api/v1/devices/get-device-details
@name("Get Device Details")
GET "https://{{WEBEXAPI}}/devices/{{_device}}"
"Authorization": "Bearer {{access_token}}"


// Lists all device configurations associated with the given device ID. Administrators can list configurations for all devices within an organization.// // https://developer.webex.com/docs/api/v1/device-configurations/list-device-configurations-for-device
@name("Get Device Configurations Details")
GET "https://{{WEBEXAPI}}/deviceConfigurations"
"Authorization": "Bearer {{access_token}}"
? "deviceId"= "{{_device}}"


// Lists all device configurations associated with the given device ID. Administrators can list configurations for all devices within an organization.// // https://developer.webex.com/docs/api/v1/device-configurations/list-device-configurations-for-device
@name("Get Device Configurations Details (with key)")
GET "https://{{WEBEXAPI}}/deviceConfigurations"
"Authorization": "Bearer {{access_token}}"
? "deviceId"= "{{_device}}"
? "key"= "Audio.Ultrasound.*"


// Update device configurations by device ID. Update requests use [JSON Patch](https://tools.ietf.org/html/rfc6902) syntax.// // https://developer.webex.com/docs/api/v1/device-configurations/update-device-configurations
@name("Update Device Configurations")
PATCH "https://{{WEBEXAPI}}/deviceConfigurations"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json-patch+json"
? "deviceId"= "{{_device}}"
json([
    {
        "op": "replace",
        "path": "Audio.Ultrasound.MaxVolume/sources/configured/value",
        "value": 70
    }
])



