#!/usr/bin/env dothttp

@name("Get camera analytics live")
GET "https://api.meraki.com/api/v0/devices/Q2FV-RQJM-572T/camera/analytics/live"
"Accept": "application/json"
"Content-Type": "application/json"
"X-Cisco-Meraki-API-Key": "{{api_key}}"
? "timespan"= "400"


@name("Get camera analytics recent")
GET "https://api.meraki.com/api/v0/devices/Q2FV-RQJM-572T/camera/analytics/recent"
"Accept": "application/json"
"Content-Type": "application/json"
"X-Cisco-Meraki-API-Key": "{{api_key}}"


@name("Get camera analytics overview")
GET "https://api.meraki.com/api/v0/devices/Q2FV-RQJM-572T/camera/analytics/overview"
"Accept": "application/json"
"Content-Type": "application/json"
"X-Cisco-Meraki-API-Key": "{{api_key}}"



