#!/usr/bin/env dothttp

@name("Create Survey")
POST "http://localhost/survey/create"
"organizer-auth": "tokenorganizer5687jfdkfldsfj"
json({
    "event": "5eba630e95c817184c9dc6a6",
    "questions": {
        "question": {
            "text": "Que pensez-vous des bananes?",
            "user": "5eb9c6b295354d09bb305240"
        },
        "answers": [
            {
                "index": 1,
                "answer": "c'est biens "
            },
            {
                "index": 2,
                "answer": "c'est nul"
            },
            {
                "index": 3,
                "answer": "pas d'avis"
            }
        ]
    }
})


@name("Show Survey")
GET "http://localhost/survey/show/"
json({
    "list_of_organizers": [
        "5eb9c6b295354d09bb305240",
        "5eb9c6bb95354d09bb305241"
    ],
    "list_of_members": [],
    "_id": "5eb9c71195354d09bb305242",
    "name": "event1udpdate",
    "description": "no description",
    "start_date": "2002-12-09T00:00:00.000Z",
    "end_date": "2002-12-19T00:00:00.000Z",
    "location": "paris",
    "cover_photograph": "photo url",
    "event_mode": "private",
    "__v": 0
})


@name("Show Survey By Id")
GET "http://localhost/survey/show/5eb9c71195354d09bb305242"
json({
    "list_of_organizers": [
        "5eb9c6b295354d09bb305240",
        "5eb9c6bb95354d09bb305241"
    ],
    "list_of_members": [],
    "_id": "5eb9c71195354d09bb305242",
    "name": "event1udpdate",
    "description": "no description",
    "start_date": "2002-12-09T00:00:00.000Z",
    "end_date": "2002-12-19T00:00:00.000Z",
    "location": "paris",
    "cover_photograph": "photo url",
    "event_mode": "private",
    "__v": 0
})


@name("Update Survey By Id")
PUT "http://localhost/survey/update/5eb9c71195354d09bb305242"
"member-auth": "tokenmember46786djfdsklmfkmdlscsq"
json({
    "list_of_organizers": [
        "5eb9c6b295354d09bb305240",
        "5eb9c6bb95354d09bb305241"
    ],
    "list_of_members": [],
    "_id": "5eb9c71195354d09bb305242",
    "name": "event1udpdate",
    "description": "this is a description",
    "start_date": "2002-12-09T00:00:00.000Z",
    "end_date": "2002-12-19T00:00:00.000Z",
    "location": "paris",
    "cover_photograph": "photo url",
    "event_mode": "private",
    "__v": 0
})


@name("Update Survey Answer")
PUT "http://localhost/survey/update/answer/5ebe5f7564dd4f0809ca3abe"
"member-auth": "tokenmember46786djfdsklmfkmdlscsq"
json({
    "answerChoice": [
        {
            "userAnswer": "5eb9c6b295354d09bb305240",
            "userChoiceIndex": 2
        }
    ]
})


@name("Delete Survey By Id")
DELETE "http://localhost/survey/destroy/5e5f8dfef32b8b655dde43f1"
"organizer-auth": "tokenorganizer5687jfdkfldsfj"
json({
    "first_name": "firstname_1dddE1"
})


@name("Search Survey")
POST "http://localhost/survey/search"



