#!/usr/bin/env dothttp

// List the floor plans that belong to your network

@name("getNetworkFloorPlans")
GET "https://{{baseUrl}}/networks/:networkId/floorPlans"
"Accept": "*/*"



// Upload a floor plan
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// name| string| The name of your floor plan.
// center| object| The longitude and latitude of the center of your floor plan. The 'center' or two adjacent corners (e.g. 'topLeftCorner' and 'bottomLeftCorner') must be specified. If 'center' is specified, the floor plan is placed over that point with no rotation. If two adjacent corners are specified, the floor plan is rotated to line up with the two specified points. The aspect ratio of the floor plan's image is preserved regardless of which corners/center are specified. (This means if that more than two corners are specified, only two corners may be used to preserve the floor plan's aspect ratio.). No two points can have the same latitude, longitude pair.
// bottomLeftCorner| object| The longitude and latitude of the bottom left corner of your floor plan.
// bottomRightCorner| object| The longitude and latitude of the bottom right corner of your floor plan.
// topLeftCorner| object| The longitude and latitude of the top left corner of your floor plan.
// topRightCorner| object| The longitude and latitude of the top right corner of your floor plan.
// imageContents| string| The file contents (a base 64 encoded string) of your image. Supported formats are PNG, GIF, and JPG. Note that all images are saved as PNG files, regardless of the format they are uploaded in.

@name("createNetworkFloorPlan")
POST "https://{{baseUrl}}/networks/:networkId/floorPlans"
"Accept": "*/*"
"Content-Type": "application/json"
data('{}')


// Find a floor plan by ID

@name("getNetworkFloorPlan")
GET "https://{{baseUrl}}/networks/:networkId/floorPlans/:floorPlanId"
"Accept": "*/*"



// Update a floor plan's geolocation and other meta data
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// name| string| The name of your floor plan.
// center| object| The longitude and latitude of the center of your floor plan. If you want to change the geolocation data of your floor plan, either the 'center' or two adjacent corners (e.g. 'topLeftCorner' and 'bottomLeftCorner') must be specified. If 'center' is specified, the floor plan is placed over that point with no rotation. If two adjacent corners are specified, the floor plan is rotated to line up with the two specified points. The aspect ratio of the floor plan's image is preserved regardless of which corners/center are specified. (This means if that more than two corners are specified, only two corners may be used to preserve the floor plan's aspect ratio.). No two points can have the same latitude, longitude pair.
// bottomLeftCorner| object| The longitude and latitude of the bottom left corner of your floor plan.
// bottomRightCorner| object| The longitude and latitude of the bottom right corner of your floor plan.
// topLeftCorner| object| The longitude and latitude of the top left corner of your floor plan.
// topRightCorner| object| The longitude and latitude of the top right corner of your floor plan.
// imageContents| string| The file contents (a base 64 encoded string) of your new image. Supported formats are PNG, GIF, and JPG. Note that all images are saved as PNG files, regardless of the format they are uploaded in. If you upload a new image, and you do NOT specify any new geolocation fields ('center, 'topLeftCorner', etc), the floor plan will be recentered with no rotation in order to maintain the aspect ratio of your new image.

@name("updateNetworkFloorPlan")
PUT "https://{{baseUrl}}/networks/:networkId/floorPlans/:floorPlanId"
"Accept": "*/*"
"Content-Type": "application/json"
data('{}')


// Destroy a floor plan

@name("deleteNetworkFloorPlan")
DELETE "https://{{baseUrl}}/networks/:networkId/floorPlans/:floorPlanId"
"Accept": "*/*"




