#!/usr/bin/env dothttp

// Retrieves a specific Episode by its UUID.

@name("/episodes/:episode_id")
GET "https://{{host}}/episodes/{{episode_id}}"


// Retrieves all Authors for a specific Episode.

@name("/episodes/:episode_id/authors")
GET "https://{{host}}/episodes/{{episode_id}}/authors"


// Retrieves all Keywords for a specific Episode.

@name("/episodes/:episode_id/keywords")
GET "https://{{host}}/episodes/{{episode_id}}/keywords"


// Retrieves a specific Keyword by its ID for a specific Episode.

@name("/episodes/:episode_id/keywords/:keyword_id")
GET "https://{{host}}/episodes/{{episode_id}}/keywords/{{keyword_id}}"


// Retrieves all Markers for a specific Episode.

@name("/episodes/:episode_id/markers")
GET "https://{{host}}/episodes/{{episode_id}}/markers"


// Retrieves a specific Marker by its ID for a specific Episode.

@name("/episodes/:episode_id/markers/:marker_id")
GET "https://{{host}}/episodes/{{episode_id}}/markers/{{marker_id}}"


// Retrieves all Metadata for a specific Episode.

@name("/episodes/:episode_id/metadata")
GET "https://{{host}}/episodes/{{episode_id}}/metadata"



