#!/usr/bin/env dothttp

// This pulls all the tweets for @InfoatSEHD and saves them to the environment.

@name("Appling County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:InfoatSEHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @InfoatSEHD and saves them to the environment.

@name("Bacon County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:InfoatSEHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @InfoatSEHD and saves them to the environment.

@name("Bulloch County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:InfoatSEHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @coastalhealth91 and saves them to the environment.

@name("Camden County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:coastalhealth91"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @InfoatSEHD and saves them to the environment.

@name("Candler County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:InfoatSEHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @InfoatSEHD and saves them to the environment.

@name("Charlton County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:InfoatSEHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @coastalhealth91 and saves them to the environment.

@name("Chatham County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:coastalhealth91"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @cdphga and saves them to the environment.

@name("Cobb & Douglas Public Health")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:cdphga"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @InfoatSEHD and saves them to the environment.

@name("Coffee County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:InfoatSEHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @NGAHealthDist and saves them to the environment.

@name("District 1, Unit 2: North Georgia Health District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:NGAHealthDist"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @CCBOH and saves them to the environment.

@name("District 3, Unit 3: Clayton County Health District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:CCBOH"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @healthydekalb and saves them to the environment.

@name("District 3, Unit 5: DeKalb Health District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:healthydekalb"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @D4publichealth and saves them to the environment.

@name("District 4: LaGrange Health District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:D4publichealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @SCHD_5_1 and saves them to the environment.

@name("District 5, Unit 1: South Central District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:SCHD_5_1"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @NCHD52 and saves them to the environment.

@name("District 5, Unit 2: North Central District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:NCHD52"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @EastCentralPH and saves them to the environment.

@name("District 6: East Central Health District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:EastCentralPH"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @SouthHealthDist and saves them to the environment.

@name("District 8, Unit 1: South Health District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:SouthHealthDist"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @InfoatSEHD and saves them to the environment.

@name("District 9, Unit 2: Southeast Health District")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:InfoatSEHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @CDPHga and saves them to the environment.

@name("Douglas County Board of Health")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:CDPHga"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @coastalhealth91 and saves them to the environment.

@name("Effingham County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:coastalhealth91"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @InfoatSEHD and saves them to the environment.

@name("Evans County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:InfoatSEHD"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @coastalhealth91 and saves them to the environment.

@name("Glynn County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:coastalhealth91"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @coastalhealth91 and saves them to the environment.

@name("Liberty County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:coastalhealth91"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @coastalhealth91 and saves them to the environment.

@name("Long County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:coastalhealth91"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @coastalhealth91 and saves them to the environment.

@name("McIntosh County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:coastalhealth91"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @infoatsehd and saves them to the environment.

@name("Pierce County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:infoatsehd"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @infoatsehd and saves them to the environment.

@name("Tattnall County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:infoatsehd"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @D4publichealth and saves them to the environment.

@name("Upson County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:D4publichealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"



