#!/usr/bin/env dothttp

@name("/wc/v3/products/reviews/:id")
GET "https://{{baseUrl}}/wc/v3/products/reviews/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "context"= "view"
? "context"= "view"


@name("/wc/v3/products/reviews/:id")
POST "https://{{baseUrl}}/wc/v3/products/reviews/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
"Content-Type": "multipart/form-data"
files(
	("product_id", "<string>"),
	("status", "["<string>","<string>"]"),
	("reviewer", "<string>"),
	("reviewer_email", "<email>"),
	("review", "<string>"),
	("rating", "<string>")
)


@name("/wc/v3/products/reviews/:id")
PUT "https://{{baseUrl}}/wc/v3/products/reviews/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "product_id"= "<string>"
? "status"= "<string>"
? "status"= "<string>"
? "reviewer"= "<string>"
? "reviewer_email"= "<email>"
? "review"= "<string>"
? "rating"= "<string>"


@name("/wc/v3/products/reviews/:id")
PATCH "https://{{baseUrl}}/wc/v3/products/reviews/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "product_id"= "<string>"
? "status"= "<string>"
? "status"= "<string>"
? "reviewer"= "<string>"
? "reviewer_email"= "<email>"
? "review"= "<string>"
? "rating"= "<string>"


@name("/wc/v3/products/reviews/:id")
DELETE "https://{{baseUrl}}/wc/v3/products/reviews/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "force"= "<string>"



