#!/usr/bin/env dothttp

@name("Create job Query")
POST "https://{{_endpoint}}/services/data/v{{version}}/jobs/query"
"Content-Type": "application/json"
json({
    "operation": "query",
    "query": "SELECT fields FROM object WHERE filter",
    "contentType": "CSV",
    "columnDelimiter": "BACKQUOTE | CARET | COMMA | PIPE | SEMICOLON | TAB",
    "lineEnding": "CRLF | LF"
})


@name("Abort a Job Query")
PATCH "https://{{_endpoint}}/services/data/v{{version}}/jobs/query/{{_jobId}}"
"Content-Type": "application/json"
json({
    "state": "Aborted"
})


@name("Get Job Info Query")
GET "https://{{_endpoint}}/services/data/v{{version}}/jobs/query/{{_jobId}}"
"Content-Type": "application/json"


@name("Delete Job Query")
DELETE "https://{{_endpoint}}/services/data/v{{version}}/jobs/query/{{_jobId}}"
"Content-Type": "application/json"



@name("Get Job Query Result")
GET "https://{{_endpoint}}/services/data/v{{version}}/jobs/query/{{_jobId}}/results"
"Content-Type": "application/json"
"Accept": "test/csv"


@name("Get All Query Jobs")
GET "https://{{_endpoint}}/services/data/v{{version}}/jobs/query"
"Content-Type": "application/json"
? "isPkChunkingEnabled"= "false"



