#!/usr/bin/env dothttp

@name("Retrieve the properties and relationships of an object of type attachments for Dynamics 365 Business Central.")
GET "https://{{baseUrl}}/companies({{company_id}})/journals({{journal_id}})/journalLines({{journalLine_id}})/attachments({{attachments_parentId}},{{attachments_id}})"
? "$select"= "<string>,<string>"


@name("Deletes an object of type attachments in Dynamics 365 Business Central")
DELETE "https://{{baseUrl}}/companies({{company_id}})/journals({{journal_id}})/journalLines({{journalLine_id}})/attachments({{attachments_parentId}},{{attachments_id}})"


@name("Updates an object of type attachments in Dynamics 365 Business Central")
PATCH "https://{{baseUrl}}/companies({{company_id}})/journals({{journal_id}})/journalLines({{journalLine_id}})/attachments({{attachments_parentId}},{{attachments_id}})"
"Content-Type": "<string>"
"If-Match": "<string>"
"Content-Type": "application/json"
data('{
    "parentId": "<uuid>",
    "id": "<uuid>",
    "fileName": "<string>",
    "byteSize": "<integer>",
    "content": "<binary>",
    "lastModifiedDateTime": "<dateTime>"
}')



