#!/usr/bin/env dothttp

// To retrieve the data of profiles of your organization.
@name("Profiles")
GET "https://{{api-domain}}/crm/v2.1/settings/profiles"
"Authorization": "{{authorization-token}}"



