#!/usr/bin/env dothttp

// Signs data using the specified passphrase for the private key.
// 
// Returns a json/application object with the following values:
// - status: "success" or "failure".
// - Signature: if successful, a Base64 string of the signature.

@name("/dsa/sign")
POST "https://yourendpoint.sr2solutions.com/aes/sign"
"x-licenseid": "6fdad058-eff1-488c-82b0-b3fd5a5bc737"
"x-licensesecret": "somebase64secret"
"Content-Type": "application/json"
data('{
	"Plaintext": "A Buffer object with the encryption key to use in Base64 format"
}')


// Verifies data against its signature.
// 
// Returns a json/application object with the following values:
// - status: "success" or "failure".
// - Verified: if successful, a boolean value that is true if the signature was verified or false if the signature failed verification.

@name("/dsa/verify")
POST "https://yourendpoint.sr2solutions.com/aes/verify"
"Content-Type": "application/json"
data('{
	"Plaintext": "A Buffer object with the encryption key to use in Base64 format",
	"Signature": "A Base64 string of the signature to verify."
}')



