#!/usr/bin/env dothttp

// Request a Two Factor Authentication via text message. This method generates a pin and sends it via text message to the user.

@name("Request a 2FA Pin")
POST "https://app.gateway.smsend.it/API/v1.0/REST/2fa/request"
"user_key": ""
"Session_key": ""
files(
	("recipient", "" , "String"),
	("senderName", "" , "String"),
	("expiry", "60" , "Integer"),
	("messageBody", "" , "String")
)


// Verify that the pin inserted by the user is valid.

@name("Verify a 2FA Pin")
POST "https://app.gateway.smsend.it/API/v1.0/REST/2fa/verify"
"user_key": ""
"Session_key": ""
files(
	("recipient", "" , "String"),
	("pin", "" , "String")
)



