#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Create Issue Link")
POST "{{baseUrl}}/rest/api/3/issueLink"
"Content-Type": "application/json"
data('{
    "inwardIssue": {
        "id": "<string>",
        "key": "<string>"
    },
    "outwardIssue": {
        "id": "<string>",
        "key": "<string>"
    },
    "type": {
        "id": "<string>",
        "name": "<string>",
        "inward": "<string>",
        "outward": "<string>"
    },
    "comment": {
        "body": {},
        "visibility": {
            "type": "<string>",
            "value": "<string>"
        },
        "properties": [
            {
                "key": "<string>",
                "value": {}
            },
            {
                "key": "<string>",
                "value": {}
            }
        ]
    }
}')



