#!/usr/bin/env dothttp

@name("register user")
POST "https://localhost/api/user/new-user-signup"
"Content-Type": "application/json"
files(
	("email", "ahmedbaig@gmail.com"),
	("password", "abc123"),
	("firstName", "ahmed"),
	("lastName", "baig"),
	("role", "user"),
	("terms", "true")
)


@name("login user")
POST "https://192.168.8.100/api/user/login-user"
files(
	("email", "ahmedbaig54@yahoo.com"),
	("password", "Baig35211")
)


@name("get user from ID")
GET "https://192.168.8.100/api/user/get-user/:userId/:token"


@name("Upload Qualification")
GET "https://{{host}}/"


@name("upload profile picture")
POST "https://locahost/api/user/upload-user-picture/:userId/:token"
files(
	("image", "None")
)


@name("Forgot Password email")
POST "https://localhost/api/user/send-forgot-password-email"
files(
	("email", "")
)


@name("Reset Password")
POST "https://localhost/api/user/reset-password/:forgotPasswordToken"
files(
	("password", "")
)


@name("Update User")
POST "https://localhost/api/user/update/:userId/:token"



@name("New User From Staff")
POST "https://localhost/api/user/new-user/:token"



@name("New User From Admin")
POST "https://localhost/api/user/new-user-admin/:token"



@name("Remove User")
POST "https://localhost/api/user/remove-user/:token"
files(
	("id", "")
)


@name("Upload Qualification")
POST "https://localhost/api/user/upload-qualification/:token"
files(
	("image", "None")
)


@name("Activate Account")
GET "https://localhost/api/user/activate-account/:token"



@name("Get Users")
GET "https://localhost/api/user/get-users/:token"




