#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Check team permissions for a project")
GET "https://{{baseUrl}}/orgs/{{org}}/teams/{{team_slug}}/projects/{{project_id}}/"


@name("Add or update team project permissions")
PUT "https://{{baseUrl}}/orgs/{{org}}/teams/{{team_slug}}/projects/{{project_id}}/"
"Content-Type": "application/json"
json({
    "permission": "admin"
})


@name("Remove a project from a team")
DELETE "https://{{baseUrl}}/orgs/{{org}}/teams/{{team_slug}}/projects/{{project_id}}/"



