#!/usr/bin/env dothttp

@name("{{baseUrl}}/Registration/CustomerInfo")
POST "https://{{baseUrl}}/Registration/CustomerInfo"
"Content-Type": "application/json"
data('{
    "pass": "<string>",
    "user": "<string>"
}')


// This takes some time to complete.
@name("{{baseUrl}}/Registration/RegisterNewTenant")
POST "https://{{baseUrl}}/Registration/RegisterNewTenant"
"Content-Type": "application/json"
data('{
    "AdminUser": "<string>",
    "Brand": "<string>",
    "InitialAlias": "<string>",
    "CustomerName": "<string>",
    "AdminPass": "<string>",
    "CustomerPass": "<string>",
    "ManagedBy": "<string>",
    "InitialStateChangeReason": "<string>",
    "Company": "<string>",
    "IsMsp": "<boolean>",
    "EntitlementIdsToEnable": [
        "<string>",
        "<string>"
    ],
    "CustomerTenantData": "<object>",
    "CustomerData": "<object>",
    "AuthSource": "<string>",
    "CustomerToken": "<string>",
    "AdditionalConfigSettings": "<object>",
    "AwsCustomerId": "<string>"
}')



