#!/usr/bin/env dothttp

@name("Idea Comment")
GET "https://{{host}}/services/data/v47.0/sobjects/IdeaComment/"


@name("Idea Comment Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/IdeaComment/{ID}/"


@name("Describe Idea Comment")
GET "https://{{host}}/services/data/v47.0/sobjects/IdeaComment/describe/"



