#!/usr/bin/env dothttp

@name("GET Sessions")
GET "https://{{sb_client}}.salesboard.biz/v1/sessions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID=080qf39is6fon7gs30skppvf9q"
? 'filters'= '{"date":{"startDate":1486422000000,"endDate":1486508399000}}'
? "page"= "1"


@name("GET Report Actions")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"


@name("GET Report Actions w/action team filter")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID=dfg9b6ulu1rnoicmp24603homo"
? "actionTypes[]"= "sessionEnd"
? "actionTypes[]"= "sessionStart"


@name("GET Report Action by ID")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions/AVmfYq8hUj_nJh9LQ1ZY"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID=080qf39is6fon7gs30skppvf9q"


@name("GET Report Actions w/action type filters")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID=hou39hkfk7hr4cvhvh7guofi40"
? "actionTypes"= "leadDLChanged"


@name("GET Report Actions w/action type filters array")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID=hou39hkfk7hr4cvhvh7guofi40"
? "actionTypes[]"= "sessionEnd"
? "actionTypes[]"= "sessionStart"


@name("GET Report Actions w/ tablet date filter")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID=hou39hkfk7hr4cvhvh7guofi40"
? "startDate"= "1479981936"
? "endDate"= "1480089936"


@name("GET Report Actions w/ users and teams filter")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "startDate"= "1569888000"
? "endDate"= "1569974400"
? "teams[]"= "85"
? "teams[]"= "88"
? "users[]"= "1311"
? "users[]"= "1309"
? "actionTypes[]"= "sessionEnd"


@name("GET Report Actions w/ server date filter")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID=dfg9b6ulu1rnoicmp24603homo"
? "createdStartDate"= "1479981936"
? "createdEndDate"= "1480089936"


@name("GET Report Actions Scroll")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/actions"
"XREQUESTEDWITH": "APIHttpRequest"
"Cookie": "PHPSESSID=dfg9b6ulu1rnoicmp24603homo"
? "scroll_id"= "DnF1ZXJ5VGhlbkZldGNoBwAAAAAAJwzBFmV0LTZXMkJfUkotRTBTaHJpaE5faXcAAAAAACcMwBZldC02VzJCX1JKLUUwU2hyaWhOX2l3AAAAAAAnDL8WZXQtNlcyQl9SSi1FMFNocmloTl9pdwAAAAAAJwzDFmV0LTZXMkJfUkotRTBTaHJpaE5faXcAAAAAACcMwhZldC02VzJCX1JKLUUwU2hyaWhOX2l3AAAAAAAnDMQWZXQtNlcyQl9SSi1FMFNocmloTl9pdwAAAAAAJwzFFmV0LTZXMkJfUkotRTBTaHJpaE5faXc="


@name("hook-notify-test")
POST "https://{{sb_client}}.salesboard.biz/v1/hook-notify-test"



@name("GET Documents")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/documents"
"XREQUESTEDWITH": "XMLHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? 'requestParams'= '{"page":1,"search":"","filters":{"deleted":false,"date":{"startDate":1486422000000,"endDate":1486508399999}}}'


@name("GET Documents")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/documents"
"XREQUESTEDWITH": "XMLHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? 'requestParams'= '{"page":1,"search":"","filters":{"deleted":false,"date":{"startDate":1486422000000,"endDate":1486508399999}}}'


@name("GET Devices")
GET "https://{{sb_client}}.salesboard.biz/v1/reports/documents"
"XREQUESTEDWITH": "XMLHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? 'requestParams'= '{"page":1,"search":"","filters":{"deleted":false,"date":{"startDate":1486422000000,"endDate":1486508399999}}}'



