#!/usr/bin/env dothttp

@name("tacacsprofile")
GET "https://{{base_url}}/ers/config/tacacsprofile"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"
? "size"= "100"
? "page"= "1"
? "filter"= "name.CONTAINS.irv"
? "sortasc"= "name"
? "sortdsc"= "name"


@name("tacacsprofile/{id}")
GET "https://{{base_url}}/ers/config/tacacsprofile/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("tacacsprofile/name/{name}")
GET "https://{{base_url}}/ers/config/tacacsprofile/name/{{name}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 tacacsprofile")
POST "https://{{base_url}}/ers/config/tacacsprofile"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 tacacsprofile/{id}")
PUT "https://{{base_url}}/ers/config/tacacsprofile/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("tacacsprofile/{id}")
DELETE "https://{{base_url}}/ers/config/tacacsprofile/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"



