#!/usr/bin/env dothttp

// Retrieve game and platform identification for the authenticated client

@name("Leaderboards")
GET "https://www.callofduty.com/api/papi-client/leaderboards/v2/title/:game/platform/:platform/time/alltime/type/core/mode/career/page/:page"
"Cookie": ""


// Retrieve game and platform identification for the authenticated client

@name("Match Details")
GET "https://www.callofduty.com/api/papi-client/crm/cod/:version/title/:game/platform/battle/fullMatch/:mode/:matchId/it"
"Cookie": ""


// List all of the multiplayer (casual) maps available and their gamemode. Keep in mind that 'war' means Team Deathmatch, 'arm' means Ground War, 'arena' means 2v2

@name("Maps & Game Modes")
GET "https://my.callofduty.com/api/papi-client/ce/:version/title/:game/platform/:platform/gameType/mp/communityMapData/availability"


// List all of the multiplayer (casual) maps available and their gamemode. Keep in mind that 'war' means Team Deathmatch, 'arm' means Ground War, 'arena' means 2v2

@name("Match Map Events (Multiplayer Only)")
GET "https://my.callofduty.com/api/papi-client/ce/:version/title/:game/platform/:platform/match/:matchId/matchMapEvents"



