#!/usr/bin/env dothttp

@name("vEdge Template Policy")
GET "https://{{vmanage}}/dataservice/template/policy/vedge/devices"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"


@name("Policy List")
GET "https://{{vmanage}}/dataservice/template/policy/list"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"



