#!/usr/bin/env dothttp

// Generate invoice pdf and send by email.
// 
// 
// ### Notes
// * Email is only sent automatically when the saleCategory is invoicedSale
// * This endpoint is only being used internally and not subjected to user input, the input that is provided herein is already validated in other point of the sale creation. 
// 
// #### Path Variables
// ```
// sale_id             4EC041C2-E733-4C56-B622-490AFF39942E    
// ```
// 
// #### Reponse status codes
// | Code| Message|Reason | 
// | -- | -- | -- | 
// | 200| Created| ivoice send by email| 
// | 400| Bad request|Malformed request syntax, read the docs | 
// | 422| Invalid info for process|Field value error, read the docs | 
// | 422| Unprocessable Entity Error|Business rule error, read the docs | 
// | 404| Not found| Bad endpoint invocation | 

@name("Generate invoice pdf and send by email")
POST "https://{{base_url}}/sales/98A1283D-9F0D-4F94-9805-25830237F12F/uploads"
json({
    "invoice": {
        "conceptos": [
            {
                "posicion": 1,
                "clave": "audi",
                "descripcion": "audit",
                "cantidad": "10",
                "unidadDeMedida": "Hora",
                "precioBaseUnitario": "1.000000",
                "importeDeDescuento": "0.1",
                "precioUnitarioConDescuentos": "0.9",
                "importeSubtotal": "1.000000",
                "impuestosTransferidos": [
                    {
                        "nombreDelImpuesto": "IVA",
                        "tasa": "16.000000",
                        "importe": "0.160000",
                        "exento": false
                    }
                ],
                "impuestosRetenidos": [],
                "importeTotal": "9.54",
                "claveProductoServicioSAT": "84111603",
                "claveProductoServicioSATDescripcion": "Auditorias internas",
                "claveUnidadMedidaSAT": "HUR"
            }
        ],
        "fechaDeEnvioAFacturacion": "2020-04-01T23:26:04.871Z",
        "codigoMoneda": "MXN",
        "tipoDeCambio": "1",
        "version": "3.3",
        "serie": "A",
        "folio": "B-3",
        "tipoDeCfdi": "I",
        "usoCfdi": "G03",
        "metodoDePago": "PPD",
        "formaDePago": "03",
        "lugarExpedicion": "52928",
        "subtotal": "1.000000",
        "impuestosTransferidos": [
            {
                "nombreDelImpuesto": "IVA",
                "tasa": "16",
                "importe": "0.16",
                "exento": false
            }
        ],
        "impuestosRetenidos": [],
        "total": "1.160000",
        "emisor": {
            "rfc": "JUFA7608212V6",
            "nombreORazonSocial": "Megacorp S.A de C.V",
            "regimenFiscalCodigo": 612,
            "codigoPostal": "52928"
        },
        "cliente": {
            "rfc": "GARY9506303N8",
            "nombreORazonSocial": "Cliente corporativo S.A de C.V",
            "codigoDePais": "MEX",
            "numRegIdTrib": ""
        },
        "certificado": {
            "certificateNumber": "30001000000400002331",
            "certificateToken": "863f4b2b6024f7b59ee4c63ebd4d0c3795a74d88dfe5fe4fb6376b2cee50e1ac"
        },
        "notas": null,
        "tipoDeComprobante": "factura",
        "xml": "cfdis/16182cf7-4485-46d3-ab9a-a0f2e6ff2526.xml",
        "id": "16182CF7-4485-46D3-AB9A-A0F2E6FF2526",
        "fechaDeFacturacion": "2020-04-01T23:26:09Z",
        "sello": "ihd0zSW4sjY07aQ4Vz8AZNmUb0zkyFhxWbSIg8VHJml+jXCDOby3RLNoNTHO1o6ys4aa5ZBM0iERQwOFvIM8YcRejos1FhbDZAhTyIbFH8q/TZbWYtwDVXV7+llux2FSP3oHpvKOtLtX2ICdbMz0S364f2fJGTTOjmrhlzyNIz2GhS8qxwRo4Rmpz9Wv2RjsEMHhiQArYc35wSWC+mUHM4URBcYrED5nZQAT44KqoP+1yapLtIejxU7oynJj71fv760MlVdD6XQB2cnQf0pcd7ViRiTLVJ0BAKw6FQcTwIIxyU6l0b0OdbgBlT1w3o3SY24nZkSV6mDm5l8xIiC3Eg==",
        "selloSAT": "a8XxVq85deHhSTqcteFIpk3cn6WRu9pxL0kWuOVNiqRi3RqSXyXxanMp2wg49SBWl0SlB6p3zOJPwGy4o0ft+HqIl+/dTBDIWc/bqaPZesu5uw+HvIUmN79FewfPSTtkMQTJTYcU3lodPFd3brs30j4MLR8+ijeW2Y3azw0gHM8keQCpFDx4VQD5E3OQ8xNvnRYSnXjU+I4ErH6aJ9sVStRG+DK+mHGhkMTpgMd6JT8cvK2ukl8oWF3znW0STJwYw+qKr1w6iiYdML9o7Ff2l7GSfAgxpLwfo7qden604QigWzmw4XzFBiHYLcFzFyKPI4cRNuf9wKHorURtmQO/Vg==",
        "cadenaOriginalDelComplemento": "||1.1|16182CF7-4485-46D3-AB9A-A0F2E6FF2526|2020-04-01T17:26:09|ASE0201179X0|ihd0zSW4sjY07aQ4Vz8AZNmUb0zkyFhxWbSIg8VHJml+jXCDOby3RLNoNTHO1o6ys4aa5ZBM0iERQwOFvIM8YcRejos1FhbDZAhTyIbFH8q/TZbWYtwDVXV7+llux2FSP3oHpvKOtLtX2ICdbMz0S364f2fJGTTOjmrhlzyNIz2GhS8qxwRo4Rmpz9Wv2RjsEMHhiQArYc35wSWC+mUHM4URBcYrED5nZQAT44KqoP+1yapLtIejxU7oynJj71fv760MlVdD6XQB2cnQf0pcd7ViRiTLVJ0BAKw6FQcTwIIxyU6l0b0OdbgBlT1w3o3SY24nZkSV6mDm5l8xIiC3Eg==|20001000000300022323||",
        "noCertificadoSAT": "20001000000300022323",
        "folioFiscal": "16182cf7-4485-46d3-ab9a-a0f2e6ff2526"
    },
    "company": {
        "legalName": "MegaCorp",
        "fiscalAddress": {
            "addressId": "38960ADE-8002-4298-9517-4EEFF3478CB7",
            "addressNumber": "14441",
            "street": "Av Siempre Viva",
            "outsideNumber": "137",
            "insideNumber": "137",
            "neighborhood": "Benito Juarez",
            "municipality": "Chihuahua",
            "city": "Chihuahua",
            "state": "Chihuahua",
            "country": "Mexico",
            "countryCode": "MEX",
            "postalCode": "31555",
            "reference": null,
            "fullAddress": null
        },
        "dataLocalized": {
            "companyNumber": "207315",
            "regimenFiscalNombre": "Personas Físicas con Actividades Empresariales y Profesionales",
            "regimenFiscalCodigo": "612",
            "curp": null,
            "registroPatronal": null,
            "ciecConfigurada": null,
            "ciecConfiguradaFecha": null,
            "connectionId": null
        },
        "logoUrl": null
    },
    "client": {
        "clientId": "E7F72444-AD2B-4C74-9A8E-6307C6EDD097",
        "taxId": "GARY950630393",
        "businessName": "Gestionix AC33",
        "commercialName": "Gestionix AC339",
        "addressId": "0E954711-EE29-401F-9D82-D4B02A96C4C4",
        "countryCode": "MEX",
        "address": {
            "addressId": "0E954711-EE29-401F-9D82-D4B02A96C4C4",
            "addressNumber": 957,
            "street": "Guanajuato",
            "outsideNumber": "114",
            "insideNumber": "5",
            "neighborhood": "Roma Nte",
            "municipality": "Albaro Obregón",
            "city": "Ciudad de México",
            "state": "Ciudad de México",
            "country": "México",
            "countryCode": "MEX",
            "postalCode": "06700",
            "reference": "Esquina",
            "fullAddress": "Guanajuato 114, Roma Nte., 06700 Ciudad de México, CDMX"
        },
        "contacts": [
            {
                "personId": "DA6D5487-9765-46D0-B919-0B34EE3090F3",
                "personNumber": 647,
                "name": "Luis M",
                "jobTitle": "Developer",
                "email": "wicho.91+001@gmail.com",
                "phone": "2255889966",
                "mobilePhone": "2225588899",
                "countryCode": "MEX",
                "country": "México",
                "registeredDate": "2020-04-07T15:50:13.663Z",
                "invoiceContact": true
            }
        ]
    }
})


// Send email to client
// 
// #### Business rules
// * Must specify the type of email you want to send, see the table below
// * Content field must be a valid base64 to generate the PDF.
// * Cases 7, 8 y 9 does not contain attachments, the body must be modified to not send the specified field
// 
// #### Sale email enum
// | Id| Name|Description| 
// | -- | -- | -- | 
// | 1| notInvoicedSaleDraft| This status allow to send the draft pdf file for a not invoiced sale by email when will be created (send only pdf)| 
// | 2| notInvoicedSaleCreate| This status allow to send the pdf file for a not invoiced sale by email when is created (Send only pdf)|
// | 3| invoiceSaleDraft|This status allow to send the draft pdf file for a invoiced sale by email when will be invoiced (send only pdf)| 
// | 4| saleInvoiceCreate|This status allow to send the invoicing files for a sale by email when is ivoiced (send xml and pdf files)| 
// | 5|notInvoicedSaleUpdateDraft|This status allow to send the draft pdf file for a not invoiced sale by email when will be updated (Send only pdf) | 
// | 6|notInvoicedSaleUpdateCreate|This status allow to send the pdf file for a not invoiced sale by email when is updated (send only pdf)  | 
// | 7|cancellationApprovalRequest|This status allow to send the email to the recipient the approval cancellation request | 
// | 8|cancellationRequestAccepted|This status allows sending the email to the user to inform them that the request was approved  | 
// | 9|cancellationRequestRejected|This status allows sending the email to the user to inform them that the request was rejected| 
// | 10|cancellationAcknowledgment |This status allow to send the files for Acknowledgment of cancellation  by email (send xml and pdf files)  | 
// 
// 
// #### Reponse status codes
// | Code| Message|Reason | 
// | -- | -- | -- | 
// | 200| Created| ivoice send by email| 
// | 400| Bad request|Malformed request syntax, read the docs | 
// | 422| Invalid info for process|Field value error, read the docs | 
// | 422| Unprocessable Entity Error|Business rule error, read the docs | 
// | 404| Not found| Bad endpoint invocation | 

@name("Send email")
POST "https://{{base_url}}/sales/emails"
json({
    "saleEmailEnum": 19,
    "saleId": "F02E52D0-A1C4-4EFC-93C0-867CD70FEA31",
    "invoiceId": "0C1A4E3B-094C-47B4-85B1-3913DAF25C58",
    "invoiceFolio": "A-1",
    "email": "gr.yocelin@gmail.com",
    "CLIENT_FIRST_NAME": "Alexis",
    "RFC_HOMELY": "XAXX010101000",
    "SALE_DATE": "2021-05-05T07:43:00.000Z",
    "CLIENT_FULL_NAME": "Alexis Landa de Arriaga",
    "CONCEPT": "Homely 05 MAy",
    "AMOUNT": "399.00",
    "currency": "MXN",
    "HOMELY_URL": "https://app.chain.inc/homely/12/33434",
    "CHAIN_LINK": "https://www.chain.inc",
    "SALE_NUMBER": "5",
    "CLIENT_RFC": "GARY9506303N8"
})



