#!/usr/bin/env dothttp

@name("Allows you to retrieve Attachments for credit notes")
GET "https://{{baseUrl}}/CreditNotes/:CreditNoteID/Attachments"
"xero-tenant-id": "<string>"


@name("Allows you to retrieve Attachments on CreditNote")
GET "https://{{baseUrl}}/CreditNotes/:CreditNoteID/Attachments/:AttachmentID"
"contentType": "<string>"
"xero-tenant-id": "<string>"



