#!/usr/bin/env dothttp

@name("Search for events in provider")
GET "https://{{baseUrl}}/search/:providerId/events"
"Authorization": ""


@name("Execute search and return raw results")
POST "https://{{baseUrl}}/search/:providerId/raw"
"Authorization": ""
"Content-Type": "application/json"
data('"<string>"')



