#!/usr/bin/env dothttp

// This endpoint returns a redirect URI (in the 'Location' header) that the customer uses to authorize your application and, together with POST /v2/oauth/access_token, generate an access token that represents that authorization.

@name("Authorize applications")
GET "https://{{baseUrl}}/v2/oauth/authorize"
? "client_id"= "<string>"
? "realm"= "customer"
? "redirect_uri"= "<string>"
? "response_type"= "<string>"
? "scope"= "user.view"
? "state"= "<string>"


// This endpoint returns an access token for the specified user and with the specified scopes. The token does not expire until the user changes their password. The body parameters must be encoded as form data.

@name("Get access tokens")
POST "https://{{baseUrl}}/v2/oauth/access_token"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "client_id": [
        "<string>"
    ],
    "grant_type": [
        "<string>"
    ],
    "client_secret": [
        "<string>"
    ],
    "code": [
        "<string>"
    ],
    "realm": [
        "customer"
    ],
    "expires": [
        "false"
    ],
    "refresh_token": [
        "<string>"
    ]
})



