#!/usr/bin/env dothttp

// In the response of this API, you'll get the details of passengers screened count, active cases, recovered cases, migrated cases and death cases.
@name("Country Data")
GET "https://covid-19india-api.herokuapp.com/v2.0/country_data"


// In the response of this API, you'll get the details of confirmed cases count, cured cases and death cases.
@name("States & Union Territories Data")
GET "https://covid-19india-api.herokuapp.com/v2.0/state_data"


// In the response of this API, you'll get the name and addresses of all the Government Labs, Private Labs approved by ICMR for testing.
@name("ICMR Lab Details")
GET "https://covid-19india-api.herokuapp.com/v2.0/icmr_lab_details"


// In the response of this API, you'll get the list of all the Helpline Numbers of the States and the Union Territories.
@name("Helpline Numbers")
GET "https://covid-19india-api.herokuapp.com/v2.0/helpline_numbers"



