#!/usr/bin/env dothttp

// Delete a User Access Device
// #### Supports Action Batches
// 
// **Resource**|**Operation**
// :-------------: |:-------------:
// `/networks/{networkId}/sm/userAccessDevices/{userAccessDeviceId}` | destroy
// 

@name("Delete A User Access Device")
DELETE "https://{{baseUrl}}/networks/:networkId/sm/userAccessDevices/:userAccessDeviceId"
"X-Cisco-Meraki-API-Key": ""


// List User Access Devices and its Trusted Access Connections

@name("List User Access Devices And Its Trusted Access Connections")
GET "https://{{baseUrl}}/networks/:networkId/sm/userAccessDevices"
"X-Cisco-Meraki-API-Key": ""
? "perPage"= "{{perPage}}"
? "startingAfter"= "{{startingAfter}}"
? "endingBefore"= "{{endingBefore}}"



