#!/usr/bin/env dothttp

@name("User Search")
GET "https://api.twitter.com/1.1//users/search.json"
? "q"= "kilm news"
? "count"= "100"


@name("KGET 17 News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KGETnews"


@name("KCOY NewsChannel 12")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KCOY"


@name("EYT NewsChannel 3")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KEYTNC3"


@name("KGO Morning News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KGOMorningNews"


@name("KPIX 5")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KPIXtv"


@name("KRON4 News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "kron4news"


@name("KTVU")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KTVU"


@name("KUSI News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KUSINews"


@name("10News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "10News"


@name("CBS News 8")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "CBS8"


@name("KION News 5 46")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KION546"


@name("KSBW Action News 8")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "ksbw"


@name("FOX40 News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "FOX40"


@name("KESQ News Channel 3")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KESQ"


@name("KRCR News Channel 7")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KRCR7"


@name("KIXE-TV")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KIXETV"


@name("Action News Now")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "ActionNewsNow"


@name("Redwood New")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KIEMNews"


@name("KRCR News Channel 7")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KRCR7"


@name("North Coast News TV")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "northcoastnews1"


@name("KSEE24 News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KSEE24"


@name("ABC30 Fresno")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "ABC30"


@name("KSEE24 News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KSEE24"


@name("KTLA 5 Morning New")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KTLAMorningNews"


@name("ABC7 Eyewitness News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "ABC7"


@name("LA 18 KSCI-TV")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "LA18Community"


@name("KCET News")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KCETNews"


@name("KDOC-TV Los Angeles")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "KDOCTV"


@name("List all of the Tweets")
GET "https://postman-echo.com/get"


@name("Check for Testing Locations")
GET "https://postman-echo.com/get"



