#!/usr/bin/env dothttp

// Retrieves a specific Season by its ID.

@name("/seasons/:season_id")
GET "https://{{host}}/seasons/{{season_id}}"


// Retrieves all Episodes for a specific Season.
// 
// #### Parameters
// 
// | Key      | Type      | Default  | Description |
// | -------- | --------- | -------- | ----------- |
// | `limit`  | `integer` | `10`     | Number of records per page. |
// | `offset` | `integer` | `0`      | Record offset for pagination. |
// | `sort`   | `string`  | `latest` | Sorts the episodes that are returned.  Available sorting fields are `title`, `number`, `custom_url`, `published_at`, `created_at` or `updated_at`. Sort order is _ascending_ by default and can be changed by appending `_asc` or `_desc` to a field. For example, to sort by title _descending_ you'd use `title_desc`.  |
// | `status` | `string`  | `null`   | Filter episodes by status. Available statuses are `importing`, `audio_imported`, `transcoding`, `transcoding_error`, `draft`, `scheduled`, `published` or `private`. |

@name("/seasons/:season_id/episodes")
GET "https://{{host}}/seasons/{{season_id}}/episodes"



