#!/usr/bin/env dothttp

// Gets a list of group or project members viewable by the authenticated user.

@name("Get Projects  Members")
GET "https://{{baseUrl}}/projects/:id/members"
? "query"= "<>"
? "page"= "<>"
? "per_page"= "<>"


// Removes a user from a group or project.

@name("Delete Projects  Members User")
DELETE "https://{{baseUrl}}/projects/:id/members/:user_id"



