#!/usr/bin/env dothttp

@name("Get all available applications list")
GET "https://{{base_url}}/api/2/applications"


@name("Get all available applications for a root tenant")
GET "https://{{base_url}}/api/2/tenants/{{my_tenant_id}}/applications"


@name("Get an application settings list")
GET "https://{{base_url}}/api/2/applications/{{application_id}}/settings/schemas"


@name("Get an application settings for a root tenant")
GET "https://{{base_url}}/api/2/applications/{{application_id}}/settings/tenants/{{my_tenant_id}}"


@name("Get the Management Portal application settings for the root tenant")
GET "https://{{base_url}}/api/2/applications/{{management_portal}}/settings/tenants/{{my_tenant_id}}"


@name("Get an application settings for a partner tenant")
GET "https://{{base_url}}/api/2/applications/{{application_id}}/settings/tenants/{{partner_tenant_id}}"


@name("Get a commitment level for a partner tenant")
GET "https://{{base_url}}/api/2/applications/{{management_portal}}/settings/tenants/{{partner_tenant_id}}/tier_level_value"


@name("Set a commitment level for a partner tenant")
PUT "https://{{base_url}}/api/2/applications/{{management_portal}}/settings/tenants/{{partner_tenant_id}}/tier_level_value"
"Content-Type": "application/json"
json({
    "value": "1",
    "lock": false
})


@name("Get a licensing mode for a partner tenant -- ONLY for legacy editions")
GET "https://{{base_url}}/api/2/applications/{{management_portal}}/settings/tenants/{{partner_tenant_id}}/licensing_mode"


@name("Set a licensing mode for a partner tenant -- ONLY for legacy editions")
PUT "https://{{base_url}}/api/2/applications/{{management_portal}}/settings/tenants/{{partner_tenant_id}}/licensing_mode"
"Content-Type": "application/json"
json({
    "value": "per_gb",
    "lock": false
})


@name("Get  legacy editions limitation status")
GET "https://{{base_url}}/api/2/applications/{{management_portal}}/settings/tenants/{{partner_tenant_id}}/hide_legacy_editions"


@name("Set  legacy editions limitation")
PUT "https://{{base_url}}/api/2/applications/{{management_portal}}/settings/tenants/{{partner_tenant_id}}/hide_legacy_editions"
json({
    "value": true
})


@name("Get an application settings for a customer tenant")
GET "https://{{base_url}}/api/2/applications/{{application_id}}/settings/tenants/{{customer_tenant_id}}"


@name("Enable an applications for a partner tenant")
POST "https://{{base_url}}/api/2/applications/{{application_id}}/bindings/tenants/{{partner_tenant_id}}"


@name("Disable an applications for a partner tenant")
DELETE "https://{{base_url}}/api/2/applications/{{application_id}}/bindings/tenants/{{partner_tenant_id}}"


@name("Get available offering items for a partner tenant")
GET "https://{{base_url}}/api/2/tenants/{{my_tenant_id}}/offering_items/available_for_child"
? "edition"= "{{edition}}"
? "kind"= "partner"


@name("Set offering items for a partner tenant")
PUT "https://{{base_url}}/api/2/tenants/{{partner_tenant_id}}/offering_items"
"Content-Type": "application/json"
json({
    "offering_items": [
        {
            "infra_id": "ba2976d0-c13e-4661-ae60-b4593583fce2",
            "name": "pw_compute_points",
            "measurement_unit": "seconds",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "compute_points",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "name": "pw_compute_points",
            "measurement_unit": "seconds",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "compute_points",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "ba2976d0-c13e-4661-ae60-b4593583fce2",
            "name": "pw_dr_cloud_servers",
            "measurement_unit": "quantity",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "dr_cloud_servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "name": "pw_dr_cloud_servers",
            "measurement_unit": "quantity",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "dr_cloud_servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "ba2976d0-c13e-4661-ae60-b4593583fce2",
            "name": "pw_dr_internet_access",
            "measurement_unit": "n/a",
            "type": "feature",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "usage_name": "dr_internet_access",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "name": "pw_dr_internet_access",
            "measurement_unit": "n/a",
            "type": "feature",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "usage_name": "dr_internet_access",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "ba2976d0-c13e-4661-ae60-b4593583fce2",
            "name": "pw_dr_storage",
            "measurement_unit": "bytes",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "dr_storage",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "name": "pw_dr_storage",
            "measurement_unit": "bytes",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "dr_storage",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "name": "pw_public_ips",
            "measurement_unit": "quantity",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "public_ips",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "ba2976d0-c13e-4661-ae60-b4593583fce2",
            "name": "pw_public_ips",
            "measurement_unit": "quantity",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "public_ips",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "019097a6-114f-4418-bd54-e01ef049f209",
            "name": "pw_storage",
            "measurement_unit": "bytes",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "storage",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "ba2976d0-c13e-4661-ae60-b4593583fce2",
            "name": "pw_vpn_concurrent_connections",
            "measurement_unit": "quantity",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "vpn_concurrent_connections",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "name": "pw_vpn_concurrent_connections",
            "measurement_unit": "quantity",
            "type": "infra",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "vpn_concurrent_connections",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "drives_shipped_to_cloud",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "b71b2c18-590a-303c-9d5a-8444fbe713ac",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "drives_shipped_to_cloud",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": null
        },
        {
            "name": "notary_storage",
            "measurement_unit": "bytes",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "f9c5744e-bd1a-36b6-b0f0-ecd7483e1796",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "notary_storage",
            "locked": true,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": null
        },
        {
            "name": "notarizations",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "f9c5744e-bd1a-36b6-b0f0-ecd7483e1796",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "notarizations",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": null
        },
        {
            "name": "esignatures",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "f9c5744e-bd1a-36b6-b0f0-ecd7483e1796",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "esignatures",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": null
        },
        {
            "name": "local_storage",
            "measurement_unit": "bytes",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "local_storage",
            "locked": true,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": null
        },
        {
            "name": "pw_child_storages",
            "measurement_unit": "bytes",
            "updated_at": "2021-01-11T10:28:28",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "child_storages",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_ess_workstations",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "workstations",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_workstations",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "workstations",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_adv_workstations",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "workstations",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_workstations",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "workstations",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_ess_servers",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_servers",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_adv_servers",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_servers",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_ess_vms",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "vms",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_vms",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "vms",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_adv_vms",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "vms",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_vms",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "vms",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_o365_seats",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "mailboxes",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_o365_mailboxes",
            "measurement_unit": "n/a",
            "updated_at": "1970-01-01T00:00:00",
            "type": "feature",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "usage_name": "o365_mailboxes",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_o365_onedrive",
            "measurement_unit": "n/a",
            "updated_at": "1970-01-01T00:00:00",
            "type": "feature",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "usage_name": "o365_onedrive",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_o365_sharepoint_sites",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "o365_sharepoint_sites",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_gsuite_seats",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "gsuite_seats",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_google_mail",
            "measurement_unit": "n/a",
            "updated_at": "1970-01-01T00:00:00",
            "type": "feature",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "usage_name": "google_mail",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_google_drive",
            "measurement_unit": "n/a",
            "updated_at": "1970-01-01T00:00:00",
            "type": "feature",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "usage_name": "google_drive",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_google_team_drive",
            "measurement_unit": "n/a",
            "updated_at": "1970-01-01T00:00:00",
            "type": "feature",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "usage_name": "google_team_drive",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_websites",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "websites",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_web_hosting_servers",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "web_hosting_servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_p_adv_web_hosting_servers",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "web_hosting_servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_web_hosting_servers",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "web_hosting_servers",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_mobiles",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "mobiles",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_o365_teams",
            "measurement_unit": "quantity",
            "updated_at": "1970-01-01T00:00:00",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "o365_teams",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        },
        {
            "name": "pw_dr_child_storages",
            "measurement_unit": "bytes",
            "updated_at": "2021-01-11T10:28:28",
            "type": "count",
            "deleted_at": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "overage": null,
                "version": 0,
                "value": null
            },
            "usage_name": "dr_child_storages",
            "locked": false,
            "status": 1,
            "tenant_id": "531789f2-2be9-42af-8474-18177593c77b",
            "edition": "per_workload"
        }
    ],
    "timestamp": "2021-04-05T10:06:08"
})


@name("Get offering items for a partner tenant")
GET "https://{{base_url}}/api/2/tenants/{{partner_tenant_id}}/offering_items"
"Content-Type": "application/json"
? "edition"= "*"



@name("Set a quota for an offering items for a partner tenant")
PUT "https://{{base_url}}/api/2/tenants/{{partner_tenant_id}}/offering_items"
"Content-Type": "application/json"
json({
    "offering_items": [
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "name": "storage",
            "type": "infra",
            "locked": false,
            "edition": "standard",
            "usage_name": "storage",
            "quota": {
                "overage": null,
                "value": null,
                "version": 1582126239603
            },
            "status": 1,
            "measurement_unit": "bytes",
            "infra_id": "019097a6-114f-4418-bd54-e01ef049f209"
        }
    ]
})


@name("Get available offering items for a folder tenant")
GET "https://{{base_url}}/api/2/tenants/{{partner_tenant_id}}/offering_items/available_for_child"
? "edition"= "{{edition}}"
? "kind"= "folder"


@name("Set offering items for a folder tenant")
PUT "https://{{base_url}}/api/2/tenants/{{folder_tenant_id}}/offering_items"
"Content-Type": "application/json"
json({
    "offering_items": [
        {
            "measurement_unit": "seconds",
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "status": 1,
            "name": "pw_compute_points",
            "usage_name": "compute_points",
            "locked": false,
            "type": "infra",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "status": 1,
            "name": "pw_dr_cloud_servers",
            "usage_name": "dr_cloud_servers",
            "locked": false,
            "type": "infra",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "n/a",
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "status": 1,
            "name": "pw_dr_internet_access",
            "usage_name": "dr_internet_access",
            "locked": false,
            "type": "feature",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb"
        },
        {
            "measurement_unit": "bytes",
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "status": 1,
            "name": "pw_dr_storage",
            "usage_name": "dr_storage",
            "locked": false,
            "type": "infra",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "status": 1,
            "name": "pw_public_ips",
            "usage_name": "public_ips",
            "locked": false,
            "type": "infra",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "bytes",
            "infra_id": "019097a6-114f-4418-bd54-e01ef049f209",
            "status": 1,
            "name": "pw_storage",
            "usage_name": "storage",
            "locked": false,
            "type": "infra",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "infra_id": "f5546128-8fb1-4b6f-b6e9-3ccfa89f60a1",
            "status": 1,
            "name": "pw_vpn_concurrent_connections",
            "usage_name": "vpn_concurrent_connections",
            "locked": false,
            "type": "infra",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "bytes",
            "infra_id": "fbc254b9-d8be-4daf-94f6-0253d23b63f0",
            "status": 1,
            "name": "fc_storage",
            "usage_name": "fc_storage",
            "locked": false,
            "type": "infra",
            "edition": null,
            "application_id": "dfd85a5f-a464-32ab-81fd-99bcc66a070f",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "bytes",
            "status": 1,
            "name": "local_storage",
            "usage_name": "local_storage",
            "locked": false,
            "type": "count",
            "edition": null,
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_ess_workstations",
            "usage_name": "workstations",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_workstations",
            "usage_name": "workstations",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_adv_workstations",
            "usage_name": "workstations",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_workstations",
            "usage_name": "workstations",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_ess_servers",
            "usage_name": "servers",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_servers",
            "usage_name": "servers",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_adv_servers",
            "usage_name": "servers",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_servers",
            "usage_name": "servers",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_ess_vms",
            "usage_name": "vms",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_vms",
            "usage_name": "vms",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_adv_vms",
            "usage_name": "vms",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_vms",
            "usage_name": "vms",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_o365_seats",
            "usage_name": "mailboxes",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "n/a",
            "status": 1,
            "name": "pw_o365_mailboxes",
            "usage_name": "o365_mailboxes",
            "locked": false,
            "type": "feature",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb"
        },
        {
            "measurement_unit": "n/a",
            "status": 1,
            "name": "pw_o365_onedrive",
            "usage_name": "o365_onedrive",
            "locked": false,
            "type": "feature",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb"
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_o365_sharepoint_sites",
            "usage_name": "o365_sharepoint_sites",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_gsuite_seats",
            "usage_name": "gsuite_seats",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "n/a",
            "status": 1,
            "name": "pw_google_mail",
            "usage_name": "google_mail",
            "locked": false,
            "type": "feature",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb"
        },
        {
            "measurement_unit": "n/a",
            "status": 1,
            "name": "pw_google_drive",
            "usage_name": "google_drive",
            "locked": false,
            "type": "feature",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb"
        },
        {
            "measurement_unit": "n/a",
            "status": 1,
            "name": "pw_google_team_drive",
            "usage_name": "google_team_drive",
            "locked": false,
            "type": "feature",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb"
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_websites",
            "usage_name": "websites",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_web_hosting_servers",
            "usage_name": "web_hosting_servers",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_p_adv_web_hosting_servers",
            "usage_name": "web_hosting_servers",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_web_hosting_servers",
            "usage_name": "web_hosting_servers",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_mobiles",
            "usage_name": "mobiles",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "pw_o365_teams",
            "usage_name": "o365_teams",
            "locked": false,
            "type": "count",
            "edition": "per_workload",
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "drives_shipped_to_cloud",
            "usage_name": "drives_shipped_to_cloud",
            "locked": false,
            "type": "count",
            "edition": null,
            "application_id": "b71b2c18-590a-303c-9d5a-8444fbe713ac",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "fc_seats",
            "usage_name": "fc_seats",
            "locked": false,
            "type": "count",
            "edition": null,
            "application_id": "dfd85a5f-a464-32ab-81fd-99bcc66a070f",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "bytes",
            "status": 1,
            "name": "notary_storage",
            "usage_name": "notary_storage",
            "locked": false,
            "type": "count",
            "edition": null,
            "application_id": "f9c5744e-bd1a-36b6-b0f0-ecd7483e1796",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "notarizations",
            "usage_name": "notarizations",
            "locked": false,
            "type": "count",
            "edition": null,
            "application_id": "f9c5744e-bd1a-36b6-b0f0-ecd7483e1796",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        },
        {
            "measurement_unit": "quantity",
            "status": 1,
            "name": "esignatures",
            "usage_name": "esignatures",
            "locked": false,
            "type": "count",
            "edition": null,
            "application_id": "f9c5744e-bd1a-36b6-b0f0-ecd7483e1796",
            "quota": {
                "version": 0,
                "overage": null,
                "value": null
            }
        }
    ]
})


@name("Get available offering items for a customer tenant")
GET "https://{{base_url}}/api/2/tenants/{{partner_tenant_id}}/offering_items/available_for_child"
? "edition"= "{{edition}}"
? "kind"= "customer"


@name("Get offering items for a customer tenant")
GET "https://{{base_url}}/api/2/tenants/{{customer_tenant_id}}/offering_items"
"Content-Type": "application/json"
? "edition"= "{{edition}}"
? "for_ui"= "true"



@name("Set offering items for a customer tenant")
PUT "https://{{base_url}}/api/2/tenants/{{customer_tenant_id}}/offering_items"
"Content-Type": "application/json"
json({
    "offering_items": [
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "bytes",
            "type": "infra",
            "status": 1,
            "infra_id": "019097a6-114f-4418-bd54-e01ef049f209",
            "usage_name": "storage",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "storage",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "quantity",
            "type": "count",
            "status": 1,
            "usage_name": "workstations",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "workstations",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "quantity",
            "type": "count",
            "status": 1,
            "usage_name": "servers",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "servers",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "quantity",
            "type": "count",
            "status": 1,
            "usage_name": "vms",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "vms",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "quantity",
            "type": "count",
            "status": 1,
            "usage_name": "mobiles",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "mobiles",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "quantity",
            "type": "count",
            "status": 1,
            "usage_name": "mailboxes",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "mailboxes",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "quantity",
            "type": "count",
            "status": 1,
            "usage_name": "websites",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "websites",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "bytes",
            "type": "count",
            "status": 1,
            "usage_name": "local_storage",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "local_storage",
            "edition": null,
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "quantity",
            "type": "count",
            "status": 1,
            "usage_name": "gsuite_seats",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "gsuite_seats",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "n/a",
            "type": "feature",
            "status": 1,
            "usage_name": "o365_mailboxes",
            "name": "o365_mailboxes",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "n/a",
            "type": "feature",
            "status": 1,
            "usage_name": "o365_onedrive",
            "name": "o365_onedrive",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "quantity",
            "type": "count",
            "status": 1,
            "usage_name": "o365_sharepoint_sites",
            "quota": {
                "value": null,
                "version": 0,
                "overage": null
            },
            "name": "o365_sharepoint_sites",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "n/a",
            "type": "feature",
            "status": 1,
            "usage_name": "google_mail",
            "name": "google_mail",
            "edition": "standard",
            "locked": false
        },
        {
            "application_id": "6e6d758d-8e74-3ae3-ac84-50eb0dff12eb",
            "measurement_unit": "n/a",
            "type": "feature",
            "status": 1,
            "usage_name": "google_drive",
            "name": "google_drive",
            "edition": "standard",
            "locked": false
        }
    ]
})


@name("Switch editions dry run")
GET "https://{{base_url}}/api/2/tenants/{{customer_tenant_id}}/edition"
"Content-Type": "application/json"
? "application_id"= "{{application_id}}"
? "target_edition"= "{{target_edition}}"



@name("Switch editions")
PUT "https://{{base_url}}/api/2/tenants/{{customer_tenant_id}}/edition"
"Content-Type": "application/json"
json({
    "application_id": "{{application_id}}",
    "target_edition": "{{target_edition}}"
})



