#!/usr/bin/env dothttp

// Get information about a media object. The returned type key will allow you to differentiate between image and// video media.// // **Note:** if you authenticate with an OAuth Token, you will receive the user_has_liked key which quickly tells// you whether the current user has liked this media item.
@name("Get information about a media object.")
GET "https://{{baseUrl}}/media/:media-id"


// Remove a like on this media by the currently authenticated user.
@name("Remove a like on this media by the current user.")
DELETE "https://{{baseUrl}}/media/:media-id/likes"



