#!/usr/bin/env dothttp

// <p>Returns a list of certificates. Can optionally sort the resulting list in ascending or
//  descending order. Other params given will be used as search values.</p>
//  <p class="italicize">Examples:</p>
//  <div class="code indent"><pre>/restman/1.0/trustedCertificates?name=MyCertificate</pre></div>
//  <p>Returns certificates with name "MyCertificate".</p>
//  <p>If a parameter is not a valid search value a bad request error will be returned.</p>
// List

@name("List Trusted Certificates")
GET "https://{{baseUrl}}/1.0/trustedCertificates"
? "sort"= "<string>"
? "order"= "<string>"
? "name"= "<array>"
? "securityZone.id"= "<array>"


// Returns a template, which is an example certificate that can be used as a reference for what certificate objects should look like.
// Template

@name("Trusted Certificates Template")
GET "https://{{baseUrl}}/1.0/trustedCertificates/template"


// Retrieves a certificate.
// Get

@name("List Trusted Certificates By ID")
GET "https://{{baseUrl}}/1.0/trustedCertificates/:id"



