#!/usr/bin/env dothttp

@name("Feed Poll Vote")
GET "https://{{host}}/services/data/v47.0/sobjects/FeedPollVote/"


@name("Feed Poll Vote Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/FeedPollVote/{ID}/"


@name("Describe Feed Poll Vote")
GET "https://{{host}}/services/data/v47.0/sobjects/FeedPollVote/describe/"



