#!/usr/bin/env dothttp

@name("READ User Enabled")
GET "https://{{apiPath}}/environments/{{envID}}/users/{{userID}}/enabled"


@name("UPDATE User Enabled")
PUT "https://{{apiPath}}/environments/{{envID}}/users/{{userID}}/enabled"
"Content-Type": "application/json"
json({
    "enabled": false
})



