#!/usr/bin/env dothttp

@name("Retrieve a mandate")
GET "https://{{baseUrl}}/v1/mandates/:mandate"
"Content-Type": "application/x-www-form-urlencoded"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"



