#!/usr/bin/env dothttp

// ## Login Api
// 
// Test Admin

@name("CREATE")
POST "http://54.154.59.231/admin/api/v1/foods/5ce5dcf029431c1742d9a2a4/discounts"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1ODU1NDc4MSwiZXhwIjoxNTU5MTU5NTgxfQ.cDfpLWBseQN0NSsKG5oXMgEzzflFlE5Wm7IGid2Ci_0"
json({
    "priceReference": 9.2
})


// ## Login Api
// 
// Test Admin

@name("READ")
GET "http://54.154.59.231/admin/api/v1/foods/5ce5dcf029431c1742d9a2a4/discounts"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1ODU1NDc4MSwiZXhwIjoxNTU5MTU5NTgxfQ.cDfpLWBseQN0NSsKG5oXMgEzzflFlE5Wm7IGid2Ci_0"


// ## Login Api
// 
// Test Admin

@name("UPDATE")
PUT "http://54.154.59.231/admin/api/v1/foods/discounts/5ce5b3134bce711b3fc53ac1"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1ODU1NDc4MSwiZXhwIjoxNTU5MTU5NTgxfQ.cDfpLWBseQN0NSsKG5oXMgEzzflFlE5Wm7IGid2Ci_0"
json({
    "isActive": true
})


// ## Login Api
// 
// Test Admin

@name("DELETE")
DELETE "http://54.154.59.231/admin/api/v1/foods/discounts/5ce5dc36ba25b815643c9ae9"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1ODU1NDc4MSwiZXhwIjoxNTU5MTU5NTgxfQ.cDfpLWBseQN0NSsKG5oXMgEzzflFlE5Wm7IGid2Ci_0"



