#!/usr/bin/env dothttp

// Retrieve a single user depending on his id

@name("/users/:id")
GET "https://{{baseUrl}}/users/:id"


// Update an existing user

@name("/users/:id")
PUT "https://{{baseUrl}}/users/:id"
"Content-Type": "application/json"
json({
    "username": "eu ad mollit reprehenderit",
    "email": "magna elit proident do",
    "provider": "pariatur aliquip dolore in",
    "password": "ad anim sunt ex",
    "resetPasswordToken": "magna quis aliqua consequat in",
    "confirmationToken": "velit nostrud",
    "confirmed": false,
    "blocked": false,
    "role": "pariatur dolore reprehenderit officia",
    "created_by": "incididunt sed",
    "updated_by": "in magna"
})


// Delete an existing user

@name("/users/:id")
DELETE "https://{{baseUrl}}/users/:id"



