#!/usr/bin/env dothttp

// Assigns a custom field context to projects.
// 
// If any project in the request is assigned to any context of the custom field, the operation fails.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Assign Custom Field Context To Projects")
PUT "https://{{baseUrl}}/rest/api/3/field/:fieldId/context/:contextId/project"
"Content-Type": "application/json"
json({
    "projectIds": [
        "<string>",
        "<string>"
    ]
})


// Removes a custom field context from projects.
// 
// A custom field context without any projects applies to all projects. Removing all projects from a custom field context would result in it applying to all projects.
// 
// If any project in the request is not assigned to the context, or the operation would result in two global contexts for the field, the operation fails.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Remove Custom Field Context From Projects")
POST "https://{{baseUrl}}/rest/api/3/field/:fieldId/context/:contextId/project/remove"
"Content-Type": "application/json"
json({
    "projectIds": [
        "<string>",
        "<string>"
    ]
})



