#!/usr/bin/env dothttp

// - Channels allowed: `app`, `meya`
// - Types allowed: `message`, `flow`, `notification`
// - The `flow_name` and `flow_args` fields are required only for `flow` type notifications.
// - The `extras` field is optional only for `notification` type. The `extras` should contain `flow_name`, `content_id` or `space_id` fields.
// 
// 
// This endpoint can also be used in machine-to-machine integration (M2M)
// [See more](https://documenter.getpostman.com/view/557358/RzfmG7QJ).

@name("Send notification")
POST "https://{{KNOWLEDGE_BASE_URL}}/workspace/v1/notifications"
"Content-Type": "application/json"
"Authorization": "{{VV_USER_TOKEN}}"
json({
    "campaign": "Postman campaign - {{$timestamp}}",
    "target": "{{VV_USER_USERNAME}}",
    "channel": "app",
    "type": "notification",
    "message": "Do you like Neymar 16/04 - 3?",
    "extras": {
        "content_id": 853387
    }
})



