#!/usr/bin/env dothttp

@name("{{baseUrl}}/TenantConfig/DeleteAdminSecurityQuestion")
POST "https://{{baseUrl}}/TenantConfig/DeleteAdminSecurityQuestion"
"Content-Type": "application/json"
? "Id"= "<string>"
data('{
    "Id": "<string>"
}')


// Reserved for on premises environments.
@name("{{baseUrl}}/TenantConfig/DeleteAdvancedConfig")
POST "https://{{baseUrl}}/TenantConfig/DeleteAdvancedConfig"
"Content-Type": "application/json"
data('{
    "tenantId": "<string>",
    "key": "<string>"
}')


@name("{{baseUrl}}/TenantConfig/GetAdminSecurityQuestion")
POST "https://{{baseUrl}}/TenantConfig/GetAdminSecurityQuestion"
? "Id"= "<string>"


@name("{{baseUrl}}/TenantConfig/GetAdminSecurityQuestions")
POST "https://{{baseUrl}}/TenantConfig/GetAdminSecurityQuestions"


// Retrieves the full configuration list for Opie... the combined set of "global" config table rows //             and "blessed tenant" rows from config table, so that they can be presented in a UI.
@name("{{baseUrl}}/TenantConfig/GetAdvancedConfig")
POST "https://{{baseUrl}}/TenantConfig/GetAdvancedConfig"


@name("{{baseUrl}}/TenantConfig/GetCustomerConfig")
POST "https://{{baseUrl}}/TenantConfig/GetCustomerConfig"


// Please use the generic GetEditableMessageTemplates instead.
@name("{{baseUrl}}/TenantConfig/GetEditableMailTemplates")
POST "https://{{baseUrl}}/TenantConfig/GetEditableMailTemplates"


@name("{{baseUrl}}/TenantConfig/GetEditableMessageTemplate")
POST "https://{{baseUrl}}/TenantConfig/GetEditableMessageTemplate"
? "templateName"= "<string>"
? "templateType"= "<string>"


@name("{{baseUrl}}/TenantConfig/GetEditableMessageTemplates")
POST "https://{{baseUrl}}/TenantConfig/GetEditableMessageTemplates"


@name("{{baseUrl}}/TenantConfig/GetGoogleKey")
POST "https://{{baseUrl}}/TenantConfig/GetGoogleKey"


@name("{{baseUrl}}/TenantConfig/GetMobileConfig")
POST "https://{{baseUrl}}/TenantConfig/GetMobileConfig"


@name("{{baseUrl}}/TenantConfig/GetSMTPConfig")
POST "https://{{baseUrl}}/TenantConfig/GetSMTPConfig"


@name("{{baseUrl}}/TenantConfig/GetTwilioConfig")
POST "https://{{baseUrl}}/TenantConfig/GetTwilioConfig"


@name("{{baseUrl}}/TenantConfig/ResetPortalConfig")
POST "https://{{baseUrl}}/TenantConfig/ResetPortalConfig"


@name("{{baseUrl}}/TenantConfig/SendTestMessageTemplate")
POST "https://{{baseUrl}}/TenantConfig/SendTestMessageTemplate"
? "templatePath"= "<string>"
? "templateType"= "<string>"


@name("{{baseUrl}}/TenantConfig/SetAdminSecurityQuestion")
POST "https://{{baseUrl}}/TenantConfig/SetAdminSecurityQuestion"
"Content-Type": "application/json"
data('{
    "Question": "<string>",
    "Culture": "all"
}')


// Reserved for on premises environments.
@name("{{baseUrl}}/TenantConfig/SetAdvancedConfig")
POST "https://{{baseUrl}}/TenantConfig/SetAdvancedConfig"
"Content-Type": "application/json"
data('{
    "tenantId": "<string>",
    "value": "<string>",
    "key": "<string>"
}')


@name("{{baseUrl}}/TenantConfig/SetCustomerConfig")
POST "https://{{baseUrl}}/TenantConfig/SetCustomerConfig"
"Content-Type": "application/json"
data('{
    "OtpCodeLength": "<integer>",
    "Icon": "<string>",
    "EnableUmc": "<boolean>",
    "SendPasswordChangeConfirmation": "<boolean>",
    "LoginBannerMessage": "<string>",
    "LoginSampleText": "<string>",
    "PortalImage": "<string>",
    "LoginBannerMessageL10nEnabled": "<boolean>",
    "ThemeColor": "<string>",
    "GlobalImage": "<string>",
    "MfaAttributeMapping": [
        "<object>",
        "<object>"
    ],
    "LoginBackgroundImage": "<string>",
    "CompanyName": "<string>",
    "IsOriginValidationEnabled": "<boolean>",
    "WelcomeMessage": "<string>",
    "EmailImage": "<string>",
    "LoginImage": "<string>",
    "IsOriginValidationOnGetEnabled": "<boolean>",
    "ForgotUsernameAllowed": "<boolean>",
    "NavigationColor": "<string>",
    "IsPasswordPersistanceEnabled": "<boolean>",
    "FastSearchEnabledEntities": [
        "<string>",
        "<string>"
    ],
    "PrivacyPolicyLink": "<string>",
    "AllowCors": [
        "<string>",
        "<string>"
    ],
    "BackgroundColor": "<string>",
    "CustomerCompany": "<string>",
    "DisplayLoginBanner": "<boolean>",
    "TermsOfUseLink": "<string>"
}')


@name("{{baseUrl}}/TenantConfig/SetGoogleKey")
POST "https://{{baseUrl}}/TenantConfig/SetGoogleKey"
"Content-Type": "application/json"
data('{
    "googleKey": "<string>",
    "GoogleKeyEnabled": "<boolean>"
}')


@name("{{baseUrl}}/TenantConfig/SetMobileConfig")
POST "https://{{baseUrl}}/TenantConfig/SetMobileConfig"
"Content-Type": "application/json"
data('{
    "CompanyName": "<string>",
    "WelcomeMessage": "<string>",
    "EndpointEnrollWelcomeTextL10nEnabled": "<boolean>",
    "CompanyImageBackgroundColor": "<string>",
    "CompanyImage": "<string>",
    "LocalizationMappings": [
        "<object>",
        "<object>"
    ]
}')


// Reserved for on premises environments.
@name("{{baseUrl}}/TenantConfig/SetPasswordPersistance")
POST "https://{{baseUrl}}/TenantConfig/SetPasswordPersistance"
? "value"= "<string>"


@name("{{baseUrl}}/TenantConfig/SetSMTPConfig")
POST "https://{{baseUrl}}/TenantConfig/SetSMTPConfig"
"Content-Type": "application/json"
data('{
    "Port": "<boolean>",
    "Host": "<boolean>",
    "SSL": "<boolean>",
    "Pass": "<boolean>",
    "User": "<boolean>",
    "SmtpConfigEnabled": "<boolean>",
    "UseConnectors": "<boolean>",
    "Connectors": [
        "<string>",
        "<string>"
    ]
}')


@name("{{baseUrl}}/TenantConfig/SetTwilioConfig")
POST "https://{{baseUrl}}/TenantConfig/SetTwilioConfig"
"Content-Type": "application/json"
data('{
    "Sid": "<string>",
    "Token": "<string>",
    "FromNumber": "<string>",
    "SmsConfigEnabled": "<string>"
}')


@name("{{baseUrl}}/TenantConfig/TestSMTPConfig")
POST "https://{{baseUrl}}/TenantConfig/TestSMTPConfig"
"Content-Type": "application/json"
data('{
    "Port": "<boolean>",
    "Host": "<boolean>",
    "SSL": "<boolean>",
    "Pass": "<boolean>",
    "User": "<boolean>",
    "SmtpConfigEnabled": "<boolean>",
    "UseConnectors": "<boolean>",
    "Connectors": [
        "<string>",
        "<string>"
    ]
}')


@name("{{baseUrl}}/TenantConfig/TestTwilioConfig")
POST "https://{{baseUrl}}/TenantConfig/TestTwilioConfig"
"Content-Type": "application/json"
data('{
    "Sid": "<string>",
    "Token": "<string>",
    "FromNumber": "<string>",
    "SmsConfigEnabled": "<string>"
}')



