#!/usr/bin/env dothttp

// Blink the LEDs on a device
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// duration| integer| The duration in seconds. Must be between 5 and 120. Default is 20 seconds
// period| integer| The period in milliseconds. Must be between 100 and 1000. Default is 160 milliseconds
// duty| integer| The duty cycle as the percent active. Must be between 10 and 90. Default is 50.

@name("Blink The LE Ds On A Device")
POST "https://{{baseUrl}}/devices/:serial/blinkLeds"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "duration": "<integer>",
    "period": "<integer>",
    "duty": "<integer>"
}')


// Reboot a device

@name("Reboot A Device")
POST "https://{{baseUrl}}/devices/:serial/reboot"
"X-Cisco-Meraki-API-Key": ""



