#!/usr/bin/env dothttp

// #### JSON Payload
// ```
// {
//     "vendor_name": "ekahau"
// }
// ```

@name("importOrgMaps")
POST "https://{{host}}/api/v1/orgs/:org_id/sites/:site_name/maps/import"
files(
	("json", ""),
	("file", "None"),
	("csv", "None")
)



