#!/usr/bin/env dothttp

@name("find all users")
GET "https://{{url}}/api/users"
? "per_page"= "20"


// update the first user from the randomly selected user from the previous request

@name("update the first user")
PUT "https://{{url}}/api/users/1"
"Content-Type": "application/json"
json({
    "name": "{{username}}",
    "job": "{{userjob}}"
})



