#!/usr/bin/env dothttp

@name("Contact Request Share")
GET "https://{{host}}/services/data/v47.0/sobjects/ContactRequestShare/"


@name("Contact Request Share Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/ContactRequestShare/{ID}/"


@name("Describe Contact Request Share")
GET "https://{{host}}/services/data/v47.0/sobjects/ContactRequestShare/describe/"



