#!/usr/bin/env dothttp

// Retrieves a list of all payouts ordered by payout date, with the most recent being first. <strong>Note:</strong> As of version 2019-10, this endpoint implements pagination by using links that are provided in the response header. Sending the <code>page</code> parameter will return an error. To learn more, see <a href="https://help.shopify.com/api/guides/paginated-rest-results"><em>Making requests to paginated REST Admin API endpoints</em></a>.

@name("Return a list of all payouts")
GET "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/shopify_payments/payouts.json"
"Content-Type": "application/json"


// Retrieves a single payout by id.

@name("Return a single payout")
GET "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/shopify_payments/payouts/{{payout_id}}.json"
"Content-Type": "application/json"



