#!/usr/bin/env dothttp

// Return average wireless latency over time for a network, device, or network client

@name("Return average wireless latency over time for a network, device, or network client")
GET "https://{{baseUrl}}/networks/:networkId/wireless/latencyHistory"
"X-Cisco-Meraki-API-Key": ""
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "resolution"= "{{resolution}}"
? "autoResolution"= "{{autoResolution}}"
? "clientId"= "{{clientId}}"
? "deviceSerial"= "{{deviceSerial}}"
? "apTag"= "{{apTag}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "accessCategory"= "{{accessCategory}}"



