#!/usr/bin/env dothttp

@name("Delaware.gov")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "delaware_gov"


@name("Governor John Carney")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "JohnCarneyDE"


@name("Health and Human Services")
GET "https://api.twitter.com/1.1/statuses/user_timeline.json"
? "screen_name"= "Delaware_DHSS"



