#!/usr/bin/env dothttp

// List the uplink status of every Meraki MX, MG and Z series devices in the organization
@name("List the uplink status of every Meraki MX, MG and Z series devices in the organization")
GET "https://{{baseUrl}}/organizations/:organizationId/uplinks/statuses"
"X-Cisco-Meraki-API-Key": ""
? "perPage"= "{{perPage}}"
? "startingAfter"= "{{startingAfter}}"
? "endingBefore"= "{{endingBefore}}"
? "networkIds"= "{{networkIds}}"
? "serials"= "{{serials}}"
? "iccids"= "{{iccids}}"



