#!/usr/bin/env dothttp

// Returns all properties for the given space. Space properties are a key-value storage associated with a space.
// 
// **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘View’ permission for the space.

@name("Get space properties")
GET "https://{{baseUrl}}/api/space/:spaceKey/property"
? "expand"= "<string>"
? "expand"= "<string>"
? "start"= "0"
? "limit"= "10"


// Creates a new space property.
// 
// **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**:
// ‘Admin’ permission for the space.

@name("Create space property")
POST "https://{{baseUrl}}/api/space/:spaceKey/property"
"Content-Type": "application/json"
data('{
    "key": "<string>",
    "value": "<object>"
}')



