#!/usr/bin/env dothttp

@name("Get current active Placekey and predecessors")
POST "https://api.placekey.io/v1/lineage"
"apikey": "{{apikey}}"
json({
    "queries": [
        "222@5vg-7gt-f75"
    ]
})



