#!/usr/bin/env dothttp

@name("Get Prospects for Campaign")
GET "https://{{sb_client}}.salesboard.biz/v2/dashboards/prospects"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "latitude"= "52.068333530081304"
? "longitude"= "4.326610298925175"
? "include"= "coordinates,resultCodes,fields"
? 'filters'= '{"teams":[2,4,5,6,7,8], "campaigns":[109,110,111,114,117,119], "audiences":[1,2,3,5]}'
? 'filters'= '{"campaigns":[1]}'
? 'filters'= '{ "audiences":[21]}'
? "ID_Campaign"= "{{sb_campaign_id}}"


@name("Get Prospects for Campaign (no location)")
GET "https://{{sb_client}}.salesboard.biz/v2/dashboards/prospects"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "latitude"= "52.068333530081304"
? "longitude"= "4.326610298925175"
? "include"= "coordinates,resultCodes,fields"
? 'filters'= '{"teams":[2,4,5,6,7,8], "campaigns":[109,110,111,114,117,119], "audiences":[1,2,3,5]}'
? 'filters'= '{"campaigns":[1]}'
? 'filters'= '{ "audiences":[21]}'
? "ID_Campaign"= "{{sb_campaign_id}}"


@name("Get Prospects by scroll id")
POST "https://{{sb_client}}.salesboard.biz/v2/dashboards/prospects/scroll"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
json({
    "scroll_id": "{{sb_scroll_id}}",
    "ID_Campaign": "{{sb_campaign_id}}",
    "include": "coordinates,resultCodes,fields"
})


@name("Update Prospect")
PUT "https://{{sb_client}}.salesboard.biz/v1/prospects/{{sb_prospect_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
json({
    "fields": {
        "name": "Sharewire",
        "postcode": "2516BE",
        "houseNumber": 36,
        "houseSuffix": "A",
        "country": "Netherlands"
    },
    "audiences": [
        1
    ]
})


@name("Delete Prospect")
DELETE "https://{{sb_client}}.salesboard.biz/v1/prospects/{{sb_prospect_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"




