#!/usr/bin/env dothttp

@name("Check public organization membership for a user")
GET "https://{{baseUrl}}/orgs/:org/public_members/:username"


// The user can publicize their own membership. (A user cannot publicize the membership for another user.)
// 
// Note that you'll need to set `Content-Length` to zero when calling out to this endpoint. For more information, see "[HTTP verbs](https://docs.github.com/rest/overview/resources-in-the-rest-api#http-verbs)."

@name("Set public organization membership for the authenticated user")
PUT "https://{{baseUrl}}/orgs/:org/public_members/:username"


@name("Remove public organization membership for the authenticated user")
DELETE "https://{{baseUrl}}/orgs/:org/public_members/:username"



