#!/usr/bin/env dothttp

// Lista os afastamentos e férias de um colaborador
// 
// ## Variáveis na URL
// 
// | Nome | Tipo | Obrigatório | Descrição |
// | ---- |----- |------------ | --------- |
// | employee_id | Integer | Sim | ID do colaborador |
// 
// 
// ## Atributos disponíveis
// 
// | Nome | Tipo | Descrição |
// | ------ | ------|----------- |
// | id | Integer | Identificador sequencial gerado automaticamente pelo sistema |
// | start_date | Date | Data de início|
// | end_date | Date | Data de término |
// | observation | String | Descrição do afastamento ou férias |
// | total_days | Integer | Total de dias afastado |
// | is_medical_certificate | Boolean | É atestado médico? |
// | crm | String | Número do CRM |
// | cid | String | Número do CID |
// | medical_name | String | Nome do médico |
// | clinic_name | String | Nome da clinica |
// | file | Object | Objeto do arquivo (Verificar tabela descritiva do objeto) |
// | employee | Object | Objeto do colaborador (Verificar tabela descritiva do objeto) |
// | absence_type | Object | Objeto do tipo de afastamento (Verificar tabela descritiva do objeto) |
// 
// #### Formato do objeto file
// 
// | Nome | Tipo    | Descrição                                                    |
// | ---- | ------- | ------------------------------------------------------------ |
// | url   | String | URL do arquivo anexado |
// | content_type | String | Formato do arquivo anexado |
// 
// #### Formato do objeto employee
// 
// | Nome | Tipo    | Descrição                                                    |
// | ---- | ------- | ------------------------------------------------------------ |
// | id   | Integer | Identificador sequencial gerado automaticamente pelo sistema |
// | picture | Object | Objeto da imagem de perfil do colaborador |
// | name | String  | Tipo de registro |
// 
// #### Formato do objeto picture
// 
// | Nome | Tipo    | Descrição                                                    |
// | ---- | ------- | ------------------------------------------------------------ |
// | url   | String | URL da imagem em tamanho padrão |
// | medium_url | String | URL da imagem redimencionada para tamanho médio |
// | small_url | String  | URL da imagem redimencionada para tamanho pequeno |
// 
// #### Formato do objeto absence_type
// 
// | Nome | Tipo    | Descrição                                                    |
// | ---- | ------- | ------------------------------------------------------------ |
// | id   | Integer | Identificador sequencial gerado automaticamente pelo sistema |
// | name | String | Nome do tipo do afastamento |
// 
// ## Opções do absence_type
// 
// | Valor | Descrição |
// | ----- | --------- |
// | 1     | Afastamento |
// | 2     | Férias |
// | 3     | Afastamento ou férias (indefinido) |

@name("Listar")
GET "https://{{server_url}}/external_api/v1/employees/{{employee_id}}/absences"
"access-token": "{{client_token}}"
? "attributes"= "id,observation,start_date,end_date,total_days"
? "count"= "{{count}}"
? "page"= "{{page_number}}"
? "per_page"= "{{per_page}}"


// Exibe o afastamento ou férias de um colaborador
// 
// ## Variáveis na URL
// 
// | Nome | Tipo | Obrigatório | Descrição |
// | ---- |----- |------------ | --------- |
// | employee_id | Integer | Sim | ID do colaborador |
// | absence_id | Integer | Sim | ID do afastamento ou férias |
// 
// 
// ## Atributos disponíveis
// 
// | Nome | Tipo | Descrição |
// | ------ | ------|----------- |
// | id | Integer | Identificador sequencial gerado automaticamente pelo sistema |
// | start_date | Date | Data de início|
// | end_date | Date | Data de término |
// | observation | String | Descrição do afastamento ou férias |
// | total_days | Integer | Total de dias afastado |
// | is_medical_certificate | Boolean | É atestado médico? |
// | crm | String | Número do CRM |
// | cid | String | Número do CID |
// | medical_name | String | Nome do médico |
// | clinic_name | String | Nome da clinica |
// | file | Object | Objeto do arquivo (Verificar tabela descritiva do objeto) |
// | employee | Object | Objeto do colaborador (Verificar tabela descritiva do objeto) |
// | absence_type | Object | Objeto do tipo de afastamento (Verificar tabela descritiva do objeto) |
// 
// #### Formato do objeto file
// 
// | Nome | Tipo    | Descrição                                                    |
// | ---- | ------- | ------------------------------------------------------------ |
// | url   | String | URL do arquivo anexado |
// | content_type | String | Formato do arquivo anexado |
// 
// #### Formato do objeto employee
// 
// | Nome | Tipo    | Descrição                                                    |
// | ---- | ------- | ------------------------------------------------------------ |
// | id   | Integer | Identificador sequencial gerado automaticamente pelo sistema |
// | picture | Object | Objeto da imagem de perfil do colaborador |
// | name | String  | Tipo de registro |
// 
// #### Formato do objeto picture
// 
// | Nome | Tipo    | Descrição                                                    |
// | ---- | ------- | ------------------------------------------------------------ |
// | url   | String | URL da imagem em tamanho padrão |
// | medium_url | String | URL da imagem redimencionada para tamanho médio |
// | small_url | String  | URL da imagem redimencionada para tamanho pequeno |
// 
// #### Formato do objeto absence_type
// 
// | Nome | Tipo    | Descrição                                                    |
// | ---- | ------- | ------------------------------------------------------------ |
// | id   | Integer | Identificador sequencial gerado automaticamente pelo sistema |
// | name | String | Nome do tipo do afastamento |
// 
// ## Opções do absence_type
// 
// | Valor | Descrição |
// | ----- | --------- |
// | 1     | Afastamento |
// | 2     | Férias |
// | 3     | Afastamento ou férias (indefinido) |

@name("Detalhar")
GET "https://{{server_url}}/external_api/v1/employees/{{employee_id}}/absences/{{absence_id}}"
"access-token": "{{client_token}}"
? "attributes"= "id,start_date,end_date,observation,total_days"


// Cria um afastamento ou férias para um colaborador.
// 
// ## Variáveis na URL
// 
// | Nome | Tipo | Obrigatório | Descrição |
// | ---- |----- |------------ | --------- |
// | employee_id | Integer | Sim | ID do colaborador |
// 
// ## Estrutura do objeto JSON a ser enviado
// 
// | Nome | Tipo | Obrigatório | Descrição |
// | ---- | -----|------------ | --------- |
// | start_date | Date | Sim | Data de início|
// | end_date | Date | Sim | Data de término |
// | observation | String | Sim | Descrição do afastamento ou férias |
// | absence_type | Inteiro | Sim | Tipo de afastamento (Verificar tabela de opções do absence_type) |
// | is_medical_certificate | Boolean | Sim | É atestado médico? |
// | crm | String | Não | Número do CRM (É obrigatório caso seja atestado médico) |
// | cid | String | Não | Número do CID (É obrigatório caso seja atestado médico) |
// | medical_name | Não | String | Nome do médico (É obrigatório caso seja atestado médico) |
// | clinic_name | Não | String | Nome da clinica (É obrigatório caso seja atestado médico) |
// | file | String | Não | Objeto do arquivo (Verificar tabela descritiva do objeto) (É obrigatório caso seja atestado médico) |
// 
// ## Opções do absence_type
// 
// | Valor | Descrição |
// | ----- | --------- |
// | 1     | Afastamento |
// | 2     | Férias |

@name("Criar")
POST "https://{{server_url}}/external_api/v1/employees/{{employee_id}}/absences"
"Content-Type": "application/json"
"access-token": "{{client_token}}"
data('{
	"absence":
	{
		"observation":"{{observation}}",
        "absence_type": {{absence_type}},
		"start_date":"{{start_date}}",
		"end_date":"{{end_date}}"
		
	}
	
}')


// Edita um afastamento ou férias para o colaborador.
// 
// ## Variáveis na URL
// 
// | Nome | Tipo | Obrigatório | Descrição |
// | ---- |----- |------------ | --------- |
// | employee_id | Integer | Sim | ID do colaborador |
// | absence_id | Integer | Sim | ID do afastamento ou férias |
// 
// ## Estrutura do objeto JSON a ser enviado
// 
// | Nome | Tipo | Obrigatório | Descrição |
// | ---- | -----|------------ | --------- |
// | start_date | Date | Sim | Data de início|
// | end_date | Date | Sim | Data de término |
// | observation | String | Sim | Descrição do afastamento ou férias |
// | absence_type | Inteiro | Sim | Tipo de afastamento (Verificar tabela de opções do absence_type) |
// | is_medical_certificate | Boolean | Sim | É atestado médico? |
// | crm | String | Não | Número do CRM (É obrigatório caso seja atestado médico) |
// | cid | String | Não | Número do CID (É obrigatório caso seja atestado médico) |
// | medical_name | Não | String | Nome do médico (É obrigatório caso seja atestado médico) |
// | clinic_name | Não | String | Nome da clinica (É obrigatório caso seja atestado médico) |
// | file | String | Não | Objeto do arquivo (Verificar tabela descritiva do objeto) (É obrigatório caso seja atestado médico) |
// 
// ## Opções do absence_type
// 
// | Valor | Descrição |
// | ----- | --------- |
// | 1     | Afastamento |
// | 2     | Férias |

@name("Editar")
PUT "https://{{server_url}}/external_api/v1/employees/{{employee_id}}/absences/{{absence_id}}"
"Content-Type": "application/json"
"access-token": "{{client_token}}"
json({
    "absence": {
        "start_date": "{{start_date}}",
        "end_date": "{{end_date}}"
    }
})


// Exclui o afastamento ou férias de um colaborador
// 
// ## Variáveis na URL
// 
// | Nome | Tipo | Obrigatório | Descrição |
// | ---- |----- |------------ | --------- |
// | employee_id | Integer | Sim | ID do colaborador |
// | absence_id | Integer | Sim | ID do afastamento ou férias |

@name("Excluir")
DELETE "https://{{server_url}}/external_api/v1/employees/{{employee_id}}/absences/{{absence_id}}"
"access-token": "{{client_token}}"




