#!/usr/bin/env dothttp

@name("Create Notification")
POST "https://localhost/api/notification/create-notification/:token"



@name("Read Notification")
GET "https://localhost/api/notification/read-notification/:token/:user/:notification"


@name("Read All Notification")
GET "https://192.168.8.100/api/notification/read-all-notification/:user/:token"



