#!/usr/bin/env dothttp

// Returns PAN details such as full name, category and status

@name("Verify PAN")
GET "https://{{sandbox_host}}/pans/:pan/verify"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"
? "consent"= "{{consent}}"
? "reason"= "{{reason}}"



