#!/usr/bin/env dothttp

// With multiple queries, you can also specify an ID with each query that echoes back, if you'd like.

@name("Get Placekeys for multiple things at once")
POST "https://api.placekey.io/v1/placekeys"
"apikey": "{{apikey}}"
"Content-Type": "application/json"
json({
    "queries": [
        {
            "street_address": "1543 Mission Street, Floor 3",
            "city": "San Francisco",
            "region": "CA",
            "postal_code": "94105",
            "iso_country_code": "US"
        },
        {
            "query_id": "thisqueryidaloneiscustom",
            "location_name": "Twin Peaks Petroleum",
            "street_address": "598 Portola Dr",
            "city": "San Francisco",
            "region": "CA",
            "postal_code": "94131",
            "iso_country_code": "US"
        },
        {
            "latitude": 37.7371,
            "longitude": -122.44283
        }
    ]
})



