#!/usr/bin/env dothttp

@name("/wc/v3/orders/:order_id/refunds")
GET "https://{{baseUrl}}/wc/v3/orders/:order_id/refunds"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "context"= "view"
? "context"= "view"
? "page"= "<string>"
? "per_page"= "<string>"
? "search"= "<string>"
? "after"= "<dateTime>"
? "before"= "<dateTime>"
? "exclude"= "<string>"
? "include"= "<string>"
? "offset"= "<string>"
? "order"= "desc"
? "order"= "desc"
? "orderby"= "date"
? "orderby"= "date"
? "parent"= "<string>"
? "parent_exclude"= "<string>"
? "dp"= "<string>"


@name("/wc/v3/orders/:order_id/refunds")
POST "https://{{baseUrl}}/wc/v3/orders/:order_id/refunds"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
"Content-Type": "multipart/form-data"
files(
	("amount", "<string>"),
	("reason", "<string>"),
	("refunded_by", "<string>"),
	("meta_data", "<string>"),
	("api_refund", "<string>")
)



