#!/usr/bin/env dothttp

@name("Get filtered activities list")
GET "https://{{base_url}}/api/task_manager/v2/activities"
? "policyType"= "backup"
? "id"= "956171946968481792"
? "resultCode"= "error"
? "lod"= "short"
? "state"= "completed"
? "taskId"= "975150580617969665"
? "uuid"= "D4BFF5F2-B9B3-4774-BD42-73951B4C84BC"
? "completedAt"= "ge(2021-02-01T00:00:00Z)"



