#!/usr/bin/env dothttp

// Performs search based on criteria specified.

@name("Search Using Criteria")
GET "https://{{api-domain}}/crm/v2/Leads/search"
? "criteria"= "((Last_Name:equals:Burns\,B)or(First_Name:starts_with:P))"



// Performs search using Email.

@name("Search Using Email")
GET "https://{{api-domain}}/crm/v2/Leads/search"
? "email"= "patricia.boyle@zylker.com"



// Perfoms search using phone

@name("Search Using Phone")
GET "https://{{api-domain}}/crm/v2/Leads/search"
? "phone"= "9090909090"



// Performs search using word

@name("Search Using Word")
GET "https://{{api-domain}}/crm/v2/Leads/search"
? "word"= "patricia"




