#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get GitHub Actions billing for an enterprise")
GET "https://{{baseUrl}}/enterprises/{{enterprise}}/settings/billing/actions"


@name("Get GitHub Packages billing for an enterprise")
GET "https://{{baseUrl}}/enterprises/{{enterprise}}/settings/billing/packages"


@name("Get shared storage billing for an enterprise")
GET "https://{{baseUrl}}/enterprises/{{enterprise}}/settings/billing/shared-storage"



