#!/usr/bin/env dothttp

// To add tags to records.

@name("Leads")
POST "https://{{api-domain}}/crm/v2/Leads/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "important,Nurturing Lead"


// To add tags to records.

@name("Accounts")
POST "https://{{api-domain}}/crm/v2/Accounts/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Passive Lead,Active"


// To add tags to records.

@name("Contacts")
POST "https://{{api-domain}}/crm/v2/Contacts/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Passive Lead,Active"


// To add tags to records.

@name("Deals")
POST "https://{{api-domain}}/crm/v2/Deals/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Cold Deal,Active Deal"


// To add tags to records.

@name("Campaigns")
POST "https://{{api-domain}}/crm/v2/Campaigns/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Seasonal,Traditional campaign"


// To add tags to records.

@name("Tasks")
POST "https://{{api-domain}}/crm/v2/Tasks/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Seasonal,Traditional"


// To add tags to records.

@name("Cases")
POST "https://{{api-domain}}/crm/v2/Cases/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Bugs,Feature Request"


// To add tags to records.

@name("Events")
POST "https://{{api-domain}}/crm/v2/Events/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Virtual,Physical"


// To add tags to records.

@name("Calls")
POST "https://{{api-domain}}/crm/v2/Events/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Cold Call"


// To add tags to records.

@name("Solutions")
POST "https://{{api-domain}}/crm/v2/Solutions/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Custom Slution,Standard Solution"


// To add tags to records.

@name("Products")
POST "https://{{api-domain}}/crm/v2/Products/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Custom,Standard"


// To add tags to records.

@name("Vendors")
POST "https://{{api-domain}}/crm/v2/Vendors/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "B2B"


// To add tags to records.

@name("Price Books")
POST "https://{{api-domain}}/crm/v2/Price_Books/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Standard,Supplier"


// To add tags to records.

@name("Quotes")
POST "https://{{api-domain}}/crm/v2/Quotes/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Standard,Fixed Quote"


// To add tags to records.

@name("Sales Orders")
POST "https://{{api-domain}}/crm/v2/Sales_Orders/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Standard,Cash Orders"


// To add tags to records.

@name("Purchase Orders")
POST "https://{{api-domain}}/crm/v2/Purchase_Orders/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Standard Order,"


// To add tags to records.

@name("Invoices")
POST "https://{{api-domain}}/crm/v2/Invoices/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Cash Invoice"


// To add tags to records.

@name("Custom")
POST "https://{{api-domain}}/crm/v2/{{custom_module_api_name}}/actions/remove_tags"
? "ids"= "{{record_id1,record_id2,..}}"
? "tag_names"= "Default"



