#!/usr/bin/env dothttp

// Gets a single Team invite

@name("Get Team Invite")
GET "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams/invites/{{team_invite_zuid}}"



// Gets a single user's Team invites

@name("Get All Team Invites")
GET "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams/invites"



// Creates a single invite for the given Team

@name("Create Team Invite")
POST "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams/invites"
"Content-Type": "application/json"
"": ""
json({
    "teamZUID": "",
    "inviteeName": "Test testington",
    "inviteeEmail": "test@email.com"
})


// Responds to a team invite based on the query parameter provided
// 
// - ?action=accept	:: Accept an invite.
// - ?action=decline	:: Decline an invite.
// - ?action=cancel	:: Cancel an invite; you must have sufficient privilege to perform this

@name("Respond to Team Invite")
PUT "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams/invites/{{team_invite_zuid}}"
"Content-Type": "application/json"
? "action"= "accept"



// Deletes a single invite for a Team

@name("Delete Team Invite")
DELETE "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams/invites/{{team_invite_zuid}}"
"Content-Type": "application/json"
"": ""




