#!/usr/bin/env dothttp

// - required params:
//   1. email
//   2. contact_no
//   3. is_default_password
// - just set is_default_password to true because non celebrities login is using OTP.

@name("Sign Up")
POST "https://order-uat.blocklist.mobi/api/users"
"Content-Type": "application/json"
data('{
  "first_name": "imaprog",
  "last_name": "coder",
  "postal_code": "",
  "address": "",
  "contact_no": "6017389445",
  "email": "shaffiq666@gmail.com",
  "username": "shafiq",
  "is_default_password": true
}')


// - required params:
//   1. email
//   2. contact_no
//   3. password
// - set the password for celebrities because celebrities login require password.

@name("Celebrity Sign Up")
POST "https://order-uat.blocklist.mobi/api/celebrity/users"
"Content-Type": "application/json"
data('{
  "first_name": "celeb",
  "last_name": "one",
  "postal_code": "",
  "address": "",
  "contact_no": "60174556378",
  "email": "celeb@gmail.com",
  "username": "imaprog",
  "password": "qijang12345",
  "wallets": [
  	{
  		"wallet_type_id": 1,
  		"wallet_address": "zx0jjdojowjjjwojw211o"
  	},
  	{
  		"wallet_type_id": 2,
  		"wallet_address": "zcxjdgsdixuouodo323oj"
  	}
   ]
}')


// - all fields are required.
// - scope & grant_type parameters value remain the same, only the username & verification_code may change.

@name("Login")
POST "http://order-uat.blocklist.mobi/api/oauth/token"
"Content-Type": "application/json"
data('{
  "username": "shafiqaziz06@gmail.com",
  "verification_code": "k7mj1x1hbw",
  "scope": "user",
  "grant_type": "password"
}')


// - all fields are required.
// - scope & grant_type parameters value remain the same, only the username & password may change.

@name("Celebrity Login")
POST "http://order-uat.blocklist.mobi/api/oauth/token"
"Content-Type": "application/json"
data('{
  "username": "celeb@gmail.com",
  "password": "qijang12345",
  "scope": "user",
  "grant_type": "password"
}')


// - use this API to received OTP for non celebrities login.
// - non celebrities login is the Login API.
// - the OTP received from SMS is the value for verification_code parameter for Login API.

@name("Request OTP")
POST "https://order-uat.blocklist.mobi/api/req/otp"
"Content-Type": "application/json"
data('{
	"username": "shafiqaziz06@gmail.com"
}')



