#!/usr/bin/env dothttp

// Gets a specific self-hosted runner configured in an organization.
// 
// You must authenticate using an access token with the `admin:org` scope to use this endpoint.

@name("Get a self-hosted runner for an organization")
GET "https://{{baseUrl}}/orgs/:org/actions/runners/:runner_id"


// Forces the removal of a self-hosted runner from an organization. You can use this endpoint to completely remove the runner when the machine you were using no longer exists.
// 
// You must authenticate using an access token with the `admin:org` scope to use this endpoint.

@name("Delete a self-hosted runner from an organization")
DELETE "https://{{baseUrl}}/orgs/:org/actions/runners/:runner_id"



