#!/usr/bin/env dothttp

@name("Create Message")
POST "https://{{api_url}}/messages"
json({
    "text": "Hello World",
    "emitter": "{{user_id}}",
    "receptor": ""
})


@name("Get messages")
GET "https://{{api_url}}/messages/"
? "emitter_id"= "{{user_id}}"




