#!/usr/bin/env dothttp

@name("Status")
GET "https://{{endpoint}}/status.xml"
"Authorization": "Basic {{credentials}}"



@name("Status Audio Volume")
GET "https://{{endpoint}}/getxml"
"Authorization": "Basic {{credentials}}"
? "location"= "/Status/Audio/Volume"



@name("Configuration")
GET "https://{{endpoint}}/configuration.xml"
"Authorization": "Basic {{credentials}}"




