#!/usr/bin/env dothttp

// List places.// Use query parameters to filter the response.// // https://developer.webex.com/docs/api/v1/places/list-places
@name("List Places")
GET "https://{{WEBEXAPI}}/places"
"Authorization": "Bearer {{access_token}}"


// Create a place.// // https://developer.webex.com/docs/api/v1/places/create-a-place
@name("Create a Place")
POST "https://{{WEBEXAPI}}/places"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
data('{ 
	"displayName" : "DevNetZone",
	"type" : "room_device"
}')


// Shows details for a place, by ID.// Specify the place ID in the placeId parameter in the URI.// // https://developer.webex.com/docs/api/v1/places/get-place-details
@name("Get Place Details")
GET "https://{{WEBEXAPI}}/places/{{_place}}"
"Authorization": "Bearer {{access_token}}"


// Updates details for a place, by ID.// Specify the place ID in the placeId parameter in the URI.// // https://developer.webex.com/docs/api/v1/places/update-a-place
@name("Update a Place")
PUT "https://{{WEBEXAPI}}/places/{{_place}}"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
data('{ 
	"displayName" : "home",
	"type" : "room_device"
}')


// Generate an activation code for a device in a specific place by placeId. Currently, activation codes may only be generated for shared places--personal mode is not supported.// // https://developer.webex.com/docs/api/v1/devices/create-a-device-activation-code
@name("Create a Device Activation Code")
POST "https://{{WEBEXAPI}}/devices/activationCode"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
data('{
	"placeId" : "{{_place}}"
}')


// Deletes a place, by ID. Will also delete all devices associated with the place.// Specify the place ID in the placeId parameter in the URI.// // https://developer.webex.com/docs/api/v1/places/delete-a-place
@name("Delete a Place")
DELETE "https://{{WEBEXAPI}}/places/{{_place}}"
"Authorization": "Bearer {{access_token}}"



