#!/usr/bin/env dothttp

// OAuth required scopes: OR.Tasks or OR.Tasks.Write.
// 
// Required permissions: Tasks.Edit.

@name("Complete the task by saving task data and action taken")
POST "https://{{baseUrl}}/tasks/GenericTasks/CompleteTask"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
data('{
    "taskId": -10272561,
    "data": {},
    "action": "ut ad"
}')


// OAuth required scopes: OR.Tasks or OR.Tasks.Write.
// 
// Required permissions: Tasks.Create.

@name("Creates a new Generic Task.")
POST "https://{{baseUrl}}/tasks/GenericTasks/CreateTask"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
data('{
    "title": "labore reprehenderit",
    "type": "ExternalTask",
    "priority": "Critical",
    "data": {},
    "taskCatalogName": "",
    "externalTag": "in est qui cupidatat"
}')


// OAuth required scopes: OR.Tasks or OR.Tasks.Read.
// 
// Required permissions: Tasks.View.

@name("Returns task data dto")
GET "https://{{baseUrl}}/tasks/GenericTasks/GetTaskDataById"
"X-UIPATH-OrganizationUnitId": "12575632"
? "taskId"= "12575632"


// OAuth required scopes: OR.Tasks or OR.Tasks.Write.
// 
// Required permissions: Tasks.Edit.

@name("Save changes done by the current user and Reassign Task to another user")
POST "https://{{baseUrl}}/tasks/GenericTasks/SaveAndReassignTask"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
data('{
    "SaveData": true,
    "Data": {},
    "NoteText": "quis ad",
    "TaskId": 35919240,
    "UserId": -24408745,
    "UserNameOrEmail": "in consectetur minim incididunt"
}')


// OAuth required scopes: OR.Tasks or OR.Tasks.Write.
// 
// Required permissions: Tasks.Edit.

@name("Save Task data")
PUT "https://{{baseUrl}}/tasks/GenericTasks/SaveTaskData"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
data('{
    "data": {},
    "taskId": -56698999
}')



