#!/usr/bin/env dothttp

# imported from http://localhost:8000/Stripe%20API.postman_collection.json

@name("List all locations")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604bc35730>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Create a location")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604bc35f70>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "address[country]": [
        "<string>"
    ],
    "address[city]": [
        "<string>"
    ],
    "address[line1]": [
        "<string>"
    ],
    "address[line2]": [
        "<string>"
    ],
    "address[postal_code]": [
        "<string>"
    ],
    "address[state]": [
        "<string>"
    ],
    "display_name": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})


@name("Delete a location")
DELETE "<dotextensions.server.postman2_1.URLClass object at 0x7f604bc38790>"
"Content-Type": "application/x-www-form-urlencoded"



@name("Retrieve a location")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604bc39190>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Update a location")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604bc399a0>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "address[city]": [
        "<string>"
    ],
    "address[country]": [
        "<string>"
    ],
    "address[line1]": [
        "<string>"
    ],
    "address[line2]": [
        "<string>"
    ],
    "address[postal_code]": [
        "<string>"
    ],
    "address[state]": [
        "<string>"
    ],
    "display_name": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})



