#!/usr/bin/env dothttp

// Retrieves all the data attributes for a person, based on the Klaviyo Person ID.

@name("Get Profile")
GET "https://{{baseUrl}}/v1/person/:person_id"
? "api_key"= "PRIVATE_KEY"


// NOTE: If you are interested in creating or updating profiles in Klaviyo, you should be using the Identify API instead. The best use-case for this route is changing a profiles's email address or other primary identifier after a profile already exists in Klaviyo.
// 
// Add or update one more more attributes for a Person, based on the Klaviyo Person ID. If a property already exists, it will be updated. If a property is not set for that record, it will be created.
// 
// You can update any attribute, by sending one or more attributes along their new values, as query parameters. Recommended attributes for this endpoint: `$email`, `$phone_number`, `$id`

@name("Update Profile")
PUT "https://{{baseUrl}}/v1/person/:person_id"
? "api_key"= "PRIVATE_KEY"
? "$email"= "george.washington@klaviyo.com"
? "$phone_number"= "13239169023"
? "$id"= "EXTERNAL_ID"


// Returns a batched timeline of all events for a person.

@name("Get Profile's Events for all Metrics")
GET "https://{{baseUrl}}/v1/person/:person_id/metrics/timeline"
? "api_key"= "PRIVATE_KEY"
? "count"= "50"
? "sort"= "desc"


// Returns a person's batched timeline for one specific event type.

@name("Get Profile's Events for a Specific Metric")
GET "https://{{baseUrl}}/v1/person/:person_id/metric/:metric_id/timeline"
? "api_key"= "PRIVATE_KEY"
? "count"= "100"
? "sort"= "desc"



