#!/usr/bin/env dothttp

// It was the second incarnation of Lord Vishnu
// 
// In this incarnation, Lord Vishnu helped gods and demons to churn the milky sea and take out the nectar. He further made sure that demons did not get the nectar.
// 
// | Order  | Avatar | Cool | Range |
// | ------ |:------:|:----:|:-----:|
// |   1    | Matsya | Water | 01 |
// |   2    | Kurma  | Water + Land |02|
// |   3    | Varaha | Land| 03 |

@name("Who is he?")
GET "https://en.wikipedia.org/wiki/Kurma"
"Content-Type": "application/json"
"Authorization": "{{api-key}}"
"Secret_key": "internal_header"
"Date": "05:09"
? "internal_param"= "defined_secret"
? "value"= "a113"


// Feast your eyes with a most satisfying state of a life swimming through the course of its horizon

@name("Art of Relaxing")
GET "https://images.fineartamerica.com/images/{{image-id}}"



