#!/usr/bin/env dothttp

@name("Fetch cats, sorted by name (ascending)")
GET "https://{{url}}/cats"
? "sort"= "name"


@name("Fetch cats, sorted by name (descending)")
GET "https://{{url}}/cats"
? "sort"= "-name"



