#!/usr/bin/env dothttp

@name("/clients/:id/visit")
POST "https://{{baseUrl}}/clients/:id/visit"
"Content-Type": "application/json"
? "id_beacon"= "<id_beacon>"



@name("/clients/:id/visit")
OPTIONS "https://{{baseUrl}}/clients/:id/visit"



