#!/usr/bin/env dothttp

@name("/wc/v3/payment_gateways/:id")
GET "https://{{baseUrl}}/wc/v3/payment_gateways/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "context"= "view"
? "context"= "view"


@name("/wc/v3/payment_gateways/:id")
POST "https://{{baseUrl}}/wc/v3/payment_gateways/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
"Content-Type": "multipart/form-data"
files(
	("title", "<string>"),
	("description", "<string>"),
	("order", "<string>"),
	("enabled", "<string>"),
	("settings", "<string>")
)


@name("/wc/v3/payment_gateways/:id")
PUT "https://{{baseUrl}}/wc/v3/payment_gateways/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "title"= "<string>"
? "description"= "<string>"
? "order"= "<string>"
? "enabled"= "<string>"
? "settings"= "<string>"


@name("/wc/v3/payment_gateways/:id")
PATCH "https://{{baseUrl}}/wc/v3/payment_gateways/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "title"= "<string>"
? "description"= "<string>"
? "order"= "<string>"
? "enabled"= "<string>"
? "settings"= "<string>"



