#!/usr/bin/env dothttp

// List the dashboard administrators in this organization

@name("List The Dashboard Administrators In This Organization")
GET "https://{{baseUrl}}/organizations/:organizationId/admins"
"X-Cisco-Meraki-API-Key": ""


// Create a new dashboard administrator
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// email| string| The email of the dashboard administrator. This attribute can not be updated.
// name| string| The name of the dashboard administrator
// orgAccess| string| The privilege of the dashboard administrator on the organization. Can be one of 'full', 'read-only', 'enterprise' or 'none'
// tags| array| The list of tags that the dashboard administrator has privileges on
// networks| array| The list of networks that the dashboard administrator has privileges on
// authenticationMethod| string| The method of authentication the user will use to sign in to the Meraki dashboard. Can be one of 'Email' or 'Cisco SecureX Sign-On'. The default is Email authentication

@name("Create A New Dashboard Administrator")
POST "https://{{baseUrl}}/organizations/:organizationId/admins"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "email": "<string>",
    "name": "<string>",
    "orgAccess": "<string>",
    "tags": [
        {
            "tag": "<string>",
            "access": "<string>"
        },
        {
            "tag": "<string>",
            "access": "<string>"
        }
    ],
    "networks": [
        {
            "id": "<string>",
            "access": "<string>"
        },
        {
            "id": "<string>",
            "access": "<string>"
        }
    ],
    "authenticationMethod": "<string>"
}')


// Update an administrator
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// name| string| The name of the dashboard administrator
// orgAccess| string| The privilege of the dashboard administrator on the organization. Can be one of 'full', 'read-only', 'enterprise' or 'none'
// tags| array| The list of tags that the dashboard administrator has privileges on
// networks| array| The list of networks that the dashboard administrator has privileges on

@name("Update An Administrator")
PUT "https://{{baseUrl}}/organizations/:organizationId/admins/:adminId"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "name": "<string>",
    "orgAccess": "<string>",
    "tags": [
        {
            "tag": "<string>",
            "access": "<string>"
        },
        {
            "tag": "<string>",
            "access": "<string>"
        }
    ],
    "networks": [
        {
            "id": "<string>",
            "access": "<string>"
        },
        {
            "id": "<string>",
            "access": "<string>"
        }
    ]
}')


// Revoke all access for a dashboard administrator within this organization

@name("Revoke All Access For A Dashboard Administrator Within This Organization")
DELETE "https://{{baseUrl}}/organizations/:organizationId/admins/:adminId"
"X-Cisco-Meraki-API-Key": ""



