#!/usr/bin/env dothttp

@name("Order Item Change Event")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemChangeEvent/"


@name("Order Item Change Event Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemChangeEvent/{ID}/"


@name("Describe Order Item Change Event")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemChangeEvent/describe/"



