#!/usr/bin/env dothttp

@name("Get details of a specific field set.")
GET "https://{{baseUrl}}/v2/accounts/{{accountId}}/field_sets/{{fieldSetId}}"
"Accept": "text/plain, application/json, text/json"
"Authorization": "Bearer {{accessToken}}"
? "fieldsCustomDataFilters"= "{{fieldsCustomDataFilters}}"



