#!/usr/bin/env dothttp

@name("Like a Tweet")
POST "https://api.twitter.com/2/users/:id/likes"
data('// Replace tweet-id-you-want-to-like with the ID you wish to like
{
    "tweet_id": "tweet-id-you-want-to-like"
}')


@name("Liked Tweets")
GET "https://api.twitter.com/2/users/:id/liked_tweets"


@name("Liking users")
GET "https://api.twitter.com/2/tweets/:id/liking_users"


@name("Unlike a Tweet")
DELETE "https://api.twitter.com/2/users/:id/likes/:tweet_id"



