#!/usr/bin/env dothttp

// #### Population Data Model
// 
// Property | Mutable? | Required? | Type | Notes
// -------- | -------- | --------- | ---- | -----
// name | Y | Y | String; must be unique w/in Env, max 256 characters | Uniqueness in Env is _case insensitive_
// description | Y | N | String |

@name("CREATE Population")
POST "https://{{apiPath}}/environments/{{envID}}/populations"
"content-type": "application/json"
json({
    "name": "Population_{{$timestamp}}",
    "description": "this is my population"
})


@name("READ All Populations")
GET "https://{{apiPath}}/environments/{{envID}}/populations"


@name("READ One Population")
GET "https://{{apiPath}}/environments/{{envID}}/populations/{{popID}}"


// See `CREATE` request for data model.

@name("UPDATE Population")
PUT "https://{{apiPath}}/environments/{{envID}}/populations/{{popID}}"
"content-type": "application/json"
json({
    "name": "UPDATED_population",
    "description": "This population has been updated."
})


@name("DELETE Population")
DELETE "https://{{apiPath}}/environments/{{envID}}/populations/{{popID}}"




