#!/usr/bin/env dothttp

@name("reports/get_activity")
POST "https://api.dropboxapi.com/2/team/reports/get_activity"
"Content-Type": "application/json"



@name("reports/get_devices")
POST "https://api.dropboxapi.com/2/team/reports/get_devices"
"Content-Type": "application/json"



@name("reports/get_membership")
POST "https://api.dropboxapi.com/2/team/reports/get_membership"
"Content-Type": "application/json"



@name("reports/get_storage")
POST "https://api.dropboxapi.com/2/team/reports/get_storage"
"Content-Type": "application/json"




