#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get a review comment for a pull request")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/pulls/comments/{{comment_id}}/"


@name("Update a review comment for a pull request")
PATCH "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/pulls/comments/{{comment_id}}/"
"Content-Type": "application/json"
json({
    "body": "I like this too!"
})


@name("Delete a review comment for a pull request")
DELETE "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/pulls/comments/{{comment_id}}/"



