#!/usr/bin/env dothttp

// Render a simple 2D bar chart using ChartJS.
@name("Bar Chart of 2D data")
POST "https://postman-echo.com/post"
"Content-Type": "application/json"
data('{
	"labels": [
		"{{$randomCountryCode}}",
		"{{$randomCountryCode}}",
		"{{$randomCountryCode}}",
		"{{$randomCountryCode}}",
		"{{$randomCountryCode}}"
	],
	"data": [
		{{$randomInt}},
		{{$randomInt}},
		{{$randomInt}},
		{{$randomInt}},
		{{$randomInt}}
	]
}')



