#!/usr/bin/env dothttp

@name("Criar")
POST "https://scp3.valid.com.br/ScpVeloe/api-veloe/v1/order/add"
"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODcwNDY4NzMsInVzZXJfbmFtZSI6InZlbG9lIiwiYXV0aG9yaXRpZXMiOlsiQ0xJRU5UIl0sImp0aSI6ImJjZDJjYTY5LTcxY2YtNDgzZC1hZWE3LWRkNDEzYTk5NTFiNyIsImNsaWVudF9pZCI6ImNsaWVudC12ZWxvZSIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.8O0Jgz6K6ekl7uQ2805iW-1Mr_aXUcjWiOT7jEw9aF8"
json({
    "totalIdentificadores": 10000,
    "entregador": "Flash",
    "idPedido": 1239,
    "dataPedido": "2020-03-25 21:52:28",
    "kits": [
        {
            "idPedido": 1239,
            "totalKit": 5000,
            "tipoKit": "BAND"
        },
        {
            "idPedido": 1239,
            "totalKit": 5000,
            "tipoKit": "SMART BAND"
        }
    ]
})


@name("Consultar")
GET "https://api-gw.hml.veloe.com.br/fabricacao-identificador/v1/api-fabricacao-identificador/gerarSerial"
"token": "{{token}}"
"Authorization": "{{basic}}"
? "fabricante"= "4"
? "tipoProduto"= "4"
? "qtdIdentificadores"= "1"


@name("Consultar Invoice")
GET "https://scp3.valid.com.br/ScpVeloe/api-veloe/v1/order/GetInvoice/1239"



