#!/usr/bin/env dothttp

@name("Channels")
GET "{{protocol}}://{{host}}/api/v2/device/{{did}}/params/channels"
"Authorization": "Bearer {{token}}"


@name("Channels Update")
PUT "{{protocol}}://{{host}}/api/v2/device/{{did}}/params/channels"
"Authorization": "Bearer {{token}}"
data('{
	"chIndex": {{chIndex}},
	"frequency": {{frequency}},
	"maxDR": {{maxDR}},
	"minDR": {{minDR}}
}')


@name("Channels Delete")
DELETE "{{protocol}}://{{host}}/api/v2/device/{{did}}/params/channels/{{chid}}"
"Authorization": "Bearer {{token}}"



