#!/usr/bin/env dothttp

@name("List all SetupAttempts")
GET "https://{{baseUrl}}/v1/setup_attempts"
"Content-Type": "application/x-www-form-urlencoded"
? "created[gt]"= "<integer>"
? "created[gte]"= "<integer>"
? "created[lt]"= "<integer>"
? "created[lte]"= "<integer>"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "limit"= "<integer>"
? "setup_intent"= "<string>"
? "starting_after"= "<string>"


@name("List all SetupIntents")
GET "https://{{baseUrl}}/v1/setup_intents"
"Content-Type": "application/x-www-form-urlencoded"
? "created[gt]"= "<integer>"
? "created[gte]"= "<integer>"
? "created[lt]"= "<integer>"
? "created[lte]"= "<integer>"
? "customer"= "<string>"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "limit"= "<integer>"
? "payment_method"= "<string>"
? "starting_after"= "<string>"



