#!/usr/bin/env dothttp

# imported from http://localhost:8000/Stripe%20API.postman_collection.json

@name("List all SetupAttempts")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604bc43160>"
"Content-Type": "application/x-www-form-urlencoded"


@name("List all SetupIntents")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604bc43610>"
"Content-Type": "application/x-www-form-urlencoded"



