#!/usr/bin/env dothttp

// Retrieves a list of access scopes associated to the access token.

@name("Retrieves a list of access scopes associated to the access token.")
GET "https://{{store_name}}.myshopify.com/admin/oauth/access_scopes.json"
"Content-Type": "application/json"



