#!/usr/bin/env dothttp

@name("Add webhooks to network")
POST "https://api.meraki.com/api/v0/networks/L_646829496481104290/httpServers"
"Accept": "application/json"
"Content-Type": "application/json"
"X-Cisco-Meraki-API-Key": "{{api_key}}"
json({
    "name": "fredsted",
    "url": "https://webhook.site/885c4fbb-eda9-4d60-a2fb-010d2bde776f",
    "sharedSecret": "denmark"
})


@name("Get webhooks in network")
GET "https://api.meraki.com/api/v0/networks/L_646829496481104290/httpServers"
"Accept": "application/json"
"Content-Type": "application/json"
"X-Cisco-Meraki-API-Key": "{{api_key}}"


@name("Send test webhook")
POST "https://api.meraki.com/api/v0/networks/L_646829496481104290/httpServers/webhookTests"
"Accept": "application/json"
"Content-Type": "application/json"
"X-Cisco-Meraki-API-Key": "{{api_key}}"
json({
    "url": "https://webhook.site/885c4fbb-eda9-4d60-a2fb-010d2bde776f"
})


@name("Get test webhook status")
GET "https://api.meraki.com/api/v0/networks/L_646829496481104290/httpServers/webhookTests/646829496481198964"
"Accept": "application/json"
"Content-Type": "application/json"
"X-Cisco-Meraki-API-Key": "{{api_key}}"



