#!/usr/bin/env dothttp

// Get services by country. <br>
// 
// <strong>US</strong>- United States<br>
// <strong>MX</strong>- Mexico<br>
// <strong>CO</strong>- Colombia<br>

@name("get all services")
GET "https://{{queries_url}}.envia.com/service"
? "country_code"= "{{country_code}}"


// Country Code = MX, US, CO <br>
// Carrier Name =  fedex, almex, dhl

@name("get services by Carrier")
GET "https://{{queries_url}}.envia.com/service/{{carrier_name}}"
? "country_code"= "{{country_code}}"


// Country Code = MX, US, CO </br>
// International = 0 (Domestic) , 1 (International) <br>
// Shipment Type = 1 (guide), 2 (ltl)

@name("get all available services")
GET "https://{{queries_url}}.envia.com/available-service/{{country_code}}/{{international}}/{{shipment_type}}"


@name("get all additional services")
GET "https://{{queries_url}}.envia.com/additional-services"


// Shipment Type = 1 (shipment_guide), 2 (ltl), 3(ftl) <br>
// Active = 0 (Inactive) , 1 (Active)

@name("get single additional services by active status")
GET "https://{{queries_url}}.envia.com/additional-services"
? "shipment_type_id"= "{{shipment_type_id}}"
? "active"= "{{active}}"



