#!/usr/bin/env dothttp

@name("Task")
GET "https://{{host}}/services/data/v47.0/sobjects/Task/"


@name("Task Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Task/{ID}/"


@name("Describe Task")
GET "https://{{host}}/services/data/v47.0/sobjects/Task/describe/"



