#!/usr/bin/env dothttp

// Get companies by sector

@name("https://api.valuer.ml/product/sectors/request")
GET "https://api.valuer.ml/product/sectors/request"
"Authorization": "Bearer YOUR-TOKEN-GOES-HERE"
"Content-Type": "application/json"
? "sector"= "biotechnology"
? "sector"= "Software"
? "limit"= "11"
? "offset"= "0"




