#!/usr/bin/env dothttp

@name("Attachment")
GET "https://{{host}}/services/data/v47.0/sobjects/Attachment/"


@name("Attachment Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Attachment/{ID}/"


@name("Describe Attachment")
GET "https://{{host}}/services/data/v47.0/sobjects/Attachment/describe/"



