#!/usr/bin/env dothttp

@name("Pokemon")
GET "https://pokeapi.co/api/v2/pokemon/"
? "limit"= "151"
? "offset"= "151"


// https://pokeapi.co/api/v2/evolution-chain/{id}/
// 
// Evolution chains are essentially family trees. They start with the lowest stage within a family and detail evolution conditions for each as well as Pokémon they can evolve into up through the hierarchy.

@name("Evolution Chains")
GET "https://pokeapi.co/api/v2/evolution-chain/"


// A generation is a grouping of the Pokémon games that separates them based on the Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and Types that did not exist in the previous generation are released.
// 

@name("Generations")
GET "https://pokeapi.co/api/v2/generation/"


// A Pokédex is a handheld electronic encyclopedia device; one which is capable of recording and retaining information of the various Pokémon in a given region with the exception of the national dex and some smaller dexes related to portions of a region. See Bulbapedia for greater detail.
// https://pokeapi.co/api/v2/pokedex/{id or name}/

@name("Pokedexes ")
GET "https://{{host}}/"


// https://pokeapi.co/api/v2/ability/{id or name}/
// 
// Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon have multiple possible abilities but can have only one ability at a time. Check out Bulbapedia for greater detail.
// 

@name("Abilities")
GET "https://{{host}}/"



