#!/usr/bin/env dothttp

// Rota para carregar todos casos da ONG

@name("Profile")
GET "http://localhost/profile"
"Authorization": "4a9a350a"


@name("Login")
POST "http://localhost/sessions"
"Content-Type": "application/json"
data('{
	"id": "4a9a350a"
}')



