#!/usr/bin/env dothttp

@name("Wave Auto Install Request")
GET "https://{{host}}/services/data/v47.0/sobjects/WaveAutoInstallRequest/"


@name("Wave Auto Install Request Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/WaveAutoInstallRequest/{ID}/"


@name("Describe Wave Auto Install Request")
GET "https://{{host}}/services/data/v47.0/sobjects/WaveAutoInstallRequest/describe/"



