#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Worklog")
GET "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:id"
? "expand"= ""


@name("Update Worklog")
PUT "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:id"
"Content-Type": "application/json"
? "notifyUsers"= "true"
? "adjustEstimate"= "auto"
? "newEstimate"= "<string>"
? "expand"= ""
? "overrideEditableFlag"= "false"
data('{
    "comment": {},
    "visibility": {
        "type": "<string>",
        "value": "<string>"
    },
    "started": "<dateTime>",
    "timeSpent": "<string>",
    "timeSpentSeconds": "<long>",
    "properties": [
        {
            "key": "<string>",
            "value": {}
        },
        {
            "key": "<string>",
            "value": {}
        }
    ]
}')


@name("Delete Worklog")
DELETE "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:id"
? "notifyUsers"= "true"
? "adjustEstimate"= "auto"
? "newEstimate"= "<string>"
? "increaseBy"= "<string>"
? "overrideEditableFlag"= "false"



