#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Worklog")
GET "https://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:id"


@name("Update Worklog")
PUT "https://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:id"
"Content-Type": "application/json"
? "notifyUsers"= "true"
? "adjustEstimate"= "auto"
? "newEstimate"= "<string>"
? "overrideEditableFlag"= "false"
data('{
    "comment": {},
    "visibility": {
        "type": "<string>",
        "value": "<string>"
    },
    "started": "<dateTime>",
    "timeSpent": "<string>",
    "timeSpentSeconds": "<long>",
    "properties": [
        {
            "key": "<string>",
            "value": {}
        },
        {
            "key": "<string>",
            "value": {}
        }
    ]
}')


@name("Delete Worklog")
DELETE "https://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:id"
? "notifyUsers"= "true"
? "adjustEstimate"= "auto"
? "newEstimate"= "<string>"
? "increaseBy"= "<string>"
? "overrideEditableFlag"= "false"



