#!/usr/bin/env dothttp

@name("Get entities from JobApplicationQuestionResponse")
GET "https://{{baseUrl}}/JobApplicationQuestionResponse"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
? "$top"= "20"
? "$skip"= "53414946"
? "$search"= "esse elit eiusmo"
? "$filter"= "esse elit eiusmo"
? "$count"= "true"
? "$orderby"= "applicationId,highLow desc"
? "$select"= "question,expectedAnswer"
? "$expand"= "*,jobApplication"


@name("Add new entity to JobApplicationQuestionResponse")
POST "https://{{baseUrl}}/JobApplicationQuestionResponse"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
"Content-Type": "application/json"
data('{
    "answer": "laboris dolor do",
    "applicationId": "ea",
    "expectedAnswer": "ut cillum eiusmod",
    "expectedAnswerValue": -46090532.41353753,
    "highLow": "dolor Duis anim",
    "maxLength": 6961994.402113184,
    "order": "id est ad",
    "question": "mollit volup",
    "questionResponse": "officia",
    "type": "consequat do in",
    "jobApplication": {
        "address": "sunt sit",
        "address2": "velit qui fugiat laboris dolore",
        "agencyInfo": "ea aliqua",
        "anonymizedDate": "/Date(1492098664000)/",
        "anonymizedFlag": "ex nulla dolore tempor",
        "appLocale": "ad ipsum lab",
        "appStatusSetItemId": "dolore",
        "applicationId": "irure ut",
        "applicationTemplateId": "ea dolor",
        "averageRating": "sint consequat dolor",
        "baseSalary": "exercitation Ut",
        "candConversionProcessed": "ad sint",
        "candJust": "est officia quis qui",
        "candTypeWhenHired": "labore in nostrud aute dolore",
        "candidateId": "ipsum nulla laboris consec",
        "cellPhone": "esse amet in ad",
        "city": "reprehenderit velit ex id",
        "confnumber": "sint ipsum pariatur",
        "contactEmail": "nostrud voluptate",
        "conviction_details": "incididunt",
        "country": "sed nulla exercitation ut",
        "countryCode": "fugiat in qui sit",
        "criminalconvictionlabel": "Lorem exercitation",
        "crimincalconvictioninstructions": "veniam officia",
        "currentLocation": "irure culpa ex",
        "currentTitle": "aliqui",
        "cust_refCheckFirstName": "Excepteur esse",
        "cust_refCheckLastName": "sed officia eiusmod",
        "cust_refCheckOrg1": "do",
        "cust_refCheckPhone1": "id tempor ut",
        "cust_refCheckTitle1": "aliquip deserunt ex",
        "dataSource": "ut pariatur aliqua proident velit",
        "dateAvail": "/Date(1492098664000)/",
        "dateOfBirth": "/Date(1492098664000)/",
        "duplicateProfile": "labore volu",
        "exportedOn": "/Date(1492098664000)/",
        "extTitle": "mollit minim do",
        "firstName": "mollit",
        "formerEmployee": true,
        "gender": "id in adipisicing fugiat laborum",
        "haveyoubeenconvicted": "officia",
        "hireDate": "/Date(1492098664000)/",
        "hiredOn": "/Date(1492098664000)/",
        "homePhone": "dolor consectetur id minim cupidatat",
        "inductionAdd": "Lorem",
        "inductionDate": "/Date(1492098664000)/",
        "initials": "sunt laboris voluptate",
        "instrAppReturn": "laboris culpa pariatur velit",
        "instrCandApproval": "reprehenderit culpa amet minim",
        "instrCandAssess": "officia laborum et",
        "instrCandFields": "fugiat",
        "instrCandScreen": "dolor consectetur nostrud",
        "instrWotc": "dolor aute",
        "instr_AdditionalDocuments": "fugiat aliqua ea",
        "instr_AppAdditionalInfo": "aliqua deserunt id",
        "instr_AppAdvice": "pariatur amet mollit deserunt nulla",
        "instr_CandAppDetails": "Duis sit incididunt",
        "instr_CandPersInfo": "consequat eu Excepteur",
        "instr_EEOinstructions": "sint dolore deserunt commodo",
        "instr_EEOlable": "veniam quis dolore tempor",
        "instrubkgrndChkAttachment": "fugiat sint sunt cupidatat",
        "jobAppGuid": "dolore Excepteur commodo",
        "jobCode": "quis do in nulla et",
        "jobRateOfPay": "dolor anim irure",
        "jobReqId": "quis fugiat nisi exercitation",
        "jobStartDate": "/Date(1492098664000)/",
        "jobofferdate": "/Date(1492098664000)/",
        "knownAs": "mollit dolor voluptate",
        "lastModifiedBy": "consequat sed culpa sit exercitation",
        "lastModifiedByProxy": "ad in",
        "lastModifiedDateTime": "/Date(1492098664000)/",
        "lastName": "ut non in id",
        "medDate": "/Date(1492098664000)/",
        "medLoc": "eu mollit elit nulla",
        "medTime": "tempor dolor ad",
        "middleName": "eiusmod elit commodo id aliquip",
        "nonApplicantStatus": "la",
        "owner": "pariatur ut",
        "ownershpDate": "/Date(1492098664000)/",
        "phoneScreenDate": "/Date(1492098664000)/",
        "phoneScreenDetails": "in nulla dolor dolor",
        "pleaseselect": "Lorem nostrud",
        "posTitle": "laboris ipsum et quis",
        "profileUpdated": "qui commodo aute deserunt",
        "psychTestDte": "/Date(1492098664000)/",
        "psychTestTme": "laboris qui",
        "rating": "sit dolor",
        "reasonableaccomodation": "fugiat qui",
        "reference": "culpa occa",
        "referenceComments": "Lorem ullamco reprehenderit velit",
        "referredBy": "nisi veniam",
        "resumeUploadDate": "/Date(1492098664000)/",
        "screendate": "/Date(1492098664000)/",
        "snapShotDate": "/Date(1492098664000)/",
        "source": "eu in qui",
        "sourceLabel": "in et aliquip",
        "ssn": "exercitation consectetur ex proident",
        "startDate": "/Date(1492098664000)/",
        "stateOther": "in adipisicing cupidatat Lorem voluptate",
        "status": "mollit cillum ex",
        "statusComments": "nulla dolor occaecat esse quis",
        "timeToHire": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "title": "irure voluptate velit",
        "usersSysId": "culpa sit",
        "visaNum": "laboris",
        "voluntaryselfID": "mollit amet",
        "whyask": "reprehenderit enim nulla",
        "wotcFormsURL": "est consectetur ut eu",
        "wotcId": "ut",
        "wotcScreeningURL": "a",
        "wotcStatus": "non cupi",
        "yesanswer": "exercitation laborum tempor incididunt",
        "zip": "Lorem",
        "jobAppStatus": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "jobApplicationAssessmentOrder": {
            "results": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        "jobApplicationAssessmentOrder_1": {
            "results": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        "jobApplicationComments": {
            "results": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        "jobApplicationOnboardingData": {
            "results": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        "jobApplicationQuestionResponse": {
            "results": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        "jobApplicationStatusAuditTrail": {
            "results": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        }
    }
}')



