#!/usr/bin/env dothttp

// Returns restrictions on a piece of content by operation. This method is
// similar to [Get restrictions](#api-content-id-restriction-get) except that
// the operations are properties of the return object, rather than items in
// a results array.
// 
// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
// Permission to view the content.

@name("Get restrictions by operation")
GET "https://{{baseUrl}}/api/content/:id/restriction/byOperation"
? "expand"= "<string>"
? "expand"= "<string>"



