#!/usr/bin/env dothttp

@name("Uri Event Stream")
GET "https://{{host}}/services/data/v47.0/sobjects/UriEventStream/"


@name("Uri Event Stream Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/UriEventStream/{ID}/"


@name("Describe Uri Event Stream")
GET "https://{{host}}/services/data/v47.0/sobjects/UriEventStream/describe/"



