#!/usr/bin/env dothttp

@name("GET plugin")
GET "https://{{sb_client}}.salesboard.biz/v1/plugin"
"XREQUESTEDWITH": "XHRHttpRequest"
"Cookie": "PHPSESSID-uuvo7vm4rounhcsnbhsmfsn632"


@name("CREATE plugin")
POST "https://{{sb_client}}.salesboard.biz/v1/plugin"
"XREQUESTEDWITH": "XHRHttpRequest"
"Cookie": "PHPSESSID-uuvo7vm4rounhcsnbhsmfsn632"



@name("UPDATE plugin")
PUT "https://{{sb_client}}.salesboard.biz/v1/plugin/2"
"XREQUESTEDWITH": "XHRHttpRequest"
"Cookie": "PHPSESSID-uuvo7vm4rounhcsnbhsmfsn632"



@name("GET  Plugins")
GET "https://{{sb_client}}.salesboard.biz/v1/plugin"
"XREQUESTEDWITH": "XHRHttpRequest"
"Cookie": "PHPSESSID-uuvo7vm4rounhcsnbhsmfsn632"


@name("DELETE plugin")
DELETE "https://{{sb_client}}.salesboard.biz/v1/plugin/2"
"XREQUESTEDWITH": "XHRHttpRequest"
"Cookie": "PHPSESSID-uuvo7vm4rounhcsnbhsmfsn632"



@name("INIT Plugin")
POST "https://{{sb_client}}.salesboard.biz/v1/plugin/1/init"
"XREQUESTEDWITH": "XHRHttpRequest"
"Cookie": "PHPSESSID=aqaj5p8gin48e9j3ntolh8qe14"



@name("RESET PASSWORD Plugin")
POST "https://{{sb_client}}.salesboard.biz/v1/plugin/1/password-reset"
"XREQUESTEDWITH": "XHRHttpRequest"
"Cookie": "PHPSESSID=aqaj5p8gin48e9j3ntolh8qe14"




