#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Contexts For A Field")
GET "None://{{baseUrl}}/rest/api/3/field/:fieldId/contexts"
? "startAt"= "0"
? "maxResults"= "20"


@name("Get Screens For A Field")
GET "None://{{baseUrl}}/rest/api/3/field/:fieldId/screens"
? "startAt"= "0"
? "maxResults"= "100"



