#!/usr/bin/env dothttp

// Let's say you have an array of items that you need to POST to the same URL one by one. You can loop on the same request and use a variable to keep track of that request.
// 
// If this variable is an array, then you can parse it as JSON in the `Pre-request script`, pop the array and set the request parameters based on that value. If the array contains any items, you loop back on the same request.

@name("Send same request multiple times")
POST "https://postman-echo.com/post"
"Content-Type": "application/json"
data('{
	"count": {{loopCount}}
}')



