#!/usr/bin/env dothttp

// You collected secret passphrases earlier. Paste them inside the quotes. You might want to paste them in order.

@name("Collect your prize")
POST "https://{{baseUrl}}/api/quiz/submit"
json({
    "answers": [
        "",
        "",
        ""
    ]
})



