#!/usr/bin/env dothttp

// Send a test webhook for a network//  #### Body Parameters // **Parameter**|**Type**|**Description** //  :-------------: |:-------------: |:-------------: // url| string| The URL where the test webhook will be sent// sharedSecret| string| The shared secret the test webhook will send. Optional. Defaults to an empty string.
@name("Send A Test Webhook For A Network")
POST "https://{{baseUrl}}/networks/:networkId/webhooks/webhookTests"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "url": "<string>",
    "sharedSecret": ""
}')


// Return the status of a webhook test for a network
@name("Return The Status Of A Webhook Test For A Network")
GET "https://{{baseUrl}}/networks/:networkId/webhooks/webhookTests/:webhookTestId"
"X-Cisco-Meraki-API-Key": ""



