#!/usr/bin/env dothttp

// Find a company by domain ou some another scope, like: app_id

@name("Company settings")
GET "https://{{KNOWLEDGE_BASE_URL}}/identity/invitations"
"Content-Type": "application/json"
"Authorization": "{{TOKEN}}"
? "email"= "renato@skore.io"



