#!/usr/bin/env dothttp

# imported from http://localhost:8000/Salesforce_Marketing_Cloud_APIs.postman_collection.json

@name("Validate Address")
POST "https://{{et_subdomain}}.rest.marketingcloudapis.com/address/v1/validateEmail"
json({
    "email": "help@example.com",
    "validators": [
        "SyntaxValidator",
        "MXValidator",
        "ListDetectiveValidator"
    ]
})



