#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List reactions for an issue")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/issues/{{issue_number}}/reactions"
? "content"= "hooray"
? "per_page"= "30"
? "page"= "1"


@name("Create reaction for an issue")
POST "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/issues/{{issue_number}}/reactions"
"Content-Type": "application/json"
json({
    "content": "heart"
})


@name("Delete an issue reaction")
DELETE "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/issues/{{issue_number}}/reactions/{{reaction_id}}/"



