#!/usr/bin/env dothttp

// #### Search stop reasons in ERP
// *(totvsProtheus=SX5/44)*
// 
// The stop reasons search allows you to filter the ERP by:
// - Unitary: by erpKey or erpId (TOTVS Protheus only)
// 
// If no field for unitary query (erpKey or erpId) is informed in the request, the search returns all valid records in table 44 of SX5.
// 
// The response will inform:
// - The number of returned objects in the “count” field
// 
// This service does not have pagination or incremental treatment.
// 
// This service does not have user field (UDF) treatment.

@name("Stop Reasons")
GET "https://{{endpoint}}/stopReasons"
basicauth("{{user}}", "{{pass}}")
? "erpKey"= "FT"
? "erpId"= "2408"


// #### Search waste reasons in ERP
// *(totvsProtheus=SX5/43)*
// 
// The waste reasons search allows you to filter the ERP by:
// - Unitary: by erpKey or erpId (TOTVS Protheus only)
// 
// If no field for unitary query (erpKey or erpId) is informed in the request, the search returns all valid records in table 43 of SX5.
// 
// The response will inform:
// - The number of returned objects in the “count” field
// 
// This service does not have pagination or incremental treatment.
// 
// This service does not have user field (UDF) treatment.

@name("Waste Reasons")
GET "https://{{endpoint}}/wasteReasons"
basicauth("{{user}}", "{{pass}}")
? "erpKey"= "FH"
? "erpId"= "2399"



