#!/usr/bin/env dothttp

@name("Get  Table")
GET "https://{{sb_client}}.salesboard.biz/v1/assets/published/tables/{{sb_table_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"


@name("Get  Table Resource")
GET "https://{{sb_client}}.salesboard.biz/v1/assets/published/tables/{{sb_table_id}}/{{sb_table_id}}.sqlite"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"



