#!/usr/bin/env dothttp

// This is a POST request allowing a user to create an account on the Teamwork app and returns a jwt token for the user to make subrequest calls

@name("Signup")
POST "https://localhost/api/v1/auth/signup"
"Content-Type": "application/json"
json({
    "firstname": "Micheal",
    "lastname": "Douglas",
    "email": "micheal@test.com",
    "password": "Michealtest1!",
    "confirmPassword": "Michealtest1!",
    "gender": "Male",
    "jobRole": "Backend engineer",
    "department": "Egineering",
    "address": "Kampala"
})


// This is a sigin/login POST request allowing a user to successfully login into his/her account and returns a jwt token for the user to make subrequest calls

@name("Signin")
POST "https://localhost/api/v1/auth/signin"
"Content-Type": "application/json"
json({
    "email": "jessica@test.com",
    "password": "Jessicatest1!"
})


// This is a POST request which enables a user to create and post an article that can be seen by other colleagues and returns a status of 200 with the new article posted and an id

@name("Post Article")
POST "https://localhost/api/v1/articles"
"Authorization": "{{bearer}}"
"Content-Type": "application/json"
json({
    "title": "Front end",
    "article": "Do you want to be a frontend designer join the HUB"
})


// This is a GET request that allows users to view articles posted by other users and returns a status of 200 with the articles posted

@name("View Articles")
GET "https://localhost/api/v1/feeds"
"Authorization": "{{bearer}}"
"Content-Type": "application/json"



// This route is a GET request that fetches and shows a specific article with an ID provided and returns a status of 200

@name("View Specific Article")
GET "https://localhost/api/v1/articles/2"
"Authorization": "{{bearer}}"
"Content-Type": "application/json"



// A PATCH request that edits an already posted article with a given ID and returns a status of 200

@name("Edit Article")
PATCH "https://localhost/api/v1/articles/2"
"Authorization": "{{bearer}}"
"Content-Type": "application/json"
json({
    "title": "Freelancing",
    "article": "Do you want to be a freelance developer and earn alot of money, say no more with upwork.com up on the market"
})


// A POST request that enables a user to post a comment on a specific article with an ID provided and returns a status of 201

@name("Comment on Article")
POST "https://localhost/api/v2/articles/457060e8-7273-48bf-8f56-ed423eb7432c/comments/443def19-7eb4-40f1-bac2-a4d1ebfb9369"
"Authorization": "{{bearer}}"
"Content-Type": "application/json"
json({
    "flag": true
})


// A DELETE request enabling a user to delete a posted article with a specific ID and returns a status of 204 

@name("Delete Article")
DELETE "https://localhost/api/v1/articles/4"
"Authorization": "{{bearer}}"
"Content-Type": "application/json"



// This is a post request which a posts a flag on a specific article with an given id and it is boolean i.e either true or false

@name("Flag Article")
POST "https://localhost/api/v1/articles/1"
"Content-Type": "application/json"
"Authorization": "{{bearer}}"
json({
    "flag": true
})


// This is an admin DELETE route and it deletes a specific article with a given ID that the admin has viewed to be flagged inappropiate by other users

@name("Delete flagged Article")
DELETE "https://localhost/api/v1/flagged/articles/1"
"Authorization": "{{bearer}}"



