#!/usr/bin/env dothttp

@name("Abstracts Get")
GET "https://{{baseUrl}}/events/v1/abstracts/:id"
"Authorization": "<string>"


@name("Abstracts Put")
PUT "https://{{baseUrl}}/events/v1/abstracts/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "event": [
        "<string>"
    ],
    "owner": [
        "<string>"
    ],
    "status": [
        "<string>"
    ],
    "description": [
        "<string>"
    ],
    "administrativeNotes": [
        "<string>"
    ],
    "scheduled": [
        "<boolean>"
    ],
    "reviewedBy": [
        "<string>"
    ],
    "dateReviewed": [
        "<dateTime>"
    ],
    "tracks": [
        "[\"<string>\",\"<string>\"]"
    ],
    "presenterName": [
        "<string>"
    ],
    "presenterBiography": [
        "<string>"
    ],
    "presenterPhoneNumber": [
        "<string>"
    ],
    "presenterEmailAddress": [
        "<string>"
    ],
    "courses": [
        "[{\"course\":\"<string>\"},{\"course\":\"<string>\"}]"
    ],
    "speakers": [
        "[{\"speaker\":\"<string>\"},{\"speaker\":\"<string>\"}]"
    ],
    "customFieldValues": [
        "[{\"customField\":\"<string>\",\"orderLineItemID\":\"<string>\",\"stringValue\":\"<string>\",\"integerValue\":\"<long>\",\"decimalValue\":\"<double>\",\"listValues\":[\"<string>\",\"<string>\"],\"booleanValue\":\"<boolean>\",\"dateTimeValue\":\"<dateTime>\",\"referenceValue\":\"<string>\",\"listValuesForDisplay\":\"<string>\",\"listValuesForSearch\":\"<string>\"},{\"customField\":\"<string>\",\"orderLineItemID\":\"<string>\",\"stringValue\":\"<string>\",\"integerValue\":\"<long>\",\"decimalValue\":\"<double>\",\"listValues\":[\"<string>\",\"<string>\"],\"booleanValue\":\"<boolean>\",\"dateTimeValue\":\"<dateTime>\",\"referenceValue\":\"<string>\",\"listValuesForDisplay\":\"<string>\",\"listValuesForSearch\":\"<string>\"}]"
    ],
    "localID": [
        "<long>"
    ],
    "wasLocalIDGenerated": [
        "<boolean>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isConfiguration": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})



