#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Default Workflow")
GET "https://{{baseUrl}}/rest/api/3/workflowscheme/:id/default"
? "returnDraftIfExists"= "false"


@name("Update Default Workflow")
PUT "https://{{baseUrl}}/rest/api/3/workflowscheme/:id/default"
"Content-Type": "application/json"
data('{
    "workflow": "<string>",
    "updateDraftIfNeeded": "<boolean>"
}')


@name("Delete Default Workflow")
DELETE "https://{{baseUrl}}/rest/api/3/workflowscheme/:id/default"
? "updateDraftIfNeeded"= "<boolean>"



