#!/usr/bin/env dothttp

@name("Create payment for reversed refund")
POST "https://{{UNLIMINT_API_URL}}/api/payments"
"Content-Type": "application/json"
json({
    "request": {
        "id": "{{$guid}}",
        "time": "{{request_time}}"
    },
    "merchant_order": {
        "id": "{{$randomUUID}}",
        "description": "Postman Collection Order ('{{request_name}}')"
    },
    "payment_method": "BANKCARD",
    "payment_data": {
        "amount": "12.34",
        "currency": "{{TERMINAL_CURRENCY}}"
    },
    "customer": {
        "email": "{{CUSTOMER_EMAIL}}"
    },
    "card_account": {
        "card": {
            "pan": "{{CARD_NON3DS_CONFIRMED}}",
            "holder": "{{$randomFullName}}",
            "expiration": "{{expiration}}",
            "security_code": "100"
        }
    }
})


@name("Create refund to reverse")
POST "https://{{UNLIMINT_API_URL}}/api/refunds"
"Content-Type": "application/json"
json({
    "request": {
        "id": "{{$guid}}",
        "time": "{{request_time}}"
    },
    "merchant_order": {
        "id": "{{$randomUUID}}",
        "description": "Postman Collection Order ('{{request_name}}')"
    },
    "payment_data": {
        "id": "{{payment_id_for_reversed_refund}}"
    }
})


@name("Reverse refund")
PATCH "https://{{UNLIMINT_API_URL}}/api/refunds/{{refund_id_to_reverse}}"
"Content-Type": "application/json"
json({
    "request": {
        "id": "{{$guid}}",
        "time": "{{request_time}}"
    },
    "refund_data": {
        "status_to": "REVERSE"
    }
})



