#!/usr/bin/env dothttp

@name("Lead Feed")
GET "https://{{host}}/services/data/v47.0/sobjects/LeadFeed/"


@name("Lead Feed Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/LeadFeed/{ID}/"


@name("Describe Lead Feed")
GET "https://{{host}}/services/data/v47.0/sobjects/LeadFeed/describe/"



