#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Check team permissions for a project (Legacy)")
GET "https://{{baseUrl}}/teams/{{team_id}}/projects/{{project_id}}/"


@name("Add or update team project permissions (Legacy)")
PUT "https://{{baseUrl}}/teams/{{team_id}}/projects/{{project_id}}/"
"Content-Type": "application/json"
json({
    "permission": "admin"
})


@name("Remove a project from a team (Legacy)")
DELETE "https://{{baseUrl}}/teams/{{team_id}}/projects/{{project_id}}/"



