#!/usr/bin/env dothttp

// Create a new project for your organization. New projects are identified by a unique identifier `requestHash` and are associated to a developer key you can use to make API requests for this project.
// 
// The field `name` is used to assign a human-readable name to the project.
// 
// The field `effort` controls whether high effort will be applied when processing media. High effort processing is robust to strong occlusion, small size and diffucult imaging conditions. Supported values are `standard` or `high`.
// 
// The field `mediaType` can be used to specify whether the new project will be used to process images or videos and the supported values are `media` or `video`.
// 
// 
// _This endpoint requires a special permission that needs to be granted to your developer key._
// 
// #### Response
// 
// The field `projectHash` uniquely identifies the project and field `developerKey` represents the developer key used to make API calls for this new project.

@name("Project")
POST "https://{{socket}}/projects"
"Content-Type": "application/x-www-form-urlencoded"
"X-DEVELOPER-KEY": ""
data({
    "name": [
        "basketball"
    ],
    "effort": [
        "high"
    ],
    "mediaType": [
        "video"
    ]
})


// List all existing projects associated with your organization.
// 
// #### Response
// 
// The field `projects` contains a list of every project associated with your organization where each project is uniquely identifier by `projectHash`. The JSON Object containing the project details also includes the `developerKey` which is used to make API calls for the specific project. The fields `mediaType` and `effort` describe whether the project is configured for processing images or videos and the processing effort level.

@name("Projects")
GET "https://{{socket}}/projects"
"Content-Type": "application/x-www-form-urlencoded"
"X-DEVELOPER-KEY": ""




