#!/usr/bin/env dothttp

// Adds an email address as unverified; sends verification email

@name("Add Unverified Email")
POST "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/users/emails"
"Content-Type": "application/json"
data('{
  "name": "First Last",
  "address": "{{email_address}}"
}')


// Removes a verified or unverified email address.

@name("Delete User Email")
DELETE "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/users/emails"
? "address"= "{{url_encoded_email}}"



// Adds an email address as unverified; sends verification email

@name("Get User Emails")
GET "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/users/emails"


// Verifies an email address.

@name("Verify Email Address")
GET "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/users/emails/verifications"
? "address"= "{{email_address}}"
? "verificationCode"= "{{verification_code}}"


// Resends the email used for verifying an email address

@name("Resend Email Verification")
POST "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/users/emails/verifications"
? "address"= "{{url_encoded_email}}"



