#!/usr/bin/env dothttp

// Lists all available metrics for the Pure1 account
@name("Get All Metrics")
GET "https://api.pure1.purestorage.com/api/{{api_version}}/metrics"
? "sort"= "availabilities[any].resolution"


// Lists all available metrics for the Pure1 account
@name("Get Array Metrics")
GET "https://api.pure1.purestorage.com/api/{{api_version}}/metrics"
? "filter"= "resource_types='arrays'"


// Lists all non-mirrored array metrics available for the Pure1 account
@name("Get Array, Non-Mirrored Metrics")
GET "https://api.pure1.purestorage.com/api/{{api_version}}/metrics"
? "filter"= "resource_types[all]='arrays' and not(contains(name, 'mirrored'))"



