#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get an environment secret")
GET "https://{{baseUrl}}/repositories/{{repository_id}}/environments/{{environment_name}}/secrets/{{secret_name}}/"


@name("Create or update an environment secret")
PUT "https://{{baseUrl}}/repositories/{{repository_id}}/environments/{{environment_name}}/secrets/{{secret_name}}/"
"Content-Type": "application/json"
json({
    "encrypted_value": "c2VjcmV0",
    "key_id": "012345678912345678"
})


@name("Delete an environment secret")
DELETE "https://{{baseUrl}}/repositories/{{repository_id}}/environments/{{environment_name}}/secrets/{{secret_name}}/"



