#!/usr/bin/env dothttp

// Consulta las facturas que están pagadas o pendientes por pagar. Se puede consultar por cliente, por suscripción o por rango de fechas.

@name("QUERY")
GET "https://{{RECURRING_API}}/recurringBill"
"Host": "sandbox.api.payulatam.com"
"Content-Type": "application/json; charset=utf-8"
"Accept": "application/json"
"Accept-Language": "{{LANGUAGE}}"
"Content-Length": "length"
"Authorization": "Basic {{RECURRING_AUTHORIZATION}}"
? "customerId"= "CUSTOMER_ID"
? "subscriptionId"= "SUBSCRIPTION_ID"
? "dateBegin"= "2019-01-01"
? "dateFinal"= "2019-12-31"



