#!/usr/bin/env dothttp

// It fetches all Campaigns for the user. 
// Possible "status": ['draft', 'running', 'paused', 'stopped']

@name("Get Appointments")
GET "https://{{sb_client}}.salesboard.biz/v1/appointments"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "include"= "details, contactTypes, meetingNotes"


// It fetches all Campaigns for the user. 
// Possible "status": ['draft', 'running', 'paused', 'stopped']

@name("Get Appointments for Prospects")
GET "https://{{sb_client}}.salesboard.biz/v1/appointments"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "include"= "details, contactTypes, meetingNotes"
? 'filters'= '{ "prospects":["XggQkXQBwekqT5TNaKR1"]}'


// It fetches all Campaigns for the user. 
// Possible "status": ['draft', 'running', 'paused', 'stopped']

@name("Get Appointment by ID")
GET "https://{{sb_client}}.salesboard.biz/v1/appointments/{{sb_appointment_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"


@name("Create Appointment")
POST "https://{{sb_client}}.salesboard.biz/v1/appointments"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
json({
    "name": "Jan Jansen",
    "ID_Prospect": "m0AhOXMB0GgsEc2oMeYr",
    "ID_Story": 1,
    "ID_Campaign": 2,
    "startDate": 1561033067000,
    "endDate": 1589382201000,
    "link": "",
    "meetingNotes": "Some notes for the meeting",
    "contactTypes": [
        "video"
    ]
})


@name("Update Appointment")
PUT "https://{{sb_client}}.salesboard.biz/v1/appointments/{{sb_appointment_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
json({
    "name": "Tim Jansen",
    "meetingNotes": "Contact person changed. Some notes for the meeting",
    "startDate": 1561033067001,
    "endDate": 1589382201001,
    "ID_Story": 10,
    "ID_Campaign": 20
})


@name("Delete Appointment")
DELETE "https://{{sb_client}}.salesboard.biz/v1/appointments/{{sb_appointment_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"




