#!/usr/bin/env dothttp

@name("{{baseUrl}}/JobFlow/DeleteJob")
POST "https://{{baseUrl}}/JobFlow/DeleteJob"
"Content-Type": "application/json"
json({
    "jobid": "<string>"
})


@name("{{baseUrl}}/JobFlow/Event")
POST "https://{{baseUrl}}/JobFlow/Event"
"Content-Type": "application/json"
json({
    "jobid": "<string>",
    "sync": "<boolean>",
    "args": "<object>",
    "event": "<string>"
})


@name("{{baseUrl}}/JobFlow/GetJob")
POST "https://{{baseUrl}}/JobFlow/GetJob"
"Content-Type": "application/json"
json({
    "jobid": "<string>"
})


@name("{{baseUrl}}/JobFlow/GetJobs")
POST "https://{{baseUrl}}/JobFlow/GetJobs"
"Content-Type": "application/json"
json({
    "type": "<string>"
})


@name("{{baseUrl}}/JobFlow/GetMyJobs")
POST "https://{{baseUrl}}/JobFlow/GetMyJobs"
"Content-Type": "application/json"
json({
    "type": "<string>"
})


@name("{{baseUrl}}/JobFlow/StartJob")
POST "https://{{baseUrl}}/JobFlow/StartJob"
"Content-Type": "application/json"
json({
    "args": "<string>",
    "script": "<string>"
})



