#!/usr/bin/env dothttp

@name("Asset Relationship")
GET "https://{{host}}/services/data/v47.0/sobjects/AssetRelationship/"


@name("Asset Relationship Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/AssetRelationship/{ID}/"


@name("Describe Asset Relationship")
GET "https://{{host}}/services/data/v47.0/sobjects/AssetRelationship/describe/"



