#!/usr/bin/env dothttp

@name("/signature_uis")
POST "https://{{base-api-url}}/signature_uis"
"Authorization": "Bearer {{your-api-key}}"
"Content-Type": "application/json"
json({
    "name": "My first template for Signature-UI",
    "description": "Here is the Signature-UI template for Yousign Developers.",
    "defaultZoom": 100,
    "logo": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQU [...] IwU3i6foIAAAAAElFTkSuQmCC",
    "languages": [
        "fr",
        "en",
        "es",
        "de",
        "it",
        "pt",
        "nl"
    ],
    "defaultLanguage": "en",
    "signImageTypesAvailable": [
        "name",
        "draw"
    ],
    "enableHeaderBar": true,
    "enableHeaderBarSignAs": true,
    "enableSidebar": true,
    "enableMemberList": true,
    "enableDocumentList": true,
    "enableDocumentDownload": true,
    "enableActivities": true,
    "authenticationPopup": true,
    "enableRefuseComment": true,
    "labels": [
        {
            "name": "NAME OF THE LABEL",
            "languages": {
                "en": "Label en",
                "fr": "Label fr"
            }
        }
    ],
    "fonts": [
        "Roboto",
        "Lato"
    ],
    "style": "Just a CSS string for customize all of our iFrame.",
    "redirectCancel": {
        "url": "https://YOUR_FORWARDING_URL.com",
        "target": "_top or _blank or _self or _parent",
        "auto": false
    },
    "redirectError": {
        "url": "https://YOUR_FORWARDING_URL.com",
        "target": "_top or _blank or _self or _parent",
        "auto": false
    },
    "redirectSuccess": {
        "url": "https://YOUR_FORWARDING_URL.com",
        "target": "_top or _blank or _self or _parent",
        "auto": false
    }
})



