#!/usr/bin/env dothttp

// Add income category to sale
// 
// ### Note
// This endpoint is only being used internally and not subjected to user input, the input that is provided herein is already validated in other point of the sale creation. 
// 
// #### Path Variables
// ```
// sale_id             4EC041C2-E733-4C56-B622-490AFF39942E    
// ```
// 
// #### Reponse status codes
// | Code| Message|Reason | 
// | -- | -- | -- | 
// | 200| OK| return income category| 
// | 400| Bad request|Malformed request syntax, read the docs | 
// | 422| Invalid info for process|Field value error, read the docs | 
// | 422| Unprocessable Entity Error|Business rule error, read the docs | 
// | 404| Not found| Bad endpoint invocation | 

@name("Add income category")
POST "https://{{base_url}}/sales/C5F831DA-47A9-4860-B339-C7E7814E404/sale_category"
json({
    "incomeCategoryId": "98A1283D-9F0D-4F94-9805-25830237F12F",
    "name": "categoria test",
    "companyNumber": 20192,
    "color": 2,
    "colorLogo": null
})


// Update income category info
// 
// ### Note
// This endpoint is only being used internally and not subjected to user input, the input that is provided herein is already validated in other point of the sale creation. 
// 
// #### Path Variables
// ```
// sale_id             4EC041C2-E733-4C56-B622-490AFF39942E    
// ```
// 
// #### Reponse status codes
// | Code| Message|Reason | 
// | -- | -- | -- | 
// | 200| OK| return income category| 
// | 400| Bad request|Malformed request syntax, read the docs | 
// | 422| Invalid info for process|Field value error, read the docs | 
// | 422| Unprocessable Entity Error|Business rule error, read the docs | 
// | 404| Not found| Bad endpoint invocation | 

@name("Update sale category")
PATCH "https://{{base_url}}/sales/C5F831DA-47A9-4860-B339-C7E7814E404/sale_category"
json({
    "incomeCategoryId": "98A1283D-9F0D-4F94-9805-25830237F12F",
    "name": "categoria test",
    "companyNumber": 20192,
    "color": 2,
    "colorLogo": null
})



