#!/usr/bin/env dothttp

@name("My Domain Discoverable Login")
GET "https://{{host}}/services/data/v47.0/sobjects/MyDomainDiscoverableLogin/"


@name("My Domain Discoverable Login Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/MyDomainDiscoverableLogin/{ID}/"


@name("Describe My Domain Discoverable Login")
GET "https://{{host}}/services/data/v47.0/sobjects/MyDomainDiscoverableLogin/describe/"



