#!/usr/bin/env dothttp

@name("List Categories")
GET "https://{{api_url}}/categories"
"Accept": "application/vnd.api+json"
? "page[number]"= "1"
? "page[size]"= "50"
? "filter[name]"= "some_name"
? "filter[description]"= "some_description"
? "sort"= "name"
? "fields[categories]"= "name,description"


@name("Create Category")
POST "https://{{api_url}}/categories"
"Accept": "application/vnd.api+json"
"Content-Type": "application/vnd.api+json"
data('{
    "data": 
        {
            "type": "categories",
            "attributes": {
                "name": "category_name",
                "description": "category_description"
            }
        }
 
}')


@name("Show Category")
GET "https://{{api_url}}/categories/1"
"Accept": "application/vnd.api+json"
? "fields[categories]"= "name,description"


@name("Update Category")
PATCH "https://{{api_url}}/categories/1"
"Accept": "application/vnd.api+json"
"Content-Type": "application/vnd.api+json"
data('{
    "data": {
        "type": "categories",
        "id": "1",
        "attributes": {
            "name": "new_category_name",
            "description": "new_category_description"
        }
    }
}')


@name("Delete Category")
DELETE "https://{{api_url}}/categories/1"
"Accept": "application/vnd.api+json"



