#!/usr/bin/env dothttp

// Returns STP settings

@name("Returns STP Settings")
GET "https://{{baseUrl}}/networks/:networkId/switch/stp"
"X-Cisco-Meraki-API-Key": ""


// Updates STP settings
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// rstpEnabled| boolean| The spanning tree protocol status in network
// stpBridgePriority| array| STP bridge priority for switches/stacks or switch profiles. An empty array will clear the STP bridge priority settings.
// 
// #### Supports Action Batches
// 
// **Resource**|**Operation**
// :-------------: |:-------------:
// `/networks/{networkId}/switch/stp` | update
// 

@name("Updates STP Settings")
PUT "https://{{baseUrl}}/networks/:networkId/switch/stp"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
json({
    "rstpEnabled": "<boolean>",
    "stpBridgePriority": [
        {
            "stpPriority": "<integer>",
            "switchProfiles": [
                "<string>",
                "<string>"
            ],
            "switches": [
                "<string>",
                "<string>"
            ],
            "stacks": [
                "<string>",
                "<string>"
            ]
        },
        {
            "stpPriority": "<integer>",
            "switchProfiles": [
                "<string>",
                "<string>"
            ],
            "switches": [
                "<string>",
                "<string>"
            ],
            "stacks": [
                "<string>",
                "<string>"
            ]
        }
    ]
})



