#!/usr/bin/env dothttp

// This pulls all the tweets for @AAHealth and saves them to the environment.

@name("Anne Arundel County Department of Health")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:AAHealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @BMore_Healthy and saves them to the environment.

@name("Baltimore City Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:BMore_Healthy"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @cecilcohealth and saves them to the environment.

@name("Cecil County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:cecilcohealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @CCDH_Maryland and saves them to the environment.

@name("Charles County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:CCDH_Maryland"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @FCHealthDept and saves them to the environment.

@name("Frederick County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:FCHealthDept"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @HarCoHealthDept and saves them to the environment.

@name("Harford County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:HarCoHealthDept"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @MoCoDHHS and saves them to the environment.

@name("Montgomery County Department of Health and Human Services")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:MoCoDHHS"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @SMCHD_gov and saves them to the environment.

@name("St. Mary's County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:SMCHD_gov"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @wicomicohealth and saves them to the environment.

@name("Wicomico County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:wicomicohealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"


// This pulls all the tweets for @worcesterhealth and saves them to the environment.

@name("Worcester County Health Department")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:worcesterhealth"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"



