#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Find Users Assignable To Projects")
GET "https://{{baseUrl}}/rest/api/3/user/assignable/multiProjectSearch"
? "query"= "<string>"
? "username"= "<string>"
? "accountId"= "<string>"
? "projectKeys"= "<string>"
? "startAt"= "0"
? "maxResults"= "50"


@name("Find Users Assignable To Issues")
GET "https://{{baseUrl}}/rest/api/3/user/assignable/search"
? "query"= "<string>"
? "sessionId"= "<string>"
? "username"= "<string>"
? "accountId"= "<string>"
? "project"= "<string>"
? "issueKey"= "<string>"
? "startAt"= "0"
? "maxResults"= "50"
? "actionDescriptorId"= "<integer>"
? "recommend"= "false"



