#!/usr/bin/env dothttp

@name("signup")
POST "https://{{localapi}}bills/api/v1/auth/signup"
"Content-Type": "application/x-www-form-urlencoded"
files(
	("email", "tim@gmail.com"),
	("password", "ttsmuj"),
	("f_name", "Tim"),
	("l_name", "Uzua"),
	("referer", ""),
	("phone", "+2348134942718")
)


@name("verify")
POST "https://{{localapi}}bills/api/v1/auth/verify"
? "code"= "11111111"
files(
	("code", "278561")
)


@name("login")
POST "https://{{localapi}}ob/api/v1/auth/login"
"Content-Type": "application/x-www-form-urlencoded"
files(
	("phone", "2349014719431"),
	("password", "122222")
)


@name("user profile")
GET "https://{{localapi}}ob/api/v1/profile/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/x-www-form-urlencoded"



@name("update profile")
PUT "https://{{localapi}}bills/api/v1/profile/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
	 "id": "15",
            "f_name": "timchoe",
            "l_name": "Sen",
            "phone": "+2348134942718",
            "email": "tim@gmail.com",
            "gender": "Malwe",
            "dob": "1988"
}')


@name("update trnx pin")
PUT "https://{{localapi}}bills/api/v1/update-transaction-pin/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
            "new_pin": "122222",
            "old_pin": "Sen89999",
            "new_pin2": "122222"
            
}')


@name("referer code")
GET "https://{{localapi}}bills/api/v1/referer-code/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
	 "id": "15",
            "f_name": "timchoe",
            "l_name": "Sen",
            "phone": "+2348134942718",
            "email": "tim@gmail.com",
            "gender": "Malwe",
            "dob": "1988"
}')


@name("saved contacts")
GET "https://{{localapi}}bills/api/v1/saved-contacts/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
	 "id": "15",
            "f_name": "timchoe",
            "l_name": "Sen",
            "phone": "+2348134942718",
            "email": "tim@gmail.com",
            "gender": "Malwe",
            "dob": "1988"
}')


@name("add contact")
POST "https://{{localapi}}bills/api/v1/save-contact/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
            "service": "airtime",
            "name": "Sen",
            "detail": "+2348134942718"
}')


@name("delete contacts")
DELETE "https://{{localapi}}bills/api/v1/delete-contact/4460af0b-f0cc-46c9-9985-c1c63f33cb43/3"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
	 "id": "15",
            "f_name": "timchoe",
            "l_name": "Sen",
            "phone": "+2348134942718",
            "email": "tim@gmail.com",
            "gender": "Malwe",
            "dob": "1988"
}')


@name("add support")
POST "https://{{localapi}}bills/api/v1/send-support/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
            "title": "Billing Error",
            "category": "Failed Transactions",
            "msg": "Hey i had a failed transaction werror and i need it ficed axap, can you do that"
}')


@name("get support")
GET "https://{{localapi}}bills/api/v1/support-msgs/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
            "title": "Billing Error",
            "msg": "Hey i had a billing werror and i need it ficed axap, can you do that"
}')


@name("view support")
GET "https://{{localapi}}bills/api/v1/view-support/4460af0b-f0cc-46c9-9985-c1c63f33cb43/1"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
            "title": "Billing Error",
            "msg": "Hey i had a billing werror and i need it ficed axap, can you do that"
}')


@name("reply support")
POST "https://{{localapi}}bills/api/v1/reply-support/4460af0b-f0cc-46c9-9985-c1c63f33cb43/1"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
            "msg": "Gbe body eh, madoooo, I tell you js that, no i cant do it"
}')


@name("create trnx pin")
POST "https://{{localapi}}bills/api/v1/create-transaction-pin/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
            "new_pin": "Sen89999s",
            "new_pin2": "Sen89999s"
            
}')


@name("update password")
PUT "https://{{localapi}}ob/api/v1/update-password/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
data('{
            "new_password": "122222",
            "old_password": "122222",
            "new_password2": "122222"
            
}')


@name("airtime ")
GET "https://{{localapi}}bills/api/v1/airtime-provider"


@name("buy airtime")
POST "https://{{localapi}}bills/api/v1/buy-airtime/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
files(
	("phone", "09014719431"),
	("amount", "50"),
	("vendor", "Airtel"),
	("vendor_code", "1")
)


@name("buy data")
POST "https://{{localapi}}bills/api/v1/buy-data/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
? "phone"= "08064044939"
? "amount"= "5"
? "vendor"= "MTN"
? "vendor_code"= "15"
? "data_size"= "25"
files(
	("phone", "08134942718"),
	("amount", "50"),
	("vendor", "MTN"),
	("vendor_code", "15")
)


@name("get data plans")
GET "https://{{localapi}}ob/api/v1/data-bundles"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
? "vendor_codename"= "airtel"


@name("get data operators")
GET "https://{{localapi}}bills/api/v1/data-operators"
"Content-Type": "application/json"
"Accept": "multipart/form-data"


@name("get cable operators")
GET "https://{{localapi}}bills/api/v1/cable-operators"
"Content-Type": "application/json"
"Accept": "multipart/form-data"


@name("confirm smartcard number (cable TV)")
GET "https://{{localapi}}bills/api/v1/cable-bundles"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
? "vendor_codename"= "gotv"
? "card_no"= "7029504523"


@name("get electricity providers")
GET "https://{{localapi}}bills/api/v1/electricity-providers"
"Content-Type": "application/json"
"Accept": "multipart/form-data"


@name("confirm meter number")
GET "https://{{localapi}}bills/api/v1/confirm-meterno"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
? "vendor_codename"= "BPE-NGCABABB-OR"
? "meterno"= "04172523989"


@name("buy electricity")
POST "https://{{localapi}}bills/api/v1/buy-electricity/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
files(
	("meterno", "04172523989"),
	("amount", "5"),
	("vendor", "AEDC"),
	("vendor_code", "BPE-NGCABABB-OR"),
	("mtype", "1"),
	("ky", "ef35dc70506ab5c358739e6bd670f94173d81913b3d21d752aaf5720d895d537")
)


@name("buy dstv/gotv")
POST "https://{{localapi}}bills/api/v1/buy-multichoice/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Content-Type": "application/json"
"Accept": "multipart/form-data"
files(
	("smartno", "7029504523"),
	("customer", "PHILLIPS TERKURA"),
	("phone", "08134942718"),
	("invoice", "1"),
	("amount", "1250"),
	("billtype", "gotv"),
	("customernumber", "105022360")
)


@name("wallet topup")
POST "https://{{localapi}}bills/api/v1/wallet-topup/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Accept": "application/json"
"Content-Type": "application/json"
files(
	("ref", "454545889"),
	("amount", "5000"),
	("cardno", "5531886652142950"),
	("cvv", "564"),
	("expirymonth", "09"),
	("expiryyear", "22")
)


@name("card pin")
POST "https://{{localapi}}bills/api/v1/card-pin/4460af0b-f0cc-46c9-9985-c1c63f33cb43"
"Accept": "application/json"
"Content-Type": "application/json"
files(
	("cardpin", "3310")
)



