#!/usr/bin/env dothttp

// Returns the theme selected for a space, if one is set. If no space
// theme is set, this means that the space is inheriting the global look
// and feel settings.
// 
// **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘View’ permission for the space.

@name("Get space theme")
GET "https://{{baseUrl}}/api/space/:spaceKey/theme"


// Sets the theme for a space. Note, if you want to reset the space theme to
// the default Confluence theme, use the 'Reset space theme' method instead
// of this method.
// 
// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
// 'Admin' permission for the space.

@name("Set space theme")
PUT "https://{{baseUrl}}/api/space/:spaceKey/theme"
"Content-Type": "application/json"
json({
    "themeKey": "<string>"
})


// Resets the space theme. This means that the space will inherit the
// global look and feel settings
// 
// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
// 'Admin' permission for the space.

@name("Reset space theme")
DELETE "https://{{baseUrl}}/api/space/:spaceKey/theme"



