#!/usr/bin/env dothttp

@name("断线重连接口")
POST "https://{{base_url}}/reconnect"
"Content-Type": "application/json"
"Authorization": "{{authorization}}"
json({
    "wId": "{{wId}}",
    "wcId": "{{微信id}}",
    "type": 2
})


@name("批量下线微信号")
POST "https://{{base_url}}/member/offline"
"Content-Type": "application/json"
"Authorization": "{{authorization}}"
json({
    "account": "18013350963",
    "wcIds": [
        "wxid_eh43uiikr66622",
        "wxid_qfmuoxz6xgkt22",
        "wxid_k6rm31zzyp0q22",
        "wxid_y9lse7geyddy21",
        "wxid_vei2i7v83t9a12",
        "liqin2433082127",
        "wxid_cmvawwyt9ocb22",
        "wxid_pybj5ebyk0yk22",
        "wxid_bc8quycz7v3b22",
        "wxid_2ox06qml57cl21",
        "wf470317638",
        "wxid_20eiyz8l0zlv22",
        "wxid_q45htcu26h5g22",
        "wxid_znxmdtml49dy22",
        "wxid_fz841v4flj2222",
        "wxid_r9ez3ia8bev922"
    ]
})


@name("查询微信是否在线")
POST "https://{{base_url}}/isOnline"
"Content-Type": "application/json"
"Authorization": "{{authorization}}"
json({
    "wId": "{{wId}}"
})


@name("退出微控平台")
POST "https://{{base_url}}/member/logout"
"Content-Type": "application/json"
"Authorization": "{{authorization}}"



@name("查询账号下已登录的微信号")
POST "https://{{base_url}}/member/getLoginWcIds"
"Content-Type": "application/json"
"Authorization": "{{authorization}}"




