#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Project's Sender Email")
GET "None://{{baseUrl}}/rest/api/3/project/:projectId/email"


@name("Set Project's Sender Email")
PUT "None://{{baseUrl}}/rest/api/3/project/:projectId/email"
"Content-Type": "application/json"
data('{
    "emailAddress": "<string>"
}')



