#!/usr/bin/env dothttp

// To add new entities to a module.

@name("Leads")
POST "https://{{api-domain}}/crm/v2.1/Leads"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Company": "Zylker",
            "Last_Name": "Daly",
            "First_Name": "Paul",
            "Email": "p.daly@zylker.com",
            "State": "Texas"
        },
        {
            "Company": "Villa Margarita",
            "Last_Name": "Dolan",
            "First_Name": "Brian",
            "Email": "brian@villa.com",
            "State": "Texas"
        }
    ],
    "lar_id": "{{lar_id}}",
    "trigger": [
        "approval",
        "workflow",
        "blueprint"
    ]
})


// To add new entities to a module.

@name("Accounts")
POST "https://{{api-domain}}/crm/v2.1/Accounts"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Parent_Account": {
                "id": "{{parent-account-id}}"
            },
            "Ownership": "Private",
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Account_Type": "Competitor",
            "Rating": "Active",
            "SIC_Code": 12792,
            "Shipping_State": "Shipping_State",
            "Website": "crm.zoho.com",
            "Employees": 12792,
            "Industry": "Data/Telecom OEM",
            "Account_Site": "Account_Site",
            "Phone": "988844559",
            "Billing_Country": "Billing_Country",
            "Account_Name": "Account_Name",
            "Account_Number": "1245681",
            "Ticker_Symbol": "Ticker_Symbol",
            "Billing_Street": "Billing_Street",
            "Billing_Code": "Billing_Code",
            "Shipping_City": "Shipping_City",
            "Shipping_Country": "Shipping_Country",
            "Shipping_Code": "Shipping_Code",
            "Billing_City": "Billing_City",
            "Billing_State": "Billing_State",
            "Fax": "Fax",
            "Annual_Revenue": 127.67,
            "Shipping_Street": "Shipping_Street"
        }
    ]
})


// To add new entities to a module.

@name("Contacts")
POST "https://{{api-domain}}/crm/v2.1/Contacts"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Account_Name": {
                "id": "{{account-id}}"
            },
            "Vendor_Name": {
                "id": "{{vendor-id}}"
            },
            "Email": "newcrmapi@zoho.com",
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Mailing_Zip": "Mailing_Zip",
            "Reports_To": "Reports_To",
            "Other_Phone": "988844559",
            "Mailing_State": "Mailing_State",
            "Twitter": "Twitter",
            "Other_Zip": "Other_Zip",
            "Mailing_Street": "Mailing_Street",
            "Other_State": "Other_State",
            "Salutation": "Mrs.",
            "Other_Country": "Other_Country",
            "First_Name": "First_Name",
            "Asst_Phone": "988844559",
            "Department": "Department",
            "Skype_ID": "Skype_ID",
            "Assistant": "Assistant",
            "Phone": "988844559",
            "Mailing_Country": "Mailing_Country",
            "Email_Opt_Out": true,
            "Date_of_Birth": "2018-01-25",
            "Mailing_City": "Mailing_City",
            "Other_City": "Other_City",
            "Title": "Title",
            "Other_Street": "Other_Street",
            "Mobile": "988844559",
            "Home_Phone": "988844559",
            "Last_Name": "Last_Name",
            "Lead_Source": "Cold Call",
            "Fax": "Fax",
            "Secondary_Email": "newcrmapi@zoho.com"
        }
    ]
})


// To add new entities to a module.

@name("Deals")
POST "https://{{api-domain}}/crm/v2.1/Deals"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Account_Name": {
                "id": "{{account-id}}"
            },
            "Contact_Name": {
                "id": "{{contact-id}}"
            },
            "Campaign_Source": {
                "id": "{{campaign-id}}"
            },
            "Type": "New Business",
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Deal_Name": "Deal_Name",
            "Amount": 1237.67,
            "Next_Step": "Next_Step",
            "Stage": "Needs Analysis",
            "Lead_Source": "Cold Call",
            "Closing_Date": "2018-01-25"
        }
    ]
})


// To create campaigns.

@name("Campaigns")
POST "https://{{api-domain}}/crm/v2.1/Campaigns"
json({
    "data": [
        {
            "Campaign_Name": "sample",
            "Type": "Conference"
        }
    ]
})


// To add new entities to a module.

@name("Tasks")
POST "https://{{api-domain}}/crm/v2.1/Tasks"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Who_Id": {
                "id": "{{contact-id}}"
            },
            "What_Id": {
                "id": "{{record-id}}"
            },
            "$se_module": "{{record-module}}",
            "Status": "In Progress",
            "Send_Notification_Email": true,
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Due_Date": "2018-01-25",
            "Priority": "Low",
            "send_notification": true,
            "Subject": "Subject",
            "Remind_At": {
                "ALARM": "FREQ=NONE;ACTION=EMAIL;TRIGGER=DATE-TIME:2018-01-25T17:09:00+05:30"
            }
        }
    ]
})


// To add new entities to a module.

@name("Cases")
POST "https://{{api-domain}}/crm/v2.1/Cases"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Product_Name": {
                "id": "{{product-id}}"
            },
            "Deal_Name": {
                "id": "{{deal-id}}"
            },
            "Account_Name": {
                "id": "{{account-id}}"
            },
            "Related_To": {
                "id": "{{contact-id}}"
            },
            "Status": "On Hold",
            "Email": "newcrmapi@zoho.com",
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Internal_Comments": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Priority": "Medium",
            "Reported_By": "Reported_By",
            "Case_Origin": "Phone",
            "Case_Reason": "Complex functionality",
            "Subject": "Subject",
            "Type": "Feature Request",
            "Phone": "988844559"
        }
    ]
})


// To add new entities to a module.

@name("Events")
POST "https://{{api-domain}}/crm/v2.1/Events"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Who_Id": {
                "id": "{{contact-id}}"
            },
            "What_Id": {
                "id": "{{record-id}}"
            },
            "$se_module": "{{record-module}}",
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Venue": "Venue",
            "Start_DateTime": "2018-01-27T15:10:00+05:30",
            "Participants": [
                {
                    "type": "lead",
                    "participant": "1000000071949"
                },
                {
                    "type": "contact",
                    "participant": "1000000071957"
                },
                {
                    "type": "email",
                    "participant": "newcrmapi@zoho.com"
                },
                {
                    "type": "user",
                    "participant": "1000000030977"
                }
            ],
            "Event_Title": "Event_Title",
            "send_notification": true,
            "End_DateTime": "2018-01-27T17:10:00+05:30"
        }
    ]
})


// To add new entities to a module.

@name("Calls (scheduled)")
POST "https://{{api-domain}}/crm/v2.1/Calls"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Who_Id": {
                "name": "Patricia Boyle",
                "id": "3652397000000649013"
            },
            "Description": "Product Demo for ZCRM",
            "Call_Start_Time": "2021-02-28T19:30:00+05:30",
            "Subject": "Demo",
            "Call_Type": "Outbound",
            "Outbound_Call_Status": "Scheduled",
            "Call_Purpose": " Product Demo ZCRM"
        }
    ]
})


// To add new entities to a module.

@name("Calls (completed)")
POST "https://{{api-domain}}/crm/v2.1/Calls"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Who_Id": {
                "name": "Patricia Boyle",
                "id": "3652397000000649013"
            },
            "Description": "Discussion ZCRM",
            "Call_Start_Time": "2021-02-23T13:30:00+05:30",
            "Subject": "Discussion",
            "Call_Type": "Outbound",
            "Outbound_Call_Status": "Completed",
            "Call_Duration": "10:00",
            "Call_Purpose": "Administrative"
        }
    ]
})


// To add new entities to a module.

@name("Calls (inbound)")
POST "https://{{api-domain}}/crm/v2.1/Calls"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Who_Id": {
                "name": "Patricia Boyle",
                "id": "3652397000000649013"
            },
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Call_Start_Time": "2019-10-23T13:25:00+05:30",
            "Subject": "Subject",
            "Call_Type": "Inbound",
            "Call_Duration": "10:00"
        }
    ]
})


// To add new entities to a module.

@name("Calls (missed)")
POST "https://{{api-domain}}/crm/v2.1/Calls"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Who_Id": {
                "name": "Patricia Boyle",
                "id": "3652397000000649013"
            },
            "Call_Start_Time": "2019-10-23T13:25:00+05:30",
            "Subject": "Subject",
            "Call_Type": "Missed"
        }
    ]
})


// To add new entities to a module.

@name("Solutions")
POST "https://{{api-domain}}/crm/v2.1/Solutions"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Product_Name": {
                "id": "{{product-id}}"
            },
            "Status": "Duplicate",
            "Answer": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Solution_Title": "Solution_Title",
            "Question": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately."
        }
    ]
})


// To add new entities to a module.

@name("Products")
POST "https://{{api-domain}}/crm/v2.1/Products"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Handler": {
                "id": "{{user-id}}"
            },
            "Vendor_Name": {
                "id": "{{vendor-id}}"
            },
            "Product_Category": "Software",
            "Qty_in_Demand": 1237.89,
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Commission_Rate": 1237.67,
            "Product_Name": "Product_Name",
            "Quantity_In_Stock": 12792,
            "Sales_Start_Date": "2018-01-25",
            "Tax": [
                "Sales Tax"
            ],
            "Support_Start_Date": "2018-01-25",
            "Product_Active": true,
            "Usage_Unit": "Caton",
            "Product_Code": "Product_Code",
            "Qty_Ordered": 1237.89,
            "Manufacturer": "LexPon Inc.",
            "Qty_in_Stock": 1237.89,
            "Support_Expiry_Date": "2018-01-25",
            "Sales_End_Date": "2018-01-25",
            "Unit_Price": 1237.67,
            "Taxable": true,
            "Reorder_Level": 1237.89
        }
    ]
})


// To add new entities to a module.

@name("Vendors")
POST "https://{{api-domain}}/crm/v2.1/Vendors"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Email": "newcrmapi@zoho.com",
            "Category": "Category",
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Vendor_Name": "Vendor_Name",
            "Website": "crm.zoho.com",
            "City": "City",
            "Phone": "988844559",
            "State": "State",
            "GL_Account": "Rental-Income",
            "Street": "Street",
            "Country": "Country",
            "Zip_Code": "Zip_Code"
        }
    ]
})


// To add new entities to a module.

@name("Price Books")
POST "https://{{api-domain}}/crm/v2.1/Price_Books"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Active": true,
            "Pricing_Details": [
                {
                    "to_range": 5,
                    "discount": 0,
                    "from_range": 1
                },
                {
                    "to_range": 11,
                    "discount": 1,
                    "from_range": 6
                },
                {
                    "to_range": 17,
                    "discount": 2,
                    "from_range": 12
                },
                {
                    "to_range": 23,
                    "discount": 3,
                    "from_range": 18
                },
                {
                    "to_range": 29,
                    "discount": 4,
                    "from_range": 24
                }
            ],
            "Pricing_Model": "Differential",
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Price_Book_Name": "Price_Book_Name"
        }
    ]
})


// To add new entities to a module.

@name("Quotes")
POST "https://{{api-domain}}/crm/v2.1/Quotes"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Contact_Name": {
                "id": "{{contact-id}}"
            },
            "Deal_Name": {
                "id": "{{deal-id}}"
            },
            "Account_Name": {
                "id": "{{account-name}}"
            },
            "Discount": 127.67,
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Shipping_State": "Shipping_State",
            "Tax": 127.67,
            "Valid_Till": "2018-01-25",
            "Billing_Country": "Billing_Country",
            "Team": "Team",
            "Carrier": "USPS",
            "Quote_Stage": "Delivered",
            "Billing_Street": "Billing_Street",
            "Adjustment": 127.67,
            "Terms_and_Conditions": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Billing_Code": "Billing_Code",
            "Product_Details": [
                {
                    "product": {
                        "id": "1000000071967"
                    },
                    "quantity": 150,
                    "Discount": 20,
                    "product_description": "product_description",
                    "Unit Price": 10,
                    "line_tax": [
                        {
                            "percentage": 10.5,
                            "name": "Sales Tax"
                        },
                        {
                            "percentage": 6.5,
                            "name": "Common Tax"
                        }
                    ]
                }
            ],
            "Subject": "Subject",
            "Shipping_City": "Shipping_City",
            "Shipping_Country": "Shipping_Country",
            "Shipping_Code": "Shipping_Code",
            "Billing_City": "Billing_City",
            "Billing_State": "Billing_State",
            "$line_tax": [
                {
                    "percentage": 12.5,
                    "name": "Sales Tax"
                },
                {
                    "percentage": 8.5,
                    "name": "Common Tax"
                }
            ],
            "Shipping_Street": "Shipping_Street"
        }
    ]
})


// To add new entities to a module.

@name("Sales Orders")
POST "https://{{api-domain}}/crm/v2.1/Sales_Orders"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Deal_Name": {
                "id": "{{deal-id}}"
            },
            "Account_Name": {
                "id": "{{account-id}}"
            },
            "Quote_Name": {
                "id": "{{quote-id}}"
            },
            "Contact_Name": {
                "id": "{{contact-id}}"
            },
            "Discount": 127.67,
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Customer_No": "Customer_No",
            "Shipping_State": "Shipping_State",
            "Tax": 127.67,
            "Billing_Country": "Billing_Country",
            "Carrier": "USPS",
            "Status": "Delivered",
            "Sales_Commission": 127.67,
            "Due_Date": "2018-01-25",
            "Billing_Street": "Billing_Street",
            "Adjustment": 127.67,
            "Terms_and_Conditions": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Billing_Code": "Billing_Code",
            "Product_Details": [
                {
                    "product": {
                        "id": "1000000071967"
                    },
                    "quantity": 150,
                    "Discount": 20,
                    "product_description": "product_description",
                    "Unit Price": 10,
                    "line_tax": [
                        {
                            "percentage": 10.5,
                            "name": "Sales Tax"
                        },
                        {
                            "percentage": 6.5,
                            "name": "Common Tax"
                        }
                    ]
                },
                {
                    "product": {
                        "id": "100000008007"
                    },
                    "quantity": 151,
                    "Discount": 21,
                    "product_description": "product_description",
                    "Unit Price": 11,
                    "line_tax": [
                        {
                            "percentage": 11.5,
                            "name": "Sales Tax"
                        },
                        {
                            "percentage": 7.5,
                            "name": "Common Tax"
                        }
                    ]
                }
            ],
            "Subject": "Subject",
            "Excise_Duty": 127.67,
            "Shipping_City": "Shipping_City",
            "Shipping_Country": "Shipping_Country",
            "Shipping_Code": "Shipping_Code",
            "Billing_City": "Billing_City",
            "Purchase_Order": "Purchase_Order",
            "Billing_State": "Billing_State",
            "$line_tax": [
                {
                    "percentage": 12.5,
                    "name": "Sales Tax"
                },
                {
                    "percentage": 8.5,
                    "name": "Common Tax"
                }
            ],
            "Pending": "Pending",
            "Shipping_Street": "Shipping_Street"
        }
    ]
})


// To add new entities to a module.

@name("Purchase Orders")
POST "https://{{api-domain}}/crm/v2.1/Purchase_Orders"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Vendor_Name": {
                "id": "{{vendor-id}}"
            },
            "Contact_Name": {
                "id": "{{contact-id}}"
            },
            "Discount": 127.67,
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Shipping_State": "Shipping_State",
            "Tax": 127.67,
            "PO_Date": "2018-01-25",
            "Billing_Country": "Billing_Country",
            "Carrier": "USPS",
            "Status": "Delivered",
            "Sales_Commission": 127.67,
            "PO_Number": "PO_Number",
            "Due_Date": "2018-01-25",
            "Billing_Street": "Billing_Street",
            "Adjustment": 127.67,
            "Terms_and_Conditions": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Billing_Code": "Billing_Code",
            "Product_Details": [
                {
                    "product": {
                        "id": "1000000071967"
                    },
                    "quantity": 150,
                    "Discount": 20,
                    "product_description": "product_description",
                    "Unit Price": 10,
                    "line_tax": [
                        {
                            "percentage": 10.5,
                            "name": "Sales Tax"
                        },
                        {
                            "percentage": 6.5,
                            "name": "Common Tax"
                        }
                    ]
                },
                {
                    "product": {
                        "id": "100000008007"
                    },
                    "quantity": 151,
                    "Discount": 21,
                    "product_description": "product_description",
                    "Unit Price": 11,
                    "line_tax": [
                        {
                            "percentage": 11.5,
                            "name": "Sales Tax"
                        },
                        {
                            "percentage": 7.5,
                            "name": "Common Tax"
                        }
                    ]
                }
            ],
            "Subject": "Subject",
            "Tracking_Number": "Tracking_Number",
            "Excise_Duty": 127.67,
            "Shipping_City": "Shipping_City",
            "Shipping_Country": "Shipping_Country",
            "Shipping_Code": "Shipping_Code",
            "Billing_City": "Billing_City",
            "Requisition_No": "Requisition_No",
            "Billing_State": "Billing_State",
            "$line_tax": [
                {
                    "percentage": 12.5,
                    "name": "Sales Tax"
                },
                {
                    "percentage": 8.5,
                    "name": "Common Tax"
                }
            ],
            "Shipping_Street": "Shipping_Street"
        }
    ]
})


// To add new entities to a module.

@name("Invoices")
POST "https://{{api-domain}}/crm/v2.1/Invoices"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"
json({
    "data": [
        {
            "Owner": {
                "id": "{{user-id}}"
            },
            "Account_Name": {
                "id": "{{account-id}}"
            },
            "Sales_Order": {
                "id": "{{sales-order-id}}"
            },
            "Contact_Name": {
                "id": "{{contact-id}}"
            },
            "Discount": 127.67,
            "Description": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Shipping_State": "Shipping_State",
            "Tax": 127.67,
            "Invoice_Date": "2018-01-25",
            "Billing_Country": "Billing_Country",
            "Status": "Delivered",
            "Sales_Commission": 127.67,
            "Due_Date": "2018-01-25",
            "Billing_Street": "Billing_Street",
            "Adjustment": 127.67,
            "Terms_and_Conditions": "Design your own layouts that align your business processes precisely. Assign them to profiles appropriately.",
            "Billing_Code": "Billing_Code",
            "Product_Details": [
                {
                    "product": {
                        "id": "1000000071967"
                    },
                    "quantity": 150,
                    "Discount": 20,
                    "product_description": "product_description",
                    "Unit Price": 10,
                    "line_tax": [
                        {
                            "percentage": 10.5,
                            "name": "Sales Tax"
                        },
                        {
                            "percentage": 6.5,
                            "name": "Common Tax"
                        }
                    ]
                },
                {
                    "product": {
                        "id": "100000008007"
                    },
                    "quantity": 151,
                    "Discount": 21,
                    "product_description": "product_description",
                    "Unit Price": 11,
                    "line_tax": [
                        {
                            "percentage": 11.5,
                            "name": "Sales Tax"
                        },
                        {
                            "percentage": 7.5,
                            "name": "Common Tax"
                        }
                    ]
                }
            ],
            "Subject": "Subject",
            "Excise_Duty": 127.67,
            "Shipping_City": "Shipping_City",
            "Shipping_Country": "Shipping_Country",
            "Shipping_Code": "Shipping_Code",
            "Billing_City": "Billing_City",
            "Purchase_Order": "Purchase_Order",
            "Billing_State": "Billing_State",
            "$line_tax": [
                {
                    "percentage": 12.5,
                    "name": "Sales Tax"
                },
                {
                    "percentage": 8.5,
                    "name": "Common Tax"
                }
            ],
            "Shipping_Street": "Shipping_Street"
        }
    ]
})



