#!/usr/bin/env dothttp

@name("Get attribute history")
GET "https://{{host}}/STH/v1/contextEntities/type/myType/id/myEntity/attributes/temperature"
"Fiware-Service": "{{service}}"
"Fiware-ServicePath": "{{subservice}}"
"X-Auth-Token": "{{token}}"
? "hLimit"= "3"
? "hOffset"= "0"
? "dateFrom"= "2017-10-16T00:00:00.000Z"
? "dateTo"= "2017-10-26T23:59:59.999Z
"


@name("Get attribute aggregation")
GET "https://{{host}}/STH/v1/contextEntities/type/myType/id/myEntity/attributes/temperature"
"Fiware-Service": "{{service}}"
"Fiware-ServicePath": "{{subservice}}"
"X-Auth-Token": "{{token}}"
? "aggrMethod"= "sum"
? "aggrPeriod"= "hour"
? "dateFrom"= "2017-10-16T00:00:00.000Z"
? "dateTo"= "2017-10-26T23:59:59.999Z
"



