#!/usr/bin/env dothttp

@name("Returns a list of itemCategories")
GET "https://{{baseUrl}}/companies({{company_id}})/itemCategories"
? "$top"= "<integer>"
? "$skip"= "<integer>"
? "$limit"= "<integer>"
? "$filter"= "<string>"
? "$select"= "<string>,<string>"


@name("Creates an object of type itemCategory in Dynamics 365 Business Central")
POST "https://{{baseUrl}}/companies({{company_id}})/itemCategories"
"Content-Type": "<string>"
"Content-Type": "application/json"
json({
    "id": "<uuid>",
    "code": "<string>",
    "displayName": "<string>",
    "lastModifiedDateTime": "<dateTime>"
})



