#!/usr/bin/env dothttp

@name("Org Metric Scan Summary")
GET "https://{{host}}/services/data/v47.0/sobjects/OrgMetricScanSummary/"


@name("Org Metric Scan Summary Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/OrgMetricScanSummary/{ID}/"


@name("Describe Org Metric Scan Summary")
GET "https://{{host}}/services/data/v47.0/sobjects/OrgMetricScanSummary/describe/"



