#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Worklog Property")
GET "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:worklogId/properties/:propertyKey"


@name("Set Worklog Property")
PUT "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:worklogId/properties/:propertyKey"
"Content-Type": "application/json"
data('{}')


@name("Delete Worklog Property")
DELETE "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/worklog/:worklogId/properties/:propertyKey"



