#!/usr/bin/env dothttp

// Test Upload file using multipart/form-data request and postman-echo/post service.

@name("Upload File")
POST "http://postman-echo.com/post"
files(
	("file", "None")
)


// Download a hello_world.pdf file using visualizer to invoke the javascript code "window.location.href" to save a file. You can set base64 data, a local file location, or a remote file location (http / https)

@name("Download File")
GET "https://{{url}}/file"
? "type"= "pdf"


// Visualize a hello_world.pdf file using visualizer to invoke html and jquery to click a button to show and hide a pdf, using embed or iframe tags. You can set base64 data, a local file location, or a remote file location (http / https) as the source to visualize the file.
// 
// In order to visualize base64 pdf, use the following directives and values:
// 
// frame-src data:;
// object-src data:;
// 
// In order to visualize a remote pdf file, use the following directives and values:
// 
// frame-src http: https:;
// object-src http: https:;
// 
// In order to visualize a local pdf file, use the following directives and values:
// 
// frame-src 'self';
// object-src 'self';

@name("Visualize File")
GET "https://{{url}}/file"
? "type"= "pdf"



