#!/usr/bin/env dothttp

@name("Buscar usuário por documento")
GET "https://leomadeiras.myvtex.com/api/dataentities/CL/search"
"x-vtex-api-appkey": "{{vtex-ApiKey}}"
"x-vtex-api-apptoken": "{{vtex-ApiToken}}"
? "_where"= "document=455.639.670-00"
? "_fields"= "_all"



// Criacao de clientes

@name("Cadastro de cliente")
POST "https://leomadeiras.myvtex.com/api/dataentities/CL/documents"
"accept": "application/vnd.vtex.ds.v10+json"
"x-vtex-api-appkey": "{{vtex-ApiKey}}"
"x-vtex-api-apptoken": "{{vtex-ApiToken}}"
json({
    "firstName": "teste TI",
    "document": "48170179025",
    "email": "testeTI@leo.com.br",
    "homePhone": "67785454",
    "lastName": "Poc leo",
    "phone": "11965654787",
    "IdExterno": "1001545453"
})


// Atualizacao de cliente

@name("Update de cliente Master Data")
PATCH "https://leomadeiras.myvtex.com/api/dataentities/CL/documents/881dc0e2-b7c1-11ea-8343-12c76e768305"
"accept": "application/vnd.vtex.ds.v10+json"
"x-vtex-api-appkey": "{{vtex-ApiKey}}"
"x-vtex-api-apptoken": "{{vtex-ApiToken}}"
json({
    "IdExterno": "100154545323"
})


// Consulta de clientes

@name("Consulta de clientes vtex por Id")
GET "https://leomadeiras.myvtex.com/api/dataentities/CL/documents/0d81f05f-b580-11ea-8343-1236299758d1"
"accept": "application/vnd.vtex.ds.v10+json"
"content-type": "application/json"
"x-vtex-api-appkey": "{{vtex-ApiKey}}"
"x-vtex-api-apptoken": "{{vtex-ApiToken}}"
? "_fields"= "_all"



@name("Consulta de clientes na api Profiles por email")
GET "https://leomadeiras.myvtex.com/api/checkout/pub/profiles"
"x-vtex-api-appkey": "{{vtex-ApiKey}}"
"x-vtex-api-apptoken": "{{vtex-ApiToken}}"
? "email"= "thales.ribeiro@leomadeiras.com.br"
? "_fields"= "_all"



@name("Criacao de endereco")
POST "https://leomadeiras.myvtex.com/api/dataentities/AD/documents"
"x-vtex-api-appkey": "{{vtex-ApiKey}}"
"x-vtex-api-apptoken": "{{vtex-ApiToken}}"
"accept": "application/vnd.vtex.ds.v10+json"
json({
    "userId": "f7761e66-a117-4e41-816e-8a83187f9c74",
    "street": "Rua teste",
    "state": "SP",
    "city": "Sao Paulo",
    "country": "Brasil",
    "neighborhood": "Centro",
    "number": "number",
    "postalCode": "05417020",
    "addressName": "Casa"
})



