#!/usr/bin/env dothttp

// Deprecated; use `POST /v2/cv/images` instead. This endpoint uploads an image for reverse image search. The image must be in JPEG or PNG format. To get the search results, pass the ID that this endpoint returns to the `GET /v2/images/{id}/similar` endpoint.

@name("Upload ephemeral images")
POST "https://{{baseUrl}}/v2/images"
"Content-Type": "application/json"
data('{
    "base64_image": "<string>"
}')



