#!/usr/bin/env dothttp

@name("Accept a repository invitation")
PATCH "https://{{baseUrl}}/user/repository_invitations/:invitation_id"


@name("Decline a repository invitation")
DELETE "https://{{baseUrl}}/user/repository_invitations/:invitation_id"



