#!/usr/bin/env dothttp

# imported from http://localhost:8000/Microsoft%20Graph.postman_collection.json

@name("Get Users")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9cec70>"


@name("Invite Guest User")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9d1070>"
"Content-Type": "application/json"
data('{ 
    "invitedUserDisplayName": "<Display Name of Invited User>", 
    "invitedUserEmailAddress": "<Email Address of Invited User>, 
    "invitedUserMessageInfo": {
        "messageLanguage": "en-US",
        "ccRecipients": [
             {
                "emailAddress": {
                    "name": "<Optional CC for Invitation>",
                    "address": "<Optional CC Email Address for Invitation>"
                 }
             }
        ],
        "customizedMessageBody": "Hi, you have just been invited to Azure AD with Postman using Microsoft Graph!"
     },
    "sendInvitationMessage": true, 
    "inviteRedirectUrl": "https://myapps.microsoft.com" 
} ')



