#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get a package for the authenticated user")
GET "https://{{baseUrl}}/user/packages/{{package_type}}/{{package_name}}/"


@name("Delete a package for the authenticated user")
DELETE "https://{{baseUrl}}/user/packages/{{package_type}}/{{package_name}}/"


@name("Restore a package for the authenticated user")
POST "https://{{baseUrl}}/user/packages/{{package_type}}/{{package_name/restore}}/"
? "token"= "aliqua consectetur elit incididu"



