#!/usr/bin/env dothttp

@name("List all files")
GET "https://{{baseUrl}}/v1/files"
"Content-Type": "application/x-www-form-urlencoded"
? "created[gt]"= "<integer>"
? "created[gte]"= "<integer>"
? "created[lt]"= "<integer>"
? "created[lte]"= "<integer>"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "limit"= "<integer>"
? "purpose"= "<string>"
? "starting_after"= "<string>"


@name("Create a file")
POST "https://files.stripe.com/v1/files"
"Content-Type": "multipart/form-data"
files(
	("file", "<string>"),
	("purpose", "<string>"),
	("expand", "["<string>","<string>"]"),
	("file_link_data", "{"create":"<boolean>","expires_at":"<unix-time>","metadata":"<object>"}")
)


@name("Retrieve a file")
GET "https://{{baseUrl}}/v1/files/:file"
"Content-Type": "application/x-www-form-urlencoded"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"



