#!/usr/bin/env dothttp

@name("Get safety relevant traffic information in the range of a given location")
GET "https://{{baseUrl}}/:location"
? "radius"= "-88105560"
? "cause"= "HR"
? "next_page_token"= "d"



