#!/usr/bin/env dothttp

@name("FOODS")
GET "https://api.greenpanier-server.com/api/v1/categories/foods"


@name("MEALS")
GET "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/api/v1/categories/meals"



