#!/usr/bin/env dothttp

@name("Product2 Change Event")
GET "https://{{host}}/services/data/v47.0/sobjects/Product2ChangeEvent/"


@name("Product2 Change Event Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Product2ChangeEvent/{ID}/"


@name("Describe Product2 Change Event")
GET "https://{{host}}/services/data/v47.0/sobjects/Product2ChangeEvent/describe/"



