#!/usr/bin/env dothttp

# imported from https://raw.githubusercontent.com/fbsamples/WhatsApp-Business-API-Postman-Collection/master/collection.json

@name("Get-First-Party-Stickerpacks")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b253a0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-First-Party-Stickerpack-Info")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b25550>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-First-Party-Stickers")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b25700>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-First-Party-Sticker-Info")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b258b0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Create-Third-Party-Stickerpacks")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b25a90>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"publisher": "<Your Publisher Name>",
	"name": "<Your Sticker Pack Name>",
	"ios_app_store_link": "<Valid iOS App Store Link>",
	"android_app_store_link": "<Valid Android App Store Link>"
}')


@name("Get-Third-Party-Stickerpacks")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b25be0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Update-Third-Party-Stickerpack")
PATCH "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b25d60>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"publisher": "<Your Publisher Name>",
	"name": "<Your Sticker Pack Name>",
	"ios_app_store_link": "<Valid iOS App Store Link>",
	"android_app_store_link": "<Valid Android App Store Link>"
}')


@name("Delete-Third-Party-Stickerpack")
DELETE "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b25eb0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-Third-Party-Stickerpack-Info")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b28040>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Create-Third-Party-Stickers")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b281c0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"image_data_id" : "<Sticker Image Media Id>",
	"emojis": ["🐥", "😃"]
}')


@name("Get-Third-Party-Stickers")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b28310>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Update-Third-Party-Sticker")
PATCH "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b28490>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"image_data_id" : "<Valid Image Media Id",
	"emojis": ["🐥", "😃"]
}')


@name("Delete-Third-Party-Sticker")
DELETE "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b28610>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"



@name("Get-Third-Party-Sticker-Info")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7fbae6b28760>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"



