#!/usr/bin/env dothttp

# imported from https://raw.githubusercontent.com/fbsamples/WhatsApp-Business-API-Postman-Collection/master/collection.json

@name("Get-First-Party-Stickerpacks")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49fdca0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-First-Party-Stickerpack-Info")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49fde50>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-First-Party-Stickers")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4985040>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-First-Party-Sticker-Info")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49851f0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Create-Third-Party-Stickerpacks")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49853d0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"publisher": "<Your Publisher Name>",
	"name": "<Your Sticker Pack Name>",
	"ios_app_store_link": "<Valid iOS App Store Link>",
	"android_app_store_link": "<Valid Android App Store Link>"
}')


@name("Get-Third-Party-Stickerpacks")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4985520>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Update-Third-Party-Stickerpack")
PATCH "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49856d0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"publisher": "<Your Publisher Name>",
	"name": "<Your Sticker Pack Name>",
	"ios_app_store_link": "<Valid iOS App Store Link>",
	"android_app_store_link": "<Valid Android App Store Link>"
}')


@name("Delete-Third-Party-Stickerpack")
DELETE "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4985820>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-Third-Party-Stickerpack-Info")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4985970>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Create-Third-Party-Stickers")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4985af0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"image_data_id" : "<Sticker Image Media Id>",
	"emojis": ["🐥", "😃"]
}')


@name("Get-Third-Party-Stickers")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4985c40>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Update-Third-Party-Sticker")
PATCH "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4985dc0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"image_data_id" : "<Valid Image Media Id",
	"emojis": ["🐥", "😃"]
}')


@name("Delete-Third-Party-Sticker")
DELETE "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4985f40>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"



@name("Get-Third-Party-Sticker-Info")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a498b0d0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"



