#!/usr/bin/env dothttp

@name("Get-First-Party-Stickerpacks")
GET "https://{{URL}}/v1/stickerpacks"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
? "namespace"= "whatsapp"


@name("Get-First-Party-Stickerpack-Info")
GET "https://{{URL}}/v1/stickerpacks/{{Test-1P-Stickerpack-Id}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
? "namespace"= "whatsapp"


@name("Get-First-Party-Stickers")
GET "https://{{URL}}/v1/stickerpacks/{{Test-1P-Stickerpack-Id}}/stickers"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
? "namespace"= "whatsapp"


@name("Get-First-Party-Sticker-Info")
GET "https://{{URL}}/v1/stickerpacks/{{Test-1P-Stickerpack-Id}}/stickers/{{Test-Sticker-Index}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
? "namespace"= "whatsapp"


@name("Create-Third-Party-Stickerpacks")
POST "https://{{URL}}/v1/stickerpacks"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"publisher": "<Your Publisher Name>",
	"name": "<Your Sticker Pack Name>",
	"ios_app_store_link": "<Valid iOS App Store Link>",
	"android_app_store_link": "<Valid Android App Store Link>"
}')


@name("Get-Third-Party-Stickerpacks")
GET "https://{{URL}}/v1/stickerpacks"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Update-Third-Party-Stickerpack")
PATCH "https://{{URL}}/v1/stickerpacks/{{Test-3P-Stickerpack-Id}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"publisher": "<Your Publisher Name>",
	"name": "<Your Sticker Pack Name>",
	"ios_app_store_link": "<Valid iOS App Store Link>",
	"android_app_store_link": "<Valid Android App Store Link>"
}')


@name("Delete-Third-Party-Stickerpack")
DELETE "https://{{URL}}/v1/stickerpacks/{{Test-3P-Stickerpack-Id}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Get-Third-Party-Stickerpack-Info")
GET "https://{{URL}}/v1/stickerpacks/{{Test-3P-Stickerpack-Id}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Create-Third-Party-Stickers")
POST "https://{{URL}}/v1/stickerpacks/{{Test-3P-Stickerpack-Id}}/stickers"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"image_data_id" : "<Sticker Image Media Id>",
	"emojis": ["🐥", "😃"]
}')


@name("Get-Third-Party-Stickers")
GET "https://{{URL}}/v1/stickerpacks/{{Test-3P-Stickerpack-Id}}/stickers"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Update-Third-Party-Sticker")
PATCH "https://{{URL}}/v1/stickerpacks/{{Test-3P-Stickerpack-Id}}/stickers/{{Test-Sticker-Index}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"image_data_id" : "<Valid Image Media Id",
	"emojis": ["🐥", "😃"]
}')


@name("Delete-Third-Party-Sticker")
DELETE "https://{{URL}}/v1/stickerpacks/{{Test-3P-Stickerpack-Id}}/stickers/{{Test-Sticker-Index}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"



@name("Get-Third-Party-Sticker-Info")
GET "https://{{URL}}/v1/stickerpacks/{{Test-3P-Stickerpack-Id}}/stickers/{{Test-Sticker-Index}}"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"



