#!/usr/bin/env dothttp

@name("Login Event")
GET "https://{{host}}/services/data/v47.0/sobjects/LoginEvent/"


@name("Login Event Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/LoginEvent/{ID}/"


@name("Describe Login Event")
GET "https://{{host}}/services/data/v47.0/sobjects/LoginEvent/describe/"



