#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Application Property")
GET "https://{{baseUrl}}/rest/api/3/application-properties"
basicauth("{{atlassian_email}}", "{{atlassian_token}}")
? "key"= "<string>"
? "permissionLevel"= "<string>"
? "keyFilter"= "<string>"


@name("Get Advanced Settings")
GET "{{baseUrl}}/rest/api/3/application-properties/advanced-settings"
basicauth("{{atlassian_email}}", "{{atlassian_token}}")


@name("Set Application Property")
PUT "https://{{baseUrl}}/rest/api/3/application-properties/:id"
basicauth("{{atlassian_email}}", "{{atlassian_token}}")
"Content-Type": "application/json"
data('{
    "id": "<string>",
    "value": "<string>"
}')



