#!/usr/bin/env dothttp

@name("/express/validate_point")
POST "https://{{baseUrl}}/express/validate_point"
? "longitude"= "<longitud>"
? "latitude"= "<latitud>"


@name("/express/validate_point")
PUT "https://{{baseUrl}}/express/validate_point"
? "longitude"= "<longitud>"
? "latitude"= "<latitud>"


@name("/express/validate_point")
OPTIONS "https://{{baseUrl}}/express/validate_point"



