#!/usr/bin/env dothttp

@name("Get the order details")
GET "https://{{url}}/api/Extendedorders/{{order_id}}"
basicauth("{{user_name}}", "{{api_key}}")
? "lang_code"= "{{lang_code}}"
? "currency_code"= "{{currency_code}}"



@name("Get the My order list")
GET "https://{{url}}/api/Extendedorders/"
basicauth("{{user_name}}", "{{api_key}}")
? "user_id"= "{{customer_id}}"
? "lang_code"= "{{lang_code}}"
? "currency_code"= "{{currency_code}}"



@name("Get the order list of guest")
GET "https://{{url}}/api/Extendedorders/"
basicauth("{{user_name}}", "{{api_key}}")
? "order_id"= "{{order_id}}"
? "lang_code"= "{{lang_code}}"
? "currency_code"= "{{currency_code}}"




