#!/usr/bin/env dothttp

// Use this API Call to generate a ticket.

@name("Generate a Ticket")
POST "https://{{crosswork_ip}}/crosswork/sso/v1/tickets"
"Content-Type": "application/x-www-form-urlencoded"
"Accept": "text/plain"
"Cache-Control": "no-cache"
? "username"= "admin"
? "password"= "Cwork123!"



// Use this API Call to generate the token using the generated ticket.

@name("Generate a Token")
POST "https://{{crosswork_ip}}/crosswork/sso/v1/tickets/{{ticket}}"
"Content-Type": "application/x-www-form-urlencoded"
"Accept": "text/plain"
"Cache-Control": "no-cache"
data({
    "service": [
        "https://172.23.193.107:30603/app-dashboard"
    ]
})



