#!/usr/bin/env dothttp

@name("READ User MFA Enabled")
GET "https://{{apiPath}}/environments/{{envID}}/users/{{userID}}/mfaEnabled"


@name("UPDATE User MFA Enabled")
PUT "https://{{apiPath}}/environments/{{envID}}/users/{{userID}}/mfaEnabled"
"content-type": "application/json"
json({
    "mfaEnabled": true
})



