#!/usr/bin/env dothttp

@name("Sample endpoint: Returns details about a particular user")
GET "https://{{baseUrl}}/user"
? "id"= "<integer>"


// Everything in AtOmXpLuD
@name("🙈🙉🙊")
GET "https://api.github.com/graphql"



