#!/usr/bin/env dothttp

// Declare the parameters as to use them in the post request. Define the value headers as Params in this request.

@name("Receive response")
GET "https://postman-echo.com/get"
? "Main-avatar"= "{{firstname}}"
? "last-name"= "{{lastname}}"
? "Habitat"= "{{value}}"


// Use the POST method to update the response. Declare the values added in your previous GET request as the Body here and check if you are receiving the valid responses using the scripts.

@name("Post response")
POST "https://postman-echo.com/post"
"Content-Type": "application/json"
json({
    "Main-avatar": "{{firstname}}",
    "last-name": "{{lastname}}",
    "Habitat": "{{value}}"
})


// Use the POST method to update the response. Declare the values added in your previous GET request as the Body here and check if you are receiving the valid responses using the scripts.

@name("Email")
POST "https://postman-echo.com/post"
"Content-Type": "application/json"
json([
    {
        "name": "{{name}}",
        "description": "{{description}}",
        "handles": [
            {
                "source": "email",
                "handle": "{{handle_email}}"
            },
            {
                "source": "phone",
                "handle": "{{handle_phone}}"
            }
        ]
    }
])



