#!/usr/bin/env dothttp

@name("Initial Get")
GET "https://postman-echo.com/get"



@name("Meme or Quote")
GET "https://type.fit/api/quotes"



@name("Jokes")
GET "https://official-joke-api.appspot.com/random_joke"


@name("Initialize O")
GET "https://{{heroku_url}}/initO"


@name("Initialize X")
GET "https://{{heroku_url}}/initX"



@name("Validate configuration")
GET "https://{{heroku_url}}/validate"
data('{
    "text":{{text}}
}')


@name("Set Index")
GET "https://{{heroku_url}}/setIndex"
data('{
    "text":{{text}}
}')


@name("Decide for opponent")
GET "https://{{heroku_url}}/decide"



@name("Invalid")
POST "https://{{response_url}}/"
json({
    "text": "Invalid configuration, Enter Again!"
})


@name("Display inter")
POST "https://{{response_url}}/"
json({
    "text": "Your move : 
{{data}}"
})


@name("Display board")
POST "https://{{response_url}}/"
json({
    "text": "{{data}}"
})


@name("Display quote")
POST "https://{{response_url}}/"
json({
    "blocks": [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "{{data}}",
                "emoji": true
            }
        }
    ]
})



