#!/usr/bin/env dothttp

@name("Get entity from JobApplicationBackgroundCheckResult by key")
GET "https://{{baseUrl}}/JobApplicationBackgroundCheckResult({{statusId}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
? "$select"= "vendorOrderNo,stepMessage"
? "$expand"= "*,backgroundCheckRequest"


@name("Update entity in JobApplicationBackgroundCheckResult")
PUT "https://{{baseUrl}}/JobApplicationBackgroundCheckResult({{statusId}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
"Content-Type": "application/json"
data('{
    "d": {
        "createdDateTime": "/Date(1492098664000)/",
        "finalStep": true,
        "reportUrl": "aute ut ",
        "statusId": "veniam velit fugiat pariatur",
        "stepMessage": "mollit tempor",
        "stepName": "Excepteur nostrud laborum",
        "stepStatus": "qui ea",
        "vendorCode": "do mollit nulla tempor officia",
        "vendorOrderNo": "ad ut",
        "backgroundCheckRequest": {
            "applicationId": "aute voluptate ut occaecat nulla",
            "createdByUser": "occaecat laboris",
            "createdDateTime": "/Date(1492098664000)/",
            "lastModifiedDateTime": "/Date(1492098664000)/",
            "orderStatus": "Duis ut dolore labore",
            "requestId": "sint in",
            "responseCode": "dolor Ut",
            "responseDetail": "sint",
            "vendorCode": "dolor ullamco labore",
            "vendorOrderNo": "dolore deserunt ea",
            "jobApplication": {
                "address": "nisi",
                "address2": "dolore",
                "agencyInfo": "veniam aliquip sed",
                "anonymizedDate": "/Date(1492098664000)/",
                "anonymizedFlag": "proident",
                "appLocale": "Duis nulla non",
                "appStatusSetItemId": "in in",
                "applicationId": "sint n",
                "applicationTemplateId": "do deserunt consectetur dolor velit",
                "averageRating": "fugiat exercitation in nulla aliqua",
                "baseSalary": "sed officia",
                "candConversionProcessed": "labore magna veniam",
                "candJust": "est eu dolore fugiat",
                "candTypeWhenHired": "Ut in Duis",
                "candidateId": "elit sed ut Ut",
                "cellPhone": "mollit",
                "city": "deserunt in ut",
                "confnumber": "commodo",
                "contactEmail": "esse aute",
                "conviction_details": "laborum sunt ex",
                "country": "Ut con",
                "countryCode": "aliqua",
                "criminalconvictionlabel": "eu",
                "crimincalconvictioninstructions": "magna officia culpa",
                "currentLocation": "nulla ex laboris dolore",
                "currentTitle": "sunt",
                "cust_refCheckFirstName": "in",
                "cust_refCheckLastName": "et dolore elit adipisicing occaecat",
                "cust_refCheckOrg1": "cillum proident",
                "cust_refCheckPhone1": "reprehenderit proiden",
                "cust_refCheckTitle1": "nisi eiusmod",
                "dataSource": "sunt Excepteur nostrud elit",
                "dateAvail": "/Date(1492098664000)/",
                "dateOfBirth": "/Date(1492098664000)/",
                "duplicateProfile": "in ve",
                "exportedOn": "/Date(1492098664000)/",
                "extTitle": "ipsum esse non",
                "firstName": "in irure",
                "formerEmployee": true,
                "gender": "deserunt officia in commodo",
                "haveyoubeenconvicted": "nisi adipisicing sed anim",
                "hireDate": "/Date(1492098664000)/",
                "hiredOn": "/Date(1492098664000)/",
                "homePhone": "minim sint aliqua",
                "inductionAdd": "anim cillum aliqua nulla",
                "inductionDate": "/Date(1492098664000)/",
                "initials": "Ut velit pariatur anim mollit",
                "instrAppReturn": "non esse",
                "instrCandApproval": "fugiat sit",
                "instrCandAssess": "pariatur officia sit",
                "instrCandFields": "exercitation esse reprehenderit",
                "instrCandScreen": "ut deserunt exercitation",
                "instrWotc": "exercitation",
                "instr_AdditionalDocuments": "in veniam reprehenderit",
                "instr_AppAdditionalInfo": "laborum mollit ut amet",
                "instr_AppAdvice": "aliqua dolore sunt",
                "instr_CandAppDetails": "et nulla aliqua Duis dolor",
                "instr_CandPersInfo": "veniam",
                "instr_EEOinstructions": "sunt adipisicing officia Excepteur",
                "instr_EEOlable": "enim culpa ea ipsum",
                "instrubkgrndChkAttachment": "in eiusmod minim",
                "jobAppGuid": "Duis dolor ipsum velit",
                "jobCode": "off",
                "jobRateOfPay": "ipsum laboris mollit ad",
                "jobReqId": "commodo",
                "jobStartDate": "/Date(1492098664000)/",
                "jobofferdate": "/Date(1492098664000)/",
                "knownAs": "fugiat ut elit",
                "lastModifiedBy": "dolor",
                "lastModifiedByProxy": "deserunt occaecat dolor",
                "lastModifiedDateTime": "/Date(1492098664000)/",
                "lastName": "est irure dolore do",
                "medDate": "/Date(1492098664000)/",
                "medLoc": "enim labore",
                "medTime": "voluptate fugiat aute dolore",
                "middleName": "culpa labore quis id",
                "nonApplicantStatus": "sunt incididunt in ullamco",
                "owner": "aliqua cillum et",
                "ownershpDate": "/Date(1492098664000)/",
                "phoneScreenDate": "/Date(1492098664000)/",
                "phoneScreenDetails": "dolor dolore",
                "pleaseselect": "dolore laboris eiusmod nulla",
                "posTitle": "laboris anim non officia",
                "profileUpdated": "nisi exercitation",
                "psychTestDte": "/Date(1492098664000)/",
                "psychTestTme": "aliquip reprehenderit",
                "rating": "quis irure anim eu",
                "reasonableaccomodation": "in voluptate exercitation consectetur",
                "reference": "exercitation Ut",
                "referenceComments": "velit culpa in",
                "referredBy": "ex exercitation ut",
                "resumeUploadDate": "/Date(1492098664000)/",
                "screendate": "/Date(1492098664000)/",
                "snapShotDate": "/Date(1492098664000)/",
                "source": "velit laborum sint",
                "sourceLabel": "ex reprehenderit labore",
                "ssn": "culpa consectetur qui aliqua",
                "startDate": "/Date(1492098664000)/",
                "stateOther": "dolor mollit",
                "status": "minim irure non",
                "statusComments": "deserunt",
                "timeToHire": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "title": "in cupidatat aliquip",
                "usersSysId": "dolor consectetur",
                "visaNum": "Excepteur incididunt",
                "voluntaryselfID": "cillum consectetur labore",
                "whyask": "in",
                "wotcFormsURL": "Lorem dolor nulla",
                "wotcId": "ut cupidatat",
                "wotcScreeningURL": "commodo dolore aliquip",
                "wotcStatus": "eu esse proident",
                "yesanswer": "sunt pariatur aliquip adipisicing nulla",
                "zip": "elit Duis",
                "jobAppStatus": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "jobApplicationAssessmentOrder": {
                    "results": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "jobApplicationAssessmentOrder_1": {
                    "results": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "jobApplicationComments": {
                    "results": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "jobApplicationOnboardingData": {
                    "results": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "jobApplicationQuestionResponse": {
                    "results": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "jobApplicationStatusAuditTrail": {
                    "results": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                }
            }
        }
    }
}')



