#!/usr/bin/env dothttp

@name("https://localhost:44352/api/style/e012dcd8-82dd-44ce-a0c8-08d7f002e730")
GET "https://localhost/api/country"
data('"Undertaker"')


@name("https://localhost:44352/api/style/e012dcd8-82dd-44ce-a0c8-08d7f002e730")
GET "https://localhost/api/country/29473585-5e82-4cfc-844e-0c371a6690d6"
data('"Undertaker"')


@name("https://localhost:44352/api/country/29473585-5e82-4cfc-844e-0c371a6690d6")
PUT "https://localhost/api/country/29473585-5e82-4cfc-844e-0c371a6690d6"
data('"Swen"')


@name("https://localhost:44352/api/country/29473585-5e82-4cfc-844e-0c371a6690d6")
DELETE "https://localhost/api/country/29473585-5e82-4cfc-844e-0c371a6690d6"
data('"Swen"')


@name("https://localhost:44352/api/country/29473585-5e82-4cfc-844e-0c371a6690d6")
POST "https://localhost/api/country"
data('"Death valley"')



