#!/usr/bin/env dothttp

@name("User Provisioning Request Share")
GET "https://{{host}}/services/data/v47.0/sobjects/UserProvisioningRequestShare/"


@name("User Provisioning Request Share Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/UserProvisioningRequestShare/{ID}/"


@name("Describe User Provisioning Request Share")
GET "https://{{host}}/services/data/v47.0/sobjects/UserProvisioningRequestShare/describe/"



