#!/usr/bin/env dothttp

// <h2>Description</h2>
// This operation returns a list of Index Servers
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/data_cube/r_data_cube_api_get_analytics_engines.htm)

@name("Index Servers")
GET "https://{{ServerUrl}}/AnalyticsServers"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"


// <h2>Description</h2>
// This operation returns properties of an index server.

@name("Index Server Properteis")
GET "https://{{ServerUrl}}/AnalyticsServers/id/{{cloudId}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"


// <h2>Description</h2>
// This operation returns a list of Inventories.

@name("Inventories")
GET "https://{{ServerUrl}}/EDiscoveryClients/Inventories"
"Accept": "application/xml"
"Authtoken": "{{TOKEN}}"


// <h2>Description</h2>
// This operation creates a new Inventory.

@name("Create Inventory")
POST "https://{{ServerUrl}}/EDiscoveryClients/Inventories"
"Accept": "application/xml"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
data('{
  "inventoryName": "Rest_Api_Inventory",
  "analyticsEngineCloud": {
    "cloudId": {{cloudId}},
    "cloudDisplayName": "{{cloudDisplayName}}"
  }
}')


// <h2>Description</h2>
// This operation adds one or more assets to an Inventory.

@name("Add Assets To Inventory")
PUT "https://{{ServerUrl}}/EDiscoveryClients/Inventories"
"Accept": "application/xml"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
data('{
  "inventoryId": {{inventoryId}},
  "assets": [
    {
      "name": "testlab.commvault.com",
      "type": 61
    },
    {
      "name": "dm2.commvault.com",
      "type": 61
    }
  ]
}')


// <h2>Description</h2>
// This operation removes an asset from the Inventory.

@name("Remove Asset From Inventory")
PUT "https://{{ServerUrl}}/EDiscoveryClients/Inventories/{{inventoryId}}/Assets"
"Accept": "application/xml"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
data('{
  "inventoryId": {{inventoryId}},
  "assets": [
    {
      "assetId": {{assetId}}
    }
  ]
}')


// <h2>Description</h2>
// This operation returns details about an Inventory

@name("Inventory Details")
GET "https://{{ServerUrl}}/EDiscoveryClients/Inventories/{{inventoryId}}"
"Accept": "application/xml"
"Authtoken": "{{TOKEN}}"


// <h2>Description</h2>
// This operation deletes an Inventory.

@name("Delete Inventory")
DELETE "https://{{ServerUrl}}/EDiscoveryClients/Inventories/{{inventoryId}}"
"Accept": "application/xml"
"Authtoken": "{{TOKEN}}"




