#!/usr/bin/env dothttp

// To get the total number of records under a tag.

@name("Leads")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Leads"


// To get the total number of records under a tag.

@name("Accounts")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Accounts"


// To get the total number of records under a tag.

@name("Contacts")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Contacts"


// To get the total number of records under a tag.

@name("Deals")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Deals"


// To get the total number of records under a tag.

@name("Campaigns")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Campaigns"


// To get the total number of records under a tag.

@name("Tasks")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Tasks"


// To get the total number of records under a tag.

@name("Cases")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Cases"


// To get the total number of records under a tag.

@name("Events")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Events"


// To get the total number of records under a tag.

@name("Calls")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Calls"


// To get the total number of records under a tag.

@name("Solutions")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Solutions"


// To get the total number of records under a tag.

@name("Products")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Products"


// To get the total number of records under a tag.

@name("Vendors")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Vendors"


// To get the total number of records under a tag.

@name("Price Books")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Price_Books"


// To get the total number of records under a tag.

@name("Quotes")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Quotes"


// To get the total number of records under a tag.

@name("Sales Orders")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Sales_Orders"


// To get the total number of records under a tag.

@name("Purchase Orders")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Purchase_Orders"


// To get the total number of records under a tag.

@name("Invoices")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Invoices"


// To get the total number of records under a tag.

@name("Activities")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "Calls"


// To get the total number of records under a tag.

@name("Custom")
GET "https://{{api-domain}}/crm/v2/settings/tags/{{tag_id}}/actions/records_count"
? "module"= "{{custom_module_api_name}}"



