#!/usr/bin/env dothttp

// Produces a summary of timesheet information across practices

@name("timesheets/summary")
GET "https://localhost/practice-management-api/timesheets/summary"



// Validates timesheets across all resources for a given period in months or weeks.  Periods start from 1st October which is the start of our financial year.  
// 
// For example, when dealing with months
// 1 = October
// 12 = September
// 
// When dealing with weeks, week 1 is the first working day in the start of the new financial year. For example in FY19
// 1 = Monday 3rd September
// 
// 
// TimesheetStatus can be one of DRAFT, SUBMITTED (marked as submitted in Harvest), APPROVED
// 
// ValidationStatus can be one of VALIDATED, WARNING

@name("timesheets/validate")
GET "https://timesheets/validate"



@name("engagements/")
GET "https://localhost/practice-management-api/engagements/"




