#!/usr/bin/env dothttp

// Provides challans analytics

@name("Get Challans Analytics")
GET "https://{{host}}/tds/payers/:payer_id/analytics/challans"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"
? "from"= "{{from}}"
? "to"= "{{to}}"



