#!/usr/bin/env dothttp

// Lists all secret scanning alerts for a private repository, from newest to oldest. To use this endpoint, you must be an administrator for the repository or organization, and you must use an access token with the `repo` scope or `security_events` scope.
// 
// GitHub Apps must have the `secret_scanning_alerts` read permission to use this endpoint.

@name("List secret scanning alerts for a repository")
GET "https://{{baseUrl}}/repos/:owner/:repo/secret-scanning/alerts"
? "state"= "<string>"
? "page"= "1"
? "per_page"= "30"



