#!/usr/bin/env dothttp

// [linked_apps/list_member_linked_apps](https://www.dropbox.com/developers/documentation/http/teams#team-linked_apps-list_member_linked_apps)
// 
// scope: `sessions.list`
// 
// List all linked applications of the team member.
// Note, this endpoint does not list any team-linked applications.

@name("linked_apps/list_member_linked_apps")
POST "https://api.dropboxapi.com/2/team/linked_apps/list_member_linked_apps"
"Content-Type": "application/json"
json({
    "team_member_id": "dbmid:AAFdgehTzw7WlXhZJsbGCLePe8RvQGYDr-I"
})


// [linked_apps/list_members_linked_apps](https://www.dropbox.com/developers/documentation/http/teams#team-linked_apps-list_members_linked_apps)
// 
// scope: `sessions.list`
// 
// List all applications linked to the team members' accounts.
// Note, this endpoint does not list any team-linked applications.

@name("linked_apps/list_members_linked_apps")
POST "https://api.dropboxapi.com/2/team/linked_apps/list_members_linked_apps"
"Content-Type": "application/json"



// [linked_apps/revoke_linked_app](https://www.dropbox.com/developers/documentation/http/teams#team-linked_apps-revoke_linked_app)
// 
// scope: `sessions.modify`
// 
// Revoke a linked application of the team member.

@name("linked_apps/revoke_linked_app")
POST "https://api.dropboxapi.com/2/team/linked_apps/revoke_linked_app"
"Content-Type": "application/json"



// [linked_apps/revoke_linked_app_batch](https://www.dropbox.com/developers/documentation/http/teams#team-linked_apps-revoke_linked_app_batch)
// 
// scope: `sessions.modify`
// 
// Revoke a list of linked applications of the team members.

@name("linked_apps/revoke_linked_app_batch")
POST "https://api.dropboxapi.com/2/team/linked_apps/revoke_linked_app_batch"
"Content-Type": "application/json"




