#!/usr/bin/env dothttp

@name("Feed Item")
GET "https://{{host}}/services/data/v47.0/sobjects/FeedItem/"


@name("Feed Item Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/FeedItem/{ID}/"


@name("Describe Feed Item")
GET "https://{{host}}/services/data/v47.0/sobjects/FeedItem/describe/"



