#!/usr/bin/env dothttp

@name("Get Prospects with Scroll [DEPRECATED]")
GET "https://{{sb_client}}.salesboard.biz/v1/prospects"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "latitude"= "52.068333530081304"
? "longitude"= "4.326610298925175"
? "include"= "coordinates,resultCodes,fields"
? 'filters'= '{"teams":[2,4,5,6,7,8], "campaigns":[109,110,111,114,117,119], "audiences":[1,2,3,5]}'
? 'filters'= '{"campaigns":[1]}'
? 'filters'= '{ "audiences":[21]}'


@name("Get Prospects by scroll id [DEPRECATED]")
POST "https://{{sb_client}}.salesboard.biz/v1/prospects/scroll"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
json({
    "scroll_id": "{{sb_scroll_id}}",
    "include": "coordinates,resultCodes,fields"
})


@name("Update Prospect (RC only) [DEPRECATED]")
PUT "https://{{sb_client}}.salesboard.biz/v1/prospects/3ffa3c57ae6d6475177c89c77a4c477a"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
data('{
    "ID_Team": 3, 
    "ID_User": 1, 
    "resultCode": 12
}')


@name("Create Prospect - for audience, with coordinates")
POST "https://{{sb_client}}.salesboard.biz/v1/prospects"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
json({
    "fields": {
        "postcode": "1011AB",
        "houseNumber": 106,
        "houseSuffix": "1",
        "street": "De Ruijterkade",
        "city": "Amsterdam",
        "country": "Netherlands"
    },
    "resultCodes": [],
    "coordinates": [
        4.905166,
        52.3777798
    ],
    "audiences": [
        1
    ]
})


@name("Get Prospects details (single) - DEPRECATED")
GET "https://{{sb_client}}.salesboard.biz/v1/prospects/{{sb_prospect_id}}"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"
? "include"= "coordinates,resultCodes,fields"



