#!/usr/bin/env dothttp

@name("Add Windows File server")
POST "https://{{ServerUrl}}/CreateTask"
"Accept": "{{Accept}}"
"Content-Type": "application/json"
"Authtoken": "{{TOKEN}}"
data('{
  "taskInfo": {
    "associations": [
      {
        "commCellId": 2
      }
    ],
    "task": {
      "taskType": 1,
      "initiatedFrom": 1,
      "taskFlags": {
        "disabled": false
      }
    },
    "subTasks": [
      {
        "subTask": {
          "subTaskType": 1,
          "operationType": 4026
        },
        "options": {
          "adminOpts": {
            "clientInstallOption": {
              "reuseADCredentials": false,
              "installOSType": 0,
              "discoveryType": 0,
              "installerOption": {
                "requestType": 0,
                "Operationtype": 0,
                "CommServeHostName": "YashGDPRAuto.dm2.commvault.com",
                "RemoteClient": false,
                "installFlags": {
                  "allowMultipleInstances": true,
                  "restoreOnlyAgents": false,
                  "killBrowserProcesses": true,
                  "install32Base": false,
                  "disableOSFirewall": false,
                  "stopOracleServices": false,
                  "skipClientsOfCS": false,
                  "addToFirewallExclusion": true,
                  "ignoreJobsRunning": false,
                  "forceReboot": false,
                  "overrideClientInfo": true,
                  "firewallInstall": {
                    "enableFirewallConfig": false,
                    "firewallConnectionType": 0,
                    "portNumber": 0
                  }
                },
                "User": {
                  "userName": "test\\tenantuser",
                  "userId": 321
                },
                "clientComposition": [
                  {
                    "packageDeliveryOption": 0,
                    "overrideSoftwareCache": false,
                    "components": {
                      "commonInfo": {
                        "globalFilters": 2
                      },
                      "fileSystem": {
                        "configureForLaptopBackups": false
                      },
                      "componentInfo": [
                        {
                          "osType": "Windows",
                          "ComponentId": 702
                        }
                      ]
                    },
                    "clientInfo": {
                      "client": {
                        "evmgrcPort": 0,
                        "cvdPort": 0
                      }
                    }
                  }
                ]
              },
              "clientDetails": [
                {
                  "clientEntity": {
                    "clientName": "windowshost.company.com",
                    "commCellId": 2
                  }
                }
              ],
              "clientAuthForJob": {
                "password": "WFhYWFhYWFg=",
                "userName": "company\\adminuser"
              }
            },
            "updateOption": {
              "rebootClient": true,
              "plan": {
                "planId": 316
              }
            }
          }
        }
      }
    ]
  }
}')


@name("Add Unix File server")
POST "https://{{ServerUrl}}/CreateTask"
"Accept": "{{Accept}}"
"Content-Type": "application/json"
"Authtoken": "{{TOKEN}}"
data('{
  "taskInfo": {
    "associations": [
      {
        "commCellId": 2
      }
    ],
    "task": {
      "taskType": 1,
      "initiatedFrom": 1,
      "taskFlags": {
        "disabled": false
      }
    },
    "subTasks": [
      {
        "subTask": {
          "subTaskType": 1,
          "operationType": 4026
        },
        "options": {
          "adminOpts": {
            "clientInstallOption": {
              "reuseADCredentials": false,
              "installOSType": 1,
              "discoveryType": 0,
              "installerOption": {
                "requestType": 0,
                "Operationtype": 0,
                "CommServeHostName": "YashGDPRAuto.dm2.commvault.com",
                "RemoteClient": false,
                "installFlags": {
                  "allowMultipleInstances": true,
                  "restoreOnlyAgents": false,
                  "killBrowserProcesses": true,
                  "install32Base": false,
                  "disableOSFirewall": false,
                  "stopOracleServices": false,
                  "skipClientsOfCS": false,
                  "addToFirewallExclusion": true,
                  "ignoreJobsRunning": false,
                  "forceReboot": false,
                  "overrideClientInfo": true,
                  "firewallInstall": {
                    "enableFirewallConfig": false,
                    "firewallConnectionType": 0,
                    "portNumber": 0
                  }
                },
                "User": {
                  "userName": "test\\tenantuser",
                  "userId": 321
                },
                "clientComposition": [
                  {
                    "packageDeliveryOption": 0,
                    "overrideSoftwareCache": false,
                    "components": {
                      "commonInfo": {
                        "globalFilters": 2
                      },
                      "fileSystem": {
                        "configureForLaptopBackups": false
                      },
                      "componentInfo": [
                        {
                          "osType": "Unix",
                          "ComponentId": 1101
                        }
                      ]
                    },
                    "clientInfo": {
                      "client": {
                        "evmgrcPort": 0,
                        "cvdPort": 0
                      }
                    }
                  }
                ]
              },
              "clientDetails": [
                {
                  "clientEntity": {
                    "clientName": "unix.company.com",
                    "commCellId": 2
                  }
                }
              ],
              "clientAuthForJob": {
                "password": "WFhYWFhYWFg=",
                "userName": "root"
              }
            },
            "updateOption": {
              "rebootClient": true,
              "plan": {
                "planId": 316
              }
            }
          }
        }
      }
    ]
  }
}')



