#!/usr/bin/env dothttp

@name("Configurable Type Configuration Settings Post")
POST "https://{{baseUrl}}/platform/v2/configurabletypeconfigurationsettings"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "id": [
        "<string>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "isActive": [
        "<boolean>"
    ],
    "namespace": [
        "<string>"
    ],
    "description": [
        "<string>"
    ],
    "value": [
        "<string>"
    ],
    "configurableType": [
        "<string>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})


@name("Configurable Type Configuration Settings Get")
GET "https://{{baseUrl}}/platform/v2/configurabletypeconfigurationsettings/:tenantid"
"Authorization": "<string>"
? "msql"= "<string>"
? "page"= "<integer>"
? "pageSize"= "<integer>"


@name("Configurable Type Configuration Settings Get")
GET "https://{{baseUrl}}/platform/v2/configurabletypeconfigurationsettings/description/:tenantid"
"Authorization": "<string>"


@name("Configurable Type Configuration Settings Delete")
DELETE "https://{{baseUrl}}/platform/v2/configurabletypeconfigurationsettings/delete/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"



