#!/usr/bin/env dothttp

// Search for hotels and retrieve availability and rates information

@name("Hotel Search")
GET "https://test.api.amadeus.com/v2/shopping/hotel-offers"
? "cityCode"= "LON"


// Get one hotel and its available offers.

@name("Hotel Search Offers")
GET "https://test.api.amadeus.com/v2/shopping/hotel-offers/by-hotel"
? "hotelId"= "BGLONBGB"


// Get room and rate details.

@name("Hotel Search Offer information")
GET "https://test.api.amadeus.com/v2/shopping/hotel-offers/176383FB301E78D430F81A6CB6134EBF801DCC1AE14FC9DCCE84D17C6B519F5B"



