#!/usr/bin/env dothttp

// # Show a particular client

@name("client_show")
GET "https://test1.fullslate.com/api/v2/clients/30"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"


// # Display a list of clients

@name("client_index")
GET "https://test1.fullslate.com/api/v2/clients"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"
? "first_name"= "tEst"
? "phone_number"= "9876543210"
? "changed_since"= "2017-11-28T02:01:52-06:00"
? "include_inactive"= "true"
? "mass_email_opt_in"= "false"
? "email"= "aabbcc11@ccddff.co"
? "last_name"= "last name"
? "include_deleted"= "false"
? "tags"= "two,one"
? "event_id"= "1201075"
? "exclude_columns"= "first_name,last_name,id,notes,active,source,referrer,no_self_scheduling_online,client_since,no_sms,no_automatic_email,mass_email_opt_in,sms_reminder_consent,birthday,schedule_color_mode,sequence,time_zone,last_booked_at,tags,suffix,middle_name,deleted,deleted_at,updated_at,created_at,company_name_ext"
? "client_since"= "2017-11-18"


// # Create a client

@name("client_create")
POST "https://test1.fullslate.com/api/v2/clients"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "first_name": "meowie start",
    "last_name": "super",
    "suffix": "mgj",
    "company_name_ext": "rapid river two",
    "emails": [
        "emailv@something.co",
        "emailv2@something.co"
    ],
    "phone_numbers": [
        {
            "number": "1122334450",
            "contact_type": "WORK"
        },
        {
            "number": "9900119920",
            "contact_type": "HOME"
        }
    ],
    "addresses": [
        {
            "street1": "11, streetv 1",
            "street2": "some where street 1",
            "city": "some city",
            "state": "astate",
            "postal_code": "12345"
        },
        {
            "street1": "12, street 2",
            "street2": "some where street 2",
            "city": "some city2",
            "state": "astate2",
            "postal_code": "90111"
        }
    ],
    "time_zone": "Kuala Lumpur",
    "no_self_scheduling_online": true,
    "no_automatic_email": true,
    "no_sms": true,
    "mass_email_opt_in": true,
    "sms_reminder_consent": true,
    "tags": [
        "test 1",
        "test 2"
    ],
    "notes": "cliet notes",
    "birthday": "1983-04-02",
    "client_since": "2017-01-31",
    "source": "source lala",
    "referrer": "referrer lala"
})


// # Update a particular client

@name("client_update")
PATCH "https://test1.fullslate.com/api/v2/clients/36"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "first_name": "many email",
    "last_name": "edited",
    "emails": [
        "newemail@test.co",
        "meow11@sss.da"
    ],
    "phone_numbers": [
        {
            "number": "1122334455",
            "contact_type": "WORK"
        },
        {
            "number": "1231231231",
            "contact_type": "HOME"
        }
    ],
    "addresses": [
        {
            "street1": "1111, street 111",
            "street2": "some where street 1111",
            "city": "city one",
            "state": "AR",
            "postal_code": "54321"
        },
        {
            "street1": "22, street 2",
            "street2": "some where street 2",
            "city": "city two",
            "state": "CA",
            "postal_code": "98765"
        }
    ],
    "no_self_scheduling_online": false,
    "no_automatic_email": false,
    "no_sms": false,
    "mass_email_opt_in": false,
    "sms_reminder_consent": false,
    "client_since": "2017-05-05",
    "birthday": "1993-04-02",
    "tags": [
        "test3",
        "test4"
    ],
    "email_cc": [
        39,
        40
    ]
})


// # Delete a client

@name("client_delete")
DELETE "https://test1.fullslate.com/api/v2/clients/164"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"



