#!/usr/bin/env dothttp

// Returns list of geocoordinates which represents estimated geolocation confidence area.

@name("IP Geolocation with Confidence Area API")
GET "https://api.bigdatacloud.net/data/ip-geolocation-with-confidence"
? "ip"= "193.114.112.122"
? "localityLanguage"= "en"
? "key"= "{{API KEY}}"


// This API returns additional security hazard report in addition to confidence area and locality information.

@name("IP Geolocation with Confidence Area and Hazard Report API")
GET "https://api.bigdatacloud.net/data/ip-geolocation-full"
? "ip"= "193.114.112.122"
? "localityLanguage"= "en"
? "key"= "{{API KEY}}"



