#!/usr/bin/env dothttp

// Display the splash page settings for the given SSID

@name("getNetworkSsidSplashSettings")
GET "https://{{baseUrl}}/networks/:networkId/ssids/:number/splashSettings"
"Accept": "*/*"



// Modify the splash page settings for the given SSID
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// splashUrl| string| [optional] The custom splash URL of the click-through splash page. Note that the URL can be configured without necessarily being used. In order to enable the custom URL, see 'useSplashUrl'
// useSplashUrl| boolean| [optional] Boolean indicating whether the user will be redirected to the custom splash url. A custom splash URL must be set if this is true. Note that depending on your SSID's access control settings, it may not be possible to use the custom splash URL.

@name("updateNetworkSsidSplashSettings")
PUT "https://{{baseUrl}}/networks/:networkId/ssids/:number/splashSettings"
"Accept": "*/*"
"Content-Type": "application/json"
json({
    "splashUrl": "https://www.custom_splash_url.com",
    "useSplashUrl": true
})



