#!/usr/bin/env dothttp

// Transparent accounts requires the marketplace to embbed the full settlement and payout experience in their environment.
// The marketplace have all liability for these accounts.

@name("Create transparent account")
POST "https://{{url}}/v2/accounts/"
"Content-Type": "application/json"
"Authorization": "OAuth {{app_accessToken}}"
json({
    "transparentAccount": true,
    "email": {
        "address": "{{$timestamp}}@myemail.com"
    },
    "person": {
        "name": "Sales Machine da Silva",
        "taxDocument": {
            "type": "CPF",
            "number": "{{t_cpf}}"
        },
        "birthDate": "1994-03-01",
        "phone": {
            "countryCode": "55",
            "areaCode": "11",
            "number": "77121055"
        },
        "address": {
            "street": "Av. Brigadeiro Faria de Lima",
            "streetNumber": "195",
            "district": "Financial District",
            "zipcode": "79031-100",
            "city": "São Paulo",
            "state": "SP",
            "country": "BRA"
        }
    },
    "type": "MERCHANT"
})



