#!/usr/bin/env dothttp

// Uses a machine learning algorithm to detect flow anomalies.

@name("Get flow anomalies suitable for timelines")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/intelligence/anomaly_detection/timeline"
"x-net-site": "{{SITE_UUID}}"
"x-api-key": "{{API_KEY}}"
json({
    "mac": "ac:ed:5c:b7:cc:b7",
    "listname": "firehol_level1",
    "flow_list": [
        1,
        2
    ]
})


// Detailed flow metadata of a anomalies from a given day.

@name("Get detailed flow report of anomaly")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/intelligence/anomaly_detection/timeline"
"x-net-site": "{{SITE_UUID}}"
"x-api-key": "{{API_KEY}}"
json({
    "mac": "ac:ed:5c:b7:cc:b7",
    "listname": "firehol_level1",
    "flow_list": [
        1,
        2
    ]
})



