#!/usr/bin/env dothttp

// The first thing the patient does is search for their record by entering their first name, last name and date of birth.
// 
// The patient finds their record and proceeds to update it.
// 
// In this example only one result is returned. Each implementation will want to handle multiple results in their own way.

@name("Patient searches for their record")
GET "https://{{hostname}}/{{api_endpoint_path}}/Patient"
"Authorization": "Bearer {{access_token}}"
? "given"= "kristopher"
? "family"= "jensen"
? "birthdate"= "2003-01-01"
data({
    "grant_type": [
        "refresh_token"
    ],
    "refresh_token": [
        "{{refresh_token}}"
    ]
})


// The patient updates the record returned above using the kiosk. In this example, the patient moved across the street and updated their address to reflect that.
// 
// Once they have finished data entry, the kiosk makes the following call.

@name("Patient updates their record")
PUT "https://{{hostname}}/{{api_endpoint_path}}/Patient/20165"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
json({
    "resource": {
        "identifier": [
            {
                "system": "http://hl7.org/fhir/sid/us-ssn",
                "value": "123456789"
            }
        ],
        "address": [
            {
                "country": "US",
                "city": "SYRACUSE",
                "use": "home",
                "line": [
                    "124 DAVIS BLVD"
                ],
                "postalCode": "84075",
                "text": "124 DAVIS BLVD  SYRACUSE UT 84075 US",
                "state": "UT",
                "type": "physical"
            }
        ],
        "gender": "male",
        "active": true,
        "birthDate": "2003-01-01",
        "deceasedBoolean": false,
        "contact": [
            {
                "address": {
                    "country": "US",
                    "city": "CLEVELAND",
                    "use": "home",
                    "line": [
                        "123 TEST ST"
                    ],
                    "postalCode": "44101",
                    "text": "123 TEST ST  CLEVELAND OH 44101 US",
                    "state": "OH",
                    "type": "physical"
                },
                "gender": "male",
                "name": {
                    "given": [
                        "FIRST",
                        "V"
                    ],
                    "use": "usual",
                    "family": "TEST",
                    "suffix": [
                        "JR"
                    ]
                },
                "telecom": [
                    {
                        "system": "phone",
                        "use": "home",
                        "value": "(555) 555-5555"
                    }
                ],
                "relationship": [
                    {
                        "coding": [
                            {
                                "system": "http://hl7.org/fhir/v2/0131",
                                "code": "EP",
                                "display": "Emergency contact person"
                            }
                        ]
                    }
                ]
            }
        ],
        "generalPractitioner": [
            {
                "reference": "Practitioner/BOYAR"
            }
        ],
        "name": [
            {
                "given": [
                    "KRISTOPHER"
                ],
                "use": "usual",
                "family": "JENSEN"
            }
        ],
        "telecom": [
            {
                "system": "phone",
                "use": "home",
                "value": "(801) 555-5555"
            }
        ],
        "id": "20165",
        "communication": [
            {
                "language": {
                    "coding": [
                        {
                            "system": "urn:ietf:bcp:47",
                            "code": "en",
                            "display": "English"
                        }
                    ]
                },
                "preferred": true
            }
        ],
        "maritalStatus": {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/v3/MaritalStatus",
                    "code": "M",
                    "display": "Married"
                }
            ]
        },
        "resourceType": "Patient"
    }
})



