#!/usr/bin/env dothttp

// 
// Schedule D, it shows debts and obligations owed to or by the committee that are
// required to be disclosed.
// 
// 

@name("/schedules/schedule_d/")
GET "https://{{baseUrl}}/schedules/schedule_d/"
? "creditor_debtor_name"= "<string>"
? "creditor_debtor_name"= "<string>"
? "nature_of_debt"= "<string>"
? "min_amount_incurred"= "<float>"
? "max_image_number"= "<string>"
? "min_payment_period"= "<float>"
? "sort_nulls_last"= "false"
? "candidate_id"= "<string>"
? "candidate_id"= "<string>"
? "sort_null_only"= "false"
? "committee_id"= "<string>"
? "committee_id"= "<string>"
? "max_amount_incurred"= "<float>"
? "line_number"= "<string>"
? "sort_hide_null"= "false"
? "sort"= "load_date"
? "min_image_number"= "<string>"
? "per_page"= "20"
? "min_amount"= "<string>"
? "max_payment_period"= "<float>"
? "api_key"= "DEMO_KEY"
? "max_amount"= "<string>"
? "image_number"= "<string>"
? "image_number"= "<string>"
? "max_date"= "<date>"
? "page"= "1"
? "min_date"= "<date>"


// 
// Schedule D, it shows debts and obligations owed to or by the committee that are
// required to be disclosed.
// 
// 

@name("/schedules/schedule_d/:sub_id/")
GET "https://{{baseUrl}}/schedules/schedule_d/:sub_id/"
? "per_page"= "20"
? "sort"= "load_date"
? "sort_null_only"= "false"
? "api_key"= "DEMO_KEY"
? "page"= "1"
? "sort_hide_null"= "false"
? "sort_nulls_last"= "false"



