#!/usr/bin/env dothttp

// Fetch the health scores of all APs on this network

@name("Fetch the health scores of all APs on this network")
GET "https://{{baseUrl}}/networks/:networkId/wireless/devices/healthScores"
"X-Cisco-Meraki-API-Key": ""



