#!/usr/bin/env dothttp

@name("http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/list_akun_bank")
POST "http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/list_akun_bank"
"Authorization": "ffde9eac08d957bbd1bd225a8c16f7"
files(
	("id_user", "111171228163838157458")
)


@name("http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/tambah_akun_bank")
POST "http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/tambah_akun_bank"
"Authorization": "ffde9eac08d957bbd1bd225a8c16f7"
files(
	("id_user", "111171228163838157458"),
	("id_akun_bank", "KPLSIX5UJ7AI7H5T"),
	("nama_bank", "BANK MUAMALAT"),
	("kode_bank", "147"),
	("nama_pemilik_rek", "Malik Ibrahim sp"),
	("no_rek", "1234321234")
)


@name("http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/hapus_akun_bank")
POST "http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/hapus_akun_bank"
"Authorization": "ffde9eac08d957bbd1bd225a8c16f7"
files(
	("id_akun_bank", "KPRI5CNGR563IVMVC")
)


@name("http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/list_bank_indo")
POST "http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/list_bank_indo"
"Authorization": "ffde9eac08d957bbd1bd225a8c16f7"




