#!/usr/bin/env dothttp

// Create a new Tag for customizing how you track your shipments

@name("Create a New Tag")
POST "https://{{baseUrl}}/v1/tags/:tag_name"
"API-Key": "{{API_KEY}}"


// Delete a tag that is no longer needed

@name("Delete Tag")
DELETE "https://{{baseUrl}}/v1/tags/:tag_name"
"API-Key": "{{API_KEY}}"


// Change a tag name while still keeping the relevant shipments attached to it

@name("Update Tag Name")
PUT "https://{{baseUrl}}/v1/tags/:tag_name/:new_tag_name"
"API-Key": "{{API_KEY}}"



