#!/usr/bin/env dothttp

@name("Create")
POST "http://localhost/incidents"
"Content-Type": "application/json"
"Authorization": "4a9a350a"
data('{
	"title": "Caso 1",
	"description": "Detalhes do caso",
	"value": 120
}')


@name("Delete")
DELETE "http://localhost/incidents/2"
"Authorization": "4a9a350a"


@name("List")
GET "http://localhost/incidents"
? "page"= "1"



