#!/usr/bin/env dothttp

// This will run an instant HTTP test.

@name("HTTP Test")
POST "https://api.sonar.constellix.com/rest/api/test/http/1"
"x-cns-security-token": "{{token}}"
"Content-Type": "application/json"
json({
    "host": "www.google.com",
    "port": 443,
    "protocolType": "HTTPS",
    "path": "",
    "fqdn": "",
    "stringToSearch": "",
    "expectedStatusCode": 200,
    "ipVersion": "IPV4"
})


// This will run an instant Trace test.

@name("Trace Test")
POST "https://api.sonar.constellix.com/rest/api/test/trace/1"
"x-cns-security-token": "{{token}}"
"Content-Type": "application/json"
json({
    "host": "www.google.com",
    "ipVersion": "IPV4",
    "type": "UDP"
})


// This will run an instant TCP test.

@name("TCP Test")
POST "https://api.sonar.constellix.com/rest/api/test/tcp/1"
"x-cns-security-token": "{{token}}"
"Content-Type": "application/json"
json({
    "host": "www.google.com",
    "port": 80,
    "stringToSearch": "",
    "ipVersion": "IPV4",
    "stringToSend": "",
    "stringToReceive": ""
})


// This will run an instant DNS test.

@name("DNS Test")
POST "https://api.sonar.constellix.com/rest/api/test/dns/1"
"x-cns-security-token": "{{token}}"
"Content-Type": "application/json"
json({
    "host": "www.google.com",
    "nameServer": "ns2.google.com",
    "recordType": "A",
    "expectedIp": ""
})



