#!/usr/bin/env dothttp

@name("sgt")
GET "https://{{base_url}}/ers/config/sgt"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"
? "size"= "100"
? "page"= "1"
? "filter"= "name.CONTAINS.irv"
? "sortasc"= "name"
? "sortdsc"= "name"


@name("sgt/{id}")
GET "https://{{base_url}}/ers/config/sgt/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("sgt")
POST "https://{{base_url}}/ers/config/sgt"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "Sgt": {
        "name": "Printers",
        "description": "Printers",
        "value": 999,
        "generationId": "0",
        "propogateToApic": true
    }
})


@name("🚧 sgt/{id}")
PUT "https://{{base_url}}/ers/config/sgt/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("sgt/{id}")
DELETE "https://{{base_url}}/ers/config/sgt/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 sgt/bulk/submit")
PUT "https://{{base_url}}/ers/config/sgt/bulk/submit"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("🚧 sgt/bulk/{bulkid}")
GET "https://{{base_url}}/ers/config/sgt/bulk/{{bulkid}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"



