#!/usr/bin/env dothttp

@name("Allows you to retrieve users")
GET "https://{{baseUrl}}/Users"
"If-Modified-Since": "<dateTime>"
"xero-tenant-id": "<string>"
? "where"= "<string>"
? "order"= "<string>"


@name("Allows you to retrieve a specified user")
GET "https://{{baseUrl}}/Users/:UserID"
"xero-tenant-id": "<string>"



