#!/usr/bin/env dothttp

// This request retrieves a middle name from database. No filtering takes place.

@name("get a ramdom middle name")
GET "https://{{server}}/{{api}}/name/middle"


// This request retrieves a middle name from database. nationality is canadian

@name("get a ramdom middle name from Canada")
GET "https://{{server}}/{{api}}/name/middle"
? "nationalities"= "Canadian"


// This request retrieves a middle name from database. nationality is canadian

@name("get a ramdom middle name from wrong nationality")
GET "https://{{server}}/{{api}}/name/middle"
? "nationalities"= "Canadian2"



