#!/usr/bin/env dothttp

@name("Macro Usage Share")
GET "https://{{host}}/services/data/v47.0/sobjects/MacroUsageShare/"


@name("Macro Usage Share Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/MacroUsageShare/{ID}/"


@name("Describe Macro Usage Share")
GET "https://{{host}}/services/data/v47.0/sobjects/MacroUsageShare/describe/"



