#!/usr/bin/env dothttp

// ### Step 3: Generate Access Token and Refresh Token// // OAuth2.0 requests are usually authenticated with an **access token**, which is passed as bearer token. To use this access token, you need to construct a normal HTTP request and include it in an Authorization header along with the value of Bearer.
@name("Generate Access Token and Refresh Token")
POST "https://{{accounts-url}}/oauth/v2/token"
files(
	("client_id", "{{client-id}}"),
	("client_secret", "{{client-secret}}"),
	("redirect_uri", "{{redirect-uri}}"),
	("code", "paste_grant_token_here"),
	("grant_type", "authorization_code")
)


// ### Step 4: Refresh Access Tokens// // As obvious as it is, refresh tokens are used to generate new access tokens when the current ones are past the expiry time.
@name("Refresh Access Tokens")
POST "https://{{accounts-url}}/oauth/v2/token"
files(
	("client_id", "{{client-id}}"),
	("client_secret", "{{client-secret}}"),
	("refresh_token", "{{refresh-token}}"),
	("grant_type", "refresh_token")
)


// ### Step 5: Revoking Tokens// // In case if you wish to revoke the refresh_token, use the below approach.
@name("Revoking Tokens")
POST "https://{{accounts-domain}}/oauth/v2/token/revoke"
files(
	("token", "{{refresh-token}}")
)



