#!/usr/bin/env dothttp

@name("Get all available locations for a root tenant")
GET "https://{{base_url}}/api/2/tenants/{{my_tenant_id}}/locations"


@name("Get all available storages for a root tenant")
GET "https://{{base_url}}/api/2/tenants/{{my_tenant_id}}/infra"


@name("Get locarions for a partner tenant")
GET "https://{{base_url}}/api/2/tenants/{{partner_tenant_id}}/locations"
"Content-Type": "application/json"



@name("Get batch locations info by uuids")
GET "https://{{base_url}}/api/2/locations"
? "uuids"= "{{location_uuids}}"


@name("Get a location info by uuid")
GET "https://{{base_url}}/api/2/locations/{{location_uuid}}"


@name("Get an infrastructure info by uuid")
GET "https://{{base_url}}/api/2/infra/{{infra_uuid}}"


@name("Get batch storages info by uuids")
GET "https://{{base_url}}/api/2/infra"
? "uuids"= "{{infra_uuids}}"



