#!/usr/bin/env dothttp

// OAuth required scopes: OR.Robots or OR.Robots.Read.
// 
// Required permissions: Environments.View.

@name("Gets a single environment.")
GET "https://{{baseUrl}}/odata/Environments({{key}})"
"X-UIPATH-OrganizationUnitId": "12575632"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"


// OAuth required scopes: OR.Robots or OR.Robots.Write.
// 
// Required permissions: Environments.Edit.

@name("Updates an environment.")
PUT "https://{{baseUrl}}/odata/Environments({{key}})"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
json({
    "Name": "sint sit",
    "Description": "nisi",
    "Robots": [
        {
            "HostingType": "Standard",
            "Name": "ullamco non",
            "Type": "RpaDeveloperPro",
            "Username": "velit ad pariatur Ut",
            "LicenseKey": "commodo amet",
            "MachineName": "et sunt cillum",
            "MachineId": -90154765,
            "ExternalName": "mollit ut tempor qui",
            "Description": "non deserunt et pariatur commodo",
            "ProvisionType": "Automatic",
            "Password": "do culpa",
            "CredentialStoreId": -98283964,
            "UserId": 58570028,
            "Enabled": true,
            "CredentialType": "Default",
            "Environments": [
                {
                    "value": "<Circular reference to #/components/schemas/EnvironmentDto detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/EnvironmentDto detected>"
                }
            ],
            "RobotEnvironments": "cupida",
            "ExecutionSettings": {},
            "IsExternalLicensed": true,
            "LimitConcurrentExecution": false,
            "Id": 99851773
        },
        {
            "HostingType": "Standard",
            "Name": "in commo",
            "Type": "StudioPro",
            "Username": "deserunt culpa ullamco officia",
            "LicenseKey": "tempor nulla aute",
            "MachineName": "veniam elit commodo tempor",
            "MachineId": -73643884,
            "ExternalName": "laboris eu cupidatat",
            "Description": "sed",
            "ProvisionType": "Automatic",
            "Password": "ipsum veniam laboris minim",
            "CredentialStoreId": -40191854,
            "UserId": -4872114,
            "Enabled": false,
            "CredentialType": "NCipher",
            "Environments": [
                {
                    "value": "<Circular reference to #/components/schemas/EnvironmentDto detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/EnvironmentDto detected>"
                }
            ],
            "RobotEnvironments": "ipsum in minim",
            "ExecutionSettings": {},
            "IsExternalLicensed": true,
            "LimitConcurrentExecution": false,
            "Id": -6196883
        }
    ],
    "Type": "Test",
    "Id": -19191780
})


// OAuth required scopes: OR.Robots or OR.Robots.Write.
// 
// Required permissions: Environments.Delete.

@name("Deletes an environment.")
DELETE "https://{{baseUrl}}/odata/Environments({{key}})"
"X-UIPATH-OrganizationUnitId": "12575632"


// OAuth required scopes: OR.Robots or OR.Robots.Write.
// 
// Required permissions: Environments.Edit.

@name("Associates a robot with the given environment.")
POST "https://{{baseUrl}}/odata/Environments({{key}})/UiPath.Server.Configuration.OData.AddRobot"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
json({
    "robotId": "proident eu laboris"
})


// OAuth required scopes: OR.Robots or OR.Robots.Write.
// 
// Required permissions: Environments.Edit.

@name("Dissociates a robot from the given environment.")
POST "https://{{baseUrl}}/odata/Environments({{key}})/UiPath.Server.Configuration.OData.RemoveRobot"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
json({
    "robotId": "proident eu laboris"
})


// OAuth required scopes: OR.Robots or OR.Robots.Write.
// 
// Required permissions: Environments.Edit.

@name("Associates a group of robots with and dissociates another group of robots from the given environment.")
POST "https://{{baseUrl}}/odata/Environments({{key}})/UiPath.Server.Configuration.OData.SetRobots"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
json({
    "addedRobotIds": [
        17136352,
        -11977032
    ],
    "removedRobotIds": [
        35249930,
        28015900
    ]
})



