#!/usr/bin/env dothttp

// <p>Returns a list of secure passwords. Can optionally sort the resulting list in ascending or
//  descending order. Other params given will be used as search values.</p>
//  <p class="italicize">Examples:</p>
//  <div class="code indent"><pre>/restman/1.0/passwords?name=MyPassword</pre></div>
//  <p>Returns secure password with name "MyPassword".</p>
//  <div class="code indent"><pre>/restman/1.0/passwords?type=Password&name=MyPassword&name=MyOtherPassword</pre></div>
//  <p>Returns secure password of Password ty

@name("List All Secure Passwords")
GET "https://{{baseUrl}}/1.0/passwords"
? "sort"= "<string>"
? "order"= "<string>"
? "name"= "<array>"
? "type"= "<array>"


// Returns a template, which is an example secure password that can be used as a reference for what secure password
//  objects should look like.
// Template

@name("Secure Passwords Template")
GET "https://{{baseUrl}}/1.0/passwords/template"


// Returns a secure password with the given ID.
// Get

@name("List Secure Passwords By ID")
GET "https://{{baseUrl}}/1.0/passwords/:id"



