#!/usr/bin/env dothttp

@name("Owned Content Document")
GET "https://{{host}}/services/data/v47.0/sobjects/OwnedContentDocument/"


@name("Owned Content Document Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/OwnedContentDocument/{ID}/"


@name("Describe Owned Content Document")
GET "https://{{host}}/services/data/v47.0/sobjects/OwnedContentDocument/describe/"



