#!/usr/bin/env dothttp

// Events are our way of letting you know when something interesting happens in your organization or more specifically, inside one of your sites.

@name("List all events")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/event/events"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"
"x-net-user": "{{USER_UUID}}"
? "filter_event_categories"= "[0]"
? "filter_event_basename"= "agent.online"
? "filter_event_severity"= "5"


// Acknowledge (and possibly sleep) an event.

@name("Acknowledge an event")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/event/events/acknowledge"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"
"x-net-user": "{{USER_UUID}}"
? "ids[0]"= "35"
? "user_id"= "{{USER_ID}}"
? "supress"= "0"


// Events types are pre-defined definitions of events that can be identified on a network.

@name("List all events types")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/event/types"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"


// Events types are pre-defined definitions of events that can be identified on a network.
// 
// Since Netify subscribership is opt-out based, this endpoint provides a collection of data that represents which subscribers have chosen to opt out of receiving information on certain event types.

@name("List all subscribers")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/event/subscribers"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"
"x-net-user": "{{USER_UUID}}"


// Update a mobile device registered on the Netify Informatics cloud.

@name("Mobile device ping")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/event/mobile/{{DUID}}/ping"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"
"x-net-user": "{{USER_UUID}}"
? "user_id"= "3527e2f201c7ed8ee97f94d4158d5f16:fd4d7b90a2078ac28c4c84b17b97390a"
? "token"= "{{FIREBASE_TOKEN}}"
? "label"= "Android 3a"



