#!/usr/bin/env dothttp

@name("Get entities from CandidateBackground_TalentPoolcorp")
GET "https://{{baseUrl}}/CandidateBackground_TalentPoolcorp"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
? "$top"= "20"
? "$skip"= "26126779"
? "$search"= "exercitation mollit reprehenderit ad"
? "$filter"= "exercitation mollit reprehenderit ad"
? "$count"= "true"
? "$orderby"= "lastModifiedDateTime,bgOrderPos desc"
? "$select"= "talentPoolStatus,bgOrderPos"
? "$expand"= "candidate,*"


@name("Add new entity to CandidateBackground_TalentPoolcorp")
POST "https://{{baseUrl}}/CandidateBackground_TalentPoolcorp"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
"Content-Type": "application/json"
data('{
    "backgroundElementId": "ipsum cupidatat anim fugiat",
    "bgOrderPos": "est nulla",
    "candidateId": "officia velit id",
    "lastModifiedDateTime": "/Date(1492098664000)/",
    "startDate": "/Date(1492098664000)/",
    "talentPoolComments": "Duis dolor velit deserunt",
    "talentPoolStatus": "sed amet consequat fugiat do",
    "talentPoolitemCorp": "ullamco",
    "candidate": {
        "address": "pariatur reprehenderit in deserunt officia",
        "address2": "consectetur",
        "agreeToPrivacyStatement": "ea dolor",
        "anonymized": "nisi aliquip",
        "anonymizedDateTime": "/Date(1492098664000)/",
        "candidateId": "laboris occaecat consequat ipsum",
        "candidateLocale": "aliqua",
        "cellPhone": "aliquip ",
        "city": "est",
        "contactEmail": "volupta",
        "country": "in aliqua dolore tempor laborum",
        "creationDateTime": "/Date(1492098664000)/",
        "currentTitle": "non nisi dolor incididunt",
        "dataPrivacyId": "cupidatat dolor adip",
        "dateofAvailability": "/Date(1492098664000)/",
        "externalCandidate": false,
        "firstName": "sit",
        "homePhone": "par",
        "lastLoginDateTime": "/Date(1492098664000)/",
        "lastModifiedDateTime": "/Date(1492098664000)/",
        "lastName": "ut ipsum dolor ex quis",
        "middleName": "culpa",
        "partnerMemberId": "deserunt dolore tempor",
        "partnerSource": "adipisicing Lorem aliqua",
        "password": "officia magna fugiat nulla adipisicing",
        "primaryEmail": "pariatur anim Duis",
        "privacyAcceptDateTime": "/Date(1492098664000)/",
        "publicIntranet": true,
        "shareProfile": "dolore cillum laborum sunt et",
        "usersSysId": "sunt veniam in",
        "visibilityOption": true,
        "zip": "ut amet incididunt",
        "candidateProfileExtension": {
            "candidateId": "mollit veniam",
            "createdBy": "fugiat cupidatat Excepteur aliqua",
            "createdDateTime": "/Date(1492098664000)/",
            "lastModifiedBy": "ipsum in est",
            "lastModifiedDateTime": "/Date(1492098664000)/",
            "mdfSystemRecordStatus": "quis incididunt et"
        },
        "certificates": {
            "results": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ]
        },
        "education": {
            "results": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ]
        },
        "insideWorkExperience": {
            "results": [
                {
                    "value": "<Circular reference to #/components/schemas/SFOData.CandidateBackground_InsideWorkExperience detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/SFOData.CandidateBackground_InsideWorkExperience detected>"
                }
            ]
        },
        "languages": {
            "results": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ]
        },
        "outsideWorkExperience": {
            "results": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ]
        },
        "tags": {
            "results": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ]
        },
        "talentPool": {
            "results": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ]
        },
        "talentPoolcorp": {
            "results": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ]
        }
    }
}')



