#!/usr/bin/env dothttp

@name("Flow Interview")
GET "https://{{host}}/services/data/v47.0/sobjects/FlowInterview/"


@name("Flow Interview Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/FlowInterview/{ID}/"


@name("Describe Flow Interview")
GET "https://{{host}}/services/data/v47.0/sobjects/FlowInterview/describe/"



