#!/usr/bin/env dothttp

// <h3>This API can be used to verify Voter ID</h3>
// 
// ## REQUEST JSON
// 
// ### Body Params
// 
// * epic_no(require) - Voter ID Number
// * consent(require) - Consent of the end user to get their information for verification purpose
// * consent_text(require) - Purpose for which user has given their consent
// 
// <em>Request timeout: 1 minute</em>
// 
// ## OUTPUT
// 
// <h4>Transaction successful</h4>
// 
// ```
// {
//     "env": 1,
//     "id": "2c63b3cf-75bc-444a-b49c-e8b36a91cac0",
//     "request_timestamp": "2019-12-20 11:55:10:810 +05:30",
//     "response_code": "101",
//     "response_msg": "Success",
//     "response_timestamp": "2019-12-20 11:55:21:717 +05:30",
//     "result": {
//         "ac_name": "Vikasnagar",
//         "ac_name_v1": "विकासनगर",
//         "ac_no": "16",
//         "age": 24,
//         "dist_name_v1": "देहरादून",
//         "district": "Dehradun",
//         "district_code": "13",
//         "email_id": "",
//         "epic_no": "NRB0399436",
//         "gender": "M",
//         "house_no": "278A",
//         "id": "S280160053010315",
//         "last_update": "Tue Jun 18 22:17:20 IST 2019",
//         "mob_no": "9412975205",
//         "name": "Mohak Talwal ",
//         "name_v1": "मोहक तलवाल  ",
//         "name_v2": "",
//         "name_v3": "",
//         "part_name": "Vikasnagar  West Part R.No.3",
//         "part_name_v1": "विकासनगर पश्‍चिम भाग क.नं.3",
//         "part_no": "53",
//         "pc_name": "Tehri Garhwal",
//         "pc_name_v1": "टिहरी गढ़वाल",
//         "pc_no": "1",
//         "ps_lat_long": "30.42012,77.68142",
//         "ps_lat_long_0_coordinate": 30.42012,
//         "ps_lat_long_1_coordinate": 77.68142,
//         "ps_name": "Shri Hoshira Singh Buddhumal Jain Girls Inter College vikasnagar,  p.o. vikasnagar,teshil- vikasnagar. district- dehradun 248198",
//         "ps_name_v1": "श्री होशियार सिंह बुद्धुमल्‍ल जैन बालिका  इण्‍टर कालेज विकासनगर, पो0 ओ0 विकासनगर,  तहसील- विकासनगर, जिला- देहरादून 248198",
//         "ps_no": "53",
//         "rln_name": "Naresh Talwar ",
//         "rln_name_v1": "नरेश तलवार  ",
//         "rln_name_v2": "",
//         "rln_name_v3": "",
//         "rln_type": "F",
//         "section_no": "1",
//         "slno_inpart": "315",
//         "st_code": "S28",
//         "state": "Uttarakhand",
//         "status": "N"
//     },
//     "transaction_status": 1
// }
// ```
// 
// <h4>Transaction failure</h4>
// 
// ```
// {
//     "id": "<< Transaction ID >>",
//     "response_code": "102",
//     "env": 1,
//     "request_timestamp": "2018-09-19 18:08:55:947 +05:30",
//     "response_timestamp": "2018-09-19 18:08:57:366 +05:30",
//     "response_msg": "Invalid ID number or combination of inputs"
// }
// ```
// <br>

@name("Verification API")
POST "https://{{base_url}}/verify-voter/v2"
"Content-Type": "application/json"
"qt_api_key": "{{qt_api_key_value}}"
"qt_agency_id": "{{qt_agency_id}}"
data('{
    "epic_no":"<< Voter Id Number >>",
    "consent":"<< Y or N >>",
    "consent_text":"<< Consent Message >>"
} ')



