#!/usr/bin/env dothttp

@name("Custom Object User License Metrics")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomObjectUserLicenseMetrics/"


@name("Custom Object User License Metrics Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomObjectUserLicenseMetrics/{ID}/"


@name("Describe Custom Object User License Metrics")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomObjectUserLicenseMetrics/describe/"



