#!/usr/bin/env dothttp

// Get an `shipment` from the WMS platform by their `Id`.
// 
// <!--
// ### Sample Response
// ```
// {
//       "get": {
//         "summary": "Find a single order by orderid",
//         "description": "",
//         "operationId": "getorder",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": " order",
//             "in": "path",
//             "description": " order to retrieve",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/ orderDTO"
//             }
//           }
//         }
//       },
//       "post": {
//         "summary": "get hold reasons",
//         "description": "",
//         "operationId": "getHoldReasons",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": "order",
//             "in": "path",
//             "description": "order to use",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/orderDTO"
//             }
//           }
//         }
//       }
//     }
// ```
// -->

@name("Shipment by Id")
GET "https://wms.slg.com/scprd/wmwebservice_rest/orders/{orderid}"
"Content-Type": "application/json"
"Authorization": "Barear Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
data('{
   "orderId": 000223
}')



