#!/usr/bin/env dothttp

// List the events for the network
@name("List The Events For The Network")
GET "https://{{baseUrl}}/networks/:networkId/events"
"X-Cisco-Meraki-API-Key": ""
? "productType"= "{{productType}}"
? "includedEventTypes[]"= "{{includedEventTypes[]}}"
? "excludedEventTypes[]"= "{{excludedEventTypes[]}}"
? "deviceMac"= "{{deviceMac}}"
? "deviceSerial"= "{{deviceSerial}}"
? "deviceName"= "{{deviceName}}"
? "clientIp"= "{{clientIp}}"
? "clientMac"= "{{clientMac}}"
? "clientName"= "{{clientName}}"
? "smDeviceMac"= "{{smDeviceMac}}"
? "smDeviceName"= "{{smDeviceName}}"
? "perPage"= "{{perPage}}"
? "startingAfter"= "{{startingAfter}}"
? "endingBefore"= "{{endingBefore}}"



