#!/usr/bin/env dothttp

// Lists addresses for an account.
// 
// *Important*: Addresses should be considered one time use only.

@name("List addresses")
GET "https://{{baseUrl}}/accounts/:account_id/addresses"



