#!/usr/bin/env dothttp

@name("/save_pbf_leads_step_1")
POST "http://localhost/save_pbf_leads_step_1"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('{	
   "submission_id": "6F8F40FA-68A8-49A0-B7E6-2E38CD08DA38",
   "name" : "Febrianto",
   "email": "febrielven@gmail.com",
   "phone_number" : "081268526827",
   "dob":"1992-02-23",
   "profession_id":"C8BE940A-820B-4CA7-BB75-E349197C1ED9",
   "salary":30000000,
   "path_ktp":"test"
}
')


@name("/get_profession")
GET "http://www.bficorporatedev.com/get_profession"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")


@name("/save_pbf_leads_step_2")
POST "http://localhost/save_pbf_leads_step_2"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('
{
   "submission_id" : "C02BE9F4-8769-49B9-AB58-34BF54A526AA",
   "province_id" : "B8E13A16-D951-40B9-A1AF-A7D25AF70F54",
   "city_id" : "C9560C69-C60F-46CC-8EBA-F5928645306C",
   "district_id" : "613FC85B-DFE2-4E96-9513-A4192ABE08B5",
   "subdistrict_id" : "0CE84354-C449-4055-B43C-D45D5D0155CB",
   "zipcode_id" : "AA7AB2F4-4AD1-4335-AAA5-02186F5CE4DD",
   "address" : "jln. Belimbing no 3 Jakarta Selatan Motor"
}
')


@name("/get_list_pbf_property_type")
GET "http://localhost/get_list_pbf_property_type"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")


@name("/save_pbf_leads_step_3")
POST "http://localhost/save_pbf_leads_step_3"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('
{
   "submission_id" : "C02BE9F4-8769-49B9-AB58-34BF54A526AA",
   "province_id" : "B8E13A16-D951-40B9-A1AF-A7D25AF70F54",
   "city_id" : "C9560C69-C60F-46CC-8EBA-F5928645306C",
   "district_id" : "613FC85B-DFE2-4E96-9513-A4192ABE08B5",
   "subdistrict_id" : "0CE84354-C449-4055-B43C-D45D5D0155CB",
   "zipcode_id" : "AA7AB2F4-4AD1-4335-AAA5-02186F5CE4DD",
   "address" : "jln. Belimbing no 3 Jakarta Selatan Motor",
   "certificate_type_id":"D5414B1E-E3FD-49B2-9CAD-E4D1DA8FF9C9",
   "certificate_on_behalf_id":"D50B7418-A880-4B68-98BE-D927CE62620F",
   "property_type_id":"F7FEAB3C-0246-4272-8677-A3DC614A1DFE",
   "is_dihuni":false
}
')


@name("/get_pbf_funding")
POST "http://localhost/get_pbf_funding"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('{
   "submission_id" : "C02BE9F4-8769-49B9-AB58-34BF54A526AA",
   "estimasi_harga":80000000
}')


@name("/get_list_pbf_certificate_type")
GET "http://localhost/get_list_pbf_certificate_type"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")


@name("/get_pbf_tenor_list")
POST "http://localhost/get_pbf_tenor_list"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('{
   "submission_id" : "C02BE9F4-8769-49B9-AB58-34BF54A526AA"
}')


@name("http://localhost:4000/pbf_calculate")
POST "http://localhost/pbf_calculate"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('{
   "submission_id" : "C02BE9F4-8769-49B9-AB58-34BF54A526AA",
   "tenor":24,
   "funding":80000000
}')


@name("/save_pbf_leads_step_4")
POST "http://localhost/save_pbf_leads_step_4"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('
{
   "submission_id" : "C02BE9F4-8769-49B9-AB58-34BF54A526AA"
}
')


@name("/save_pbf_leads_step_5")
POST "http://localhost/save_pbf_leads_step_5"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('
{
   "submission_id" : "C02BE9F4-8769-49B9-AB58-34BF54A526AA"
}
')


@name("http://localhost:4000/save_pbf_leads_step_6")
POST "http://localhost/save_pbf_leads_step_6"
basicauth("userapi.bfi.co.id", "D1g1t4l4p1")
"Content-Type": "application/json"
data('
{
   "submission_id" : "C02BE9F4-8769-49B9-AB58-34BF54A526AA"
}
')



