#!/usr/bin/env dothttp

@name("Authorization Form Data Use History")
GET "https://{{host}}/services/data/v47.0/sobjects/AuthorizationFormDataUseHistory/"


@name("Authorization Form Data Use History Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/AuthorizationFormDataUseHistory/{ID}/"


@name("Describe Authorization Form Data Use History")
GET "https://{{host}}/services/data/v47.0/sobjects/AuthorizationFormDataUseHistory/describe/"



