#!/usr/bin/env dothttp

@name("READ Application Role Assignments")
GET "https://{{apiPath}}/environments/{{envID}}/applications/{{appID}}/roleAssignments"


@name("CREATE Application Role Assignments")
POST "https://{{apiPath}}/environments/{{envID}}/applications/{{appID}}/roleAssignments"
"Content-Type": "application/json"
data('{
    "role": {
        "id": "{{roleID}}"
    },
    "scope": {
        "id": "{{envID}}",
        "type": "ENVIRONMENT"
    }
}')


@name("READ One Application Role Assignment")
GET "https://{{apiPath}}/environments/{{envID}}/applications/{{appID}}/roleAssignments/{{roleAssignmentID}}"


@name("DELETE Application Role Assignment")
DELETE "https://{{apiPath}}/environments/{{envID}}/applications/{{appID}}/roleAssignments/{{roleAssignmentID}}"




