#!/usr/bin/env dothttp

// Send the user an email with a link to create account in company
// 
// The headers Authorization and Referer in the method at least one must be informed, depending on the origin of the call, if the method is called from the WEB by default the browser will inform the Referer or if the method is called from an M2M integration the method has to inform the company token in Authorization

@name("Invite user")
POST "https://{{KNOWLEDGE_BASE_URL}}/workspace/v1/invites"
"Authorization": "{{TOKEN}}"
"Referer": "{{DOMAIN_REFERER}}"
json({
    "credential": "jose+901@skore.io",
    "company_id": 114
})



