#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List provisioned SCIM groups for an enterprise")
GET "https://{{baseUrl}}/scim/v2/enterprises/{{enterprise}}/Groups"
? "startIndex"= "56334219"
? "count"= "56334219"
? "filter"= "aliqua consectetur elit incididu"
? "excludedAttributes"= "aliqua consectetur elit incididu"


@name("Provision a SCIM enterprise group and invite users")
POST "https://{{baseUrl}}/scim/v2/enterprises/{{enterprise}}/Groups"
"Content-Type": "application/json"
json({
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:Group"
    ],
    "displayName": "octo-org",
    "members": [
        {
            "value": "92b58aaa-a1d6-11ea-8227-b9ce9e023ccc"
        },
        {
            "value": "aaaa8c34-a6b2-11ea-9d70-bbbbbd1c8fd5"
        }
    ]
})



