#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Project Role For Project")
GET "https://{{baseUrl}}/rest/api/3/project/:projectIdOrKey/role/:id"


@name("Set Actors For Project Role")
PUT "https://{{baseUrl}}/rest/api/3/project/:projectIdOrKey/role/:id"
"Content-Type": "application/json"
data('{
    "categorisedActors": "<object>"
}')


@name("Add Actors To Project Role")
POST "https://{{baseUrl}}/rest/api/3/project/:projectIdOrKey/role/:id"
"Content-Type": "application/json"
data('{
    "user": [
        "<string>",
        "<string>"
    ],
    "group": [
        "<string>",
        "<string>"
    ]
}')


@name("Delete Actors From Project Role")
DELETE "https://{{baseUrl}}/rest/api/3/project/:projectIdOrKey/role/:id"
? "user"= "<string>"
? "group"= "<string>"



