#!/usr/bin/env dothttp

@name("Apex Email Notification")
GET "https://{{host}}/services/data/v47.0/sobjects/ApexEmailNotification/"


@name("Apex Email Notification Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/ApexEmailNotification/{ID}/"


@name("Describe Apex Email Notification")
GET "https://{{host}}/services/data/v47.0/sobjects/ApexEmailNotification/describe/"



