#!/usr/bin/env dothttp

@name("Get asset by token")
GET "https://{{baseUrl}}/assets/:assetToken"
"Authorization": ""


@name("Update an existing hardware asset in category")
PUT "https://{{baseUrl}}/assets/:assetToken"
"Authorization": ""
"Content-Type": "application/json"
json({
    "assetTypeToken": "<string>",
    "backgroundColor": "<string>",
    "borderColor": "<string>",
    "foregroundColor": "<string>",
    "icon": "<string>",
    "imageUrl": "<string>",
    "metadata": "<object>",
    "name": "<string>",
    "token": "<string>"
})


@name("Delete asset by token")
DELETE "https://{{baseUrl}}/assets/:assetToken"
"Authorization": ""


@name("Get label for area")
GET "https://{{baseUrl}}/assets/:assetToken/label/:generatorId"
"Authorization": ""



