#!/usr/bin/env dothttp

// Retrieves the account's current balance.

@name("Return the current balance")
GET "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/shopify_payments/balance.json"
"Content-Type": "application/json"



