#!/usr/bin/env dothttp

// Get themes, social providers, auth providers, and event listeners available on this server

@name("Get all  [SAT]")
GET "https://{{keycloak_url}}/admin/realms/{{realm}}"
"Content-Type": "application/json"



