#!/usr/bin/env dothttp

@name("Button - URL")
POST "https://{{url}}/{{apiVersion}}/api/whatsapp/{{appId}}/notification"
"Content-Type": "application/json"
"Authorization": "Bearer {{jwt}}"
json({
    "storage": "full",
    "destination": {
        "integrationId": "{{integrationId}}",
        "destinationId": "{{phone}}"
    },
    "author": {
        "name": "{{authorName}}",
        "email": "{{authorEmail}}",
        "role": "appMaker"
    },
    "messageSchema": "whatsapp",
    "message": {
        "type": "template",
        "template": {
            "namespace": "{{templateNamespace}}",
            "name": "{{your_template_name}}",
            "language": {
                "policy": "deterministic",
                "code": "en"
            },
            "components": [
                {
                    "type": "body",
                    "parameters": [
                        {
                            "type": "text",
                            "text": "Parameter 1"
                        },
                        {
                            "type": "text",
                            "text": "Parameter 2"
                        },
                        {
                            "type": "text",
                            "text": "Parameter 3"
                        }
                    ]
                },
                {
                    "type": "button",
                    "sub_type": "url",
                    "index": "0",
                    "parameters": [
                        {
                            "type": "text",
                            "text": "9rwnB8RbYmPF5t2Mn09x4h"
                        }
                    ]
                }
            ]
        }
    }
})


@name("Button - Quick Reply")
POST "https://{{url}}/{{apiVersion}}/api/whatsapp/{{appId}}/notification"
"Content-Type": "application/json"
"Authorization": "Bearer {{jwt}}"
json({
    "storage": "full",
    "destination": {
        "integrationId": "{{integrationId}}",
        "destinationId": "{{phone}}"
    },
    "author": {
        "name": "{{authorName}}",
        "email": "{{authorEmail}}",
        "role": "appMaker"
    },
    "messageSchema": "whatsapp",
    "message": {
        "type": "template",
        "template": {
            "namespace": "{{templateNamespace}}",
            "name": "{{your_template_name}}",
            "language": {
                "policy": "deterministic",
                "code": "en"
            },
            "components": [
                {
                    "type": "body",
                    "parameters": [
                        {
                            "type": "text",
                            "text": "Parameter 1"
                        },
                        {
                            "type": "text",
                            "text": "Parameter 2"
                        },
                        {
                            "type": "text",
                            "text": "Parameter 3"
                        }
                    ]
                },
                {
                    "type": "button",
                    "sub_type": "quick_reply",
                    "index": "0",
                    "parameters": [
                        {
                            "type": "payload",
                            "payload": "aGlzIHRoaXMgaXMgY29vZHNhc2phZHdpcXdlMGZoIGFTIEZISUQgV1FEV0RT"
                        }
                    ]
                },
                {
                    "type": "button",
                    "sub_type": "quick_reply",
                    "index": "1",
                    "parameters": [
                        {
                            "type": "payload",
                            "payload": "aGlzIHRoaXMgaXMgY29vZHNhc2phZHdpcXdlMGZoIG951"
                        }
                    ]
                },
                {
                    "type": "button",
                    "sub_type": "quick_reply",
                    "index": "2",
                    "parameters": [
                        {
                            "type": "payload",
                            "payload": "aGlzIHRoaXMgaXMgY29vZHNhc2phZHdpcXdlMGZoIG753"
                        }
                    ]
                }
            ]
        }
    }
})



