#!/usr/bin/env dothttp

// Imports a CSV or xlsx file to store products.
// accepts a file, a dropbox folder link for images, and has an option `delete_old_products` to delete all store previous products upon successful import.

@name("Import Products")
POST "https://{{api_url}}/products/import/"
"Authorization": "{{Authorization}}"
"STORE-ID": "{{STORE_ID}}"
"ROLE": "Manager"
"Content-Type": "application/x-www-form-urlencoded"
"Access-Token": "{{X-MANAGER-TOKEN}}"
"response_type": "application/json"
? "url_ending"= "Hr1R7"
files(
	("file", "None"),
	("folder_link", ""),
	("delete_old_products", "true"),
	("response_type", "json")
)



