#!/usr/bin/env dothttp

// You must be a system administrator or have radius administrator permissions.
@name("{{baseUrl}}/Radius/GetClients")
POST "https://{{baseUrl}}/Radius/GetClients"
? "isQueryResponse"= "<string>"


// You must be a system administrator or have radius administrator permissions.  Will return null if//             connector has no radius config.
@name("{{baseUrl}}/Radius/GetConfig")
POST "https://{{baseUrl}}/Radius/GetConfig"
? "connectorUuid"= "<string>"


@name("{{baseUrl}}/Radius/GetServers")
POST "https://{{baseUrl}}/Radius/GetServers"


@name("{{baseUrl}}/Radius/GetUserIdentifierAttributes")
POST "https://{{baseUrl}}/Radius/GetUserIdentifierAttributes"


// You must be a system administrator or have radius administrator permissions.
@name("{{baseUrl}}/Radius/RemoveClients")
POST "https://{{baseUrl}}/Radius/RemoveClients"
"Content-Type": "application/json"
data('{
    "clients": [
        "<object>",
        "<object>"
    ]
}')


@name("{{baseUrl}}/Radius/RemoveServers")
POST "https://{{baseUrl}}/Radius/RemoveServers"
"Content-Type": "application/json"
data('{
    "HostAddress": [
        "<string>",
        "<string>"
    ]
}')


// You must be a system administrator or have radius administrator permissions.  When updating an existing client,//             any properties not provided in the body will retain the existing values.  ClientSecret and ClientName are//             required on all new clients.
@name("{{baseUrl}}/Radius/SetClient")
POST "https://{{baseUrl}}/Radius/SetClient"
"Content-Type": "application/json"
data('{
    "ClientAddress": "<string>",
    "ClientCulture": "<string>",
    "ClientName": "<string>",
    "ClientDescription": "<string>",
    "ClientSecret": "<string>",
    "ClientAllowNewLinesInPrompts": "<boolean>"
}')


// You must be a system administrator or have radius administrator permissions.
@name("{{baseUrl}}/Radius/SetConfig")
POST "https://{{baseUrl}}/Radius/SetConfig"
"Content-Type": "application/json"
data('{
    "Port": "<integer>",
    "connectorUuid": "<string>",
    "ReceiveTimeout": "<integer>"
}')


@name("{{baseUrl}}/Radius/SetServer")
POST "https://{{baseUrl}}/Radius/SetServer"
"Content-Type": "application/json"
data('{
    "HostDescription": "<string>",
    "HostDisplayName": "<string>",
    "UserIdSubstAttr": "<integer>",
    "HostAddress": "<string>",
    "HostCustomPromptMechChosen": "<string>",
    "HostSharedSecret": "<string>",
    "UserIdCustomSubstAttrName": "<string>",
    "HostPort": "<integer>",
    "ReceiveTimeout": "<integer>",
    "MaxAttempts": "<integer>"
}')



