#!/usr/bin/env dothttp

@name("Permission Set Tab Setting")
GET "https://{{host}}/services/data/v47.0/sobjects/PermissionSetTabSetting/"


@name("Permission Set Tab Setting Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/PermissionSetTabSetting/{ID}/"


@name("Describe Permission Set Tab Setting")
GET "https://{{host}}/services/data/v47.0/sobjects/PermissionSetTabSetting/describe/"



