#!/usr/bin/env dothttp

@name("Note And Attachment")
GET "https://{{host}}/services/data/v47.0/sobjects/NoteAndAttachment/"


@name("Note And Attachment Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/NoteAndAttachment/{ID}/"


@name("Describe Note And Attachment")
GET "https://{{host}}/services/data/v47.0/sobjects/NoteAndAttachment/describe/"



