#!/usr/bin/env dothttp

// OAuth required scopes: OR.Queues or OR.Queues.Read.
// 
// Required permissions: Queues.View.

@name("Gets the list of queue definitions.")
GET "https://{{baseUrl}}/odata/QueueDefinitions"
"X-UIPATH-OrganizationUnitId": "12575632"
? "mandatoryPermissions"= "enim officia ut oc"
? "mandatoryPermissions"= "quis ex ullamco sit"
? "atLeastOnePermissions"= "enim officia ut oc"
? "atLeastOnePermissions"= "quis ex ullamco sit"
? "$expand"= "esse sit qui"
? "$filter"= "esse sit qui"
? "$select"= "esse sit qui"
? "$orderby"= "esse sit qui"
? "$top"= "12575632"
? "$skip"= "12575632"
? "$count"= "true"


// OAuth required scopes: OR.Queues or OR.Queues.Write.
// 
// Required permissions: Queues.Create.

@name("Creates a new queue.")
POST "https://{{baseUrl}}/odata/QueueDefinitions"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
data('{
    "Name": "sint anim",
    "Description": "nisi esse labore do nostrud",
    "MaxNumberOfRetries": -59711733,
    "AcceptAutomaticallyRetry": true,
    "EnforceUniqueReference": true,
    "SpecificDataJsonSchema": "officia in",
    "OutputDataJsonSchema": "in nostrud",
    "AnalyticsDataJsonSchema": "ea",
    "CreationTime": "1967-04-21T09:16:06.704Z",
    "ProcessScheduleId": -481109,
    "SlaInMinutes": 854853273,
    "RiskSlaInMinutes": 605567712,
    "ReleaseId": -87900143,
    "IsProcessInCurrentFolder": false,
    "FoldersCount": -42221294,
    "OrganizationUnitId": -87211335,
    "OrganizationUnitFullyQualifiedName": "dolor officia ",
    "Id": 47857950
}')



