#!/usr/bin/env dothttp

@name("List Decision Trees")
GET "https://connect.creditsafe.com/v1/decisionEngine/GUID"
"Content-Type": "application/json"
"Authorization": "Bearer {{connectAuthToken}}"


@name("Decision Engine Request")
GET "https://connect.creditsafe.com/v1/decisionEngine/{DecisionEngineGuid}"
"Content-Type": "application/json"
"Authorization": "Bearer {{connectAuthToken}}"
? "companyId"= "{companyId}"



