#!/usr/bin/env dothttp

@name("/wc/v3/orders/:order_id/notes")
GET "https://{{baseUrl}}/wc/v3/orders/:order_id/notes"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "context"= "view"
? "context"= "view"
? "type"= "any"
? "type"= "any"


@name("/wc/v3/orders/:order_id/notes")
POST "https://{{baseUrl}}/wc/v3/orders/:order_id/notes"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
"Content-Type": "multipart/form-data"
files(
	("note", "<string>"),
	("customer_note", "<string>"),
	("added_by_user", "<string>")
)



