#!/usr/bin/env dothttp

// List the status of every Meraki device in the organization
@name("List the status of every Meraki device in the organization")
GET "https://{{baseUrl}}/organizations/:organizationId/devices/statuses"
"X-Cisco-Meraki-API-Key": ""
? "perPage"= "{{perPage}}"
? "startingAfter"= "{{startingAfter}}"
? "endingBefore"= "{{endingBefore}}"



