#!/usr/bin/env dothttp

@name("CREATE Pairing Key")
POST "https://{{apiPath}}/environments/{{envID}}/users/{{userID}}/pairingKeys"
"Content-Type": "application/json"
json({
    "applications": [
        {
            "id": "{{appID}}"
        }
    ]
})


@name("READ One Pairing Key")
GET "https://{{apiPath}}/environments/{{envID}}/users/{{userID}}/pairingKeys/{{pairingKeyID}}"


@name("DELETE Pairing Key")
DELETE "https://{{apiPath}}/environments/{{envID}}/users/{{userID}}/pairingKeys/{{pairingKeyID}}"



