#!/usr/bin/env dothttp

@name("/version/validate")
GET "https://{{baseUrl}}/version/validate"
? "client"= "{{idClient}}"
? "version"= "<version>"


@name("/version/validate")
OPTIONS "https://{{baseUrl}}/version/validate"



