#!/usr/bin/env dothttp

// This URI returns all the transaction settlements for a Location. To narrow your search data using specific criteria, use the following parameters to filter your results: // // <ul>// <li> customer_token</li>// <li> transaction_id</li>// <li> customer_id</li>// <li> order_number</li>// <li> reference_id</li>// <li> start_settle_date / end_settle_date</li>// <li> settle_response_code</li>// <li> method</li>// </ul>// // **NOTES**: <ul><li>All date filter parameters are time aware.</li><li> If the `start_settle_date` and `end_settle_date` filters are not passed in via the body of the requst, the query automatically uses a default date range of 90 days. If you do not pass in any date filters, the system automatically uses the current date and the previous 90 days.</li></ul>
@name("All Settlements from a Location")
GET "https://{{baseURI}}/organizations/org_{{organizationID}}/locations/loc_{{locationID}}/settlements/"
basicauth("{{apiaccessid}}", "{{apisecurekey}}")



// This URI returns all the transaction settlements for a Location within a specific date range.
@name("Settlements from a Specific Data Range")
GET "https://{{baseURI}}/organizations/org_{{organizationID}}/locations/loc_{{locationID}}/settlements/"
basicauth("{{apiaccessid}}", "{{apisecurekey}}")
? "filter"= "start_settle_date+eq+'2016-10-01'+AND+end_settle_date+eq+'2016-10-31'"



// This URI returns all the settlement data for a specific transaction. **NOTE**: Most transactions only have one settlement, but due to disputes and returns, some transactions may have multiple settlements.
@name("Settlements by Transaction ID")
GET "https://{{baseURI}}/organizations/org_{{organizationID}}/locations/loc_{{locationID}}/transactions/trn_{{transactionID}}/settlements/"
basicauth("{{apiaccessid}}", "{{apisecurekey}}")



// This URI returns all the transaction settlements for an Organization. To narrow your search data using specific criteria, use the following parameters to filter your results: // // <ul>// <li> location_id</li>// <li> customer_token</li>// <li> transaction_id</li>// <li> customer_id</li>// <li> order_number</li>// <li> reference_id</li>// <li> start_settle_date / end_settle_date</li>// <li> settle_response_code</li>// <li> method</li>// </ul>// // **NOTES**: <ul><li>All date filter parameters are time aware.</li><li> If the `start_settle_date` and `end_settle_date` filters are not passed in via the body of the requst, the query automatically uses a default date range of 90 days. If you do not pass in any date filters, the system automatically uses the current date and the previous 90 days.</li></ul>
@name("All Settlements from an Organization")
GET "https://{{baseURI}}/organizations/org_{{organizationID}}/settlements/"
basicauth("{{apiaccessid}}", "{{apisecurekey}}")




