#!/usr/bin/env dothttp

// Anime and manga datum, including character, staff, and live airing data.
// 
// URL: https://anilist.gitbook.io/anilist-apiv2-docs/

@name("AniList")
POST "https://graphql.anilist.co/"



// Providing on-chain blockchain analytics.
// 
// URL - https://bitquery.io/blog/working-with-blockchain-data

@name("Bitquery")
POST "https://graphql.bitquery.io/"



// Chemical surface reaction energies and structures
// 
// URL: http://docs.catalysis-hub.org/en/latest/tutorials/index.html#graphql

@name("Catalysis Hub")
POST "https://api.catalysis-hub.org/graphql"



// Chemical surface reaction energies and structures
// 
// URL: http://docs.catalysis-hub.org/en/latest/tutorials/index.html#graphql

@name("Countries")
POST "https://countries.trevorblades.com/"




