#!/usr/bin/env dothttp

// To get the Notes associated with an Invoice.

@name("Notes")
GET "https://{{api-domain}}/crm/v2.1/Invoices/{{record_id}}/Notes"


// To get the Attachments associated with an Invoice.

@name("Attachments")
GET "https://{{api-domain}}/crm/v2.1/Invoices/{{record_id}}/Attachments"


// To get the Activities associated with an Invoice.

@name("Activities")
GET "https://{{api-domain}}/crm/v2.1/Invoices/{{record_id}}/Activities"


// To get the Closed Activities associated with an Invoice.

@name("Closed Activities")
GET "https://{{api-domain}}/crm/v2.1/Invoices/{{record_id}}/Activities_History"


// To get the Emails associated with an Email.

@name("Emails")
GET "https://{{api-domain}}/crm/v2.1/Invoices/{{record_id}}/Emails"



