#!/usr/bin/env dothttp

// Lists users in your organization with pagination in most cases.  A subset of users can be returned that match a supported filter expression or search criteria.

@name("List Users")
GET "https://{{baseUrl}}/api/v1/users"
? "q"= "<string>"
? "after"= "<string>"
? "limit"= "<integer>"
? "filter"= "<string>"
? "format"= "<string>"
? "search"= "<string>"
? "expand"= "<string>"



