#!/usr/bin/env dothttp

// You are able to easily monitor your consumption of the different services offered by Yousign:
// - `simpleSignature`: the number of finished electronic signatures (please note that 1 procedure completed with 2 signatories will be counted as 2)
// - `advancedSignature`: the number of finished Advanced Electronic Signatures
// - `archiving`: the volume of archived documents (in bytes) through the Yousign API
// - `serverStamp`: the number of documents sealed using a server stamp
// - `documentVerification`: the number of identity or bank documents verified by API. Identity verifications performed in the context of Advanced Electronic Signature are not included in this counter.
// 
// The consumption is calculated for the entire workspace.
// 
// ## Filters
// You can filter the results for a more precise analysis of your consumption:
// - by specifying the **period** for which you want to know your consumption => `period[<after|before|strictly_after|strictly_before>]=value` or `period=value` 
// - if you both use the API and the application, you can use the **source** filter => `source=api|app`

@name("/consumptions/metrics")
GET "https://{{base-api-url}}/consumptions/metrics"
"Authorization": "Bearer {{your-api-key}}"
"Content-Type": "application/json"



