#!/usr/bin/env dothttp

@name("/profile-jobs")
GET "https://{{baseUrl}}/profile-jobs"
? "_limit"= "-69288629"
? "_sort"= "anim eiusmod do ut"
? "_start"= "-69288629"
? "="= "anim eiusmod do ut"
? "_ne"= "anim eiusmod do ut"
? "_lt"= "anim eiusmod do ut"
? "_lte"= "anim eiusmod do ut"
? "_gt"= "anim eiusmod do ut"
? "_gte"= "anim eiusmod do ut"
? "_contains"= "anim eiusmod do ut"
? "_containss"= "anim eiusmod do ut"
? "_in"= "non Ut aliquip cillum"
? "_in"= "Ut veniam consequat sunt sint"
? "_nin"= "non Ut aliquip cillum"
? "_nin"= "Ut veniam consequat sunt sint"


// Create a new record

@name("/profile-jobs")
POST "https://{{baseUrl}}/profile-jobs"
"Content-Type": "application/json"
data('{
    "Title": "in incididunt",
    "localizations": [
        "cupidatat reprehenderit dolor magna sint",
        "minim dese"
    ],
    "locale": "dolore consectetur id commodo minim",
    "created_by": "mollit nulla labore",
    "updated_by": "dolor cupidatat consequat "
}')


@name("/profile-jobs/count")
GET "https://{{baseUrl}}/profile-jobs/count"



