#!/usr/bin/env dothttp

@name("SMS History")
GET "https://bsms.hostandsoft.com/app/sms/api"
? "action"= "get-inbox"
? "api_key"= "YOUR API KEY"


@name("SMS History")
POST "https://bsms.hostandsoft.com/app/sms/api"
files(
	("action", "get-inbox"),
	("api_key", "YOUR API KEY")
)



