#!/usr/bin/env dothttp

// List the Bluetooth clients seen by APs in this network

@name("List The Bluetooth Clients Seen By A Ps In This Network")
GET "https://{{baseUrl}}/networks/:networkId/bluetoothClients"
"X-Cisco-Meraki-API-Key": ""
? "t0"= "{{t0}}"
? "timespan"= "{{timespan}}"
? "perPage"= "{{perPage}}"
? "startingAfter"= "{{startingAfter}}"
? "endingBefore"= "{{endingBefore}}"
? "includeConnectivityHistory"= "{{includeConnectivityHistory}}"


// Return a Bluetooth client. Bluetooth clients can be identified by their ID or their MAC.

@name("Return A Bluetooth Client")
GET "https://{{baseUrl}}/networks/:networkId/bluetoothClients/:bluetoothClientId"
"X-Cisco-Meraki-API-Key": ""
? "includeConnectivityHistory"= "{{includeConnectivityHistory}}"
? "connectivityHistoryTimespan"= "{{connectivityHistoryTimespan}}"



