#!/usr/bin/env dothttp

// To get the list of territories enabled for your organization.
@name("Territories")
GET "https://{{api-domain}}/crm/v2.1/settings/territories"
"Authorization": "{{authorization-token}}"
"Content-Type": "application/json"


// To assign territories to multiple records or a single record.
@name("Assign Territories")
POST "https://{{api-domain}}/crm/v2.1/Accounts/actions/assign_territories"
json({
    "data": [
        {
            "id": "{{record_id1}}",
            "Territories": [
                {
                    "id": "{{territory_id1}}"
                },
                {
                    "id": "{{territory_id2}}"
                }
            ]
        },
        {
            "id": "{{record_id2}}",
            "Territories": [
                {
                    "id": "{{territory_id1}}"
                },
                {
                    "id": "{{territory_id2}}"
                }
            ]
        }
    ]
})


// To remove territories assigned to multiple records or a single record.
@name("Remove Territories")
POST "https://{{api-domain}}/crm/v2.1/Accounts/actions/remove_territories"
json({
    "data": [
        {
            "id": "{{record_ID1}}",
            "Territories": [
                {
                    "id": "{{territory_ID1}}"
                },
                {
                    "id": "{{territory_ID2}}"
                }
            ]
        },
        {
            "id": "{{record_ID2}}",
            "Territories": [
                {
                    "id": "{{territory_ID1}}"
                },
                {
                    "id": "{{territory_ID2}}"
                }
            ]
        }
    ]
})


// To get the details of the territories assigned to a record.
@name("Get Territories Assigned")
GET "https://{{api-domain}}/crm/v2.1/Accounts/4150868000004395059"



