#!/usr/bin/env dothttp

@name("Send a post on the order")
POST "https://{{url}}/api/ExtendedDiscussion"
basicauth("{{user_name}}", "{{api_key}}")
"Content-Type": "application/json"
data('{
  "lang_code": "en",
  "message": "aaaagdfg",
  "name": "Customer",
  "order_id": "{{order_id}}",
  "thread_id": "2227",
  "select_gdpr_agreement" : "Y",
  "user_id": 971
}')


@name("Get the thread id")
GET "https://{{url}}/api/ExtendedDiscussion/"
basicauth("{{user_name}}", "{{api_key}}")
? "view"= "initiate_discussion"
? "order_id"= "{{order_id}}"
? "lang_code"= "{{lang_code}}"




