#!/usr/bin/env dothttp

// Updates a screen scheme. Only screen schemes used in classic projects can be updated.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Update Screen Scheme")
PUT "https://{{baseUrl}}/rest/api/3/screenscheme/:screenSchemeId"
"Content-Type": "application/json"
json({
    "name": "<string>",
    "description": "<string>",
    "screens": {
        "type": "string",
        "description": "The ID of the default screen. When specified, must include a screen ID as a default screen is required.",
        "writeOnly": true,
        "default": "<string>"
    }
})


// Deletes a screen scheme. A screen scheme cannot be deleted if it is used in an issue type screen scheme.
// 
// Only screens schemes used in classic projects can be deleted.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Delete Screen Scheme")
DELETE "https://{{baseUrl}}/rest/api/3/screenscheme/:screenSchemeId"



