#!/usr/bin/env dothttp

// <h3>This API can be used to verify an Electricity Bill.</h3>
// <br>
// <h4>REQUEST:</h4>
// <br>
// 
// ```
// {
//     "consumer_id":"<< Consumer ID provided on bill >>",
//     "service_provider":"<<Electricity Service Provider>>",
//     "consent":"<< Y or N >>",
//     "consent_text":"<< Consent Message >>"
// } 
// ```
// <br>
// <h4>RESPONSE JSON:</h4>
// <br>
// <h5>Transaction Success | Electricity Bill verification Success:</h5>
// <br>
// 
// ```
// {
//     "id": "<< Transaction ID >>",
//     "response_code": "101",
//     "env": 1,
//     "request_timestamp": "2018-09-17 11:56:23:226 +05:30",
//     "response_timestamp": "2018-09-17 11:56:25:541 +05:30",
//     "transaction_status": 1,
//     "result": {
//         "address": "SMG P 195/**********",
//         "amount_payable": "",
//         "bill_amount": "",
//         "bill_date": "",
//         "bill_due_date": "",
//         "bill_issue_date": "",
//         "bill_no": "",
//         "consumer_name": "VXXXY CXXXXX",
//         "consumer_number": "13XXXXXX61XX",
//         "email_address": "",
//         "mobile_number": "7XX99XXXXX",
//         "total_amount": ""
//     },
//     "response_msg": "Valid Authentication"
// }
// ```
// 
// <br>
// <h5>Transaction Failure:</h5>
// <br>
// 
// ```
// {
//     "id": "<< Transaction ID>>",
//     "response_code": "102",
//     "env": 1,
//     "request_timestamp": "2018-09-19 18:08:55:947 +05:30",
//     "response_timestamp": "2018-09-19 18:08:57:366 +05:30",
//     "response_msg": "Invalid ID number or combination of inputs"
// }
// ```
// 
// <br>
// 
// 

@name("Verification API")
POST "https://{{base_url}}/verify-electricitybill"
"Content-Type": "application/json"
"qt_api_key": "{{qt_api_key_value}}"
"qt_agency_id": "{{qt_agency_id}}"
data('{
    "consumer_id":"<<Consumer Id>>",
    "service_provider":"<<Service Provider>>",
    "consent":"<< Y or N >>",
    "consent_text":"<< Consent Message >>"
} ')


// This API can be used to fetch the Electricity bill verification transaction's meta-data (no customer data is stored) for any status check etc.
// 
// <h4>Fetch response</h4>
// 
// ```
// {
//     "id": "<< Transaction ID>>",
//     "consent": "Y",
//     "consent_text": "<< Consent Text >>",
//     "env": 1,
//     "response_code": 101,
//     "response_msg": "Valid Authentication",
//     "transaction_status": 1,
//     "request_timestamp": "2018-09-14 15:09:49:107 +05:30",
//     "response_timestamp": "2018-09-14 15:09:50:391 +05:30"
// }
// ```

@name("Fetch API")
GET "https://{{base_url}}/verify-lpg/fetch/<<transaction_id>>"
"qt_api_key": "{{qt_api_key_value}}"
"qt_agency_id": "{{qt_agency_id}}"



