#!/usr/bin/env dothttp

// Get all available services for usage on plans

@name("List all services")
GET "https://{{API_BASE_URL}}/services"


@name("Create a service")
POST "https://{{API_BASE_URL}}/services"
data('[
    {
        "name": "Depósito via TED",
        "description": "Depósito via TED | parati-provider",
        "provider": "parati-provider", //parati-provider | bs2 | cdt-visa | celcoin
        "type": "deposit"
    }
]')



