#!/usr/bin/env dothttp

@name("1、查询部门列表")
GET "http://localhost/wx/web/dept/list"
files(
	("pageNum", "1"),
	("pageSize", "3"),
	("deptId", "1"),
	("deptName", ""),
	("delFlag", "0")
)


@name("2、查询部门详情")
GET "http://localhost/wx/web/dept/1"


@name("2、查询部门树形结构")
GET "http://localhost/wx/web/dept/treeselect"



@name("3、添加部门")
POST "http://localhost/wx/web/dept"
"Content-Type": "application/json"
json({
    "deptId": 333,
    "deptName": "技术部",
    "deptNameEn": "hg",
    "parentId": 1,
    "deptOrder": 1,
    "remark": "备注技术部",
    "delFlag": "0"
})


@name("4、修改部门")
PUT "http://localhost/wx/web/dept"
"Content-Type": "application/json"
json({
    "deptId": 333,
    "deptName": "技术部",
    "deptNameEn": "hg",
    "parentId": 1,
    "deptOrder": 1,
    "remark": "备注技术部",
    "delFlag": "0"
})


@name("5、删除部门")
DELETE "http://localhost/wx/web/dept/2"



