#!/usr/bin/env dothttp

@name("READ Organization Capabilities")
GET "https://{{apiPath}}/organizations/{{orgID}}/capabilities"


@name("READ Environment Capabilities")
GET "https://{{apiPath}}/environments/{{envID}}/capabilities"



