#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Ids Of Deleted Worklogs")
GET "None://{{baseUrl}}/rest/api/3/worklog/deleted"
? "since"= "0"


@name("Get Worklogs")
POST "None://{{baseUrl}}/rest/api/3/worklog/list"
"Content-Type": "application/json"
? "expand"= ""
data('{
    "ids": [
        "<long>"
    ]
}')


@name("Get Ids Of Updated Worklogs")
GET "None://{{baseUrl}}/rest/api/3/worklog/updated"
? "since"= "0"
? "expand"= ""



