#!/usr/bin/env dothttp

@name("Receber por transferência bancária de uma conta Pagstar")
POST "http://18.224.82.80/api/partner/buy/bank-transfer"
json({
    "value": 100,
    "currency": "brl",
    "customer_email": "email@email.com",
    "name": "Gengivudo",
    "phone_number": "13982234569",
    "document_number": "47497065823",
    "bank_selected": "BRADESCO_TRANSFER",
    "bank": {
        "branch": "3750",
        "account": "783796"
    }
})


@name("Exibir dados de uma  transferência bancária")
GET "http://18.224.82.80/api/partner/verify/bank-transfer/id/5f02a727e11ed620ab5352e8"


@name("Lista de  transferências bancárias realizados para sua conta")
GET "http://18.224.82.80/api/partner/list/bank-transfer"



