#!/usr/bin/env dothttp

@name("/contries/:id")
GET "https://{{baseUrl}}/contries/:id"


// Update a record

@name("/contries/:id")
PUT "https://{{baseUrl}}/contries/:id"
"Content-Type": "application/json"
data('{
    "name": "est aute consec",
    "created_by": "eu et do ullamco aliquip",
    "updated_by": "Excepteur laborum"
}')


// Delete a record

@name("/contries/:id")
DELETE "https://{{baseUrl}}/contries/:id"



