#!/usr/bin/env dothttp

// Aggregated connectivity info for this network, grouped by clients
@name("getNetworkClientsConnectionStats")
GET "https://{{baseUrl}}/networks/:networkId/clients/connectionStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"



// Aggregated latency info for this network, grouped by clients
@name("getNetworkClientsLatencyStats")
GET "https://{{baseUrl}}/networks/:networkId/clients/latencyStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"
? "fields"= "{{fields}}"



// Aggregated connectivity info for a given client on this network. Clients are identified by their MAC.
@name("getNetworkClientConnectionStats")
GET "https://{{baseUrl}}/networks/:networkId/clients/:clientId/connectionStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"



// Aggregated latency info for a given client on this network. Clients are identified by their MAC.
@name("getNetworkClientLatencyStats")
GET "https://{{baseUrl}}/networks/:networkId/clients/:clientId/latencyStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"
? "fields"= "{{fields}}"



// Aggregated connectivity info for this network
@name("getNetworkConnectionStats")
GET "https://{{baseUrl}}/networks/:networkId/connectionStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"



// Aggregated connectivity info for this network, grouped by node
@name("getNetworkDevicesConnectionStats")
GET "https://{{baseUrl}}/networks/:networkId/devices/connectionStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"



// Aggregated latency info for this network, grouped by node
@name("getNetworkDevicesLatencyStats")
GET "https://{{baseUrl}}/networks/:networkId/devices/latencyStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"
? "fields"= "{{fields}}"



// Aggregated connectivity info for a given AP on this network
@name("getNetworkDeviceConnectionStats")
GET "https://{{baseUrl}}/networks/:networkId/devices/:serial/connectionStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"



// Aggregated latency info for a given AP on this network
@name("getNetworkDeviceLatencyStats")
GET "https://{{baseUrl}}/networks/:networkId/devices/:serial/latencyStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"
? "fields"= "{{fields}}"



// List of all failed client connection events on this network in a given time range
@name("getNetworkFailedConnections")
GET "https://{{baseUrl}}/networks/:networkId/failedConnections"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"
? "serial"= "{{serial}}"
? "clientId"= "{{clientId}}"



// Aggregated latency info for this network
@name("getNetworkLatencyStats")
GET "https://{{baseUrl}}/networks/:networkId/latencyStats"
"Accept": "*/*"
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "band"= "{{band}}"
? "ssid"= "{{ssid}}"
? "vlan"= "{{vlan}}"
? "apTag"= "{{apTag}}"
? "fields"= "{{fields}}"




