#!/usr/bin/env dothttp

@name("Login")
POST "https://test.salesforce.com/services/oauth2/token"
? "grant_type"= "password"
? "client_id"= "3MVG93MGy9V8hF9P5tOvZXvSk6U4CwgTmSzHnQqOYwBVHSn6y7W8WqZVNQAwPDOAwtjSwl_l_eMprWAWkj3TE"
? "client_secret"= "C293DA72E2F5DE8519A663E1EF1B7FC81DB7E6E66FB761F49C354F536F2A346A"
? "username"= "vs-integracion-sf@security.cl.qa"
? "password"= "vS*s.1nt3.fL6Ahm7dujdS6yO5fGEPCWBLp"


@name("GetLeadById")
GET "https://vidasecurity--sndsalud.my.salesforce.com/services/data/v48.0/sobjects/Lead/00QR000000JBXfGMAX2"
"Authorization": "Bearer 00DR00000020Ylj!AQgAQBUo0UoREvNaDT90Xve26x3AerJrcdLiM74OTS0AqAF8ZfLD6a_9ynF0w0Xc6Ythwm9UFh2HR2Fz0puGWVNBvZH86NLp"


@name("GetCampaignsByrut")
GET "https://vidasecurity--qa.my.salesforce.com/services/data/v48.0/query/"
"Authorization": "Bearer 00D7A000000DO0P!AREAQGvxNBmen7j.YsYBWKjeKJ02qivK0Lf.FRopr26EZwizLamKhFbIGkpTQUD5SuSz4v0QWtCyjFQl.1uUEkiuSLWhsjnG"
? "q"= "SELECT+Id,Name,CampaignId,Campaign.Name+FROM+CampaignMember"


@name("PostLead")
POST "https://vidasecurity--qa.my.salesforce.com/services/data/v48.0/sobjects/Lead"
"Authorization": "Bearer 00D7A000000DO0P!AREAQMGR429qS7RHhdpCIBDHFz8XPGGv_4miPkKqSxppzvwbfbx2L.6ZDoSlu.MRETME4wKV8iZ0haDGRGToaT8KKZhbJwoU"
json({
    "LastName": "SALAZAR",
    "FirstName": "ISAAC ANTONIO",
    "Salutation": null,
    "RecordTypeId": "0120H000001QUFSQA4",
    "Title": null,
    "Company": null,
    "Street": null,
    "City": null,
    "State": null,
    "PostalCode": null,
    "Country": null,
    "Latitude": null,
    "Longitude": null,
    "GeocodeAccuracy": null,
    "Phone": "91561750",
    "Email": "isaac.salazar@security.cl",
    "Website": null,
    "Description": null,
    "LeadSource": null,
    "Status": "Abrir",
    "Industry": null,
    "Rating": null,
    "CurrencyIsoCode": "CLF",
    "AnnualRevenue": null,
    "NumberOfEmployees": null,
    "HasOptedOutOfEmail": false,
    "IsConverted": false,
    "ConvertedDate": null,
    "ConvertedAccountId": null,
    "ConvertedContactId": null,
    "ConvertedOpportunityId": null,
    "IndividualId": null,
    "PROSPE_Carga_Fecha_Nacimiento__c": "1988-11-19",
    "PROSP_Carga_Apellido_Materno__c": "ARANEDA",
    "PROSP_Carga_Email_2__c": null,
    "PROSP_Carga_RUT__c": "16903814",
    "PROSP_Carga_Tel_fono_2__c": null,
    "PROSP_No_quiere_ser_contactado_Televenta__c": false,
    "rrpu__Alert_Message__c": null,
    "Marcas__Edad__c": null,
    "Marcas__Rut__c": null,
    "Genero__c": null,
    "Potencial_Cliente__c": null,
    "Renta__c": null,
    "RUT__c": null
})


@name("Post Account")
POST "https://vidasecurity--TestCarga.cs67.my.salesforce.com/services/data/v45.0/sobjects/Account"
"Content-Type": "application/json"
"Authorization": "Bearer 00D0n0000004Yjo!AQEAQFNSlPbdU1kfbaGlpyA1gBu2JjetwHZMC.EZrntCMVvdfvQeCJzs0t7rcotyFLXmcK4CFBQBwdujnu2HzXVpThwHTpWw"
json({
    "Nombres_Cliente__c": "JOSE MANUEL",
    "LastName": "ARIAS ARANCIBIA",
    "OwnerId": "005i0000004xhHpAAI",
    "Tipo_de_Persona__c": "N",
    "Rut_contacto__pc": "2340667",
    "FirstName": "JOSE MANUEL",
    "Empresa_Origen__c": "Vida Security",
    "DV_contacto__pc": "5",
    "Rut__c": "2340667",
    "DV__c": "5",
    "CurrencyIsoCode": "CLF"
})


@name("PatchMember")
PATCH "https://vidasecurity--qa.my.salesforce.com/services/data/v48.0/sobjects/CampaignMember/00v0H00001UN0Oo2"
"Content-Type": "application/json"
"Authorization": "Bearer 00D7A000000DO0P!AREAQGvxNBmen7j.YsYBWKjeKJ02qivK0Lf.FRopr26EZwizLamKhFbIGkpTQUD5SuSz4v0QWtCyjFQl.1uUEkiuSLWhsjnG"
json({
    "MCAMP_Carga_Tel_fono_3__c": "isaac.salazar@security.cl"
})



