#!/usr/bin/env dothttp

@name("Absolutely 302 Redirects n times.")
GET "https://{{baseUrl}}/absolute-redirect/:n"


@name("Decodes base64url-encoded string.")
GET "https://{{baseUrl}}/base64/:value"


@name("Prompts the user for authorization using HTTP Basic Auth.")
GET "https://{{baseUrl}}/basic-auth/:user/:passwd"


@name("Prompts the user for authorization using bearer authentication.")
GET "https://{{baseUrl}}/bearer"


@name("Returns Brotli-encoded data.")
GET "https://{{baseUrl}}/brotli"


@name("Returns n random bytes generated with given seed")
GET "https://{{baseUrl}}/bytes/:n"


@name("Returns Deflate-encoded data.")
GET "https://{{baseUrl}}/deflate"


@name("The request's DELETE parameters.")
DELETE "https://{{baseUrl}}/delete"


@name("Returns page denied by robots.txt rules.")
GET "https://{{baseUrl}}/deny"


@name("Drips data over a duration after an optional initial delay.")
GET "https://{{baseUrl}}/drip"
? "duration"= "2"
? "numbytes"= "10"
? "code"= "200"
? "delay"= "2"


@name("Returns a UTF-8 encoded body.")
GET "https://{{baseUrl}}/encoding/utf8"


@name("Assumes the resource has the given etag and responds to If-None-Match and If-Match headers appropriately.")
GET "https://{{baseUrl}}/etag/:etag"
"If-None-Match": "do Duis amet dolor"
"If-Match": "do Duis amet dolor"


@name("The request's query parameters.")
GET "https://{{baseUrl}}/get"


@name("Returns GZip-encoded data.")
GET "https://{{baseUrl}}/gzip"


@name("Return the incoming request's HTTP headers.")
GET "https://{{baseUrl}}/headers"


@name("Prompts the user for authorization using HTTP Basic Auth.")
GET "https://{{baseUrl}}/hidden-basic-auth/:user/:passwd"


@name("Returns a simple HTML document.")
GET "https://{{baseUrl}}/html"


@name("Returns the requester's IP Address.")
GET "https://{{baseUrl}}/ip"


@name("Returns a simple JSON document.")
GET "https://{{baseUrl}}/json"


@name("Generate a page containing n links to other pages which do the same.")
GET "https://{{baseUrl}}/links/:n/:offset"


@name("The request's PATCH parameters.")
PATCH "https://{{baseUrl}}/patch"


@name("The request's POST parameters.")
POST "https://{{baseUrl}}/post"


@name("The request's PUT parameters.")
PUT "https://{{baseUrl}}/put"


@name("Streams n random bytes generated with given seed, at given chunk size per packet.")
GET "https://{{baseUrl}}/range/:numbytes"


@name("302 Redirects n times.")
GET "https://{{baseUrl}}/redirect/:n"


@name("Relatively 302 Redirects n times.")
GET "https://{{baseUrl}}/relative-redirect/:n"


@name("Returns some robots.txt rules.")
GET "https://{{baseUrl}}/robots.txt"


@name("Streams n random bytes generated with given seed, at given chunk size per packet.")
GET "https://{{baseUrl}}/stream-bytes/:n"


@name("Stream n JSON responses")
GET "https://{{baseUrl}}/stream/:n"


@name("Return the incoming requests's User-Agent header.")
GET "https://{{baseUrl}}/user-agent"


@name("Return a UUID4.")
GET "https://{{baseUrl}}/uuid"


@name("Returns a simple XML document.")
GET "https://{{baseUrl}}/xml"



