#!/usr/bin/env dothttp

@name("block")
POST "http://api.openbanking.ng/customer/block"
"Accept": "*/*"
"Content-Type": "application/json"
? "customerId"= "{{customerId}}"



@name("getByBVN")
GET "http://api.openbanking.ng/customer/getByBVN"
"Accept": "*/*"
"Content-Type": "application/json"
data("The Customer's Bank Verification Number")


// The Customer ID is the unique identifier for a customer as defined by a Bank

@name("Finds a Customer by Customer ID")
GET "http://api.openbanking.ng/customer/getByCustomerId"
"Accept": "*/*"
"Content-Type": "application/json"
data("The Customer's unique identifier")


@name("getByEmail")
GET "http://api.openbanking.ng/customer/getByEmail"
"Accept": "*/*"
"Content-Type": "application/json"
data("The Customer's Email Address")


@name("getByPhoneNumber")
GET "http://api.openbanking.ng/customer/getByPhoneNumber"
"Accept": "*/*"
"Content-Type": "application/json"
data("The Customer's Phone Number ex: +234")


@name("updateCustomerInformation")
POST "http://api.openbanking.ng/customer/update"
"Accept": "*/*"
"Content-Type": "application/json"
data('customerUpdateRequest')



