#!/usr/bin/env dothttp

// Get a list of valid device MAC options.

@name("Get options")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/devices/options"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"


// Get a list of device MAC addresses.

@name("Get device MACs")
GET "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/devices"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"


// Create a new device MAC identity.

@name("Create device MAC")
POST "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/device_macs"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"
? "device_id"= "2"
? "mac"= "f8:8f:ca:10:c3:ff"
? "label"= "-"
? "ips[0]"= "192.168.1.100"


// Update an existing device mac record.

@name("Update device MAC")
PATCH "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/device_macs/:id"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"
? "label"= "Google Pixel 3"
? "mac"= "F8:8F:CA:10:C3:DD"
? "owner_id"= "1"
? "group_id"= "1"
? "os_id"= "0"
? "type_id"= "0"


// Delete an existing device MAC.

@name("Delete device MAC")
DELETE "https://{{URL_INFORMATICS}}/api/{{API_VERSION}}/identity/devices/:id"
"x-api-key": "{{API_KEY}}"
"x-net-organization": "{{ORG_UUID}}"



