#!/usr/bin/env dothttp

// ## Login Api
// 
// Test Admin

@name("CREATE")
POST "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/admin/api/v1/categories/meals"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1OTYzMTk3NiwiZXhwIjoxNTYwMjM2Nzc2fQ.DLt1cIbVXSIMZQS--sdt-QyqFT9UFraBYAdeFswZkWo"
json({
    "name": "kkk",
    "description": "Description For Category Meal Breakfast"
})


// ## Login Api
// 
// Test Admin

@name("READ")
GET "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/admin/api/v1/categories/meals"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU2MjAxNTc2MCwiZXhwIjoxNTYyNjIwNTYwfQ.mmr-Xl66F_-K1Ck7HVJGBhUsMG_AtNs_rL9ZBYJ1YJ0"
? "start"= "0"
? "limit"= "10"


// ## Login Api
// 
// Test Admin

@name("UPDATE")
PUT "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/admin/api/v1/categories/meals/5cf61990b4a0ed72d27b227d"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1OTYzMTk3NiwiZXhwIjoxNTYwMjM2Nzc2fQ.DLt1cIbVXSIMZQS--sdt-QyqFT9UFraBYAdeFswZkWo"
json({
    "name": "Lunch",
    "description": "Description For Category Meal Lunch"
})


// ## Login Api
// 
// Test Admin

@name("UPDATE PHOTO")
PUT "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/admin/api/v1/categories/meals/photo/5cf6196bb4a0ed72d27b227b"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU2MjAxNTc2MCwiZXhwIjoxNTYyNjIwNTYwfQ.mmr-Xl66F_-K1Ck7HVJGBhUsMG_AtNs_rL9ZBYJ1YJ0"
files(
	("image", "None")
)


// ## Login Api
// 
// Test Admin

@name("DELETE")
DELETE "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/admin/api/v1/categories/meals/5cf61980b4a0ed72d27b227c"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1OTYzMTk3NiwiZXhwIjoxNTYwMjM2Nzc2fQ.DLt1cIbVXSIMZQS--sdt-QyqFT9UFraBYAdeFswZkWo"



