#!/usr/bin/env dothttp

// Lists the organizations that are selected to have GitHub Actions enabled in an enterprise. To use this endpoint, the enterprise permission policy for `enabled_organizations` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."
// 
// You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.

@name("List selected organizations enabled for GitHub Actions in an enterprise")
GET "https://{{baseUrl}}/enterprises/:enterprise/actions/permissions/organizations"
? "per_page"= "30"
? "page"= "1"


// Replaces the list of selected organizations that are enabled for GitHub Actions in an enterprise. To use this endpoint, the enterprise permission policy for `enabled_organizations` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."
// 
// You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.

@name("Set selected organizations enabled for GitHub Actions in an enterprise")
PUT "https://{{baseUrl}}/enterprises/:enterprise/actions/permissions/organizations"
"Content-Type": "application/json"
data('{
    "selected_organization_ids": [
        "<integer>",
        "<integer>"
    ]
}')



