#!/usr/bin/env dothttp

@name("User Email Preferred Person")
GET "https://{{host}}/services/data/v47.0/sobjects/UserEmailPreferredPerson/"


@name("User Email Preferred Person Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/UserEmailPreferredPerson/{ID}/"


@name("Describe User Email Preferred Person")
GET "https://{{host}}/services/data/v47.0/sobjects/UserEmailPreferredPerson/describe/"



