#!/usr/bin/env dothttp

// OAuth required scopes: OR.Administration or OR.Administration.Read.
// 
// Host only. Requires authentication.

@name("Gets host licenses.")
GET "https://{{baseUrl}}/odata/HostLicenses"
? "$expand"= "esse sit qui"
? "$filter"= "esse sit qui"
? "$select"= "esse sit qui"
? "$orderby"= "esse sit qui"
? "$top"= "12575632"
? "$skip"= "12575632"
? "$count"= "true"


// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Uploads a new offline license activation.
The content of the license is sent as a file embedded in the HTTP request.")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.ActivateLicenseOffline"
"Content-Type": "multipart/form-data"
files(
	("file", "magna eu tempor ea")
)


// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Activate the license for the host")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.ActivateLicenseOnline"
"Content-Type": "application/json"
json({
    "licenseKey": "e",
    "environment": "culpa",
    "email": "ull"
})


// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Deactivate the license for the host")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.DeactivateLicenseOnline"
"Content-Type": "application/json"



// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Deletes a tenant license based on its key.")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.DeleteTenantLicense"
"Content-Type": "application/json"
json({
    "tenantId": 77992166
})


// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Deactivate the license offline for the host")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.GetDeactivateLicenseOffline"
"Content-Type": "application/json"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"



// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Create the offline activation request for the host")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.GetLicenseOffline"
"Content-Type": "application/json"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"
json({
    "licenseKey": "e",
    "environment": "culpa",
    "email": "ull"
})


// OAuth required scopes: OR.Administration or OR.Administration.Read.
// 
// Host only. Requires authentication.

@name("Gets a single tenant license based on its id.")
GET "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.GetTenantLicense(tenantId={{tenantId}})"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"


// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Sets the license for a specific tenant")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.SetTenantLicense"
"Content-Type": "application/json"
json({
    "license": {
        "TenantId": -666272,
        "HostLicenseId": 13771845
    }
})


// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Update the license for the host")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.UpdateLicenseOnline"


// OAuth required scopes: OR.Administration or OR.Administration.Write.
// 
// Host only. Requires authentication.

@name("Uploads a new host license file that was previously generated with Regutil.
The content of the license is sent as a file embedded in the HTTP request.")
POST "https://{{baseUrl}}/odata/HostLicenses/UiPath.Server.Configuration.OData.UploadLicense"
"Content-Type": "multipart/form-data"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"
files(
	("file", "magna eu tempor ea")
)



