#!/usr/bin/env dothttp

// This endpoint allows you to create collections using the Postman Collection v2 format. For more information about the v2 schema, check the format [here](https://schema.getpostman.com/json/collection/v2.0.0/docs/index.html).
// 
// On successful creation of the collection, the response returns the collection `name`, `id` and the `uid`.
// 
// > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.

@name("Create collection")
POST "https://api.getpostman.com/collections"
"X-Api-Key": "{{postman_api_key}}"
"Content-Type": "application/json"
data('{
  "collection": {
    "info": {
      "name": "Demo collection for mocking",
      "description": "This is just a sample collection.",
      "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    "item": [
          {
            "name": "Sample POST Request",
            "request": {
              "url": "https://postman-echo.com/post",
              "method": "POST",
              "header": [
                {
                  "key": "Content-Type",
                  "value": "application/json"
                }
              ],
              "body": {
                "mode": "raw",
                "raw": "{\"data\": \"123\"}"
              },
              "description": "This is a sample POST Request"
            }
      },
      {
        "name": "Sample GET Request",
        "request": {
          "url": "https://postman-echo/get",
          "method": "GET",
          "description": "This is a sample GET Request"
        }
      }
    ]
  }
}')


// This endpoint allows you to create a mock on a collection. You can also provide an environment UID to resolve any environment variables in the collection.
// 
// > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.

@name("Create mock")
POST "https://api.getpostman.com/mocks"
"Content-Type": "application/json"
"X-Api-Key": "{{postman_api_key}}"
data('{
  "mock": {
    "collection": "{{collection_uid}}"
  }
}')



