#!/usr/bin/env dothttp

// You must supply an access token for every request to this API. This token must be send in the
// "Authorization" header. In order to get an access token, this endpoint must be called

@name("Authentication")
POST "https://auth-recette.planetvo.info/auth/realms/Medias2.0/protocol/openid-connect/token"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "grant_type": [
        "password"
    ],
    "client_id": [
        "publication2-listing"
    ],
    "username": [
        "<username>"
    ],
    "password": [
        "<password>"
    ]
})


// # Get classifieds for a matching code.
// The matching code is mandaroty. It is a string generally used to identify a customer. It can be a
// customer reference in your system. Or it can be our reference if you don’t have one.
// Classifieds can only be obtained per matching code. That means you must know the matching
// codes that are linked to your credentials in order to get query this API.

@name("Get Classifeds")
GET "https://api-recette.publicationvo.info/listing/classified"
? "matchingCode"= "bm31c1"
? "streamCode"= "BMWIUCP"



