#!/usr/bin/env dothttp

// Return the 1:Many NAT mapping rules for an MX network
@name("getNetworkOneToManyNatRules")
GET "https://{{baseUrl}}/networks/:networkId/oneToManyNatRules"
"Accept": "*/*"



// Set the 1:Many NAT mapping rules for an MX network//  #### Body Parameters // **Parameter**|**Type**|**Description** //  :-------------: |:-------------: |:-------------: // rules| array| An array of 1:Many nat rules
@name("updateNetworkOneToManyNatRules")
PUT "https://{{baseUrl}}/networks/:networkId/oneToManyNatRules"
"Accept": "*/*"
"Content-Type": "application/json"
data('{
  "rules": [
    {
      "publicIp": "146.11.11.13",
      "uplink": "internet1",
      "portRules": [
        {
          "name": "Rule 1",
          "protocol": "tcp",
          "publicPort": "9443",
          "localIp": "192.168.128.1",
          "localPort": "443",
          "allowedIps": [
            "any"
          ]
        },
        {
          "name": "Rule 2",
          "protocol": "tcp",
          "publicPort": "8080",
          "localIp": "192.168.128.1",
          "localPort": "80",
          "allowedIps": [
            "10.82.110.0/24",
            "10.82.111.0/24"
          ]
        }
      ]
    }
  ]
}')



