#!/usr/bin/env dothttp

@name("Order Item History")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemHistory/"


@name("Order Item History Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemHistory/{ID}/"


@name("Describe Order Item History")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemHistory/describe/"



