#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Resolutions")
GET "{{baseUrl}}/rest/api/3/resolution"


@name("Get Resolution")
GET "None://{{baseUrl}}/rest/api/3/resolution/:id"



