#!/usr/bin/env dothttp

// Calculate projected pot size based on current pot size and growth inputs

@name("/v1/calculate-projection")
POST "https://{{NAMESPACE_URL}}{{PENSION_PROJECTION_PORT}}/pension-projection/v1/calculate-projection"
"Content-Type": "application/json"
"Authorization": "{{PENSION_PROJECTION_API_KEY}}"
data('{
  "nominal_multiplier": 6.5,
  "inflationary_divisor": 2.5,
  "charges": 0.75,
  "gross_monthly_contribution": 500,
  "pot_size": 100000,
  "early_tax_free_cash": 25000,
  "months_to_retirement": 120
}')



