#!/usr/bin/env dothttp

@name("Retrieve hardware status summary")
GET "https://{{vmanage}}/dataservice/device/hardware/status/summary"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve hardware errored alarm list")
GET "https://{{vmanage}}/dataservice/device/hardware/errors"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"


@name("Retrieve hardware alarm list from device")
GET "https://{{vmanage}}/dataservice/device/hardware/alarms"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve hardware alarm list from vManage")
GET "https://{{vmanage}}/dataservice/device/hardware/synced/alarms"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve hardware system data list")
GET "https://{{vmanage}}/dataservice/device/hardware/system"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve hardware inventory list from device")
GET "https://{{vmanage}}/dataservice/device/hardware/inventory"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve hardware inventory list from vManage")
GET "https://{{vmanage}}/dataservice/device/hardware/synced/inventory"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve hardware environment list from device")
GET "https://{{vmanage}}/dataservice/device/hardware/environment"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve hardware environment list from vManage")
GET "https://{{vmanage}}/dataservice/device/hardware/synced/environment"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve hardware temperature threshold list")
GET "https://{{vmanage}}/dataservice/device/hardware/threshold"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"



