#!/usr/bin/env dothttp

// Returns the bundle for the given resources. This API call is capable of returning a bundle created from multiple
//  resources.
// Export Bundle

@name("Exports Bundle")
GET "https://{{baseUrl}}/1.0/bundle"
? "defaultAction"= "<string>"
? "exportGatewayRestManagementService"= "<boolean>"
? "activeConnector"= "<array>"
? "cassandraConnection"= "<array>"
? "trustedCertificate"= "<array>"
? "clusterProperty"= "<array>"
? "customKeyValue"= "<array>"
? "emailListener"= "<array>"
? "encapsulatedAssertion"= "<array>"
? "firewallRule"= "<array>"
? "folder"= "<array>"
? "genericEntity"= "<array>"
? "httpConfiguration"= "<array>"
? "identityProvider"= "<array>"
? "interfaceTag"= "<array>"
? "jdbcConnection"= "<array>"
? "jmsDestination"= "<array>"
? "listenPort"= "<array>"
? "policy"= "<array>"
? "policyAlias"= "<array>"
? "policyBackedService"= "<array>"
? "privateKey"= "<array>"
? "service"= "<array>"
? "serviceAlias"= "<array>"
? "resource"= "<array>"
? "revocationCheckingPolicy"= "<array>"
? "role"= "<array>"
? "sampleMessage"= "<array>"
? "scheduledTask"= "<array>"
? "password"= "<array>"
? "securityZone"= "<array>"
? "serverModuleFile"= "<array>"
? "siteMinderConfiguration"= "<array>"
? "workQueue"= "<array>"
? "logSink"= "<array>"
? "requireActiveConnector"= "<array>"
? "requireCassandraConnection"= "<array>"
? "requireTrustedCertificate"= "<array>"
? "requireClusterProperty"= "<array>"
? "requireCustomKeyValue"= "<array>"
? "requireEmailListener"= "<array>"
? "requireEncapsulatedAssertion"= "<array>"
? "requireFirewallRule"= "<array>"
? "requireFolder"= "<array>"
? "requireGenericEntity"= "<array>"
? "requireHttpConfiguration"= "<array>"
? "requireIdentityProvider"= "<array>"
? "requireInterfaceTag"= "<array>"
? "requireJdbcConnection"= "<array>"
? "requireJmsDestination"= "<array>"
? "requireListenPort"= "<array>"
? "requirePolicy"= "<array>"
? "requirePolicyAlias"= "<array>"
? "requirePolicyBackedService"= "<array>"
? "requirePrivateKey"= "<array>"
? "requireService"= "<array>"
? "requireServiceAlias"= "<array>"
? "requireResource"= "<array>"
? "requireRevocationCheckingPolicy"= "<array>"
? "requireRole"= "<array>"
? "requireSampleMessage"= "<array>"
? "requireScheduledTask"= "<array>"
? "requirePassword"= "<array>"
? "requireSecurityZone"= "<array>"
? "requireServerModuleFile"= "<array>"
? "requireSiteMinderConfiguration"= "<array>"
? "requireWorkQueue"= "<array>"
? "requireSolutionKit"= "<array>"
? "all"= "<boolean>"
? "includeDependencies"= "<boolean>"
? "includeSolutionKits"= "<boolean>"
? "encryptSecrets"= "<boolean>"
? "encryptUsingClusterPassphrase"= "<boolean>"
? "encassAsPolicyDependency"= "<boolean>"
? "includeOnlyServicePolicy"= "<boolean>"
? "includeOnlyDependencies"= "<boolean>"
? "includeGatewayConfiguration"= "<boolean>"


// This will import a batch of bundles.
// Import Bundles
// 1.0.4

@name("Imports Batch of Bundles")
PUT "https://{{baseUrl}}/1.0/bundle/batch"
? "test"= "<boolean>"
? "activate"= "<boolean>"
? "versionComment"= "<string>"


// Returns the bundle for the given resource type. The resource type is either a policy, service, or folder
// Export Folder Service Or Policy Bundle
// Folder, Service or Policy Export

@name("Exports Bundle By Resource Type And ID")
GET "https://{{baseUrl}}/1.0/bundle/:resourceType/:id"
? "defaultAction"= "<string>"
? "defaultMapBy"= "<string>"
? "includeRequestFolder"= "<boolean>"
? "exportGatewayRestManagementService"= "<boolean>"
? "includeDependencies"= "<boolean>"
? "encryptSecrets"= "<boolean>"
? "encryptUsingClusterPassphrase"= "<boolean>"
? "includeOnlyServicePolicy"= "<boolean>"
? "includeOnlyDependencies"= "<boolean>"



