#!/usr/bin/env dothttp

@name("{{baseUrl}}/TenantCnames/Get")
POST "https://{{baseUrl}}/TenantCnames/Get"


@name("{{baseUrl}}/TenantCnames/GetDomainInfo")
POST "https://{{baseUrl}}/TenantCnames/GetDomainInfo"


// If the cname is the only user created, it is set as preferred cname.
@name("{{baseUrl}}/TenantCnames/Register")
POST "https://{{baseUrl}}/TenantCnames/Register"
? "cnamePrefix"= "<string>"


@name("{{baseUrl}}/TenantCnames/SetPreferred")
POST "https://{{baseUrl}}/TenantCnames/SetPreferred"
? "customCname"= "<string>"


@name("{{baseUrl}}/TenantCnames/UiGet")
POST "https://{{baseUrl}}/TenantCnames/UiGet"


@name("{{baseUrl}}/TenantCnames/UnRegister")
POST "https://{{baseUrl}}/TenantCnames/UnRegister"
? "customCname"= "<string>"



