#!/usr/bin/env dothttp

// View the Change Log for your organization

@name("View the Change Log for your organization")
GET "https://{{baseUrl}}/organizations/:organizationId/configurationChanges"
"X-Cisco-Meraki-API-Key": ""
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "perPage"= "{{perPage}}"
? "startingAfter"= "{{startingAfter}}"
? "endingBefore"= "{{endingBefore}}"
? "networkId"= "{{networkId}}"
? "adminId"= "{{adminId}}"



