#!/usr/bin/env dothttp

// Pulls a list of COVID-19 testing locations for the state.
@name("Arizona")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("California")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("Delaware")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("Florida")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("Massachusetts")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("Nevada")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("New Jersey")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("New York")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("Pennsylvania")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("Texas")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("Utah")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"


// Pulls a list of COVID-19 testing locations for the state.
@name("Washington")
GET "https://covid-19-testing.github.io/locations/:state/complete.json"



