#!/usr/bin/env dothttp

@name("API Login")
POST "https://{{host}}/api/login"
"Content-Type": "application/json"
json({
    "username": "admin",
    "password": "1"
})


@name("API Register")
POST "https://{{host}}/api/register"
json({
    "email": "c@admin.com",
    "name": "CCC",
    "password": "1"
})


@name("API Change Password")
GET "https://{{host}}/"



