#!/usr/bin/env dothttp

// This call fetches all the relations which are linked to the specified API version along with their details.// // The response will contain a `relations` object which lists all the relation types which are linked to the API version. Each of the relation type will be an object which details the relations of this type. // // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Get linked relations")
GET "https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/relations"


// This call fetches all the relations by type which are linked to the specified API version along with their details.// // The response will contain an array with key `{{relationType}}`. Each of the item will consist of all the details related each of the relation.// // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Get  documentation relations")
GET "https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/documentation"


// This call fetches all the relations by type which are linked to the specified API version along with their details.// // The response will contain an array with key `{{relationType}}`. Each of the item will consist of all the details related each of the relation.// // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Get environment relations")
GET "https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/environment"


// This call fetches all the relations by type which are linked to the specified API version along with their details.// // The response will contain an array with key `{{relationType}}`. Each of the item will consist of all the details related each of the relation.// // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Get test suite relations")
GET "https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/testsuite"


// This call fetches all the relations by type which are linked to the specified API version along with their details.// // The response will contain an array with key `{{relationType}}`. Each of the item will consist of all the details related each of the relation.// // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Get contract test relations")
GET "https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/contracttest"


// This call fetches all the relations by type which are linked to the specified API version along with their details.// // The response will contain an array with key `{{relationType}}`. Each of the item will consist of all the details related each of the relation.// // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Get integration test relations")
GET "https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/integrationtest"


// This call fetches all the relations by type which are linked to the specified API version along with their details.// // The response will contain an array with key `{{relationType}}`. Each of the item will consist of all the details related each of the relation.// // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Get monitor relations")
GET "https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/monitor"


// This call allows you to add existing Postman entities as new relations to an API. The request body should contain the relations to be created along with an array of entity IDs. // // <table>//   <tr>//     <th>Relation</th>//     <th>Entity ID type</th>//   <tr>//   <tr>//     <td>contracttest</td>//     <td>Collection UIDs</td>//   </tr>//   <tr>//     <td>integrationtest</td>//     <td>Collection UIDs</td>//   </tr>//   <tr>//     <td>documentation</td>//     <td>Collection UIDs</td>//   </tr>//   <tr>//     <td>testsuite</td>//     <td>Collection UIDs</td>//   </tr>//   <tr>//     <td>environment</td>//     <td>Environment UIDs</td>//   </tr>//   <tr>//     <td>mock</td>//     <td>Mock IDs</td>//   </tr>//   <tr>//     <td>monitor</td>//     <td>Monitor IDs</td>//   </tr>// </table>// // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Create relations")
POST "https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/relations"
"Content-Type": "application/json"
json({
    "contracttest": [
        "collection-uid-1"
    ],
    "testsuite": [
        "collection-uid-1",
        "collection-uid-2"
    ],
    "documentation": [
        "collection-uid-3"
    ],
    "mock": [
        "mock-uid-1"
    ]
})


// This call allows you to keep the relation in sync with the API schema.// // // > Requires <a href="#authentication">API Key</a> as `X-Api-Key` request header or `apikey` URL query parameter.
@name("Sync relations with schema")
PUT "https://api.getpostman.com/apis/:apiId/versions/:apiVersionId/:entityType/:entityId/syncWithSchema"



