#!/usr/bin/env dothttp

@name("Hide a reply")
PUT "https://api.twitter.com/2/tweets/:id/hidden"
"Content-Type": "application/json"
data('{
    "hidden": true
}')


@name("Unide a reply")
PUT "https://api.twitter.com/2/tweets/:id/hidden"
"Content-Type": "application/json"
data('{
    "hidden": false
}')



