#!/usr/bin/env dothttp

// Get Alias Data by AppID

@name("/getAliasDataByAppID")
POST "https://{{baseUrl}}/getAliasDataByAppID"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "oa_app_id": "anim Lorem non voluptate",
    "oa_object_id": "irure Lorem ad deserunt"
})


// Save Alias Data

@name("/saveAliasData")
POST "https://{{baseUrl}}/saveAliasData"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "oa_guid": "nostrud fugiat pariatur incididunt eu",
    "oa_app_id": "laborum",
    "oa_object_id": "nostrud ullamco",
    "oa_display_conf": "aliq",
    "oa_status": "consectetur ad"
})


// Update Alias Data

@name("/updateAliasData")
POST "https://{{baseUrl}}/updateAliasData"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "entity": {
        "oa_app_id": "Duis exercitation adipisicing deserunt",
        "oa_object_id": "irure",
        "oa_display_conf": "officia",
        "oa_status": "ut sunt voluptate minim"
    },
    "cond": {
        "oa_app_id": "esse reprehenderi",
        "oa_object_id": "quis consectetur officia",
        "oa_display_conf": "voluptate dolore aute ex",
        "oa_status": "in ut"
    }
})


// Add User Project Templates

@name("/addUserProjectTemplates")
POST "https://{{baseUrl}}/addUserProjectTemplates"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "upt_guid": "in cillum eu consequat",
        "upt_temp_guid": "incididunt ipsum veniam",
        "upt_user_guid": "ut proident in sunt officia",
        "upt_proj_guid": "esse et ipsum in",
        "upt_global": true
    }
})


// Add Template

@name("/addABTemplate")
POST "https://{{baseUrl}}/addABTemplate"
"jwt": "esse minim anim"
"Content-Type": "application/json"
data('"veniam esse et laboris"')


// Get Templates

@name("/getABTemplates")
POST "https://{{baseUrl}}/getABTemplates"
"jwt": "esse minim anim"


// Get Template by Template Id

@name("/getABTemplateByTemplateId")
POST "https://{{baseUrl}}/getABTemplateByTemplateId"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "at_guid": "tempor ex sunt"
})


// Bind Object

@name("/bindObject")
POST "https://{{baseUrl}}/bindObject"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "ao_oguid": "dolor sint incididunt",
        "app_oguid": "aliqua in",
        "object_oguid": "nisi quis",
        "object_type": "velit mollit",
        "ao_created_by": "enim culpa consectetur",
        "ao_status": "do ex est"
    }
})


// Unbind Object

@name("/unbindObject")
POST "https://{{baseUrl}}/unbindObject"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "ao_oguid": "veniam aliquip Ut"
    }
})


// Fetch Object

@name("/fetchObject")
POST "https://{{baseUrl}}/fetchObject"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "ao_oguid": "veniam aliquip Ut"
    }
})


// Save Object Data Relation

@name("/saveObjectDataRelation")
POST "https://{{baseUrl}}/saveObjectDataRelation"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "odr_oguid": "sint dolore do",
        "odr_app_id": "culpa officia laborum",
        "odr_project_id": "consectetur aliqua pariatur aute ut",
        "odr_template_id": "elit",
        "odr_ui_comp_id": "mollit incididunt",
        "odr_ui_comp_type": "in velit nostrud id",
        "odr_connection_id": "commodo",
        "odr_build_from": "voluptate in fugiat enim sunt",
        "odr_table_name": "do mollit",
        "odr_type": "sed deserunt minim incididunt sint",
        "odr_object_id": "amet Excepteur labore",
        "odr_sql_template": "qui ex voluptate et Excepteur",
        "odr_display_conf": "Duis ipsum"
    }
})


// Bulk Save Object Data Relation

@name("/bulkSaveObjectDataRelation")
POST "https://{{baseUrl}}/bulkSaveObjectDataRelation"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": [
        {
            "odr_oguid": "do",
            "odr_app_id": "nulla qui reprehenderit",
            "odr_project_id": "quis ullamco",
            "odr_template_id": "sint dolor",
            "odr_ui_comp_id": "proident",
            "odr_ui_comp_type": "eu amet",
            "odr_connection_id": "ex reprehenderit",
            "odr_build_from": "minim nisi",
            "odr_table_name": "ea commodo",
            "odr_type": "pariatur deserunt ipsum",
            "odr_object_id": "ipsum ",
            "odr_sql_template": "dolore Lorem",
            "odr_display_conf": "dolore culpa"
        },
        {
            "odr_oguid": "adipisicing in",
            "odr_app_id": "voluptate sunt ea",
            "odr_project_id": "ullamco ut",
            "odr_template_id": "adipisicing veniam ut",
            "odr_ui_comp_id": "in al",
            "odr_ui_comp_type": "est",
            "odr_connection_id": "labore consectetur",
            "odr_build_from": "laborum magna quis sed",
            "odr_table_name": "sunt laborum reprehenderit velit",
            "odr_type": "e",
            "odr_object_id": "ad ea",
            "odr_sql_template": "velit officia enim commodo",
            "odr_display_conf": "voluptate Ut"
        }
    ]
})


// Delete Object Data Relation

@name("/deleteObjectDataRelation")
POST "https://{{baseUrl}}/deleteObjectDataRelation"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "odr_oguid": "minim sed"
    }
})


// Get Object Data Relation

@name("/getObjectDataRelation")
POST "https://{{baseUrl}}/getObjectDataRelation"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "odr_oguid": "minim sed"
    }
})


// Get Cust Application Data

@name("/getCustApplicationData")
POST "https://{{baseUrl}}/getCustApplicationData"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "ca_oguid": "exercitation dolore in Duis nulla"
    }
})


// Save Application MetaData

@name("/saveApplicationMetaData")
POST "https://{{baseUrl}}/saveApplicationMetaData"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "ca_oguid": "commodo Duis",
        "ca_project_id": "aliquip ad et",
        "ca_app_name": "culpa esse consectetur",
        "ca_app_url": "esse",
        "ca_template_id": "exercitation",
        "ca_generated_application": "Duis",
        "ca_created_by": "commodo reprehenderit in sunt",
        "ca_status": "nostrud"
    }
})


// Update Application

@name("/updateApplication")
POST "https://{{baseUrl}}/updateApplication"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "ca_oguid": "commodo Duis",
        "ca_project_id": "aliquip ad et",
        "ca_app_name": "culpa esse consectetur",
        "ca_app_url": "esse",
        "ca_template_id": "exercitation",
        "ca_generated_application": "Duis",
        "ca_created_by": "commodo reprehenderit in sunt",
        "ca_status": "nostrud"
    }
})


// Delete Application

@name("/deleteApplication")
POST "https://{{baseUrl}}/deleteApplication"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "ca_oguid": "exercitation dolore in Duis nulla"
    }
})


// Get Applications by App Id

@name("/getApplicationsByAppId")
POST "https://{{baseUrl}}/getApplicationsByAppId"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "ca_oguid": "exercitation dolore in Duis nulla"
    }
})


// Get Applications by Project Id

@name("/getApplicationsByProjectId")
POST "https://{{baseUrl}}/getApplicationsByProjectId"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "odr_project_id": "qui nulla mollit"
    }
})


// Get Applications by Connection Id

@name("/getApplicationsByConnectionId")
POST "https://{{baseUrl}}/getApplicationsByConnectionId"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "odr_connection_id": "id veniam"
    }
})


// Update Object Data Relation

@name("/updateComponentRelation")
POST "https://{{baseUrl}}/updateComponentRelation"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "entity": {
        "odr_app_id": "aliquip sit esse amet",
        "odr_project_id": "commodo ea irure et",
        "odr_template_id": "in magna cupidatat nostrud",
        "odr_ui_comp_id": "ad ullamco minim",
        "odr_ui_comp_type": "ullamco Duis do",
        "odr_connection_id": "magna laboris mollit",
        "odr_build_from": "nostrud ipsum non veniam fugiat",
        "odr_table_name": "Lorem aute",
        "odr_type": "reprehenderit elit Excepteur ex est",
        "odr_object_id": "do ut",
        "odr_sql_template": "do qui est",
        "odr_display_conf": "nulla"
    },
    "cond": {
        "odr_oguid": "culpa dolor"
    }
})


// Get Cust App with current project and user

@name("/getCurrentApplications")
POST "https://{{baseUrl}}/getCurrentApplications"
"jwt": "esse minim anim"


// Save App Page

@name("/appPage")
POST "https://{{baseUrl}}/appPage"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": {
        "pageData": [
            {
                "ap_generated_page": "sed laboris minim",
                "ap_page_name": "occaecat",
                "ap_page_config_json": "irure"
            },
            {
                "ap_generated_page": "dolore et velit minim qui",
                "ap_page_name": "in dolor ea",
                "ap_page_config_json": "officia anim"
            }
        ],
        "url": "Duis ex enim"
    }
})


// Save User Project Page

@name("/userProjectPage")
POST "https://{{baseUrl}}/userProjectPage"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "data": [
        {
            "upp_app_guid": "aliqua",
            "upp_proj_guid": "ex in",
            "upp_page_guid": "Ut amet Excepteur"
        },
        {
            "upp_app_guid": "ut anim sint",
            "upp_proj_guid": "anim voluptate fugiat",
            "upp_page_guid": "officia anim non id ut"
        }
    ]
})


// Update Template Type

@name("/updateABTemplateType")
POST "https://{{baseUrl}}/updateABTemplateType"
"jwt": "esse minim anim"
"Content-Type": "application/json"
json({
    "at_guid": "incididunt esse",
    "at_type": "ut aute fugiat magna"
})



