#!/usr/bin/env dothttp

@name("Data Use Purpose Share")
GET "https://{{host}}/services/data/v47.0/sobjects/DataUsePurposeShare/"


@name("Data Use Purpose Share Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/DataUsePurposeShare/{ID}/"


@name("Describe Data Use Purpose Share")
GET "https://{{host}}/services/data/v47.0/sobjects/DataUsePurposeShare/describe/"



