#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Selectable Issue Field Options")
GET "https://{{baseUrl}}/rest/api/3/field/:fieldKey/option/suggestions/edit"
? "startAt"= "0"
? "maxResults"= "50"
? "projectId"= "<long>"


@name("Get Visible Issue Field Options")
GET "https://{{baseUrl}}/rest/api/3/field/:fieldKey/option/suggestions/search"
? "startAt"= "0"
? "maxResults"= "<integer>"
? "projectId"= "<long>"



