#!/usr/bin/env dothttp

@name("/wc/v3/products/attributes/:attribute_id/terms/:id")
GET "https://{{baseUrl}}/wc/v3/products/attributes/:attribute_id/terms/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "context"= "view"
? "context"= "view"


@name("/wc/v3/products/attributes/:attribute_id/terms/:id")
POST "https://{{baseUrl}}/wc/v3/products/attributes/:attribute_id/terms/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
"Content-Type": "multipart/form-data"
files(
	("name", "<string>"),
	("slug", "<string>"),
	("description", "<string>"),
	("menu_order", "<string>")
)


@name("/wc/v3/products/attributes/:attribute_id/terms/:id")
PUT "https://{{baseUrl}}/wc/v3/products/attributes/:attribute_id/terms/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "name"= "<string>"
? "slug"= "<string>"
? "description"= "<string>"
? "menu_order"= "<string>"


@name("/wc/v3/products/attributes/:attribute_id/terms/:id")
PATCH "https://{{baseUrl}}/wc/v3/products/attributes/:attribute_id/terms/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "name"= "<string>"
? "slug"= "<string>"
? "description"= "<string>"
? "menu_order"= "<string>"


@name("/wc/v3/products/attributes/:attribute_id/terms/:id")
DELETE "https://{{baseUrl}}/wc/v3/products/attributes/:attribute_id/terms/:id"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "force"= "<string>"



