#!/usr/bin/env dothttp

// Retrieve a list of all bounce events and details about them - message, contact and campaign IDs, timestamp etc.
// 
// Note: If no query parameters are used, will return events with FromTS equal to the current day at 00:00 UTC.

@name("Retrieve All Bounce Events")
GET "https://api.mailjet.com/v3/REST/bouncestatistics"
basicauth("{{Enter your API Key here}}", "{{Enter your Secret Key here}}")
? "CampaignID"= "{{CampaignID}}"
? "ContactsList"= "{{ListID}}"
? "EventFromTs"= "2018-01-01T00:00:00"
? "EventToTs"= "2018-01-01T00:00:00"
? "FromTS"= "2018-01-01T00:00:00"
? "Period"= "month"
? "ToTS"= "2018-01-01T00:00:00"
? "Limit"= "1000"
? "Offset"= "0"
? "countOnly"= "false"
? "Sort"= "{{property_name+ASC_or_DESC}}"


// Retrieve information about a specific bounce event.
// 

@name("Retrieve a Single Bounce Event")
GET "https://api.mailjet.com/v3/REST/bouncestatistics/{{message_ID}}"
basicauth("{{Enter your API Key here}}", "{{Enter your Secret Key here}}")


// Retrieve a list of all click events and details about them - message and contact IDs, timestamp, URL and click delay.
// 
// Note: If no query parameters are used, will return events with FromTS equal to the current day at 00:00 UTC.

@name("Retrieve All Click Events")
GET "https://api.mailjet.com/v3/REST/clickstatistics"
basicauth("{{Enter your API Key here}}", "{{Enter your Secret Key here}}")
? "CampaignID"= "{{CampaignID}}"
? "ContactsList"= "{{ListID}}"
? "CustomCampaign"= "{{CustomValue}}"
? "EventFromTs"= "2018-01-01T00:00:00"
? "EventToTs"= "2018-01-01T00:00:00"
? "FromTS"= "2018-01-01T00:00:00"
? "From"= "{{FromEmail}}"
? "FromDomain"= "{{FromDomain}}"
? "FromID"= "{{FromID}}"
? "FromType"= "2"
? "IsDeleted"= "false"
? "IsNewsletterTool"= "true"
? "MessageID"= "{{MessageID}}"
? "MessageStatus"= "4"
? "Period"= "month"
? "ToTS"= "2018-01-01T00:00:00"
? "Limit"= "1000"
? "Offset"= "0"
? "countOnly"= "false"
? "Sort"= "{{property_name+ASC_or_DESC}}"


// Retrieve a list of all open events and details about them - message, campaign and contact IDs, timestamp etc.
// 
// If no query parameters are used, will return events with FromTS equal to the current day at 00:00 UTC.

@name("Retrieve All Open Events")
GET "https://api.mailjet.com/v3/REST/openinformation"
basicauth("{{Enter your API Key here}}", "{{Enter your Secret Key here}}")
? "CampaignID"= "{{CampaignID}}"
? "ContactsList"= "{{ListID}}"
? "CustomCampaign"= "{{CustomValue}}"
? "EventFromTs"= "2018-01-01T00:00:00"
? "EventToTs"= "2018-01-01T00:00:00"
? "FromTS"= "2018-01-01T00:00:00"
? "From"= "{{FromEmail}}"
? "FromDomain"= "{{FromDomain}}"
? "FromID"= "{{FromID}}"
? "FromType"= "2"
? "IsDeleted"= "true"
? "MessageStatus"= "3"
? "Period"= "month"
? "ToTS"= "2018-01-01T00:00:00"
? "Limit"= "1000"
? "Offset"= "0"
? "countOnly"= "false"
? "Sort"= "{{property_name+ASC_or_DESC}}"


// Retrieve open event details for a specific message.

@name("Retrieve a Single Open Event")
GET "https://api.mailjet.com/v3/REST/openinformation/{{message_ID}}"
basicauth("{{Enter your API Key here}}", "{{Enter your Secret Key here}}")



