#!/usr/bin/env dothttp

@name("Retrieves a single CustomerPolicy identified by the supplied ID")
GET "https://{{baseUrl}}/security/v1/customerpolicys/:id"
"Authorization": "<string>"
"If-None-Match": "<string>"


@name("Creates or updates an CustomerPolicy with a specific ID")
PUT "https://{{baseUrl}}/security/v1/customerpolicys/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "features": [
        "[\"<string>\",\"<string>\"]"
    ],
    "statements": [
        "[\"<string>\",\"<string>\"]"
    ],
    "expires": [
        "<dateTime>"
    ],
    "customer": [
        "<string>"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isConfiguration": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})



