#!/usr/bin/env dothttp

@name("Account")
GET "https://{{host}}/services/data/v47.0/sobjects/Account/"


@name("Account Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Account/{ID}/"


@name("Describe Account")
GET "https://{{host}}/services/data/v47.0/sobjects/Account/describe/"



