#!/usr/bin/env dothttp

# imported from http://localhost:8000/Stripe%20API.postman_collection.json

@name("Create an account link")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f605190a4f0>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "account": [
        "<string>"
    ],
    "type": [
        "<string>"
    ],
    "collect": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "refresh_url": [
        "<string>"
    ],
    "return_url": [
        "<string>"
    ]
})


@name("List all connected accounts")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f60519136d0>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Create an account")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604be62910>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "account_token": [
        "<string>"
    ],
    "bank_account[account_number]": [
        "<string>"
    ],
    "bank_account[country]": [
        "<string>"
    ],
    "bank_account[account_holder_name]": [
        "<string>"
    ],
    "bank_account[account_holder_type]": [
        "<string>"
    ],
    "bank_account[currency]": [
        "<string>"
    ],
    "bank_account[object]": [
        "<string>"
    ],
    "bank_account[routing_number]": [
        "<string>"
    ],
    "business_profile[mcc]": [
        "<string>"
    ],
    "business_profile[name]": [
        "<string>"
    ],
    "business_profile[product_description]": [
        "<string>"
    ],
    "business_profile[support_address]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\"}"
    ],
    "business_profile[support_email]": [
        "<string>"
    ],
    "business_profile[support_phone]": [
        "<string>"
    ],
    "business_profile[support_url]": [
        "<string>"
    ],
    "business_profile[url]": [
        "<string>"
    ],
    "business_type": [
        "<string>"
    ],
    "capabilities[acss_debit_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[afterpay_clearpay_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[au_becs_debit_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[bacs_debit_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[bancontact_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[card_issuing]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[card_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[cartes_bancaires_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[eps_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[fpx_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[giropay_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[grabpay_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[ideal_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[jcb_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[legacy_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[oxxo_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[p24_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[sepa_debit_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[sofort_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[tax_reporting_us_1099_k]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[tax_reporting_us_1099_misc]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[transfers]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "company[address]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\"}"
    ],
    "company[address_kana]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\",\"town\":\"<string>\"}"
    ],
    "company[address_kanji]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\",\"town\":\"<string>\"}"
    ],
    "company[directors_provided]": [
        "<boolean>"
    ],
    "company[executives_provided]": [
        "<boolean>"
    ],
    "company[name]": [
        "<string>"
    ],
    "company[name_kana]": [
        "<string>"
    ],
    "company[name_kanji]": [
        "<string>"
    ],
    "company[owners_provided]": [
        "<boolean>"
    ],
    "company[phone]": [
        "<string>"
    ],
    "company[registration_number]": [
        "<string>"
    ],
    "company[structure]": [
        "<string>"
    ],
    "company[tax_id]": [
        "<string>"
    ],
    "company[tax_id_registrar]": [
        "<string>"
    ],
    "company[vat_id]": [
        "<string>"
    ],
    "company[verification]": [
        "{\"document\":{\"back\":\"<string>\",\"front\":\"<string>\"}}"
    ],
    "country": [
        "<string>"
    ],
    "default_currency": [
        "<string>"
    ],
    "documents[bank_account_ownership_verification]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_license]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_memorandum_of_association]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_ministerial_decree]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_registration_verification]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_tax_id_verification]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "email": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "external_account": [
        "<string>"
    ],
    "individual[address]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\"}"
    ],
    "individual[address_kana]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\",\"town\":\"<string>\"}"
    ],
    "individual[address_kanji]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\",\"town\":\"<string>\"}"
    ],
    "individual[dob]": [
        "{\"day\":\"<integer>\",\"month\":\"<integer>\",\"year\":\"<integer>\"}"
    ],
    "individual[email]": [
        "<string>"
    ],
    "individual[first_name]": [
        "<string>"
    ],
    "individual[first_name_kana]": [
        "<string>"
    ],
    "individual[first_name_kanji]": [
        "<string>"
    ],
    "individual[gender]": [
        "<string>"
    ],
    "individual[id_number]": [
        "<string>"
    ],
    "individual[last_name]": [
        "<string>"
    ],
    "individual[last_name_kana]": [
        "<string>"
    ],
    "individual[last_name_kanji]": [
        "<string>"
    ],
    "individual[maiden_name]": [
        "<string>"
    ],
    "individual[metadata]": [
        "<object>"
    ],
    "individual[phone]": [
        "<string>"
    ],
    "individual[political_exposure]": [
        "<string>"
    ],
    "individual[ssn_last_4]": [
        "<string>"
    ],
    "individual[verification]": [
        "{\"additional_document\":{\"back\":\"<string>\",\"front\":\"<string>\"},\"document\":{\"back\":\"<string>\",\"front\":\"<string>\"}}"
    ],
    "settings[branding]": [
        "{\"icon\":\"<string>\",\"logo\":\"<string>\",\"primary_color\":\"<string>\",\"secondary_color\":\"<string>\"}"
    ],
    "settings[card_issuing]": [
        "{\"tos_acceptance\":{\"date\":\"<unix-time>\",\"ip\":\"<string>\",\"user_agent\":\"<string>\"}}"
    ],
    "settings[card_payments]": [
        "{\"decline_on\":{\"avs_failure\":\"<boolean>\",\"cvc_failure\":\"<boolean>\"},\"statement_descriptor_prefix\":\"<string>\"}"
    ],
    "settings[payments]": [
        "{\"statement_descriptor\":\"<string>\",\"statement_descriptor_kana\":\"<string>\",\"statement_descriptor_kanji\":\"<string>\"}"
    ],
    "settings[payouts]": [
        "{\"debit_negative_balances\":\"<boolean>\",\"schedule\":{\"delay_days\":\"<string>\",\"interval\":\"<string>\",\"monthly_anchor\":\"<integer>\",\"weekly_anchor\":\"<string>\"},\"statement_descriptor\":\"<string>\"}"
    ],
    "tos_acceptance[date]": [
        "<unix-time>"
    ],
    "tos_acceptance[ip]": [
        "<string>"
    ],
    "tos_acceptance[service_agreement]": [
        "<string>"
    ],
    "tos_acceptance[user_agent]": [
        "<string>"
    ],
    "type": [
        "<string>"
    ]
})


@name("Delete an account")
DELETE "<dotextensions.server.postman2_1.URLClass object at 0x7f604be6ca30>"
"Content-Type": "application/x-www-form-urlencoded"



@name("Retrieve account")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604be725b0>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Update an account")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604be72be0>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "account_token": [
        "<string>"
    ],
    "bank_account[account_number]": [
        "<string>"
    ],
    "bank_account[country]": [
        "<string>"
    ],
    "bank_account[account_holder_name]": [
        "<string>"
    ],
    "bank_account[account_holder_type]": [
        "<string>"
    ],
    "bank_account[currency]": [
        "<string>"
    ],
    "bank_account[object]": [
        "<string>"
    ],
    "bank_account[routing_number]": [
        "<string>"
    ],
    "business_profile[mcc]": [
        "<string>"
    ],
    "business_profile[name]": [
        "<string>"
    ],
    "business_profile[product_description]": [
        "<string>"
    ],
    "business_profile[support_address]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\"}"
    ],
    "business_profile[support_email]": [
        "<string>"
    ],
    "business_profile[support_phone]": [
        "<string>"
    ],
    "business_profile[support_url]": [
        "<string>"
    ],
    "business_profile[url]": [
        "<string>"
    ],
    "business_type": [
        "<string>"
    ],
    "capabilities[acss_debit_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[afterpay_clearpay_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[au_becs_debit_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[bacs_debit_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[bancontact_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[card_issuing]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[card_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[cartes_bancaires_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[eps_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[fpx_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[giropay_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[grabpay_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[ideal_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[jcb_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[legacy_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[oxxo_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[p24_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[sepa_debit_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[sofort_payments]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[tax_reporting_us_1099_k]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[tax_reporting_us_1099_misc]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "capabilities[transfers]": [
        "{\"requested\":\"<boolean>\"}"
    ],
    "company[address]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\"}"
    ],
    "company[address_kana]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\",\"town\":\"<string>\"}"
    ],
    "company[address_kanji]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\",\"town\":\"<string>\"}"
    ],
    "company[directors_provided]": [
        "<boolean>"
    ],
    "company[executives_provided]": [
        "<boolean>"
    ],
    "company[name]": [
        "<string>"
    ],
    "company[name_kana]": [
        "<string>"
    ],
    "company[name_kanji]": [
        "<string>"
    ],
    "company[owners_provided]": [
        "<boolean>"
    ],
    "company[phone]": [
        "<string>"
    ],
    "company[registration_number]": [
        "<string>"
    ],
    "company[structure]": [
        "<string>"
    ],
    "company[tax_id]": [
        "<string>"
    ],
    "company[tax_id_registrar]": [
        "<string>"
    ],
    "company[vat_id]": [
        "<string>"
    ],
    "company[verification]": [
        "{\"document\":{\"back\":\"<string>\",\"front\":\"<string>\"}}"
    ],
    "default_currency": [
        "<string>"
    ],
    "documents[bank_account_ownership_verification]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_license]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_memorandum_of_association]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_ministerial_decree]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_registration_verification]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "documents[company_tax_id_verification]": [
        "{\"files\":[\"<string>\",\"<string>\"]}"
    ],
    "email": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "external_account": [
        "<string>"
    ],
    "individual[address]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\"}"
    ],
    "individual[address_kana]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\",\"town\":\"<string>\"}"
    ],
    "individual[address_kanji]": [
        "{\"city\":\"<string>\",\"country\":\"<string>\",\"line1\":\"<string>\",\"line2\":\"<string>\",\"postal_code\":\"<string>\",\"state\":\"<string>\",\"town\":\"<string>\"}"
    ],
    "individual[dob]": [
        "{\"day\":\"<integer>\",\"month\":\"<integer>\",\"year\":\"<integer>\"}"
    ],
    "individual[email]": [
        "<string>"
    ],
    "individual[first_name]": [
        "<string>"
    ],
    "individual[first_name_kana]": [
        "<string>"
    ],
    "individual[first_name_kanji]": [
        "<string>"
    ],
    "individual[gender]": [
        "<string>"
    ],
    "individual[id_number]": [
        "<string>"
    ],
    "individual[last_name]": [
        "<string>"
    ],
    "individual[last_name_kana]": [
        "<string>"
    ],
    "individual[last_name_kanji]": [
        "<string>"
    ],
    "individual[maiden_name]": [
        "<string>"
    ],
    "individual[metadata]": [
        "<object>"
    ],
    "individual[phone]": [
        "<string>"
    ],
    "individual[political_exposure]": [
        "<string>"
    ],
    "individual[ssn_last_4]": [
        "<string>"
    ],
    "individual[verification]": [
        "{\"additional_document\":{\"back\":\"<string>\",\"front\":\"<string>\"},\"document\":{\"back\":\"<string>\",\"front\":\"<string>\"}}"
    ],
    "settings[branding]": [
        "{\"icon\":\"<string>\",\"logo\":\"<string>\",\"primary_color\":\"<string>\",\"secondary_color\":\"<string>\"}"
    ],
    "settings[card_issuing]": [
        "{\"tos_acceptance\":{\"date\":\"<unix-time>\",\"ip\":\"<string>\",\"user_agent\":\"<string>\"}}"
    ],
    "settings[card_payments]": [
        "{\"decline_on\":{\"avs_failure\":\"<boolean>\",\"cvc_failure\":\"<boolean>\"},\"statement_descriptor_prefix\":\"<string>\"}"
    ],
    "settings[payments]": [
        "{\"statement_descriptor\":\"<string>\",\"statement_descriptor_kana\":\"<string>\",\"statement_descriptor_kanji\":\"<string>\"}"
    ],
    "settings[payouts]": [
        "{\"debit_negative_balances\":\"<boolean>\",\"schedule\":{\"delay_days\":\"<string>\",\"interval\":\"<string>\",\"monthly_anchor\":\"<integer>\",\"weekly_anchor\":\"<string>\"},\"statement_descriptor\":\"<string>\"}"
    ],
    "tos_acceptance[date]": [
        "<unix-time>"
    ],
    "tos_acceptance[ip]": [
        "<string>"
    ],
    "tos_acceptance[service_agreement]": [
        "<string>"
    ],
    "tos_acceptance[user_agent]": [
        "<string>"
    ]
})


@name("List all account capabilities")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604be04bb0>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Retrieve an account capability")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604be063d0>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Update an account capability")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604be06d90>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "requested": [
        "<boolean>"
    ]
})


@name("Retrieve all bank accounts or cards")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604be118e0>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Create a bank account or card")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604be11d00>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "bank_account[account_number]": [
        "<string>"
    ],
    "bank_account[country]": [
        "<string>"
    ],
    "bank_account[account_holder_name]": [
        "<string>"
    ],
    "bank_account[account_holder_type]": [
        "<string>"
    ],
    "bank_account[currency]": [
        "<string>"
    ],
    "bank_account[object]": [
        "<string>"
    ],
    "bank_account[routing_number]": [
        "<string>"
    ],
    "default_for_currency": [
        "<boolean>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "external_account": [
        "<string>"
    ]
})


@name("Delete a bank account or card")
DELETE "<dotextensions.server.postman2_1.URLClass object at 0x7f604be0f130>"
"Content-Type": "application/x-www-form-urlencoded"



@name("Retrieve a bank account or card")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604be0f7c0>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Update a bank account or card")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604be200a0>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "account_holder_name": [
        "<string>"
    ],
    "account_holder_type": [
        "<string>"
    ],
    "address_city": [
        "<string>"
    ],
    "address_country": [
        "<string>"
    ],
    "address_line1": [
        "<string>"
    ],
    "address_line2": [
        "<string>"
    ],
    "address_state": [
        "<string>"
    ],
    "address_zip": [
        "<string>"
    ],
    "default_for_currency": [
        "<boolean>"
    ],
    "exp_month": [
        "<string>"
    ],
    "exp_year": [
        "<string>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "name": [
        "<string>"
    ]
})


@name("Create an account link")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f604be247c0>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "redirect_url": [
        "<string>"
    ]
})



