#!/usr/bin/env dothttp

// Returns the application categories for traffic shaping rules.

@name("Returns the application categories for traffic shaping rules.")
GET "https://{{baseUrl}}/networks/:networkId/trafficShaping/applicationCategories"
"X-Cisco-Meraki-API-Key": ""



