#!/usr/bin/env dothttp

// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-campaigns-list-campaigns)

@name("List all campaigns")
GET "https://{{base-url}}/accounts/me/crm/campaigns/"


// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-campaigns-retrieve-a-campaign)

@name("Retrieve a campaign")
GET "https://{{base-url}}/accounts/me/crm/campaigns/$CAMPAIGN_ID/"


// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-campaigns-create-a-campaign)

@name("Create a campaign")
POST "https://{{base-url}}/accounts/me/crm/campaigns/"
"Content-Type": "application/json"
data('{
  "campaign_type": "string",
  "status": "string",
  "end": "string",
  "name": "string",
  "parent": "string",
  "start": "string",
  "description": "string",
  "actual_cost": 0,
  "expected_revenue": 0,
  "raw": "string",
  "owner": "string",
  "id": "string",
  "budgeted_cost": 0
}')


// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-campaigns-update-a-campaign)

@name("Update a campaign")
PATCH "https://{{base-url}}/accounts/me/crm/campaigns/$CAMPAIGN_ID/"
"Content-Type": "application/json"
data('{
  "campaign_type": "string",
  "status": "string",
  "end": "string",
  "name": "string",
  "parent": "string",
  "start": "string",
  "description": "string",
  "actual_cost": 0,
  "expected_revenue": 0,
  "raw": "string",
  "owner": "string",
  "id": "string",
  "budgeted_cost": 0
}')


// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-campaigns-delete-a-campaign)

@name("Delete a campaign")
DELETE "https://{{base-url}}/accounts/me/crm/campaigns/$CAMPAIGN_ID/"



