#!/usr/bin/env dothttp

// Get a list of paginated offer lines.

@name("List offer lines")
GET "https://{{api_url}}/offers/{{offer_number}}/lines"
"Content-Type": "application/json"
"Accept": "application/json"
? "limit"= "15"
? "type"= "text"


// Retrieve an offer line.

@name("Retrieve an offer line")
GET "https://{{api_url}}/offers/{{offer_number}}/lines/{{offer_line_id}}"
"Content-Type": "application/json"
"Accept": "application/json"


// Create a new offer line.

@name("Create a new offer line")
POST "https://{{api_url}}/offers/{{offer_number}}/lines"
"Content-Type": "application/json"
"Accept": "application/json"
data('{
	"type": "regular",
	"content": "My custom line description",
	"unit": "",
	"quantity": 2,
	"price_inc_vat": 10,
	"vat_percentage": 6
}')


// Update an existing offer line.

@name("Update an offer line")
PATCH "https://{{api_url}}/offers/{{offer_number}}/lines/{{offer_line_id}}"
"Content-Type": "application/json"
"Accept": "application/json"
data('{
	"content": "My edited line description",
	"price": 10,
	"vat_percentage": 21
}')


// Delete an offer line.

@name("Delete an offer line")
DELETE "https://{{api_url}}/offers/{{offer_number}}/lines/{{offer_line_id}}"
"Content-Type": "application/json"
"Accept": "application/json"




