#!/usr/bin/env dothttp

// Remove a forked_from relationship

@name("Delete Projects  Fork")
DELETE "https://{{baseUrl}}/projects/:id/fork"


// Mark this project as forked from another

@name("Add Projects  Fork Forked From")
POST "https://{{baseUrl}}/projects/:id/fork/:forked_from_id"



