#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get a repository subscription")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/subscription"


@name("Set a repository subscription")
PUT "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/subscription"
"Content-Type": "application/json"
json({
    "subscribed": true,
    "ignored": false
})


@name("Delete a repository subscription")
DELETE "https://{{baseUrl}}/repos/{{owner}}/{{repo}}/subscription"



