#!/usr/bin/env dothttp

// Send a test to validate if can connect to AWS S3. Optionally provide a configuration in the request body to test. If no valid configuration is present in the request body the current server configuration will be tested.
// ##### Permissions
// Must have `manage_system` permission.
// __Minimum server version__: 4.8

@name("Test AWS S3 connection")
POST "https://{{baseURL}}/file/s3_test"
"Authorization": "Bearer {{token}}"
"Content-Type": "application/json"
data('Mattermost configuration')



