#!/usr/bin/env dothttp

@name("Get Published Assets summary for current User")
GET "https://{{sb_client}}.salesboard.biz/v1/assets/published/updates"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"


@name("Get Published Assets summary for Campaign")
GET "https://{{sb_client}}.salesboard.biz/v1/assets/published/updates"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"
? "ID_Campaign"= "{{sb_campaign_id}}"


@name("Get Published Assets summary for Team - not in use")
GET "https://{{sb_client}}.salesboard.biz/v1/assets/published/updates"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"
? "ID_Team"= "1"


@name("Get Published update for a single Asset")
GET "https://{{sb_client}}.salesboard.biz/v1/assets/published/updates/forms/9"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"


@name("Get Published Asset by name")
POST "https://{{sb_client}}.salesboard.biz/v1/assets/published/updates/query"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"
json({
    "type": "form",
    "name": "{{sb_asset_name}}"
})



