#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List notifications for the authenticated user")
GET "https://{{baseUrl}}/notifications"
? "all"= "false"
? "participating"= "false"
? "since"= "aliqua consectetur elit incididu"
? "before"= "aliqua consectetur elit incididu"
? "per_page"= "30"
? "page"= "1"


@name("Mark notifications as read")
PUT "{{baseUrl}}/notifications"
"Content-Type": "application/json"
json({
    "last_read_at": "1996-11-16T01:54:26.801Z",
    "read": false
})



