#!/usr/bin/env dothttp

// Get the content (intro/extra) from a given credit note.

@name("List credit note content")
GET "https://{{api_url}}/creditnotes/{{creditnote_number}}/content"
"Content-Type": "application/json"
"Accept": "application/json"
? "limit"= "15"


// Retrieve credit note content by its type.
// 
// Supported types: intro, extra

@name("Retrieve credit note content")
GET "https://{{api_url}}/creditnotes/{{creditnote_number}}/content/{{creditnote_content_type}}"
"Content-Type": "application/json"
"Accept": "application/json"


// Update credit note content for the given type.
// 
// Supported types: intro, extra

@name("Update credit note content")
PATCH "https://{{api_url}}/creditnotes/{{creditnote_number}}/content/{{creditnote_content_type}}"
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "columns": 4,
    "column_1": "colo uno",
    "column_2": "colo duo",
    "column_3": "colo trio",
    "column_4": ""
})


// Delete credit note content.

@name("Delete credit note content")
DELETE "https://{{api_url}}/creditnotes/{{creditnote_number}}/content/{{creditnote_content_type}}"
"Content-Type": "application/json"
"Accept": "application/json"



