#!/usr/bin/env dothttp

@name("getSiteVirtualBeacons")
GET "https://{{host}}/api/v1/sites/:site_id/vbeacons"


@name("getSiteVirtualBeaconDetails")
GET "https://{{host}}/api/v1/sites/:site_id/vbeacons/:vbeacon_id"


// Create Virtual Beacon
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
//  uuid|string|bluetooth tag UUID
//  major|int|bluetooth tag major
//  minor|int|bluetooth tag minor
//  power_mode|string|default / custom
//  power|int|required if power\_mode==custom, -30 - 100, in dBm. For default power_mode, power = 4 dBm.
//  name|string|name / label of the device
//  message|string|a message that can be displayed when the sdkclient gets near the vbeacon
//  url|string|URL to show, optional
//  wayfinding\_nodename|string|the name to be used in wayfinding\_path or wayfinding_grid blob
//  map_id|string|map where the device belongs to
//  x|float|x in pixel
//  y|float|y in pixel

@name("createSiteVirtualBeacon")
POST "https://{{host}}/api/v1/sites/:site_id/vbeacons"
"Accept": "application/json"
"X-CSRFToken": "{{csrftoken}}"
"Content-Type": "application/json"
json({
    "uuid": "31375aeb-b8d3-1ea6-83bf-a31eb04e1c38",
    "major": 1356,
    "minor": 21,
    "power_mode": "default",
    "message": "Welcome to Mist",
    "url": "http://www.mist.com/any",
    "wayfinding_nodename": "node1",
    "name": "conference room",
    "map_id": "63eda950-c6da-11e4-a628-60f81dd250cc",
    "x": 53.5,
    "y": 173.1
})


@name("editSiteVirtualBeacon")
PUT "https://{{host}}/api/v1/sites/:site_id/vbeacons/:vbeacon_id"
"Accept": "application/json"
"X-CSRFToken": "{{csrftoken}}"
"Content-Type": "application/json"
json({
    "name": "Board Room"
})


@name("deleteSiteVirtualBeacon")
DELETE "https://{{host}}/api/v1/sites/:site_id/vbeacons/:vbeacon_id"
"Accept": "application/json"
"X-CSRFToken": "{{csrftoken}}"
"Content-Type": "application/json"



