#!/usr/bin/env dothttp

// <!--
// ### Sample Response
// ```
// {
//       "get": {
//         "summary": "Find a single order by orderid",
//         "description": "",
//         "operationId": "getorder",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": " order",
//             "in": "path",
//             "description": " order to retrieve",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/ orderDTO"
//             }
//           }
//         }
//       },
//       "post": {
//         "summary": "get hold reasons",
//         "description": "",
//         "operationId": "getHoldReasons",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": "order",
//             "in": "path",
//             "description": "order to use",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/orderDTO"
//             }
//           }
//         }
//       }
//     }
// ```
// -->

@name("Subscription")
POST "https://wms.slg.com/scprd/wmwebservice_rest/webhooks/subscriptions"
"Content-Type": "application/json"
"Authorization": "Barear Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
data('{
    "subscriptionDetails": {
        "subscriptionType": "company.propertyChange",
        "propertyName": "companyname"
    },
    "enabled": true
}')


// <!--
// ### Sample Response
// ```
// {
//       "get": {
//         "summary": "Find a single order by orderid",
//         "description": "",
//         "operationId": "getorder",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": " order",
//             "in": "path",
//             "description": " order to retrieve",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/ orderDTO"
//             }
//           }
//         }
//       },
//       "post": {
//         "summary": "get hold reasons",
//         "description": "",
//         "operationId": "getHoldReasons",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": "order",
//             "in": "path",
//             "description": "order to use",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/orderDTO"
//             }
//           }
//         }
//       }
//     }
// ```
// -->

@name("Delete a subscription")
DELETE "https://wms.slg.com/scprd/wmwebservice_rest/webhooks/subscriptions{subscriptionId}"
"Content-Type": "application/json"
"Authorization": "Barear Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
data('{
    "subscriptionId": "0000000000000000",
    "enabled": false
}')



