#!/usr/bin/env dothttp

// Return multicast settings for a network

@name("Return Multicast Settings For A Network")
GET "https://{{baseUrl}}/networks/:networkId/switch/routing/multicast"
"X-Cisco-Meraki-API-Key": ""


// Update multicast settings for a network
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// defaultSettings| object| Default multicast setting for entire network. IGMP snooping and Flood unknown multicast traffic settings are enabled by default.
// overrides| array| Array of paired switches/stacks/profiles and corresponding multicast settings. An empty array will clear the multicast settings.
// 
// #### Supports Action Batches
// 
// **Resource**|**Operation**
// :-------------: |:-------------:
// `/networks/{networkId}/switch/routing/multicast` | update
// 

@name("Update Multicast Settings For A Network")
PUT "https://{{baseUrl}}/networks/:networkId/switch/routing/multicast"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "defaultSettings": {
        "igmpSnoopingEnabled": "<boolean>",
        "floodUnknownMulticastTrafficEnabled": "<boolean>"
    },
    "overrides": [
        {
            "igmpSnoopingEnabled": "<boolean>",
            "floodUnknownMulticastTrafficEnabled": "<boolean>",
            "switchProfiles": [
                "<string>",
                "<string>"
            ],
            "switches": [
                "<string>",
                "<string>"
            ],
            "stacks": [
                "<string>",
                "<string>"
            ]
        },
        {
            "igmpSnoopingEnabled": "<boolean>",
            "floodUnknownMulticastTrafficEnabled": "<boolean>",
            "switchProfiles": [
                "<string>",
                "<string>"
            ],
            "switches": [
                "<string>",
                "<string>"
            ],
            "stacks": [
                "<string>",
                "<string>"
            ]
        }
    ]
}')



