#!/usr/bin/env dothttp

@name("Case Team Member")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamMember/"


@name("Case Team Member Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamMember/{ID}/"


@name("Describe Case Team Member")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamMember/describe/"



