#!/usr/bin/env dothttp

@name("Dand BCompany")
GET "https://{{host}}/services/data/v47.0/sobjects/DandBCompany/"


@name("Dand BCompany Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/DandBCompany/{ID}/"


@name("Describe Dand BCompany")
GET "https://{{host}}/services/data/v47.0/sobjects/DandBCompany/describe/"



