#!/usr/bin/env dothttp

@name("Stamp")
GET "https://{{host}}/services/data/v47.0/sobjects/Stamp/"


@name("Stamp Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Stamp/{ID}/"


@name("Describe Stamp")
GET "https://{{host}}/services/data/v47.0/sobjects/Stamp/describe/"



