#!/usr/bin/env dothttp

@name("api test")
GET "https://{{baseUrl}}/api.test"
? "error"= "<string>"
? "foo"= "<string>"


@name("apps permissions info")
GET "https://{{baseUrl}}/apps.permissions.info"


@name("apps event authorizations list")
GET "https://{{baseUrl}}/apps.event.authorizations.list"
"token": "<string>"
? "event_context"= "<string>"
? "cursor"= "<string>"
? "limit"= "<integer>"


@name("apps permissions request")
GET "https://{{baseUrl}}/apps.permissions.request"
? "scopes"= "<string>"
? "trigger_id"= "<string>"


@name("apps permissions resources list")
GET "https://{{baseUrl}}/apps.permissions.resources.list"
? "cursor"= "<string>"
? "limit"= "<integer>"


@name("apps permissions scopes list")
GET "https://{{baseUrl}}/apps.permissions.scopes.list"


@name("apps uninstall")
GET "https://{{baseUrl}}/apps.uninstall"
? "client_id"= "<string>"
? "client_secret"= "<string>"


@name("apps permissions users list")
GET "https://{{baseUrl}}/apps.permissions.users.list"
? "cursor"= "<string>"
? "limit"= "<integer>"


@name("apps permissions users request")
GET "https://{{baseUrl}}/apps.permissions.users.request"
? "scopes"= "<string>"
? "trigger_id"= "<string>"
? "user"= "<string>"


@name("bots info")
GET "https://{{baseUrl}}/bots.info"
? "bot"= "<string>"


@name("auth revoke")
GET "https://{{baseUrl}}/auth.revoke"
? "test"= "<boolean>"


@name("auth test")
GET "https://{{baseUrl}}/auth.test"
"token": "<string>"


@name("calls add")
POST "https://{{baseUrl}}/calls.add"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "external_unique_id": [
        "<string>"
    ],
    "join_url": [
        "<string>"
    ],
    "external_display_id": [
        "<string>"
    ],
    "desktop_app_join_url": [
        "<string>"
    ],
    "date_start": [
        "<integer>"
    ],
    "title": [
        "<string>"
    ],
    "created_by": [
        "<string>"
    ],
    "users": [
        "<string>"
    ]
})


@name("calls end")
POST "https://{{baseUrl}}/calls.end"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "id": [
        "<string>"
    ],
    "duration": [
        "<integer>"
    ]
})


@name("calls participants add")
POST "https://{{baseUrl}}/calls.participants.add"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "id": [
        "<string>"
    ],
    "users": [
        "<string>"
    ]
})


@name("calls participants remove")
POST "https://{{baseUrl}}/calls.participants.remove"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "id": [
        "<string>"
    ],
    "users": [
        "<string>"
    ]
})


@name("calls info")
GET "https://{{baseUrl}}/calls.info"
"token": "<string>"
? "id"= "<string>"


@name("calls update")
POST "https://{{baseUrl}}/calls.update"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "id": [
        "<string>"
    ],
    "title": [
        "<string>"
    ],
    "join_url": [
        "<string>"
    ],
    "desktop_app_join_url": [
        "<string>"
    ]
})


@name("chat delete")
POST "https://{{baseUrl}}/chat.delete"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "ts": [
        "<number>"
    ],
    "channel": [
        "<string>"
    ],
    "as_user": [
        "<boolean>"
    ]
})


@name("chat delete Scheduled Message")
POST "https://{{baseUrl}}/chat.deleteScheduledMessage"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "scheduled_message_id": [
        "<string>"
    ],
    "as_user": [
        "<boolean>"
    ]
})


@name("chat get Permalink")
GET "https://{{baseUrl}}/chat.getPermalink"
? "channel"= "C2U86NC6M"
? "message_ts"= "1612288689.000200"


@name("chat post Ephemeral")
POST "https://{{baseUrl}}/chat.postEphemeral"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "user": [
        "<string>"
    ],
    "as_user": [
        "<boolean>"
    ],
    "attachments": [
        "<string>"
    ],
    "blocks": [
        "<string>"
    ],
    "icon_emoji": [
        "<string>"
    ],
    "icon_url": [
        "<string>"
    ],
    "link_names": [
        "<boolean>"
    ],
    "parse": [
        "<string>"
    ],
    "text": [
        "<string>"
    ],
    "thread_ts": [
        "<string>"
    ],
    "username": [
        "<string>"
    ]
})


@name("chat post Message")
POST "https://{{baseUrl}}/chat.postMessage"
"token": "{{bot_token}}"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "as_user": [
        "<string>"
    ],
    "attachments": [
        "<string>"
    ],
    "blocks": [
        "<string>"
    ],
    "icon_emoji": [
        "<string>"
    ],
    "icon_url": [
        "<string>"
    ],
    "link_names": [
        "<boolean>"
    ],
    "mrkdwn": [
        "<boolean>"
    ],
    "parse": [
        "<string>"
    ],
    "reply_broadcast": [
        "<boolean>"
    ],
    "text": [
        "test"
    ],
    "thread_ts": [
        "<string>"
    ],
    "unfurl_links": [
        "<boolean>"
    ],
    "unfurl_media": [
        "<boolean>"
    ],
    "username": [
        "<string>"
    ]
})


@name("chat me Message")
POST "https://{{baseUrl}}/chat.meMessage"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "text": [
        "<string>"
    ]
})


@name("chat schedule Message")
POST "https://{{baseUrl}}/chat.scheduleMessage"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "text": [
        "<string>"
    ],
    "post_at": [
        "<string>"
    ],
    "parse": [
        "<string>"
    ],
    "as_user": [
        "<boolean>"
    ],
    "link_names": [
        "<boolean>"
    ],
    "attachments": [
        "<string>"
    ],
    "blocks": [
        "<string>"
    ],
    "unfurl_links": [
        "<boolean>"
    ],
    "unfurl_media": [
        "<boolean>"
    ],
    "thread_ts": [
        "<number>"
    ],
    "reply_broadcast": [
        "<boolean>"
    ]
})


@name("chat scheduled Messages list")
GET "https://{{baseUrl}}/chat.scheduledMessages.list"
"token": "<string>"
? "channel"= "<string>"
? "latest"= "<number>"
? "oldest"= "<number>"
? "limit"= "<integer>"
? "cursor"= "<string>"


@name("chat unfurl")
POST "https://{{baseUrl}}/chat.unfurl"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "ts": [
        "<string>"
    ],
    "unfurls": [
        "<string>"
    ],
    "user_auth_message": [
        "<string>"
    ],
    "user_auth_required": [
        "<boolean>"
    ],
    "user_auth_url": [
        "<string>"
    ]
})


@name("chat update")
POST "https://{{baseUrl}}/chat.update"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "ts": [
        "<string>"
    ],
    "as_user": [
        "<string>"
    ],
    "attachments": [
        "<string>"
    ],
    "blocks": [
        "<string>"
    ],
    "link_names": [
        "<string>"
    ],
    "parse": [
        "<string>"
    ],
    "text": [
        "<string>"
    ]
})


@name("conversations info")
GET "https://{{baseUrl}}/conversations.info"
? "channel"= "<string>"
? "include_locale"= "<boolean>"
? "include_num_members"= "<boolean>"


@name("conversations archive")
POST "https://{{baseUrl}}/conversations.archive"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ]
})


@name("conversations close")
POST "https://{{baseUrl}}/conversations.close"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ]
})


@name("conversations create")
POST "https://{{baseUrl}}/conversations.create"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "name": [
        "<string>"
    ],
    "is_private": [
        "<boolean>"
    ]
})


@name("conversations invite")
POST "https://{{baseUrl}}/conversations.invite"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "users": [
        "<string>"
    ]
})


@name("conversations join")
POST "https://{{baseUrl}}/conversations.join"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ]
})


@name("conversations history")
GET "https://{{baseUrl}}/conversations.history"
? "channel"= "<string>"
? "latest"= "<number>"
? "oldest"= "<number>"
? "inclusive"= "<boolean>"
? "limit"= "<integer>"
? "cursor"= "<string>"


@name("conversations open")
POST "https://{{baseUrl}}/conversations.open"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "users": [
        "<string>"
    ],
    "return_im": [
        "<boolean>"
    ]
})


@name("conversations kick")
POST "https://{{baseUrl}}/conversations.kick"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "user": [
        "<string>"
    ]
})


@name("conversations leave")
POST "https://{{baseUrl}}/conversations.leave"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ]
})


@name("conversations list")
GET "https://{{baseUrl}}/conversations.list"
? "exclude_archived"= "<boolean>"
? "types"= "<string>"
? "limit"= "<integer>"
? "cursor"= "<string>"


@name("conversations mark")
POST "https://{{baseUrl}}/conversations.mark"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "ts": [
        "<number>"
    ]
})


@name("conversations set Topic")
POST "https://{{baseUrl}}/conversations.setTopic"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "topic": [
        "<string>"
    ]
})


@name("conversations unarchive")
POST "https://{{baseUrl}}/conversations.unarchive"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ]
})


@name("dialog open")
GET "https://{{baseUrl}}/dialog.open"
"token": "<string>"
? "dialog"= "<string>"
? "trigger_id"= "<string>"


@name("conversations members")
GET "https://{{baseUrl}}/conversations.members"
? "channel"= "<string>"
? "limit"= "<integer>"
? "cursor"= "<string>"


@name("conversations rename")
POST "https://{{baseUrl}}/conversations.rename"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "name": [
        "<string>"
    ]
})


@name("conversations replies")
GET "https://{{baseUrl}}/conversations.replies"
? "channel"= "<string>"
? "ts"= "<number>"
? "latest"= "<number>"
? "oldest"= "<number>"
? "inclusive"= "<boolean>"
? "limit"= "<integer>"
? "cursor"= "<string>"


@name("conversations set Purpose")
POST "https://{{baseUrl}}/conversations.setPurpose"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "purpose": [
        "<string>"
    ]
})


@name("dnd end Dnd")
POST "https://{{baseUrl}}/dnd.endDnd"
"token": "<string>"


@name("dnd end Snooze")
POST "https://{{baseUrl}}/dnd.endSnooze"
"token": "<string>"


@name("dnd info")
GET "https://{{baseUrl}}/dnd.info"
? "user"= "<string>"


@name("dnd set Snooze")
POST "https://{{baseUrl}}/dnd.setSnooze"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "token": [
        "<string>"
    ],
    "num_minutes": [
        "<string>"
    ]
})


@name("dnd team Info")
GET "https://{{baseUrl}}/dnd.teamInfo"
? "users"= "<string>"


@name("emoji list")
GET "https://{{baseUrl}}/emoji.list"


@name("files delete")
POST "https://{{baseUrl}}/files.delete"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "file": [
        "<string>"
    ]
})


@name("files comments delete")
POST "https://{{baseUrl}}/files.comments.delete"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "file": [
        "<string>"
    ],
    "id": [
        "<string>"
    ]
})


@name("files list")
GET "https://{{baseUrl}}/files.list"
? "user"= "<string>"
? "channel"= "<string>"
? "ts_from"= "<number>"
? "ts_to"= "<number>"
? "types"= "<string>"
? "count"= "<string>"
? "page"= "<string>"
? "show_files_hidden_by_limit"= "<boolean>"


@name("files remote update")
POST "https://{{baseUrl}}/files.remote.update"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "token": [
        "<string>"
    ],
    "file": [
        "<string>"
    ],
    "external_id": [
        "<string>"
    ],
    "title": [
        "<string>"
    ],
    "filetype": [
        "<string>"
    ],
    "external_url": [
        "<string>"
    ],
    "preview_image": [
        "<string>"
    ],
    "indexable_file_contents": [
        "<string>"
    ]
})


@name("files info")
GET "https://{{baseUrl}}/files.info"
? "file"= "<string>"
? "count"= "<string>"
? "page"= "<string>"
? "limit"= "<integer>"
? "cursor"= "<string>"


@name("files upload")
POST "https://{{baseUrl}}/files.upload"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "token": [
        "<string>"
    ],
    "file": [
        "<string>"
    ],
    "content": [
        "<string>"
    ],
    "filetype": [
        "<string>"
    ],
    "filename": [
        "<string>"
    ],
    "title": [
        "<string>"
    ],
    "initial_comment": [
        "<string>"
    ],
    "channels": [
        "<string>"
    ],
    "thread_ts": [
        "<number>"
    ]
})


@name("files remote add")
POST "https://{{baseUrl}}/files.remote.add"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "token": [
        "<string>"
    ],
    "external_id": [
        "<string>"
    ],
    "title": [
        "<string>"
    ],
    "filetype": [
        "<string>"
    ],
    "external_url": [
        "<string>"
    ],
    "preview_image": [
        "<string>"
    ],
    "indexable_file_contents": [
        "<string>"
    ]
})


@name("files remote info")
GET "https://{{baseUrl}}/files.remote.info"
? "file"= "<string>"
? "external_id"= "<string>"


@name("migration exchange")
GET "https://{{baseUrl}}/migration.exchange"
? "users"= "<string>"
? "team_id"= "<string>"
? "to_old"= "<boolean>"


@name("files remote list")
GET "https://{{baseUrl}}/files.remote.list"
? "channel"= "<string>"
? "ts_from"= "<number>"
? "ts_to"= "<number>"
? "limit"= "<integer>"
? "cursor"= "<string>"


@name("files remote remove")
POST "https://{{baseUrl}}/files.remote.remove"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "token": [
        "<string>"
    ],
    "file": [
        "<string>"
    ],
    "external_id": [
        "<string>"
    ]
})


@name("files remote share")
GET "https://{{baseUrl}}/files.remote.share"
? "file"= "<string>"
? "external_id"= "<string>"
? "channels"= "<string>"


@name("files revoke Public URL")
POST "https://{{baseUrl}}/files.revokePublicURL"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "file": [
        "<string>"
    ]
})


@name("files shared Public URL")
POST "https://{{baseUrl}}/files.sharedPublicURL"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "file": [
        "<string>"
    ]
})


@name("pins list")
GET "https://{{baseUrl}}/pins.list"
? "channel"= "<string>"


@name("reactions list")
GET "https://{{baseUrl}}/reactions.list"
? "user"= "<string>"
? "full"= "<boolean>"
? "count"= "<integer>"
? "page"= "<integer>"
? "cursor"= "<string>"
? "limit"= "<integer>"


@name("oauth token")
GET "https://{{baseUrl}}/oauth.token"
? "client_id"= "<string>"
? "client_secret"= "<string>"
? "code"= "<string>"
? "redirect_uri"= "<string>"
? "single_channel"= "<boolean>"


@name("reactions add")
POST "https://{{baseUrl}}/reactions.add"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "timestamp": [
        "<string>"
    ]
})


@name("reactions remove")
POST "https://{{baseUrl}}/reactions.remove"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "name": [
        "<string>"
    ],
    "file": [
        "<string>"
    ],
    "file_comment": [
        "<string>"
    ],
    "channel": [
        "<string>"
    ],
    "timestamp": [
        "<string>"
    ]
})


@name("oauth v2 access")
GET "https://{{baseUrl}}/oauth.v2.access"
? "client_id"= "<string>"
? "client_secret"= "<string>"
? "code"= "<string>"
? "redirect_uri"= "<string>"


@name("pins add")
POST "https://{{baseUrl}}/pins.add"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "timestamp": [
        "<string>"
    ]
})


@name("oauth access")
GET "https://{{baseUrl}}/oauth.access"
? "client_id"= "<string>"
? "client_secret"= "<string>"
? "code"= "<string>"
? "redirect_uri"= "<string>"
? "single_channel"= "<boolean>"


@name("reactions get")
GET "https://{{baseUrl}}/reactions.get"
? "channel"= "<string>"
? "file"= "<string>"
? "file_comment"= "<string>"
? "full"= "<boolean>"
? "timestamp"= "<string>"


@name("pins remove")
POST "https://{{baseUrl}}/pins.remove"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "timestamp": [
        "<string>"
    ]
})


@name("reminders complete")
POST "https://{{baseUrl}}/reminders.complete"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "reminder": [
        "<string>"
    ]
})


@name("reminders add")
POST "https://{{baseUrl}}/reminders.add"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "text": [
        "<string>"
    ],
    "time": [
        "<string>"
    ],
    "user": [
        "<string>"
    ]
})


@name("reminders delete")
POST "https://{{baseUrl}}/reminders.delete"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "reminder": [
        "<string>"
    ]
})


@name("reminders info")
GET "https://{{baseUrl}}/reminders.info"
? "reminder"= "<string>"


@name("reminders list")
GET "https://{{baseUrl}}/reminders.list"


@name("rtm connect")
GET "https://{{baseUrl}}/rtm.connect"
? "batch_presence_aware"= "<boolean>"
? "presence_sub"= "<boolean>"


@name("search messages")
GET "https://{{baseUrl}}/search.messages"
? "count"= "<integer>"
? "highlight"= "<boolean>"
? "page"= "<integer>"
? "query"= "<string>"
? "sort"= "<string>"
? "sort_dir"= "<string>"


@name("stars add")
POST "https://{{baseUrl}}/stars.add"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "file": [
        "<string>"
    ],
    "file_comment": [
        "<string>"
    ],
    "timestamp": [
        "<string>"
    ]
})


@name("stars list")
GET "https://{{baseUrl}}/stars.list"
? "count"= "<string>"
? "page"= "<string>"
? "cursor"= "<string>"
? "limit"= "<integer>"


@name("stars remove")
POST "https://{{baseUrl}}/stars.remove"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "channel": [
        "<string>"
    ],
    "file": [
        "<string>"
    ],
    "file_comment": [
        "<string>"
    ],
    "timestamp": [
        "<string>"
    ]
})


@name("team access Logs")
GET "https://{{baseUrl}}/team.accessLogs"
? "before"= "<string>"
? "count"= "<string>"
? "page"= "<string>"


@name("team billable Info")
GET "https://{{baseUrl}}/team.billableInfo"
? "user"= "<string>"


@name("team info")
GET "https://{{baseUrl}}/team.info"
? "team"= "<string>"


@name("usergroups enable")
POST "https://{{baseUrl}}/usergroups.enable"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "usergroup": [
        "<string>"
    ],
    "include_count": [
        "<boolean>"
    ]
})


@name("team integration Logs")
GET "https://{{baseUrl}}/team.integrationLogs"
? "app_id"= "<string>"
? "change_type"= "<string>"
? "count"= "<string>"
? "page"= "<string>"
? "service_id"= "<string>"
? "user"= "<string>"


@name("team profile get")
GET "https://{{baseUrl}}/team.profile.get"
? "visibility"= "<string>"


@name("usergroups create")
POST "https://{{baseUrl}}/usergroups.create"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "name": [
        "<string>"
    ],
    "channels": [
        "<string>"
    ],
    "description": [
        "<string>"
    ],
    "handle": [
        "<string>"
    ],
    "include_count": [
        "<boolean>"
    ]
})


@name("usergroups disable")
POST "https://{{baseUrl}}/usergroups.disable"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "usergroup": [
        "<string>"
    ],
    "include_count": [
        "<boolean>"
    ]
})


@name("usergroups list")
GET "https://{{baseUrl}}/usergroups.list"
? "include_users"= "<boolean>"
? "include_count"= "<boolean>"
? "include_disabled"= "<boolean>"


@name("usergroups users list")
GET "https://{{baseUrl}}/usergroups.users.list"
? "include_disabled"= "<boolean>"
? "usergroup"= "<string>"


@name("usergroups update")
POST "https://{{baseUrl}}/usergroups.update"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "usergroup": [
        "<string>"
    ],
    "handle": [
        "<string>"
    ],
    "description": [
        "<string>"
    ],
    "channels": [
        "<string>"
    ],
    "include_count": [
        "<boolean>"
    ],
    "name": [
        "<string>"
    ]
})


@name("usergroups users update")
POST "https://{{baseUrl}}/usergroups.users.update"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "usergroup": [
        "<string>"
    ],
    "users": [
        "<string>"
    ],
    "include_count": [
        "<boolean>"
    ]
})


@name("users delete Photo")
POST "https://{{baseUrl}}/users.deletePhoto"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "token": [
        "<string>"
    ]
})


@name("users get Presence")
GET "https://{{baseUrl}}/users.getPresence"
? "user"= "<string>"


@name("users conversations")
GET "https://{{baseUrl}}/users.conversations"
? "user"= "<string>"
? "types"= "<string>"
? "exclude_archived"= "<boolean>"
? "limit"= "<integer>"
? "cursor"= "<string>"


@name("users info")
GET "https://{{baseUrl}}/users.info"
? "include_locale"= "<boolean>"
? "user"= "<string>"


@name("views open")
GET "https://{{baseUrl}}/views.open"
"token": "<string>"
? "trigger_id"= "<string>"
? "view"= "<string>"


@name("users identity")
GET "https://{{baseUrl}}/users.identity"


@name("users list")
GET "https://{{baseUrl}}/users.list"
? "limit"= "<integer>"
? "cursor"= "<string>"
? "include_locale"= "<boolean>"


@name("users lookup By Email")
GET "https://{{baseUrl}}/users.lookupByEmail"
? "email"= "jroche@slack-corp.com"


@name("users profile set")
POST "https://{{baseUrl}}/users.profile.set"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "name": [
        "<string>"
    ],
    "profile": [
        "<string>"
    ],
    "user": [
        "<string>"
    ],
    "value": [
        "<string>"
    ]
})


@name("users profile get")
GET "https://{{baseUrl}}/users.profile.get"
? "include_labels"= "<boolean>"
? "user"= "<string>"


@name("users set Active")
POST "https://{{baseUrl}}/users.setActive"
"token": "<string>"


@name("users set Photo")
POST "https://{{baseUrl}}/users.setPhoto"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "token": [
        "<string>"
    ],
    "crop_w": [
        "<string>"
    ],
    "crop_x": [
        "<string>"
    ],
    "crop_y": [
        "<string>"
    ],
    "image": [
        "<string>"
    ]
})


@name("users set Presence")
POST "https://{{baseUrl}}/users.setPresence"
"token": "<string>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "presence": [
        "<string>"
    ]
})


@name("views publish")
GET "https://{{baseUrl}}/views.publish"
"token": "<string>"
? "user_id"= "<string>"
? "view"= "<string>"
? "hash"= "<string>"


@name("views push")
GET "https://{{baseUrl}}/views.push"
"token": "<string>"
? "trigger_id"= "<string>"
? "view"= "<string>"


@name("views update")
GET "https://{{baseUrl}}/views.update"
"token": "<string>"
? "view_id"= "<string>"
? "external_id"= "<string>"
? "view"= "<string>"
? "hash"= "<string>"


@name("workflows step Completed")
GET "https://{{baseUrl}}/workflows.stepCompleted"
"token": "<string>"
? "workflow_step_execute_id"= "<string>"
? "outputs"= "<string>"


@name("workflows step Failed")
GET "https://{{baseUrl}}/workflows.stepFailed"
"token": "<string>"
? "workflow_step_execute_id"= "<string>"
? "error"= "<string>"


@name("workflows update Step")
GET "https://{{baseUrl}}/workflows.updateStep"
"token": "<string>"
? "workflow_step_edit_id"= "<string>"
? "inputs"= "<string>"
? "outputs"= "<string>"
? "step_name"= "<string>"
? "step_image_url"= "<string>"



