#!/usr/bin/env dothttp

@name("getSubscriptions")
GET "https://{{host}}/api/v1/self/subscriptions"


@name("subscribe")
POST "https://{{host}}/api/v1/orgs/:org_id/subscriptions"
"Accept": "application/json"
"X-CSRFToken": "{{csrftoken}}"
"Content-Type": "application/json"


@name("unsubscribe")
DELETE "https://{{host}}/api/v1/orgs/:org_id/subscriptions"
"X-CSRFToken": "{{csrftoken}}"



