#!/usr/bin/env dothttp

@name("Get webhooks")
GET "https://webexapis.com/v1/webhooks"
"Accept": "application/json"
"Content-Type": "application/json"


@name("Create new webhook")
POST "https://webexapis.com/v1/webhooks"
"Accept": "application/json"
"Content-Type": "application/json"
json({
    "name": "postmanbot",
    "targetUrl": "https://webhook.site/6b4c63c3-e568-45db-8db9-4c4eb0e9e10f",
    "resource": "messages",
    "event": "created",
    "filter": "mentionedPeople=Y2lzY29zcGFyazovL3VzL1BFT1BMRS82YTAzYjVlNi03ZGYxLTRjZDMtOWE2Ni01MDhlMWQ4MjY4M2M"
})


@name("Get webhook details")
GET "https://webexapis.com/v1/webhooks/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svZGM3ZTZhNGQtZDg2Zi00YzhiLTg0ZTctYmM4NWU1ZjJkNzE4"
"Accept": "application/json"
"Content-Type": "application/json"


@name("Delete webhook")
DELETE "https://webexapis.com/v1/webhooks/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svZGM3ZTZhNGQtZDg2Zi00YzhiLTg0ZTctYmM4NWU1ZjJkNzE4"
"Accept": "application/json"
"Content-Type": "application/json"



