#!/usr/bin/env dothttp

@name("Get entity from CandidateProfileExtension by key")
GET "https://{{baseUrl}}/CandidateProfileExtension({{candidateId}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
? "$select"= "mdfSystemRecordStatus,lastModifiedDateTime"


@name("Update entity in CandidateProfileExtension")
PUT "https://{{baseUrl}}/CandidateProfileExtension({{candidateId}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
"Content-Type": "application/json"
data('{
    "d": {
        "candidateId": "adipisicing culpa",
        "createdBy": "anim ullamco sint irure",
        "createdDateTime": "/Date(1492098664000)/",
        "lastModifiedBy": "et",
        "lastModifiedDateTime": "/Date(1492098664000)/",
        "mdfSystemRecordStatus": "ut eiusmod"
    }
}')


@name("Delete entity from CandidateProfileExtension")
DELETE "https://{{baseUrl}}/CandidateProfileExtension({{candidateId}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
"If-Match": "exercitation mollit reprehenderit ad"



