#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Update a repository invitation")
PATCH "https://{{baseUrl}}/repos/{{owner}}/{{repo/invitations/:invitation_id}}/"
"Content-Type": "application/json"
json({
    "permissions": "write"
})


@name("Delete a repository invitation")
DELETE "https://{{baseUrl}}/repos/{{owner}}/{{repo/invitations/:invitation_id}}/"



