#!/usr/bin/env dothttp

@name("Malaysian National ID and Malaysian Credit Bureau")
POST "https://resttest.datazoo.com/api/Malaysia/Verify.json"
data('{
    "dataSources":  [
        "Malaysia Credit Bureau",
        "Malaysia National ID" // include second data source to search
    ],
    "reportingReference": "",
    "idNo": "920202025992",
    "firstName": "Christine",
    "middleName": "",
    "lastName": "Wong",
    "dateOfBirth": "1992-02-02",
    "streetNo": "D-15-01, Z Residence",
    "streetName": "Taman Industri Bukit Oug",
    "city": "Bukit Jalil",
    "state": "Kuala Lumpur",
    "postCode": "58200",
    "CreditBureauConsentObtained": true,
    "NationalIdConsentObtained":true // include consent flag for second data source
}')


@name("Australian Residential and Passport")
POST "https://resttest.datazoo.com/api/Australia/Verify.json"
data('{
    "dataSources":  [
        "Australian Residential",
        "Australian Third Party Datasets" // include second data source to search
    ],
	"reportingReference": "DataZoo_Test",
    "firstName": "John",
    "middleName": null,
    "lastName": "Smith",
    "dateOfBirth": "1965-01-01", //yyyy-mm-dd
    "unitNo": null,
    "streetNo": "77",
    "streetName": "Test",
    "streetType": "St",
    "suburb": "Test Suburb",
    "state": "QLD",
    "postCode": "4655",
    "homePhoneNo": null,
    "mobilePhoneNo": null,
    "emailAddress": null,
    "passportNo": "C5100511",
    "gender": "Male",
    "thirdPartyDatasetsConsentObtained": true
}')



