#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get All Issue Field Options")
GET "https://{{baseUrl}}/rest/api/3/field/:fieldKey/option"
? "startAt"= "0"
? "maxResults"= "50"


@name("Create Issue Field Option")
POST "https://{{baseUrl}}/rest/api/3/field/:fieldKey/option"
"Content-Type": "application/json"
data('{
    "value": "<string>",
    "properties": "<object>",
    "config": {
        "scope": {
            "projects": [
                "<long>"
            ],
            "projects2": [
                {
                    "id": "<long>",
                    "attributes": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ]
                }
            ],
            "global": {
                "attributes": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ]
            }
        },
        "attributes": [
            "<string>"
        ]
    }
}')



