#!/usr/bin/env dothttp

@name("Une ligne")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Un Arrêt")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Les Arrêts paginés")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Les lignes paginées")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Lignes Filtre sur la première")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Lignes Filtre sur la dernière")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Lignes paginées deuxième page")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Lignes -> Arrêts")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Lignes > Arrêts paginés")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Lignes -> Itinéraires -> Arrêts")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Lignes -> Nombre de Courses (Basique)")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



// Récupérer le nombre de courses total avec un filtre sur les dates.
// 
// Il est possible de faire différents types de recherche, suivant les arguments de la requête :  
// * from uniquement : après cette date
// * to uniquement : avant cette date
// * from et to : entre 2 dates 

@name("Lignes -> Nombre de Courses Total (Filtres)")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



@name("Lignes-> Nombre de Courses par date")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"



// Récupérer le nombre de courses par date avec un filtre sur les dates.
// 
// Il est possible de faire différents types de recherche, suivant les arguments de la requête :  
// * from uniquement : après cette date
// * to uniquement : avant cette date
// * from et to : entre 2 dates 

@name("Lignes-> Nombre de Courses par date (Filtres)")
POST "https://{{IBOO_URL}}/api/v1/datas/{{publication_api_namespace}}/graphql"
"Authorization": "Token token={{publication_api_key}}"




