#!/usr/bin/env dothttp

@name("Email Services Address")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailServicesAddress/"


@name("Email Services Address Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailServicesAddress/{ID}/"


@name("Describe Email Services Address")
GET "https://{{host}}/services/data/v47.0/sobjects/EmailServicesAddress/describe/"



