#!/usr/bin/env dothttp

@name("Outgoing Email")
GET "https://{{host}}/services/data/v47.0/sobjects/OutgoingEmail/"


@name("Outgoing Email Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/OutgoingEmail/{ID}/"


@name("Describe Outgoing Email")
GET "https://{{host}}/services/data/v47.0/sobjects/OutgoingEmail/describe/"



