#!/usr/bin/env dothttp

// Returns a [paginated](#pagination) list of all custom field option for a context. Options are returned first then cascading options, in the order they display in Jira.
// 
// This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Get Custom Field Options (Context)")
GET "https://{{baseUrl}}/rest/api/3/field/:fieldId/context/:contextId/option"
? "optionId"= "<long>"
? "onlyOptions"= "false"
? "startAt"= "0"
? "maxResults"= "100"


// Updates the options of a custom field.
// 
// If any of the options are not found, no options are updated. Options where the values in the request match the current values aren't updated and aren't reported in the response.
// 
// Note that this operation **only works for issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource**, it cannot be used with issue field select list options created by Connect apps.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Update Custom Field Options (Context)")
PUT "https://{{baseUrl}}/rest/api/3/field/:fieldId/context/:contextId/option"
"Content-Type": "application/json"
json({
    "options": [
        {
            "id": "<string>",
            "value": "<string>",
            "disabled": "<boolean>"
        },
        {
            "id": "<string>",
            "value": "<string>",
            "disabled": "<boolean>"
        }
    ]
})


// Creates options and, where the custom select field is of the type Select List (cascading), cascading options for a custom select field. The options are added to a context of the field.
// 
// This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Create Custom Field Options (Context)")
POST "https://{{baseUrl}}/rest/api/3/field/:fieldId/context/:contextId/option"
"Content-Type": "application/json"
json({
    "options": [
        {
            "value": "<string>",
            "optionId": "<string>",
            "disabled": "<boolean>"
        },
        {
            "value": "<string>",
            "optionId": "<string>",
            "disabled": "<boolean>"
        }
    ]
})


// Changes the order of custom field options or cascading options in a context.
// 
// This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Reorder Custom Field Options (Context)")
PUT "https://{{baseUrl}}/rest/api/3/field/:fieldId/context/:contextId/option/move"
"Content-Type": "application/json"
json({
    "customFieldOptionIds": [
        "<string>",
        "<string>"
    ],
    "after": "<string>",
    "position": "<string>"
})


// Deletes a custom field option.
// 
// Options with cascading options cannot be deleted without deleting the cascading options first.
// 
// This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Delete Custom Field Options (Context)")
DELETE "https://{{baseUrl}}/rest/api/3/field/:fieldId/context/:contextId/option/:optionId"



