#!/usr/bin/env dothttp

@name("ByProductId")
GET "http://dev.api.completecarparts.com/v1/related/product/12974"


@name("ByBlogGuid")
GET "http://dev.api.completecarparts.com/v1/related/blog/146191dd-ffb3-4d6c-9f70-0e0c1003d353"



