#!/usr/bin/env dothttp

// Modify the welcome banner,
// 
// Connect via tsh to see the change

@name("Change WelcomeBanner (multiline)")
POST "https://{{WEBEXAPI}}/xapi/command/SystemUnit.WelcomeBanner.Set"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
"": ""
data('{
    "deviceId": "{{_deviceId}}",
    "arguments": {},
    "body": "****************\nWebex Device\nAuthorized Access Only\n****************"
}




')



