#!/usr/bin/env dothttp

# imported from http://localhost:8000/Microsoft%20Graph.postman_collection.json

@name("List catalog entries")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9b63d0>"



