#!/usr/bin/env dothttp

// Return the SSID statuses of an access point
@name("Return the SSID statuses of an access point")
GET "https://{{baseUrl}}/devices/:serial/wireless/status"
"X-Cisco-Meraki-API-Key": ""



