#!/usr/bin/env dothttp

@name("Create payment with card tokenization")
POST "https://{{UNLIMINT_API_URL}}/api/payments"
"Content-Type": "application/json"
json({
    "request": {
        "id": "{{$guid}}",
        "time": "{{request_time}}"
    },
    "merchant_order": {
        "id": "{{$randomUUID}}",
        "description": "Postman Collection Order ('{{request_name}}')"
    },
    "payment_method": "BANKCARD",
    "payment_data": {
        "amount": "12.34",
        "currency": "{{TERMINAL_CURRENCY}}",
        "generate_token": true
    },
    "customer": {
        "email": "{{CUSTOMER_EMAIL}}"
    },
    "card_account": {
        "card": {
            "pan": "{{CARD_NON3DS_CONFIRMED}}",
            "holder": "{{$randomFullName}}",
            "expiration": "{{expiration}}",
            "security_code": "100"
        }
    }
})


@name("Get payment by id for card token")
GET "https://{{UNLIMINT_API_URL}}/api/payments/{{payment_id_for_card_token}}"


@name("Create payment with card token")
POST "https://{{UNLIMINT_API_URL}}/api/payments"
"Content-Type": "application/json"
json({
    "request": {
        "id": "{{$guid}}",
        "time": "{{request_time}}"
    },
    "merchant_order": {
        "id": "{{merchant_order_id}}",
        "description": "Postman Collection Order ('{{request_name}}')"
    },
    "payment_method": "BANKCARD",
    "payment_data": {
        "amount": "12.34",
        "currency": "{{TERMINAL_CURRENCY}}"
    },
    "customer": {
        "email": "{{CUSTOMER_EMAIL}}"
    },
    "card_account": {
        "token": "{{card_token}}",
        "card": {
            "security_code": "100"
        }
    }
})



