#!/usr/bin/env dothttp

// Returns the system information for the Confluence Cloud tenant. This
// information is used by Atlassian.
// 
// **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
// Permission to access the Confluence site ('Can use' global permission).

@name("Get system info")
GET "https://{{baseUrl}}/api/settings/systemInfo"



