#!/usr/bin/env dothttp

// 
// Schedule F, it shows all special expenditures a national or state party committee
// makes in connection with the general election campaigns of federal candidates.
// 
// These coordinated party expenditures do not count against the contribution limits but are subject to other limits,
// these limits are detailed in Chapter 7 of the FEC Campaign Guide for Political Party Committees.

@name("/schedules/schedule_f/")
GET "https://{{baseUrl}}/schedules/schedule_f/"
? "max_image_number"= "<string>"
? "sort_nulls_last"= "false"
? "payee_name"= "<string>"
? "payee_name"= "<string>"
? "cycle"= "<integer>"
? "cycle"= "<integer>"
? "candidate_id"= "<string>"
? "candidate_id"= "<string>"
? "sort_null_only"= "false"
? "committee_id"= "<string>"
? "committee_id"= "<string>"
? "sort_hide_null"= "false"
? "min_image_number"= "<string>"
? "per_page"= "20"
? "sort"= "expenditure_date"
? "min_amount"= "<string>"
? "api_key"= "DEMO_KEY"
? "max_amount"= "<string>"
? "image_number"= "<string>"
? "image_number"= "<string>"
? "page"= "1"
? "max_date"= "<date>"
? "line_number"= "<string>"
? "min_date"= "<date>"


// 
// Schedule F, it shows all special expenditures a national or state party committee
// makes in connection with the general election campaigns of federal candidates.
// 
// These coordinated party expenditures do not count against the contribution limits but are subject to other limits,
// these limits are detailed in Chapter 7 of the FEC Campaign Guide for Political Party Committees.

@name("/schedules/schedule_f/:sub_id/")
GET "https://{{baseUrl}}/schedules/schedule_f/:sub_id/"
? "per_page"= "20"
? "page"= "1"
? "api_key"= "DEMO_KEY"



