#!/usr/bin/env dothttp

// [token/from_oauth1](https://www.dropbox.com/developers/documentation/http/documentation#auth-token-from_oauth1)
// 
// scope: `None`
// 
// Creates an OAuth 2.0 access token from the supplied OAuth 1.0 access token.

@name("token/from_oauth1")
POST "https://api.dropboxapi.com/2/auth/token/from_oauth1"
"Content-Type": "application/json"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"
json({
    "oauth1_token": "qievr8hamyg6ndck",
    "oauth1_token_secret": "qomoftv0472git7"
})


// [token/revoke](https://www.dropbox.com/developers/documentation/http/documentation#auth-token-revoke)
// 
// scope: `None`
// 
// Disables the access token used to authenticate the call.

@name("token/revoke")
POST "https://api.dropboxapi.com/2/auth/token/revoke"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"



