#!/usr/bin/env dothttp

@name("Add the item in the cart")
POST "https://{{url}}/api/Addofflinecart"
basicauth("{{user_name}}", "{{api_key}}")
"Content-Type": "application/json"
data('{
  "addtocart": [
    {
      "product_data": {
        "amount": "1",
        "extra": [],
        "product_id": "214",
        "product_options": []
      }
    }
  ],
  "user_id": {{customer_id}}
}')



