#!/usr/bin/env dothttp

@name("get all countries")
GET "http://{{queries_url}}.envia.com/country"


// Get country details by country id. <br>
// 
// <strong>US</strong>- United States<br>
// <strong>MX</strong>- Mexico<br>
// <strong>CO</strong>- Colombia<br>

@name("get single country")
GET "http://{{queries_url}}.envia.com/country/{{country_code}}"



