#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get a package version for an organization")
GET "https://{{baseUrl}}/orgs/{{org}}/packages/{{package_type}}/{{package_name/versions/:package_version_id}}/"


@name("Delete package version for an organization")
DELETE "https://{{baseUrl}}/orgs/{{org}}/packages/{{package_type}}/{{package_name/versions/:package_version_id}}/"


@name("Restore package version for an organization")
POST "https://{{baseUrl}}/orgs/{{org}}/packages/{{package_type}}/{{package_name/versions/{{package_version_id}}/restore}}/"



