#!/usr/bin/env dothttp

// Untuk menampilkan data Booking (Rencana) operasi yang belum dilaksanana oleh Pasien BPJS berdasarkan Kartu Peserta-nya.

@name("localhost/ehealthsys-rsia/index.php?r=jkn/operasi/belumTerlaksana")
POST "https://rsrb.rsrizkibunda.com/index.php"
"Content-Type": "application/json"
"Accept": "application/json"
"X-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InN5c2FkbWluIiwidGltZXN0YW1wIjoiMTU4OTQ0MDA1OCJ9.6dh5VY37t6-uCUHPMiP-HyjLU2_NLTfll5M-jXwDCnk"
? "r"= "jkn/operasi/belumTerlaksana"
data('{
   "nopeserta":"0000986745532"
}')


// Menampilkan list semua jadwal Booking/Operasi berdasarkan periode booking-nya. Pada hasil list terebut ditampilkan juga mana yang sudah dilaksanakan dan mana yang belum.

@name("localhost/ehealthsys-rsia/index.php?r=jkn/operasi/jadwal")
POST "https://rsrb.rsrizkibunda.com/index.php"
"Content-Type": "application/json"
"Accept": "application/json"
"X-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InN5c2FkbWluIiwidGltZXN0YW1wIjoiMTU4OTQ0MDA1OCJ9.6dh5VY37t6-uCUHPMiP-HyjLU2_NLTfll5M-jXwDCnk"
? "r"= "jkn/operasi/jadwal"
data('{
   "tanggalawal":"2020-05-1",
   "tanggalakhir":"2020-05-14"
}')



