#!/usr/bin/env dothttp

@name("RECEIVING MOBILE REQUESTS")
POST "https://{{USSDBaseURL}}/{{endPoint}}"
json({
    "USERID": "NALOTest",
    "MSISDN": "233XXXXXXXXX",
    "USERDATA": "3",
    "MSGTYPE": false,
    "NETWORK": "MTN"
})



