#!/usr/bin/env dothttp

@name("List project columns")
GET "https://{{baseUrl}}/projects/:project_id/columns"
? "per_page"= "30"
? "page"= "1"


@name("Create a project column")
POST "https://{{baseUrl}}/projects/:project_id/columns"
"Content-Type": "application/json"
data('{
    "name": "<string>"
}')



