#!/usr/bin/env dothttp

// This endpoint is deprecated and will be removed in GitLab 9.0.

@name("Get Projects  Merge Request Merge Request")
GET "https://{{baseUrl}}/projects/:id/merge_request/:merge_request_id"


// Post projects  merge request merge request  cancel merge when build succeeds

@name("Add Projects  Merge Request Merge Request  Cancel Merge When Build Succeeds")
POST "https://{{baseUrl}}/projects/:id/merge_request/:merge_request_id/cancel_merge_when_build_succeeds"


// Get projects  merge request merge request  changes

@name("Get Projects  Merge Request Merge Request  Changes")
GET "https://{{baseUrl}}/projects/:id/merge_request/:merge_request_id/changes"


// Get projects  merge request merge request  closes issues

@name("Get Projects  Merge Request Merge Request  Closes Issues")
GET "https://{{baseUrl}}/projects/:id/merge_request/:merge_request_id/closes_issues"
? "page"= "<>"
? "per_page"= "<>"


// Get projects  merge request merge request  comments

@name("Get Projects  Merge Request Merge Request  Comments")
GET "https://{{baseUrl}}/projects/:id/merge_request/:merge_request_id/comments"
? "page"= "<>"
? "per_page"= "<>"


// Get projects  merge request merge request  commits

@name("Get Projects  Merge Request Merge Request  Commits")
GET "https://{{baseUrl}}/projects/:id/merge_request/:merge_request_id/commits"


// Put projects  merge request merge request  merge

@name("Put Projects  Merge Request Merge Request  Merge")
PUT "https://{{baseUrl}}/projects/:id/merge_request/:merge_request_id/merge"



