#!/usr/bin/env dothttp

@name("Request-Code")
POST "https://{{URL}}/v1/account"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"cc": "<Country Code>",
	"phone_number": "<Phone Number>",
	"method": "< sms | voice >",
	"cert": "<Valid Cert from Business Manager>",
	"pin": "<Two-Step Verification PIN"
}')


@name("Register-Account")
POST "https://{{URL}}/v1/account/verify"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
	"code": "<Registration Code Received via SMS/Voice>"
}')



