#!/usr/bin/env dothttp

// Currently all BSA messages have a station code of "BART" signifying that they are system-wide. If future messages are tagged for specific stations, and a station is specified in the orig parameter, information will be provided for the specified station as well as any system-wide tagged messages. To get all messages, regardless of tags, specify "orig=all".
// 
// The "type" element will either be DELAY or EMERGENCY. The "sms_text" element is a shortened version of the "description" element for use with text messaging. This element might be longer than allowed in a single text message, so it might need to be broken up into several messages.

@name("Service advisory")
GET "http://api.bart.gov/api/bsa.aspx"
? "cmd"= "bsa"
? "key"= "{{key}}"
? "json"= "y"


// Count of trains active

@name("Count")
GET "http://api.bart.gov/api/bsa.aspx"
? "cmd"= "count"
? "key"= "{{key}}"
? "json"= "y"


// Current elevator information

@name("Elevators")
GET "http://api.bart.gov/api/bsa.aspx"
? "cmd"= "elev"
? "key"= "{{key}}"
? "json"= "y"



