#!/usr/bin/env dothttp

@name("Send Mail")
POST "https://{{api-domain}}/crm/v2.1/Leads/{{record_id}}/actions/send_mail"
json({
    "data": [
        {
            "from": {
                "user_name": "Patricia Boyle",
                "email": "p.boyle@abc.com"
            },
            "to": [
                {
                    "user_name": "user1",
                    "email": "user1@gmail.com"
                }
            ],
            "cc": [
                {
                    "user_name": "user2",
                    "email": "user2email@zoho.com"
                }
            ],
            "bcc": [
                {
                    "user_name": "user3",
                    "email": "user3email@zoho.com"
                }
            ],
            "reply_to": {
                "user_name": "user4",
                "email": "user4email@zoho.com"
            },
            "org_email": false,
            "in_reply_to": "2cceafa194d037b63f2000181dd8186486f1eb0360aee76d802b6d376dea97e7",
            "scheduled_time": "2020-06-12T12:12:12+05:30",
            "subject": "Testing Send Mail API",
            "content": "<h3><span style=\"background-color: rgb(254, 255, 102)\">Mail is of rich text format</span></h3><h3><span style=\"background-color: rgb(254, 255, 102)\"><img src=\"https://www.zohoapis.com/crm/viewInLineImage?fileContent=2cceafa194d037b63f2000181dd818646fd5e5167a274098b625c35654a20ed2\"></span></h3><h3><span style=\"background-color: rgb(254, 255, 102)\">REGARDS,</span></h3><div><span style=\"background-color: rgb(254, 255, 102)\">AZ</span></div><div><span style=\"background-color: rgb(254, 255, 102)\">ADMIN</span></div> <div></div>",
            "mail_format": "html",
            "attachments": [
                {
                    "id": "2cceafa194d037b63f2000181dd818646fd5e5167a274098b625c35654a20ed2"
                }
            ]
        }
    ]
})


@name("From Addresses")
GET "https://{{api-domain}}/crm/v2.1/settings/emails/actions/from_addresses"


// To send emails through an API.

@name("Send Mail from Inventory Module")
POST "https://{{api-domain}}/crm/v2.1/Purchase_Orders/{{record_id}}/actions/send_mail""
json({
    "data": [
        {
            "from": {
                "user_name": "Patricia Boyle",
                "email": "p.boyle@abc.com"
            },
            "to": [
                {
                    "user_name": "user1",
                    "email": "user1@gmail.com"
                }
            ],
            "inventory_details": {
                "inventory_template": {
                    "id": "{{inventory_template_id}}",
                    "name": "CT Scan Machines.pdf"
                }
            },
            "paper_type": "A4",
            "view_type": "portrait"
        }
    ]
})


// Use the following keys when you have enabled GDPR compliance settings, and want to send an email asking for the user's consent or request data. Note that it is mandatory to send the consent form in the email's "content" key, when you ask for the lead's/contact's consent.
// 

@name("Send GDPR-related data")
POST "https://{{api-domain}}/crm/v2.1/Leads/{{record_id}}/actions/send_mail"
json({
    "data": [
        {
            "from": {
                "user_name": "Patricia Boyle",
                "email": "p.boyle@abc.com"
            },
            "to": [
                {
                    "user_name": "user1",
                    "email": "user1email@zoho.com"
                }
            ],
            "subject": "Mail subject",
            "content": "<br><a href=\"${ConsentForm.en_US}\" id=\"ConsentForm\" class=\"en_US\" target=\"_blank\">Consent form link</a><br><br><br><br><br><h3><span style=\"background-color: rgb(254, 255, 102)\">REGARDS,</span></h3><div><span style=\"background-color: rgb(254, 255, 102)\">AZ</span></div><div><span style=\"background-color: rgb(254, 255, 102)\">ADMIN</span></div> <div></div>",
            "consent_email": true,
            "mail_format": "html",
            "data_subject_request": {
                "id": "{{data_subject_request_id}}",
                "type": "access"
            }
        }
    ]
})



