#!/usr/bin/env dothttp

@name(" All Domain Event Categories")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/event_categories/"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "2de41f72-1dbf-41e5-890e-cdca760f6185"


@name("Event Categories By Id")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/event_categories/1"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "01c31217-2229-4db2-af56-143ef51c0e91"



