#!/usr/bin/env dothttp

# imported from http://localhost:8000/Stripe%20API.postman_collection.json

@name("List all exchange rates")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604bd44e20>"
"Content-Type": "application/x-www-form-urlencoded"


@name("Retrieve an exchange rate")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f604bd448b0>"
"Content-Type": "application/x-www-form-urlencoded"



