#!/usr/bin/env dothttp

@name("Metadata Container Configuration Settings Get")
GET "https://{{baseUrl}}/platform/v2/metadatacontainerconfigurationsettings/:id"
"Authorization": "<string>"


@name("Metadata Container Configuration Settings Put")
PUT "https://{{baseUrl}}/platform/v2/metadatacontainerconfigurationsettings/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "id": [
        "<string>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "isActive": [
        "<boolean>"
    ],
    "namespace": [
        "<string>"
    ],
    "description": [
        "<string>"
    ],
    "value": [
        "<string>"
    ],
    "metadataContainer": [
        "<string>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})



