#!/usr/bin/env dothttp

// Returns the full record for all events that have occurred since the sync token was created.

@name("Get Events")
GET "https://{{baseUrl}}/events"
? "resource"= "<string>"
? "sync"= "<string>"


// Deletes a specific, existing project status update.

@name("Delete Project Statuses Project Status")
DELETE "https://{{baseUrl}}/project_statuses/:project-status_gid"


// Returns the compact records for all teams in the organization visible to the authorized user.

@name("Get Organizations Organization Teams")
GET "https://{{baseUrl}}/organizations/:organization_gid/teams"


// Returns the project membership record.

@name("Get Project Memberships Project Membership")
GET "https://{{baseUrl}}/project_memberships/:project_membership_gid"


// Updates the story and returns the full record for the updated story. Only comment stories can have their text updated, and only comment stories and attachment stories can be pinned. Only one of text and html_text can be specified.

@name("Put Stories Story")
PUT "https://{{baseUrl}}/stories/:story_gid"


// Returns the full record for a single attachment.

@name("Get Attachments Attachment")
GET "https://{{baseUrl}}/attachments/:attachment_gid"


// Updates an existing enum option. Enum custom fields require at least one enabled enum option.

@name("Put Enum Options Enum Option")
PUT "https://{{baseUrl}}/enum_options/:enum_option_gid"



