#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get a team (Legacy)")
GET "https://{{baseUrl}}/teams/{{team_id}}/"


@name("Update a team (Legacy)")
PATCH "https://{{baseUrl}}/teams/{{team_id}}/"
"Content-Type": "application/json"
json({
    "name": "new team name",
    "description": "new team description",
    "privacy": "closed"
})


@name("Delete a team (Legacy)")
DELETE "https://{{baseUrl}}/teams/{{team_id}}/"


@name("List pending team invitations (Legacy)")
GET "https://{{baseUrl}}/teams/{{team_id}}/invitations"
? "per_page"= "30"
? "page"= "1"


@name("List child teams (Legacy)")
GET "https://{{baseUrl}}/teams/{{team_id}}/teams"
? "per_page"= "30"
? "page"= "1"



