#!/usr/bin/env dothttp

// Retrieve package tracking information

@name("Get Tracking Information")
GET "https://{{baseUrl}}/v1/tracking"
"API-Key": "{{API_KEY}}"


// Allows you to subscribe to tracking updates for a package. You specify the carrier_code and tracking_number of the package,
// and receive notifications via webhooks whenever the shipping status changes.

@name("Start Tracking a Package")
POST "https://{{baseUrl}}/v1/tracking/start"
"API-Key": "{{API_KEY}}"


// Unsubscribe from tracking updates for a package.

@name("Stop Tracking a Package")
POST "https://{{baseUrl}}/v1/tracking/stop"
"API-Key": "{{API_KEY}}"



