#!/usr/bin/env dothttp

@name("List milestones")
GET "https://{{baseUrl}}/repos/:owner/:repo/milestones"
? "state"= "open"
? "sort"= "due_on"
? "direction"= "asc"
? "per_page"= "30"
? "page"= "1"


@name("Create a milestone")
POST "https://{{baseUrl}}/repos/:owner/:repo/milestones"
"Content-Type": "application/json"
data('{
    "title": "<string>",
    "state": "open",
    "description": "<string>",
    "due_on": "<string>"
}')



