#!/usr/bin/env dothttp

@name("Search Layout")
GET "https://{{host}}/services/data/v47.0/sobjects/SearchLayout/"


@name("Search Layout Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/SearchLayout/{ID}/"


@name("Describe Search Layout")
GET "https://{{host}}/services/data/v47.0/sobjects/SearchLayout/describe/"



