#!/usr/bin/env dothttp

@name("Api Event")
GET "https://{{host}}/services/data/v47.0/sobjects/ApiEvent/"


@name("Api Event Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/ApiEvent/{ID}/"


@name("Describe Api Event")
GET "https://{{host}}/services/data/v47.0/sobjects/ApiEvent/describe/"



