#!/usr/bin/env dothttp

@name("User Role")
GET "https://{{host}}/services/data/v47.0/sobjects/UserRole/"


@name("User Role Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/UserRole/{ID}/"


@name("Describe User Role")
GET "https://{{host}}/services/data/v47.0/sobjects/UserRole/describe/"



