#!/usr/bin/env dothttp

// Retrieves a database object using the ID specified in the request path. 

@name("Retrieve a database")
GET "https://api.notion.com/v1/databases/:id"
"Notion-Version": "2021-05-13"


@name("Query a Database")
POST "https://api.notion.com/v1/databases/:id/query"
"Authorization": "Bearer secret_t1CdN9S8yicG5eWLUOfhcWaOscVnFXns"
"Content-Type": "application/json"
"Notion-Version": "2021-05-13"
json({
    "filter": {
        "or": [
            {
                "property": "Status",
                "select": {
                    "equals": "Reading"
                }
            },
            {
                "property": "Publisher",
                "select": {
                    "equals": "NYT"
                }
            }
        ]
    },
    "sorts": [
        {
            "property": "Score /5",
            "direction": "ascending"
        }
    ]
})



