#!/usr/bin/env dothttp

// List link aggregation groups

@name("getNetworkSwitchLinkAggregations")
GET "https://{{baseUrl}}/networks/:networkId/switch/linkAggregations"
"Accept": "*/*"



// Create a link aggregation group
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// switchPorts| array| Array of switch or stack ports for creating aggregation group. Minimum 2 and maximum 8 ports are supported.
// switchProfilePorts| array| Array of switch profile ports for creating aggregation group. Minimum 2 and maximum 8 ports are supported.

@name("createNetworkSwitchLinkAggregation")
POST "https://{{baseUrl}}/networks/:networkId/switch/linkAggregations"
"Accept": "*/*"
"Content-Type": "application/json"
json({
    "switchPorts": [
        {
            "serial": "Q234-ABCD-0001",
            "portId": "1"
        },
        {
            "serial": "Q234-ABCD-0002",
            "portId": "2"
        },
        {
            "serial": "Q234-ABCD-0003",
            "portId": "3"
        },
        {
            "serial": "Q234-ABCD-0004",
            "portId": "4"
        },
        {
            "serial": "Q234-ABCD-0005",
            "portId": "5"
        },
        {
            "serial": "Q234-ABCD-0006",
            "portId": "6"
        },
        {
            "serial": "Q234-ABCD-0007",
            "portId": "7"
        },
        {
            "serial": "Q234-ABCD-0008",
            "portId": "8"
        }
    ]
})


// Update a link aggregation group
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// switchPorts| array| Array of switch or stack ports for updating aggregation group. Minimum 2 and maximum 8 ports are supported.
// switchProfilePorts| array| Array of switch profile ports for updating aggregation group. Minimum 2 and maximum 8 ports are supported.

@name("updateNetworkSwitchLinkAggregation")
PUT "https://{{baseUrl}}/networks/:networkId/switch/linkAggregations/:linkAggregationId"
"Accept": "*/*"
"Content-Type": "application/json"
json({
    "id": "NDU2N18yXzM=",
    "switchPorts": [
        {
            "serial": "Q234-ABCD-0001",
            "portId": "1"
        },
        {
            "serial": "Q234-ABCD-0002",
            "portId": "2"
        },
        {
            "serial": "Q234-ABCD-0003",
            "portId": "3"
        },
        {
            "serial": "Q234-ABCD-0004",
            "portId": "4"
        },
        {
            "serial": "Q234-ABCD-0005",
            "portId": "5"
        },
        {
            "serial": "Q234-ABCD-0006",
            "portId": "6"
        },
        {
            "serial": "Q234-ABCD-0007",
            "portId": "7"
        },
        {
            "serial": "Q234-ABCD-0008",
            "portId": "8"
        }
    ]
})


// Split a link aggregation group into separate ports

@name("deleteNetworkSwitchLinkAggregation")
DELETE "https://{{baseUrl}}/networks/:networkId/switch/linkAggregations/:linkAggregationId"
"Accept": "*/*"




