#!/usr/bin/env dothttp

# imported from http://localhost:8000/Salesforce_APIs.postman_collection.json

@name("Generate Quote Document API")
POST "https://{{_endpoint}}/services/apexrest/SBQQ/ServiceRouter"
"Content-Type": "application/json"
? "loader"= "QuoteDocumentAPI.SaveProposal"
json({
    "saver": "SBQQ.QuoteDocumentAPI.Save",
    "model": {
        "name": "test",
        "quoteId": "<SFDC_ID>",
        "templateId": "<SFDC_ID>",
        "outputFormat": "PDF",
        "language": "en_US",
        "paperSize": "Default"
    }
})



