#!/usr/bin/env dothttp

// Update a role

@name("/users-permissions/roles/:role")
PUT "https://{{baseUrl}}/users-permissions/roles/:role"
"Content-Type": "application/json"
json({
    "name": "minim Excepteur velit consectetur laborum",
    "description": "in minim ",
    "type": "mollit ex",
    "permissions": [
        "dolore non nisi cillum",
        "laborum voluptate incididunt pariatur id"
    ],
    "users": [
        "dolor",
        "proident sed ad in"
    ],
    "created_by": "adipisicing nostrud in",
    "updated_by": "irure ut Duis"
})


// Delete a role

@name("/users-permissions/roles/:role")
DELETE "https://{{baseUrl}}/users-permissions/roles/:role"



