#!/usr/bin/env dothttp

// Use this API call to update a single DNS check in Sonar.

@name("Update DNS Check")
PUT "https://api.sonar.constellix.com/rest/api/dns/99999"
"x-cns-security-token": "{{token}}"
"Content-Type": "application/json"
json({
    "name": "example",
    "checkSites": [
        16
    ]
})


// This call will create a DNS Check in your Sonar account.

@name("Create DNS Check")
POST "https://api.sonar.constellix.com/rest/api/dns"
"Content-Type": "application/json"
"x-cns-security-token": "{{token}}"
json({
    "name": "Example",
    "fqdn": "google.co.uk",
    "resolver": "google.co.uk",
    "checkSites": [
        1,
        2
    ]
})


// This call will return all the details for a single Sonar check.

@name("Get DNS Check Details")
GET "https://api.sonar.constellix.com/rest/api/dns/99999"
"x-cns-security-token": "{{token}}"
"Content-Type": "application/json"


// This API call will return all configured DNS checks within your Sonar account.

@name("Get All DNS Checks")
GET "https://api.sonar.constellix.com/rest/api/dns"
"x-cns-security-token": "{{token}}"
"Content-Type": "application/json"
? "ids"= "13550"
? "ids"= "14550"



