#!/usr/bin/env dothttp

// This endpoint lists information about one or more videos, including the aspect ratio and URLs to previews.

@name("List videos")
GET "https://{{baseUrl}}/v2/videos"
? "id"= "<string>"
? "view"= "minimal"


// This endpoint shows information about a video, including URLs to previews and the sizes that it is available in.

@name("Get details about videos")
GET "https://{{baseUrl}}/v2/videos/:id"
? "language"= "<string>"
? "view"= "full"


// This endpoint lists the categories (Shutterstock-assigned genres) that videos can belong to.

@name("List video categories")
GET "https://{{baseUrl}}/v2/videos/categories"
? "language"= "<string>"



