#!/usr/bin/env dothttp

// Return the access control lists for a MS network

@name("Return The Access Control Lists For A MS Network")
GET "https://{{baseUrl}}/networks/:networkId/switch/accessControlLists"
"X-Cisco-Meraki-API-Key": ""


// Update the access control lists for a MS network
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// rules| array| An ordered array of the access control list rules (not including the default rule). An empty array will clear the rules.

@name("Update The Access Control Lists For A MS Network")
PUT "https://{{baseUrl}}/networks/:networkId/switch/accessControlLists"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
json({
    "rules": [
        {
            "policy": "<string>",
            "protocol": "<string>",
            "srcCidr": "<string>",
            "dstCidr": "<string>",
            "comment": "<string>",
            "ipVersion": "<string>",
            "srcPort": "<string>",
            "dstPort": "<string>",
            "vlan": "<string>"
        },
        {
            "policy": "<string>",
            "protocol": "<string>",
            "srcCidr": "<string>",
            "dstCidr": "<string>",
            "comment": "<string>",
            "ipVersion": "<string>",
            "srcPort": "<string>",
            "dstPort": "<string>",
            "vlan": "<string>"
        }
    ]
})



