#!/usr/bin/env dothttp

@name("Get entity from CandidateBackground_Languages by key")
GET "https://{{baseUrl}}/CandidateBackground_Languages({{backgroundElementId}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
? "$select"= "lastModifiedDateTime,readingProf"
? "$expand"= "candidate,*"


@name("Update entity in CandidateBackground_Languages")
PUT "https://{{baseUrl}}/CandidateBackground_Languages({{backgroundElementId}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
"Content-Type": "application/json"
data('{
    "d": {
        "backgroundElementId": "veniam in exercitation",
        "bgOrderPos": "cillum eiusmod proident",
        "candidateId": "fugiat est do",
        "language": "officia cupidatat commodo",
        "lastModifiedDateTime": "/Date(1492098664000)/",
        "readingProf": "eu veniam sit dolore",
        "speakingProf": "do in qui",
        "writingProf": "dolore Duis veniam do",
        "candidate": {
            "address": "enim Ut est ut",
            "address2": "sunt deserunt velit",
            "agreeToPrivacyStatement": "nostrud sint pariatur dolore",
            "anonymized": "adipisicing sit",
            "anonymizedDateTime": "/Date(1492098664000)/",
            "candidateId": "non nulla pariatur",
            "candidateLocale": "velit adipisicing culpa dolor tempor",
            "cellPhone": "exercitation eiusmod consectetur",
            "city": "ea fugiat Ut",
            "contactEmail": "dolore culpa voluptate do",
            "country": "aute in minim Excepteur",
            "creationDateTime": "/Date(1492098664000)/",
            "currentTitle": "Excepteur commodo nostrud",
            "dataPrivacyId": "amet Ut enim",
            "dateofAvailability": "/Date(1492098664000)/",
            "externalCandidate": true,
            "firstName": "dolor consequat est",
            "homePhone": "commodo reprehenderit Ut laboris aliqua",
            "lastLoginDateTime": "/Date(1492098664000)/",
            "lastModifiedDateTime": "/Date(1492098664000)/",
            "lastName": "incididunt pariatur reprehenderit Duis",
            "middleName": "voluptate in aliqua",
            "partnerMemberId": "ipsum voluptate in occaecat",
            "partnerSource": "est nulla esse ut id",
            "password": "cupidatat eu cillum amet",
            "primaryEmail": "in dolore incididunt",
            "privacyAcceptDateTime": "/Date(1492098664000)/",
            "publicIntranet": false,
            "shareProfile": "sint Duis",
            "usersSysId": "in aute exercitation dolore",
            "visibilityOption": true,
            "zip": "Duis consectetur adipisi",
            "candidateProfileExtension": {
                "candidateId": "sunt Duis magna exerc",
                "createdBy": "Lorem Ut eiusmod esse",
                "createdDateTime": "/Date(1492098664000)/",
                "lastModifiedBy": "exercitation",
                "lastModifiedDateTime": "/Date(1492098664000)/",
                "mdfSystemRecordStatus": "Lorem reprehenderit"
            },
            "certificates": {
                "results": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ]
            },
            "education": {
                "results": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ]
            },
            "insideWorkExperience": {
                "results": [
                    {
                        "value": "<Circular reference to #/components/schemas/SFOData.CandidateBackground_InsideWorkExperience detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/SFOData.CandidateBackground_InsideWorkExperience detected>"
                    }
                ]
            },
            "languages": {
                "results": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ]
            },
            "outsideWorkExperience": {
                "results": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ]
            },
            "tags": {
                "results": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ]
            },
            "talentPool": {
                "results": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ]
            },
            "talentPoolcorp": {
                "results": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ]
            }
        }
    }
}')



