#!/usr/bin/env dothttp

// NASA’s InSight Mars lander takes continuous weather measurements (temperature, wind, pressure) on the surface of Mars at Elysium Planitia, a flat, smooth plain near Mars’ equator. Summaries of these data are available at https://mars.nasa.gov/insight/weather/. 

@name("Weather")
GET "https://api.nasa.gov/insight_weather/"
? "api_key"= "{{api_key}}"
? "feedtype"= "json"
? "ver"= "1.0"



