#!/usr/bin/env dothttp

// ## Login Api
// 
// Test Admin

@name("CREATE")
POST "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/admin/api/v1/users/customers"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1Nzc1OTk0NywiZXhwIjoxNTU4MzY0NzQ3fQ.HKTilltsNw-f4MHrWOLHsuVxoksjQ-LwMwI7akrBENA"
data('{
    "firstname": "Mithun",
    "lastname": "Das",
    "phone": "+919836810493",
    "email": "mithun.das@jumacro.com",
    "password": "123456789"
    
}')


// ## Login Api
// 
// Test Admin

@name("READ")
GET "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/admin/api/v1/users/customers"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1OTU4NzU5NiwiZXhwIjoxNTYwMTkyMzk2fQ.tiKzXZiJunGczMLtKuitXsilRl320cjMFQ67nw6LcRw"


// ## Login Api
// 
// Test Admin

@name("UPDATE")
PUT "http://ec2-54-154-59-231.eu-west-1.compute.amazonaws.com/admin/api/v1/users/5cd9847f347f1f199c6c434a"
"Content-Type": "application/json"
"Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDk4NTY3MzQ3ZjFmMTk5YzZjNDM0YiIsImlhdCI6MTU1Nzc1OTk0NywiZXhwIjoxNTU4MzY0NzQ3fQ.HKTilltsNw-f4MHrWOLHsuVxoksjQ-LwMwI7akrBENA"
data('{
    "phone": "+4466464646"
    
}')



