#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get organization membership for a user")
GET "https://{{baseUrl}}/orgs/{{org}}/memberships/{{username}}/"


@name("Set organization membership for a user")
PUT "https://{{baseUrl}}/orgs/{{org}}/memberships/{{username}}/"
"Content-Type": "application/json"
json({
    "role": "member"
})


@name("Remove organization membership for a user")
DELETE "https://{{baseUrl}}/orgs/{{org}}/memberships/{{username}}/"



