#!/usr/bin/env dothttp

// Returns [PAN](#pan-entity) details

@name("Fetch PAN")
GET "https://{{host}}/pans/:pan"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"
? "consent"= "{{consent}}"
? "reason"= "{{reason}}"



