#!/usr/bin/env dothttp

@name("Returns a list of taxAreas")
GET "https://{{baseUrl}}/companies({{company_id}})/taxAreas"
? "$top"= "<integer>"
? "$skip"= "<integer>"
? "$limit"= "<integer>"
? "$filter"= "<string>"
? "$select"= "<string>,<string>"


@name("Creates an object of type taxArea in Dynamics 365 Business Central")
POST "https://{{baseUrl}}/companies({{company_id}})/taxAreas"
"Content-Type": "<string>"
"Content-Type": "application/json"
json({
    "id": "<uuid>",
    "code": "<string>",
    "displayName": "<string>",
    "taxType": "<string>",
    "lastModifiedDateTime": "<dateTime>"
})



