#!/usr/bin/env dothttp

// https://devdocs.transsmart.com/#_retrieve_list
// 
// Method for retrieving the list of shipments that are waiting to be manifested.
// There are a few request parameters that can be used to filter the list. For details, please refer to the link above.

@name("2.4.1 Retrieve list")
GET "https://{{base_url}}/v2/shipments/{{account}}/manifest/list"
? "date"= "{{pickupDate}}"
? "carrier"= "DHP"
? "pagedResult"= "false"
? "size"= "5"
? "page"= "0"


// https://devdocs.transsmart.com/#_manifest_shipments
// 
// Triggers the creation of a manifest for the provided combination of request parameters.
// Returns true if shipments were manifested, else false.

@name("2.4.2 Trigger manifest")
GET "https://{{base_url}}/v2/shipments/{{account}}/manifest"
? "from"= "{{pickupDate}}"
? "to"= "{{pickupDate}}"
? "carrier"= "DHP"


// https://devdocs.transsmart.com/#_retrieve_list
// 
// Method for retrieving the list of shipments that are waiting to be manifested. Response will not be a json format, it will be a downloadable document.
// 
// There are a few request parameters that can be used to filter the list. For details, please refer to the link above.

@name("2.4.3 Retrieve list download")
GET "https://{{base_url}}/v2/shipments/{{account}}/manifest/list/download"
? "date"= "{{pickupDate}}"
? "carrier"= "DHP"
? "pagedResult"= "false"



