#!/usr/bin/env dothttp

@name("List all credit notes")
GET "https://{{baseUrl}}/v1/credit_notes"
"Content-Type": "application/x-www-form-urlencoded"
? "customer"= "<string>"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "invoice"= "<string>"
? "limit"= "<integer>"
? "starting_after"= "<string>"


@name("Create a credit note")
POST "https://{{baseUrl}}/v1/credit_notes"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "invoice": [
        "<string>"
    ],
    "amount": [
        "<integer>"
    ],
    "credit_amount": [
        "<integer>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "lines[0]": [
        "{\"type\":\"<string>\",\"amount\":\"<integer>\",\"description\":\"<string>\",\"invoice_line_item\":\"<string>\",\"quantity\":\"<integer>\",\"tax_rates\":[\"<string>\",\"<string>\"],\"unit_amount\":\"<integer>\",\"unit_amount_decimal\":\"<decimal>\"}"
    ],
    "lines[1]": [
        "{\"type\":\"<string>\",\"amount\":\"<integer>\",\"description\":\"<string>\",\"invoice_line_item\":\"<string>\",\"quantity\":\"<integer>\",\"tax_rates\":[\"<string>\",\"<string>\"],\"unit_amount\":\"<integer>\",\"unit_amount_decimal\":\"<decimal>\"}"
    ],
    "memo": [
        "<string>"
    ],
    "out_of_band_amount": [
        "<integer>"
    ],
    "reason": [
        "<string>"
    ],
    "refund": [
        "<string>"
    ],
    "refund_amount": [
        "<integer>"
    ]
})


@name("Preview a credit note")
GET "https://{{baseUrl}}/v1/credit_notes/preview"
"Content-Type": "application/x-www-form-urlencoded"
? "amount"= "<integer>"
? "credit_amount"= "<integer>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "invoice"= "<string>"
? 'lines[0]'= '{"type":"<string>","amount":"<integer>","description":"<string>","invoice_line_item":"<string>","quantity":"<integer>","tax_rates":["<string>","<string>"],"unit_amount":"<integer>","unit_amount_decimal":"<decimal>"}'
? 'lines[1]'= '{"type":"<string>","amount":"<integer>","description":"<string>","invoice_line_item":"<string>","quantity":"<integer>","tax_rates":["<string>","<string>"],"unit_amount":"<integer>","unit_amount_decimal":"<decimal>"}'
? "memo"= "<string>"
? "out_of_band_amount"= "<integer>"
? "reason"= "<string>"
? "refund"= "<string>"
? "refund_amount"= "<integer>"


@name("Retrievee a credit note's preview items")
GET "https://{{baseUrl}}/v1/credit_notes/preview/lines"
"Content-Type": "application/x-www-form-urlencoded"
? "amount"= "<integer>"
? "credit_amount"= "<integer>"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "invoice"= "<string>"
? "limit"= "<integer>"
? 'lines[0]'= '{"type":"<string>","amount":"<integer>","description":"<string>","invoice_line_item":"<string>","quantity":"<integer>","tax_rates":["<string>","<string>"],"unit_amount":"<integer>","unit_amount_decimal":"<decimal>"}'
? 'lines[1]'= '{"type":"<string>","amount":"<integer>","description":"<string>","invoice_line_item":"<string>","quantity":"<integer>","tax_rates":["<string>","<string>"],"unit_amount":"<integer>","unit_amount_decimal":"<decimal>"}'
? "memo"= "<string>"
? "out_of_band_amount"= "<integer>"
? "reason"= "<string>"
? "refund"= "<string>"
? "refund_amount"= "<integer>"
? "starting_after"= "<string>"


@name("Retrieve a credit note's line items")
GET "https://{{baseUrl}}/v1/credit_notes/:credit_note/lines"
"Content-Type": "application/x-www-form-urlencoded"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "limit"= "<integer>"
? "starting_after"= "<string>"


@name("Retrieve a credit note")
GET "https://{{baseUrl}}/v1/credit_notes/:id"
"Content-Type": "application/x-www-form-urlencoded"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"


@name("Update a credit note")
POST "https://{{baseUrl}}/v1/credit_notes/:id"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ],
    "memo": [
        "<string>"
    ]
})


@name("Void a credit note")
POST "https://{{baseUrl}}/v1/credit_notes/:id/void"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})



