#!/usr/bin/env dothttp

@name("Register User")
POST "https://{{authPath}}/{{envID}}/flows/{{flowID}}"
"Content-Type": "application/vnd.pingidentity.user.register+json"
"Cookie": "ST={{sessionToken}}"
data('{
    "username": "register-user_{{$timestamp}}",
    "email": "do-not-send@pingidentity.com",
    "password": "2Federate!"
}')


@name("Send (Resend) Verification Code")
POST "https://{{authPath}}/{{envID}}/flows/{{flowID}}"
"Content-Type": "application/vnd.pingidentity.user.sendVerificationCode+json"
"Cookie": "ST={{sessionToken}}"
data('{
    "verificationCode": "xxxxxx"
}')


@name("Verify User")
POST "https://{{authPath}}/{{envID}}/flows/{{flowID}}"
"Content-Type": "application/vnd.pingidentity.user.verify+json"
"Cookie": "ST={{sessionToken}}"
data('{
    "verificationCode": "xxxxxx"
}')



