#!/usr/bin/env dothttp

@name("/wc/v3/products/categories/batch")
POST "https://{{baseUrl}}/wc/v3/products/categories/batch"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
"Content-Type": "multipart/form-data"
files(
	("name", "<string>"),
	("slug", "<string>"),
	("parent", "<string>"),
	("description", "<string>"),
	("display", "["<string>","<string>"]"),
	("image", "<string>"),
	("menu_order", "<string>")
)


@name("/wc/v3/products/categories/batch")
PUT "https://{{baseUrl}}/wc/v3/products/categories/batch"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "name"= "<string>"
? "slug"= "<string>"
? "parent"= "<string>"
? "description"= "<string>"
? "display"= "<string>"
? "display"= "<string>"
? "image"= "<string>"
? "menu_order"= "<string>"


@name("/wc/v3/products/categories/batch")
PATCH "https://{{baseUrl}}/wc/v3/products/categories/batch"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "name"= "<string>"
? "slug"= "<string>"
? "parent"= "<string>"
? "description"= "<string>"
? "display"= "<string>"
? "display"= "<string>"
? "image"= "<string>"
? "menu_order"= "<string>"



