#!/usr/bin/env dothttp

@name("Create User")
POST "http://localhost/user/create"
"Content-Type": "application/json"
json({
    "first_name": "jacopo",
    "last_name": "bonardi",
    "email": "jacopobonardi@hotmail.com",
    "password": "facebook",
    "age": 27,
    "city": "smallville",
    "city_code": 95670,
    "street_number": 110,
    "street_type": "rue",
    "street_name": "bonaparte",
    "phone": "01 97 56 98 56"
})


@name("Show all User")
GET "http://localhost/user/show/"


@name("Show User By Id")
GET "http://localhost/user/show/5ef904c2d66b1950aa0da703"


@name("Update User By Id")
PUT "http://localhost/user/update/5ebd4956892f50569e017e36"
json({
    "first_name": "david"
})


@name("Delete User By Id")
DELETE "http://localhost/user/destroy/5e5f8dfef32b8b655dde43f1"
"Content-Type": "application/json"
json({
    "first_name": "firstname_1dddE1"
})


@name("Search User")
POST "http://localhost/user/search"
json({
    "limit": 5,
    "sort": {
        "first_name": -1
    }
})



