#!/usr/bin/env dothttp

@name("get Mall Coupons")
GET "https://{{baseUrl}}/malls/:id/coupons"
? "checkpoint_id"= "<checkpoint_id>"
? "forward"= "laborum"
? "size"= "laborum"


@name("/malls/:id/coupons")
OPTIONS "https://{{baseUrl}}/malls/:id/coupons"



