#!/usr/bin/env dothttp

@name("Send Text Message")
GET "https://bsms.hostandsoft.com/app/sms/api"
? "action"= "send-sms"
? "api_key"= "YOUR API KEY"
? "to"= "RECIPIENT NUMBER "
? "from"= "SENDER ID"
? "sms"= "MESSAGE"


@name("Send Text Message")
POST "https://bsms.hostandsoft.com/app/sms/api"
files(
	("action", "send-sms"),
	("api_key", "YOUR API KEY"),
	("to", "RECIPIENT NUMBER "),
	("from", "SENDER ID"),
	("sms", "MESSAGE")
)


@name("Send Unicode Message")
GET "https://bsms.hostandsoft.com/app/sms/api"
? "action"= "send-sms"
? "api_key"= "YOUR API KEY"
? "to"= "RECIPIENT NUMBER "
? "from"= "SENDER ID"
? "sms"= "MESSAGE"
? "unicode"= "1"


@name("Send Unicode Message")
POST "https://bsms.hostandsoft.com/app/sms/api"
files(
	("action", "send-sms"),
	("api_key", "YOUR API KEY"),
	("to", "RECIPIENT NUMBER "),
	("from", "SENDER ID"),
	("sms", "MESSAGE"),
	("unicode", "1")
)


@name("Send Scheduled Message")
GET "https://bsms.hostandsoft.com/app/sms/api"
? "action"= "send-sms"
? "api_key"= "YOUR API KEY"
? "to"= "RECIPIENT NUMBER "
? "from"= "SENDER ID"
? "sms"= "MESSAGE"
? "schedule"= "SCHEDULE TIME"


@name("Send Scheduled Message")
POST "https://bsms.hostandsoft.com/app/sms/api"
files(
	("action", "send-sms"),
	("api_key", "YOUR API KEY"),
	("to", "RECIPIENT NUMBER "),
	("from", "SENDER ID"),
	("sms", "MESSAGE"),
	("schedule", "SCHEDULE TIME")
)



