#!/usr/bin/env dothttp

// Similar to querying shipments, we allow you to query manifests since there will likely be a large number over a long period of time.

@name("List Manifests")
GET "https://{{baseUrl}}/v1/manifests"
"API-Key": "{{API_KEY}}"


// Each ShipEngine manifest is created for a specific warehouse, so you'll need to provide the warehouse_id
// rather than the ship_from address. You can create a warehouse for each location that you want to create manifests for.

@name("Create Manifest")
POST "https://{{baseUrl}}/v1/manifests"
"API-Key": "{{API_KEY}}"
"Content-Type": "application/json"
data('""')


// Get Manifest By Id

@name("Get Manifest By Id")
GET "https://{{baseUrl}}/v1/manifests/:manifest_id"
"API-Key": "{{API_KEY}}"



