#!/usr/bin/env dothttp

// Bulk Get Devices Detail

@name("Get Devices List")
GET "http://api.kpiiot.com/devices/batch"
"apiKey": "boellFwZM5CsjyJqX3Mu5xKFqVmMgojS"
"": ""
? "device_ids"= "18932"
? "sno"= "KINGPIGEONTEST03"
? "status"= "4"
? "size"= "10"


// Get the Device Detail(Include Data Points List) according to Device ID 

@name("Get Data Points List by Device ID")
GET "http://api.kpiiot.com/devices/18932"
"apiKey": "boellFwZM5CsjyJqX3Mu5xKFqVmMgojS"


// Get the Current Values of devices according to the device ids.

@name("Get Current Values  by Device Id List")
GET "http://api.kpiiot.com/devices/datastreams"
"apiKey": "boellFwZM5CsjyJqX3Mu5xKFqVmMgojS"
? "device_ids"= "18932"


// Get the history data of the data points 

@name("Get History Data by device_id")
GET "http://api.kpiiot.com/devices/18932/datastreams"
"apiKey": "boellFwZM5CsjyJqX3Mu5xKFqVmMgojS"
? "param_ids"= "1729"
? "limit"= "10"


// Commit a Control Command to the Server to control the device.

@name("Send Command")
POST "http://api.kpiiot.com/devices/cmds"
"apiKey": "boellFwZM5CsjyJqX3Mu5xKFqVmMgojS"
? "device_id"= "18932"
? "param_id"= "1729"
? "rw"= "2"
? "data"= "1"


// Get the Current Value of the Device According to Device ID

@name("Get Current Values by Device ID")
GET "http://47.107.247.209/devices/18860/datapoints"
"apiKey": "1MirQHBBO8FtDcZ0Yj0uRLErJTZ8hthr"


// Add a New Device

@name("Add New Device(Testing Version)")
POST "http://47.107.247.209/devices"
"apiKey": "1MirQHBBO8FtDcZ0Yj0uRLErJTZ8hthr"
? "name"= "testxuhw"



