#!/usr/bin/env dothttp

// Adds profiles to a list. This endpoint is functionally equivalent to adding profiles to a list via a CSV upload and will immediately add profiles to the list. If you would like to subscribe profiles to a list and use the double opt-in settings for the list, please use the subscribe endpoint.

@name("Add Members to a List")
POST "https://{{baseUrl}}/v2/list/:list_id/members"
"Content-Type": "application/json"
? "api_key"= "PRIVATE_KEY"
json({
    "profiles": [
        {
            "email": "george.washington@klaviyo.com"
        },
        {
            "phone_number": "13239169023"
        }
    ]
})


// Checks if profiles are in a specific list.

@name("Check if Profiles Are in a Specific List")
GET "https://{{baseUrl}}/v2/list/:list_id/members"
? "api_key"= "PRIVATE_KEY"
? "emails"= "george.washington@klaviyo.com"
? "emails"= "john.adams@klaviyo.com"
? "phone_numbers"= "13239169023"
? "push_tokens"= "PUSH_TOKEN"


// Removes profiles from a list.

@name("Remove Profiles From List")
DELETE "https://{{baseUrl}}/v2/list/:list_id/members"
"Content-Type": "application/json"
? "api_key"= "PRIVATE_KEY"
json({
    "emails": [
        "george.washington@klaviyo.com",
        "abraham.lincoln@klaviyo.com"
    ],
    "phone_numbers": [
        "13239169023"
    ],
    "push_tokens": [
        "PUSH_TOKEN"
    ]
})



