#!/usr/bin/env dothttp

@name("cancelDirectDebit")
GET "http://api.openbanking.ng/direct_debit/cancelDirectDebit"
"Accept": "*/*"
"Content-Type": "application/json"
? "cancelationReason"= "{{cancelationReason}}"
data('Reference ID and Cancelation Reason')


@name("getDirectDebit")
GET "http://api.openbanking.ng/direct_debit/getDirectDebit"
"Accept": "*/*"
"Content-Type": "application/json"
? "accountNumber"= "{{accountNumber}}"
data('Reference Number and Account Number')


@name("setupDirectDebit")
POST "http://api.openbanking.ng/direct_debit/setupDirectDebit"
"Accept": "*/*"
"Content-Type": "application/json"
data('directDebitSetup')



