#!/usr/bin/env dothttp

// Return the MTU configuration

@name("Return The MTU Configuration")
GET "https://{{baseUrl}}/networks/:networkId/switch/mtu"
"X-Cisco-Meraki-API-Key": ""


// Update the MTU configuration
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// defaultMtuSize| integer| MTU size for the entire network. Default value is 9578.
// overrides| array| Override MTU size for individual switches or switch profiles. An empty array will clear overrides.
// 
// #### Supports Action Batches
// 
// **Resource**|**Operation**
// :-------------: |:-------------:
// `/networks/{networkId}/switch/mtu` | update
// 

@name("Update The MTU Configuration")
PUT "https://{{baseUrl}}/networks/:networkId/switch/mtu"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "defaultMtuSize": "<integer>",
    "overrides": [
        {
            "mtuSize": "<integer>",
            "switches": [
                "<string>",
                "<string>"
            ],
            "switchProfiles": [
                "<string>",
                "<string>"
            ]
        },
        {
            "mtuSize": "<integer>",
            "switches": [
                "<string>",
                "<string>"
            ],
            "switchProfiles": [
                "<string>",
                "<string>"
            ]
        }
    ]
}')



