#!/usr/bin/env dothttp

@name("Content Version Comment")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentVersionComment/"


@name("Content Version Comment Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentVersionComment/{ID}/"


@name("Describe Content Version Comment")
GET "https://{{host}}/services/data/v47.0/sobjects/ContentVersionComment/describe/"



