#!/usr/bin/env dothttp

// The `GET /environments/{environmentId}/notificationsSettings` endpoint returns the notifications settings resource for a specified environment.

@name("READ Notifications Settings")
GET "https://{{apiPath}}/environments/{{envID}}/notificationsSettings"
"Authorization": "Bearer {{jwtToken}}"
data('curl -X "GET" "https://api.pingone.com/v1/environments/{environmentId}/notificationsSettings" \
-H \'Authorization: Bearer jwtToken\'
')


// The `PUT /environments/{environmentId}/notificationsSettings` endpoint updates the notifications settings for the specified environment.

@name("UPDATE Notifications Settings")
PUT "https://{{apiPath}}/environments/{{envID}}/notificationsSettings"
"Content-Type": "application/json"
"Authorization": "Bearer {{jwtToken}}"
data('{
    "restrictions": {
        "smsVoiceQuota": {
            "daily": 1
        }
    },
    "whitelist": [
        {
            "user": {
                "id": "ef285863-10b6-4b84-800e-4285b2e140cd"
            }
        }
    ],
    "smsProvidersFallbackChain": [ {TwilioPhoneDeliverySettingsId}, "PINGONE_TWILIO" ],
    "deliveryMode": "WHITELIST",
    "defaultLanguage": "en"
}')


// The `DELETE /environments/{environmentId}/notificationsSettings` operation resets the notifications settings for the specified environment to its default.
// 
// A successful DELETE orreset operation returns an HTTP 200 OK status, and the notifications resource reset with its default settings.

@name("DELETE Notifications Settings")
DELETE "https://{{apiPath}}/environments/{{envID}}/notificationsSettings"
"Authorization": "Bearer {{jwtToken}}"




