#!/usr/bin/env dothttp

// > **Note**: Sending sensitive information in the query string is arguably not secure, but you will likely come across this if you're working with public APIs. If you're building your own API, a better option is to send the API key as an Authorization header, as seen in the last example.
// 
// Sending an API key in the query string as part of the URL is a common practice. 
// 
// Go to the [NASA API portal](https://api.nasa.gov/), and sign up for an API key to access and use web services available on the Data.gov developer network. An API key is a required query parameter for this request, as seen under the **Params** tab. If you don't have a valid API key, you can browse the [saved examples](https://learning.postman.com/docs/postman/collections/examples/).
// 
// #### Update your environment variable
// [Update the environment variable](https://learning.postman.com/docs/postman/variables-and-environments/managing-environments/#accessing-environments) called `api_key` by adding your own API key, and hit **Send**.
// 
// #### Keep your environment variable private
// If you're [sharing the environment](https://learning.postman.com/docs/postman/variables-and-environments/managing-environments/#working-with-environments-as-a-team) with your team in a team workspace, use the environment's **initial** value to share data with the team. Use the environment's **current** value to restrict this data to your session within the Postman app.
// 
// #### Use your environment variable
// You can access `api_key` using double curly braces in the text fields, like `{{api_key}}`, as seen under the **Params** tab.
// You can also access `api_key` using `pm.environment.get('variableName')` in the script areas, as seen under the **Pre-request Script** tab.

@name("API key as query parameter")
GET "https://api.nasa.gov/planetary/apod"
? "api_key"= "{{api_key}}"


// We are going to re-create the same request as the previous example, but this time using an Authorization helper. Using an Authorization helper allows us to [re-use the same authorization](https://learning.postman.com/docs/postman/sending-api-requests/authorization/#inheriting-auth) throughout an entire collection, folder, or as seen here - a single request.
// 
// #### Add an Authorization helper
// Under the **Authorization** tab, select **API Key** from the TYPE dropdown. Add your Key and Value here. In this example, we will configure the helper to add this data to **Query Params**. You can preview this under the **Params** tab. 
// 
// > **Note**: auto-generated query parameters and headers are included in the [Postman-generated code snippets](https://learning.postman.com/docs/postman/sending-api-requests/generate-code-snippets/), but not included in the [Postman documentation](https://learning.postman.com/docs/postman/api-documentation/documenting-your-api/) rendered in the web. 
// 
// > If you want to be explicit in the documentation about required parameters, then manually add the parameters as shown in the previous example. If you want to be explicit in the documentation about required headers, then manually add a request header, as shown in the next example.

@name("Using an Authorization helper")
GET "https://api.nasa.gov/planetary/apod"


// Under the **Headers** tab, add a Key and Value for Postman to send as headers. For example, the [Postman API](https://explore.postman.com/api/1590/postman-api) allows you to add an `x-api-key` request header. Create an environment variable with the value of your Postman API key, and hit **Send**.
// 
// > **Note**: these headers are included in the [Postman documentation](https://learning.postman.com/docs/postman/api-documentation/documenting-your-api/) rendered in the web, but the auto-generated headers and params shown in the previous request are not. If you want to be explicit in the documentation, then add headers as shown in this example.
// 
// #### Keep your environment variable private
// Remember, if you're [sharing the environment](https://learning.postman.com/docs/postman/variables-and-environments/managing-environments/#working-with-environments-as-a-team) with your team in a team workspace, use the environment's **initial** value to share data with the team. Use the environment's **current** value to restrict this data to your session within the Postman app.
// 
// #### Final check before publishing documentation
// If you plan to publish collection and environment, you can [preview the documentation](https://learning.postman.com/docs/postman/api-documentation/publishing-your-docs/#configuring-your-public-docs). Postman will warn you about anything that appears to be a sensitive token. For example, if you accidentally put your Postman API key in the **initial** value (instead of **current** value), Postman will highlight those secrets in the live preview.

@name("Adding a request header")
GET "https://{{base_url}}/collections"
"x-api-key": "{{postman_api_key}}"



