#!/usr/bin/env dothttp

# imported from https://raw.githubusercontent.com/fbsamples/WhatsApp-Business-API-Postman-Collection/master/collection.json

@name("Check-Contact")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f44a4a08f40>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
   "blocking": "wait",
   "contacts": [
      "{{Recipient-WA-ID}}"
   ],
   "force_check": "<false (default) | true>"
}')


@name("Check-Contact-Async")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49c7100>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
   "contacts": [
      "{{Recipient-WA-ID}}"
   ],
   "force_check": "<false (default) | true>"
}')


@name("Contact-Get-Identity")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49c75e0>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"


@name("Contact-Ack-Identity")
PUT "<dotextensions.server.postman2_1.URLClass object at 0x7f44a49c7370>"
"Content-Type": "application/json"
"Authorization": "Bearer {{AdminAuthToken}}"
data('{
   "hash": "<identity hash>"
}')



