#!/usr/bin/env dothttp

// A simple `GET` request to determine the status of the latest bitbucket pipelines build on the `develop` branch of the specified repository.
@name("Documenter Service")
GET "https://api.bitbucket.org/2.0/repositories/postmanlabs/scribe/pipelines/"
basicauth("{{username}}", "{{token}}")
"Authorization": "Basic cG9zdG1hbi1hZG1pbjpIWkc4N3pMaE5MdTZ5VGcyakwzZQ=="
? "sort"= "-created_on"
? "target.ref_name"= "develop"



// A simple `GET` request to determine the status of the latest bitbucket pipelines build on the `develop` branch of the specified repository.
@name("God Service")
GET "https://api.bitbucket.org/2.0/repositories/postmanlabs/postman-god-server/pipelines/"
basicauth("{{username}}", "{{token}}")
"Authorization": "Basic cG9zdG1hbi1hZG1pbjpIWkc4N3pMaE5MdTZ5VGcyakwzZQ=="
? "sort"= "-created_on"
? "target.ref_name"= "develop"



// A simple `GET` request to determine the status of the latest bitbucket pipelines build on the `develop` branch of the specified repository.
@name("Identity Service")
GET "https://api.bitbucket.org/2.0/repositories/postmanlabs/postman-identity-service/pipelines/"
basicauth("{{username}}", "{{token}}")
"Authorization": "Basic cG9zdG1hbi1hZG1pbjpIWkc4N3pMaE5MdTZ5VGcyakwzZQ=="
? "sort"= "-created_on"
? "target.ref_name"= "develop"



// A simple `GET` request to fetch the latest `Postman Native` build from the corresponding BuildKite agent. (Mac only for now)
@name("Postman Native")
GET "https://api.buildkite.com/v2/organizations/postman/pipelines/postman-app-nightly-builds/builds"
? "branch"= "develop"
? "access_token"= "{{buildkite_token}}"



// A simple `GET` request to determine the status of the latest bitbucket pipelines build on the `develop` branch of the specified repository.
@name("Presence Service")
GET "https://api.bitbucket.org/2.0/repositories/postmanlabs/presence/pipelines/"
basicauth("{{username}}", "{{token}}")
"Authorization": "Basic cG9zdG1hbi1hZG1pbjpIWkc4N3pMaE5MdTZ5VGcyakwzZQ=="
? "sort"= "-created_on"
? "target.ref_name"= "develop"



// A simple `GET` request to determine the status of the latest bitbucket pipelines build on the `develop` branch of the specified repository.
@name("Pro Dashboard")
GET "https://api.bitbucket.org/2.0/repositories/postmanlabs/postman-pro-dash/pipelines/"
basicauth("{{username}}", "{{token}}")
"Authorization": "Basic cG9zdG1hbi1hZG1pbjpIWkc4N3pMaE5MdTZ5VGcyakwzZQ=="
? "sort"= "-created_on"
? "target.ref_name"= "develop"



// A simple `GET` request to determine the status of the latest bitbucket pipelines build on the `develop` branch of the specified repository.
@name("Sync Service")
GET "https://api.bitbucket.org/2.0/repositories/postmanlabs/postman-sync-server/pipelines/"
basicauth("{{username}}", "{{token}}")
"Authorization": "Basic cG9zdG1hbi1hZG1pbjpIWkc4N3pMaE5MdTZ5VGcyakwzZQ=="
? "sort"= "-created_on"
? "target.ref_name"= "develop"



// A simple `GET` request to determine the status of the latest bitbucket pipelines build on the `develop` branch of the specified repository.
@name("User Directory Service")
GET "https://api.bitbucket.org/2.0/repositories/postmanlabs/uds/pipelines/"
basicauth("{{username}}", "{{token}}")
"Authorization": "Basic cG9zdG1hbi1hZG1pbjpIWkc4N3pMaE5MdTZ5VGcyakwzZQ=="
? "sort"= "-created_on"
? "target.ref_name"= "develop"



// A simple `POST` request to send daily build status notifications to the channel defined by the `bb-pipeline-slack-channel` environment variable (`#engineering by default`) for the develop branch on BitBucket Pipelines.
@name("Publish daily status to Slack")
POST "https://hooks.slack.com/services/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"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "payload": [
        "{{bbp-slack-body}}"
    ]
})


// A simple `POST` request to send individual failed build status notifications to repsective repository owners.
@name("Send individual failure notifications")
POST "https://hooks.slack.com/services/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"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "payload": [
        "{{bbp-slack-body-personal}}"
    ]
})


// A simple `GET` request to fetch the latest `Postman Chrome` build from the corresponding BuildKite agent.
@name("Postman Chrome")
GET "https://api.buildkite.com/v2/organizations/postman/pipelines/chrome-integration-tests/builds"
? "branch"= "develop"
? "access_token"= "{{buildkite_token}}"



// A simple `GET` request to determine the status of the latest bitbucket pipelines build on the `develop` branch of the specified repository.
@name("Domain Verification Service")
GET "https://api.bitbucket.org/2.0/repositories/postmanlabs/postman-domainverification-service/pipelines/"
basicauth("{{username}}", "{{token}}")
"Authorization": "Basic cG9zdG1hbi1hZG1pbjpIWkc4N3pMaE5MdTZ5VGcyakwzZQ=="
? "sort"= "-created_on"
? "target.ref_name"= "develop"




