#!/usr/bin/env dothttp

// Right now just a sample
@name("Get a JIRA issue")
GET "https://postmanlabs.atlassian.net/rest/api/2/issue/13321"
"Authorization": "Basic YWJoaW5hdjpnb2RlbGVzY2hlcmJhY2g="
"Content-Type": "application/json"



// Right now just a sample
@name("Get JIRA issues with the github label")
GET "https://postmanlabs.atlassian.net/rest/api/2/search"
"Authorization": "Basic YWJoaW5hdjpnb2RlbGVzY2hlcmJhY2g="
"Content-Type": "application/json"
? 'jql'= 'labels in ("github")'



// HTTP Basic authentication issue// // https://answers.atlassian.com/questions/12272394/http-basic-authentication-not-working-anymore-for-jira.atlassian.com-rest-api
@name("JIRA authentication example")
OPTIONS "http://postmanlabs.atlassian.net/rest/api/2/"



@name("Get user permissions")
GET "https://postmanlabs.atlassian.net/rest/api/2/mypermissions"
"Authorization": "Basic YWJoaW5hdjpnb2RlbGVzY2hlcmJhY2g="



@name("Metadata for issue creation")
GET "http://postmanlabs.atlassian.net/rest/api/2/issue/createmeta"
"Content-Type": "application/json"
"Authorization": "Basic YWJoaW5hdjpnb2RlbGVzY2hlcmJhY2g="




