#!/usr/bin/env dothttp

// # Display a list of employee's categories

@name("employee_category_index")
GET "https://test1.fullslate.com/api/v2/employees/categories"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"
? "name"= "emp cat 1"
? "include_deleted"= "true"


// # Show a particular employee's category

@name("employee_category_show")
GET "https://test1.fullslate.com/api/v2/employees/categories/159"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"


// # Create an employee's category

@name("employee_category_create")
POST "https://test1.fullslate.com/api/v2/employees/categories"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "name": "emp cat 2",
    "overview": "category overview",
    "details": "category detail",
    "parent_category_id": 205
})


// # Update an employee's category

@name("employee_category_update")
PATCH "https://test1.fullslate.com/api/v2/employees/categories/159"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"
json({
    "name": "category edited 999",
    "overview": "category edited overview",
    "details": "category detail edited",
    "parent_category_id": null
})


// # Delete an employee's category

@name("employee_category_delete")
DELETE "https://test1.fullslate.com/api/v2/employees/categories/200"
"Authorization": "Bearer t1bmlYSGIo33AzI1kzAmNABk3V04xiPS0ueLxnpCrW5LnjH3py"
"Content-Type": "application/json"
"Accept": "application/json"




