#!/usr/bin/env dothttp

// To get data for a single resource entity, the `GET {{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails/{{trustedEmailId}}` operation returns data for the trusted email address resource with the specified ID.
// 

@name("READ One Trusted Email Address")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails/{{trustedEmailId}}"
"Authorization": "Bearer {{jwtToken}}"


// The `GET {{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails` endpoint returns a list of all trusted email address resources associated with the specified trusted email domain resource in the specified environment.

@name("READ All Trusted Email Addresses")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails"
"Authorization": "Bearer {{jwtToken}}"


// The `POST {{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails` operation adds a new trusted email address resource entity to trusted email domain resource the specified environment.
// 
// A verification code is sent to provided email address, and the response code will be `201 Successfully created`. If the trusted email address already existed and there was an attempt to create it again, the response code will be 200.

@name("CREATE Trusted Email Address")
POST "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails"
"Content-Type": "application/json"
"Authorization": "Bearer {{jwtToken}}"
json({
    "emailAddress": "noreply1@auth.shopco.com"
})


// The `POST {{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails/{{trustedEmailId}}` operation is used to activate a new trusted email address resource of the trusted email domain in the specified environment. This operation uses the `application/vnd.pingidentity.trustedEmail.activate+json` custom media type as the content type in the request header.
// 

@name("Activate Trusted Email Address")
POST "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails/{{trustedEmailId}}"
"Content-Type": "application/vnd.pingidentity.trustedEmail.activate+json"
"Authorization": "Bearer {{jwtToken}}"
data('{  
   "verificationCode":"avu0w4lt"
}')


// The `POST {{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails/{{trustedEmailId}}` operation is used to resend a verification code to a new trusted email address resource of the trusted email domain in the specified environment. This operation uses the `application/vnd.pingidentity.trustedEmail.sendVerificationCode+json` custom media type as the content type in the request header.
// 

@name("Resend Verification Code To Email")
POST "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails/{{trustedEmailId}}"
"Content-Type": "application/vnd.pingidentity.trustedEmail.sendVerificationCode+json"
"Authorization": "Bearer {{jwtToken}}"



// The sample shows the `DELETE {{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails/{{trustedEmailId}}` operation to delete the trusted email address resource of the trusted email domain resource entity specified by its ID in the request URL.
// 
// 
// When successful, the `DELETE` request returns a code `204 Successfully deleted. No Content` message.

@name("DELETE Trusted Email Address")
DELETE "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainId}}/trustedEmails/{{trustedEmailId}}"
"Authorization": "Bearer {{jwtToken}}"



