#!/usr/bin/env dothttp

@name("")
GET "http://test.fhir.org/r4/DocumentReference"
"Accept": "application/json"
? "_content"= "{{_content}}"
? "_id"= "{{_id}}"
? "_lastUpdated"= "{{_lastUpdated}}"
? "_profile"= "{{_profile}}"
? "_query"= "{{_query}}"
? "_security"= "{{_security}}"
? "_tag"= "{{_tag}}"
? "_text"= "{{_text}}"
? "authenticator"= "{{authenticator}}"
? "author"= "{{author}}"
? "class"= "{{class}}"
? "created"= "{{created}}"
? "custodian"= "{{custodian}}"
? "description"= "{{description}}"
? "encounter"= "{{encounter}}"
? "event"= "{{event}}"
? "facility"= "{{facility}}"
? "format"= "{{format}}"
? "identifier"= "{{identifier}}"
? "indexed"= "{{indexed}}"
? "language"= "{{language}}"
? "location"= "{{location}}"
? "patient"= "{{patient}}"
? "period"= "{{period}}"
? "related-id"= "{{related-id}}"
? "related-ref"= "{{related-ref}}"
? "relatesto"= "{{relatesto}}"
? "relation"= "{{relation}}"
? "relationship"= "{{relationship}}"
? "securitylabel"= "{{securitylabel}}"
? "setting"= "{{setting}}"
? "status"= "{{status}}"
? "subject"= "{{subject}}"
? "type"= "{{type}}"
? "_sort"= "{{_sort}}"
? "_count"= "{{_count}}"
? "_summary"= "{{_summary}}"
? "_include"= "{{_include}}"
? "_reverseInclude"= "{{_reverseInclude}}"
? "_filter"= "{{_filter}}"
? "_format"= "{{_format}}"


@name("")
POST "http://test.fhir.org/r4/DocumentReference"
"Accept": "application/json"



@name("")
GET "http://test.fhir.org/r4/DocumentReference/:id"
"Accept": "application/json"


@name("")
PUT "http://test.fhir.org/r4/DocumentReference/:id"
"Accept": "application/json"



@name("")
DELETE "http://test.fhir.org/r4/DocumentReference/:id"
"Accept": "application/json"



@name("")
GET "http://test.fhir.org/r4/DocumentReference/:id/_history"
"Accept": "application/json"
? "_count"= "{{_count}}"
? "_since"= "{{_since}}"


@name("")
GET "http://test.fhir.org/r4/DocumentReference/_history"
"Accept": "application/json"
? "_count"= "{{_count}}"
? "_since"= "{{_since}}"


@name("")
GET "http://test.fhir.org/r4/DocumentReference/:id/_history/:vid"
"Accept": "application/json"



