#!/usr/bin/env dothttp

// Making sure ethe results of each security test run is stored as part of the environment for each stage.
@name("Is there output from security tests?")
GET "https://api.getpostman.com/environments"
"X-Api-Key": "{{postman_api_key}}"


// Checking to see if the API passed its security testing run, either manually or automated.
@name("Did the API pass the security tests?")
GET "https://api.getpostman.com/environments"
"X-Api-Key": "{{postman_api_key}}"



