#!/usr/bin/env dothttp

// To get the Notes associated with a Purchase Order.

@name("Notes")
GET "https://{{api-domain}}/crm/v2/Purchase_Orders/{{record_id}}/Notes"


// To get the Attachments associated with a Purchase Order.

@name("Attachments")
GET "https://{{api-domain}}/crm/v2/Purchase_Orders/{{record_id}}/Attachments"


// To get the Activities associated with a Purchase Order.

@name("Activities")
GET "https://{{api-domain}}/crm/v2/Purchase_Orders/{{record_id}}/Activities"


// To get the Closed Activities associated with a Purchase Order.

@name("Closed Activities")
GET "https://{{api-domain}}/crm/v2/Purchase_Orders/{{record_id}}/Activities_History"


// To get the Emails associated with a Purchase Order.

@name("Emails")
GET "https://{{api-domain}}/crm/v2/Purchase_Orders/{{record_id}}/Emails"



