#!/usr/bin/env dothttp

@name("Event Location Rooms Get")
GET "https://{{baseUrl}}/events/v1/eventlocationrooms/:id"
"Authorization": "<string>"


@name("Event Location Rooms Put")
PUT "https://{{baseUrl}}/events/v1/eventlocationrooms/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "event": [
        "<string>"
    ],
    "number": [
        "<integer>"
    ],
    "code": [
        "<string>"
    ],
    "resources": [
        "[{\"timeSlot\":\"<string>\",\"resource\":\"<string>\"},{\"timeSlot\":\"<string>\",\"resource\":\"<string>\"}]"
    ],
    "setupInformation": [
        "<string>"
    ],
    "capacity": [
        "<integer>"
    ],
    "notes": [
        "<string>"
    ],
    "customFieldValues": [
        "[{\"customField\":\"<string>\",\"orderLineItemID\":\"<string>\",\"stringValue\":\"<string>\",\"integerValue\":\"<long>\",\"decimalValue\":\"<double>\",\"listValues\":[\"<string>\",\"<string>\"],\"booleanValue\":\"<boolean>\",\"dateTimeValue\":\"<dateTime>\",\"referenceValue\":\"<string>\",\"listValuesForDisplay\":\"<string>\",\"listValuesForSearch\":\"<string>\"},{\"customField\":\"<string>\",\"orderLineItemID\":\"<string>\",\"stringValue\":\"<string>\",\"integerValue\":\"<long>\",\"decimalValue\":\"<double>\",\"listValues\":[\"<string>\",\"<string>\"],\"booleanValue\":\"<boolean>\",\"dateTimeValue\":\"<dateTime>\",\"referenceValue\":\"<string>\",\"listValuesForDisplay\":\"<string>\",\"listValuesForSearch\":\"<string>\"}]"
    ],
    "localID": [
        "<long>"
    ],
    "wasLocalIDGenerated": [
        "<boolean>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isConfiguration": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})



