#!/usr/bin/env dothttp

// To delete a file attached to a record.

@name("Leads")
DELETE "https://{{api-domain}}/crm/v2.1/Leads/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Contacts")
DELETE "https://{{api-domain}}/crm/v2.1/Contacts/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Accounts")
DELETE "https://{{api-domain}}/crm/v2.1/Accounts/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Deals")
DELETE "https://{{api-domain}}/crm/v2.1/Deals/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Campaigns")
DELETE "https://{{api-domain}}/crm/v2.1/Campaigns/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Tasks")
DELETE "https://{{api-domain}}/crm/v2.1/Tasks/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Cases")
DELETE "https://{{api-domain}}/crm/v2.1/Cases/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Events")
DELETE "https://{{api-domain}}/crm/v2.1/Events/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Solutions")
DELETE "https://{{api-domain}}/crm/v2.1/Solutions/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Products")
DELETE "https://{{api-domain}}/crm/v2.1/Products/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Vendors")
DELETE "https://{{api-domain}}/crm/v2.1/Vendors/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Price Books")
DELETE "https://{{api-domain}}/crm/v2.1/Price_Books/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Quotes")
DELETE "https://{{api-domain}}/crm/v2.1/Quotes/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Sales Orders")
DELETE "https://{{api-domain}}/crm/v2.1/Sales_Orders/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Purchase Orders")
DELETE "https://{{api-domain}}/crm/v2.1/Purchase_Orders/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Invoices")
DELETE "https://{{api-domain}}/crm/v2.1/Invoices/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Custom")
DELETE "https://{{api-domain}}/crm/v2.1/{{custom_module_api_name}}/{{record_id}}/Attachments/{{attachment_id}}"


// To delete a file attached to a record.

@name("Notes")
DELETE "https://{{api-domain}}/crm/v2.1/notes/{{record_id}}/Attachments/{{attachment_id}}"



