#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get GitHub Actions permissions for an enterprise")
GET "https://{{baseUrl}}/enterprises/{{enterprise}}/actions/permissions"


@name("Set GitHub Actions permissions for an enterprise")
PUT "https://{{baseUrl}}/enterprises/{{enterprise}}/actions/permissions"
"Content-Type": "application/json"
json({
    "enabled_organizations": "all",
    "allowed_actions": "selected"
})



