#!/usr/bin/env dothttp

// The `GET /environments/{environmentId}/branding` endpoint returns the branding configuration details for the specified environment resource.

@name("READ Branding")
GET "https://{{apiPath}}/environments/{{envID}}/branding"
"Authorization": "Bearer {{jwtToken}}"


// The `PUT /environments/{environmentId}/branding` endpoint returns the branding configuration details for the specified environment resource. In the request body, the 
// `backgroundColor` property value is expressed as a hex code, and the `logo` property value must be a valid URL that points to an image of a supported type.
// 

@name("UPDATE Branding")
PUT "https://{{apiPath}}/environments/{{envID}}/branding"
"Content-Type": "application/json"
"Authorization": "Bearer {{jwtToken}}"
json({
    "backgroundColor": "#0082C4",
    "logo": {
        "href": "<url-to-image>",
        "id": "{{imgID}}"
    }
})


// The `DELETE /environments/{environmentId}/branding` operation deletes the branding configuration for the specified environment resource. When the branding configuration is deleted, branding for the environment reverts back to the default.
// 
// 
// For successful delete operations, a `204 NO CONTENT` message is returned by the request.

@name("DELETE Branding")
DELETE "https://{{apiPath}}/environments/{{envID}}/branding"
"Authorization": "Bearer {{jwtToken}}"




