#!/usr/bin/env dothttp

// To get the notes associated with a Task.

@name("Notes")
GET "https://{{api-domain}}/crm/v2.1/Tasks/{{record_id}}/Notes"


// To get the attachments associated with a Task.

@name("Attachments")
GET "https://{{api-domain}}/crm/v2.1/Tasks/{{record_id}}/Attachments"



