#!/usr/bin/env dothttp

// <p>Returns a list of JDBC connections. Can optionally sort the resulting list in ascending or
//  descending order. Other params given will be used as search values.</p>
//  <p class="italicize">Examples:</p>
//  <div class="code indent"><pre>/restman/1.0/jdbcConnections?name=MyJDBCConnection</pre></div>
//  <p>Returns JDBC connection with name "MyJDBCConnection".</p>
//  <p>If a parameter is not a valid search value a bad request error will be returned.</p>
// List

@name("List All JDBC Connections")
GET "https://{{baseUrl}}/1.0/jdbcConnections"
? "sort"= "<string>"
? "order"= "<string>"
? "name"= "<array>"
? "enabled"= "<boolean>"
? "jdbcUrl"= "<array>"
? "driverClass"= "<array>"
? "username"= "<array>"
? "securityZone.id"= "<array>"


// Returns a JDBC connection with the given ID.
// Get

@name("List JDBC Connections By ID")
GET "https://{{baseUrl}}/1.0/jdbcConnections/:id"


// Returns a template, which is an example JDBC connection that can be used as a reference for what JDBC connection
//  objects should look like.
// Template

@name("JDBC Connections Template")
GET "https://{{baseUrl}}/1.0/jdbcConnections/template"



