#!/usr/bin/env dothttp

// Retrieve your own user profile.
// 
// Responses
// =========
// - **200 OK on success**
// - 401 Unathorized

@name("Get my information")
GET "https://{{cloudcraft_url}}/user/me"



