#!/usr/bin/env dothttp

@name("Login Ip")
GET "https://{{host}}/services/data/v47.0/sobjects/LoginIp/"


@name("Login Ip Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/LoginIp/{ID}/"


@name("Describe Login Ip")
GET "https://{{host}}/services/data/v47.0/sobjects/LoginIp/describe/"



