#!/usr/bin/env dothttp

// List all available content filtering categories for an MX network
@name("getNetworkContentFilteringCategories")
GET "https://{{baseUrl}}/networks/:networkId/contentFiltering/categories"
"Accept": "*/*"




