#!/usr/bin/env dothttp

// Get the uplink loss percentage and latency in milliseconds, and goodput in kilobits per second for a wired network device.
@name("Get the uplink loss percentage and latency in milliseconds, and goodput in kilobits per second for a wired network device.")
GET "https://{{baseUrl}}/devices/:serial/lossAndLatencyHistory"
"X-Cisco-Meraki-API-Key": ""
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "resolution"= "{{resolution}}"
? "uplink"= "{{uplink}}"
? "ip"= "{{ip}}"



