#!/usr/bin/env dothttp

// Paginate over a list of unsubscribes for a domain.
@name("Get domain unsubscribes")
GET "https://{{BASE_URL}}/{{mydomain}}/unsubscribes"
"Authorization": "Basic {{token}}"


// Paginate over a list of unsubscribes for a domain.
@name("Get single unsubscribe")
GET "https://{{BASE_URL}}/{{mydomain}}/unsubscribes/{{address}}"
"Authorization": "Basic {{token}}"


// Paginate over a list of unsubscribes for a domain.
@name("Add single unsubscribe")
POST "https://{{BASE_URL}}/{{mydomain}}/unsubscribes"
"Authorization": "Basic {{token}}"
files(
	("address", ""),
	("tag", ""),
	("created_at", "")
)


// Add multiple unsubscribe records to the unsubscribe list in a single API call.
@name("Add multiple unsubscribes")
POST "https://{{BASE_URL}}/{{mydomain}}/unsubscribes"
"Content-Type": "application/json"
"Authorization": "Basic {{token}}"
data('[
  {
    "address": "alice@example.com",
    "tags": ["some tag"],
    "created_at": "Thu, 13 Oct 2011 18:02:00 UTC"
  },
  {
    "address": "bob@example.com",
    "tags": ["*"]
  },
  {
    "address": "carol@example.com"
  }
]')


// Add multiple unsubscribe records to the unsubscribe list in a single API call.
@name("Delete single unsubscribe")
DELETE "https://{{BASE_URL}}/{{mydomain}}/unsubscribes/{{address}}"
"Authorization": "Basic {{token}}"



