#!/usr/bin/env dothttp

@name("Event Navigation")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/event_navigations"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "01c31217-2229-4db2-af56-143ef51c0e91"


@name("Event Navigation By Id")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/event_navigations/6"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "bd4d193b-5f0b-469e-962b-be2d4b1f661e"



