#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Project Issue Security Scheme")
GET "https://{{baseUrl}}/rest/api/3/project/:projectKeyOrId/issuesecuritylevelscheme"


@name("Get Project Notification Scheme")
GET "https://{{baseUrl}}/rest/api/3/project/:projectKeyOrId/notificationscheme"
? "expand"= "<string>"


@name("Get Project Issue Security Levels")
GET "https://{{baseUrl}}/rest/api/3/project/:projectKeyOrId/securitylevel"



