#!/usr/bin/env dothttp

@name("Today")
GET "http://calapi.inadiutorium.cz/api/v0/en/calendars/general-en/today"



@name("Tomorrow")
GET "http://calapi.inadiutorium.cz/api/v0/en/calendars/general-en/tomorrow"



@name("Yesterday")
GET "http://calapi.inadiutorium.cz/api/v0/en/calendars/general-en/yesterday"




