#!/usr/bin/env dothttp

@name("Returns a list of unitsOfMeasure")
GET "https://{{baseUrl}}/companies({{company_id}})/unitsOfMeasure"
? "$top"= "<integer>"
? "$skip"= "<integer>"
? "$limit"= "<integer>"
? "$filter"= "<string>"
? "$select"= "<string>,<string>"


@name("Creates an object of type unitOfMeasure in Dynamics 365 Business Central")
POST "https://{{baseUrl}}/companies({{company_id}})/unitsOfMeasure"
"Content-Type": "<string>"
"Content-Type": "application/json"
data('{
    "id": "<uuid>",
    "code": "<string>",
    "displayName": "<string>",
    "internationalStandardCode": "<string>",
    "lastModifiedDateTime": "<dateTime>"
}')



