#!/usr/bin/env dothttp

@name("Get area by token")
GET "https://{{baseUrl}}/areas/:areaToken"
"Authorization": ""
? "includeAreaType"= "true"
? "includeParentArea"= "true"


@name("Update existing area")
PUT "https://{{baseUrl}}/areas/:areaToken"
"Authorization": ""
"Content-Type": "application/json"
json({
    "areaTypeToken": "<string>",
    "backgroundColor": "<string>",
    "borderColor": "<string>",
    "bounds": [
        {
            "elevation": "<double>",
            "latitude": "<double>",
            "longitude": "<double>"
        },
        {
            "elevation": "<double>",
            "latitude": "<double>",
            "longitude": "<double>"
        }
    ],
    "description": "<string>",
    "foregroundColor": "<string>",
    "icon": "<string>",
    "imageUrl": "<string>",
    "metadata": "<object>",
    "name": "<string>",
    "parentToken": "<string>",
    "token": "<string>"
})


@name("Delete area by token")
DELETE "https://{{baseUrl}}/areas/:areaToken"
"Authorization": ""


@name("List alerts for an area")
GET "https://{{baseUrl}}/areas/:areaToken/alerts"
"Authorization": ""
? "endDate"= "<string>"
? "page"= "1"
? "pageSize"= "100"
? "startDate"= "<string>"


@name("List device assignments for an area")
GET "https://{{baseUrl}}/areas/:areaToken/assignments"
"Authorization": ""
? "includeArea"= "false"
? "includeAsset"= "false"
? "includeCustomer"= "false"
? "includeDevice"= "false"
? "page"= "1"
? "pageSize"= "100"
? "status"= "<string>"


@name("List command invocations for an area")
GET "https://{{baseUrl}}/areas/:areaToken/invocations"
"Authorization": ""
? "endDate"= "<string>"
? "page"= "1"
? "pageSize"= "100"
? "startDate"= "<string>"


@name("Get label for area")
GET "https://{{baseUrl}}/areas/:areaToken/label/:generatorId"
"Authorization": ""


@name("List locations for an area")
GET "https://{{baseUrl}}/areas/:areaToken/locations"
"Authorization": ""
? "endDate"= "<string>"
? "page"= "1"
? "pageSize"= "100"
? "startDate"= "<string>"


@name("List measurements for an area")
GET "https://{{baseUrl}}/areas/:areaToken/measurements"
"Authorization": ""
? "endDate"= "<string>"
? "page"= "1"
? "pageSize"= "100"
? "startDate"= "<string>"


@name("List command responses for an area")
GET "https://{{baseUrl}}/areas/:areaToken/responses"
"Authorization": ""
? "endDate"= "<string>"
? "page"= "1"
? "pageSize"= "100"
? "startDate"= "<string>"


@name("List state changes associated with an area")
GET "https://{{baseUrl}}/areas/:areaToken/statechanges"
"Authorization": ""
? "endDate"= "<string>"
? "page"= "1"
? "pageSize"= "100"
? "startDate"= "<string>"



