#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get an artifact")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo/actions/artifacts/:artifact_id}}/"


@name("Delete an artifact")
DELETE "https://{{baseUrl}}/repos/{{owner}}/{{repo/actions/artifacts/:artifact_id}}/"


@name("Download an artifact")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo/actions/artifacts/{{artifact_id}}/:archive_format}}/"



