#!/usr/bin/env dothttp

// A `GET` to the /estimates/price endpoint allows your application to estimate the price of a trip for a given origin and destination.

@name("Estimate price")
GET "https://api.trippy.com/v1/estimates/price"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"



// A `GET` to the /estimates/time endpoint allows your application to estimate the time for a trip for a given origin and destination.

@name("Estimate time")
GET "https://api.trippy.com/v1/estimates/time"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"




