#!/usr/bin/env dothttp

// Checks to make sure all schema have properties.

@name("Do all schema have properties?")
GET "https://api.getpostman.com/apis/:api_id/versions/:version_id/schemas/:schema_id"


// Checks to see if all schema properties have descriptions.

@name("Do all schema properties have descriptions?")
GET "https://api.getpostman.com/apis/:api_id/versions/:version_id/schemas/:schema_id"



