#!/usr/bin/env dothttp

@name("Multi Read")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/attendance/audit_records/multi_read"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "326a9c6d-64fc-4053-9410-ca12234eea08"
json({
    "dateRange": {
        "endDate": "2020-01-07",
        "startDate": "2020-01-06",
        "symbolicPeriod": {
            "id": 1,
            "qualifier": "QUALIFIER"
        }
    },
    "employees": {
        "ids": [
            1
        ],
        "qualifiers": [
            ""
        ],
        "refs": [
            {
                "id": 1,
                "qualifier": "QUALIFIER"
            }
        ]
    }
})


// https://cust01-npr03-api-cms01.npr.mykronos.com/default-model/version/1-0/apis/get/v1/attendance/actions/%7Bid%7D/documents

@name("Retrieve Actions' Documents By Id")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/attendance/actions/3784/documents"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "326a9c6d-64fc-4053-9410-ca12234eea08"
? "is_manager_role"= "1"



// https://cust01-npr03-api-cms01.npr.mykronos.com/default-model/version/1-0/apis/post/v1/attendance/actions/documents/multi_read

@name("Retrieve Actions' Documents")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/attendance/actions/documents/multi_read"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "326a9c6d-64fc-4053-9410-ca12234eea08"
json({
    "dateRange": {
        "endDate": "2020-01-07",
        "startDate": "2020-01-06",
        "symbolicPeriod": {
            "id": 1,
            "qualifier": "QUALIFIER"
        }
    },
    "employees": {
        "ids": [
            1
        ],
        "qualifiers": [
            ""
        ],
        "refs": [
            {
                "id": 1,
                "qualifier": "QUALIFIER"
            }
        ]
    },
    "isManagerRole": false
})


// https://cust01-npr03-api-cms01.npr.mykronos.com/default-model/version/1-0/apis/post/v1/attendance/actions/multi_read

@name("Retrieve Multiple Actions")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/attendance/actions/multi_read"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "326a9c6d-64fc-4053-9410-ca12234eea08"
json({
    "dateRange": {
        "endDate": "2020-01-07",
        "startDate": "2020-01-06",
        "symbolicPeriod": {
            "id": 1,
            "qualifier": "QUALIFIER"
        }
    },
    "employees": {
        "ids": [
            1
        ],
        "qualifiers": [
            ""
        ],
        "refs": [
            {
                "id": 1,
                "qualifier": "QUALIFIER"
            }
        ]
    },
    "isManagerRole": false,
    "requiredOnly": false
})


// https://cust01-npr03-api-cms01.npr.mykronos.com/default-model/version/1-0/apis/get/v1/attendance/actions/%7Bid%7D

@name("Retrieve Action by ID")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/attendance/actions/5"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "d9e14ffa-7aa0-45ca-99a7-2a69bc36b9cc"



