#!/usr/bin/env dothttp

@name("Mail Merge Templates Post")
POST "https://{{baseUrl}}/platform/v2/mailmergetemplates"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "searchType": [
        "<string>"
    ],
    "description": [
        "<string>"
    ],
    "template": [
        "<string>"
    ],
    "hiddenInTemplates": [
        "<boolean>"
    ],
    "isConfiguration": [
        "<boolean>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})


@name("Mail Merge Templates Get")
GET "https://{{baseUrl}}/platform/v2/mailmergetemplates/:tenantid"
"Authorization": "<string>"
? "msql"= "<string>"
? "page"= "<integer>"
? "pageSize"= "<integer>"


@name("Mail Merge Templates Get")
GET "https://{{baseUrl}}/platform/v2/mailmergetemplates/description/:tenantid"
"Authorization": "<string>"


@name("Mail Merge Templates Delete")
DELETE "https://{{baseUrl}}/platform/v2/mailmergetemplates/delete/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"



