#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get User")
GET "https://{{baseUrl}}/rest/api/3/user"
? "accountId"= "<string>"
? "username"= "<string>"
? "key"= "<string>"
? "expand"= "<string>"


@name("Create User")
POST "{{baseUrl}}/rest/api/3/user"
"Content-Type": "application/json"
data('{
    "displayName": "<string>",
    "emailAddress": "<string>",
    "key": "<string>",
    "name": "<string>",
    "password": "<string>",
    "notification": "<string>",
    "applicationKeys": [
        "<string>",
        "<string>"
    ]
}')


@name("Delete User")
DELETE "https://{{baseUrl}}/rest/api/3/user"
? "accountId"= "<string>"
? "username"= "<string>"
? "key"= "<string>"


@name("Get User Groups")
GET "https://{{baseUrl}}/rest/api/3/user/groups"
? "accountId"= "<string>"
? "username"= "<string>"
? "key"= "<string>"


@name("Find Users With Permissions")
GET "https://{{baseUrl}}/rest/api/3/user/permission/search"
? "query"= "<string>"
? "username"= "<string>"
? "accountId"= "<string>"
? "permissions"= "<string>"
? "issueKey"= "<string>"
? "projectKey"= "<string>"
? "startAt"= "0"
? "maxResults"= "50"


@name("Find Users For Picker")
GET "https://{{baseUrl}}/rest/api/3/user/picker"
? "query"= "<string>"
? "maxResults"= "50"
? "showAvatar"= "false"
? "exclude"= "<string>"
? "exclude"= "<string>"
? "excludeAccountIds"= "<string>"
? "excludeAccountIds"= "<string>"
? "avatarSize"= "<string>"
? "excludeConnectUsers"= "false"


@name("Find Users With Browse Permission")
GET "https://{{baseUrl}}/rest/api/3/user/viewissue/search"
? "query"= "<string>"
? "username"= "<string>"
? "accountId"= "<string>"
? "issueKey"= "<string>"
? "projectKey"= "<string>"
? "startAt"= "0"
? "maxResults"= "50"



