#!/usr/bin/env dothttp

@name("Uri Event")
GET "https://{{host}}/services/data/v47.0/sobjects/UriEvent/"


@name("Uri Event Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/UriEvent/{ID}/"


@name("Describe Uri Event")
GET "https://{{host}}/services/data/v47.0/sobjects/UriEvent/describe/"



