#!/usr/bin/env dothttp

@name("Generate a token")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/authentication/access_token"
"Content-Type": "application/x-www-form-urlencoded"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
data({
    "username": [
        "RIGHTPUNCH"
    ],
    "password": [
        "Pass1234!"
    ],
    "client_id": [
        "46S4xwWKhZIaBrn249sEk7pYAQC92VD6"
    ],
    "client_secret": [
        "Zg1YjO1KIMBUI9cv"
    ],
    "grant_type": [
        "password"
    ],
    "auth_chain": [
        "OAuthLdapService"
    ]
})


@name("Refresh Token")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/authentication/access_token"
"Content-Type": "application/x-www-form-urlencoded"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
data({
    "refresh_token": [
        "ed0a455f-3248-4784-985b-0336b15da399"
    ],
    "client_id": [
        "46S4xwWKhZIaBrn249sEk7pYAQC92VD6"
    ],
    "client_secret": [
        "Zg1YjO1KIMBUI9cv"
    ],
    "grant_type": [
        "refresh_token"
    ],
    "auth_chain": [
        "OAuthLdapService"
    ]
})


@name("Call an API resource")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/persons/3110"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "8005f729-4063-455d-b9be-c39928e4b4b4"



@name("Call an API resource Copy")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/persons/3784"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "68d8c8d9-0008-4f5a-802e-c01b3625902b"



@name("Retrieve Aggregated Data (Employee List)")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/data/multi_read"
"Content-Type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "d2432ee0-6557-4066-8c3c-c62a0fdb1a65"
json({
    "select": [
        {
            "key": "EMP_COMMON_FULL_NAME"
        },
        {
            "key": "EMP_COMMON_PRIMARY_JOB"
        },
        {
            "key": "EMP_COMMON_PRIMARY_ORG"
        },
        {
            "key": "PEOPLE_HIRE_DATE"
        }
    ],
    "from": {
        "view": "EMP",
        "employeeSet": {
            "hyperfind": {
                "id": 3784
            },
            "dateRange": {
                "symbolicPeriod": {
                    "qualifier": "Current_Payperiod"
                }
            }
        }
    },
    "options": {
        "requestTag": "myCache"
    },
    "index": 0,
    "count": 500
})


@name("Retrieve Aggregated Data (Employee List) Copy")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/persons/base_persons/multi_read"
"Content-Type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "d2432ee0-6557-4066-8c3c-c62a0fdb1a65"
json({
    "where": {
        "extensionType": "employeeExtension",
        "hyperFindFilter": {
            "dateRange": {
                "dateRange": "DATERANGE",
                "endDate": "2020-01-26",
                "startDate": "2016-09-26",
                "symbolicPeriod": {
                    "id": 1,
                    "qualifier": "QUALIFIER"
                }
            },
            "hyperfind": {
                "id": 1,
                "qualifier": "QUALIFIER"
            },
            "visibilityCode": "VISIBILITYCODE"
        },
        "isEmployeeAllowed": false,
        "onlyActivePerson": false
    }
})


@name("https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/hyperfind/execute")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/hyperfind/execute"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "68d8c8d9-0008-4f5a-802e-c01b3625902b"
json({
    "dateRange": {
        "symbolicPeriod": {
            "id": 1
        }
    },
    "hyperfind": {
        "qualifier": "All Home"
    }
})


@name("1_batch")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/hyperfind/execute"
"Content-Type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "bf432bc6-3c8b-4a9e-9db8-47a2fd12961c"
json({
    "dateRange": {
        "symbolicPeriod": {
            "id": 1
        }
    },
    "hyperfind": {
        "qualifier": "All Home"
    }
})


@name("https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/persons/3784")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/persons/3784"
"Content-Type": "application/x-www-form-urlencoded"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "06039298-2e0a-48de-980d-868d4d540b41"



