#!/usr/bin/env dothttp

@name("Allows you to retrieve Attachment on invoices or purchase bills by it's filename")
GET "https://{{baseUrl}}/Invoices/:InvoiceID/Attachments/:FileName"
"contentType": "<string>"
"xero-tenant-id": "<string>"


@name("Allows you to update Attachment on invoices or purchase bills by it's filename")
POST "https://{{baseUrl}}/Invoices/:InvoiceID/Attachments/:FileName"
"xero-tenant-id": "<string>"
"Content-Type": "application/octet-stream"
data('"<byte>"')


@name("Allows you to create an Attachment on invoices or purchase bills by it's filename")
PUT "https://{{baseUrl}}/Invoices/:InvoiceID/Attachments/:FileName"
"xero-tenant-id": "<string>"
"Content-Type": "application/octet-stream"
? "IncludeOnline"= "false"
data('"<byte>"')



