#!/usr/bin/env dothttp

@name("Retrieve ACL match counters from device")
GET "https://{{vmanage}}/dataservice/device/acl/matchcounter"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"



