#!/usr/bin/env dothttp

// Show current user’s account. To access user’s primary account, primary keyword can be used instead of the account id in the URL.
@name("Show an account")
GET "https://{{baseUrl}}/accounts/:account_id"


// Promote an account as primary account.
@name("Set account as primary")
GET "https://{{baseUrl}}/accounts/:account_id/primary"



