#!/usr/bin/env dothttp

@name("Returns a list of countriesRegions")
GET "https://{{baseUrl}}/companies({{company_id}})/countriesRegions"
? "$top"= "<integer>"
? "$skip"= "<integer>"
? "$limit"= "<integer>"
? "$filter"= "<string>"
? "$select"= "<string>,<string>"


@name("Creates an object of type countryRegion in Dynamics 365 Business Central")
POST "https://{{baseUrl}}/companies({{company_id}})/countriesRegions"
"Content-Type": "<string>"
"Content-Type": "application/json"
json({
    "id": "<uuid>",
    "code": "<string>",
    "displayName": "<string>",
    "addressFormat": "<string>",
    "lastModifiedDateTime": "<dateTime>"
})



