#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Votes")
GET "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/votes"


@name("Add Vote")
POST "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/votes"


@name("Delete Vote")
DELETE "None://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/votes"



