#!/usr/bin/env dothttp

@name("Get All File Systems")
GET "https://{{host_url}}/api/{{api_version}}/file-systems"


@name("Get All File System Snapshots")
GET "https://{{host_url}}/api/{{api_version}}/file-system-snapshots"



