#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Group")
GET "None://{{baseUrl}}/rest/api/3/group"
? "groupname"= "<string>"
? "expand"= "<string>"


@name("Create Group")
POST "{{baseUrl}}/rest/api/3/group"
"Content-Type": "application/json"
data('{
    "name": "<string>"
}')


@name("Remove Group")
DELETE "None://{{baseUrl}}/rest/api/3/group"
? "groupname"= "<string>"
? "swapGroup"= "<string>"


@name("Bulk Get Groups")
GET "None://{{baseUrl}}/rest/api/3/group/bulk"
? "startAt"= "0"
? "maxResults"= "50"
? "groupId"= "<string>"
? "groupName"= "<string>"


@name("Get Users From Group")
GET "None://{{baseUrl}}/rest/api/3/group/member"
? "groupname"= "<string>"
? "includeInactiveUsers"= "false"
? "startAt"= "0"
? "maxResults"= "50"



