#!/usr/bin/env dothttp

// Enables an authenticated GitHub App to find an installation's information using the installation id. The installation's account type (`target_type`) will be either an organization or a user account, depending which account the repository belongs to.
// 
// You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.

@name("Get an installation for the authenticated app")
GET "https://{{baseUrl}}/app/installations/:installation_id"


// Uninstalls a GitHub App on a user, organization, or business account. If you prefer to temporarily suspend an app's access to your account's resources, then we recommend the "[Suspend an app installation](https://docs.github.com/v3/apps/#suspend-an-app-installation)" endpoint.
// 
// You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.

@name("Delete an installation for the authenticated app")
DELETE "https://{{baseUrl}}/app/installations/:installation_id"


// Creates an installation access token that enables a GitHub App to make authenticated API requests for the app's installation on an organization or individual account. Installation tokens expire one hour from the time you create them. Using an expired token produces a status code of `401 - Unauthorized`, and requires creating a new installation token. By default the installation token has access to all repositories that the installation can access. To restrict the access to specific repositories, you can provide the `repository_ids` when creating the token. When you omit `repository_ids`, the response does not contain the `repositories` key.
// 
// You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.

@name("Create an installation access token for an app")
POST "https://{{baseUrl}}/app/installations/:installation_id/access_tokens"
"Content-Type": "application/json"
data('{
    "repositories": [
        "<string>",
        "<string>"
    ],
    "repository_ids": [
        "<integer>",
        "<integer>"
    ],
    "permissions": {
        "actions": "<string>",
        "administration": "<string>",
        "checks": "<string>",
        "content_references": "<string>",
        "contents": "<string>",
        "deployments": "<string>",
        "environments": "<string>",
        "issues": "<string>",
        "metadata": "<string>",
        "packages": "<string>",
        "pages": "<string>",
        "pull_requests": "<string>",
        "repository_hooks": "<string>",
        "repository_projects": "<string>",
        "secret_scanning_alerts": "<string>",
        "secrets": "<string>",
        "security_events": "<string>",
        "single_file": "<string>",
        "statuses": "<string>",
        "vulnerability_alerts": "<string>",
        "workflows": "<string>",
        "members": "<string>",
        "organization_administration": "<string>",
        "organization_hooks": "<string>",
        "organization_plan": "<string>",
        "organization_projects": "<string>",
        "organization_secrets": "<string>",
        "organization_self_hosted_runners": "<string>",
        "organization_user_blocking": "<string>",
        "team_discussions": "<string>"
    }
}')



