#!/usr/bin/env dothttp

// Retrieve all webhooks for the specified videoask.

@name("Retrieve webhooks")
GET "https://{{base_url}}/forms/{{form_id}}/webhooks"
"Authorization": "Bearer {{token}}"


// Retrieve a single webhook.

@name("Retrieve single webhook")
GET "https://{{base_url}}/forms/{{form_id}}/webhooks/{{tag}}"
"Authorization": "Bearer {{token}}"


// Create or update webhook.

@name("Create or update webhook")
PUT "https://{{base_url}}/forms/{{form_id}}/webhooks/{{tag}}"
"Authorization": "Bearer {{token}}"
"Content-Type": "application/json"
json({
    "url": "<url>",
    "event_types": [
        "form_response",
        "form_response_transcribed"
    ]
})


// Delete a webhook.

@name("Delete webhook")
DELETE "https://{{base_url}}/forms/{{form_id}}/webhooks/{{tag}}"
"Authorization": "Bearer {{token}}"



