#!/usr/bin/env dothttp

// Get all available `VehicleBodies` for the given **marketId**. Optional query params **classId** **bodyId** or **productGroups** may be used to filter the result and must conform to the pattern [0-9A-Z_-]+.

@name("Get all available bodies for the given marketId.")
GET "https://{{baseUrl}}/markets/:marketId/bodies"
? "classId"= "S-KLASSE"
? "bodyId"= "LIMOUSINE_LANG"
? "productGroups"= "VAN"
? "productGroups"= "SPRINTER"
? "fieldsFilter"= "nulla sed"
? "fieldsFilter"= "nulla ex qui"


// Get the `VehicleBody` for the given **marketId** and **bodyId**.

@name("Get the body for the given marketId and bodyId.")
GET "https://{{baseUrl}}/markets/:marketId/bodies/:bodyId"
? "fieldsFilter"= "nulla sed"
? "fieldsFilter"= "nulla ex qui"



