#!/usr/bin/env dothttp

@name("Update an existing pet")
PUT "https://petstore.swagger.io/v2/pet"
"Accept": "application/xml, application/json"
"Content-Type": "application/json"
data('Pet object that needs to be added to the store')


@name("Add a new pet to the store")
POST "https://petstore.swagger.io/v2/pet"
"Accept": "application/xml, application/json"
"Content-Type": "application/json"
data('Pet object that needs to be added to the store')


// Multiple status values can be provided with comma separated strings

@name("Finds Pets by status")
GET "https://petstore.swagger.io/v2/pet/findByStatus"
"Accept": "application/xml, application/json"
? "status"= "{{status}}"


// Muliple tags can be provided with comma separated strings. Use         tag1, tag2, tag3 for testing.

@name("Finds Pets by tags")
GET "https://petstore.swagger.io/v2/pet/findByTags"
"Accept": "application/xml, application/json"
? "tags"= "{{tags}}"


// Returns a single pet

@name("Find pet by ID")
GET "https://petstore.swagger.io/v2/pet/:petId"
"Accept": "application/xml, application/json"


@name("Updates a pet in the store with form data")
POST "https://petstore.swagger.io/v2/pet/:petId"
"Accept": "application/xml, application/json"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "name": [
        "{{name}}"
    ],
    "status": [
        "{{status}}"
    ]
})


@name("Deletes a pet")
DELETE "https://petstore.swagger.io/v2/pet/:petId"
"Accept": "application/xml, application/json"
"api_key": "{{api_key}}"



@name("uploads an image")
POST "https://petstore.swagger.io/v2/pet/:petId/uploadImage"
"Accept": "application/json"
"Content-Type": "multipart/form-data"
files(
	("additionalMetadata", "{{additionalMetadata}}"),
	("file", "{{file}}")
)



