#!/usr/bin/env dothttp

@name("{{baseUrl}}/LDAPDirectoryService/AddLDAPDirectoryServiceConfig")
POST "https://{{baseUrl}}/LDAPDirectoryService/AddLDAPDirectoryServiceConfig"
"Content-Type": "application/json"
json({
    "UniqueIdentifier": "<string>",
    "UsePagedSearch": "<boolean>",
    "UseBrokenShadowExpire": "<boolean>",
    "PropertyToAttributeMap": "<object>",
    "ServerType": "<string>",
    "ScriptingPropertyToAttributeMap": "<object>"
})


@name("{{baseUrl}}/LDAPDirectoryService/DeleteLDAPDirectoryServiceConfig")
POST "https://{{baseUrl}}/LDAPDirectoryService/DeleteLDAPDirectoryServiceConfig"
"Content-Type": "application/json"
json({
    "DirectoryServiceUuid": "<string>"
})


@name("{{baseUrl}}/LDAPDirectoryService/GetCloudConnectors")
POST "https://{{baseUrl}}/LDAPDirectoryService/GetCloudConnectors"
"Content-Type": "application/json"
json({
    "DirectoryServiceUuid": "<string>"
})


@name("{{baseUrl}}/LDAPDirectoryService/GetDirectoryServiceVersion")
POST "https://{{baseUrl}}/LDAPDirectoryService/GetDirectoryServiceVersion"
"Content-Type": "application/json"
json({
    "directoryServiceUuid": "<string>"
})


@name("{{baseUrl}}/LDAPDirectoryService/GetLDAPDirectoryServiceConfig")
POST "https://{{baseUrl}}/LDAPDirectoryService/GetLDAPDirectoryServiceConfig"
"Content-Type": "application/json"
json({
    "DirectoryServiceUuid": "<string>"
})


@name("{{baseUrl}}/LDAPDirectoryService/GetLDAPDirectoryServiceUuidByName")
POST "https://{{baseUrl}}/LDAPDirectoryService/GetLDAPDirectoryServiceUuidByName"
"Content-Type": "application/json"
json({
    "DirectoryServiceName": "<string>"
})


// This is intended for UI use, to fill in the prompts for the names of the attributes in the
//              customer's mappings.

@name("{{baseUrl}}/LDAPDirectoryService/GetMappableAttributeList")
POST "https://{{baseUrl}}/LDAPDirectoryService/GetMappableAttributeList"
"Content-Type": "application/json"
json({
    "operation": "<string>"
})


@name("{{baseUrl}}/LDAPDirectoryService/GetPropertyToAttributeMappings")
POST "https://{{baseUrl}}/LDAPDirectoryService/GetPropertyToAttributeMappings"
"Content-Type": "application/json"
json({
    "directoryServiceUuid": "<string>"
})


@name("{{baseUrl}}/LDAPDirectoryService/GetScriptingPropertyToAttributeMappings")
POST "https://{{baseUrl}}/LDAPDirectoryService/GetScriptingPropertyToAttributeMappings"
"Content-Type": "application/json"
json({
    "directoryServiceUuid": "<string>"
})


@name("{{baseUrl}}/LDAPDirectoryService/ModifyLDAPDirectoryServiceConfig")
POST "https://{{baseUrl}}/LDAPDirectoryService/ModifyLDAPDirectoryServiceConfig"
"Content-Type": "application/json"
json({
    "UniqueIdentifier": "<string>",
    "UsePagedSearch": "<boolean>",
    "UseBrokenShadowExpire": "<boolean>",
    "PropertyToAttributeMap": "<object>",
    "ServerType": "<string>",
    "ScriptingPropertyToAttributeMap": "<object>"
})


@name("{{baseUrl}}/LDAPDirectoryService/SetPropertyToAttributeMappings")
POST "https://{{baseUrl}}/LDAPDirectoryService/SetPropertyToAttributeMappings"
"Content-Type": "application/json"
json({
    "directoryServiceUuid": "<string>",
    "propertyToAttributeMappings": "<object>"
})


@name("{{baseUrl}}/LDAPDirectoryService/SetScriptingPropertyToAttributeMappings")
POST "https://{{baseUrl}}/LDAPDirectoryService/SetScriptingPropertyToAttributeMappings"
"Content-Type": "application/json"
json({
    "scriptingPropertyToAttributeMappings": "<object>",
    "directoryServiceUuid": "<string>"
})


// Using a supplied LDAP configuration OR a the UUID of an existing LDAP directory service (one or the
//              other is required), this API will attempt to look up a user (specified by login
//              name) and apply the mappings from the configuration.  This is intended for UI use to enable the
//              customer to validate their mappings prior to saving the server configuration.

@name("{{baseUrl}}/LDAPDirectoryService/TestUserLookup")
POST "https://{{baseUrl}}/LDAPDirectoryService/TestUserLookup"
"Content-Type": "application/json"
json({
    "Version": "<integer>",
    "TestUserName": "<string>",
    "DirectoryServiceUuid": "<string>",
    "Settings": "<string>"
})


@name("{{baseUrl}}/LDAPDirectoryService/VerifyLDAPDirectoryServiceConfig")
POST "https://{{baseUrl}}/LDAPDirectoryService/VerifyLDAPDirectoryServiceConfig"
"Content-Type": "application/json"
json({
    "UniqueIdentifier": "<string>",
    "UsePagedSearch": "<boolean>",
    "UseBrokenShadowExpire": "<boolean>",
    "PropertyToAttributeMap": "<object>",
    "ServerType": "<string>",
    "ScriptingPropertyToAttributeMap": "<object>"
})



