#!/usr/bin/env dothttp

@name("List command invocation events for assignment")
GET "https://{{baseUrl}}/assignments/:token/invocations"
"Authorization": ""
? "endDate"= "<string>"
? "includeCommand"= "true"
? "page"= "1"
? "pageSize"= "100"
? "startDate"= "<string>"


@name("Create command invocation event for assignment")
POST "https://{{baseUrl}}/assignments/:token/invocations"
"Authorization": ""
"Content-Type": "application/json"
json({
    "alternateId": "<string>",
    "commandToken": "<string>",
    "eventDate": "<dateTime>",
    "eventType": "<string>",
    "initiator": "<string>",
    "initiatorId": "<string>",
    "metadata": "<object>",
    "parameterValues": "<object>",
    "target": "<string>",
    "targetId": "<string>",
    "updateState": "<boolean>"
})


@name("Schedule command invocation")
POST "https://{{baseUrl}}/assignments/:token/invocations/schedules/:scheduleToken"
"Authorization": ""
"Content-Type": "application/json"
json({
    "alternateId": "<string>",
    "commandToken": "<string>",
    "eventDate": "<dateTime>",
    "eventType": "<string>",
    "initiator": "<string>",
    "initiatorId": "<string>",
    "metadata": "<object>",
    "parameterValues": "<object>",
    "target": "<string>",
    "targetId": "<string>",
    "updateState": "<boolean>"
})



