#!/usr/bin/env dothttp

// The sample shows the `GET /organizations/{organizationId}/capabilities` operation to return the organization's current capabilities.

@name("READ Organization Capabilities")
GET "https://{{apiPath}}/organizations/{{orgID}}/capabilities"
"Authorization": "Bearer {{jwtToken}}"


// The sample shows the `GET /environments/{environmentId}/capabilities` operation to return the specified environment's current capabilities.

@name("READ Environment Capabilities")
GET "https://{{apiPath}}/environments/{{envID}}/capabilities"
"Authorization": "Bearer {{jwtToken}}"



