#!/usr/bin/env dothttp

// Gets a single Team by its ZUID

@name("Get Team")
GET "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams/{{team_zuid}}"


// Gets a single team

@name("Create Team")
POST "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams"
"Content-Type": "application/json"
data('{
  "Name": "Example Team Name"
}')


// Updates a team with the given values.

@name("Update Team")
PUT "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams/{{team_zuid}}"
"Content-Type": "application/json"
data('{
    "name": "Defenders"
}')


// Delete a single team

@name("Delete Team")
DELETE "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams/{{team_zuid}}"
"Content-Type": "application/json"


// Gets a all teams associated with the user

@name("Get All Teams")
GET "{{protocol}}://{{accounts_api_url}}/{{accounts_api_version}}/teams"



