#!/usr/bin/env dothttp

// The default value of the reason is "*Signed by Yousign*" but can therefore be overridden by the value of your choice. 
// 
// This functionality is mainly implemented with the use of the [Server stamp](https://dev.yousign.com/#7e50aa62-9e08-4017-b44a-cbd971bd5d4b).

@name("/file_objects")
POST "https://{{base-api-url}}/file_objects"
"Authorization": "Bearer {{your-api-key}}"
"Content-Type": "application/json"
json({
    "file": "/files/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "member": "/members/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "position": "230,499,464,589",
    "page": 2,
    "mention": "Read and approved",
    "mention2": "Signed by John Doe",
    "reason": "Signed by John Doe (Yousign)"
})



