#!/usr/bin/env dothttp

// Retrieve all sections from a specific Space.

@name("List sections")
GET "https://{{KNOWLEDGE_BASE_URL}}/workspace/v2/spaces/{{SPACE_ID}}/sections"
"Content-Type": "application/json"
"Authorization": "{{TOKEN}}"
"Skore-Request-Metadata": "{"url: "list sections"}"


// Retrieve all content from a specific section.

@name("Contents of section v2")
GET "https://{{KNOWLEDGE_BASE_URL}}/workspace/v2/sections/{{SECTION_ID}}/contents"
"Content-Type": "application/json"
"Authorization": "{{TOKEN}}"
? "sort_by"= "position:desc"
? "limit"= "1"
? "continuation"= "DnF1ZXJ5VGhlbkZl"



