#!/usr/bin/env dothttp

@name("Fetch agents list limited by a tenant for which API Client was created")
GET "https://{{base_url}}/api/agent_manager/v2/agents"


@name("Force to start update of all agents")
POST "https://{{base_url}}/api/agent_manager/v2/agents/update:force"


@name("Fetch agents list for a tenant")
GET "https://{{base_url}}/api/agent_manager/v2/agents"
? "tenant_id"= "{{tenant_id_int}}"


@name("Fetch an agent by id")
GET "https://{{base_url}}/api/agent_manager/v2/agents/{{agent_id}}"


@name("Get agents update configuration")
GET "https://{{base_url}}/api/agent_manager/v2/agents/update/configuration"


@name("Get the agents refernces")
GET "https://{{base_url}}/api/agent_manager/v2/agent_update_references"
? "update_channel"= "STABLE"
? "os_family"= "WINDOWS"
? "os_arch"= "X64"


@name("Get an agent update settings")
GET "https://{{base_url}}/api/agent_manager/v2/agent_update_settings/{{agent_id}}"
? "master"= "true"


@name("Get agents master update settings for a tenant")
GET "https://{{base_url}}/api/agent_manager/v2/agent_update_settings/{{customer_tenant_id}}"
? "master"= "true"



