#!/usr/bin/env dothttp

@name("Case Team Template")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamTemplate/"


@name("Case Team Template Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamTemplate/{ID}/"


@name("Describe Case Team Template")
GET "https://{{host}}/services/data/v47.0/sobjects/CaseTeamTemplate/describe/"



