#!/usr/bin/env dothttp

// <p>Returns a list of generic entities. Can optionally sort the resulting list in ascending or
//  descending order. Other params given will be used as search values.</p>
//  <p class="italicize">Examples:</p>
//  <div class="code indent"><pre>/restman/1.0/activeConnectors?name=MyGenericEntity</pre></div>
//  <p>Returns generic entity with name "MyGenericEntity".</p>
//  <p>If a parameter is not a valid search value a bad request error will be returned.</p>
// List

@name("List All Generic Entities")
GET "https://{{baseUrl}}/1.0/genericEntities"
? "sort"= "<string>"
? "order"= "<string>"
? "name"= "<array>"
? "enabled"= "<boolean>"
? "entityClassName"= "<array>"


// Retrieves a generic entity given its ID

@name("List Generic Entities By Id")
GET "https://{{baseUrl}}/1.0/genericEntities/:id"


// Returns a template, which is an example generic entity that can be used as a reference for what generic entity
//  objects should look like.
// Template

@name("Generic Entities Template")
GET "https://{{baseUrl}}/1.0/genericEntities/template"



