#!/usr/bin/env dothttp

@name("On/Off")
GET "http://{{ipAddress}}/api/v1/:auth_token/state/on"



@name("On/Off - update")
PUT "http://{{ipAddress}}/api/v1/:auth_token/state"
"Content-Type": "application/json"
json({
    "on": {
        "value": true
    }
})


@name("Brightness")
GET "http://{{ipAddress}}/api/v1/:auth_token/state/brightness"



// Duration field is optional, and specified in seconds.

@name("Brightness - update")
PUT "http://{{ipAddress}}/api/v1/:auth_token/state"
data('{"brightness" : {"value":100, "duration":30}}')


@name("Hue")
GET "http://{{ipAddress}}/api/v1/:auth_token/state/hue"



@name("Hue - update")
PUT "http://{{ipAddress}}/api/v1/:auth_token/state"
data('{"hue" : {"value":120}}')


@name("Saturation")
GET "http://{{ipAddress}}/api/v1/:auth_token/state/sat"



@name("Saturation - update")
PUT "http://{{ipAddress}}/api/v1/:auth_token/state/sat"
data('{"sat" : {"value": 20}}')


// 1.5.0:
// 
// - Min and max values returned for ct are wrong. They should be 1200-6500, but are returned 0-100.

@name("Color Temperature")
GET "http://{{ipAddress}}/api/v1/:auth_token/state/ct"



// 1.5.0:
// 
// - Min and max values returned for ct are wrong. They should be 1200-6500, but are returned 0-100.

@name("Color Temperature - update")
PUT "http://{{ipAddress}}/api/v1/:auth_token/state"
data('{"ct" : {"value": 3000}}')


@name("Color Mode")
GET "http://{{ipAddress}}/api/v1/:auth_token/state/colorMode"




