#!/usr/bin/env dothttp

// If API is online and functional, responds with `HTTP 200 OK` and a requested API version

@name("Check API status")
GET "https://{{domain}}/api/v3/status"


// If API in online and functional, and presented `access token` is valid and not expired, responds with a `HTTP 200 OK` status, current endpoint API version and list of claims from supplied `access token`

@name("Check access token status")
GET "https://{{domain}}/api/v3/status/oauth"



