#!/usr/bin/env dothttp

@name("Add a new breed")
POST "https://{{baseUrl}}/breed"
"Content-Type": "application/json"
json({
    "categoryId": 1,
    "breedName": "Dalmation"
})


@name("Get breeds based on category")
GET "https://{{baseUrl}}/breed/1"



