#!/usr/bin/env dothttp

// Authorizes a new transaction for a given wallet.

@name("/transactions/authorize (authorization)")
POST "https://{{API_BASE_URL}}/transactions/authorize"
"Content-Type": "application/json"
"X-Request-Signature": "{{X_REQUEST_SIGNATURE}}"
"X-Request-Timestamp": "{{X_REQUEST_TIMESTAMP}}"
data('{
  "event": "authorization",
  "type": "card",
  "asset": "BRLP",
  "amount": "20.00",
  "walletId": "360fcfbf-58b0-43b1-ba08-44f06de5db85",
  "transitoryAccountType": "card_transaction",
  "additionalData": {
    "merchantName": "TEST",
    "merchantCode": "TEST",
    "raw": {}
  }
}
')


// Settles an authorized transaction(sends it from `authorized` to `executed`).

@name("/transactions/authorize (settlement)")
POST "https://{{API_BASE_URL}}/transactions/authorize"
"Content-Type": "application/json"
"X-Request-Signature": "{{X_REQUEST_SIGNATURE}}"
"X-Request-Timestamp": "{{X_REQUEST_TIMESTAMP}}"
data('{
  "event": "settlement",
  "type": "card",
  "asset": "BRLP",
  "amount": "0.50",
  "transactionId": "415f63b3-435c-4b74-9b40-b52aa870f19c",
  "walletId": "360fcfbf-58b0-43b1-ba08-44f06de5db85",
  "transitoryAccountType": "card_transaction"
}')


// Refunds a settled transaction(creates a new transaction of type `transaction_reversal` reverting the original transaction)

@name("/transactions/authorize (refund)")
POST "https://{{API_BASE_URL}}/transactions/authorize"
"Content-Type": "application/json"
"X-Request-Signature": "{{X_REQUEST_SIGNATURE}}"
"X-Request-Timestamp": "{{X_REQUEST_TIMESTAMP}}"
data('{
  "event": "refund",
  "type": "transaction_reversal",
  "asset": "BRLP",
  "amount": "0.50",
  "transactionId": "5ae20f15-33bd-459e-bb60-21bdde488a8f",
  "walletId": "360fcfbf-58b0-43b1-ba08-44f06de5db85"
}
')


// Reverts an authorized transaction.

@name("/transactions/authorize (authorization_reversal)")
POST "https://{{API_BASE_URL}}/transactions/authorize"
"Content-Type": "application/json"
"X-Request-Signature": "{{X_REQUEST_SIGNATURE}}"
"X-Request-Timestamp": "{{X_REQUEST_TIMESTAMP}}"
data('{
  "event": "authorization_reversal",
  "type": "card",
  "asset": "BRLP",
  "amount": "0.50",
  "transactionId": "c5dbbf84-e243-4d02-beb3-3890ec702391",
  "walletId": "360fcfbf-58b0-43b1-ba08-44f06de5db85",
  "transitoryAccountType": "card_transaction"
}')



