#!/usr/bin/env dothttp

// You must use a [JWT](https://docs.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
// 
// The permissions the installation has are included under the `permissions` key.

@name("List installations for the authenticated app")
GET "https://{{baseUrl}}/app/installations"
? "per_page"= "30"
? "page"= "1"
? "since"= "<string>"
? "outdated"= "<string>"



