#!/usr/bin/env dothttp

@name("networkdevicegroup")
GET "https://{{base_url}}/ers/config/networkdevicegroup"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"
? "size"= "100"
? "page"= "1"
? "filter"= "name.CONTAINS.irv"
? "sortasc"= "name"
? "sortdsc"= "name"


@name("networkdevicegroup/{id}")
GET "https://{{base_url}}/ers/config/networkdevicegroup/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("networkdevicegroup/name/{name}")
GET "https://{{base_url}}/ers/config/networkdevicegroup/name/{{name}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"


@name("networkdevicegroup: Device Type")
POST "https://{{base_url}}/ers/config/networkdevicegroup"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"
data('{
  "NetworkDeviceGroup": {
    "name": "Device Type#All Device Types#SDWAN",
    "description": "...",
    "othername": "Device Type"
  }
}')


@name("networkdevicegroup: Location Copy")
POST "https://{{base_url}}/ers/config/networkdevicegroup"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"
data('{
  "NetworkDeviceGroup": {
    "name": "Location#All Locations#SNG",
    "description": "...",
    "othername": "Location"
  }
}')


@name("networkdevicegroup/{id}")
PUT "https://{{base_url}}/ers/config/networkdevicegroup/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"
data('{
  "NetworkDeviceGroup": {
    "name": "Device Type#All Device Types#SDWAN",
    "description": "SDWAN description",
    "othername": "Device Type"
  }
}')


@name("networkdevicegroup/{id}")
DELETE "https://{{base_url}}/ers/config/networkdevicegroup/{{id}}"
basicauth("{{rest_username}}", "{{rest_password}}")
"Content-Type": "application/json"
"Accept": "application/json"



