#!/usr/bin/env dothttp

// This pulls all the tweets for @healthvermont and saves them to the environment.

@name("Bennington Vermont Department of Health")
GET "https://api.twitter.com/labs/2/tweets/search"
? "query"= "from:healthvermont"
? "tweet.fields"= "created_at,author_id,lang,context_annotations"
? "place.fields"= "client_credentials"
? "max_results"= "100"



