#!/usr/bin/env dothttp

@name("Get WebApp Settings (Deprecated)")
GET "https://{{sb_client}}.salesboard.biz/v1/settings/settings-webapp"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"


@name("Get WebApp Settings V2")
GET "https://{{sb_client}}.salesboard.biz/v2/settings/webapp"
"XREQUESTEDWITH": "WebAppHttpRequest"
"Cookie": "PHPSESSID={{sb_token}}"



