#!/usr/bin/env dothttp

// <h2>Description</h2>
// This operation returns values for global parameters.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_global_parameters.htm)

@name("Global Parameter")
POST "https://{{ServerUrl}}/CommServ/GlobalParams"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
data('{
  "globalParamsRequestList": [
    "CI_STATE_FAILED",
    "CI_STATE_SKIPPED",
    "AppMgrThreadIdleTimeout"
  ]
}')


// <h2>Description</h2>
// This operation sets a global parameter.

@name("Set Global Parameter")
POST "https://{{ServerUrl}}/setGlobalParam"
"Authtoken": "{{TOKEN}}"
"Accept": "{{Accept}}"
"Content-Type": "application/json"
data('{
	"name": "AppMgrInitThreadCount",
	"value": "10"
}')



