#!/usr/bin/env dothttp

// By default, a user is created as a `manager`. Be careful, it means as an assistant and not as a administrator.
// 
// Here are the 3 different levels of permissions:
// 
// * **Manager:** He's able to create procedures.
// * **Signer:** Manager's permissions + he's able to sign procedures.
// * **Admin:** Signer's permissions + he's able to acces to admin menu (user management, API keys, branding, ...).

@name("/users")
POST "https://{{base-api-url}}/users"
"Authorization": "Bearer {{your-api-key}}"
"Content-Type": "application/json"
json({
    "firstname": "John",
    "lastname": "Doe",
    "email": "api@yousign.fr",
    "title": "API teacher",
    "phone": "+33612345678"
})



