#!/usr/bin/env dothttp

@name("Indonesia Resident Identity Card")
POST "https://resttest.datazoo.com/api/Indonesia/Verify.json"
data('{
	"dataSources": [
        "Indonesia Resident Id Card"
    ],
	"nik": "8171022701820005",
	"fullName": "Muhammad Amin Keliora",
	"dateOfBirth": "1982-01-27",
	"gender": "Male",
	"streetName": "Kebun Cengkeh 002",
	"village": "Batu Merah",
	"district": "Kota Ambon",
	"city": "Maluku",
	"indonesiaResidentIdentityCardConsentObtained": true
}
')



