#!/usr/bin/env dothttp

// https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/validateEmail.htm// // Validates an email by specifying the email address and validators to be used in the request body of the HTTP POST. You can use more than one validator in the same call.
@name("Validate Address")
POST "https://{{et_subdomain}}.rest.marketingcloudapis.com/address/v1/validateEmail"
json({
    "email": "help@example.com",
    "validators": [
        "SyntaxValidator",
        "MXValidator",
        "ListDetectiveValidator"
    ]
})



