#!/usr/bin/env dothttp

@name("Create Natural Docket")
POST "https://{{domain}}/api/natural_docket_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "natural_docket_seeds",
        "attributes": {
            "first_name": "John",
            "last_name": "Doe",
            "nationality": "AR",
            "gender_code": "male",
            "marital_status_code": "single",
            "politically_exposed": "false",
            "birth_date": "1990-12-31"
        },
        "relationships": {
            "issue": {
                "data": {
                    "id": "2",
                    "type": "issues"
                }
            }
        }
    }
})


@name("Update Natural Docket")
PATCH "https://{{domain}}/api/natural_docket_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "natural_docket_seeds",
        "attributes": {
            "first_name": "John",
            "last_name": "Doe",
            "nationality": "AR",
            "gender_code": "male",
            "marital_status_code": "single",
            "politically_exposed": "false",
            "birth_date": "1990-12-31"
        },
        "relationships": {
            "issue": {
                "data": {
                    "id": "2",
                    "type": "issues"
                }
            }
        }
    }
})


@name("Create Legal Entity Docket")
POST "https://{{domain}}/api/legal_entity_docket_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "legal_entity_docket_seeds",
        "attributes": {
            "industry": "it",
            "business_description": "software",
            "country": "AR",
            "commercial_name": "AwesomeCompany",
            "legal_name": "My Company Inc."
        },
        "relationships": {
            "issue": {
                "data": {
                    "type": "issues",
                    "id": "some_issue.id"
                }
            }
        }
    }
})


@name("Update Legal Entity Docket")
PATCH "https://{{domain}}/api/legal_entity_docket_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "legal_entity_docket_seeds",
        "attributes": {
            "industry": "it",
            "business_description": "software",
            "country": "AR",
            "commercial_name": "AwesomeCompany",
            "legal_name": "My Company Inc."
        }
    }
})


// The identification should be checked by an attachment demonstrating its validity.

@name("Create Identification")
POST "https://{{domain}}/api/identification_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "identification_seeds",
        "attributes": {
            "identification_kind_code": "national_id",
            "issuer": "AR",
            "number": "12345678"
        },
        "relationships": {
            "issue": {
                "data": {
                    "type": "issues",
                    "id": "some_issue.id"
                }
            }
        }
    }
})


// The identification should be checked by an attachment demonstrating its validity.

@name("Update Identification")
PATCH "https://{{domain}}/api/identification_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
data('{
	"data": {
		"type":"identification_seeds",
		"attributes": {
			"identification_kind_code": "national_id",
			"issuer": "AR",
			"number": "12345678"
		}
	},
	 
}')


@name("Create Note")
POST "https://{{domain}}/api/note_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "note_seeds",
        "attributes": {
            "body": "these are custom notes",
            "title": "identification note"
        },
        "relationships": {
            "issue": {
                "data": {
                    "type": "issues",
                    "id": "some_issue.id"
                }
            }
        }
    }
})


@name("Update Note")
PATCH "https://{{domain}}/api/note_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
data('{
	"data": {
		"type":"note_seeds",
		"attributes": {
			"body": "these are custom notes",
			"title": "identification note"
		}
	},
	 
}')


// The domicile should be checked by an attachment demonstrating its validity.

@name("Create Domicile")
POST "https://{{domain}}/api/domicile_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "domicile_seeds",
        "attributes": {
            "city": "CABA",
            "country": "AR",
            "floor": "0",
            "postal_code": "1001",
            "street_address": "Balcarce",
            "street_number": "50"
        },
        "relationships": {
            "issue": {
                "data": {
                    "id": "2",
                    "type": "issues"
                }
            }
        }
    }
})


// The domicile should be checked by an attachment demonstrating its validity.

@name("Update domicile")
PATCH "https://{{domain}}/api/domicile_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "domicile_seeds",
        "attributes": {
            "city": "CABA",
            "country": "AR",
            "floor": "0",
            "postal_code": "1001",
            "street_address": "Balcarce",
            "street_number": "50"
        },
        "relationships": {
            "issue": {
                "data": {
                    "id": "2",
                    "type": "issues"
                }
            }
        }
    }
})


@name("Create Email")
POST "https://{{domain}}/api/email_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "email_seeds",
        "attributes": {
            "address": "person@example.com",
            "email_kind_code": "invoicing"
        }
    },
    "relationships": {
        "issue": {
            "data": {
                "id": "2",
                "type": "issues"
            }
        }
    }
})


@name("Update Email")
PATCH "https://{{domain}}/api/email_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
data('{
	"data": {
		"type":"email_seeds",
		"attributes": {
			"address": "person@example.com",
			"email_kind_code": "invoicing"
		}
	},
	 
}')


@name("Create Argentina Invoicing Detail")
POST "https://{{domain}}/api/argentina_invoicing_detail_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "argentina_invoicing_detail_seeds",
        "attributes": {
            "address": "Balcarce, 50, 0, CABA",
            "country": "AR",
            "full_name": "John, Doe",
            "receipt_kind_code": "b",
            "tax_id": "20123456786",
            "tax_id_kind_code": "cuil",
            "vat_status_code": "consumidor_final"
        },
        "relationships": {
            "issue": {
                "data": {
                    "id": "2",
                    "type": "issues"
                }
            }
        }
    }
})


@name("Update Argentina Invoicing Detail")
PATCH "https://{{domain}}/api/argentina_invoicing_detail_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
data('{
	"data": {
		"type":"argentina_invoicing_detail_seeds",
		"attributes": {
			"address": "Balcarce, 50, 0, CABA",
			"country": "AR",
			"full_name": "John, Doe",
			"receipt_kind_code": "b",
			"tax_id": "20123456786",
			"tax_id_kind_code": "cuil",
			"vat_status_code": "consumidor_final"
		}
	},
	 
}')


@name("Create Chile Invoicing Detail")
POST "https://{{domain}}/api/chile_invoicing_detail_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "argentina_invoicing_detail_seeds",
        "attributes": {
            "ciudad": "santiago",
            "comuna": "Chile",
            "giro": "2332",
            "tax_id": "12053214-6",
            "vat_status_code": "consumidor_final"
        },
        "relationships": {
            "issue": {
                "data": {
                    "id": "2",
                    "type": "issues"
                }
            }
        }
    }
})


@name("Update Chile Invoicing Detail")
PATCH "https://{{domain}}/api/chile_invoicing_detail_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "argentina_invoicing_detail_seeds",
        "attributes": {
            "ciudad": "santiago",
            "comuna": "Chile",
            "giro": "2332",
            "tax_id": "12053214-6",
            "vat_status_code": "consumidor_final"
        }
    }
})


@name("Create Allowance")
POST "https://{{domain}}/api/allowance_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "allowance_seeds",
        "attributes": {
            "kind_code": "usd"
        },
        "relationships": {
            "issue": {
                "data": {
                    "id": "2",
                    "type": "issues"
                }
            }
        }
    }
})


@name("Update Allowance")
PATCH "https://{{domain}}/api/allowance_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
data('{
	"data": {
		"type":"allowance_seeds",
		"attributes": {
			"kind_code": "usd"
		}
	},
	 
}')


@name("Create Phone")
POST "https://{{domain}}/api/phone_seeds"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "phone_seeds",
        "attributes": {
            "country": "AR",
            "number": "12345678",
            "phone_kind_code": "main"
        }
    },
    "relationships": {
        "issue": {
            "data": {
                "id": "2",
                "type": "issues"
            }
        }
    }
})


@name("Update Phone")
PATCH "https://{{domain}}/api/phone_seeds/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
data('{
	"data": {
		"type":"phone_seeds",
		"attributes": {
			"country": "AR",
			"number": "12345678",
			"phone_kind_code": "main"
		}
	},
	 
}')


// Attachments include a full base64 encoded version of the file as the __document__ attribute.
// 
// We accept the following file types:
// 
//     'image/bmp',
//     'image/jpeg',
//     'image/jpg',
//     'image/gif',
//     'image/png'
//     'application/pdf',
//     'application/zip',
//     'application/x-rar-compressed'
// 
// 
// Keep in mind just changing the extension won't work, if the file format you want to send is not supported, put it in a zip or rar and upload that.

@name("Create Attachments")
POST "https://{{domain}}/api/attachments"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
json({
    "data": {
        "type": "attachments",
        "attributes": {
            "document": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P+/HgAFhAJ/wlseKgAAAABJRU5ErkJggg==",
            "document_file_name": "pixel.png",
            "document_content_type": "image/png",
            "document_size": "68"
        },
        "relationships": {
            "attached_to_seed": {
                "data": {
                    "id": "1",
                    "type": "identification_seeds"
                }
            }
        }
    },
    "included": [
        {
            "type": "identification_seeds",
            "attributes": {
                "number": "12345678",
                "issuer": "AR",
                "identification_kind_code": "national_id",
                "created_at": "2018-10-23T17:32:52.000Z",
                "updated_at": "2018-10-23T17:32:52.000Z"
            },
            "relationships": {
                "attachments": {
                    "data": []
                }
            },
            "id": "1"
        }
    ]
})



