#!/usr/bin/env dothttp

@name("Account Operation Upload File")
POST "https://{{base_url}}/sales/account_operation/upload"
json({
    "salesEmailTypeEnum": 14,
    "company": {
        "companyId": "BB5D908C-EB94-46D3-A987-2A81DC429DE1",
        "companyNumber": "208497",
        "taxId": "XIA190128J61",
        "legalName": "Sable Digital Studio SA de CV",
        "commercialName": "Sable",
        "countryCode": "MEX",
        "companyStatus": "active",
        "color": 46,
        "companyLogo": "https://gestionix-core-images-dev.azurewebsites.net/images/25a805ec2b4eba42c5345ae26b06425d",
        "companyDocumentsLogo": "https://gestionix-core-images-dev.azurewebsites.net/images/b153e710fa9b038237c57ec17bcd7e45",
        "creationDate": "2020-09-09T17:07:29.770Z",
        "fiscalAddress": {
            "addressId": "EF916A7D-0AE4-4D0C-870F-DE09DD3DF7D8",
            "addressNumber": "16721",
            "street": "",
            "outsideNumber": "",
            "insideNumber": "",
            "neighborhood": "",
            "municipality": "",
            "city": "",
            "state": "",
            "country": "",
            "countryCode": "MEX",
            "postalCode": "11310",
            "reference": null,
            "fullAddress": ""
        },
        "commercialAddress": "16722",
        "subscriptionNumber": "2020094348208497",
        "IANAHusoHorario": "America/Mexico_City",
        "ReferenciasDelHusoHorario": "Tiempo del Centro",
        "dataLocalized": {
            "companyNumber": "208497",
            "regimenFiscalNombre": "General de Ley Personas Morales",
            "regimenFiscalCodigo": "601",
            "curp": null,
            "registroPatronal": null,
            "ciecConfigurada": null,
            "ciecConfiguradaFecha": null,
            "connectionId": null
        },
        "digitalCertificates": [
            {
                "companyNumber": "208497",
                "certificateNumber": "30001000000400002443",
                "certificateToken": "583f2b1f2028c139cd5cf2f40a1fe696db51f3c0871ea40563a574029405c54d",
                "registeredDate": "2020-09-09T17:20:39.833Z",
                "expirationDate": "2023-06-17T20:40:51.000Z",
                "certificateStatus": "valid",
                "certificateType": "CSD",
                "countryCode": "MEX"
            }
        ],
        "timezone": "America/Mexico_City",
        "logoUrl": "https://gestionix-core-images-dev.azurewebsites.net/images/25a805ec2b4eba42c5345ae26b06425d"
    },
    "client": {
        "clientId": "5BC50E32-8C29-483E-AC2C-7553442350FC",
        "clientNumber": 1,
        "companyNumber": 208497,
        "branchNumber": null,
        "taxId": "XAXX010101000",
        "businessName": null,
        "commercialName": "Público General",
        "addressId": null,
        "countryCode": "MEX",
        "gln": null,
        "clientStatusId": 1,
        "clientStatus": "active",
        "registeredDate": "2020-09-09T17:07:39.617Z",
        "lastActivity": "2021-01-14T18:09:14.390Z",
        "sellOnCredit": false,
        "maximumCreditAmount": null,
        "maximumCreditCurrency": null,
        "maximumCreditDays": null,
        "tagValueGroup": "alto",
        "tagActivityBehavior": "decreciente",
        "tagCreditBehavior": "sin información",
        "tagDebLevel": "sin información",
        "tagPaymentBehavior": "sin información",
        "salesQuotesDefaultContactId": null,
        "salesOrderDefaultContactId": null,
        "salesDefaultContactId": null,
        "assignedSalesPersonId": null,
        "defaultPriceList": null,
        "avatarURL": null,
        "color": 35,
        "pendingPayment": 0,
        "contacts": [
            {
                "personId": "9DB23182-8D3D-40F7-83B3-7B031EF8A11D",
                "personNumber": 880,
                "name": "Yocelin Garcia",
                "jobTitle": "",
                "email": "gr.yocelin@gmail.com",
                "phone": "",
                "mobilePhone": "",
                "countryCode": "MEX",
                "country": null,
                "registeredDate": "2020-12-23T20:34:53.880Z",
                "invoiceContact": true
            }
        ]
    },
    "accountOperation": {
        "id": 575,
        "accountOperationStatus": "received",
        "accountOperationType": "income",
        "amount": "100.00",
        "branchNumber": 16670,
        "clientId": "5bc50e32-8c29-483e-ac2c-7553442350fc",
        "companyNumber": 208497,
        "currency": "MXN",
        "fileAttachmentUrl": null,
        "accountId": 1,
        "internalNote": "mucsh mushas notas",
        "operationDatetime": "2021-01-14T06:00:00Z",
        "operationNumber": 24,
        "timeZone": "Etc/UTC",
        "tzOffset": 0,
        "paymentForm": {
            "code": "03",
            "paymentType": "Transferencia electrónica de fondos"
        },
        "sales": [
            {
                "saleId": "068a5a71-eccf-4cbf-b3ee-44edc3ae85b6",
                "amount": "100.00",
                "saleNumber": 447,
                "invoiceFolio": "351bb50b-94fd-4314-b4ff-ec149b340306",
                "partiality": 4,
                "previousBalance": "477.19",
                "outstandingBalance": "377.19",
                "currency": "MXN",
                "paymentMethod": "PPD",
                "serie": "A-298"
            }
        ],
        "paymentDetail": {
            "transferType": "spei",
            "trackingKey": "3456456435634563456",
            "certificate": "MDE5ODc1NDk4NTEzOTU4NjE0OTUxMzU=",
            "paymentChain": "3456456435634563400",
            "paymentStamp": "T1RJek56VXhNemduTmpVd09UZzBNalk1T0RNME56VXdNVE0wT1RjMk1ERXpPVFEzTmprd01UTTBOell3T1RFek9EWXdNVE0wT0RZd01UTTROakE1TVRRMQ==",
            "issuerAccount": "4519714396115986",
            "checkNumber": "undefined",
            "emitterTaxId": "undefined",
            "bank": {
                "name": "Banco Nacional de México, S.A., Institución de Banca Múltiple, Grupo Financiero Banamex",
                "bankCode": "002"
            }
        },
        "rep": null,
        "formaDePago": "03",
        "formaDePagoDescription": "Transferencia electrónica de fondos",
        "timezoneOffset": 0,
        "salesRelated": [
            {
                "folioFiscalCfdi": "351bb50b-94fd-4314-b4ff-ec149b340306",
                "saleNumber": "VE-447",
                "currency": "MXN",
                "metodoDePago": "PPD",
                "metodoDePagoDescripcion": "Pago en parcialidades",
                "partiality": 4,
                "previousBalance": "477.19",
                "amountPaid": "100.00",
                "outstandingBalance": "377.19"
            }
        ],
        "detalleDePago": {
            "title": "Detalle de la Transferencia",
            "detail": [
                {
                    "Tipo de transferencia": "spei"
                },
                {
                    "Banco de origen": "Banco Nacional de México, S.A., Institución de Banca Múltiple, Grupo Financiero Banamex"
                },
                {
                    "RFC banco de origen": "BNM840515VB1"
                },
                {
                    "Clave de rastreo": "3456456435634563456"
                },
                {
                    "Certificado de pago": "MDE5ODc1NDk4NTEzOTU4NjE0OTUxMzU="
                },
                {
                    "Cadena de pago": "3456456435634563400"
                },
                {
                    "Sello de pago": "T1RJek56VXhNemduTmpVd09UZzBNalk1T0RNME56VXdNVE0wT1RjMk1ERXpPVFEzTmprd01UTTBOell3T1RFek9EWXdNVE0wT0RZd01UTTROakE1TVRRMQ=="
                },
                {
                    "Cuenta emisor": "4519714396115986"
                }
            ]
        }
    }
})


@name("Account Operation Cancel")
POST "https://{{base_url}}/sales/account_operation/cancel"
json({
    "salesEmailTypeEnum": 17,
    "company": {
        "companyId": "BB5D908C-EB94-46D3-A987-2A81DC429DE1",
        "companyNumber": "208497",
        "taxId": "XIA190128J61",
        "legalName": "Luft agencia digital",
        "commercialName": "Luft",
        "countryCode": "MEX",
        "companyStatus": "active",
        "color": 46,
        "companyLogo": "https://gestionix-core-images-dev.azurewebsites.net/images/25a805ec2b4eba42c5345ae26b06425d",
        "companyDocumentsLogo": "https://gestionix-core-images-dev.azurewebsites.net/images/b153e710fa9b038237c57ec17bcd7e45",
        "creationDate": "2020-09-09T17:07:29.770Z",
        "fiscalAddress": {
            "addressId": "EF916A7D-0AE4-4D0C-870F-DE09DD3DF7D8",
            "addressNumber": "16721",
            "street": "",
            "outsideNumber": "",
            "insideNumber": "",
            "neighborhood": "",
            "municipality": "",
            "city": "",
            "state": "",
            "country": "",
            "countryCode": "MEX",
            "postalCode": "11444",
            "reference": null,
            "fullAddress": ""
        },
        "commercialAddress": "16722",
        "subscriptionNumber": "2020094348208497",
        "IANAHusoHorario": "America/Mexico_City",
        "ReferenciasDelHusoHorario": "Tiempo del Centro",
        "dataLocalized": {
            "companyNumber": "208497",
            "regimenFiscalNombre": "General de Ley Personas Morales",
            "regimenFiscalCodigo": "601",
            "curp": null,
            "registroPatronal": null,
            "ciecConfigurada": null,
            "ciecConfiguradaFecha": null,
            "connectionId": null
        },
        "digitalCertificates": [
            {
                "companyNumber": "208497",
                "certificateNumber": "30001000000400002443",
                "certificateToken": "583f2b1f2028c139cd5cf2f40a1fe696db51f3c0871ea40563a574029405c54d",
                "registeredDate": "2020-09-09T17:20:39.833Z",
                "expirationDate": "2023-06-17T20:40:51.000Z",
                "certificateStatus": "valid",
                "certificateType": "CSD",
                "countryCode": "MEX"
            }
        ],
        "timezone": "America/Mexico_City",
        "logoUrl": "https://gestionix-core-images-dev.azurewebsites.net/images/25a805ec2b4eba42c5345ae26b06425d"
    },
    "client": {
        "clientId": "5BC50E32-8C29-483E-AC2C-7553442350FC",
        "clientNumber": 1,
        "companyNumber": 208497,
        "branchNumber": null,
        "taxId": "XAXX010101000",
        "businessName": null,
        "commercialName": "Público General",
        "addressId": null,
        "countryCode": "MEX",
        "gln": null,
        "clientStatusId": 1,
        "clientStatus": "active",
        "registeredDate": "2020-09-09T17:07:39.617Z",
        "lastActivity": "2021-03-11T00:50:58.130Z",
        "sellOnCredit": false,
        "maximumCreditAmount": null,
        "maximumCreditCurrency": null,
        "maximumCreditDays": null,
        "tagValueGroup": "alto",
        "tagActivityBehavior": "decreciente",
        "tagCreditBehavior": "sin información",
        "tagDebLevel": "sin información",
        "tagPaymentBehavior": "sin información",
        "salesQuotesDefaultContactId": null,
        "salesOrderDefaultContactId": null,
        "salesDefaultContactId": null,
        "assignedSalesPersonId": null,
        "defaultPriceList": null,
        "avatarURL": null,
        "color": 35,
        "pendingPayment": 0,
        "contacts": [
            {
                "personId": "9DB23182-8D3D-40F7-83B3-7B031EF8A11D",
                "personNumber": 880,
                "name": "Yocelin Garcia",
                "jobTitle": "",
                "email": "gr.yocelin@gmail.com",
                "phone": "",
                "mobilePhone": "",
                "countryCode": "MEX",
                "country": null,
                "registeredDate": "2020-12-23T20:34:53.880Z",
                "invoiceContact": true
            }
        ]
    },
    "rep": {
        "fechaDeFacturacion": "2021-03-12T02:25:15Z",
        "subtotal": null,
        "acuseDeCancelacion": null,
        "tipoDeCambio": 1,
        "total": 1181.57,
        "codigoMoneda": "MXN",
        "fechaDeExpiracionCancelacion": null,
        "emisor": {
            "codigoPostal": "11444",
            "nombreORazonSocial": "Luft agencia digital",
            "regimenFiscalCodigo": "601",
            "rfc": "XIA190128J61"
        },
        "lugarExpedicion": "11444",
        "conceptos": [
            {
                "posicion": 1,
                "clave": "Actividad - ACT",
                "descripcion": "Pago - P",
                "cantidad": "1",
                "unidadDeMedida": "Hora",
                "precioBaseUnitario": "0",
                "importeDeDescuento": "0",
                "precioUnitarioConDescuentos": "0",
                "importeSubtotal": "0",
                "impuestosTransferidos": [],
                "impuestosRetenidos": [],
                "importeTotal": "0",
                "claveProductoServicioSAT": "84111506",
                "claveProductoServicioSATDescripcion": "Servicios de facturación",
                "claveUnidadMedidaSAT": "HUR"
            }
        ],
        "tipoDeCfdi": "P",
        "cliente": {
            "clientId": null,
            "clientNumber": null,
            "codigoDePais": "MEX",
            "codigoPostal": null,
            "nombreORazonSocial": "Yocelin Garcia",
            "numRegIdTrib": null,
            "pais": "",
            "rfc": "XAXX010101000"
        },
        "id": "C0C079F5-9A17-4D2D-8AB3-239D71404BF8",
        "cfdisRelacionados": [
            {
                "folioFiscalCfdi": "79cdb71d-d654-4987-be3d-c33f8bd715e7",
                "tipoDeRelacion": "04"
            },
            {
                "folioFiscalCfdi": "79cdb71d-d654-4987-be3d-c33f8bd715e7",
                "tipoDeRelacion": "04"
            }
        ],
        "certificado": {
            "certificateNumber": "30001000000400002443",
            "certificateToken": "583f2b1f2028c139cd5cf2f40a1fe696db51f3c0871ea40563a574029405c54d"
        },
        "metodoDePago": "PPD",
        "impuestosRetenidos": [],
        "formaDePago": "01",
        "impuestosTransferidos": [],
        "complementoPago": {
            "beneficiario": null,
            "cadenaPago": null,
            "certificadoPago": null,
            "doctoRelacionados": [
                {
                    "folioFiscalCfdi": "79cdb71d-d654-4987-be3d-c33f8bd715e7",
                    "saleNumber": "A-570",
                    "currency": "MXN",
                    "metodoDePago": "PPD",
                    "metodoDePagoDescripcion": "Pago en parcialidades",
                    "partiality": 1,
                    "previousBalance": "2181.57",
                    "amountPaid": "1000.00",
                    "outstandingBalance": "1181.57"
                },
                {
                    "folioFiscalCfdi": "79cdb71d-d654-4987-be3d-c33f8bd715e7",
                    "saleNumber": "A-570",
                    "currency": "MXN",
                    "metodoDePago": "PPD",
                    "metodoDePagoDescripcion": "Pago en parcialidades",
                    "partiality": 2,
                    "previousBalance": "1181.57",
                    "amountPaid": "181.57",
                    "outstandingBalance": "1000.00"
                }
            ],
            "fechaDePago": "2021-03-11T06:00:00Z",
            "numeroDeOperacion": null,
            "ordenante": null,
            "selloPago": null,
            "tipoCadenaPago": null,
            "version": "1.0"
        },
        "sello": "FzgFBVXAtw47wNCkA5HEkkdwOJtqBuXF46DS0+IyfdtZ7iZlbHFckHcZYt8Sf1LcRVvEEvOw17Q9Nt7OHYEr+wV6Z6WjYh/qu7O+FNI5VbABi3NdQg4xeBIXQzHfu5rVLAxq/fES2j748HjQQbUlWU78J+5dff7+KyP3v6iNk5kLR3/04W7jY3FzvOcR4EeJViPTr5hbB/EZyxm7dnF1j5PCz5yikkWlK47/8OE6Jcvj3lgNuIFdpwvPtDLMk8LGgSUZhVhQH89clGQMV+VEO1euc2Cw1qV1wkoEAsTK25lB9sxRZx+uz44TXBWXWYrfYZ79mPubxG/rCMf9F4f8LA==",
        "tipoDeComprobante": "rep",
        "fechaDeEnvioAFacturacion": "2021-03-12T02:25:11.852Z",
        "status": "vigente",
        "version": "3.3",
        "folio": "44",
        "selloSAT": "A3+uItLpUy1t6nNVQ9lvMw8kdNSWO0/YiK4JAe9i1G4sgxjRst8QGvSepu+q58nLbwSaAzxTzePWR9WqnQvlSjEF6bsGuNRHvQBVOj3ju0PTNMgFwtzGTL7XUpfH+N44HsYQRmjFXJE8QngzCvMmuZDuwnKDl3prMT/RxqeWMzABe6QLseekkgqZ23LZRTjf9m2zs4lO3EH/WGgfZsdozmdhBRACUqSTpqMlNu9NFWLFxKnoYKfFN52S8Aki/hZcECAFLMRFP+IE5M3UYHc+/d6ogNfyfV0L3iCFvJ6gbVtxj4CpEdOGG9zneLs9gYothYTcSvAvoDvl5xFD+N1DwQ==",
        "noCertificadoSAT": "30001000000300036825",
        "usoCfdi": "P01",
        "serie": "REP",
        "companyNumber": 208497,
        "xml": "cfdis/c0c079f5-9a17-4d2d-8ab3-239d71404bf8.xml",
        "folioFiscal": "c0c079f5-9a17-4d2d-8ab3-239d71404bf8",
        "addenda": null,
        "cadenaOriginalDelComplemento": "||1.1|C0C079F5-9A17-4D2D-8AB3-239D71404BF8|2021-03-11T20:25:15|ASE0201179X0|FzgFBVXAtw47wNCkA5HEkkdwOJtqBuXF46DS0+IyfdtZ7iZlbHFckHcZYt8Sf1LcRVvEEvOw17Q9Nt7OHYEr+wV6Z6WjYh/qu7O+FNI5VbABi3NdQg4xeBIXQzHfu5rVLAxq/fES2j748HjQQbUlWU78J+5dff7+KyP3v6iNk5kLR3/04W7jY3FzvOcR4EeJViPTr5hbB/EZyxm7dnF1j5PCz5yikkWlK47/8OE6Jcvj3lgNuIFdpwvPtDLMk8LGgSUZhVhQH89clGQMV+VEO1euc2Cw1qV1wkoEAsTK25lB9sxRZx+uz44TXBWXWYrfYZ79mPubxG/rCMf9F4f8LA==|30001000000300036825||"
    },
    "accountOperation": {
        "id": 1354,
        "accountOperationStatus": "received",
        "accountOperationType": "income",
        "amount": "1181.57",
        "branchNumber": 16670,
        "clientId": "5bc50e32-8c29-483e-ac2c-7553442350fc",
        "companyNumber": 208497,
        "currency": "MXN",
        "fileAttachmentUrl": null,
        "accountId": 1,
        "internalNote": "Notas para el cliente",
        "operationDatetime": "2021-03-11T06:00:00Z",
        "operationNumber": 44,
        "timeZone": "Etc/UTC",
        "tzOffset": 0,
        "paymentForm": {
            "code": "01",
            "paymentType": "Efectivo"
        },
        "sales": [
            {
                "saleId": "7dc7b6d6-b487-4928-b4d5-0949352cdd6b",
                "amount": "1000.00",
                "saleNumber": 804,
                "invoiceFolio": "79cdb71d-d654-4987-be3d-c33f8bd715e7",
                "partiality": 1,
                "previousBalance": "2181.57",
                "outstandingBalance": "1181.57",
                "currency": "MXN",
                "paymentMethod": "PPD",
                "serie": "A-570"
            },
            {
                "saleId": "7dc7b6d6-b487-4928-b4d5-0949352cdd6b",
                "amount": "181.57",
                "saleNumber": 804,
                "invoiceFolio": "79cdb71d-d654-4987-be3d-c33f8bd715e7",
                "partiality": 2,
                "previousBalance": "1181.57",
                "outstandingBalance": "1000.00",
                "currency": "MXN",
                "paymentMethod": "PPD",
                "serie": "A-570"
            }
        ],
        "paymentDetail": null,
        "rep": null,
        "formaDePago": "01",
        "formaDePagoDescription": "Efectivo",
        "timezoneOffset": 0,
        "salesRelated": [
            {
                "folioFiscalCfdi": "79cdb71d-d654-4987-be3d-c33f8bd715e7",
                "saleNumber": "VE-804",
                "currency": "MXN",
                "metodoDePago": "PPD",
                "metodoDePagoDescripcion": "Pago en parcialidades",
                "partiality": 1,
                "previousBalance": "1181.57",
                "amountPaid": "181.57",
                "outstandingBalance": "1000.00",
                "saleId": "7dc7b6d6-b487-4928-b4d5-0949352cdd6b",
                "paymentStatus": "partiallyPaid"
            },
            {
                "folioFiscalCfdi": "79cdb71d-d654-4987-be3d-c33f8bd715e7",
                "saleNumber": "VE-804",
                "currency": "MXN",
                "metodoDePago": "PPD",
                "metodoDePagoDescripcion": "Pago en parcialidades",
                "partiality": 2,
                "previousBalance": "1181.57",
                "amountPaid": "181.57",
                "outstandingBalance": "1000.00",
                "saleId": "7dc7b6d6-b487-4928-b4d5-0949352cdd6b",
                "paymentStatus": "fullyPaid"
            }
        ]
    },
    "user": {
        "userNumber": 12342,
        "color": 15,
        "image": null,
        "fullName": "Danny Tejeo"
    }
})



