#!/usr/bin/env dothttp

@name("Picklist Value Info")
GET "https://{{host}}/services/data/v47.0/sobjects/PicklistValueInfo/"


@name("Picklist Value Info Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/PicklistValueInfo/{ID}/"


@name("Describe Picklist Value Info")
GET "https://{{host}}/services/data/v47.0/sobjects/PicklistValueInfo/describe/"



