#!/usr/bin/env dothttp

// You can get the authentications per application counts for a selected environment over a specified time period. The `GET /environments/{environmentId}/applicationSignons` request must specify a `filter` expression that designates a date for the `occurredAt` attribute. The `samplePeriod`, and `samplePeriodCount` query parameters are expected values in the request URL, but they are not part of the `filter` expression. The `limit` request parameter is optional and can be omitted.
// 
// ::: info
// **Note:** If the `limit` query parameter is omitted from the request, its value is set to 100 by default.
// :::
// 
// 
// When the `endDate` in the response is determined to overlap the current date, the `partial` attribute shows that the response represents a shorter duration than requested by the `samplePeriod` and `samplePeriodCount`. The request shows the `partial` attribute in the response.
// 

@name("READ Authentications Per Application")
GET "https://{{apiPath}}/environments/{{envID}}/applicationSignons"
"Authorization": "Bearer {{jwtToken}}"
? "limit"= "10"
? "samplePeriod"= "1"
? "samplePeriodCount"= "10"
? 'filter'= 'occurredAt ge "2019-06-01T00:00:00Z"'


// When the `endDate` in the response is determined to overlap the current date, the `partial` attribute shows that the response represents a shorter duration than requested by the `samplePeriod` and `samplePeriodCount`. This sample request shows the `partial` attribute in the response.
// 

@name("READ Authentications Per Application (Partial)")
GET "https://{{apiPath}}/environments/{{envID}}/applicationSignons"
"Authorization": "Bearer {{jwtToken}}"
? "limit"= "1"
? "samplePeriod"= "1"
? "samplePeriodCount"= "100"
? 'filter'= 'occurredAt ge "2019-10-03T00:00:00Z""'



