#!/usr/bin/env dothttp

@name("Lookup Tables Post")
POST "https://{{baseUrl}}/platform/v2/lookuptables"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "description": [
        "<string>"
    ],
    "rows": [
        "[{\"name\":\"<string>\",\"value\":\"<string>\"},{\"name\":\"<string>\",\"value\":\"<string>\"}]"
    ],
    "isConfiguration": [
        "<boolean>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})


@name("Lookup Tables Get")
GET "https://{{baseUrl}}/platform/v2/lookuptables/:tenantid"
"Authorization": "<string>"
? "msql"= "<string>"
? "page"= "<integer>"
? "pageSize"= "<integer>"


@name("Lookup Tables Get")
GET "https://{{baseUrl}}/platform/v2/lookuptables/description/:tenantid"
"Authorization": "<string>"


@name("Lookup Tables Delete")
DELETE "https://{{baseUrl}}/platform/v2/lookuptables/delete/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"



