#!/usr/bin/env dothttp

@name("Create Transaction")
POST "https://{{apiPrefix}}/bank/transactions"
"Content-Type": "application/json"
"Authorization": "Bearer {{access-token}}"
json({
    "consumer_xref": "C-X-08f323deadbeefa7af34d5feb414ce27",
    "bank_transaction_id": "",
    "scheme_transaction_id": "",
    "message_type_indicator": "",
    "transmission_date_time": "2020-03-02T13:25:12+01:00",
    "local_transaction_date_time": "2020-03-02T13:25:12+01:00",
    "processing_code": 123456,
    "original_processing_code": 123456,
    "response_code": 0,
    "retrieval_reference_number": "",
    "authorisation_identification_response": "",
    "is_tokenised": true,
    "card": {
        "bin": 1234567,
        "last_four": 1234
    },
    "token": {
        "bin": 1234567,
        "last_four": 1234
    },
    "amount": {
        "transaction": {
            "amount": "123.45",
            "currency_code": "036"
        }
    },
    "acquirer": {
        "system_trace_audit_number": 123456
    },
    "merchant": {
        "category_code": 1234,
        "network_id": "",
        "terminal_id": "",
        "pseudo_terminal_id": "",
        "name_location": ""
    }
})


@name("Get a Single Transaction Record")
GET "https://{{apiPrefix}}/transactions/{{transaction-xref}}"
"Authorization": "Bearer {{access-token}}"



