#!/usr/bin/env dothttp

// Get the list of devices and device properties for the current user.  This will return a list of JSON objects that represent the devices attached to your gateway.
// 
// One object in the returned list will have type `GATEWAY` and represents the gateway itself.  The gateway device includes a `firmwareVersion` attribute which shows the Wifi and Zigby firmware versions, respectively.

@name("List Devices")
GET "https://{{address}}{{apiBasePath}}/devices/"
"Authorization": "Bearer {{access_token}}"



// Get the status of a device.

@name("Get Device")
GET "https://{{address}}{{apiBasePath}}/devices/{{deviceId}}"
"Authorization": "Bearer {{access_token}}"



// Turn a light or plug on or off.

@name("Light / Plug on")
PATCH "https://{{address}}{{apiBasePath}}/devices/{{deviceId}}"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
json({
    "onOff": "on"
})


// Change the brightness to a specific value.

@name("Change Brightness")
PATCH "https://{{address}}{{apiBasePath}}/devices/{{deviceId}}"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
json({
    "brightness": 50
})


// Set a light to a specific named color
// Supported colors:
//     red
//     green
//     blue
//     yellow
//     purple
//     orange
//     pink

@name("Change Color")
PATCH "https://{{address}}{{apiBasePath}}/devices/{{deviceId}}"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
json({
    "color": "red"
})


// Set a light to a specific named color temperature

@name("Change Color Temperature")
PATCH "https://{{address}}{{apiBasePath}}/devices/{{deviceId}}"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
json({
    "colorTemperature": 2700
})


// Set a light to a specific RGBW value

@name("Change to RGBW Color")
PATCH "https://{{address}}{{apiBasePath}}/devices/{{deviceId}}"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
json({
    "colorRGBW": {
        "red": 255,
        "green": 126,
        "blue": 0,
        "white": 0
    }
})



