#!/usr/bin/env dothttp

// This endpoint allows the client to retrieve a single
// published article given its `id`.

@name("A published article by ID")
GET "https://{{baseUrl}}/articles/:id"


// This endpoint allows the client to update an existing article.
// 
// "Articles" are all the posts that users create on DEV that typically
// show up in the feed. They can be a blog post, a discussion question,
// a help thread etc. but is referred to as article within the code.
// 
// ### Rate limiting
// 
// There is a limit of 30 requests per 30 seconds.
// 
// ### Additional resources
// 
// - [Rails tests for Articles API](https://github.com/forem/forem/blob/master/spec/requests/api/v0/articles_spec.rb)

@name("Update an article")
PUT "https://{{baseUrl}}/articles/:id"
"Content-Type": "application/json"
data('{
    "article": {
        "title": "Hello, World!",
        "published": true,
        "body_markdown": "Hello DEV, this is my first post",
        "tags": [
            "discuss",
            "help"
        ],
        "series": "Hello series",
        "canonical_url": "https://example.com/blog/hello"
    }
}')



