#!/usr/bin/env dothttp

// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-leads-list-leads)

@name("List all leads")
GET "https://{{base-url}}/accounts/me/crm/leads/"


// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-leads-retrieve-a-lead)

@name("Retrieve a lead")
GET "https://{{base-url}}/accounts/me/crm/leads/$LEAD_ID/"


// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-leads-update-a-lead)

@name("Update a lead")
PATCH "https://{{base-url}}/accounts/me/crm/leads/$LEAD_ID/"
"Content-Type": "application/json"
data('{
  "status": "string",
  "rating": "string",
  "first_name": "string",
  "last_name": "string",
  "middle_name": "string",
  "description": "string",
  "title": "string",
  "industry": "string",
  "company": "string",
  "fax": "string",
  "phone": "string",
  "email": "string",
  "raw": "string",
  "annual_revenue": 0,
  "address": "string",
  "owner": "string",
  "id": "string"
}')


// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-leads-create-a-lead)

@name("Create a lead")
POST "https://{{base-url}}/accounts/me/crm/leads/"
"Content-Type": "application/json"
data('{
  "status": "string",
  "rating": "string",
  "first_name": "string",
  "last_name": "string",
  "middle_name": "string",
  "description": "string",
  "title": "string",
  "industry": "string",
  "company": "string",
  "fax": "string",
  "phone": "string",
  "email": "string",
  "raw": "string",
  "annual_revenue": 0,
  "address": "string",
  "owner": "string",
  "id": "string"
}')


// [Link to API reference](https://developers.kloudless.com/docs/v1/crm#crm-leads-delete-a-lead)

@name("Delete a lead")
DELETE "https://{{base-url}}/accounts/me/crm/leads/$LEAD_ID/"



