#!/usr/bin/env dothttp

@name("Custom Http Header")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomHttpHeader/"


@name("Custom Http Header Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomHttpHeader/{ID}/"


@name("Describe Custom Http Header")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomHttpHeader/describe/"



