#!/usr/bin/env dothttp

@name("Return a list of items")
GET "https://{{baseUrl}}/companies({{company_id}})/items"
? "$top"= "<integer>"
? "$skip"= "<integer>"
? "$limit"= "<integer>"
? "$filter"= "<string>"
? "$expand"= "<string>,<string>"
? "$select"= "<string>,<string>"


@name("Create an item")
POST "https://{{baseUrl}}/companies({{company_id}})/items"
"Content-Type": "application/json"
data('{
    "id": "<uuid>",
    "number": "<string>",
    "displayName": "<string>",
    "type": "<string>",
    "itemCategoryId": "<uuid>",
    "itemCategoryCode": "<string>",
    "blocked": "<boolean>",
    "baseUnitOfMeasureId": "<uuid>",
    "baseUnitOfMeasure": {
        "code": "<string>",
        "displayName": "<string>",
        "symbol": "<string>",
        "unitConversion": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "picture": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "defaultDimensions": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ],
        "itemCategory": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        }
    },
    "gtin": "<string>",
    "inventory": "<decimal>",
    "unitPrice": "<decimal>",
    "priceIncludesTax": "<boolean>",
    "unitCost": "<decimal>",
    "taxGroupId": "<uuid>",
    "taxGroupCode": "<string>",
    "lastModifiedDateTime": "<dateTime>"
}')



