#!/usr/bin/env dothttp

// API to add a new cat.
@name("Add new cat")
POST "https://{{url}}/cats"
"Content-Type": "application/json"
data('{
	"name": "{{name}}",
	"breed": "{{breed}}",
	"owner": {{ownerId}}
}')


// Update details of a cat, identified by `id`
@name("Update cat details")
PUT "https://{{url}}/cats/:id"
"Content-Type": "application/json"



// Delete details of a cat, identified by `id`
@name("Delete cat details")
DELETE "https://{{url}}/cats/:id"



