#!/usr/bin/env dothttp

// {
//   "username": "lector",
//   "password": "lector",
//   "name": "Pedro Perez",
//   "tipo": "INVITADO", (puede ser ADMIN o INVITADO)
//   "email": "lector@gmail.com"
// }

@name("Crear usuario")
POST "https://167.99.3.9/user/create"
"Content-Type": "application/json"
json({
    "username": "valeria",
    "password": "valeria",
    "name": "Valeria",
    "tipo": "ADMIN"
})


@name("Listar usuarios")
GET "https://167.99.3.9/user/getAll"



@name("login")
POST "https://167.99.3.9/user/login"
"Content-Type": "application/json"
json({
    "username": "valeria",
    "password": "valeria"
})



