#!/usr/bin/env dothttp

// Retrieve [invoices](#invoice-entity). Provide count and skip for pagination.

@name("Fetch Invoices")
GET "https://{{host}}/gst/businesses/:business_id/invoices"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"
? "query"= "{{query}}"
? "count"= "{{count}}"
? "skip"= "{{skip}}"


// Retrieve an [invoice](#invoice-entity)

@name("Fetch Invoice")
GET "https://{{host}}/gst/businesses/:business_id/invoices/:invoice_id"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"


// Creates an [invoice](#invoice-entity) in your business 

@name("Post Invoice")
POST "https://{{host}}/gst/businesses/:business_id/invoices"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"
"Content-Type": "application/json"
json({
    "sgst": 0,
    "place_of_supply": "Gujarat",
    "discount": 500,
    "gst": 179.82,
    "igst": 179.82,
    "@entity": "tax_invoice",
    "invoice_date": "01/01/2020",
    "total": 1178.82,
    "balance": 1178.82,
    "supplier": {
        "scheme": "Regular",
        "contact": {
            "mobile": "1234567890",
            "email": "john@doe.com",
            "@entity": "contact"
        },
        "name": "John Doe Private Limited",
        "registered": true,
        "billing_address": {
            "area": "Vastrapur",
            "country": "India",
            "city": "Ahmedabad",
            "street": "1, ABC Lakeview Tower",
            "state": "Gujarat",
            "full_address": "1, ABC Lakeview Tower, Ahmedabad-380015 Gujarat, India",
            "type": "Billing",
            "@entity": "address"
        },
        "gstin": "24AAACQ3770E2ZZ",
        "display_name": "John",
        "@entity": "dealer"
    },
    "invoice_number": "28370",
    "document_type": "Invoice",
    "purchaser": {
        "contact": {
            "mobile": "1234567891",
            "email": "jane@doe.com",
            "@entity": "contact"
        },
        "name": "jane@doe.com",
        "registered": false,
        "billing_address": {
            "full_address": "Gujarat",
            "type": "Billing",
            "@entity": "address"
        },
        "display_name": "jane@doe.com",
        "@entity": "dealer"
    },
    "payment_status": "Unpaid",
    "is_reverse_charge": false,
    "cgst": 0,
    "transaction_type": "Sale",
    "cess": 0,
    "reference_number": "order_A927311111",
    "url": "...",
    "taxable_value": 999,
    "subtotal": 1499,
    "is_round_off": false,
    "items": [
        {
            "is_rate_inclusive_of_tax": false,
            "code": "998222",
            "quantity": 1,
            "item_type": "Services",
            "description": "Product 1",
            "discount": 500,
            "sale_price": 1499,
            "@entity": "item",
            "gst_rate": 18,
            "unit": "UNT",
            "is_exempt": false,
            "purchase_price": 1499
        }
    ],
    "is_uploaded": false,
    "is_cancelled": false,
    "status": "Unsent"
})


// Share your [invoice](#invoice-entity) to dealers by provideing list of their email

@name("Share Invoice")
POST "https://{{host}}/gst/businesses/:business_id/invoices/:invoice_id/share"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"
? "recipients"= "{{recepients}}"


// Remove [invoice](#invoice-entity) from your business

@name("Delete Invoice")
DELETE "https://{{host}}/gst/businesses/:business_id/invoices/:invoice_id"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"



