#!/usr/bin/env dothttp

@name("Create Listing Products")
POST "https://{{root}}api/v1/listing-products"
"token": "{{token}}"
"Content-Type": "application/json"
json({
    "product_cuids": [
        "126611056.2028360546"
    ]
})


@name("GET Listing Products")
GET "https://{{root}}api/v1/listing-products"
"token": "{{token}}"
"Content-Type": "application/json"
? "limit"= "10"
? "page"= "1"



@name("Update Listing producrt")
PUT "https://{{root}}api/v1/listing-products/:id"
"token": "{{token}}"
"Content-Type": "application/json"
json({
    "stock": 78
})


@name("Update Listing products (many)")
PUT "https://{{root}}api/v1/listing-products"
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVjYTQ5Zjg4NDg1ODBlMDAxNzYwYWNiYiIsImVtYWlsIjoib3BlZTEwMEB5b3BtYWlsLmNvbSIsIm9yZ19pZCI6IjVjYTQ5Zjg4NDg1ODBlMDAxNzYwYWNiYyJ9LCJpYXQiOjE1NTUzNDMyNzUsImV4cCI6MTU1NTk0ODA3NX0.6TuJtW-JLHAnInxAPlDS43BjKgAwXGP4vyphQ5nkyaI"
"Content-Type": "application/json"
json({
    "addPreFixDesc": "mo ta sau",
    "addPrefixName": "them ten sau",
    "addSuffixDesc": "mo ta truoc",
    "addSuffixName": "them ten truoc",
    "changePricePercent": "1000",
    "product_ids": [
        "5cba9da95015d5e57dd71881"
    ]
})


@name("GET Listing Product")
GET "https://{{root}}api/v1/listing-products/:id"
"token": "{{token}}"
"Content-Type": "application/json"
json({
    "product_cuids": [
        "9811668483183070",
        "98116681236629735",
        "98116681236632634",
        "98116681247000187"
    ]
})


@name("Delete Listing producrt")
DELETE "https://{{root}}api/v1/listing-products/5ca24ebac5301654bcb2317f"
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVjYTI0ZWFjYzUzMDE2NTRiY2IyMzE3YSIsImVtYWlsIjoib3BlZTAwMUB5b3BtYWlsLmNvbSIsIm9yZ19pZCI6IjVjYTI0ZWFjYzUzMDE2NTRiY2IyMzE3YiJ9LCJpYXQiOjE1NTQxNDA4NDUsImV4cCI6MTU1NDc0NTY0NX0.wsj_fhBHBphsaFNhN47HHN-mJH2mYf__pjQ0Ouc3tDs"


@name("Delete Many Listing products")
DELETE "https://{{root}}api/v1/listing-products"
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVjYTQ5Zjg4NDg1ODBlMDAxNzYwYWNiYiIsImVtYWlsIjoib3BlZTEwMEB5b3BtYWlsLmNvbSIsIm9yZ19pZCI6IjVjYTQ5Zjg4NDg1ODBlMDAxNzYwYWNiYyJ9LCJpYXQiOjE1NTUzNDMyNzUsImV4cCI6MTU1NTk0ODA3NX0.6TuJtW-JLHAnInxAPlDS43BjKgAwXGP4vyphQ5nkyaI"
? "product_ids[]"= "5cba9e7e5823e546108bd49e"
? "product_ids[]"= "5cba9e7e5823e546108bd49c"


@name("import  to shop")
POST "https://{{root}}api/v1/listing-products/import"
"token": "{{token}}"
"Content-Type": "application/json"
json({
    "listing_product_ids": [
        "5cca56a1493822001cf15011"
    ],
    "market": "shopee",
    "shopid": "102235819"
})



