#!/usr/bin/env dothttp

@name("count")
POST "https://api.dropboxapi.com/2/file_requests/count"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"


@name("create")
POST "https://api.dropboxapi.com/2/file_requests/create"
"Content-Type": "application/json"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"
data('{
    "title": "Homework submission", 
    "destination": "/File Requests/Homework", 
    "deadline": {
        "deadline": "2020-10-12T17:00:00Z", 
        "allow_late_uploads": "seven_days"
    }, 
    "open": true
}')


@name("delete")
POST "https://api.dropboxapi.com/2/file_requests/delete"
"Content-Type": "application/json"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"
data('{
    "ids": [
        "oaCAVmEyrqYnkZX9955Y", 
        "BaZmehYoXMPtaRmfTbSG"
    ]
}')


@name("delete_all_closed")
POST "https://api.dropboxapi.com/2/file_requests/delete_all_closed"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"


@name("get")
POST "https://api.dropboxapi.com/2/file_requests/get"
"Content-Type": "application/json"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"
data('{
    "id": "oaCAVmEyrqYnkZX9955Y"
}')


@name("list")
POST "https://api.dropboxapi.com/2/file_requests/list_v2"
"Content-Type": "application/json"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"
data('{
    "limit": 1000
}')


@name("list/continue")
POST "https://api.dropboxapi.com/2/file_requests/list/continue"
"Content-Type": "application/json"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"
data('{
    "cursor": "ZtkX9_EHj3x7PMkVuFIhwKYXEpwpLwyxp9vMKomUhllil9q7eWiAu"
}')


@name("update")
POST "https://api.dropboxapi.com/2/file_requests/update"
"Content-Type": "application/json"
"Dropbox-API-Path-Root": "{".tag": "namespace_id", "namespace_id": "2"}"
"Dropbox-API-Select-User": "dbmid:FDFSVF-DFSDF"
data('{
    "id": "oaCAVmEyrqYnkZX9955Y", 
    "title": "Homework submission", 
    "destination": "/File Requests/Homework", 
    "deadline": {
        ".tag": "update", 
        "deadline": "2020-10-12T17:00:00Z", 
        "allow_late_uploads": "seven_days"
    }, 
    "open": true
}')



