#!/usr/bin/env dothttp

// Get information about, edit, or delete a comment.// To post a comment, use Feed Elements Capability, Comments Items.// // https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_comments_specific.htm#connect_resources_comments_specific
@name("Comment")
PATCH "https://{{_endpoint}}/services/data/v{{version}}/chatter/comments/:COMMENT_ID"
"Content-Type": "application/json"
json({
    "body": {
        "messageSegments": [
            {
                "type": "Text",
                "text": "Editing a comment"
            }
        ]
    }
})


// Get information about, edit, or delete a comment.// // https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_comments_specific.htm#connect_resources_comments_specific
@name("Comment - Delete")
DELETE "https://{{_endpoint}}/services/data/v{{version}}/chatter/comments/:COMMENT_ID"



