#!/usr/bin/env dothttp

// Turn the country's ISO in the URL and chart label into a variable
// 
// The country names are as per ISO 3166 standards.
// Examples:
// - India - IND
// - United States of America - USA
// - Czech Republic - CZE
// 
// [List of all the ISO codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes)

@name("Add ISO variable")
GET "https://covidapi.info/api/v1/country/{{ISO}}"



// ### Postman Console
// 
// The [Postman Console](https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/#network-calls-with-the-postman-console) is a great way to debug and validate your assumptions. Every request sent via Postman is logged in this console, as well as any log statements from within your scripts. Open the Postman Console using the icon in the bottom left, hit **Send** to see what happens.
// 
// ![[screenshot console](https://i.imgur.com/uWcigTj.png)](https://i.imgur.com/uWcigTj.png)
// 
// ### Developer Tools
// 
// The [Developer Tools](https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/#devtools-console-logs) also has a console that you can use for more visibility into the HTML visualized under the **Visualize** tab. This helps us debug what's going on within the template string. Under the **Visualize** tab, right-click on the HTML rendered, and select **Inspect visualization**. Look under the **Console** tab to see your console logs.
// 
// ![[screenshot DevTools](https://i.imgur.com/1NxWTnl.png)](https://i.imgur.com/1NxWTnl.png)

@name("Troubleshooting")
GET "https://covidapi.info/api/v1/country/{{ISO}}"




