#!/usr/bin/env dothttp

// If you’re only interested in a Company’s logo, and don’t need any other data about the company, you can use our Logo API.

@name("Logo")
GET "https://logo.clearbit.com/:domain"



