#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Project Issue Type Hierarchy")
GET "https://{{baseUrl}}/rest/api/3/project/:projectId/hierarchy"



