#!/usr/bin/env dothttp

@name("Player Search")
GET "https://my.callofduty.com/api/papi-client/crm/cod/v2/platform/:platform/username/:username/search"
"X-CSRF-TOKEN": "{{TOKEN_API}}"
"Cookie": "API_CSRF_TOKEN={{TOKEN_API}}; ACT_SSO_COOKIE={{TOKEN_SSO}}; ACT_SSO_COOKIE_EXPIRY=1591153892430; atkn={{TOKEN_ATKN}};"


// Fetch anyone's Warzone profile

@name("Warzone Profile")
GET "https://my.callofduty.com/api/papi-client/stats/cod/:version/title/:game/platform/:platform/gamer/:username/profile/type/:mode"
"Cookie": "ACT_SSO_COOKIE={{TOKEN_SSO}}; ACT_SSO_COOKIE_EXPIRY=1591153892430; atkn={{TOKEN_ATKN}};"


// Fetch anyone's Warzone match history

@name("Warzone Matches")
GET "https://my.callofduty.com/api/papi-client/crm/cod/:version/title/:game/platform/:platform/gamer/:username/matches/:mode/start/:start/end/:end/details"
"Cookie": "ACT_SSO_COOKIE={{TOKEN_SSO}}; ACT_SSO_COOKIE_EXPIRY=1591153892430; atkn={{TOKEN_ATKN}};"
? "limit"= "1"


// Fetch anyone's Multiplayer profile

@name("Multiplayer Profile")
GET "https://my.callofduty.com/api/papi-client/stats/cod/:version/title/:game/platform/:platform/gamer/:username/profile/type/:mode"
"Cookie": "ACT_SSO_COOKIE={{TOKEN_SSO}}; ACT_SSO_COOKIE_EXPIRY=1591153892430; atkn={{TOKEN_ATKN}};"
? "periods"= "1616126399000,1616039999000,1615953599000,1615867199000,1615780799000,1615697999000,1615611599000"


// Fetch anyone's Multiplayer match history

@name("Multiplayer Matches")
GET "https://my.callofduty.com/api/papi-client/crm/cod/:version/title/:game/platform/:platform/gamer/:username/matches/:mode/start/:start/end/:end/details"
"Cookie": "ACT_SSO_COOKIE={{TOKEN_SSO}}; ACT_SSO_COOKIE_EXPIRY=1591153892430; atkn={{TOKEN_ATKN}};"
? "limit"= "1"


@name("Warzone Profile by UnoID")
GET "https://my.callofduty.com/api/papi-client/crm/cod/:version/title/:game/platform/:platform/uno/:username/matches/:mode/start/:start/end/:end/details"
"Cookie": "ACT_SSO_COOKIE={{TOKEN_SSO}}; ACT_SSO_COOKIE_EXPIRY=1591153892430; atkn={{TOKEN_ATKN}};"
? "limit"= "1"



