#!/usr/bin/env dothttp

// List the clients that have used this network in the timespan
@name("List The Clients That Have Used This Network In The Timespan")
GET "https://{{baseUrl}}/networks/:networkId/clients"
"X-Cisco-Meraki-API-Key": ""
? "t0"= "{{t0}}"
? "timespan"= "{{timespan}}"
? "perPage"= "{{perPage}}"
? "startingAfter"= "{{startingAfter}}"
? "endingBefore"= "{{endingBefore}}"


// Return the client associated with the given identifier. Clients can be identified by a client key or either the MAC or IP depending on whether the network uses Track-by-IP.
@name("Return The Client Associated With The Given Identifier")
GET "https://{{baseUrl}}/networks/:networkId/clients/:clientId"
"X-Cisco-Meraki-API-Key": ""



