#!/usr/bin/env dothttp

@name("Retrieve tunnel statistics all devices from device")
GET "https://{{vmanage}}/dataservice/device/tunnel/statistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve tunnel BFD statistics all devices from device")
GET "https://{{vmanage}}/dataservice/device/tunnel/bfd_statistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve tunnel IPSec statistics all devices from device")
GET "https://{{vmanage}}/dataservice/device/tunnel/ipsec_statistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve tunnel GRE keepalives information")
GET "https://{{vmanage}}/dataservice/device/tunnel/gre-keepalives"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve tunnel statistics packet duplication")
GET "https://{{vmanage}}/dataservice/device/tunnel/packet-duplicate"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve tunnel fec statistics")
GET "https://{{vmanage}}/dataservice/device/tunnel/fec_statistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"



