#!/usr/bin/env dothttp

// The `procedure` parameter is mandatory.
// 
// This means that attachment files must be added **after the creation of the procedure**. You will not be able to add attachments until you have created the signing procedure.
// 
// 
// | Param        | Description                                                                                                                                                                                                                          |
// | ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
// | `signable`   | Files that will be signed by the signers. This is the default value.                                                                                                                                                                 |
// | `attachment` | Files that will NOT be signed by the signers (e.g. annex, terms of use, flyers, commercial brochure, and so on). However, they may be consulted by the participants within the signing procedure before signing the other documents. |
// 

@name("/files")
POST "https://{{base-api-url}}/files"
"Authorization": "Bearer {{your-api-key}}"
"Content-Type": "application/json"
data('{
    "name": "Name of my attachment.pdf",
    "content": "JVBERi0xLjUKJb/3ov4KICA[...]VPRgo=",
    "procedure": "/procedures/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "type": "attachment"
}')



