#!/usr/bin/env dothttp

@name("List  Sent Transfers")
GET "https://{{domain}}/api/sent_transfers"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
? "filter[currency_code]"= "{currency_code}"
? "filter[days]"= "{days}"
? "filter[user]"= "{user_id}"
? "page[page]"= "{page_number}"
? "page[per_page]"= "{requests_per_page}"


@name("Show Sent Transfer")
GET "https://{{domain}}/api/sent_transfers/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"


// Send balance between accounts you manage.

@name("Create SentTransfer")
POST "https://{{domain}}/api/sent_transfers"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
data('{
    "type": "sent_transfers",
    "attributes": {
        "currency_code": "btc",
        "amount": 1000
    },
    "relationships": {
        "user": {
            "data": {
                "id": 1,
                "type": "users"
            }
        },
        "receiver": {
            "data": {
                "id": 2,
                "type": "users"
            }
        }
    }
}')


@name("List Received Transfers")
GET "https://{{domain}}/api/received_transfers"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"
? "filter[currency_code]"= "{currency_code}"
? "filter[days]"= "{days}"
? "filter[user]"= "{user_id}"
? "page[page]"= "{page_number}"
? "page[per_page]"= "{requests_per_page}"


@name("Show Received Transfer")
GET "https://{{domain}}/api/received_transfers/:id"
"Content-Type": "application/json"
"Authorization": "{{your_api_key}}"
"Version": "2.0"



