#!/usr/bin/env dothttp

// Delete projects  repository tags tag name

@name("Delete Projects  Repository Tags Tag Name")
DELETE "https://{{baseUrl}}/projects/:id/repository/tags/:tag_name"


// Post projects  repository tags tag name release

@name("Add Projects  Repository Tags Tag Name Release")
POST "https://{{baseUrl}}/projects/:id/repository/tags/:tag_name/release"



