#!/usr/bin/env dothttp

@name("v3/users - Create Reference User")
POST "https://api.vitalsource.com/v3/users.xml"
"X-VitalSource-API-Key": "{{vst_api_key}}"
"Content-Type": "text/xml"
data('<user>
	<reference>Postman_Test_001</reference>
	<first-name>Jose</first-name>
	<last-name>Tester</last-name>
</user>	')


@name("v3/users/:param - Read (Verify)")
GET "https://api.vitalsource.com/v3/users/{{vst_GUID}}"
"X-VitalSource-API-Key": "{{vst_api_key}}"


@name("v3/users/:param - Update")
PUT "https://api.vitalsource.com/v3/users.xml/{{vst_GUID}}"
"X-VitalSource-API-Key": "{{vst_api_key}}"
"X-VitalSource-Access-Token": "{{vst_access_token}}"
data('<user>
	<reference>Integrations_Test_001</reference>
	<first-name>Jose</first-name>
	<last-name>New_last_name</last-name>
</user>	')



