#!/usr/bin/env dothttp

@name("Quick Text Usage Share")
GET "https://{{host}}/services/data/v47.0/sobjects/QuickTextUsageShare/"


@name("Quick Text Usage Share Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/QuickTextUsageShare/{ID}/"


@name("Describe Quick Text Usage Share")
GET "https://{{host}}/services/data/v47.0/sobjects/QuickTextUsageShare/describe/"



