#!/usr/bin/env dothttp

// This endpoint creates one or more image collections (lightboxes). To add images to the collections, use `POST /v2/images/collections/{id}/items`.

@name("Create image collections")
POST "https://{{baseUrl}}/v2/images/collections"
"Content-Type": "application/json"
json({
    "name": "<string>"
})


// This endpoint lists your collections of images and their basic attributes.

@name("List image collections")
GET "https://{{baseUrl}}/v2/images/collections"
? "embed"= "<string>"
? "page"= "1"
? "per_page"= "100"


// This endpoint gets more detailed information about a collection, including its cover image and timestamps for its creation and most recent update. To get the images in collections, use `GET /v2/images/collections/{id}/items`.

@name("Get the details of image collections")
GET "https://{{baseUrl}}/v2/images/collections/:id"
? "embed"= "<string>"
? "share_code"= "<string>"


// This endpoint sets a new name for an image collection.

@name("Rename image collections")
POST "https://{{baseUrl}}/v2/images/collections/:id"
"Content-Type": "application/json"
json({
    "name": "<string>"
})


// This endpoint deletes an image collection.

@name("Delete image collections")
DELETE "https://{{baseUrl}}/v2/images/collections/:id"


// This endpoint adds one or more images to a collection by image IDs.

@name("Add images to collections")
POST "https://{{baseUrl}}/v2/images/collections/:id/items"
"Content-Type": "application/json"
json({
    "items": [
        {
            "id": "<string>",
            "added_time": "<dateTime>",
            "media_type": "<string>"
        },
        {
            "id": "<string>",
            "added_time": "<dateTime>",
            "media_type": "<string>"
        }
    ]
})


// This endpoint lists the IDs of images in a collection and the date that each was added.

@name("Get the contents of image collections")
GET "https://{{baseUrl}}/v2/images/collections/:id/items"
? "share_code"= "<string>"
? "page"= "1"
? "per_page"= "100"


// This endpoint removes one or more images from a collection.

@name("Remove images from collections")
DELETE "https://{{baseUrl}}/v2/images/collections/:id/items"
? "item_id"= "<string>"



