#!/usr/bin/env dothttp

@name("get New Shops")
GET "https://{{baseUrl}}/shops/new"
? "checkpoint_id"= "<checkpoint_id>"
? "size"= "<size>"
? "forward"= "<forward>"


@name("/shops/new")
OPTIONS "https://{{baseUrl}}/shops/new"



