#!/usr/bin/env dothttp

// <h2>Description</h2>
// This operation returns a list of backup sets for a client.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_backup_set.htm)

@name("Backup Set")
GET "https://{{ServerUrl}}/Backupset"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
? "clientId"= "2"



// <h2>Description</h2>
// This operation returns Backupset Id
// 
// <p>&nbsp;</p>
// <h2>Request Parameters</h2>
// <table class="tableintopic" border="0" cellspacing="0" cellpadding="2">
// <tbody>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">Name</p>
// </td>
// <td>
// <p class="tabletext">Description</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">clientName</p>
// </td>
// <td>
// <p class="tabletext">Name of the client(URL Encoded)</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">agent</p>
// </td>
// <td>
// <p class="tabletext">Name of the Agent(URL Encoded)</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">instanceName</p>
// </td>
// <td>
// <p class="tabletext">Instance Name(URL Encoded)</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">backupset</p>
// </td>
// <td>
// <p class="tabletext">Backupset Name(URL Encoded)</p>
// </td>
// </tr>
// <tr align="left" valign="top">
// <td>
// <p class="tabletext">subclient</p>
// </td>
// <td>
// <p class="tabletext">Subclient Name(URL Encoded)</p>
// </td>
// </tr>
// </tbody>
// </table>
// 
// [_For all Agent Names_](http://documentation.commvault.com/commvault/v11/article?p=45467.htm#o99081)

@name("Backupset Id")
GET "https://{{ServerUrl}}/GetId"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
? "clientname"= "{{clientName}}"
? "agent"= "File System"
? "backupset"= "defaultBackupSet"


// <h2>Description</h2>
// This operation returns the properties associated with a backup set.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/get_backup_set_properties.htm)

@name("Backup Set Properties")
GET "https://{{ServerUrl}}/Backupset/{{backupsetId}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"



// <h2>Description</h2>
// This operation runs a backup job for a subclient or a backup set.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/post_create_task_backup.htm)

@name("Create Task (Backup)")
POST "https://{{ServerUrl}}/CreateTask"
"Accept": "{{Accept}}"
"Content-Type": "application/json"
"Authtoken": "{{TOKEN}}"
data('{
  "taskInfo": {
    "associations": [
      {
        "applicationId": 33,
        "clientName": "{{clientName}}",
        "commCellId": 0,
        "backupsetName": "{{backupsetName}}",
        "_type_": 7,
        "appName": "File System"
      }
    ],
    "task": {
      "sequenceNumber": 10,
      "initiatedFrom": 2,
      "taskType": 1,
      "policyType": 0,
      "taskId": 0,
      "taskFlags": {
        "disabled": false
      }
    },
    "subTasks": [
      {
        "subTask": {
          "subTaskType": 2,
          "operationType": 2
        },
        "options": {
          "backupOpts": {
            "truncateLogsOnSource": false,
            "sybaseSkipFullafterLogBkp": false,
            "backupLevel": 1,
            "runIncrementalBackup": true,
            "isSpHasInLineCopy": false,
            "runSILOBackup": false,
            "doNotTruncateLog": false,
            "dataOpt": {
              "skipCatalogPhaseForSnapBackup": false,
              "followMountPoints": true,
              "enableIndexCheckPointing": false,
              "enforceTransactionLogUsage": false,
              "spaceReclamation": false,
              "skipConsistencyCheck": false,
              "createNewIndex": false,
              "verifySynthFull": false
            },
            "dataPathOpt": {
              "mediaAgent": {
                "mediaAgentId": 0
              },
              "library": {
                "libraryId": 0
              },
              "drivePool": {
                "drivePoolId": 0
              },
              "spareGroup": {
                "spareMediaGroupId": 0
              },
              "drive": {
                "driveId": 0
              }
            },
            "mediaOpt": {
              "markMediaFullOnSuccess": false,
              "numberofDays": 30,
              "startNewMedia": true,
              "retentionJobType": 2,
              "allowOtherSchedulesToUseMediaSet": true,
              "reserveResourcesBeforeScan": false
            }
          },
          "commonOpts": {
            "jobDescription": "",
            "jobRetryOpts": {
              "killRunningJobWhenTotalRunningTimeExpires": false,
              "numberOfRetries": 0,
              "enableNumberOfRetries": false,
              "runningTime": {
                "enableTotalRunningTime": false,
                "totalRunningTime": 3600
              }
            },
            "startUpOpts": {
              "startInSuspendedState": false,
              "useDefaultPriority": true,
              "priority": 166
            }
          }
        }
      }
    ]
  }
}')


// <h2>Description</h2>
// This operation runs a backup job for a backup set.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/post_backup_set_backup.htm)

@name("Backup Set Backup")
POST "https://{{ServerUrl}}/Backupset/{{backupsetId}}/action/backup"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"



// <h2>Description</h2>
// This operation creates a backup set.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/post_backup_set.htm)

@name("Backup Set")
POST "https://{{ServerUrl}}/Backupset"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
data('{
  "association": {
    "entity": [
      {
        "clientName": "{{clientName}}",
        "subclientName": "default",
        "backupsetName": "{{$guid}}",
        "instanceName": "DefaultInstanceName",
        "appName": "File System"
      }
    ]
  }
}')


// <h2>Description</h2>
// This operation updates the properties associated with a backup set.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/post_backup_set_properties.htm)

@name("Backup Set Properties")
POST "https://{{ServerUrl}}/Backupset/{{backupsetId}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"
"Content-Type": "application/json"
data('{
  "backupsetProperties": {
    "commonBackupSet": {
      "newBackupSetName": "{{backupsetName}}"
    }
  },
  "association": {
    "entity": [
      {
        "clientName": "{{clientName}}",
        "backupsetName": "{{backupsetName}}",
        "instanceName": "DefaultInstanceName",
        "appName": "File System"
      }
    ]
  }
}')


// <h2>Description</h2>
// This operation deletes a backup set.
// 
// [_More Details_](http://documentation.commvault.com/commvault/v11/article?p=features/rest_api/operations/delete_backup_set.htm)

@name("Backup Set")
DELETE "https://{{ServerUrl}}/Backupset/{{backupsetId2}}"
"Accept": "{{Accept}}"
"Authtoken": "{{TOKEN}}"




