#!/usr/bin/env dothttp

// Return an overview of the license state for an organization

@name("Return an overview of the license state for an organization")
GET "https://{{baseUrl}}/organizations/:organizationId/licenses/overview"
"X-Cisco-Meraki-API-Key": ""



