#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Suspend an app installation")
PUT "https://{{baseUrl}}/app/installations/{{installation_id}}/suspended"


@name("Unsuspend an app installation")
DELETE "https://{{baseUrl}}/app/installations/{{installation_id}}/suspended"



