#!/usr/bin/env dothttp

@name("https://{{dnac}}:{{port}}/api/v1/image/importation/site/-1?imageCategory=PHYSICAL")
GET "https://{{dnac}}/api/v1/image/importation/site/-1"
"x-auth-token": "{{token}}"
? "imageCategory"= "PHYSICAL"


@name("https://{{dnac}}:{{port}}/api/v1/image/importation?name=cat3k")
GET "https://{{dnac}}/api/v1/image/importation"
"x-auth-token": "{{token}}"
? "name"= "cat9k"


@name("https://{{apic}}:{{port}}/api/v1/network-device/ip-address/10.10.22.70")
GET "https://{{dnac}}/api/v1/network-device/ip-address/10.10.22.70"
"x-auth-token": "{{token}}"


@name("https://{{dnac}}:{{port}}/api/v1/image/distribution")
POST "https://{{dnac}}/api/v1/image/distribution"
"x-auth-token": "{{token}}"
"Content-Type": "application/json"
data('[
	{
		"deviceUuid": "{{deviceId}}",
		"imageUuid": "{{imageId}}"
	}
]')


@name("https://{{dnac}}:{{port}}/api/v1/task/{{taskId}}")
GET "https://{{dnac}}/api/v1/task/{{taskId}}"
"x-auth-token": "{{token}}"


@name("https://{{dnac}}:{{port}}/{{additionalStatusURL}}")
GET "https://{{dnac}}/{{additionalStatusURL}}"
"x-auth-token": "{{token}}"


@name("https://{{dnac}}:{{port}}/api/v1/device-image/device/{{deviceId}}/file")
GET "https://{{dnac}}/api/v1/device-image/device/{{deviceId}}/file"
"x-auth-token": "{{token}}"


@name("https://{{apic}}:{{port}}/api/v1/device-image/device/{{deviceId}}/file/cat3k_caa-rpcore.16.06.01.SPA.pkg")
DELETE "https://{{dnac}}/api/v1/device-image/device/{{deviceId}}/file/cat9k_iosxe.16.06.02s.SPA.bin"
"x-auth-token": "{{token}}"
"Content-Type": "application/json"


// Gets a task status.
// uses environment variable for the taskId

@name("https://{{dnac}}:{{port}}/api/v1/task/{{taskId}}")
GET "https://{{dnac}}/api/v1/task/{{taskId}}"
"x-auth-token": "{{token}}"


@name("https://{{dnac}}:{{port}}/api/v1/image/activation/device")
POST "https://{{dnac}}/api/v1/image/activation/device"
"x-auth-token": "{{token}}"
"Content-Type": "application/json"
data('[
	{
		"distributeIfNeeded": false,
		"activateLowerImageVersion": false,
		"imageUuidList": [
			"{{imageId}}"
		],
		"deviceUpgradeMode": "install",
		"deviceUuid": "{{deviceId}}"
	}
]')


@name("https://{{apic}}:{{port}}/api/v1/network-device/ip-address/10.10.22.69")
GET "https://{{dnac}}/api/v1/network-device/ip-address/10.10.22.69"
"x-auth-token": "{{token}}"


@name("https://{{dnac}}:{{port}}/api/v1/device-image/device?id={{deviceId}}")
GET "https://{{dnac}}/api/v1/device-image/device"
"x-auth-token": "{{token}}"
? "id"= "{{deviceId2}},{{deviceId}}"


@name("https://{{dnac}}:{{port}}/api/v1/image/task?operation=&taskType=activate&limit=50&sortOrder=des")
GET "https://{{dnac}}/api/v1/image/task"
"x-auth-token": "{{token}}"
? "taskType"= "activate"
? "limit"= "50"
? "sortOrder"= "des"


@name("https://{{dnac}}:{{port}}/api/v1/task?parentId={{deviceTaskUuid}}&sortBy=startTime&order=asc")
GET "https://{{dnac}}/api/v1/task"
"x-auth-token": "{{token}}"
? "parentId"= "{{deviceTaskUuid}}"
? "sortBy"= "startTime"
? "order"= "asc"



