#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List project collaborators")
GET "https://{{baseUrl}}/projects/{{project_id}}/collaborators"
? "affiliation"= "all"
? "per_page"= "30"
? "page"= "1"



