#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get a package for an organization")
GET "https://{{baseUrl}}/orgs/{{org}}/packages/{{package_type}}/{{package_name}}/"


@name("Delete a package for an organization")
DELETE "https://{{baseUrl}}/orgs/{{org}}/packages/{{package_type}}/{{package_name}}/"


@name("Restore a package for an organization")
POST "https://{{baseUrl}}/orgs/{{org}}/packages/{{package_type}}/{{package_name/restore}}/"
? "token"= "aliqua consectetur elit incididu"



