#!/usr/bin/env dothttp

// create User record
// - username is required

@name("Create User")
POST "https://{{host}}/users/"
"Content-Type": "application/json"
json({
    "username": "ashish"
})


// Authenticate login credentials and returns authtoken for api access.
// 
// It  calls the LOGIN_API of HealthApp where all user exists. If it returns unauthenticated then it means provided credentials are wrong.

@name("Login")
GET "https://{{host}}/login/"
basicauth("bholanath", "pochinki")
"Content-Type": "application/json"



// creates multiple reports.
// report fields are,
// - username [ report belongs to ]
// - disease [ type of disease]
// - machine [ type of machine ]
// - taken_by [ report taken by ]
// - created_at [ report submitted on ]

@name("Create Report")
POST "https://{{host}}/reports/"
"Content-Type": "application/json"
json([
    {
        "username": "ashish",
        "disease": "BS",
        "machine": "BS_CHECK_MMK",
        "taken_by": "ayush",
        "created_at": "2016-05-18T16:00:00Z"
    },
    {
        "username": "amit",
        "disease": "BP",
        "machine": "BP_PRESSURE_CHECK_MMK",
        "taken_by": "ayush",
        "created_at": "2016-05-18T16:00:00Z"
    }
])


// fetch single user information
// 
// API - /users/[username]/

@name("Fetch User")
GET "https://{{host}}/users/ashish/"
"Content-Type": "application/json"



// fetch all users

@name("Fetch Users")
GET "https://{{host}}/users/"
"Content-Type": "application/json"



// delete user and user's reports.
// 
// API - users/[username]/

@name("Delete User")
DELETE "https://{{host}}/users/ashish/"
"Content-Type": "application/json"



// show all available reports

@name("Fetch all reports")
GET "https://{{host}}/reports/"
"Content-Type": "application/json"



// fetch user's reports
// 
// API - users/[users]/reports/

@name("Fetch report for users")
GET "https://{{host}}/users/ashish/reports/"
"Content-Type": "application/json"




