#!/usr/bin/env dothttp

// Returns a list of all camera recording schedules.
@name("Returns a list of all camera recording schedules.")
GET "https://{{baseUrl}}/networks/:networkId/camera/schedules"
"X-Cisco-Meraki-API-Key": ""



