#!/usr/bin/env dothttp

@name("Get an organization membership for the authenticated user")
GET "https://{{baseUrl}}/user/memberships/orgs/:org"


@name("Update an organization membership for the authenticated user")
PATCH "https://{{baseUrl}}/user/memberships/orgs/:org"
"Content-Type": "application/json"
json({
    "state": "<string>"
})



