#!/usr/bin/env dothttp

// Get the `VehicleModel` object for the given **marketId** and **modelId**.

@name("Get the model for the given marketId and modelId.")
GET "https://{{baseUrl}}/markets/:marketId/models/:modelId"
? "fieldsFilter"= "nulla sed"
? "fieldsFilter"= "nulla ex qui"



