#!/usr/bin/env dothttp

@name("sync Orders From shop")
POST "https://{{root}}api/v1/orders/sync"
"token": "{{token}}"
"Content-Type": "application/json"
json({
    "market": "shopee",
    "target_shop": "28988716"
})


// ```
// 	target_shops: Joi.array(),
//     order_status: Joi.array(),
//     from_date: Joi.date(),
//     to_date: Joi.date(),
//     limit: Joi.number(),
//     page: Joi.number(),
//     q: Joi.string(),
// ```

@name("Get sync Orders")
GET "https://{{root}}api/v1/orders/sync"
"token": "{{token}}"
"Content-Type": "application/json"
? "order_status[]"= "CANCELLED"
? "order_status[]"= "TO_RETURN"
? "target_shops[]"= "99701102"
? "from_date"= "2019-05-16T06:45:36.267Z"
? "to_date"= "2019-07-16T06:45:36.267Z"
? "page"= "1"
? "limit"= "10"
? "q"= "19090820392E27G"


@name("Get sync Order Details")
GET "https://{{root}}api/v1/orders/sync/:id"
"token": "{{token}}"
"Content-Type": "application/json"




