#!/usr/bin/env dothttp

@name("Create Prospect")
POST "https://{{baseUrl}}/prospects"
"Authorization": "Bearer {{accessToken}}"
"Content-Type": "multipart/form-data"
files(
	("first_name", "John"),
	("last_name", "doe"),
	("phones[0][number]", "1111122222"),
	("phones[0][label]", "home"),
	("email", "john@example.com"),
	("company_name", "Teasley Lane"),
	("rep_id", " 25"),
	("referred_by_type", " customer"),
	("referred_by_id", " 25"),
	("temp_id", " 23"),
	("is_commercial", "1"),
	("call_required", "0"),
	("customer_contacts[0][first_name]", "Test"),
	("customer_contacts[0][last_name]", "Test"),
	("job[name]", "Test Job"),
	("job[day]", "0"),
	("job[hour]", "0"),
	("job[min]", "0"),
	("job[same_as_customer_address]", "0"),
	("job[same_as_customer_rep]", "0"),
	("job[city]", "Teasley Lane"),
	("job[address]", "Teasley Lane"),
	("job[state_id]", "5"),
	("job[country_id]", "1"),
	("job[address_line_1]", ""),
	("job[lat]", "123"),
	("job[long]", "321"),
	("job[alt_id]", "1"),
	("job[estimator_ids][]", "11"),
	("job[description]", "Job test 023456789"),
	("job[trades][]", "2"),
	("job[other_trade_type_description]", "xcgcg"),
	("job[call_required]", "0"),
	("job[appointment_required]", "0"),
	("job[insurance]", "0"),
	("job[duration]", "0:0:0"),
	("address[place_id]", "ChIJ31h8CwgyR4YRzmHGl02ozio"),
	("address[company_name]", "Teasley Lane"),
	("address[address]", "Teasley Lane"),
	("address[country]", "United States"),
	("address[zip]", "77375"),
	("address[country_id]", "1"),
	("address[state_id]", "5"),
	("address[lat]", "10.812973"),
	("address[long]", "-16.978363"),
	("address[same_as_customer_address]", "1"),
	("billing[place_id]", "ChIJ31h8CwgyR4YRzmHGl02ozio"),
	("billing[company_name]", "Teasley Lane"),
	("billing[address]", "Teasley Lane"),
	("billing[country]", "United States"),
	("billing[zip]", "012365"),
	("billing[country_id]", "1"),
	("billing[state_id]", "43"),
	("billing[lat]", "456"),
	("billing[long]", "789"),
	("billing[same_as_customer_address]", "1")
)



