#!/usr/bin/env dothttp

@name("List all authorizations")
GET "https://{{baseUrl}}/v1/issuing/authorizations"
"Content-Type": "application/x-www-form-urlencoded"
? "card"= "<string>"
? "cardholder"= "<string>"
? "created[gt]"= "<integer>"
? "created[gte]"= "<integer>"
? "created[lt]"= "<integer>"
? "created[lte]"= "<integer>"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "limit"= "<integer>"
? "starting_after"= "<string>"
? "status"= "<string>"


@name("Retrieve an authorization")
GET "https://{{baseUrl}}/v1/issuing/authorizations/:authorization"
"Content-Type": "application/x-www-form-urlencoded"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"


@name("Update an authorization")
POST "https://{{baseUrl}}/v1/issuing/authorizations/:authorization"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})


@name("Approve an authorization")
POST "https://{{baseUrl}}/v1/issuing/authorizations/:authorization/approve"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "amount": [
        "<integer>"
    ],
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})


@name("Decline an authorization")
POST "https://{{baseUrl}}/v1/issuing/authorizations/:authorization/decline"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})



