#!/usr/bin/env dothttp

// OAuth required scopes: OR.TestSets or OR.TestSets.Read.
// 
// Required permissions: TestSets.View.
// 
// Responses:
// 200 Return a specific Test Set identified by key
// 403 If the caller doesn't have permissions to view Test Sets
// 404 If the Test Set is not found

@name("Return a specific Test Set identified by key")
GET "https://{{baseUrl}}/odata/TestSets({{key}})"
"X-UIPATH-OrganizationUnitId": "12575632"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"


// OAuth required scopes: OR.TestSets or OR.TestSets.Write.
// 
// Required permissions: TestSets.Edit.
// 
// Responses:
// 200 Returns the updated Test Set
// 403 If the caller doesn't have permissions to update Test Sets

@name("Update an existing Test Set")
PUT "https://{{baseUrl}}/odata/TestSets({{key}})"
"X-UIPATH-OrganizationUnitId": "12575632"
"Content-Type": "application/json"
data('{
    "Name": "non proident",
    "Packages": [
        {
            "PackageIdentifier": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "VersionMask": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "TestSetId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "TestSet": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "IncludePrerelease": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModificationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModifierUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreatorUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Id": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        {
            "PackageIdentifier": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "VersionMask": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "TestSetId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "TestSet": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "IncludePrerelease": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModificationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModifierUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreatorUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Id": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        }
    ],
    "TestCases": [
        {
            "DefinitionId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "ReleaseId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "VersionNumber": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Enabled": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Definition": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "TestSetId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "TestSet": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModificationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModifierUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreatorUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Id": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        {
            "DefinitionId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "ReleaseId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "VersionNumber": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Enabled": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Definition": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "TestSetId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "TestSet": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModificationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModifierUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreatorUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Id": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        }
    ],
    "Key": "urn:uuid:37294f7a-ab1f-99ed-b4b9-304f0fd3d538",
    "Description": "proident",
    "SourceType": "ExternalTool",
    "OrganizationUnitId": -55214217,
    "EnvironmentId": -4440791,
    "Environment": {
        "Name": "laborum sunt",
        "Id": -16196540
    },
    "TestCaseCount": -18804272,
    "RobotId": 49535365,
    "InputArguments": [
        {
            "Name": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Type": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Value": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModificationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModifierUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreatorUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Id": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        },
        {
            "Name": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Type": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Value": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModificationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "LastModifierUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreationTime": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "CreatorUserId": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "Id": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        }
    ],
    "IsDeleted": true,
    "DeleterUserId": -29257379,
    "DeletionTime": "1991-05-03T15:24:27.209Z",
    "LastModificationTime": "2003-10-31T22:59:38.929Z",
    "LastModifierUserId": 39028019,
    "CreationTime": "1976-12-02T04:04:31.901Z",
    "CreatorUserId": -44108591,
    "Id": 5788179
}')


// OAuth required scopes: OR.TestSets or OR.TestSets.Write.
// 
// Required permissions: TestSets.Delete.
// 
// Responses:
// 204 The Test Set was deleted
// 403 If the caller doesn't have permissions to delete Test Sets

@name("Delete a test set")
DELETE "https://{{baseUrl}}/odata/TestSets({{key}})"
"X-UIPATH-OrganizationUnitId": "12575632"



