#!/usr/bin/env dothttp

@name("Super Admin Add")
POST "http://54.154.59.231/admin/api/v1/users/"
"Content-Type": "application/json"
data('{
    "firstname": "Admin",
    "lastname": "MD",
    "phone": "+448989898989",
    "email": "adminmd@test.com",
    "password": "123456"
    
}')



