#!/usr/bin/env dothttp

// #### Message event payload schema
// 
// |**Field**|**Description**|
// |--|--|
// |**trigger**|"message:appUser", or "message:appMaker"
// |**app**|A nested object representing the conversations app associated with the event. See the truncated app schema below for details.|
// |**messages**|An array of objects representing the messages associated with the event. See the message schema below for details.|
// |**appUser**|A nested object representing the appUser associated with the event. See the truncated appUser schema below for details.|
// |**conversation**|A nested object representing the conversation associated with the event. See the truncated conversation schema below for details.|
// |**recentNotifications** optional|An array of objects representing the contextual notifications associated with the event. See the message schema below for details.|
// |**client** optional|A nested object representing the client associated with the message. This field is only included when the message has an associated client, the trigger is "message:appUser" and includeClient on webhook settings is set to true. See the client schema for details.|
// |**version**|The API version used to create the webhook. See API version for details.|

@name("message:appUser ")
POST "https://{{yourAPI}}/"
"Content-Type": "application/json"
"x-api-key": "CNXZYblQpmhmCuJtm61vMHMhW_WAbqEgsXYq7FNAwcbMb9LN26phXpLaxIQSq_nnkBICGDD3Zcls7eE9gExxaQ"
json({
    "trigger": "message:appUser",
    "app": {
        "_id": "5dbff7692b527f00100a014d"
    },
    "version": "v1.1",
    "messages": [
        {
            "type": "text",
            "text": "Hello good morning ðŸŒž",
            "role": "appUser",
            "received": 1579582098.065,
            "name": "Jon Doe",
            "authorId": "169f7f16eedf7ddfca30f294",
            "_id": "5e268292223904000dd5e4d0",
            "source": {
                "originalMessageId": "ABEGkYYGglWEAhD0r80U_CwSHmioDDbgHckc",
                "originalMessageTimestamp": 1579582097,
                "type": "whatsapp",
                "integrationId": "5dc3fc8f9380390011bb2305"
            }
        }
    ],
    "appUser": {
        "_id": "169f7f16rfaf7ddfca30f294",
        "conversationStarted": true,
        "givenName": "Jon Doe",
        "signedUpAt": "2019-12-13T05:03:52.690Z",
        "properties": {}
    },
    "conversation": {
        "_id": "8c2169c2c38ef816de7ebd65"
    }
})



