#!/usr/bin/env dothttp

// Add a target group//  #### Body Parameters // **Parameter**|**Type**|**Description** //  :-------------: |:-------------: |:-------------: // name| string| The name of this target group// scope| string| The scope and tag options of the target group. Comma separated values beginning with one of withAny, withAll, withoutAny, withoutAll, all, none, followed by tags. Default to none if empty.
@name("Add A Target Group")
POST "https://{{baseUrl}}/networks/:networkId/sm/targetGroups"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "name": "<string>",
    "scope": "<string>"
}')


// Delete a target group from a network
@name("Delete A Target Group From A Network")
DELETE "https://{{baseUrl}}/networks/:networkId/sm/targetGroups/:targetGroupId"
"X-Cisco-Meraki-API-Key": ""


// List the target groups in this network
@name("List The Target Groups In This Network")
GET "https://{{baseUrl}}/networks/:networkId/sm/targetGroups"
"X-Cisco-Meraki-API-Key": ""
? "withDetails"= "{{withDetails}}"


// Return a target group
@name("Return A Target Group")
GET "https://{{baseUrl}}/networks/:networkId/sm/targetGroups/:targetGroupId"
"X-Cisco-Meraki-API-Key": ""
? "withDetails"= "{{withDetails}}"


// Update a target group//  #### Body Parameters // **Parameter**|**Type**|**Description** //  :-------------: |:-------------: |:-------------: // name| string| The name of this target group// scope| string| The scope and tag options of the target group. Comma separated values beginning with one of withAny, withAll, withoutAny, withoutAll, all, none, followed by tags. Default to none if empty.
@name("Update A Target Group")
PUT "https://{{baseUrl}}/networks/:networkId/sm/targetGroups/:targetGroupId"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "name": "<string>",
    "scope": "<string>"
}')



