#!/usr/bin/env dothttp

// Get the current's user data with:
// 1. Store detailed data.
// 2. User's role.
// 3. User's permissions.
// 
// No need to pass any parameter, the system will recognize the user via X-MANAGER-Token. 

@name("Profile")
GET "https://{{api_url}}/managers/account/profile"
"Accept": "{{Accept}}"
"Authorization": "{{Authorization}}"
"Accept-Language": "{{Accept-Language}}"
"User-Agent": "{{User-Agent}}"
"X-MANAGER-TOKEN": "{{X-MANAGER-TOKEN}}"


// Get a manager token with a long lifespan (6 monthes), since regular manager tokens have a short lifespan and considered unreliable for a system to system integration.

@name("Third Party Access Token")
GET "https://{{api_url}}/managers/account/third-parties/authorization-access-token"
"Accept": "{{Accept}}"
"Authorization": "{{Authorization}}"
"Accept-Language": "{{Accept-Language}}"
"User-Agent": "{{User-Agent}}"
"X-MANAGER-TOKEN": "{{X-MANAGER-TOKEN}}"



