#!/usr/bin/env dothttp

// Retrieves a list of assets for a theme. Listing theme assets returns only metadata about each asset. To get an asset's contents, you need to <a href="#show">retrieve the asset individually</a>.

@name("Retrieves a list of assets for a theme")
GET "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/themes/{{theme_id}}/assets.json"
"Content-Type": "application/json"


// <p>Retrieves a single asset for a theme by its key.</p> <p>To retrieve a single asset, include <code>asset[key]=#{asset_key}</code> as a request parameter. For example, to retrieve the asset with a key of <code>templates/index.liquid</code>, the request might be <code>/admin/themes/828155753/assets.json?asset[key]=templates/index.liquid</code>.</p> <p>For more information on the <code>key</code> property, see <a href="#key-property"><em>Asset properties</em></a>.</p>

@name("Retrieves a single asset for a theme")
GET "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/themes/{{theme_id}}/assets.json"
"Content-Type": "application/json"


// <p>Creates or updates an asset for a theme.</p> <p>In the PUT request, you can include the <code>src</code> or <code>source_key</code> property to create the asset from an existing file.</p>

@name("Creates or updates an asset for a theme")
PUT "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/themes/{{theme_id}}/assets.json"
"Content-Type": "application/json"



// Deletes an asset from a theme.

@name("Deletes an asset from a theme")
DELETE "https://{{store_name}}.myshopify.com/admin/api/{{api_version}}/themes/{{theme_id}}/assets.json"
"Content-Type": "application/json"




