#!/usr/bin/env dothttp

@name("Collaboration Group Record")
GET "https://{{host}}/services/data/v47.0/sobjects/CollaborationGroupRecord/"


@name("Collaboration Group Record Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/CollaborationGroupRecord/{ID}/"


@name("Describe Collaboration Group Record")
GET "https://{{host}}/services/data/v47.0/sobjects/CollaborationGroupRecord/describe/"



