#!/usr/bin/env dothttp

// Returns a string based token.
// 
// **Returns**
// 
// ```json
// {
// 	"id":1,
// 	"result":"65e60c5a93b2f2c05e61681bf5e94b49",
// 	"error":null
// }
// ```

@name("login")
GET "https://{{HOST}}/auth"
"Content-Type": "application/json"
data('{
  "id": 1,
  "method": "login",
  "params": [
    "root",
    "ZXasqw12"
  ]
}')



