#!/usr/bin/env dothttp

// # Register Assets
// 
// Registers a list of assets that a customer has stored in their system.
// 
// ##  Quickstart
// 
// You'll need an API key and a [Resource Owner Grant](http://developers.gettyimages.com/en/authorization-faq.html) access token to use this resource.
// Please see our [Getting Started](http://developers.gettyimages.com/en/getting-started.html) page for more information on how to sign up for an API key. 
// 
// _Note_: In the event of a successful query (response code 200) there will be nothi

@name("Register Assets")
POST "https://{{baseUrl}}/v3/asset-registrations"


// Use this endpoint to retrieve collections associated with your Getty Images account. To browse available collections see our [Image collections page]( http://www.gettyimages.com/creative-images/collections).
// 
// You'll need an API key and access token to use this resource. Please see our [Getting Started](http://developers.gettyimages.com/en/getting-started.html) page for more information on how to sign up for an API key.

@name("Get Collections")
GET "https://{{baseUrl}}/v3/collections"
"Authorization": "<>"
"Accept": "<>"


// Returns a list of country objects that contains country name, two letter ISO abbreviation and three letter ISO abbreviation.
// 
// You'll need an API key and access token to use this resource. Please see our [Getting Started](http://developers.gettyimages.com/en/getting-started.html) page for more information on how to sign up for an API key.

@name("Get Countries")
GET "https://{{baseUrl}}/v3/countries"
"Accept": "<>"
"Authorization": "<>"


// This endpoint returns all products available to the username used during authentication. As such, this endpoint requires the use of
// a fully authorized access_token. The product data can then be used as search filters, restricting results to images from a specific product.
// 
// You'll need an API key and access token to use this resource. Please see our [Getting Started](http://developers.gettyimages.com/en/getting-started.html)
// page for more information on how to sign up for an API key.

@name("Get Products")
GET "https://{{baseUrl}}/v3/products"
"Authorization": "<>"
"Accept": "<>"
? "fields"= "<>"


// This endpoint returns a list of all assets purchased on gettyimages.com by the username used for authentication. 
// Use of this endpoint requires configuration changes to your API key. 
// Please contact [developersupport@gettyimages.com](mailto:developersupport@gettyimages.com) to learn more.
// 
// You'll need an API key and access token to use this resource. Please see our [Getting Started](http://developers.gettyimages.com/en/getting-started.html)
// page for more information on how to sign up for an

@name("Get Purchased Images")
GET "https://{{baseUrl}}/v3/purchased-assets"
"Authorization": "<>"
"Accept": "<>"
? "end_date"= "<>"
? "page"= "<>"
? "page_size"= "<>"
? "start_date"= "<get>"


// This endpoint returns a list of all images purchased on gettyimages.com by the username used for authentication.
// Use of this endpoint requires configuration changes to your API key. Please contact [developersupport@gettyimages.com](mailto:developersupport@gettyimages.com)
// to learn more.
// 
// You'll need an API key and access token to use this resource. Please see our [Getting Started](http://developers.gettyimages.com/en/getting-started.html)
// page for more information on how to sign up for an A

@name("Get Previously Purchased Images")
GET "https://{{baseUrl}}/v3/purchased-images"
"Authorization": "<>"
"Accept": "<>"
? "end_date"= "<>"
? "page"= "<>"
? "page_size"= "<>"
? "start_date"= "<get>"


// # Report Usage
// 
// Use this endpoint to report the usages of a set of assets. The count of assets submitted in a single batch to this endpoint is limited to 1000. Note that all asset Ids specified must be valid or the operation will fail causing no usages to be recorded. In this case, you will need to remove the invalid asset Ids from the query request and re-submit the query.
// 
// ##  Quickstart
// 
// You'll need an API key and a [Resource Owner Grant](http://developers.gettyimages.com/en/authorizati

@name("Reports Usage Batches")
PUT "https://{{baseUrl}}/v3/usage-batches/:id"
"Authorization": "<>"



