#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get a gist comment")
GET "https://{{baseUrl}}/gists/{{gist_id}}/comments/{{comment_id}}/"


@name("Update a gist comment")
PATCH "https://{{baseUrl}}/gists/{{gist_id}}/comments/{{comment_id}}/"
"Content-Type": "application/json"
json({
    "body": "Body of the attachment"
})


@name("Delete a gist comment")
DELETE "https://{{baseUrl}}/gists/{{gist_id}}/comments/{{comment_id}}/"



