#!/usr/bin/env dothttp

@name("Get certs information")
GET "https://{{keycloak_url}}/realms/{{realm}}/protocol/openid-connect/certs"


// Get configuration information

@name("Well known configuration")
GET "https://{{keycloak_url}}/realms/{{realm}}/.well-known/openid-configuration"
"Content-Type": "application/x-www-form-urlencoded"



