#!/usr/bin/env dothttp

// To revoke access to a shared record that was shared to users.
@name("Leads")
DELETE "https://{{api-domain}}/crm/v2.1/Leads/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Accounts")
DELETE "https://{{api-domain}}/crm/v2.1/Accounts/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Contacts")
DELETE "https://{{api-domain}}/crm/v2.1/Contacts/{{record_id}}/actions/share"



// To revoke access to a shared record that was shared to users.
@name("Deals")
DELETE "https://{{api-domain}}/crm/v2.1/Deals/{{record_id}}/actions/share"



// To revoke access to a shared record that was shared to users.
@name("Campaigns")
DELETE "https://{{api-domain}}/crm/v2.1/Campaigns/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Cases")
DELETE "https://{{api-domain}}/crm/v2.1/Cases/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Solutions")
DELETE "https://{{api-domain}}/crm/v2.1/Solutions/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Products")
DELETE "https://{{api-domain}}/crm/v2.1/Products/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Vendors")
DELETE "https://{{api-domain}}/crm/v2.1/Vendors/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Price Books")
DELETE "https://{{api-domain}}/crm/v2.1/Price_Books/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Quotes")
DELETE "https://{{api-domain}}/crm/v2.1/Quotes/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Sales Orders")
DELETE "https://{{api-domain}}/crm/v2.1/Sales_Orders/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Purchase Orders")
DELETE "https://{{api-domain}}/crm/v2.1/Purchase_Orders/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Invoices")
DELETE "https://{{api-domain}}/crm/v2.1/Invoices/{{record_id}}/actions/share"


// To revoke access to a shared record that was shared to users.
@name("Custom")
DELETE "https://{{api-domain}}/crm/v2.1/{{custom_module_api_name}}/{{record_id}}/actions/share"



