#!/usr/bin/env dothttp

// 获得所有的摄影打印服务

@name("getAllShootAndPrint")
GET "https://{{url}}/api/v1/shootandprint/all"


// 获得所有的摄影打印服务，分页显示

@name("getPageShootAndPrint")
GET "https://{{url}}/api/v1/shootandprint/split"
? "page"= "1"


// 获得一个id，摄影打印服务
// 
// **参数**
// - id: 表示`ShootAndPrint`的主键（需要加在请求链接里）

@name("getOneShootAndPrint")
GET "https://{{url}}/api/v1/shootandprint/id"


// 新增一个id，摄影打印服务

@name("creatOneShootAndPrint")
POST "https://{{url}}/api/v1/shootandprint"
files(
	("name", "橘子摄影"),
	("imageURL", "/image/studio/jzsy.jpeg"),
	("introduce", "清新/唯美/浪漫/大气/自然，缔造桔子新风尚！"),
	("content", "提供外景婚纱摄影，个性写真的专业摄影工作室。拥有强大的摄影工作团队，是由有活力、时尚的年轻摄影师组成"),
	("time", "周一到周五 9:00~11:00/14:00~17:00"),
	("site", "静安区威海路229号恒利国际大厦裙楼3楼"),
	("phone", "400-168-1314")
)


// 更新摄影打印服务
// 
// **参数**
// - id: 表示`ShootAndPrint`的主键（需要加在请求链接里）

@name("udpateOneShootAndPrint")
PATCH "https://{{url}}/api/v1/shootandprint/id"
files(
	("name", ""),
	("imageURL", ""),
	("introduce", ""),
	("content", ""),
	("time", ""),
	("site", ""),
	("phone", ""),
	("qq", ""),
	("wechat", "")
)


// 删除一个id，摄影打印服务
// 
// **参数**
// - id: 表示`ShootAndPrint`的主键（需要加在请求链接里）

@name("deleteOneShootAndPrint")
DELETE "https://{{url}}/api/v1/shootandprint/7"



// 搜索摄影打印服务
// 
// **参数**
// - term: 表示搜索的项目（site）

@name("searchShootAndPrint")
GET "https://{{url}}/api/v1/shootandprint/search"


// 获得所有的摄影打印服务（按照摄影打印服务发布的时间排列）

@name("getAllShootAndPrintSortByTime")
GET "https://{{url}}/api/v1/shootandprint/sort"



