#!/usr/bin/env dothttp

// Boards are where you collect, curate, collaborate on and manage photo and video assets in one place. More information on the [Boards FAQ](http://www.gettyimages.com/boards/faq).
// Use this endpoint to remove a set of assets from a board.
// 
// You'll need an API key and a [Resource Owner Grant](http://developers.gettyimages.com/en/authorization-faq.html) access token to use this resource. Please see our [Getting Started](http://developers.gettyimages.com/en/getting-started.html) page for more inform

@name("Remove Assets From Board")
DELETE "https://{{baseUrl}}/v3/boards/:board_id/assets"
"Authorization": "<>"
"Accept": "<>"
? "asset_ids"= "<get>"


// Boards are where you collect, curate, collaborate on and manage photo and video assets in one place. More information on the [Boards FAQ](http://www.gettyimages.com/boards/faq). Use this endpoint to remove an asset from a board.
// 
// You'll need an API key and a [Resource Owner Grant](http://developers.gettyimages.com/en/authorization-faq.html) access token to use this resource. Please see our [Getting Started](http://developers.gettyimages.com/en/getting-started.html) page for more information on

@name("Remove an asset from a board")
DELETE "https://{{baseUrl}}/v3/boards/:board_id/assets/:asset_id"
"Authorization": "<>"
"Accept": "<>"



