#!/usr/bin/env dothttp

@name("/shops")
GET "https://{{baseUrl}}/shops"
? "checkpoint_id"= "<checkpoint_id>"
? "size"= "<size>"
? "forward"= "<forward>"


@name("filter Shops")
POST "https://{{baseUrl}}/shops"
"Content-Type": "application/json"
? "checkpoint_id"= "<checkpoint_id>"
? "forward"= "laborum"
? "size"= "laborum"
? "id_client"= "{{idClient}}"
data('{
    "sort_by": "views",
    "mall_array": [
        //arreglo de mall
    ],
    "filter_level": "categorias, subcategorias o estilos",
    "filter_identities": [

    ]
}')


@name("/shops")
OPTIONS "https://{{baseUrl}}/shops"



