#!/usr/bin/env dothttp

// Send the data you want to visualize in the **Body** as **raw** `JSON` then pass it into the visualizer template via the `data` object in the response.// // * Open the request **Tests** to see how Postman builds the response JSON into the visualizer template.// // Try tweaking it by changing to a 'line' or 'pie' chart, then send different types of data and visualize them your own way!
@name("Basic visualizer chart demo")
POST "https://postman-echo.com/post"
json({
    "names": [
        "Dorothea",
        "Rose",
        "Blanche",
        "Sophia"
    ],
    "nums": [
        1,
        3,
        2,
        4
    ]
})



