#!/usr/bin/env dothttp

// OAuth required scopes: OR.Webhooks or OR.Webhooks.Read.
// 
// Required permissions: Webhooks.View.

@name("Gets a single webhook")
GET "https://{{baseUrl}}/odata/Webhooks({{key}})"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"


// OAuth required scopes: OR.Webhooks or OR.Webhooks.Write.
// 
// Required permissions: Webhooks.Edit.

@name("Update an existing webhook subscription")
PUT "https://{{baseUrl}}/odata/Webhooks({{key}})"
"Content-Type": "application/json"
json({
    "AllowInsecureSsl": true,
    "Enabled": false,
    "SubscribeToAllEvents": false,
    "Url": "http://kYDVvONPBLJGEl.zbgqMZ1cplfwaSLTaU8m1N+nvJnFDASZwNiVbsTv1",
    "Secret": "Excepteur fugiat ut deserunt",
    "Events": [
        {
            "EventType": "dolor mollit do"
        },
        {
            "EventType": "occaecat labore nulla tempor ipsum"
        }
    ],
    "Id": 33416940
})


// OAuth required scopes: OR.Webhooks or OR.Webhooks.Write.
// 
// Required permissions: Webhooks.Edit.

@name("Patches a webhook")
PATCH "https://{{baseUrl}}/odata/Webhooks({{key}})"
"Content-Type": "application/json"
json({
    "AllowInsecureSsl": true,
    "Enabled": false,
    "SubscribeToAllEvents": false,
    "Url": "http://kYDVvONPBLJGEl.zbgqMZ1cplfwaSLTaU8m1N+nvJnFDASZwNiVbsTv1",
    "Secret": "Excepteur fugiat ut deserunt",
    "Events": [
        {
            "EventType": "dolor mollit do"
        },
        {
            "EventType": "occaecat labore nulla tempor ipsum"
        }
    ],
    "Id": 33416940
})


// OAuth required scopes: OR.Webhooks or OR.Webhooks.Write.
// 
// Required permissions: Webhooks.Delete.

@name("Delete a webhook subscription")
DELETE "https://{{baseUrl}}/odata/Webhooks({{key}})"


// OAuth required scopes: OR.Webhooks or OR.Webhooks.Write.
// 
// Required permissions: Webhooks.View.

@name("Sends a Ping request to webhook endpoint.
Used for testing connectivity and availability of target URL")
POST "https://{{baseUrl}}/odata/Webhooks({{key}})/UiPath.Server.Configuration.OData.Ping"
? "$expand"= "esse sit qui"
? "$select"= "esse sit qui"



