#!/usr/bin/env dothttp

@name("Get  Table Query Select")
POST "https://{{sb_client}}.salesboard.biz/v1/assets/tables/query-select"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"
json({
    "tableName": "table",
    "columns": [],
    "whereParsed": "",
    "size": 100,
    "from": 0
})


@name("Get  Table Query Select by ID")
POST "https://{{sb_client}}.salesboard.biz/v1/assets/tables/query-select-by-id"
"XREQUESTEDWITH": "WebAppHttpRequest"
"cookie": "PHPSESSID={{sb_token}}"
json({
    "tableId": 7,
    "columns": [
        "*"
    ],
    "where": "",
    "whereParsed": "",
    "size": 100,
    "from": 0
})



