#!/usr/bin/env dothttp

// [Link to API reference](https://developers.kloudless.com/docs/v1/storage#links-retrieve-a-link)

@name("Get information for a specific link")
GET "https://{{base-url}}/accounts/me/storage/links/$LINK_ID/"


// [Link to our API reference](https://developers.kloudless.com/api-explorer/#!/accounts/storage_folders_links_read)

@name("Links to the folder at the service level")
GET "https://{{base-url}}/accounts/me/storage/folders/$FOLDER_ID/links/"


// [Link to our API reference](https://developers.kloudless.com/api-explorer/#!/accounts/storage_files_links_read)

@name("Links to the file at the service level")
GET "https://{{base-url}}/accounts/me/storage/files/$FILE_ID/links/"


@name("Links to the folder at the service-level")
GET "https://{{base-url}}/accounts/me/storage/folders/$FOLDER_ID/links/"


// [Link to our API reference](https://developers.kloudless.com/docs/v1/storage#links-list-links)

@name("List links created for this account")
GET "https://{{base-url}}/accounts/me/storage/links"


// [Link to API reference](https://developers.kloudless.com/docs/v1/storage#links-create-a-link)

@name("Create a link for this account")
POST "https://{{base-url}}/accounts/me/storage/links/"
"Content-Type": "application/json"
json({
    "active": true,
    "password": "string",
    "expiration": "string",
    "file_id": "string",
    "direct": true
})


// [Link to API reference](https://developers.kloudless.com/docs/v1/storage#links-update-a-link)

@name("Update a specific link")
PATCH "https://{{base-url}}/accounts/me/storage/links/$LINK_ID/"
"Content-Type": "application/json"


// [Link to API reference](https://developers.kloudless.com/docs/v1/storage#links-delete-a-link)

@name("Links to the file at the service-level")
DELETE "https://{{base-url}}/accounts/me/storage/files/$FILE_ID/links/"



// [Link to API reference](https://developers.kloudless.com/docs/v1/storage#links-delete-a-link)

@name("Delete a specific link")
DELETE "https://{{base-url}}/accounts/me/storage/links/$LINK_ID/"



@name("Links to the folder at the service-level")
DELETE "https://{{base-url}}/accounts/me/storage/folders/$FOLDER_ID/links/"




