#!/usr/bin/env dothttp

@name("List all open reviews")
GET "https://{{baseUrl}}/v1/reviews"
"Content-Type": "application/x-www-form-urlencoded"
? "created[gt]"= "<integer>"
? "created[gte]"= "<integer>"
? "created[lt]"= "<integer>"
? "created[lte]"= "<integer>"
? "ending_before"= "<string>"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"
? "limit"= "<integer>"
? "starting_after"= "<string>"


@name("Retrieve a review")
GET "https://{{baseUrl}}/v1/reviews/:review"
"Content-Type": "application/x-www-form-urlencoded"
? "expand[0]"= "<string>"
? "expand[1]"= "<string>"


@name("Approve a review")
POST "https://{{baseUrl}}/v1/reviews/:review/approve"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "expand[0]": [
        "<string>"
    ],
    "expand[1]": [
        "<string>"
    ]
})



