#!/usr/bin/env dothttp

@name("Retrieve Notification Events by Date Range")
GET "https://connect.creditsafe.com/v1/monitoring/notificationEvents"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"
? "startDate"= "2018-01-01T14:15:55Z"
? "endDate"= "2019-05-06T23:00:00Z"
? "page"= "0"
? "pageSize"= "1000"


@name("Retrieve Notification Events for a Company")
GET "https://connect.creditsafe.com/v1/monitoring/portfolios/{portfolioId}/companies/{id}/notificationEvents"
"Authorization": "Bearer {{connectAuthToken}}"
"Content-Type": "application/json"



