#!/usr/bin/env dothttp

// Requirement: username and password.
// Note: As this is a private API, this is tokenless, oauthless, etc.

@name("Login")
POST "https://api.ecoledirecte.com/v3/login.awp"
data('data={
	"identifiant": "{{username}}",
	"motdepasse": "{{password}}"
}')


// Query requirements: Account Type, Account ID
// Body Requirements: token, start_date, end_date and hole schedule

@name("Work Schedule")
POST "https://api.ecoledirecte.com/v3/{{account_type}}/{{id}}/emploidutemps.awp"
? "verbe"= "get"
data('data={
    "dateDebut": "2020-06-05",
    "dateFin": "2020-06-05",
    "avecTrous": false,
    "token": "{{token}}"
}')


// Requirements: token and ID

@name("User Settings")
POST "https://api.ecoledirecte.com/v3/logins/{{id_login}}.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Requirements: token, id and data to update

@name("Update User Settings")
POST "https://api.ecoledirecte.com/v3/logins/{{id_login}}.awp"
? "verbe"= "put"
data('data={
    "id": 1455076,
        "identifiant": "kmxslr",
        "email": "contact@zeroside.co",
        "portable": "",
        "autreQuestionSecrete": "autre",
        "questionSecrete": "Autre",
        "reponse": "ertua",
        "niveauMDPAutorise": 2,
    "nouveauMotDePasse": "Hm99jQ51",
    "confirmationMotDePasse": "Hm99jQ51",
    "token": "{{token}}"
}')


// Requirements: Path and token

@name("Individual Settings")
POST "https://api.ecoledirecte.com/v3/parametreIndividuel.awp"
? "verbe"= "get"
data('data={
    "path": "{{path}}",
    "token": "{{token}}"
}')


@name("Update Individual Settings")
POST "https://api.ecoledirecte.com/v3/parametreIndividuel.awp"
? "verbe"= "put"
data('data={
    "path": "{{path}}",
    "value": true,
    "token": "{{token}}"
}')


// Requirements: Token

@name("Classroom Activity")
POST "https://api.ecoledirecte.com/v3/Classes/94/viedelaclasse.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Query requirements: ID
// Body requirements: token

@name("School Life")
POST "https://api.ecoledirecte.com/v3/eleves/{{id}}/viescolaire.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Query requirements: ID
// Body requirements: token

@name("Grades")
POST "https://api.ecoledirecte.com/v3/eleves/{{id}}/notes.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Query requirements: ID
// Body requirements: token

@name("Homework List")
POST "https://api.ecoledirecte.com/v3/Eleves/{{id}}/cahierdetexte.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Query requirements: ID
// Body requirements: token

@name("Digital Books")
POST "https://api.ecoledirecte.com/v3/Eleves/{{id}}/manuelsNumeriques.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Query requirements: id
// Body requirements: token

@name("MCQ List")
POST "https://api.ecoledirecte.com/v3/eleves/{{id}}/qcms/0/associations.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Body requirements: token

@name("List of documents")
POST "https://api.ecoledirecte.com/v3/elevesDocuments.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Query requirements: account_type, id
// Body requirements: token

@name("Timeline with post-it")
POST "https://api.ecoledirecte.com/v3/{{account_type}}/{{id}}/timelineAccueilCommun.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Requirements: token
// Note: This is located on professors API (P)

@name("Levels list")
POST "https://apip.ecoledirecte.com/v3/niveauxListe.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')


// Query requirements: id
// Body requirements: token

@name("Get professor schedule")
POST "https://apip.ecoledirecte.com/v3/enseignant/{{id}}/appel/horaires.awp"
? "verbe"= "get"
data('data={
	"token": "{{token}}"
}')



