#!/usr/bin/env dothttp

// 
// Provides cumulative receipt totals by entity type, over a two year cycle. Totals are adjusted to avoid double counting.
// 
// This is [the sql](https://github.com/fecgov/openFEC/blob/develop/data/migrations/V41__large_aggregates.sql) that creates these calculations.

@name("/totals/by_entity/")
GET "https://{{baseUrl}}/totals/by_entity/"
? "per_page"= "20"
? "sort"= "end_date"
? "cycle"= "<integer>"
? "sort_null_only"= "false"
? "api_key"= "DEMO_KEY"
? "page"= "1"
? "sort_hide_null"= "false"
? "sort_nulls_last"= "false"


// 
// This endpoint provides information about a committee's Form 3, Form 3X, or Form 3P financial reports,
// which are aggregated by two-year period. We refer to two-year periods as a `cycle`.
// 
// The cycle is named after the even-numbered year and includes the year before it. To obtain
// totals from 2013 and 2014, you would use 2014. In odd-numbered years, the current cycle
// is the next year — for example, in 2015, the current cycle is 2016.
// 
// For presidential and Senate candidates, multiple two-year cycles exist between elections.
// 
// Parameter `full_election` is replaced by `election_full`. Please use `election_full` instead.

@name("/totals/:committee_type/")
GET "https://{{baseUrl}}/totals/:committee_type/"
? "per_page"= "20"
? "sort"= "-cycle"
? "sort_nulls_last"= "false"
? "committee_designation"= "<string>"
? "committee_designation"= "<string>"
? "api_key"= "DEMO_KEY"
? "cycle"= "<integer>"
? "cycle"= "<integer>"
? "sort_null_only"= "false"
? "committee_id"= "<string>"
? "page"= "1"
? "sort_hide_null"= "false"



