#!/usr/bin/env dothttp

// The production API endpoints for the public version of this API are at `https://api.us.socrata.com/api/catalog/v1` for domains in North America and `https://api.eu.socrata.com/api/catalog/v1` for all other domains. For example, to query for datasets categorized as 'Public Safety', you could use the following query:
// 
// `http://api.us.socrata.com/api/catalog/v1?categories=public%20safety`
// 
// Read the documentation [here](https://socratadiscovery.docs.apiary.io/#).

@name("Discovery")
GET "http://api.us.socrata.com/api/catalog/v1"
"": "bi"
? "categories"= "public safety"



