#!/usr/bin/env dothttp

@name("GetCountriesAvailable")
POST "http://www.holidaywebservice.com/continents"
"Content-Type": "text/xml"
data('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hol="http://www.holidaywebservice.com/HolidayService_v2/">
   <soapenv:Header/>
   <soapenv:Body>
      <hol:GetCountriesAvailable/>
   </soapenv:Body>
</soapenv:Envelope>')



