#!/usr/bin/env dothttp

# imported from http://localhost:8000/jira-reference.postman_collection.json

@name("Get Remote Issue Link By Id")
GET "https://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/remotelink/:linkId"


@name("Update Remote Issue Link By Id")
PUT "https://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/remotelink/:linkId"
"Content-Type": "application/json"
data('{
    "object": {
        "title": "<string>",
        "url": "<string>",
        "summary": "<string>",
        "icon": {
            "url16x16": "<string>",
            "title": "<string>",
            "link": "<string>"
        },
        "status": {
            "resolved": "<boolean>",
            "icon": {
                "url16x16": "<string>",
                "title": "<string>",
                "link": "<string>"
            }
        }
    },
    "globalId": "<string>",
    "application": {
        "type": "<string>",
        "name": "<string>"
    },
    "relationship": "<string>"
}')


@name("Delete Remote Issue Link By Id")
DELETE "https://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey/remotelink/:linkId"



