#!/usr/bin/env dothttp

// Changes the order of issue types in an issue type scheme.
// 
// The request body parameters must meet the following requirements:
// 
//  *  all of the issue types must belong to the issue type scheme.
//  *  either `after` or `position` must be provided.
//  *  the issue type in `after` must not be in the issue type list.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Change Order Of Issue Types")
PUT "https://{{baseUrl}}/rest/api/3/issuetypescheme/:issueTypeSchemeId/issuetype/move"
"Content-Type": "application/json"
json({
    "issueTypeIds": [
        "<string>",
        "<string>"
    ],
    "after": "<string>",
    "position": "<string>"
})


// Returns a [paginated](#pagination) list of issue type schemes.
// 
// Only issue type schemes used in classic projects are returned.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Get All Issue Type Schemes")
GET "https://{{baseUrl}}/rest/api/3/issuetypescheme"
? "startAt"= "0"
? "maxResults"= "50"
? "id"= "<long>"


// Creates an issue type scheme.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Create Issue Type Scheme")
POST "https://{{baseUrl}}/rest/api/3/issuetypescheme"
"Content-Type": "application/json"
json({
    "issueTypeIds": [
        "<string>",
        "<string>"
    ],
    "name": "<string>",
    "description": "<string>",
    "defaultIssueTypeId": "<string>"
})


// Returns a [paginated](#pagination) list of issue type scheme items.
// 
// Only issue type scheme items used in classic projects are returned.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Get Issue Type Scheme Items")
GET "https://{{baseUrl}}/rest/api/3/issuetypescheme/mapping"
? "startAt"= "0"
? "maxResults"= "50"
? "issueTypeSchemeId"= "<long>"


// Adds issue types to an issue type scheme.
// 
// The added issue types are appended to the issue types list.
// 
// If any of the issue types exist in the issue type scheme, the operation fails and no issue types are added.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Add Issue Types To Issue Type Scheme")
PUT "https://{{baseUrl}}/rest/api/3/issuetypescheme/:issueTypeSchemeId/issuetype"
"Content-Type": "application/json"
json({
    "issueTypeIds": [
        "<string>",
        "<string>"
    ]
})


// Updates an issue type scheme.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Update Issue Type Scheme")
PUT "https://{{baseUrl}}/rest/api/3/issuetypescheme/:issueTypeSchemeId"
"Content-Type": "application/json"
json({
    "name": "<string>",
    "description": "<string>",
    "defaultIssueTypeId": "<string>"
})


// Deletes an issue type scheme.
// 
// Only issue type schemes used in classic projects can be deleted.
// 
// Any projects assigned to the scheme are reassigned to the default issue type scheme.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Delete Issue Type Scheme")
DELETE "https://{{baseUrl}}/rest/api/3/issuetypescheme/:issueTypeSchemeId"


// Removes an issue type from an issue type scheme.
// 
// This operation cannot remove:
// 
//  *  any issue type used by issues.
//  *  any issue types from the default issue type scheme.
//  *  the last standard issue type from an issue type scheme.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Remove Issue Type From Issue Type Scheme")
DELETE "https://{{baseUrl}}/rest/api/3/issuetypescheme/:issueTypeSchemeId/issuetype/:issueTypeId"



