#!/usr/bin/env dothttp

// Get a list of paginated customers.

@name("List customers")
GET "https://{{api_url}}/customers"
"Content-Type": "application/json"
"Accept": "application/json"
? "limit"= "15"


// Create a new customer.

@name("Create a new customer")
POST "https://{{api_url}}/customers"
"Content-Type": "application/json"
"Accept": "application/json"
data('{
	"kind": "business",
	"name": "Evil Corp.",
	"business_type": "sme",
	"vat_number": "XX0123456789",
	"vat_type": "reverse",
	"email": "evil.corp@example.com"
}')



