#!/usr/bin/env dothttp

# imported from http://localhost:8000/Microsoft%20Graph.postman_collection.json

@name("Get all connections")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9bcee0>"


@name("Create Connection")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9bf0a0>"
"Content-Type": "application/json"
data('{
    "id": "sampleConnectionId",
    "name": "Sample connection",
    "description": "Sample connection description"
}')


@name("Get connection")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9bf190>"


@name("Register schema")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9bf3d0>"
"Content-Type": "application/json"
"prefer": "respond-async"
data('{
    "baseType": "microsoft.graph.externalItem",
    "properties": [
        {
            "name": "id",
            "type": "string",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": false,
            "labels": [],
            "aliases": []
        },
        {
            "name": "title",
            "type": "string",
            "isSearchable": true,
            "isRetrievable": true,
            "isQueryable": true,
            "labels": [
                "title"
            ],
            "aliases": []
        },
        {
            "name": "extension",
            "type": "string",
            "isSearchable": true,
            "isRetrievable": true,
            "isQueryable": true,
            "labels": [],
            "aliases": []
        },
        {
            "name": "createdBy",
            "type": "string",
            "isSearchable": true,
            "isRetrievable": true,
            "isQueryable": true,
            "labels": [
                "createdBy"
            ],
            "aliases": []
        },
        {
            "name": "createdDateTime",
            "type": "dateTime",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": true,
            "labels": [
                "createdDateTime"
            ],
            "aliases": []
        },
        {
            "name": "lastModifiedBy",
            "type": "string",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": true,
            "labels": [],
            "aliases": []
        },
        {
            "name": "lastModifiedDate",
            "type": "dateTime",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": true,
            "labels": [
                "lastModifiedDateTime"
            ],
            "aliases": []
        },
        {
            "name": "url",
            "type": "string",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": false,
            "labels": [
                "url"
            ],
            "aliases": []
        },
        {
            "name": "description",
            "type": "string",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": false,
            "labels": [],
            "aliases": []
        },
        {
            "name": "authors",
            "type": "stringCollection",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": false,
            "labels": [
                "authors"
            ],
            "aliases": []
        },
        {
            "name": "iconUrl",
            "type": "string",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": false,
            "labels": ["iconUrl"],
            "aliases": []
        },
        {
            "name": "containerName",
            "type": "string",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": false,
            "labels": ["containerName"],
            "aliases": []
        },
        {
            "name": "containerUrl",
            "type": "string",
            "isSearchable": false,
            "isRetrievable": true,
            "isQueryable": false,
            "labels": ["containerUrl"],
            "aliases": []
        }
    ]
}')


@name("Get schema")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9bf520>"


@name("Delete connection")
DELETE "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9bf670>"


@name("Get connection operation status")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c9bf7c0>"



