#!/usr/bin/env dothttp

@name("Quote Template Rich Text Data")
GET "https://{{host}}/services/data/v47.0/sobjects/QuoteTemplateRichTextData/"


@name("Quote Template Rich Text Data Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/QuoteTemplateRichTextData/{ID}/"


@name("Describe Quote Template Rich Text Data")
GET "https://{{host}}/services/data/v47.0/sobjects/QuoteTemplateRichTextData/describe/"



