#!/usr/bin/env dothttp

# imported from http://localhost:8000/Microsoft%20Graph.postman_collection.json

@name("Get My Notebooks")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c847cd0>"
"Content-Type": "application/json"


@name("Get My Notebook Sections")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c847e80>"
"Content-Type": "application/json"


@name("Get My Notebook Pages")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c84c070>"
"Content-Type": "application/json"


@name("Create Notebook")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f028c84c310>"
"Content-Type": "application/json"
data('{
  "displayName": "Postman Notebook 1"
}')


@name("Create Section")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f028c84c4f0>"
"Content-Type": "application/json"
data('{
  "displayName": "Section 1"
}')



