#!/usr/bin/env dothttp

// Get an `Order` from the WMS platform by their `Id`.
// 
// <!--
// ### Sample Response
// ```
// {
//       "get": {
//         "summary": "Find a single order by orderid",
//         "description": "",
//         "operationId": "getorder",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": " order",
//             "in": "path",
//             "description": " order to retrieve",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/ orderDTO"
//             }
//           }
//         }
//       },
//       "post": {
//         "summary": "get hold reasons",
//         "description": "",
//         "operationId": "getHoldReasons",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": "order",
//             "in": "path",
//             "description": "order to use",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/orderDTO"
//             }
//           }
//         }
//       }
//     }
// ```
// -->

@name("Single Order")
GET "https://wms.slg.com/scprd/wmwebservice_rest/orders/{orderid}"
"Content-Type": "application/json"
"Authorization": "Barear Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
data('{
   "orderId": 000223
}')


// Get an `Orders` from the WMS platform by their `Timeline`.
// 
// <!--
// ### Sample Response
// ```
// {
//       "get": {
//         "summary": "Find a single order by orderid",
//         "description": "",
//         "operationId": "getorder",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": " order",
//             "in": "path",
//             "description": " order to retrieve",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/ orderDTO"
//             }
//           }
//         }
//       },
//       "post": {
//         "summary": "get hold reasons",
//         "description": "",
//         "operationId": "getHoldReasons",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": "order",
//             "in": "path",
//             "description": "order to use",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/orderDTO"
//             }
//           }
//         }
//       }
//     }
// ```
// -->

@name("Get all Order by Timeline")
GET "https://wms.slg.com/scprd/wmwebservice_rest/orders/{timeline}"
"Content-Type": "application/json"
"Authorization": "Barear Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
json({
    "startdate": "13/11/2019",
    "enddate": "13/11/2019"
})


// Create a new `Order` from the WMS platform.
// 
// <!--
// ### Sample Response
// ```
// {
//       "get": {
//         "summary": "Find a single order by orderid",
//         "description": "",
//         "operationId": "getorder",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": " order",
//             "in": "path",
//             "description": " order to retrieve",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/ orderDTO"
//             }
//           }
//         }
//       },
//       "post": {
//         "summary": "get hold reasons",
//         "description": "",
//         "operationId": "getHoldReasons",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": "order",
//             "in": "path",
//             "description": "order to use",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/orderDTO"
//             }
//           }
//         }
//       }
//     }
// ```
// -->

@name("Create Order")
POST "https://wms.slg.com/scprd/wmwebservice_rest/orders/{orderInfo}"
"Content-Type": "application/json"
"Authorization": "Barear Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
json({
    "OrderName": "Brew",
    "OrderId": 1234,
    "CompanyName": "\"abc\"",
    "Sender": "\"xyz\"",
    "CreateDate": "13/11/2019",
    "CreatedBy": "AAA"
})


// Update an `Order` from the WMS platform by orderId.
// 
// <!--
// ### Sample Response
// ```
// {
//       "get": {
//         "summary": "Find a single order by orderid",
//         "description": "",
//         "operationId": "getorder",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": " order",
//             "in": "path",
//             "description": " order to retrieve",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/ orderDTO"
//             }
//           }
//         }
//       },
//       "post": {
//         "summary": "get hold reasons",
//         "description": "",
//         "operationId": "getHoldReasons",
//         "consumes": [
//           "application/json"
//         ],
//         "produces": [
//           "application/json"
//         ],
//         "parameters": [
//           {
//             "name": "warehouse",
//             "in": "path",
//             "description": "warehouse to perform the operation on",
//             "required": true,
//             "type": "string"
//           },
//           {
//             "name": "order",
//             "in": "path",
//             "description": "order to use",
//             "required": true,
//             "type": "string"
//           }
//         ],
//         "responses": {
//           "200": {
//             "description": "successful operation",
//             "schema": {
//               "$ref": "#/definitions/orderDTO"
//             }
//           }
//         }
//       }
//     }
// ```
// -->

@name("Update Order")
PUT "https://wms.slg.com/scprd/wmwebservice_rest/orders/{orderInfo}"
"Content-Type": "application/json"
"Authorization": "Barear Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
json({
    "OrderName": "Brew updated",
    "OrderId": 1234,
    "CompanyName": "\"abc1\"",
    "Sender": "\"xyz1\"",
    "CreateDate": "13/11/2019",
    "CreatedBy": "AAA"
})



