#!/usr/bin/env dothttp

@name("get all provinces")
GET "https://{{queries_url}}.envia.com/provinces"


// Get provinces by state code. <br>
// 
// <strong>AN </strong>- ABEJORRAL<br>
// <strong>NS </strong>- ABREGO<br>
// <strong>ME </strong>- ACACIAS<br>

@name("get provinces by state code")
GET "https://{{queries_url}}.envia.com/provinces/{{state_code}}"



