#!/usr/bin/env dothttp

@name("{{baseUrl}}/Roles/GetPagedRoleMembers")
POST "https://{{baseUrl}}/Roles/GetPagedRoleMembers"
"Content-Type": "application/json"
data('{
    "Name": "<string>",
    "FilterValue": "<string>",
    "PageNumber": "<integer>",
    "Ascending": "<string>",
    "FilterBy": [
        "<string>",
        "<string>"
    ],
    "PageSize": "<integer>",
    "SortBy": "<string>"
}')


// You must be a system administrator or have role management permissions.

@name("{{baseUrl}}/Roles/UpdateRole")
POST "https://{{baseUrl}}/Roles/UpdateRole"
"Content-Type": "application/json"
data('{
    "Name": "<string>",
    "CheckPrincipalTypes": [
        "<string>",
        "<string>"
    ],
    "Roles": "<object>",
    "Users": "<object>",
    "Groups": "<object>",
    "Description": "<string>"
}')



