#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Remove Screen Tab Field")
DELETE "None://{{baseUrl}}/rest/api/3/screens/:screenId/tabs/:tabId/fields/:id"


@name("Move Screen Tab Field")
POST "None://{{baseUrl}}/rest/api/3/screens/:screenId/tabs/:tabId/fields/:id/move"
"Content-Type": "application/json"
data('{
    "after": "<uri>",
    "position": "<string>"
}')



