#!/usr/bin/env dothttp

# imported from http://localhost:8000/Microsoft%20Graph.postman_collection.json

@name("Get an open extension")
GET "<dotextensions.server.postman2_1.URLClass object at 0x7f028c84c790>"


@name("Create an open extension")
POST "<dotextensions.server.postman2_1.URLClass object at 0x7f028c84ca60>"
"Content-Type": "application/json"
data('{
  "@odata.type": "microsoft.graph.openTypeExtension",
  "extensionName": "com.contoso.roamingSettings",
  "theme": "dark",
  "color": "purple",
  "lang": "Japanese"
}')


@name("Update an open extension")
PATCH "<dotextensions.server.postman2_1.URLClass object at 0x7f028c84ccd0>"
"Content-Type": "application/json"
data('{
  "theme": "light",
  "color": "red",
  "lang": "Swahili"
}')



