#!/usr/bin/env dothttp

@name("/profiles/:id")
GET "https://{{baseUrl}}/profiles/:id"


// Update a record

@name("/profiles/:id")
PUT "https://{{baseUrl}}/profiles/:id"
"Content-Type": "application/json"
json({
    "height": -65241154,
    "profile_job": "ea veniam aute Lorem",
    "annual_income": -20744728,
    "profile_education": "dolor dolore",
    "created_by": "ut dolore deserunt mollit laborum",
    "updated_by": "laboris cupidatat mollit f"
})


// Delete a record

@name("/profiles/:id")
DELETE "https://{{baseUrl}}/profiles/:id"



