#!/usr/bin/env dothttp

@name("CREATE Email Domain")
POST "https://{{apiPath}}/environments/{{envID}}/emailDomains"
"Content-Type": "application/json"
data('{  
   "domainName":"auth.shopco.com"
}')


@name("READ Email Domain")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}"
"Content-Type": "application/json"


@name("READ All Email Domains")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains"
"Content-Type": "application/json"


@name("DELETE Email Domain")
DELETE "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}"
"Content-Type": "application/json"


@name("READ Email Domain Ownership Tokens")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/ownership"
"Content-Type": "application/json"


@name("READ Email Domain Dkim Tokens")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/dkim"
"Content-Type": "application/json"


@name("READ Email Domain SPF Tokens")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/spf"
"Content-Type": "application/json"


@name("READ All Email Domain Trusted Emails")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/trustedEmails"
"Content-Type": "application/json"


@name("CREATE Email Domain Trusted Email")
POST "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/trustedEmails"
"Content-Type": "application/json"
data('{  
   "emailAddress":"noreply1@auth.shopco.com"
}')


@name("Activate Trusted Email")
POST "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/trustedEmails/{{trustedEmailID}}"
"content-type": "application/vnd.pingidentity.trustedEmail.activate+json"
"Accept": "application/vnd.pingidentity.user.import+json"
data('{  
   "verificationCode":"e85jsutg"
}')


@name("Resend Verification Code for Trusted Email")
POST "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/trustedEmails/{{trustedEmailID}}"
"Content-Type": "application/vnd.pingidentity.trustedEmail.sendVerificationCode+json"



@name("READ Email Domain Trusted Email")
GET "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/trustedEmails/{{trustedEmailID}}"
"Content-Type": "application/json"


@name("DELETE Email Domain Trusted Email")
DELETE "https://{{apiPath}}/environments/{{envID}}/emailDomains/{{emailDomainID}}/trustedEmails/{{trustedEmailID}}"
"Content-Type": "application/json"


@name("READ Notifications Settings with Trusted Email")
GET "https://{{apiPath}}/environments/{{envID}}/notificationsSettings"


@name("UPDATE Notifications Settings with Trusted Email")
PUT "https://{{apiPath}}/environments/{{envID}}/notificationsSettings"
"Content-Type": "application/json"
data('{
    "restrictions": {
        "smsVoiceQuota": {
            "daily": 30
        }
    },
    "whitelist": [
    	{
    		"user": 
    		{
    			"id": "{{userId}}"
    		}
    		
    	}
    	],
    "deliveryMode": "ALL",
    "defaultLanguage": "en",
    "from": {"name": "from", "address":"noreply_new@pingidentity.com"},
    "replyTo": {"name": "reply", "address":"noreply_new@pingidentity.com"}
}')



