#!/usr/bin/env dothttp

// Remove the specified set of accounts by institution login id from the Finicity system.
// 
// (Note that the request and response are the same for JSON and XML clients.)

@name("Delete Customer Accounts By Institution Login")
DELETE "https://{{baseUrl}}/aggregation/v1/customers/:customerId/institutionLogins/:institutionLoginId"


// This service has been replaced by version 2 call now "Migrate Institution Login Accounts"
// 
// This service is to migrate accounts from legacy FI to new OAuth FI. 
// 
// A successful API response will return a list of accounts for the given institution login id with an http status code as 200.

@name("Migrate Institution Login Accounts V1")
PUT "https://{{baseUrl}}/aggregation/v1/customers/:customerId/institutionLogins/:institutionLoginId/institutions/:newInstitutionId"



