#!/usr/bin/env dothttp

// OAuth required scopes: OR.Monitoring or OR.Monitoring.Read.
// 
// Required permissions: License.View.

@name("Gets the consumption licensing usage statistics")
GET "https://{{baseUrl}}/api/Stats/GetConsumptionLicenseStats"
? "tenantId"= "12575632"
? "days"= "12575632"


// OAuth required scopes: OR.Monitoring or OR.Monitoring.Read.
// 
// Requires authentication.
// 
// Returns the name and the total number of entities registered in Orchestrator for a set of entities.
// All the counted entity types can be seen in the result below.
//      [
//            {
//              "title": "Processes",
//              "count": 1
//            },
//            {
//              "title": "Assets",
//              "count": 0
//            },
//            {
//              "title": "Queues",
//              "count": 0
//            },
//            {
//              "title": "Schedules",
//              "count": 0
//            }
//      ]

@name("Gets the total number of various entities registered in Orchestrator")
GET "https://{{baseUrl}}/api/Stats/GetCountStats"


// OAuth required scopes: OR.Monitoring or OR.Monitoring.Read.
// 
// Required permissions: Jobs.View.
// 
// Returns the total number of Successful, Faulted and Canceled jobs respectively.
// Example of returned result:
//     [
//           {
//             "title": "Successful",
//             "count": 0
//           },
//           {
//             "title": "Faulted",
//             "count": 0
//           },
//           {
//             "title": "Canceled",
//             "count": 0
//           }
//     ]

@name("Gets the total number of jobs aggregated by Job State")
GET "https://{{baseUrl}}/api/Stats/GetJobsStats"


// OAuth required scopes: OR.Monitoring or OR.Monitoring.Read.
// 
// Required permissions: License.View.

@name("Gets the licensing usage statistics")
GET "https://{{baseUrl}}/api/Stats/GetLicenseStats"
? "tenantId"= "12575632"
? "days"= "12575632"


// OAuth required scopes: OR.Monitoring or OR.Monitoring.Read.
// 
// Required permissions: Robots.View.
// 
// Returns the total number of Available, Busy, Disconnected and Unresponsive robots respectively.
// Example of returned result:
//     [
//           {
//             "title": "Available",
//             "count": 1
//           },
//           {
//             "title": "Busy",
//             "count": 0
//           },
//           {
//             "title": "Disconnected",
//             "count": 1
//           },
//           {
//             "title": "Unresponsive",
//             "count": 0
//           }
//     ]

@name("Gets the total number of robots aggregated by Robot State")
GET "https://{{baseUrl}}/api/Stats/GetSessionsStats"



