#!/usr/bin/env dothttp

@name("Messaging Session Feed")
GET "https://{{host}}/services/data/v47.0/sobjects/MessagingSessionFeed/"


@name("Messaging Session Feed Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/MessagingSessionFeed/{ID}/"


@name("Describe Messaging Session Feed")
GET "https://{{host}}/services/data/v47.0/sobjects/MessagingSessionFeed/describe/"



