#!/usr/bin/env dothttp

// Test here...

@name("getAuthorizationToken")
GET "http://api.openbanking.ng/access/getAuthorizationToken"
"Accept": "*/*"
"Content-Type": "application/json"
? "clientSecret"= "{{clientSecret}}"
? "grantType"= "{{grantType}}"
data('Requires Client Identifier, Secret and Grant Type')



