#!/usr/bin/env dothttp

// Return the uplink loss and latency for every MX in the organization from at latest 2 minutes ago

@name("Return the uplink loss and latency for every MX in the organization from at latest 2 minutes ago")
GET "https://{{baseUrl}}/organizations/:organizationId/devices/uplinksLossAndLatency"
"X-Cisco-Meraki-API-Key": ""
? "t0"= "{{t0}}"
? "t1"= "{{t1}}"
? "timespan"= "{{timespan}}"
? "uplink"= "{{uplink}}"
? "ip"= "{{ip}}"



