#!/usr/bin/env dothttp

// 获得所有的修改码

@name("getAllUserCode")
GET "https://{{url}}/api/v1/usercode/all"


// 获得一个id，修改码
// 
// **参数**
// - id: 表示`UserCode`的主键（需要加在请求链接里）

@name("getOneUserCode")
GET "https://{{url}}/api/v1/usercode/id"


// 使用修改码
// 
// **参数**
// - code: 表示使用的修改码

@name("userdUserCode")
GET "https://{{url}}/api/v1/usercode/used"
? "code"= "CCCCC"
? "acc"= "17700000000"


// 新增一个id，修改码

@name("creatOneUserCode")
POST "https://{{url}}/api/v1/usercode"
files(
	("userID", "1"),
	("code", "AAAAA")
)


// 更新一个id，修改码
// 
// **参数**
// - id: 表示`UserCode`的主键（需要加在请求链接里）

@name("updateOneUserCode")
PATCH "https://{{url}}/api/v1/usercode/1"
files(
	("userID", "1"),
	("code", "AAAAB")
)


// 删除一个id，修改码
// 
// **参数**
// - id: 表示`UserCode`的主键（需要加在请求链接里）

@name("deleteOneUserCode")
DELETE "https://{{url}}/api/v1/usercode/id"



// 搜索一个id，修改码
// 
// **参数**
// - term: 表示搜索的项目（code）

@name("searchUserCode")
GET "https://{{url}}/api/v1/usercode/search"
? "term"= "AAAAA"


// 获得所有的修改码（按照修改码创建的时间排列）

@name("getAllUserCodeSortByTime")
GET "https://{{url}}/api/v1/usercode/sort"



