#!/usr/bin/env dothttp

@name("Retrieve FIB list from device")
GET "https://{{vmanage}}/dataservice/device/ip/fib"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"
? "color"= "{{color}}"


@name("Retrieve cedge_cef from device")
GET "https://{{vmanage}}/dataservice/device/ip/cedge_cef"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve route table list from device")
GET "https://{{vmanage}}/dataservice/device/ip/routetable"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"
? "vpn-id"= "{{vpnId}}"


@name("Retrieve IP MFIB OIL list from device")
GET "https://{{vmanage}}/dataservice/device/ip/mfiboil"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve IP MFIB statistics from device")
GET "https://{{vmanage}}/dataservice/device/ip/mfibstats"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Generate IP MFIB summary list from device")
GET "https://{{vmanage}}/dataservice/device/ip/mfibsummary"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve NAT interface list from device")
GET "https://{{vmanage}}/dataservice/device/ip/nat/interface"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve NAT translation list from device")
GET "https://{{vmanage}}/dataservice/device/ip/nat/translation"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve NAT filter list from device")
GET "https://{{vmanage}}/dataservice/device/ip/nat/filter"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve NAT interface statistics from device")
GET "https://{{vmanage}}/dataservice/device/ip/nat/interfacestatistics"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve NAT64 interface list from device")
GET "https://{{vmanage}}/dataservice/device/ip/nat64/translation"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"


@name("Retrieve ietf routing list from device")
GET "https://{{vmanage}}/dataservice/device/ip/ipRoutes"
"X-XSRF-TOKEN": "{{X-XSRF-TOKEN}}"
? "deviceId"= "{{deviceId}}"



