#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Get Issue Link")
GET "None://{{baseUrl}}/rest/api/3/issueLink/:linkId"


@name("Delete Issue Link")
DELETE "None://{{baseUrl}}/rest/api/3/issueLink/:linkId"



