#!/usr/bin/env dothttp

@name("/wc/v3/products/tags")
GET "https://{{baseUrl}}/wc/v3/products/tags"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
? "context"= "view"
? "context"= "view"
? "page"= "<string>"
? "per_page"= "<string>"
? "search"= "<string>"
? "exclude"= "<string>"
? "include"= "<string>"
? "offset"= "<string>"
? "order"= "asc"
? "order"= "asc"
? "orderby"= "name"
? "orderby"= "name"
? "hide_empty"= "<string>"
? "product"= "<string>"
? "slug"= "<string>"


@name("/wc/v3/products/tags")
POST "https://{{baseUrl}}/wc/v3/products/tags"
basicauth("{{CLIENT_KEY}}", "{{CLIENT_SECRET}}")
"Content-Type": "multipart/form-data"
files(
	("name", "<string>"),
	("slug", "<string>"),
	("description", "<string>")
)



