#!/usr/bin/env dothttp

// List static delegated prefixes for a network

@name("List Static Delegated Prefixes For A Network")
GET "https://{{baseUrl}}/networks/:networkId/appliance/staticDelegatedPrefixes"
"X-Cisco-Meraki-API-Key": ""


// Add a static delegated prefix from a network
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// prefix| string| A static IPv6 prefix
// origin| object| The origin of the prefix
// description| string| A name or description for the prefix
// 
// #### Supports Action Batches
// 
// **Resource**|**Operation**
// :-------------: |:-------------:
// `/networks/{networkId}/appliance/staticDelegatedPrefixes` | create
// 

@name("Add A Static Delegated Prefix From A Network")
POST "https://{{baseUrl}}/networks/:networkId/appliance/staticDelegatedPrefixes"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "prefix": "<string>",
    "origin": {
        "type": "<string>",
        "interfaces": [
            "<string>",
            "<string>"
        ]
    },
    "description": "<string>"
}')


// Return a static delegated prefix from a network

@name("Return A Static Delegated Prefix From A Network")
GET "https://{{baseUrl}}/networks/:networkId/appliance/staticDelegatedPrefixes/:staticDelegatedPrefixId"
"X-Cisco-Meraki-API-Key": ""


// Update a static delegated prefix from a network
//  #### Body Parameters 
// **Parameter**|**Type**|**Description** 
//  :-------------: |:-------------: |:-------------: 
// prefix| string| A static IPv6 prefix
// origin| object| The origin of the prefix
// description| string| A name or description for the prefix
// 
// #### Supports Action Batches
// 
// **Resource**|**Operation**
// :-------------: |:-------------:
// `/networks/{networkId}/appliance/staticDelegatedPrefixes/{staticDelegatedPrefixId}` | update
// 

@name("Update A Static Delegated Prefix From A Network")
PUT "https://{{baseUrl}}/networks/:networkId/appliance/staticDelegatedPrefixes/:staticDelegatedPrefixId"
"X-Cisco-Meraki-API-Key": ""
"Content-Type": "application/json"
data('{
    "prefix": "<string>",
    "origin": {
        "type": "<string>",
        "interfaces": [
            "<string>",
            "<string>"
        ]
    },
    "description": "<string>"
}')


// Delete a static delegated prefix from a network
// #### Supports Action Batches
// 
// **Resource**|**Operation**
// :-------------: |:-------------:
// `/networks/{networkId}/appliance/staticDelegatedPrefixes/{staticDelegatedPrefixId}` | destroy
// 

@name("Delete A Static Delegated Prefix From A Network")
DELETE "https://{{baseUrl}}/networks/:networkId/appliance/staticDelegatedPrefixes/:staticDelegatedPrefixId"
"X-Cisco-Meraki-API-Key": ""



