#!/usr/bin/env dothttp

@name("Order Item Feed")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemFeed/"


@name("Order Item Feed Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemFeed/{ID}/"


@name("Describe Order Item Feed")
GET "https://{{host}}/services/data/v47.0/sobjects/OrderItemFeed/describe/"



