#!/usr/bin/env dothttp

# imported from https://www.getpostman.com/collections/d8ed5a08800a7e606296

@name("Bulk Get Users")
GET "None://{{baseUrl}}/rest/api/3/user/bulk"
? "startAt"= "0"
? "maxResults"= "10"
? "username"= "<string>"
? "username"= "<string>"
? "key"= "<string>"
? "key"= "<string>"
? "accountId"= "<string>"
? "accountId"= "<string>"


@name("Get Account Ids For Users")
GET "None://{{baseUrl}}/rest/api/3/user/bulk/migration"
? "startAt"= "0"
? "maxResults"= "10"
? "username"= "<string>"
? "username"= "<string>"
? "key"= "<string>"
? "key"= "<string>"



