#!/usr/bin/env dothttp

// Authenticated tax payer can save entire GSTR-4 invoices by uploading json to GST portal

@name("Upload GSTR-4")
POST "https://{{host}}/gsp/tax-payer/:gstin/gstrs/gstr-4/:year/:month"
"Authorization": "{{access_token}}"
"x-api-key": "{{api_key}}"
"x-api-version": "{{version}}"
"Content-Type": "application/json"
json({
    "gstin": "24AAACJ3770E2ZZ",
    "fp": "122019",
    "txos": {
        "itms": [
            {
                "samt": 0,
                "rt": 5,
                "camt": 0,
                "trnovr": 0
            }
        ]
    }
})



