#!/usr/bin/env dothttp

@name("My Joined Teams")
GET "https://graph.microsoft.com/v1.0/me/joinedTeams"


@name("Members of a Team")
GET "https://graph.microsoft.com/v1.0/groups/{{TeamId}}/members"


@name("Channels of a Team")
GET "https://graph.microsoft.com/v1.0/teams/{{TeamId}}/channels"


@name("Channel info")
GET "https://graph.microsoft.com/v1.0/teams/{{TeamId}}/channels/{{ChannelId}}"


@name("Create Team")
POST "https://graph.microsoft.com/v1.0/teams"
"Content-Type": "application/json"
json({
    "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
    "displayName": "My Sample Team",
    "description": "My Sample Team’s Description"
})


@name("Create Channel")
POST "https://graph.microsoft.com/v1.0/teams/{{TeamId}}/channels"
"Content-Type": "application/json"
json({
    "displayName": "Architecture Discussion",
    "description": "This channel is where we debate all future architecture plans"
})


@name("Apps in a Team")
GET "https://graph.microsoft.com/v1.0/teams/{{TeamId}}/installedApps"
"Content-Type": "application/json"
? "$expand"= "teamsAppDefinition"


@name("Tabs in a Channel")
GET "https://graph.microsoft.com/v1.0/teams/{{TeamId}}/channels/{{ChannelId}}/tabs"
"Content-Type": "application/json"
? "$expand"= "teamsApp"


@name("Items in a Team Drive")
GET "https://graph.microsoft.com/v1.0/groups/{{TeamId}}/drive/root/children"
"Content-Type": "application/json"


@name("Messages (without replies) in a Channel (beta)")
GET "https://graph.microsoft.com/beta/teams/{{TeamId}}/channels/{{ChannelId}}/messages"
"Content-Type": "application/json"


@name("Message in a channel (beta)")
GET "https://graph.microsoft.com/beta/teams/{{TeamId}}/channels/{{ChannelId}}/messages/{{MessageId}}"
"Content-Type": "application/json"


@name("Replies to a Message in a Channel (beta)")
GET "https://graph.microsoft.com/beta/teams/{{TeamId}}/channels/{{ChannelId}}/messages/{{MessageId}}/replies"
"Content-Type": "application/json"


@name("Reply of a Message (beta)")
GET "https://graph.microsoft.com/beta/teams/{{TeamId}}/channels/{{ChannelId}}/messages/{{MessageId}}/replies/{{ReplyId}}"
"Content-Type": "application/json"


@name("Create a chat thread (beta)")
POST "https://graph.microsoft.com/beta/teams/{{TeamId}}/channels/{{ChannelId}}/messages"
"Content-Type": "application/json"
json({
    "body": {
        "content": "Hello World!"
    }
})


@name("Create a chat thread (beta) html")
POST "https://graph.microsoft.com/beta/teams/{{TeamId}}/channels/{{ChannelId}}/messages"
"Content-Type": "application/json"
json({
    "body": {
        "contentType": "html",
        "content": "<div><div>
<div><img alt=\"GIF Image\" height=\"250\" src=\"https://media3.giphy.com/media/f5xmRWRu4zxxh2mE5v/giphy.gif?cid=de9bf95eevnce0lknjlbneccchvdkn991jea1gtmw2zmvdke&amp;rid=giphy.gif\" width=\"250\" style=\"max-height:250px; width:250px; height:250px\"></div>


</div>
</div>"
    }
})



