#!/usr/bin/env dothttp

// List all notifications for the current user, sorted by most recently updated.

@name("List notifications for the authenticated user")
GET "https://{{baseUrl}}/notifications"
? "all"= "false"
? "participating"= "false"
? "since"= "<string>"
? "before"= "<string>"
? "per_page"= "30"
? "page"= "1"


// Marks all notifications as "read" removes it from the [default view on GitHub](https://github.com/notifications). If the number of notifications is too large to complete in one request, you will receive a `202 Accepted` status and GitHub will run an asynchronous process to mark notifications as "read." To check whether any "unread" notifications remain, you can use the [List notifications for the authenticated user](https://docs.github.com/rest/reference/activity#list-notifications-for-the-authenticated-user) endpoint and pass the query parameter `all=false`.

@name("Mark notifications as read")
PUT "https://{{baseUrl}}/notifications"
"Content-Type": "application/json"
json({
    "last_read_at": "<dateTime>",
    "read": "<boolean>"
})



