#!/usr/bin/env dothttp

// The meta endpoint is so-called because it is an endpoint about endpoints.  Its primary purpose is to enable the HqO Platform to see if the service is available and as such is often referred to as a "heartbeat" operation.  Only API-level authentication is required.

@name("Get meta")
GET "https://{{baseUrl}}/service-booking/v1/meta"
? "trid"= "{{trackingId}}"


// This endpoint accepts credentials for a user that was created using the CreateUser endpoint.  If successfully authenticated, it responds with a UserToken object that contains an access token.  This access token will then be used on subsequent functional endpoints that require user level authentication in addition to API authentication as described in the Authentication section.

@name("Login")
POST "https://{{baseUrl}}/service-booking/v1/login"
"Accept": "application/json; charset=utf-8"
"Accept-Encoding": "gzip"
"Content-Type": "application/json; charset=utf-8"
? "trid"= "{{trackingId}}"
data('"<object>"')



