#!/usr/bin/env dothttp

@name("http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/receipt_order_food")
POST "http://devapi2kanten.ayrtonware.com/api_kanten_dev/v1/receipt_order_food"
"Authorization": "ffde9eac08d957bbd1bd225a8c16f7"
files(
	("id_order", "CL1wb31rtpc2bphn"),
	("email", "islahudin.soft01engineer@gmail.com")
)



