#!/usr/bin/env dothttp

@name("/admin/v1/users")
GET "https://{{duo-API-HOST}}/admin/v1/users"
basicauth("{{admin-ikey}}", "{{duo-admin-HMAC}}")
"Date": "{{duo-DATE}}"
"Content-Type": "application/x-www-form-urlencoded"



