#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List repository collaborators")
GET "https://{{baseUrl}}/repos/{{owner}}/{{repo/collaborators}}/"
? "affiliation"= "all"
? "per_page"= "30"
? "page"= "1"



