#!/usr/bin/env dothttp

// This endpoint creates a valid JWT and refresh token given a successful login.

@name("/v1/oauth/token")
POST "https://{{NAMESPACE_URL}}{{AUTH_SERVICE_PORT}}/auth-service/v1/oauth/token"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "username": [
        "{{AUTH_SERVICE_USERNAME}}"
    ],
    "password": [
        "{{AUTH_SERVICE_PASSWORD}}"
    ]
})


@name("/v1/oauth/refresh-token")
POST "https://{{NAMESPACE_URL}}{{AUTH_SERVICE_PORT}}/auth-service/v1/oauth/refresh-token"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "refresh_token": [
        "{{AUTH_SERVICE_REFRESH_TOKEN}}"
    ]
})


@name("/v1/oauth/revoke-token")
POST "https://{{NAMESPACE_URL}}{{AUTH_SERVICE_PORT}}/auth-service/v1/oauth/revoke-token"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "jwt": [
        "{{AUTH_SERVICE_JWT_TOKEN}}"
    ]
})



