#!/usr/bin/env dothttp

@name("Get all problems")
GET "https://codeforces.com/api/problemset.problems"
? "tags"= "{{problemTags}}"


@name("Generate Problemset")
GET "https://codeforces.com/api/user.status"
? "handle"= "{{userId}}"
? "from"= "1"



