#!/usr/bin/env dothttp

@name("Deactivate Standby")
POST "https://{{WEBEXAPI}}/xapi/command/Standby.Deactivate"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
"": ""
json({
    "deviceId": "{{_deviceId}}"
})


// So far nothing interesting seems to come back from this.

@name("Get Room Analytics")
GET "https://{{WEBEXAPI}}/xapi/status/"
"Authorization": "Bearer {{access_token}}"
? "deviceId"= "{{_deviceId}}"
? "name"= "RoomAnalytics.PeopleCount.Current"


@name("Activate Standby")
POST "https://{{WEBEXAPI}}/xapi/command/Standby.Activate"
"Authorization": "Bearer {{access_token}}"
"Content-Type": "application/json"
"": ""
json({
    "deviceId": "{{_deviceId}}"
})



