#!/usr/bin/env dothttp

@name("List of Categories")
GET "https://{{api_url}}/managers/store/categories"
"Accept": "{{Accept}}"
"Authorization": "{{Authorization}}"
"X-MANAGER-TOKEN": "{{X-MANAGER-TOKEN}}"
"Accept-Language": "{{Accept-Language}}"
"User-Agent": "{{User-Agent}}"


@name("Category By Id")
GET "https://{{api_url}}/managers/store/categories/67119/view"
"Accept": "{{Accept}}"
"Authorization": "{{Authorization}}"
"X-MANAGER-TOKEN": "{{X-MANAGER-TOKEN}}"
"Accept-Language": "{{Accept-Language}}"
"User-Agent": "{{User-Agent}}"
"STORE-ID": "{{STORE_ID}}"


@name("Create Store Category")
POST "https://{{api_url}}/managers/store/categories/add"
"Accept": "{{Accept}}"
"Authorization": "{{Authorization}}"
"X-MANAGER-TOKEN": "{{X-MANAGER-TOKEN}}"
"User-Agent": "{{User-Agent}}"
"Accept-Language": "{{Accept-Language}}"
files(
	("name[ar]", "قسم المنتجات اليدوية"),
	("name[en]", "handmade products"),
	("description[ar]", "منتجات تُصنع خصيصًا عند الطلب"),
	("description[en]", "ondemand handmade products")
)


@name("Update Category Publishing")
POST "https://{{api_url}}/managers/store/categories/:id/publishing"
"Accept": "{{Accept}}"
"Authorization": "{{Authorization}}"
"X-MANAGER-TOKEN": "{{X-MANAGER-TOKEN}}"
"User-Agent": "{{User-Agent}}"
"Accept-Language": "{{Accept-Language}}"
files(
	("is_published", "1"),
	("_method", "put")
)


@name("Create/Update Category Products")
POST "https://{{api_url}}/managers/store/categories/67119/products/update"
"Accept": "{{Accept}}"
"Authorization": "{{Authorization}}"
"X-MANAGER-TOKEN": "{{X-MANAGER-TOKEN}}"
"User-Agent": "{{User-Agent}}"
"Accept-Language": "{{Accept-Language}}"
files(
	("products[]", "{{product_id}}"),
	("products[]", "{{product_id}}"),
	("_method", "put")
)


@name("Delete Category Products")
POST "https://{{api_url}}/managers/store/categories/67119/products/delete"
"Accept": "{{Accept}}"
"Authorization": "{{Authorization}}"
"X-MANAGER-TOKEN": "{{X-MANAGER-TOKEN}}"
"User-Agent": "{{User-Agent}}"
"Accept-Language": "{{Accept-Language}}"
files(
	("products[]", "{{product_id}}"),
	("_method", "delete")
)



