#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("Get an installation for the authenticated app")
GET "https://{{baseUrl}}/app/installations/{{installation_id}}/"


@name("Delete an installation for the authenticated app")
DELETE "https://{{baseUrl}}/app/installations/{{installation_id}}/"


@name("Create an installation access token for an app")
POST "https://{{baseUrl}}/app/installations/{{installation_id}}/access_tokens"
"Content-Type": "application/json"
json({
    "repositories": [
        "rails",
        "rails"
    ],
    "repository_ids": [
        1
    ],
    "permissions": {
        "contents": "read",
        "issues": "read",
        "deployments": "write",
        "single_file": "read"
    }
})



