#!/usr/bin/env dothttp

@name("Pricebook2")
GET "https://{{host}}/services/data/v47.0/sobjects/Pricebook2/"


@name("Pricebook2 Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/Pricebook2/{ID}/"


@name("Describe Pricebook2")
GET "https://{{host}}/services/data/v47.0/sobjects/Pricebook2/describe/"



