#!/usr/bin/env dothttp

// Show VPN status for networks in an organization
@name("Show VPN status for networks in an organization")
GET "https://{{baseUrl}}/organizations/:organizationId/appliance/vpn/statuses"
"X-Cisco-Meraki-API-Key": ""
? "perPage"= "{{perPage}}"
? "startingAfter"= "{{startingAfter}}"
? "endingBefore"= "{{endingBefore}}"
? "networkIds"= "{{networkIds}}"



