#!/usr/bin/env dothttp

// Returns URLs pointing to images of this vehicle's equipments. The images are available in the highest possible resolution (usually 740x416 px).

@name("image Components Equipments GET")
GET "https://{{baseUrl}}/markets/:marketId/models/:modelId/configurations/:configurationId/images/components/equipments"


// Returns URLs pointing to images of this vehicle's equipments. The images are available in the highest possible resolution (usually 740x416 px).

@name("image Components Equipments By Code GET")
GET "https://{{baseUrl}}/markets/:marketId/models/:modelId/configurations/:configurationId/images/components/equipments/:componentCode"



