#!/usr/bin/env dothttp

@name("Custom Brand")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomBrand/"


@name("Custom Brand Detail")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomBrand/{ID}/"


@name("Describe Custom Brand")
GET "https://{{host}}/services/data/v47.0/sobjects/CustomBrand/describe/"



