#!/usr/bin/env dothttp

// Makes sure all of the parameters are camel case -- still working on this one.

@name("Do only POST, PUT, and PATCH have bodies?")
GET "https://postman-echo.com/get"


// Makes sure that all method query parameters have descriptions.

@name("Do request bodies have a description?")
GET "https://postman-echo.com/get"


// Makes sure that all method query parameters have descriptions.

@name("Do request bodies have a JSON media type?")
GET "https://postman-echo.com/get"


// Makes sure that all method query parameters have descriptions.

@name("Do request boeis have schema?")
GET "https://postman-echo.com/get"


// Makes sure that all method query parameters have descriptions.

@name("Do request bodies have examples?")
GET "https://postman-echo.com/get"



