#!/usr/bin/env dothttp

# {{baseUrl=api.github.com}}

@name("List email addresses for the authenticated user")
GET "https://{{baseUrl}}/user/emails"
? "per_page"= "30"
? "page"= "1"


@name("Add an email address for the authenticated user")
POST "{{baseUrl}}/user/emails"
"Content-Type": "application/json"
json({
    "emails": [
        "octocat@github.com",
        "mona@github.com"
    ]
})


@name("Delete an email address for the authenticated user")
DELETE "{{baseUrl}}/user/emails"
"Content-Type": "application/json"
json({
    "emails": [
        "octocat@github.com",
        "mona@github.com"
    ]
})



