#!/usr/bin/env dothttp

@name("/purchases")
POST "https://{{baseUrl}}/purchases"
"Content-Type": "application/json"
"Authorization": "<Authorization>"
"x-api-key": "{{apiKey}}"
? "discount_code"= "<discount_code>"
? "id_mall"= "<id_mall>"
data('{
    "id_card": "id de la tarjeta",
    "id_product": "id del producto",
    "amount": "cantidad",
    "device_fingerprint": "num",
    "platform": "plataforma: ios, web, android"
}')


@name("/purchases")
OPTIONS "https://{{baseUrl}}/purchases"



