#!/usr/bin/env dothttp

@name("Effective Job by Name")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/jobs"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "94a57f46-b141-40d9-9c4b-d4550e75272f"
? "name"= "null"
? "date"= "2019-12-30"



@name("Effective Job by Id")
GET "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/jobs/1"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "94a57f46-b141-40d9-9c4b-d4550e75272f"
? "date"= "2020-01-01"



@name("Retrive Job List")
POST "https://PRIMECOMMUNICATION-uat-nosso.npr.mykronos.com/api/v1/commons/jobs/external_ids/multi_read"
"content-type": "application/json"
"appkey": "d7uHl4AOoIqfenE511jwMYns1bSHMxan"
"Authorization": "a96e3fdd-d051-42ed-bb46-b11cbabecb59"
json({
    "where": {
        "date": "2020-01-06",
        "externalIds": [
            "All Home"
        ]
    }
})



