#!/usr/bin/env dothttp

@name("List device groups that match criteria")
GET "https://{{baseUrl}}/devicegroups"
"Authorization": ""
? "page"= "1"
? "pageSize"= "100"
? "role"= "<string>"


@name("Create new device group")
POST "https://{{baseUrl}}/devicegroups"
"Authorization": ""
"Content-Type": "application/json"
data('{
    "backgroundColor": "<string>",
    "borderColor": "<string>",
    "description": "<string>",
    "foregroundColor": "<string>",
    "icon": "<string>",
    "imageUrl": "<string>",
    "metadata": "<object>",
    "name": "<string>",
    "roles": [
        "<string>",
        "<string>"
    ],
    "token": "<string>"
}')



