#!/usr/bin/env dothttp

// A `GET` request to this endpoint returns the list of all request headers as part of the response JSON.
// In Postman, sending your own set of headers through the [Headers tab](https://www.getpostman.com/docs/requests#headers?source=echo-collection-app-onboarding) will reveal the headers as part of the response.

@name("Request Headers")
GET "https://postman-echo.com/headers"
"my-sample-header": "Lorem ipsum dolor sit amet"


// This endpoint causes the server to send custom set of response headers. Providing header values as part of the URL parameters of a `GET` request to this endpoint returns the same as part of response header.
// 
// To send your own set of headers, simply add or replace the the URL parameters with your own set.

@name("Response Headers")
GET "https://postman-echo.com/response-headers"
? "foo1"= "bar1"
? "foo2"= "bar2"



