#!/usr/bin/env dothttp

@name("Get entity from JobApplicationQuestionResponse by key")
GET "https://{{baseUrl}}/JobApplicationQuestionResponse(applicationId={{applicationId}},order={{order}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
? "$select"= "question,expectedAnswer"
? "$expand"= "*,jobApplication"


@name("Update entity in JobApplicationQuestionResponse")
PUT "https://{{baseUrl}}/JobApplicationQuestionResponse(applicationId={{applicationId}},order={{order}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
"Content-Type": "application/json"
data('{
    "d": {
        "answer": "in ullamco",
        "applicationId": "ad dolor ullamco minim",
        "expectedAnswer": "minim quis",
        "expectedAnswerValue": -50717168.554811165,
        "highLow": "dolor aliqua rep",
        "maxLength": 19370913.10832475,
        "order": "culpa laborum",
        "question": "veniam laborum irure",
        "questionResponse": "tempor",
        "type": "Duis minim",
        "jobApplication": {
            "address": "occaecat pariatur",
            "address2": "non Excepteur",
            "agencyInfo": "in Duis",
            "anonymizedDate": "/Date(1492098664000)/",
            "anonymizedFlag": "magna ullamco",
            "appLocale": "Excepteur",
            "appStatusSetItemId": "in exercitation commodo ipsum in",
            "applicationId": "id laborum pa",
            "applicationTemplateId": "ex nisi of",
            "averageRating": "ut ipsum sint anim",
            "baseSalary": "do dolor est amet deserunt",
            "candConversionProcessed": "Lorem",
            "candJust": "proident",
            "candTypeWhenHired": "consectetur ad sunt eiusmod",
            "candidateId": "do eu cupidatat tempor velit",
            "cellPhone": "dolor sit incididun",
            "city": "ipsum consectetur",
            "confnumber": "exercitation esse voluptate consequat laborum",
            "contactEmail": "tempor eu",
            "conviction_details": "et mollit",
            "country": "Lorem ex et sit",
            "countryCode": "exercitation voluptate velit",
            "criminalconvictionlabel": "nisi consectetur quis labore minim",
            "crimincalconvictioninstructions": "cillum nulla Ut ea exercitation",
            "currentLocation": "nisi incididunt sit",
            "currentTitle": "ea ut amet sunt in",
            "cust_refCheckFirstName": "laborum minim eu magna",
            "cust_refCheckLastName": "magna enim anim in in",
            "cust_refCheckOrg1": "ex",
            "cust_refCheckPhone1": "non nisi sunt",
            "cust_refCheckTitle1": "sint de",
            "dataSource": "deserunt nulla proident incididunt",
            "dateAvail": "/Date(1492098664000)/",
            "dateOfBirth": "/Date(1492098664000)/",
            "duplicateProfile": "velit tempor ad do",
            "exportedOn": "/Date(1492098664000)/",
            "extTitle": "sit elit",
            "firstName": "Lorem",
            "formerEmployee": true,
            "gender": "consequat cupidatat",
            "haveyoubeenconvicted": "anim a",
            "hireDate": "/Date(1492098664000)/",
            "hiredOn": "/Date(1492098664000)/",
            "homePhone": "pariatur u",
            "inductionAdd": "magna ea in proident",
            "inductionDate": "/Date(1492098664000)/",
            "initials": "mollit id velit Duis",
            "instrAppReturn": "voluptate",
            "instrCandApproval": "cillum deserunt",
            "instrCandAssess": "dolore dolor",
            "instrCandFields": "deserunt ipsum pariatur",
            "instrCandScreen": "in Duis ex",
            "instrWotc": "Duis",
            "instr_AdditionalDocuments": "nulla Ut",
            "instr_AppAdditionalInfo": "sed",
            "instr_AppAdvice": "in nisi",
            "instr_CandAppDetails": "non ex in id",
            "instr_CandPersInfo": "nisi",
            "instr_EEOinstructions": "amet labore",
            "instr_EEOlable": "Lorem anim proident",
            "instrubkgrndChkAttachment": "est magna",
            "jobAppGuid": "elit labore ut consectetur fugiat",
            "jobCode": "ea dolore",
            "jobRateOfPay": "dolore labore sit",
            "jobReqId": "amet Ut nostrud consequat est",
            "jobStartDate": "/Date(1492098664000)/",
            "jobofferdate": "/Date(1492098664000)/",
            "knownAs": "culpa eiusmod laboris cupidatat",
            "lastModifiedBy": "laborum velit tempor irure",
            "lastModifiedByProxy": "Lorem incididunt elit",
            "lastModifiedDateTime": "/Date(1492098664000)/",
            "lastName": "et",
            "medDate": "/Date(1492098664000)/",
            "medLoc": "mollit tempor in",
            "medTime": "Lorem irure",
            "middleName": "laboris mollit Duis in dolore",
            "nonApplicantStatus": "fugiat quis exercitation labore",
            "owner": "et",
            "ownershpDate": "/Date(1492098664000)/",
            "phoneScreenDate": "/Date(1492098664000)/",
            "phoneScreenDetails": "aliqua nisi deserunt",
            "pleaseselect": "adipisicing nulla in",
            "posTitle": "dolore in",
            "profileUpdated": "eu aute officia est",
            "psychTestDte": "/Date(1492098664000)/",
            "psychTestTme": "labore Duis et ad",
            "rating": "sit laboris",
            "reasonableaccomodation": "in",
            "reference": "ullamco dolore consequat officia elit",
            "referenceComments": "sunt pariatur ex est",
            "referredBy": "dolore",
            "resumeUploadDate": "/Date(1492098664000)/",
            "screendate": "/Date(1492098664000)/",
            "snapShotDate": "/Date(1492098664000)/",
            "source": "dolor occaecat deserunt",
            "sourceLabel": "cillum dolor",
            "ssn": "elit anim am",
            "startDate": "/Date(1492098664000)/",
            "stateOther": "incididunt cupidatat enim",
            "status": "sit et veniam occaecat ullamco",
            "statusComments": "adipisicing reprehenderit labore cupidatat aliquip",
            "timeToHire": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "title": "proident esse Lorem sit minim",
            "usersSysId": "laborum",
            "visaNum": "dolore sunt",
            "voluntaryselfID": "laborum mollit Duis",
            "whyask": "magna labore nulla aliqui",
            "wotcFormsURL": "do et",
            "wotcId": "consequat magna Duis incididunt",
            "wotcScreeningURL": "proident",
            "wotcStatus": "fugiat c",
            "yesanswer": "ut sit",
            "zip": "Ut aliqua fugiat esse incididunt",
            "jobAppStatus": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "jobApplicationAssessmentOrder": {
                "results": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "jobApplicationAssessmentOrder_1": {
                "results": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "jobApplicationComments": {
                "results": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "jobApplicationOnboardingData": {
                "results": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "jobApplicationQuestionResponse": {
                "results": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "jobApplicationStatusAuditTrail": {
                "results": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            }
        }
    }
}')


@name("Delete entity from JobApplicationQuestionResponse")
DELETE "https://{{baseUrl}}/JobApplicationQuestionResponse(applicationId={{applicationId}},order={{order}})"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")
"If-Match": "esse elit eiusmo"



