#!/usr/bin/env dothttp

@name("List Panels")
POST "https://{{endpoint}}/putxml"
"Content-Type": "text/xml"
"Authorization": "Basic {{credentials}}"
data('<Command>
	<UserInterface>
		<Extensions>
			<List/>
		</Extensions>
	</UserInterface>
</Command>
')


@name("Save Panel")
POST "https://{{endpoint}}/putxml"
"Content-Type": "text/xml"
"Authorization": "Basic {{credentials}}"
data('<Command>
	<UserInterface>
 		<Extensions>
 			<Panel>
	 			<Save>
            	   <PanelId>US</PanelId>
            	   <body>&lt;Extensions&gt;
  &lt;Version&gt;1.6&lt;/Version&gt;
  &lt;Panel&gt;
    &lt;Type&gt;Home&lt;/Type&gt;
    &lt;Icon&gt;Proximity&lt;/Icon&gt;
    &lt;Color&gt;#FFB400&lt;/Color&gt;
    &lt;Name&gt;Ultrasound&lt;/Name&gt;
    &lt;ActivityType&gt;Custom&lt;/ActivityType&gt;
    &lt;Page&gt;
      &lt;Name&gt;Ultrasound&lt;/Name&gt;
      &lt;Row&gt;
        &lt;Name&gt;Volume&lt;/Name&gt;
        &lt;Widget&gt;
          &lt;WidgetId&gt;US_volume_text2&lt;/WidgetId&gt;
          &lt;Name&gt;?&lt;/Name&gt;
          &lt;Type&gt;Text&lt;/Type&gt;
          &lt;Options&gt;size=1;fontSize=normal;align=center&lt;/Options&gt;
        &lt;/Widget&gt;
        &lt;Widget&gt;
          &lt;WidgetId&gt;US_volume_slider2&lt;/WidgetId&gt;
          &lt;Type&gt;Slider&lt;/Type&gt;
          &lt;Options&gt;size=3&lt;/Options&gt;
        &lt;/Widget&gt;
      &lt;/Row&gt;
      &lt;Options/&gt;
    &lt;/Page&gt;
  &lt;/Panel&gt;
&lt;/Extensions&gt;</body>
	 			</Save>	
 			</Panel>
 		</Extensions>
 	</UserInterface>
</Command>


')


@name("Remove All Panels")
POST "https://{{endpoint}}/putxml"
"Content-Type": "text/xml"
"Authorization": "Basic {{credentials}}"
data('<Command>
	<UserInterface>
 		<Extensions>
 			<Clear/>
 		</Extensions>
 	</UserInterface>
</Command>
')



