#!/usr/bin/env dothttp

@name("Creates a new PortalLink")
POST "https://{{baseUrl}}/security/v1/portallink"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "isPublic": [
        "<boolean>"
    ],
    "type": [
        "<integer>"
    ],
    "event": [
        "<string>"
    ],
    "competition": [
        "<string>"
    ],
    "url": [
        "<string>"
    ],
    "expirationDate": [
        "<dateTime>"
    ],
    "code": [
        "<string>"
    ],
    "html": [
        "<string>"
    ],
    "displayOrder": [
        "<integer>"
    ],
    "membersOnly": [
        "<boolean>"
    ],
    "isActive": [
        "<boolean>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isConfiguration": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})


@name("Creates or updates an PortalLink with a specific ID")
PUT "https://{{baseUrl}}/security/v1/portallink/:id"
"Authorization": "<string>"
"Asynchronous": "<boolean>"
"Content-Type": "application/x-www-form-urlencoded"
data({
    "isPublic": [
        "<boolean>"
    ],
    "type": [
        "<integer>"
    ],
    "event": [
        "<string>"
    ],
    "competition": [
        "<string>"
    ],
    "url": [
        "<string>"
    ],
    "expirationDate": [
        "<dateTime>"
    ],
    "code": [
        "<string>"
    ],
    "html": [
        "<string>"
    ],
    "displayOrder": [
        "<integer>"
    ],
    "membersOnly": [
        "<boolean>"
    ],
    "isActive": [
        "<boolean>"
    ],
    "securityLock": [
        "{\"participants\":[{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"},{\"roleID\":\"<string>\",\"accessLevel\":\"<integer>\"}]}"
    ],
    "id": [
        "<string>"
    ],
    "name": [
        "<string>"
    ],
    "keywords": [
        "<string>"
    ],
    "lastModifiedBy": [
        "<string>"
    ],
    "lastModifiedByName": [
        "<string>"
    ],
    "lastModifiedDate": [
        "<dateTime>"
    ],
    "createdDate": [
        "<dateTime>"
    ],
    "createdBy": [
        "<string>"
    ],
    "createdByName": [
        "<string>"
    ],
    "lockedForDeletion": [
        "<boolean>"
    ],
    "isConfiguration": [
        "<boolean>"
    ],
    "isSealed": [
        "<boolean>"
    ],
    "systemTimestamp": [
        "<byte>"
    ],
    "existsInNoSQL": [
        "<boolean>"
    ]
})



