#!/usr/bin/env dothttp

// 
// This endpoint retrieves all users of the company.
// 
// ##### Request Params
// | Name | Value
// --- | --- |
// | **Includes[]** | Array of keys :- **profile**
// 
// #### includes[] Details
// 
// > profile 
// 
// The profile information will be returned by includes in the format below:
// 
// ```json
//   "profile": {
//      "id": 18,
//      "user_id": 25,
//      "phone": null,
//      "additional_phone": null,
//      "address": "123 Nassau Street",
//      "address_line_1": "",
//      "city": "New York",
//      "state_id": 32,
//      "state": "New York",
//      "country_id": 1,
//      "country": "United States",
//      "zip": "10038",
//      "position": "",
//      "profile_pic": null
//  }
// ```
// 
// profile field will have all the information of profile associated with the user. 
// 
// #####  Profile field detail
// 
// * **id**: Unique id   
// * **user_id**: User id associated with profile.
// * **phone**: Phone details of user profile.
// * **additional_phone**:  Additional phones details of user profile.
// * **address**: Street address of the user profile.
// * **address_line_1**:  An optional additional field for the street address
// *  **city**: City of the user profile.
// * **state_id**: State id of the user profile. 
// * **state**: State information of the address 
// * **country_id**: Country id of the user profile.
// * **country**: Country information of the address with all the details.
// *  **zip**:  The postal code (zip, postcode) of the user profile address.
// * **position**: Position of the user.  
// * **profile_pic**: profile picture of the user 
// 
// ##### Request Params (for sorting)
// 
// | Name | Value |
// --- | --- |
// | **sort_by** | Options available: `first_name, email, created_at, group_id`
// | **sort_order** | Options available: `asc, desc`
// 
// > Example `?sort_by=id&sort_order=asc`
// 
// ##### Filters:-
// | Name | Value
// --- | --- |
// | **active** | boolean (0 or 1) 
// | **inactive** | boolean (0 or 1) 
// 
// | **user_id[]** | Array of user ids
// 
// > Example `?inactive=1`
// 
// ##### searching:-
// | Name | Value
// --- | --- |
// | **query** | Search keyword
// 
// > Example `?query=John`

@name("Users")
GET "https://{{baseUrl}}/company/users"
"Authorization": "Bearer {{accessToken}}"



