#!/usr/bin/env dothttp

@name("Materialtypes")
GET "https://{{BaseUrl}}/materialtypes"


@name("Materials")
GET "https://{{BaseUrl}}/materials"


@name("Thickness")
GET "https://{{BaseUrl}}/thicknesses"


@name("Rotations")
GET "https://{{BaseUrl}}/rotations"


@name("Plates")
GET "https://{{BaseUrl}}/plates"


@name("Nestingoptions")
GET "https://{{BaseUrl}}/nestingoption"


@name("Machines")
GET "https://{{BaseUrl}}/machine"
? "filter"= "calculationmachines"


@name("Formats")
GET "https://{{BaseUrl}}/format"


@name("Colors")
GET "https://{{BaseUrl}}/colors"


@name("Errors")
GET "https://{{BaseUrl}}/errors"



