#!/usr/bin/env dothttp

// https://devdocs.transsmart.com/#_single_shipment_retrieval
// 
// Only the shipment data of the corresponding {reference} is returned.
// Make sure to properly urlescape the value of the reference, to avoid interference in case the reference contains special characters.

@name("2.2.1 Single shipment")
GET "https://{{base_url}}/v2/shipments/{{account}}/{{reference}}"


// https://devdocs.transsmart.com/#_multiple_shipments_retrieval
// 
// When the {reference} path parameter is left out, all shipments for the specified account will be returned. To reduce the amount of data in the response the client must use page number {page} and page size {size} as querystring parameters.

@name("2.2.2 Batch of shipments")
GET "https://{{base_url}}/v2/shipments/{{account}}"
? "page"= "1"
? "size"= "5"



