#!/usr/bin/env dothttp

@name("Planetary Eart Assets")
GET "https://api.nasa.gov/planetary/earth/assets"
? "lon"= "100.75"
? "lat"= "1.5"
? "begin"= "{{begin}}"
? "api_key"= "{{api_key}}"


// This endpoint retrieves the Landsat 8 image for the supplied location and date. The response will include the date and URL to the image that is closest to the supplied date. The requested resource may not be available for the exact date in the request. You can retrieve a list of available resources through the assets endpoint. 

@name("Planetary Earth Imagery")
GET "https://api.nasa.gov/planetary/earth/imagery/"
? "lon"= "100.75"
? "lat"= "1.5"
? "date"= "{{date}}"
? "cloud_score"= "True"
? "dim"= "0.025"
? "api_key"= "{{api_key}}"



